### ISSUE TITLE
PHP error when trying to export issue on OJS Testdrive site

### ISSUE THREAD

**Issue by Olegas** [pkp/pkp-lib#10269] opened 2024-08-02 08:09 UTC
**Describe the bug**
Trying to export a non-empty (with non zero items count) issue using Native XML Plugin results in a PHP error

`PKP\user\Repository::get(): Argument #1 ($id) must be of type int, null given, called in /var/www/html/lib/pkp/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.php on line 93
`

Export file is not generated.

**To Reproduce**
1. Go to https://ojs34.testdrive.publicknowledgeproject.org/index.php/testdrive-journal/management/importexport/plugin/NativeImportExportPlugin
2. Login with admin/testdrive
3. Click on "Export Issues"
4. Select any issue with non zero (!) items count with checkbox
5. Press "Export issues" button

**What application are you using?**
 OJS 3.4 (Testdrive)

**Additional information**
![Снимок экрана 2024-08-02 в 11 07 01](https://github.com/user-attachments/assets/331d30a8-8e8f-4440-846b-059b92533fd9)

**Comment by jonasraoni** [comment] 2024-08-02 08:35
Thanks for the report @Olegas! Closing as a duplicate of https://github.com/pkp/pkp-lib/issues/9414

**Closed by jonasraoni** 2024-08-02 08:35 UTC

**Comment by jonasraoni** [comment] 2024-08-02 09:12
FYI this should be fixed on the next release, I've uploaded a small fix, the related issue has some extra discussions, so maybe it will be slower to be closed.
