### ISSUE TITLE
Call to getAssocId() on null value

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#7644] opened 2022-01-24 12:13 UTC
**Describe the bug**
When viewing the Activity Log of an article it never finishes "Loading".

**To Reproduce**
Not sure if som information is missing (or how to find what is missing), but the stack trace complains about null value (see below).

**What application are you using?**
 OJS 3.3.0-8

**Additional information**

```
PHP Fatal error:  Uncaught Error: Call to a member function getAssocId() on null in /usr/home/luizborges/www/public_html/lib/pkp/classes/services/PKPSubmissionFileService.inc.php:774
Stack trace:
#0 /usr/home/luizborges/www/public_html/lib/pkp/controllers/grid/eventLog/EventLogGridRow.inc.php(79): PKP\\Services\\PKPSubmissionFileService->getWorkflowStageId(Object(SubmissionFile))
#1 /usr/home/luizborges/www/public_html/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1066): EventLogGridRow->initialize(Object(Request))
#2 /usr/home/luizborges/www/public_html/lib/pkp/classes/controllers/grid/GridHandler.inc.php(983): GridHandler->_getInitializedRowInstance(Object(Request), 22, Object(SubmissionEventLogEntry))
#3 /usr/home/luizborges/www/public_html/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1031): GridHandler->renderRowsInternally(Object(Request), Array)
#4 /usr/home/luizborges/www/public_html/lib/pkp/classes/controllers/grid/GridHandler.inc.php(921): GridHandler->renderGridBodyPartsInternally(Object(Request))
#5 /us in /usr/home/luizborges/www/public_html/lib/pkp/classes/services/PKPSubmissionFileService.inc.php on line 774, referer: https://periodicos.fclar.unesp.br/alfa/workflow/index/14270/4

```
![image](https://user-images.githubusercontent.com/18707781/150781000-0f16ebf1-f185-4165-ba17-aab3fdfb794c.png)

EDIT:
I changed line 775 on `lib/pkp/classes/services/PKPSubmissionFileService.inc.php` to:
`$query = $note ? $queryDao->getById($note->getAssocId()) : null;`

Could that create any side effect?

**Comment by NateWr** [comment] 2022-01-24 12:54
Hi @luizbgomide, this is a duplicate of https://github.com/pkp/pkp-lib/issues/7453, which was fixed and merged in. The fix will go out with the next maintenance release (3.3.0-9).

**Closed by NateWr** 2022-01-24 12:54 UTC
