### ISSUE TITLE
request for a feature Allow authors to withdraw their articles if the journal is unable to fulfill its publication promise

### ISSUE THREAD

**Issue by promedacademy** [pkp/pkp-lib#6818] opened 2021-03-03 20:02 UTC
**Describe the problem you would like to solve**
Example: Our authors need a way to [ withdraw their articles if the journal is unable to fulfill its publication promise or any inconvenience happened]

**Describe the solution you'd like**
Tell us how you would like this solution to be solved.
Add "withdraw" link in the submission  menu beside each submitted article that open a customizable form fields for why the  author want to withdraw the article or any other fields to be filled, this form should be notified to the editorial team to take a decision either to accept or deny withdrawal request or further discussion with the author. If accepted all records and files  related to this submission to be archived or deleted  and all participants (authors, editors , section editors, and reviewers are notified 
**Who is asking for this feature?**
Authors mainly and all editorial team 

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by asmecher** [comment] 2021-03-03 20:11
This is a duplicate of https://github.com/pkp/pkp-lib/issues/1813; please review the discussion there and add anything you think is helpful.

**Closed by asmecher** 2021-03-03 20:11 UTC
