### ISSUE TITLE
[OJS] Problem with downloading the new locale.

### ISSUE THREAD

**Issue by mariuszsienkiewicz** [pkp/pkp-lib#6239] opened 2020-09-15 11:02 UTC
**OJS**: 3.2.1.0
The problem occurs when I'm trying to install the Romanian Language.

Error Log: lib/pkp/classes/file/wrappers/HTTPFileWrapper.inc.php:120 Could not connect to pkp.sfu.ca (404; 5) 
And I found constant LANGUAGE_PACK_DESCRIPTOR_URL and it contains: 'http://pkp.sfu.ca/ojs/xml/%s/locales.xml'
http://pkp.sfu.ca/ojs/xml/3.2.1.0/locales.xml - gives us 404 error code.

Apart from the obvious problem with the missing file on the http://pkp.sfu.ca/ website, there is another one, despite the fact that the new language could not be downloaded, the system reports a successful operation with the information "All selected locale(s) installed and activated." but the language does not appear on the page or in the files.

I believe that the user should be notified in some way about the error without looking at the error log.

**Comment by NateWr** [comment] 2020-09-16 09:02
Hi @mariuszsienkiewicz, thanks for the report. It looks like this code has changed significantly between 3.2.1.0 and our latest `master` branch.

**Comment by asmecher** [comment] 2020-09-21 15:37
@mariuszsienkiewicz, OJS has always had a feature that permitted users to install language packs from the PKP website, but we've never used it; instead, we've shipped all locale files with the software. So yes, the `LANGUAGE_PACK_DESCRIPTOR_URL` will result in a 404, but it's always been that way (and it's not the way users have installed languages). The warning and 404 have already been corrected in the `master` branch through the removal of that feature.

Are you needing to install more up-to-date versions of the Romanian locale files than you currently have in your 3.2.1 installation? Or are you trying to enable the language as it's currently shipped with 3.2.1?

**Comment by mariuszsienkiewicz** [comment] 2020-09-22 08:31
Hi @asmecher, thank you for the information. I didn't know about it.

I wanted to enable the language, it is present on the language list but I do not have the ro_RO folder inside `locale` and `lib/pkp/locale` folder because 3.2.1.0 and 3.2.1.1 versions are not shipped with that language as far as I can see. This confused me and that is why I thought the language, in this case, will be downloaded from the pkp.sfu.ca website but you already explained it to me.

**Comment by NateWr** [comment] 2020-09-22 11:21
I'm going to close this issue since it's not a bug. But it looks like we do have fairly complete translations for Romanian (see the status for [ojs](https://translate.pkp.sfu.ca/languages/ro_RO/ojs/) and [pkp-lib](https://translate.pkp.sfu.ca/languages/ro_RO/pkp-lib/)).

I'm not sure why the language isn't present for you but it may be possible to simply download the release package for your version and copy the files over.

**Closed by NateWr** 2020-09-22 11:21 UTC

**Comment by asmecher** [comment] 2020-09-22 15:07
@mariuszsienkiewicz, if you're interested in installing new content that's in Weblate (https://translate.pkp.sfu.ca) but not yet released, see these instructions: https://forum.pkp.sfu.ca/t/new-locale-support-installed-manually-on-omp/61843
