### ISSUE TITLE
If you create a new role with JM permissions, they are automatically assigned to all new submissions

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#7103] opened 2021-06-04 19:10 UTC
**Describe the bug**
This was reported by a PKP PS hosted client on OJS 3.2.1. I tested it on 3.2.0 and 3.3 and found the same thing. The user created a new role with the permission level of Journal Manager. All new submissions made to the journal are now assigned to the user in that role. It happens when there are multiple users in the Journal Editor and Section Editor role. It happens when there is no section editor assigned to the section. If there is a section editor assigned, the submission will be assigned to the user in the new role and to the section editor.

**To Reproduce**
1. Create new role with JM permission
2. Assign a user to the new role
3. Log in as an author and make a new submission
4. Log out as the author and check the submission list. You will see the submission under All Active with the user in the new role assigned.

**What application are you using?**
OJS 3.2.0, 3.2.1, and 3.3

**Comment by NateWr** [comment] 2021-06-07 10:49
@asmecher it looks like this is intentional, when there is only one user in a JM user group. But it also looks like this goes back to the OJS 3 beta (and maybe earlier):

https://github.com/pkp/pkp-lib/blame/b2b45d77413f62d091714aa0c48521c8dbe1ee1c/classes/submission/form/PKPSubmissionSubmitStep4Form.inc.php#L54

It looks like this was functionality applied to assistant roles that was later adapted to JM roles:

https://github.com/pkp/pkp-lib/commit/f4326ad96974ea33a852e8fd72382d41f3c1f438#diff-bec9507729c3b47633890185f73161de9c2df738d6e132246aed325d07d47d10R53

I'm not sure I have a recommendation here for what a good default behaviour should be. It doesn't seem very intuitive, but it seems like changing this either way will impact existing workflows that rely on it. I think to address it we probably need configuration options...

**Comment by NateWr** [comment] 2021-06-09 08:47
> I'd be in favour of making this configurable, especially if it means unifying the section editor auto-assignment with other roles, but I'm not sure we know the "best" place to configure these -- e.g. are other kinds of users assigned depending on the submission's section, or are they journal-wide?

At the risk of blowing this up into something bigger than it needs to be: one of the things I'd like to see is the ability to configure automatic assignments during the editorial workflow. It would be nice if journals could configure, for example, that a Layout Editor is automatically assigned when a submission reaches the Production stage. This would help automate the hand-off, especially to managers/assistants who often need to intervene at some step of the process.

**Comment by asmecher** [comment] 2024-01-18 18:32
The automatic assignment behaviour has been removed starting with 3.4.0, in favour of the ability to designate automatic assignments for more types of roles in section and category settings. (Duplicate of pkp/pkp-lib#7191.)

**Closed by asmecher** 2024-01-18 18:32 UTC
Labels: Hosting
