### ISSUE TITLE
user name and task name not showing in dashboard

### ISSUE THREAD

**Issue by me-kell** [pkp/pkp-lib#8003] opened 2022-06-15 08:15 UTC
**Describe the bug**
user name and task name not showing in dashboard

**To Reproduce**
1. Log in
2. See upper right corner at `header div.app__headerActions div.app__userNav` and `header div.app__headerActions div.app__tasks`

**What application are you using?**
 OJS version 3.3.0-8

**Additional information**
The cause seems to be following css-style in `styles/build.css`

```
.-screenReader {
  clip: rect(1px,1px,1px,1px);
  position: absolute !important; // <---
  left: -2000px;
}
```
My workaround is

```
div.pkpDropdown.app__headerAction.app__userNav button.pkpButton span.-screenReader {
    position: unset !important;
}

div.app__headerActions div.app__headerAction.app__tasks button span.-screenReader {
    position: unset !important;
}
```

**Comment by NateWr** [comment] 2022-06-23 12:25
I believe this is the intended behaviour. I'm going to close this issue for now. If you think I've made a mistake, please provide some screenshots showing before/after to help us evaluate whether this information should be visible or not.

**Closed by NateWr** 2022-06-23 12:25 UTC

**Comment by me-kell** [comment] 2022-06-23 13:36
See the following screenshots:

1. Dashboard logged in as admin
2. Dashboard logged in as admin and anotheruser
3. Journal logged in as admin
4. Journal logged in as admin and anotheruser

![grafik](https://user-images.githubusercontent.com/2512653/175311963-32b2c968-7c97-47e6-a514-095aecf47e14.png)

**Comment by NateWr** [comment] 2022-06-23 13:47
I see. No, we don't have any plans to change this. I'd recommend posting in the [feature requests](https://forum.pkp.sfu.ca/c/questions/feature-requests/8) category of our community forum. You'll have an opportunity to discuss with other users to see if they agree with you.

**Comment by me-kell** [comment] 2022-06-23 14:11
Thank you.

Do you know where the screenshot in the documentation comes from? Which version? Why is the username shown there?

**Comment by NateWr** [comment] 2022-06-23 15:00
That would be version OJS 3.2.x or less. It was changed in 3.3

**Comment by me-kell** [comment] 2022-06-23 15:08
Does this mean that this feature was in OJS 3.2.x and it disappeared in OJS 3.3.x?
I'll check this in a fresh OJS 3.2.1-4 installation.

**Comment by me-kell** [comment] 2022-09-15 18:52
> I see. No, we don't have any plans to change this. I'd recommend posting in the [feature requests](https://forum.pkp.sfu.ca/c/questions/feature-requests/8) category of our community forum. You'll have an opportunity to discuss with other users to see if they agree with you.

IMHO this should not need a feature request since this is a feature that already existed and apparently disappeared.

The username is though brought to the html/css code but wrongly shown with `left: -2000px` (see my comments above).
When the user is logged as another user both the "parent" username and the current username are shown.
See detailed comments/explanations under (https://forum.pkp.sfu.ca/t/username-not-showing-in-dashboard/73754/2). Specially at (https://forum.pkp.sfu.ca/t/username-not-showing-in-dashboard/73754/3?u=me-kell)

**Comment by nmueller18** [comment] 2022-09-15 20:22
I very much second this request for showing the username in the dashboard as was the case in OJS 3.2. As site and journal manager with several identities of different granularity of access rights, it is very annoying that I cannot see with one glance which identity I am currently using but only find out when I am not allowed to do certain things.

**Comment by me-kell** [comment] 2022-09-16 10:37
I really cannot understand why not to show the username. Please reopen this issue.

For those like me want to see the username showing in the dashboard (this is a copy of https://forum.pkp.sfu.ca/t/username-not-showing-in-dashboard/73754/8):

Some Browsers, e.g. Firefox allow to locally override the css (for one site or for all sites). See for instance [How can I override the CSS of a site in Firefox with userContent.css?](https://superuser.com/a/319322) There is also a similar way for Chrome which I haven't tested yet [see here](https://superuser.com/a/638257).

**For Firefox**

1. Create a directory `chrome` in your firefox profile directory (in Windows usually `C:\Users\username\AppData\Roaming\Mozilla\Firefox\Profiles\#####`).

2. Create a file `userContent.css` in the new created `chrome` directory with following content (don't forget to replace "www.example.org" with your domain!):

```css
@-moz-document domain(www.example.org) {
    div.pkpDropdown.app__headerAction.app__userNav button.pkpButton span.-screenReader {
        position: unset !important;
    }
}
```
3. In Firefox visit `about:config` and change the setting `toolkit.legacyUserProfileCustomizations.stylesheets` to `true`

4. Restart Firefox, visit your OJS-URL and ... voilà

![username|216x146](upload://ox2Ftx0Ab7UjftsKLDIttISjBEu.png)

**If you have access to the OJS system.**

Simply add the following css-snippet to `styles/build.css` under your ojs folder (usually `/var/www/ojs`):

```css
    div.pkpDropdown.app__headerAction.app__userNav button.pkpButton span.-screenReader {
        position: unset !important;
    }
```

e.g. with:

```
$ echo "div.pkpDropdown.app__headerAction.app__userNav button.pkpButton span.-screenReader { position: unset "'!'"important;}" | sudo tee -a styles/build.css
```
