### ISSUE TITLE
Metadata tab disappears  

### ISSUE THREAD

**Issue by alexdryden** [pkp/pkp-lib#7550] opened 2021-12-15 17:57 UTC
**Describe the bug**
When adding a publication format to OMP, the metadata tab does not initially appear:
<img width="1437" alt="Screen Shot 2021-12-15 at 11 44 38 AM" src="https://user-images.githubusercontent.com/47127862/146228212-b80773d0-f0f5-4158-acf0-02cc82fc5ea6.png">

Then, it does appear when editing the publication format:
<img width="1429" alt="Screen Shot 2021-12-15 at 12 49 58 PM" src="https://user-images.githubusercontent.com/47127862/146238942-64987af7-58de-4a6d-8ba7-6e40030241db.png">

But disappears if the box " This format will be available at a separate website " is checked:
<img width="1431" alt="Screen Shot 2021-12-15 at 12 50 46 PM" src="https://user-images.githubusercontent.com/47127862/146239030-3811142f-c21c-40b2-872b-ed08606cc9ff.png">

**To Reproduce**
1. In OPM, go to a book in the production stage (or unpublish a published book)
2. Click on Publication format and Add Publication format
3. Confirm that Metadata tab does not appear
4. Enter a name under format details and leave the publication format as a "Digital (DA)"
5. Hit save
6. Click edit on the publication format you just created
7. Confirm that the metadata tab now appears.
8. Check the box " This format will be available at a separate website "  and enter a website
9. Click save
10. Click edit again and confirm that the metadata tab no longer appears. 

**What application are you using?**
OMP 3.3.0-3 (seeing the same behavior in 3.2.1-1)

**Comment by NateWr** [comment] 2021-12-16 11:00
I believe this is as intended. If I recall correctly, remote galleys and publication formats do not have "metadata". @withanage do you know if this is the case?

**Comment by alexdryden** [comment] 2021-12-16 21:35
Hmm. Maybe our use case is atypical, we primarily use OMP as a catalog and discovery service for a digital press. Is there a reason why remote galleys or formats shouldn't have metadata? I.e., are we going to run into any issues down the road because we are publishing remote publications with metadata (using a workaround)?

**Comment by withanage** [comment] 2021-12-16 22:35
@alexdryden 

As @NateWr  mentioned I  think in older versions  we.g.  3.2.1-1  or 3.2.1  as I  remember this was not available and was intended.

But I have tested in OMP 3.3.0-8 and  and  I can confirm  the workflow you  described is working.


Could you run a update and let us know, if  this is not the case for you ?

https://user-images.githubusercontent.com/1921992/146458936-4d3581d4-860d-47a1-ad69-ad878be6ff33.mp4

**Comment by NateWr** [comment] 2021-12-20 10:03
Closing this as fixed in 3.3.0-8 but feel free to post if you're able to reproduce in 3.3.0-8.

**Closed by NateWr** 2021-12-20 10:03 UTC
