### ISSUE TITLE
Consider Setup 1 fields to be multilingual

### ISSUE THREAD

**Issue by nerijus** [pkp/pkp-lib#2535] opened 2017-05-17 16:22 UTC
OJS version 2.4.8-2.

I select another language in the "Form Language" dropbox, press Submit, then enter the info in another language for:
1.1 General Information
1.2 Principal Contact
etc
and press "Save and continue". But the info is changed for English as well. Then if I change the info for the Form Language: English, another language info (entered in the previous step) is overwritten in English. So I cannot have Journal Setup->Details in different languages.

**Comment by bozana** [comment] 2017-05-18 09:44
@nerijus, not all fields/information are meant to be multilingual. The two you have mention (Setup 1.1. and 1.2), for example, are the same for every language, thus, changing the form language and then the entries would just save them, as you have noticed. 
On the other side, some fields are multilingual, for example Setup 2.1, and there you can change the form language in order to enter those different multilingual values/entries.
Thus, this is not the bug and I will close the issue.
Also, please consider first using the forum (https://github.com/pkp/ojs/pull/1385) instead of GitHub Issue, if you are not sure that it is a general bug/issue.

**Comment by nerijus** [comment] 2017-05-24 08:01
No, Setup 1.1 is not the same. For example, in Lithuanian it is:

Lietuvos mokslų akademijos Leidybos skyrius
Gedimino pr. 3, LT-01103  Vilnius

In English:

Lithuanian Academy of Sciences Publishers
3 Gedimino Ave, 01103 Vilnius, Lithuania

In non Latin based languages (Chinese, Russian, Arabic, etc) it will definitely be not the same.
So it is a bug, could you please reopen it?

**Comment by bozana** [comment] 2017-05-24 08:47
@nerijus, this is not a bug, maybe a feature/change request: Once a decision was made what input fields should be multilingual in the system. For some users/use cases this might not be enough. If you think that some other input fields should be multilingual as well, could you please describe it so (not as a bug but as a feature wish/need) and in more detail i.e. what other fields would you like/need to be multilingual and explanation/reason why (like you did in the last comment)?

**Comment by nerijus** [comment] 2017-05-24 10:05
Yes, it's a feature request, sorry. Is there some list of the fields, which are multilingual?

**Comment by asmecher** [comment] 2017-05-24 17:34
The multilingual fields are listed here: https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/manager/form/setup/JournalSetupStep1Form.inc.php#L74

**Comment by nerijus** [comment] 2017-06-08 11:48
I changed JournalSetupStep1Form.inc.php like this:
```
--- /home/backup/www/html/ojs/classes/manager/form/setup/JournalSetupStep1Form.inc.php	2017-03-15 22:01:03.000000000 +0200
+++ /var/www/html/ojs/classes/manager/form/setup/JournalSetupStep1Form.inc.php	2017-06-01 16:19:44.763992572 +0300
@@ -71,7 +71,7 @@
 	 * @return array
 	 */
 	function getLocaleFieldNames() {
-		return array('title', 'initials', 'abbreviation', 'contactTitle', 'contactAffiliation', 'contactMailingAddress', 'sponsorNote', 'publisherNote', 'contributorNote', 'history', 'searchDescription', 'searchKeywords', 'customHeaders');
+		return array('title', 'initials', 'abbreviation', 'mailingAddress', 'contactName', 'contactTitle', 'contactAffiliation', 'contactMailingAddress', 'sponsorNote', 'publisherNote', 'contributorNote', 'history', 'searchDescription', 'searchKeywords', 'customHeaders');
 	}
 
 	/**
```

But now my changes in 1.1 General Information->Mailing Address are silently discarded (in any language).

**Comment by bozana** [comment] 2017-06-08 13:36
@nerijus, yes, you would need to do further changes as well, for example:
-- to remove it from here: https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/manager/form/setup/JournalSetupStep1Form.inc.php#L31
-- to change the form variable to be an array, like all the other multilingual fields, here: https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/templates/manager/setup/step1.tpl#L59-L66
-- to change every call of that setting, because it changed from a string to an array, for example here: https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/templates/about/contact.tpl#L16-L21

This also means that you will have to consider that change at each upgrade...

**Comment by nerijus** [comment] 2017-10-25 19:11
-- to remove it from here: https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/classes/manager/form/setup/JournalSetupStep1Form.inc.php#L31

I am not sure I need to remove mailingAddress from here, as contactMailingAddress is translated, and it is present here.

**Comment by nerijus** [comment] 2017-10-25 19:28
Now my diff is this:
```
diff -ur -x cache ojs.orig/classes/manager/form/setup/JournalSetupStep1Form.inc.php ojs/classes/manager/form/setup/JournalSetupStep1Form.inc.php
--- ojs.orig/classes/manager/form/setup/JournalSetupStep1Form.inc.php	2017-03-15 22:01:03.000000000 +0200
+++ ojs/classes/manager/form/setup/JournalSetupStep1Form.inc.php	2017-10-25 22:16:01.008546689 +0300
@@ -71,7 +71,7 @@
 	 * @return array
 	 */
 	function getLocaleFieldNames() {
-		return array('title', 'initials', 'abbreviation', 'contactTitle', 'contactAffiliation', 'contactMailingAddress', 'sponsorNote', 'publisherNote', 'contributorNote', 'history', 'searchDescription', 'searchKeywords', 'customHeaders');
+		return array('title', 'initials', 'abbreviation', 'mailingAddress', 'contactTitle', 'contactAffiliation', 'contactMailingAddress', 'sponsorNote', 'publisherNote', 'contributorNote', 'history', 'searchDescription', 'searchKeywords', 'customHeaders');
 	}
 
 	/**
diff -ur -x cache ojs.orig/templates/about/contact.tpl ojs/templates/about/contact.tpl
--- ojs.orig/templates/about/contact.tpl	2017-03-15 22:01:03.000000000 +0200
+++ ojs/templates/about/contact.tpl	2017-10-25 21:54:38.378870108 +0300
@@ -13,11 +13,11 @@
 {include file="common/header.tpl"}
 {/strip}
 <div id="contact">
-{if !empty($journalSettings.mailingAddress)}
+{if ($currentJournal->getLocalizedSetting('mailingAddress'))}
 <div id="mailingAddress">
 <h3>{translate key="common.mailingAddress"}</h3>
 <p>
-	{$journalSettings.mailingAddress|nl2br}
+	{$currentJournal->getLocalizedSetting('mailingAddress')|nl2br}
 </p>
 </div>
 {/if}
diff -ur -x cache ojs.orig/templates/manager/setup/step1.tpl ojs/templates/manager/setup/step1.tpl
--- ojs.orig/templates/manager/setup/step1.tpl	2017-03-15 22:01:03.000000000 +0200
+++ ojs/templates/manager/setup/step1.tpl	2017-10-25 21:36:04.754580874 +0300
@@ -59,7 +59,7 @@
 	<tr valign="top">
 		<td width="20%" class="label">{fieldLabel name="mailingAddress" key="common.mailingAddress"}</td>
 		<td width="80%" class="value">
-			<textarea name="mailingAddress" id="mailingAddress" rows="3" cols="40" class="textArea">{$mailingAddress|escape}</textarea>
+			<textarea name="mailingAddress[{$formLocale|escape}]" id="mailingAddress" rows="3" cols="40" class="textArea">{$mailingAddress[$formLocale]|escape}</textarea>
 			<br />
 			<span class="instruct">{translate key="manager.setup.mailingAddressDescription"}</span>
 		</td>
```
But the info entered in any language in 1.1 General Information->Mailing Address is not saved. What else is missing?

**Closed** 2021-11-17 12:12 UTC
