### ISSUE TITLE
OJS 3.0b: Journal Appearance, image management/deletion

### ISSUE THREAD

**Issue by mxbees** [pkp/pkp-lib#868] opened 2015-11-04 19:18 UTC
In playing around with the various appearance options I'm encountering UI issues around the image management.

When you delete an image, it doesn't disappear from the UI. If you hit 'save' and get the notification that your changes have been saved, the image is still there. Then, if you try to delete it again (as in, you think it is still there because it didn't go anywhere). You'll get the confirmation page but you can't click 'ok' because it actually _is_ deleted.

It's confusing. The only way the image actually disappears from the UI is if you refresh the page, only then do you know that you successfully removed the image. This happens with:
- Homepage mage
- Journal Thumbnail
- Title image

Sometimes, though, you have the opposite. When uploading a 'title image' it won't show up on the page until you do a refresh. However, other images appear on the page after saving your image.
- homepage image
- journal thumbnail
- title image
- journal logo

After playing a bit more, I think the problem is that this behaviour is unpredictable because sometimes the image will show up or delete but not others. Either way, its confusing.

**Comment by asmecher** [comment] 2015-11-05 19:30
Thanks, @nmpx. @NateWr, I suspect there's overlap here with existing entries; could you review and combine as needed?

**Comment by NateWr** [comment] 2015-11-09 16:47
I wasn't able to replicate this with latest master of OJS. Just to be clear, here are the steps I took to reproduce:

1. Login as Journal Manager (`dbarnes`)
2. Go to Settings > Website > Appearance.
3. Click the **Upload** link under Journal Thumbnail. The file upload modal appeared.
4. Click Add Files. Select a file. Click Start Upload. Click Ok. The image appeared under Journal Thumbnail.
5. Clicked the Delete link. A confirmation modal pops up. Click Ok. The image disappears.

Are you taking different steps when you have the problem @nmpx? If so let me know exactly what you're doing as that will help me reproduce the problem,.

**Comment by nmpx** [comment] 2015-11-18 18:00
Hey. I followed your directions exactly and had the same problem. This is also a fresh install of the git master dev branch (installed today). The rest of my environment:

- Debian 8
- PHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10)
- mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.3
- Server version: Apache/2.4.10 (Debian)

I made a screencast of what I did and how it looks for me. See the link below. 

https://youtu.be/DIKxaJSwqhk

**Comment by nmpx** [comment] 2015-11-19 15:38
Ok. I finally have the PHP error logs for the above:

````
[Thu Nov 19 10:34:54.651953 2015] [:error] [pid 1828] [client 10.0.2.2:43175] PHP Warning:  key_exists() expects parameter 2 to be array, null given in /var/www/html/lib/pkp/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php on line 181, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:34:54.652002 2015] [:error] [pid 1828] [client 10.0.2.2:43175] PHP Warning:  unlink(public/journals/2/): Is a directory in /var/www/html/lib/pkp/classes/file/FileManager.inc.php on line 294, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:34:55.107017 2015] [:error] [pid 1828] [client 10.0.2.2:43175] PHP Warning:  key_exists() expects parameter 2 to be array, null given in /var/www/html/lib/pkp/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php on line 181, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:34:55.107062 2015] [:error] [pid 1828] [client 10.0.2.2:43175] PHP Warning:  unlink(public/journals/2/): Is a directory in /var/www/html/lib/pkp/classes/file/FileManager.inc.php on line 294, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:34:55.508333 2015] [:error] [pid 1828] [client 10.0.2.2:43175] PHP Warning:  key_exists() expects parameter 2 to be array, null given in /var/www/html/lib/pkp/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php on line 181, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:34:55.508371 2015] [:error] [pid 1828] [client 10.0.2.2:43175] PHP Warning:  unlink(public/journals/2/): Is a directory in /var/www/html/lib/pkp/classes/file/FileManager.inc.php on line 294, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:34:55.825231 2015] [:error] [pid 1828] [client 10.0.2.2:43175] PHP Warning:  key_exists() expects parameter 2 to be array, null given in /var/www/html/lib/pkp/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php on line 181, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:34:55.825290 2015] [:error] [pid 1828] [client 10.0.2.2:43175] PHP Warning:  unlink(public/journals/2/): Is a directory in /var/www/html/lib/pkp/classes/file/FileManager.inc.php on line 294, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:35:12.054743 2015] [:error] [pid 2352] [client 10.0.2.2:43178] PHP Warning:  key_exists() expects parameter 2 to be array, null given in /var/www/html/lib/pkp/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php on line 181, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:35:12.054786 2015] [:error] [pid 2352] [client 10.0.2.2:43178] PHP Warning:  unlink(public/journals/2/): Is a directory in /var/www/html/lib/pkp/classes/file/FileManager.inc.php on line 294, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:35:12.333061 2015] [:error] [pid 2352] [client 10.0.2.2:43178] PHP Warning:  key_exists() expects parameter 2 to be array, null given in /var/www/html/lib/pkp/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php on line 181, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:35:12.333121 2015] [:error] [pid 2352] [client 10.0.2.2:43178] PHP Warning:  unlink(public/journals/2/): Is a directory in /var/www/html/lib/pkp/classes/file/FileManager.inc.php on line 294, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:35:12.611472 2015] [:error] [pid 2352] [client 10.0.2.2:43178] PHP Warning:  key_exists() expects parameter 2 to be array, null given in /var/www/html/lib/pkp/controllers/tab/settings/appearance/form/PKPAppearanceForm.inc.php on line 181, referer: http://localhost:8080/index.php/test2/management/settings/website
[Thu Nov 19 10:35:12.611525 2015] [:error] [pid 2352] [client 10.0.2.2:43178] PHP Warning:  unlink(public/journals/2/): Is a directory in /var/www/html/lib/pkp/classes/file/FileManager.inc.php on line 294, referer: http://localhost:8080/index.php/test2/management/settings/website
````

**Comment by asmecher** [comment] 2019-04-16 23:38
Closing as out of date -- the setup forms have been overhauled since this was filed.

**Closed by asmecher** 2019-04-16 23:38 UTC
