### ISSUE TITLE
XML import fails with error: Submission file added to review round that does not exist

### ISSUE THREAD

**Issue by Ge2C** [pkp/pkp-lib#8137] opened 2022-08-07 14:23 UTC
**What application are you using?**
 OJS v3.3.0.11 booh export and inport
 
**Describe the bug**
Native XML Import/export Failed, Error occur at importing issue, when clicking import button

**To Reproduce**
1. Export Native XML Issue
2. Open Tools > Native XML Plugin
3. Click Upload FIle Select file and wailting until uploaded
4. Click Import
5. Show blank result, check dev tool see code 500 

**Additional information**
Example export file that can produce the bug: [example-article-import.xml.txt](https://github.com/pkp/pkp-lib/files/9281700/example-article-import.xml.txt) Rename to `.xml` before using.

**XHR and fetch show 500**
link [journal_url]/management/importexport/plugin/NativeImportExportPlugin/import?temporaryFileId=100&csrfToken=bb79838ada1b733c8643dd98c58f6473&_=1659881201929See

**Check Log**
[07-Aug-2022 20:50:10 Asia/Jakarta] PHP Fatal error: Uncaught Exception: Submission file added to review round that does not exist. in /home/public_html/lib/pkp/classes/services/PKPSubmissionFileService.inc.php:348
Stack trace:
#0 /home/public_html/lib/pkp/plugins/importexport/native/filter/NativeXmlSubmissionFileFilter.inc.php(207): PKP\Services\PKPSubmissionFileService->add(Object(SubmissionFile), Object(Request))
#1 /home/public_html/lib/pkp/plugins/importexport/native/filter/NativeImportFilter.inc.php(60): NativeXmlSubmissionFileFilter->handleElement(Object(DOMElement))
#2 /home/public_html/lib/pkp/classes/filter/Filter.inc.php(449): NativeImportFilter->process(Object(DOMDocument))
#3 /home/public_html/lib/pkp/plugins/importexport/native/filter/NativeXmlSubmissionFilter.inc.php(169): Filter->execute(Object(DOMDocument))
#4 /home/public_html/lib/pkp/plugins/importexport/native/filter/NativeXmlSubmissionFilter.inc.php(127): NativeXmlSubmissionFilter->parseSubmissio in /home/public_html/lib/pkp/classes/services/PKPSubmissionFileService.inc.php on line 348

---
**PRs**

**Branch `stable-3_3_0`**
[OJS]: #pkp/ojs/pull/3515 (TESTS ONLY)
[pkp-lib]: #8211

**Branch `main`**
[OJS]: #pkp/ojs/pull/3516 (TESTS ONLY)
[pkp-lib]: #8212

**Comment by NateWr** [comment] 2022-08-08 11:07
Thanks for your bug report @Ge2C, with the reproduction steps and error message. This error will be related to your specific data set, so we won't be able to reproduce it with our datasets.

Can you attach the `.xml` file that is produced after step 1? You can anonymize the text data within it, for example by changing the names of submissions, authors and files.

**Comment by Ge2C** [comment] 2022-08-08 12:00
Thank for the response @NateWr, this is the sample file that I try to import, it export an article that I take from my journal, you can download it from [here](https://gtwo.my.id/native-20220808-181748-articles-1.xml), it't not an entire issue like I reported but it results in the same error message, but if you need entire issue just tell me.

**Comment by NateWr** [comment] 2022-08-08 12:32
Thanks @Ge2C. I've confirmed the bug and updated the issue with the appropriate labels/milestones. Someone else will investigate when we have the time.

**Comment by asmecher** [comment] 2022-08-11 23:58
@defstat, could you take a look at this one?

**Comment by defstat** [comment] 2022-08-26 10:18
@Ge2C thanks for reporting that.

The problem in your case seems to be that the export process did not exclude all the REVIEW specific submission files, even though the review rounds are not currently exported by the Native Import/Export plugin.

In the [top ](https://github.com/pkp/pkp-lib/issues/8137#issue-1331031565) comment of the current issue, we have added one [PR ](https://github.com/pkp/pkp-lib/pull/8211) that may solve your problem. Could you apply this change on your installation (preferably on a dev environment) to see if it solves the issue. 

Just a note: you have to export your data again in order to see if the import succeeds after the change.

**Comment by Ge2C** [comment] 2022-08-28 11:10
Thanks for the fix @defstat,

I apply the change based on PR in my OJS installation and try to export/import again, it works like charm and run without error, but the entire REVIEW process is gone. Was the review round not included in the export are intentional? Wouldn't that defeat the purpose of import/export, I mean review progress is required for full article publication?

**Comment by defstat** [comment] 2022-08-28 16:01
@Ge2C Thanks for confirming, you have been most helpful.

Yes, the review process is supposed to be gone after the native import/export process, as it, currently at least, does not export the review rounds. 

@asmecher the PRs are in the top issue comment for both `stable-3_3_0` and `main` branches for review.

**Comment by asmecher** [comment] 2022-08-29 23:38
Thanks, @Ge2C and @defstat -- much appreciated! All merged.

**Closed by asmecher** 2022-08-29 23:38 UTC
Labels: Bug:1:Low
