### ISSUE TITLE
File uploader not working on OJS 3

### ISSUE THREAD

**Issue by mouseonthemoon** [pkp/pkp-lib#1797] opened 2016-09-03 14:12 UTC
Can't upload a logo in the OJS settings wizard, not in google Chrome neither in Firefox

"The system file uploader is loading. If it doesn't appear it is likely that none of its runtimes is supported by this browser. Please, contact administration for support. "

**Comment by asmecher** [comment] 2016-09-03 16:45
@mouseonthemoon, this may be because of a Javascript error elsewhere in the system, which causes Javascript to stop executing before the uploader is initialized. I'd suggest checking your Javascript console, either by using built-in browser tools, or using something like Firebug for Firefox.

**Comment by ancht** [comment] 2016-09-05 03:55
@asmecher  
I got the same issue and the rest upload buttons not working. When inspected, the Chrome browser 's console show this warning and error,

  
<img width="533" alt="admin_wizard_inspected" src="https://cloud.githubusercontent.com/assets/21995563/18237060/29975208-7357-11e6-8db6-4e0c136b7a18.png">

**Comment by asmecher** [comment] 2016-09-05 04:03
This is a duplicate of https://github.com/pkp/pkp-lib/issues/1795 -- watch that entry for a resolution. Meanwhile you can access the settings forms outside of the setup wizard, where they should work without trouble.

**Closed by asmecher** 2016-09-05 04:04 UTC
