### ISSUE TITLE
Logic Error in SQL query invalidates editorial statistics

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#9132] opened 2023-07-04 13:18 UTC
**Describe the bug**
When compiling the number of published submissions for all our journals I recognized differences in the reported OJS stats (editorial stats) as compared to the actual number of publications listed in the frontend. For some journals even zero published submissions are shown.

Some of these differences can be accounted for by the known issues with missing publication dates and imported articles.

However, sticking to one particular case with no imported articles at all, 37 articles listed in the frontend and 0 published submissions reported in editorial stats over the last 2 years, I debugged the code and came across the followling lines intended to exclude imported submissions:

https://github.com/pkp/pkp-lib/blob/5cad3a1534781d682b242b528158b957702948f1/classes/services/queryBuilders/PKPStatsEditorialQueryBuilder.inc.php#L365-L371

In line 369 all publications with no publication date are selected, i.e. included in the response instead of excluded as was intended. Changeing line 369 to:

```
$q->whereNotNull('pi.date_published')
```
generates the correct number of 37 published articles in the editorial stats backend.

**To Reproduce**
1. Count the number of publsihed submission in the frontend (maybe for a certian period to make it easier)
4. Compare to the number of published submissions in the editorial stats in the backend

**What application are you using?**
 OJS version 3.3.0-14

**Additional Information**
Original discussion of this code: https://github.com/pkp/pkp-lib/issues/6011

<hr>

PRs:
- https://github.com/pkp/pkp-lib/pull/9163 (stable-3_3_0)
- https://github.com/pkp/ojs/pull/3973 (stable-3_3_0 only submodule update)
- https://github.com/pkp/pkp-lib/pull/9162 (stable-3_4_0)
- https://github.com/pkp/ojs/pull/3972 (stable-3_4_0 only submodule update)
- https://github.com/pkp/pkp-lib/pull/9172
- https://github.com/pkp/ojs/pull/3978  (only submodule update)

Fix1:
- https://github.com/pkp/pkp-lib/pull/9218 (stable-3_3_0)
- https://github.com/pkp/ojs/pull/4000 (stable-3_3_0 only submodule update)
- https://github.com/pkp/omp/pull/1437 (stable-3_3_0 only submodule update)
- https://github.com/pkp/ops/pull/551 (stable-3_3_0 only submodule update)
- https://github.com/pkp/pkp-lib/pull/9221 (stable-3_4_0)
- https://github.com/pkp/ojs/pull/4002 (stable-3_4_0 only submodule update)
- https://github.com/pkp/omp/pull/1439 (stable-3_4_0 only submodule update)
- https://github.com/pkp/ops/pull/553 (stable-3_4_0 only submodule update)

**Comment by bozana** [comment] 2023-07-11 11:29
Hi @ronste, good catch!
I think that part of the code (`whereNull`) is correct -- it is an `OR` condition -- else, if using `whereNotNull`, the other editorial stats (e.g. number of received submissions) would be wrong because those not published would not be considered. 

I think the problem is in this line: 	
`->orWhere('s.date_submitted', '<=', Capsule::raw('pi.date_published')); `
and I think it should be:
`->orWhere(Capsule::raw('DATE(s.date_submitted)'), '<=', Capsule::raw('pi.date_published'));`
The date_submitted is a datetime, e.g. `2023-06-27 18:31:12`, and date_published is a date, e.g. `2023-06-27`. Thus, if both are the same dates, on the same day, the condition will never be true.

Could you please check if those missing articles are maybe submitted and published on the same day i.e. hoe are the submitted and published date of those articles?

**Comment by ronste** [comment] 2023-07-11 15:43
Hi @bozana ,

when I try your suggestion, i.e.

```
$q->where(function($q) {
			$q->whereNull('pi.date_published')
			->orWhere(Capsule::raw('DATE(s.date_submitted)'), '<=', Capsule::raw('pi.date_published'));
```

I get:
  - 25 published submission
  - 37 other submission
  - 37 imported submissions

instead of 37 published and 0 imported:

![grafik](https://github.com/pkp/pkp-lib/assets/54445456/9c0c813e-5bf5-4711-aac0-29da352d5266)

And I just did another short test. I created a new empty journal (actually a fresh installation) and created and published a single submission. With the original code the editorial activity shows:

![grafik](https://github.com/pkp/pkp-lib/assets/54445456/8dd78084-14a2-43a8-ac98-f799f953d926)

With the code you suggested I get:

![grafik](https://github.com/pkp/pkp-lib/assets/54445456/9dfe13b1-094b-408a-b33c-45d62bd6af62)

That is certainly better. But the submissions are still counted as `imported`.

If I apply your fix to replace `'s.date_submitted'`with `Capsule::raw('DATE(s.date_submitted)')` to the function `countImported()` I indeed get a count of zero imported submissions. In the same file I can see a number of other occurances of `'s.date_submitted'` where this might kick in.

However, i still can't figure out why I only get 25 published submissions for my joural instead of 37. When I run the query in the database, i.e.:

```sql
select * from `submissions` as `s` left join `publications` as `pi` on
  `pi`.`publication_id` = (select `pi2`.`publication_id` from `publications` as `pi2` where
    `pi2`.`submission_id` = `s`.`submission_id` and `pi2`.`status` = 3
      order by `pi2`.`date_published` asc limit 1) where `s`.`context_id` in (1) and
        `s`.`submission_progress` = 0 and
      (`pi`.`date_published` is null or DATE(s.date_submitted) >= pi.date_published) and
        `pi`.`date_published` > '2021-07-05';
```

I get the correct number of 37 rows of publications.

**Comment by bozana** [comment] 2023-07-13 12:04
yes, I would then need to apply the changes to those other places in the code :+1: 
Hmmm... let me think about that 25 vs. 37 published....

**Comment by ronste** [comment] 2023-07-13 12:27
> what do you get wit this sql:
> 
> ```
> select * from `submissions` as `s` 
> left join `publications` as `pi` on `pi`.`publication_id` = (select `pi2`.`publication_id` from `publications` as `pi2` where `pi2`.`submission_id` = `s`.`submission_id` and `pi2`.`status` = 3 order by `pi2`.`date_published` asc limit 1) 
> left join `publications` as `p` on `p`.`publication_id` = (select `p2`.`publication_id` from `publications` as `p2` where `p2`.`submission_id` = s.submission_id and `p2`.`status` = 3 order by `p2`.`date_published` asc limit 1) 
> where `s`.`context_id` in (1) and `s`.`submission_progress` = 0 and (`pi`.`date_published` is null or `s`.`date_submitted` <= pi.date_published) and `s`.`status` = 3 and `p`.`date_published` >= 2021-07-11 and `p`.`date_published` <= 2023-07-10
> ```

> 

I get an empty set.

By the way, this is the journal used for this test: [https://dedo.ub.uni-siegen.de/index.php/de_do](https://dedo.ub.uni-siegen.de/index.php/de_do).
We are talking about the issues 2021 and 2022 which together have 37 publications (plus two issue pdfs) on the web site.

**Comment by ronste** [comment] 2023-07-13 12:37
> Ah sorry the DATE around was missing, thus:
> 
> ```
> select * from `submissions` as `s` 
> left join `publications` as `pi` on `pi`.`publication_id` = (select `pi2`.`publication_id` from `publications` as `pi2` where `pi2`.`submission_id` = `s`.`submission_id` and `pi2`.`status` = 3 order by `pi2`.`date_published` asc limit 1) 
> left join `publications` as `p` on `p`.`publication_id` = (select `p2`.`publication_id` from `publications` as `p2` where `p2`.`submission_id` = s.submission_id and `p2`.`status` = 3 order by `p2`.`date_published` asc limit 1) 
> where `s`.`context_id` in (1) and `s`.`submission_progress` = 0 and (`pi`.`date_published` is null or DATE(`s`.`date_submitted`) <= pi.date_published) and `s`.`status` = 3 and `p`.`date_published` >= 2021-07-11 and `p`.`date_published` <= 2023-07-10
> ```

Still an empty set unfortunately. Maybe we can have a call to try these things? Can you send me your number by e-mail?

**Comment by bozana** [comment] 2023-07-13 12:57
Date maybe needs ' around it:
```
select * from `submissions` as `s` 
left join `publications` as `pi` on `pi`.`publication_id` = (select `pi2`.`publication_id` from `publications` as `pi2` where `pi2`.`submission_id` = `s`.`submission_id` and `pi2`.`status` = 3 order by `pi2`.`date_published` asc limit 1) 
left join `publications` as `p` on `p`.`publication_id` = (select `p2`.`publication_id` from `publications` as `p2` where `p2`.`submission_id` = s.submission_id and `p2`.`status` = 3 order by `p2`.`date_published` asc limit 1) 
where `s`.`context_id` in (1) and `s`.`submission_progress` = 0 and (`pi`.`date_published` is null or DATE(`s`.`date_submitted`) <= pi.date_published) and `s`.`status` = 3 and `p`.`date_published` >= '2021-07-11' and `p`.`date_published` <= '2023-07-10'

```

**Comment by ronste** [comment] 2023-07-13 13:01
> start and end date maybe need ' around it:
> 
> ```
> select * from `submissions` as `s` 
> left join `publications` as `pi` on `pi`.`publication_id` = (select `pi2`.`publication_id` from `publications` as `pi2` where `pi2`.`submission_id` = `s`.`submission_id` and `pi2`.`status` = 3 order by `pi2`.`date_published` asc limit 1) 
> left join `publications` as `p` on `p`.`publication_id` = (select `p2`.`publication_id` from `publications` as `p2` where `p2`.`submission_id` = s.submission_id and `p2`.`status` = 3 order by `p2`.`date_published` asc limit 1) 
> where `s`.`context_id` in (1) and `s`.`submission_progress` = 0 and (`pi`.`date_published` is null or DATE(`s`.`date_submitted`) <= pi.date_published) and `s`.`status` = 3 and `p`.`date_published` >= '2021-07-11' and `p`.`date_published` <= '2023-07-10'
> ```

Now its 25

**Comment by bozana** [comment] 2023-07-13 13:04
This is the SQL executed to get published submissions. How do other 12 submissions from you not fit into it... ? :thinking:

**Comment by bozana** [comment] 2023-07-14 12:08
@ronste, I've just tested the case when an article is submitted, assigned to an already published issue, and then published. The article date published is not the issue's date published, but the current date. I have tested it using the latest release i.e. the current stable_3_3_0 branch. Thus, this is not your case. Maybe QuickSubmitt plugin behaves differently, maybe you can double check that i.e. if your users have used that plugin and entered the date published that way...
However I will provide the SQL fix here, that we agreed solves the wrong numbers on the editorial statistics page.

**Comment by ronste** [comment] 2023-07-21 07:35
> @ronste, I've just tested the case when an article is submitted, assigned to an already published issue, and then published. The article date published is not the issue's date published, but the current date. I have tested it using the latest release i.e. the current stable_3_3_0 branch. Thus, this is not your case. Maybe QuickSubmitt plugin behaves differently, maybe you can double check that i.e. if your users have used that plugin and entered the date published that way... However I will provide the SQL fix here, that we agreed solves the wrong numbers on the editorial statistics page.

Hi @bozana ,

thanks for the discuission of the issue and the fixes! I will have a look at our specific case(s) when I'm back from vacation. This aprticular journal started with OJS 3 but other have an OJS 2 history, so there might be different reasons for the remaining issue.

**Comment by asmecher** [comment] 2023-08-02 18:58
@bozana, could you check out [this comment](https://github.com/pkp/pkp-lib/commit/96883fad1a05f57615e59a360fdf927d4d2c1735#r123427322)?

**Comment by bozana** [comment] 2023-08-11 12:10
Fixes merged, thus closing...

**Closed by bozana** 2023-08-11 12:10 UTC
Labels: Bug:1:Low
