### ISSUE TITLE
Native XML export doesn't work for OMP and OJS

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1263] opened 2016-03-14 13:13 UTC
I get a mostly empty XML file when trying to run the Native XML export function for OMP and OJS.

```
<?xml version="1.0"?>
<articles xmlns="http://pkp.sfu.ca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pkp.sfu.ca native.xsd"/>
```

Not sure if this is something that needs to be fixed for OMP 1.2...

**Comment by asmecher** [comment] 2016-03-17 00:27
Could you send me a DB dump and an ID for the submission that's failing export? I'll have a look.

**Comment by bozana** [comment] 2016-03-17 09:18
I've just found a 'bug' in OMP, related to the native export: The reviewer files have no genre. Is this meant to be so? However, this produces the "Assertion failed" for https://github.com/pkp/pkp-lib/blob/master/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php#L89 and error "Call to a member function getName() on null" for https://github.com/pkp/pkp-lib/blob/master/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php#L90.

**Comment by asmecher** [comment] 2016-03-18 05:14
Maybe @jnugent remembers re: the DOI question above?

**Comment by jnugent** [comment] 2016-03-18 12:51
Actually, we did add DOIs to Monographs in general, if I recall.  @asmecher remember our discussion about adding DOI support to Submissions in general?  

Some code from OMP master:  
https://github.com/pkp/omp/blob/master/plugins/pubIds/doi/DOIPubIdPlugin.inc.php#L84

**Comment by jnugent** [comment] 2016-03-18 12:54
Actually, let me dig into this further. I thought we added the DOI foms to submission metadata as well.

**Comment by bozana** [comment] 2016-03-21 13:17
Apparent there was a requirement for reviewer files not to have a genre, s. https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8358 and https://github.com/pkp/pkp-lib/commit/9657dd599620ca9b688dc2a447c1789b7d83c0c4.
In submission_files tables, the genre_id column is defined so it could be null. Thus, the bug a) above should probably be repaired in the native import/export i.e. the genre_id = null for reviewer files should be considered there.

**Comment by asmecher** [comment] 2016-03-21 18:01
Hmm, I suggest keeping the XML parallel to the database, i.e. not specifying a genre leads to a null genre ID. This may cause confusion for users crafting their own XML who exclude a genre, but I hate that less than hard-coding a special interpretation for the current null genre / reviewer file convention.

**Comment by jnugent** [comment] 2016-03-21 18:08
I'm okay with this idea.  I think it might be a good idea to add an assertion during Native Import that fails if there is no genre id and the submission file is not of type SUBMISSION_FILE_REVIEW_FILE.  I'm cool with folks crafting their own XML so long as it does not lead to a potentially corrupt database.

**Comment by asmecher** [comment] 2016-03-21 18:12
Agreed, @jnugent, that's a very good idea.

**Comment by bozana** [comment] 2016-03-21 19:35
OK, I'll change it like you say -- The omitted genre is possible only for SUBMISSION_FILE_REVIEW_FILE and SUBMISSION_FILE_REVIEW_ATTACHMENT else there will be an assertion. I thought that the reviewer files can be send to copyediting as well, but this is apparently not the case, only for example from internal to external review. THANKS!!!

**Comment by bozana** [comment] 2016-03-21 20:15
Hmmm I have a NULL for some SUBMISSION_FILE_REVIEW_REVISION files in my DB, but I cannot reproduce it... :-(

**Comment by bozana** [comment] 2016-03-21 20:22
Oh sorry, I managed it: if a (internal) reviewer file is send to the external review, it appears in the list "Review Files" on top of that page, and it has genre = null. When I then upload a revision file, I can choose that file as source and in that case the genre is also null.

**Comment by asmecher** [comment] 2016-03-22 15:26
I don't know of anything that'll break with a `genre IS NULL`, but I'd rather we don't encourage it. I'd suggest we require it for the import, except for the reviewer file case, unless we run into a reason to change that.

**Comment by bozana** [comment] 2016-03-22 15:45
@asmecher, OK. I just oriented myself on the export i.e. if someone is using OMP export XML file to import it into another OMP installation. I.e. the genre in the export XML file (and in the DB) could be null also for other files (e.g. in copyediting).

**Comment by asmecher** [comment] 2016-03-22 15:48
@bozana, ah, of course. Hmm. Well, perhaps if we're going to support null `genre_id`s, then we should jump in with both feet. OK -- relax the requirement and we'll have to watch and see what happens.

**Comment by bozana** [comment] 2016-03-22 15:51
@asmecher, OK, I will relax the requirement for now. We could eventually see if we want to somehow restrict the reviewer files for sending them to other workflow stages i.e. external review...

**Comment by bozana** [comment] 2016-03-22 16:18
@asmecher or @jnugent, could you please take a look at the changes above, especially changes for the element "remote". If OK so I would make a PR. 
From this issue then only the DOI for monographs question is left at the moment. For this I will wait for Jason to tell me how is it meant to be... :-)
Also, do you have an idea how to best inform the user to fill in the settings > workflow > production when needed?

**Comment by jnugent** [comment] 2016-03-22 18:39
@bozana the only place I can see getRemoteURL being used is ArticleGalley specifically, when we redirect people to them when viewed.  It's an actual redirection performed in ArticleHandler, and possibly not quite the same thing as embedding a remote URL in a page href element.   So, I agree with you that it should be Representation only.

**Comment by jnugent** [comment] 2016-03-22 18:40
I'm still digging around for the DOI issue.

**Comment by bozana** [comment] 2016-03-23 11:01
Here the PRs:
a), f), g) from above: https://github.com/pkp/pkp-lib/pull/1299
c), d) from above: https://github.com/pkp/omp/pull/246

**Comment by asmecher** [comment] 2016-03-23 16:20
Thanks, merged the above!

On e), I recently added a warning at the top of the ONIX plugin's export page. Could certainly be improved, but enough for OMP 1.2.

**Comment by bozana** [comment] 2016-03-23 16:48
Thanks @asmecher! Apparently the ONIX export is also used in the native export, for some parts of the native XML export file, so that the warning is also happening here. I will take a look on your solution, where and how you have added the warning, and if we could do something similar here...

**Comment by jnugent** [comment] 2016-03-23 16:50
@bozana yes, the ONIX filter is used in part of the Native XML, in order to prevent having to duplicate a lot of the ONIX fields in the other filter.

**Comment by asmecher** [comment] 2016-03-23 16:55
@bozana, grep for `plugins.importexport.onix30.pressMissingFields`; it should be easy enough just to re-use that, though maybe the actual settings check could be moved into PHP so it can be re-used.

**Comment by bozana** [comment] 2016-03-23 17:43
@asmecher and @jnugent, I am just not sure if I should provide the export also if the data is missing or not. I believe it is only used for the "Product" part of the publication_format element. Maybe we can make it optional?

**Comment by asmecher** [comment] 2016-03-23 17:46
@jnugent, I remember we did something vaguely similar that involved pre-processing the ONIX spec using an XSL or something like that, to permit supporting a more relaxed behavior but without actually duplicating and modifying the spec. Do you remember where that was?

**Comment by bozana** [comment] 2016-04-04 10:18
Here is the PR for e) above: https://github.com/pkp/omp/pull/258, OK so?

**Comment by bozana** [comment] 2016-04-04 10:57
In the commit/PR above I just solved the assertion failure from b), till we figure out, if the DOI plug-in should consider monographs at all...

**Comment by asmecher** [comment] 2016-04-04 20:22
Thanks, @bozana! What of the above remains for the 1.2 release?

**Comment by bozana** [comment] 2016-04-05 08:23
@asmecher, this issue can be closed -- all of the points above are solved. We can maybe just open a new issue for the DOI plugin monograph option?

**Comment by asmecher** [comment] 2016-04-05 15:54
@bozana Thanks!

**Comment by bozana** [comment] 2016-04-11 12:46
The needed native export improvements for OJS 3.0:
- [ ] a) The filter for supplementary files.

**Closed** 2016-08-09 11:11 UTC
Labels: Open Journal Systems, Open Monograph Press
