### ISSUE TITLE
DOAJ Plugin may create duplicates

### ISSUE THREAD

**Issue by mpbraendle** [pkp/pkp-lib#8463] opened 2022-12-02 07:21 UTC
**Describe the bug**
When an article is already marked registered in the DOAJ export plugin, and the user wants to register again (e.g. because of an update), PUT should be used instead of POST . Otherwise a duplicate will be created at DOAJ.

**To Reproduce**
See https://forum.pkp.sfu.ca/t/bugs-in-doaj-export-plugin-orcid-id-missing-in-json-registration-of-duplicates-possible/75673

**What application are you using?**
 OJS 3.3.0-13

**Comment by bozana** [comment] 2023-05-09 14:08
Hi @mpbraendle,
Have you experienced the problem? Do you know if any and what article metadata has changed that led to a duplicate?
I cannot reproduce it using the DOAJ test system.
Using PUT would mean that we would need to have DAOJ article ID, which we do not have/save. And if an article is manually marked as registered, we for sure do not have that ID.
I will double check with DOAJ how does this internally function, because I could not reproduce the problem -- the system somehow always knows what article needs to be updated...

**Comment by bozana** [comment] 2023-08-21 12:31
I will close this issue because we haven't heard from exact use case/problem, and the change would bring some other difficulties...

**Closed by bozana** 2023-08-21 12:31 UTC
Labels: Bug:1:Low
