### ISSUE TITLE
Images aren't handled correctly on the front end of HTML galleys in versioned articles

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#7330] opened 2021-09-24 18:18 UTC
**Describe the bug**
Related forum thread with a description of the bug and steps to reproduce: https://forum.pkp.sfu.ca/t/no-images-in-html-galley-of-a-versioned-article/69614

**What application are you using?**
Confirmed for the current main branch of OJS, also relevant for 3.3

**Additional information**
URL that is built by the HTML galley plugin is correct, the problem seems to be in how `ArticleHandler`  deals with requests to galleys of previous article's versions.

**Comment by asmecher** [comment] 2021-09-24 19:06
If it's relevant to 3.3.0-x, it should be fixed there -- Images/CSS in HTML galleys rarely gets testing before release, so this would be a great candidate for an automated test!

**Comment by Vitaliy-1** [comment] 2021-09-26 18:20
Looking at this one, I'd suggest using a version-specific URL for download operations for dependent files. For galleys that refer to the old version of publication it looks:
```
...article/download/[submissionId]/[galleyId]/[submissionFileId]
```
it results in redirect here: https://github.com/pkp/ojs/blob/3c6325159ce631b64c8fa8c2abc52e1c762ed49c/pages/article/ArticleHandler.inc.php#L176

Because the `download` URL doesn't include publication id, during Handler initialization `currentPublication` is used to retrieve its galleys. And as `galleyId` in the request actually is associated with the old publication, this redirect happens.

**Comment by asmecher** [comment] 2022-08-31 00:54
@Vitaliy-1, I wasn't able to reproduce the problem by following the user's reproduction steps; were you able to reproduce the issue yourself?

**Comment by bozana** [comment] 2022-08-31 13:41
I've just tested it with stable-3_3_0 and could not reproduce the problem

**Comment by asmecher** [comment] 2022-08-31 16:10
Hmm, I still can't duplicate it :upside_down_face: Can you take a look at resolving this, @bozana? Or send me a DB dump and file set that demonstrates?

**Comment by bozana** [comment] 2022-09-01 09:31
I will take a look into both (preview and older versions)...

**Comment by bozana** [comment] 2022-09-01 10:28
PRs:
ojs stable-3_3_0: https://github.com/pkp/ojs/pull/3529

**Comment by bozana** [comment] 2022-09-01 10:33
@asmecher, could you take a look at the PR?
Somehow, the problem only occurs when htmlArticleGalley plugin is used. 
Else, without the plugin, it somehow works... :-O :thinking:

**Comment by asmecher** [comment] 2022-09-02 23:20
The PRs appear to work for me -- that is, I wasn't able to replicate the problem before, but the changes continue to work as expected. @ctgraham, can you test one of the PRs with your replication of the problem?

**Comment by ctgraham** [comment] 2022-09-02 23:38
Already confirmed in the OJS PR.
https://github.com/pkp/ojs/pull/3529#issuecomment-1234266063

**Comment by asmecher** [comment] 2022-09-02 23:41
Perfect -- thanks, all! Merged.

**Closed by asmecher** 2022-09-02 23:41 UTC
Labels: Bug:1:Low
