### ISSUE TITLE
Submission Hyperlink

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6269] opened 2020-10-06 21:01 UTC
**Describe the bug**
When a journal puts an HTML hyperlink to open a new tab in the submission guideline the way the URL function differs on the journal front end and within the submission steps. 

**To Reproduce**
Front end (User facing Submission page) - when clicked will open a new window as dictated by the HTML code.

Backend (Author submission step) - If an author were to click on the hyperlink in the submission process it opens the page in the same window. 

**What application are you using?**
OJS 3.2

**Additional Information**
The hyperlink within the submission process should ideally allow for the link to open in a new window or have a warning that you're leaving the current page.

**Comment by asmecher** [comment] 2020-10-07 14:28
@pmangahis, could you include a few screenshots so I'm sure I'm looking for the right thing? Thanks!

**Comment by pmangahis** [comment] 2020-10-07 15:40
Hi @asmecher,

Here are two recordings of this in action. The hyperlink gets added by the user in Settings>Workflow>Submission>Checklist (if this is helpful)

Front end
![Frontend Submission hyperlink](https://user-images.githubusercontent.com/50342731/95353942-b3c40d80-0878-11eb-8849-1d4f702a17f4.gif)

Backend

![Backend Submission hyperlink](https://user-images.githubusercontent.com/50342731/95353974-bd4d7580-0878-11eb-98e6-e1c8d1d9bbf3.gif)

**Comment by NateWr** [comment] 2020-10-08 10:53
Confirmed. This is because `|strip_unsafe_html` is applied in the [backend](https://github.com/pkp/pkp-lib/blob/master/templates/submission/form/step1.tpl#L38) but not the [frontend](https://github.com/pkp/pkp-lib/blob/master/templates/frontend/pages/submissions.tpl#L49).

What do you think, Alec? Since this is input from a manager or admin, is it safe without `strip_unsafe_html`? Or can we extend `strip_unsafe_html` to allow `target` attributes?

**Comment by asmecher** [comment] 2020-10-08 14:11
I would support removing `strip_unsafe_html` as this is a journal setting, and generally we don't filter data that's entered by site admin or manager users.

**Comment by NateWr** [comment] 2020-10-12 09:33
PRs:
https://github.com/pkp/pkp-lib/pull/6280
https://github.com/pkp/pkp-lib/pull/6281 (stable-3_2_1)

Tests:
https://github.com/pkp/ojs/pull/2880

**Comment by NateWr** [comment] 2020-10-12 11:29
Merged to `master` and `stable-3_2_1`.

**Closed by NateWr** 2020-10-12 11:29 UTC
Labels: Bug, Hosting
