### ISSUE TITLE
[OJS] Enable copying editor decision emails

### ISSUE THREAD

**Issue by spapad** [pkp/pkp-lib#3240] opened 2018-01-05 07:31 UTC
In OJS 2 there was an option available for copying (cc) the email sent from reviewers to authors about the editor decision. This is no longer available in OJS 3.

**Comment by asmecher** [comment] 2018-01-05 18:10
This is a duplicate of https://github.com/pkp/pkp-lib/issues/743.

**Closed by asmecher** 2018-01-05 18:10 UTC
