### ISSUE TITLE
Unable to upgrade 3.3.0.2: Call to a member function getConnection() on null

### ISSUE THREAD

**Issue by jameswill** [pkp/pkp-lib#6703] opened 2021-02-02 10:29 UTC
**Describe the bug**
After applying necessary changes when I visit http://domain.com/[[DIR]]/index.php/index/install/installUpgrade it gives blank page.

On further debugging I found following error.

_Array ( [type] => 1 [message] => Uncaught Error: Call to a member function getConnection() on null in [[PATH]]/[[DIR]]/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74_

It seems newly added laravel is conflicting.

**To Reproduce**
1. Back up your files and database
2. Remove files of existing installation.
3. Restore your config.inc.php with all new changes present in new version.
4. Visit http://domain.com/[[DIR]]/index.php/index/install/upgrade and click on "Upgrade" throws above error.

**What application are you using?**
 OJS, OMP and OPS version 3.3.0.2

**Additional information**
Using PHP 7.3 and Mysql 5.5

**Comment by NateWr** [comment] 2021-02-02 11:00
Have you read the [Release Notebook](http://localhost:4000/dev/release-notebooks/en/3.3-release-notebook) for 3.3? In particular, take a look at the note on the [connection_charset](http://localhost:4000/dev/release-notebooks/en/3.3-release-notebook#update-connection_charset) config file.

**Comment by NateWr** [comment] 2021-02-02 11:03
Sorry, I accidentally put in some bad links there. Let's try this again:

Have you read the [Release Notebook](https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.3-release-notebook) for 3.3? In particular, check out the section on the [connection_charset](https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.3-release-notebook#update-connection_charset) config option. This was the source of this error in at least one other case.

**Comment by gemusehandler** [comment] 2021-02-02 21:01
Working on MacOS. Can't upgrade, can't install new version. Not through the browser, nor with command line. This is the result from new install through the browser:

Errors occurred during installation
A database error has occurred: SQLSTATE[HY000] [1049] Unknown database 'ojs33' (SQL: create table `announcement_types` (`type_id` bigint not null auto_increment primary key, `assoc_type` smallint not null, `assoc_id` bigint not null) default character set utf8 collate 'utf8_general_ci')

**Comment by asmecher** [comment] 2021-02-02 21:37
@gemusehandler, I see you've already posted on the forum at https://forum.pkp.sfu.ca/t/serious-issue-with-database-upgrade-failed-from-3-2-1-3-to-3-3-0-2/65598/3 -- that's the best place to get feedback on this.

**Comment by jameswill** [comment] 2021-02-03 07:17
> 
> 
> Sorry, I accidentally put in some bad links there. Let's try this again:
> 
> Have you read the [Release Notebook](https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.3-release-notebook) for 3.3? In particular, check out the section on the [connection_charset](https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.3-release-notebook#update-connection_charset) config option. This was the source of this error in at least one other case.

Yes. I am aware of this and I have configure config.inc.php with reference of config.TEMPLATE.inc.php keeping the database details same as that of the original installation.

**Comment by NateWr** [comment] 2021-02-03 10:05
@jameswill here is the code that [initializes the database connection](https://github.com/pkp/pkp-lib/blob/master/classes/core/PKPApplication.inc.php#L210-L220). Can you double-check that each of the config settings shown there is correct?

Where you see: `Config::getVar('i18n', 'connection_charset', 'utf8')` that will return the `connection_charset` config option or `utf8` if no config option exists with that name.

**Comment by jameswill** [comment] 2021-02-03 10:44
Yes. That setting is there in /lib/pkp/classes/core/PKPApplication.inc.php

**Comment by Vitaliy-1** [comment] 2021-02-03 11:47
I'm able to reproduce the error, or at least get the same error message when trying to upgrade through a web interface. The problem doesn't occur when upgrading from a command line. Exploring...

**Comment by Vitaliy-1** [comment] 2021-02-03 12:04
I was able to solve it by initializing Laravel's database connection in the constructor of the `Upgrade` class.
E.g., like:
```
Application::get()->initializeDatabaseConnection();
```
But I'm not quite familiar with this part of code. Should this be done in `Installer`'s constructor? Or is there a better place?

**Comment by jameswill** [comment] 2021-02-03 12:10
> 
> 
> I was able to solve it by initializing Laravel's database connection in the constructor of the `Upgrade` class.
> E.g., like:
> 
> ```
> Application::get()->initializeDatabaseConnection();
> ```
> 
> But I'm not quite familiar with this part of code. Should this be done in `Installer`'s constructor? Or is there a better place?

Exactly in which file you made changes ?

**Comment by asmecher** [comment] 2021-02-03 22:24
For the error message when using the web-based upgrade form:
```
Uncaught Error: Call to a member function getConnection() on null in [[PATH]]/[[DIR]]/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74
```
You can fix this by applying the following change: https://github.com/asmecher/pkp-lib/commit/b03a74da7f58f15005d0d3294a4d58e2845abf9c
If applying a patch, you can use...
```bash
cd lib/pkp
wget -O - -q https://github.com/asmecher/pkp-lib/commit/b03a74da7f58f15005d0d3294a4d58e2845abf9c.diff | patch -p1
```

@Vitaliy-1, can you confirm that this fixes the issue for you?

**Comment by jameswill** [comment] 2021-02-04 04:45
Hi,

This resolves the issue I mentioned above but it leads to another error.

Errors occurred during installation:

    A database error has occurred: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'omp331.journal_settings' doesn't exist (SQL: select `js`.`journal_id` as `id`, `js`.`setting_value` as `locales` from `journal_settings` as `js` inner join `journals` as `j` on `j`.`journal_id` = `js`.`journal_id` where `js`.`setting_name` = supportedFormLocales)

![image](https://user-images.githubusercontent.com/6368036/106845840-ca1c9180-66d1-11eb-9159-ec47a78fd314.png)


What is causing this ?

**Comment by jameswill** [comment] 2021-02-04 10:17
I also wanted to add that above code only does not work with OMP as there is no "journal_settings" table available.

However it is working properly with OPS.

**Comment by NateWr** [comment] 2021-02-04 10:36
@jameswill yes, an unfortunate bug to make it in (my fault). That's being tracked and addressed in #6710.

**Comment by jameswill** [comment] 2021-02-04 11:02
Shall I wait for the 3.3.0.3 release with the solutions for OJS, OPS and OMP as well ?

What is ETA for the new releases ?

**Comment by asmecher** [comment] 2021-02-04 16:51
@jameswill, we'll have OJS/OMP/OPS 3.3.0-3 out within a couple of days.

**Comment by asmecher** [comment] 2021-02-05 20:18
@Vitaliy-1, your confirmation on https://github.com/pkp/pkp-lib/issues/6703#issuecomment-772868354 would be great, but I'm closing this issue for now as resolved.

**Closed by asmecher** 2021-02-05 20:18 UTC

**Comment by Vitaliy-1** [comment] 2021-02-08 08:32
@asmecher, I confirm that it solves the issue and can be merged.

**Comment by asmecher** [comment] 2021-02-08 17:30
Unfortunately I forgot to merge this for inclusion in 3.3.0-3 :( however I will merge it now.

**Comment by asmecher** [comment] 2021-02-08 17:42
For anyone encountering this problem, you can fix it by applying https://github.com/pkp/pkp-lib/pull/6719/files. The change needs to be applied to `lib/pkp/classes/install/form/UpgradeForm.inc.php`.

**Comment by jameswill** [comment] 2021-02-09 08:41
Hi,

Shall we wait for 3.3.0-4 ? What is the ETA for the same ?

The above fix is required in both the packages. i.e OJS and OMP as without this fix both the packages give error.

I am also getting different issue in OPS upgrade which I have mentioned #6737

**Comment by Vitaliy-1** [comment] 2021-02-09 09:21
I'd recommend upgrading from a command line but it should be safe to apply the fix before performing an upgrade. The fix is against a shared library, it's applied to all 3 applications.

**Comment by jameswill** [comment] 2021-02-09 11:43
Hi,

However CLI upgrade can not be perfomed on shared hosting environment. Hence it would be great if the patch releases as soon as possible.

**Comment by asmecher** [comment] 2021-02-09 15:58
> Shall we wait for 3.3.0-4 ? What is the ETA for the same ?

I expect 3.3.0-4 will be out within a week or two -- so far the web-based upgrade form is the only major fix, and since there's a one-liner change to work around it, I'd like to wait for another issue or two to merit a release.

**Comment by paulo-graca** [comment] 2024-12-07 10:54
For others with same issue and land on this issue, like I did when looking for answers...

I was having kind of the same error message:
```log
PHP Fatal error:  Uncaught Error: Call to a member function getConnection() on null in /vagrant/ojs-3.3.0-18/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74
Stack trace:
#0 /vagrant/ojs-3.3.0-18/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php(200): Illuminate\Database\Capsule\Manager::connection()
#1 /vagrant/ojs-3.3.0-18/lib/pkp/classes/db/DAO.inc.php(68): Illuminate\Database\Capsule\Manager::__callStatic()
#2 /vagrant/ojs-3.3.0-18/lib/pkp/classes/context/ContextDAO.inc.php(61): DAO->retrieve()
#3 /vagrant/ojs-3.3.0-18/tools/rebuildSearchIndex.php(48): ContextDAO->getByPath()
#4 /vagrant/ojs-3.3.0-18/tools/rebuildSearchIndex.php(76): rebuildSearchIndex->execute()
#5 {main}
  thrown in /vagrant/ojs-3.3.0-18/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php on line 74
sáb 07 dez 2024 10:22:47 UTC
```

just after testing a migration process from OJS version 3.2.1-2 to 3.3.0-18. I was trying to do an index rebuild on a local setup to populate the index tables (submission_search_keyword_list, submission_search_object_keywords and submission_search_objects). My fault, the issue was related with me forgetting to change config.inc.php to:
```
installed = On
```
because that wasn't a new setup. Problem fixed.

(this isn't the same issue reported here, but I hope it help others when finding an answer)

**Comment by Faujinurdin** [comment] 2024-12-22 09:53
> For anyone encountering this problem, you can fix it by applying https://github.com/pkp/pkp-lib/pull/6719/files. The change needs to be applied to `lib/pkp/classes/install/form/UpgradeForm.inc.php`.

after i apply this fix   i got another error " You are trying to downgrade the product "orcidProfile" from version [1.1.2.28] to version [1.1.2.8]. Downgrades are not supported."

sholud i disable the plugin first before Upgrade or uninstall it

**Comment by Faujinurdin** [comment] 2024-12-22 10:03
> > For anyone encountering this problem, you can fix it by applying https://github.com/pkp/pkp-lib/pull/6719/files. The change needs to be applied to `lib/pkp/classes/install/form/UpgradeForm.inc.php`.
> 
> after i apply this fix i got another error " You are trying to downgrade the product "orcidProfile" from version [1.1.2.28] to version [1.1.2.8]. Downgrades are not supported."
> 
> sholud i disable the plugin first before Upgrade or uninstall it


i already get the solution 👍 
i delete the newer Plugin in the  database
