### ISSUE TITLE
two entries in the oai interface after removing a submission from TOC and rescheduling it again

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#6625] opened 2021-01-19 15:58 UTC
**Describe the bug**
When a submission is removed from the TOC of an published issue and then published again, the submission appears twice via the OAI interface, as deleted and as published. It seems like the tombstone table is considered when removing the submission from the TOC but not considered when (re)publishing the submission.

**To Reproduce**
1. Go to a published issue
2. Click Edit > TOC > Submission Remove
3. Go to the submission
4. Click on Schedule For Publication > Publish
5. See the OAI interface

**What application are you using?**
 OJS version 3.3, master branch

**Additional information**
The issue was discovered through this PR: https://github.com/pkp/ojs/pull/2995, so that the current tests are failing now :-\
It seems that the unpublishing of a submission does not make any entries into the tombstone table.

**Comment by NateWr** [comment] 2021-01-20 14:59
Here's a PR for ojs to see if this fixes the tests. I'm working on OMP now.

PR:
https://github.com/pkp/ojs/pull/3001

**Comment by NateWr** [comment] 2021-01-20 15:51
FYI, the OJS tests have passed so I went ahead and merged those changes in order to fix the tests in master, but they haven't been through code review. @bozana would you be able to take a look at these PRs to see if you can spot anything I've missed?

**Comment by asmecher** [comment] 2021-01-26 01:49
Hi @NateWr -- good spotting throughout. Some answers to your questions:

> I noticed that publication formats from unpublished submissions were being included in the OAI set due to this line. I changed that to = ' . STATUS_PUBLISHED. If that's correct, is that something we should backport?

Yes, please do.

> It looks like OMP's OAI shows all of the publication formats for the latest version. Since the IDs of publication formats change between versions, that means that pub formats will "disappear" with a new version. For example, if I publish a book with one format, it might have an ID like this: oai:omp.localhost:8000:publicationFormat/21. If I then create a new version and publish that, 21 is gone and a new entry in OAI appears: oai:omp.localhost:8000:publicationFormat/22. Is that ok and the expected behaviour?

This is not ideal and I'll have to think about a better solution. In the meantime, I think the best way to at least keep consistent is to add a tombstone when a new version is created, so that harvesters can be informed that the old version is gone. Alternately we could simply disable tombstone support and inform clients via the OAI interface that [deleted records are not supported](http://www.openarchives.org/OAI/openarchivesprotocol.html#deletion) for the moment. I would prefer the former solution. Unfortunately the OAI-PMH interface isn't rich enough to support much else.

> Related to the last point, when a version is unpublished, we put a tombstone in for each of the available pub formats. This can lead to a problem in the following (uncommon) scenario. Let's say I published two versions of a book. OAI will show results from the latest version. If I then unpublish the first version and delete a publication format, I'll get a tombstone made for that format. So in this case it would be possible to have a tombstone for a publication format from an old version. Is that ok and the expected behaviour?

Yes, I think that's actually fine. Clients should be able to handle the deletion of records that aren't in their holdings.

> OMP inserts/deletes tombstones when a context is enabled or disabled. Does that do anything? Is the OAI endpoint even accessible when a context is disabled?

This is for the sake of the site-wide OAI interface, which collects content from all journals/presses and would be affected by the disabling of a particular journal or press. (You can request it with an OAI URL using `index` for the journal/press path.) Presenting tombstones for a press that was previously enabled but has been disabled seems like a sensible behaviour, although for a rare/drastic operation. This should be made consistent between OJS, OMP, and OPS, if it's not currently.

> This has got me thinking that we should really invest in some tests that cover any functionality around published material that is not visually apparent in the normal use of the software. OAI, RSS and Google Scholar tags come to mind, but there are probably others. I don't think these tests need to be run against the PHP/SQL matrix. Instead, we need a set of tests that deliberately go through publishing, versioning and unpublishing workflows and then check to ensure the correct data is shown in each place. Is it worth filing an issue specifically about this?

Yes, please do file this. I'd like to look into infrastructural changes to make this possible, e.g. replacing our homebrew interfaces with third-party libraries, and that could eliminate much of the need to test if it's already covered by the lib; then we should be using unit tests rather than coaxing e.g. Cypress into working with XML.

**Comment by NateWr** [comment] 2021-01-26 15:24
Thanks @asmecher, I've backported the fix to only show published items to `stable-3_2_1` and filed an issue for the distribution tests (https://github.com/pkp/pkp-lib/issues/6674).

The following PRs fix tombstone handling in OMP so that pub format tombstones exist for any published versions except the current version. And I've fixed some issues with the add/delete of tombstones as a context is enabled/disabled/deleted.

Two remaining questions:

1. It doesn't look like OPS creates any tombstones, so I didn't introduce it. Do we need to do something here?
2. Do we need a migration to handle any bad tombstones between 3.2 and 3.3? I suspect if items are being published/unpublished, there may be some stray tombstones in there where they shouldn't be. But I doubt the problem is widespread.

PRs:
https://github.com/pkp/omp/pull/912
https://github.com/pkp/ojs/pull/3015

**Comment by NateWr** [comment] 2021-01-27 11:45
Both PRs are merged. I'll leave this open pending the questions in the last comment.

**Comment by asmecher** [comment] 2021-01-28 02:30
> It doesn't look like OPS creates any tombstones, so I didn't introduce it. Do we need to do something here?

Yes, please file this!

> Do we need a migration to handle any bad tombstones between 3.2 and 3.3? I suspect if items are being published/unpublished, there may be some stray tombstones in there where they shouldn't be. But I doubt the problem is widespread.

I don't *think* so... OAI data consumers should be resilient about deletion data, and as long as actual data gets properly delivered, I think trying to clean this up without doing a pretty thorough review first would just compound the problem.

**Closed** 2021-01-28 09:21 UTC
Labels: Bug
