### ISSUE TITLE
Upload an image error

### ISSUE THREAD

**Issue by keldeeek** [pkp/pkp-lib#2480] opened 2017-04-28 15:26 UTC
Hello,

Uploading an image in wysiwyg editor doesn't work in OJS 3.0.2.0 with the php error:
PHP Fatal error:  Call to a member function getUserVar() on a non-object in /WebServer/ojs3/data/classes/i18n/AppLocale.inc.php on line 70, referer: http://ojs3.ioffe.ru/plugins/generic/tinymce/plugins/justboil.me/dialog-v4.htm

![screen shot 2017-04-28 at 16 26 16](https://cloud.githubusercontent.com/assets/28147177/25530876/818d8288-2c30-11e7-8902-795e2d16085b.png)

**Comment by asmecher** [comment] 2017-04-28 15:41
This is a duplicate of https://github.com/pkp/pkp-lib/issues/1919 -- I'd suggest adding your feedback there.

**Closed by asmecher** 2017-04-28 15:41 UTC
