### ISSUE TITLE
Consider re-adding subscription settings

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1777] opened 2016-08-31 17:20 UTC
This option doesn't do anything.

![site-access-option](https://cloud.githubusercontent.com/assets/2306629/18139056/9d26f07e-6fa7-11e6-923f-8f27b2036229.png)

**Comment by asmecher** [comment] 2016-08-31 17:22
@stranack, you hit a related one too -- do you have an issue # handy?

@NateWr, this is part of the subscription toolkit which isn't written yet. The option should be removed for now. (I can do it if you're busy -- just FYI.)

**Comment by asmecher** [comment] 2016-08-31 19:19
@NateWr, I hope I didn't pounce on something you were working on, but I removed the option. Will do some checks over here and drop a back-link to this issue so we can revert/assess the previous code when we add subscription support post-3.0.

**Comment by asmecher** [comment] 2016-08-31 20:04
Related, from @stranack:

> This should be modified until we have a subscription module:
>
> Access to Journal Content
>
> OJS provides a number of security-related options that can be used to restrict the journal's contents, and maintain additional information about submissions for auditing purposes.
>
> - The journal will provide open access to its contents.
> - This requires the assignment of a Subscription Manager who has access to the subscription module, which includes additional open access, self-archiving, and email notification options.
> - OJS will not be used to publish the journal's contents online.
>
> Maybe just drop the second option?

I'll handle that too.

**Comment by asmecher** [comment] 2017-07-11 17:08
Dupe of #1816.

**Closed by asmecher** 2017-07-11 17:08 UTC
