### ISSUE TITLE
Consider completed review event in the editorial history

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#3898] opened 2018-07-11 17:09 UTC
s. https://forum.pkp.sfu.ca/t/no-new-emails-are-received-when-a-new-review-is-received/46276/6

**Comment by NateWr** [comment] 2020-05-07 08:20
Duplicate of https://github.com/pkp/pkp-lib/issues/3990

**Closed by NateWr** 2020-05-07 08:20 UTC
Labels: Enhancement
