### ISSUE TITLE
User in Section Editor and Journal Editor role can't schedule for publication when assigned as Section Editor

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#6324] opened 2020-11-09 22:35 UTC
In OJS 3.2.1-1, a user who has both the Journal Editor and Section Editor role, but is assigned to a particular submission as a Section Editor, is not able to assign an article to an issue or schedule it for publication.  In OJS 3.2, a Section Editor doesn't have this permission to schedule for publication.  However, it seems like if the user does have the role of Journal Editor, they should be able to schedule for publication, regardless of which role they have on a particular submission.  Otherwise the user has to reassign themselves to the submission as Journal Editor in order to schedule for publication.  Can this be fixed?

**Comment by NateWr** [comment] 2020-11-10 10:28
A Section Editor should be able to schedule a submission for publication as long as they have access to the Production stage. I'd recommend checking the role configuration to make sure that they have access to that stage.

Regarding the broader question of permitting someone assigned in one role to access functions for another role, there's a rather painful [backstory](https://github.com/pkp/pkp-lib/issues/3130). Long story short: users are only allowed to take actions on a submission based on the role of their participant assignment, _not the role the user has in the journal_.

This is an important distinction to preserve because editors and assistants may play dual roles as authors and reviewers. It is also possible to assign section editor roles that restrict editorial permissions to certain stages, or even assign an editor that does not have permission to edit metadata or make editorial decisions.

Yes, a Journal Editor (`ROLE_ID_MANAGER`) can always leapfrog these restrictions by assigning themselves to a submission in the higher access role. For this reason, we discourage this kind of dual role. But we do provide some guardrails for particularly problematic scenarios, like assigning a Journal Editor as a Reviewer (which unfortunately does happen).

**Comment by amandastevens** [comment] 2020-11-27 17:57
Thanks, Nate, I understand now why it's set up this way.  I remember there being discussion when 3.2 was released about re-allowing Section Editors to schedule articles for publication in an upcoming release. Is that still planned?

**Comment by NateWr** [comment] 2020-11-30 09:46
Section Editors assigned to the submission should be able to schedule articles for publication if the Section Editor role is assigned to the Production stage (in the default role configuration, this is the case).

**Comment by kshuttle** [comment] 2022-01-11 22:47
I have encountered a situation where section editors are not able to assign a submission to an issue without first assigning a journal editor role on the submission, even though the Section Editor role is assigned to the Production stage.

This seems to be happening because the journal _only_ has section editors assigned to each submission, and no other roles (the section editors are assigned to the section, so submissions go straight to the Active queue with the section editors assigned).

To reproduce this issue:

- I confirm that section editors have every stage assignment checked off, and permission to edit metadata.

![image](https://user-images.githubusercontent.com/59741486/149033158-8739cabe-949a-4f3a-9293-7bbada66c5c2.png)

- Submissions come in and are assigned automatically to the Section Editors, with no other users assigned to the submission
![image](https://user-images.githubusercontent.com/59741486/149032858-cbe48139-1d94-46bb-b6f0-042e5c62877e.png)

- I confirm that all section editors automatically have metadata editing permissions turned on
![image](https://user-images.githubusercontent.com/59741486/149032927-6afae98d-276e-43a9-bf10-bfc2a401d56c.png)

- I login as a section editor, move the submission through the workflow, and schedule it for publication, at which point I see the "you do not have access to this stage of the workflow" message.
![image](https://user-images.githubusercontent.com/59741486/149033021-d77e672f-b0c3-4ba5-9059-193b30392f18.png)

A straightforward workaround would be for the section editors to assign a journal editor to each submission that comes in. However, based on the above information it sounds like the section editors should have the ability to send the submissions to production, as long as the section editor role as access to this part of the workflow. Can this be confirmed / clarified?

**Comment by NateWr** [comment] 2022-01-12 10:16
Thanks for the excellent reproduction steps, @kshuttle! I think the problem you're running into is that the section editor you are logged in as (Jones Julie) has the "recommend only" setting enabled. Editors with this setting are not permitted to publish a submission.

(If you look at the screenshot with "Edit Assignment", you'll see that is for a different editor, Julia Lane.)

It seems to me that the "recommend only" setting should only apply to the review stage. So a "recommend only" editor should be able to publish if they are assigned to the production stage and have permission to edit metadata. That said, it kind of goes against the workflow we expect for such editors. A "recommend only" editor is usually not expected to play a deciding or controlling role on the submission. So it may be safer, albeit confusing, to leave the restriction as it is. What do you think?

**Comment by kshuttle** [comment] 2022-01-12 17:44
Thanks @NateWr for weighing in on this!
Unfortunately the section editor is not able to schedule the submission for publication even without the "recommend only" settings turned on.
However, the journal is using OJS 3.2 and we were not able to reproduce the problem in 3.3, so I believe we may be able to close this issue and recommend an upgrade.

**Comment by librariam** [comment] 2022-01-27 14:28
Reopening the issue because I have also encountered this in 3.3.0.8 (and this was after I convinced Kate that it's not a 3.3 issue - sorry @kshuttle!). I can confirm that the Section Editor has all permissions (to edit metadata, record a decision, etc.). They are still getting "you don't have access to this stage" when trying to assign an article to an issue. 

Perhaps it has something to do with the Section Editor not having these permissions at first, and then getting them enabled after they were assigned to the submission?

**Comment by NateWr** [comment] 2022-02-01 16:26
@librariam  was not able to reproduce it last time I tried in 3.3-x. Can you provide steps to reproduce this in the 3.3 demo install, along with screenshots that confirm the permissions of the Participant, as well as the stage assignments of the Role? I

**Comment by kshuttle** [comment] 2022-02-03 01:47
Hi @NateWr,

I made an animated GIFs demonstrating the steps to reproduce this in an OJS 3.3 demo journal. To summarize what's here:
1. I checked the section editor role settings and permissions
2. I checked the section editor was assigned to the appropriate section
3. I logged in as an author (not shown) and uploaded a submission to the section in question
4. I checked the section editor settings in the submission and logged in as the section editor 
5. I sent the submission through to production (skipping review for the purposes of the demonstration), and reached the error message at the end

5. The section editor was not permitted to assign the submission to an issue 
![1-confirm-section-editor-settings](https://user-images.githubusercontent.com/59741486/152267527-916648ee-bd73-459e-963b-dc3bf8cb4cc4.gif)
![2-confirm-section-assigned-editor](https://user-images.githubusercontent.com/59741486/152267532-2f52f98f-887f-47e4-9eeb-460f42927a9f.gif)
![3-upload-submission](https://user-images.githubusercontent.com/59741486/152267535-51aeab6a-1e47-4481-918b-3ab26f6f6398.gif)
 ![4-check-section-editor-again](https://user-images.githubusercontent.com/59741486/152267630-2646c321-c5ab-4dc9-a0a8-1b79695ac1d9.gif)
![5-section-editor-send-to-issue](https://user-images.githubusercontent.com/59741486/152267633-c5ac16a9-0193-4ff7-b0d0-e24b89d45b58.gif)

Let me know if you'd like me to try anything differently with the demo GIFs.

**Comment by NateWr** [comment] 2022-02-03 10:33
Thanks @kshuttle, that helped! So the problem is that the user does not have permission to edit the metadata. If you look at the gif in step 4, you'll notice that the checkbox "Allow this person to make changes" is not checked. If you check this, the editor can publish without an error.

I was able to reproduce this, and the fix, in the [OJS test drive install](https://pkp.sfu.ca/ojs/ojs_demo/). I'm not sure why the Section Editor role is not given this permission by default in the test drive install. It's configured to work that way [by default](https://github.com/pkp/ojs/blob/stable-3_3_0/registry/userGroups.xml#L22) and this change went in [before 3.3 was released](https://github.com/pkp/ojs/commit/4754ea1793005df700b959aea0d94445c389f2b6#diff-25c1a7a22030522d801d1192d390161840aee272f6ebf0a4ed2c92cb2b03d9ee).

@mfelczak is the test drive a fresh installation of 3.3? Or might it have been upgraded from a 3.2 instance? I'm wondering if permissions for this role are missing because they aren't added during an upgrade. That would explain why we have trouble reproducing it on the dev side.

Either way, the UI isn't handling this well. Should a participant who is not allowed to edit metadata be permitted to assign a submission to an issue and publish it? I could see an argument for either way. Thoughts @kshuttle and @librariam?

**Comment by librariam** [comment] 2022-02-12 02:26
@NateWr I did some more tests and can confirm that checking the "allow this person to make changes" checkbox resolves permission assignment issue **EXCEPT** in the following scenario:

- **Section editor is assigned to a submission as a Section Editor, but also has a Journal Manager role with the journal**

In fact, in this case the Section Editor would get a different error at a different step: 

1. Log in as a Section Editor assigned to a submission with the "allow this person to make changes" checkbox not initially checked. Attempt to schedule for publication. When assigning to an issue, you get an error "You are not allowed to edit this publication"

![Error_checkbox_not_checked](https://user-images.githubusercontent.com/45104797/153692374-4fdc126b-3564-457e-a811-c8d77c4684a1.png)

2. Check the "allow this person to make changes". Attempt to schedule for publication. Assigning to an issue works. But when clicking "Schedule for publication" button (or "Publish" if it's a past issue), you get an error "You don't currently have access to that stage of the workflow"

![Error_checkbox_checked](https://user-images.githubusercontent.com/45104797/153692558-bca61727-545f-496b-81ed-d51b7ce6f037.png)

I can confirm that Section Editor role has access to all stages of the workflow. I was able to replicate it in the the [OJS test drive install](https://pkp.sfu.ca/ojs/ojs_demo/) as well as 2 other 3.3 installs, previously upgraded. I could not come up with a workaround other than having a non-assigned JE account publish the article.

This happens most commonly when a journal uses section editor auto-assignment per section to automatically assign accounts that have JM & SE permission. 

To your question on whether a participant who is not allowed to edit metadata should be able to publish, I think this is more a matter of being explicit of what is included in the permission. Currently it's not obvious that metadata editing permission includes the ability to schedule/publish. I think it needs to be added to the current permission wording, so that JE could make an informed decision on permissions (and of course, checking the checkbox should actually fix the issue). 

Current wording:

- Within submission: _"Allow this person to make changes to the publication, such as the title, abstract, metadata and other publication details. You may wish to revoke this privilege if the submission has received a final check and is ready for publication."_
- At the role level: _" Permit submission metadata edit."_

**Comment by asmecher** [comment] 2022-09-14 22:31
@NateWr, unless you have any objections, I'll defer this to 3.3.0-13.

**Comment by NateWr** [comment] 2023-01-24 09:52
This is a duplicate of #6875, which has been fixed. The fix will be available from version 3.3.0-14.

**Closed by NateWr** 2023-01-24 09:52 UTC
Labels: Hosting, Bug:1:Low
