### ISSUE TITLE
[OPS] cannot install plugins from the gallery

### ISSUE THREAD

**Issue by gianfj** [pkp/pkp-lib#8822] opened 2023-03-16 08:41 UTC
**Describe the bug**
Installing plugins from the plugin gallery does not work.

**To Reproduce**
1. Open the plugin gallery
2. Select any plugin
3. Click "Install"
4. The "Are you sure you wish to install this plugin?" dialog opens and clicking in "OK" does not work.

**What application are you using?**
OPS 3.4.0rc1

**Additional information**
Relevant Apache logs:
```
[Thu Mar 16 08:32:18.477250 2023] [php:error] [pid 40] [client 172.31.0.1:60134] PHP Fatal error:  Uncaught UnexpectedValueException: Cannot create phar '/tmp/plugin18rQwH', file extension (or combination) not recognised or the directory does not exist in /var/www/html/lib/pkp/classes/plugins/PluginHelper.php:67\nStack trace:\n#0 /var/www/html/lib/pkp/classes/plugins/PluginHelper.php(67): PharData->__construct('/tmp/plugin18rQ...')\n#1 /var/www/html/lib/pkp/controllers/grid/plugins/PluginGalleryGridHandler.php(318): PKP\\plugins\\PluginHelper->extractPlugin('/tmp/plugin18rQ...', 'shariff-3.4.0.0')\n#2 [internal function]: PKP\\controllers\\grid\\plugins\\PluginGalleryGridHandler->installPlugin(Array, Object(APP\\core\\Request))\n#3 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\\core\\Request))\n#4 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\\core\\Request), Array)\n#5 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\\core\\PKPComponentRouter->route(Object(APP\\core\\Request))\n#6 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))\n#7 /var/www/html/index.php(21): PKP\\core\\PKPApplication->execute()\n#8 {main}\n  thrown in /var/www/html/lib/pkp/classes/plugins/PluginHelper.php on line 67, referer:https://ops.testing.publicknowledgeproject.org/
```

**Comment by jonasraoni** [comment] 2023-03-16 09:30
Closed as a duplicate of https://github.com/pkp/pkp-lib/issues/8723

**Closed** 2023-03-16 09:31 UTC
