### ISSUE TITLE
[OPS] Version number showing Publication ID for authors

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6056] opened 2020-06-30 17:16 UTC
**Describe the bug**
Version numbers are showing the Publication ID (instead of actual version numbers) when viewing as an author.

**To Reproduce**
1. Login as the author of a preprint that is already posted
2. Create a new version as an author
3. Notice how the version numbers are not showing as 1, 2, 3, but showing other numbers that match Publication ID

**What application are you using?**
OPS 3.2.1

**Additional information**
![image](https://user-images.githubusercontent.com/4059679/86156412-4b78c980-badc-11ea-9549-f071110509ff.png)

**Comment by JhonathanLepidus** [comment] 2020-07-01 19:31
This problem also occurs for me. It's simple to solve, so, if approved, we could send a PR.

**Comment by NateWr** [comment] 2020-07-02 09:54
@JhonathanLepidus yes, please, we'd love to have a PR! I've confirmed it on my end.

**Comment by JhonathanLepidus** [comment] 2020-07-02 16:19
We sent two PRs, since it was necessary changes in *ops* and *pkp-lib*

You could check them: [#6063](https://github.com/pkp/pkp-lib/pull/6063), [#51 ](https://github.com/pkp/ops/pull/51)

**Comment by JhonathanLepidus** [comment] 2020-07-02 16:22
We should also send these modifications to *stable-3_2_1* branchs?

**Comment by NateWr** [comment] 2020-07-06 11:31
Thanks @JhonathanLepidus! Yes, if you can create a PR to the `stable-3_2_1` branches as well that'd be great. If not we can cherry-pick it in for you but we prefer to have a PR.

I notice that there is a merge conflict with the OPS PR. This happens when your copy of the `master` branch is a little out of date and there are new commits that cause a conflict. You can resolve this by syncing your `master` branch and rebasing your branch.

Finally, the last thing we need to do is to kick off the tests. Because changes occur across pkp-lib and ops, you'll need to add a submodule commit to make sure the tests run across the correct branch of the pkp-lib submodule. You can find more details in our testing documentation:

https://docs.pkp.sfu.ca/dev/testing/en/continuous-integration#tests-for-pull-requests

Let me know if you have any questions about this.

**Comment by JhonathanLepidus** [comment] 2020-07-07 20:31
I made a syncing in my OPS branchs and added the submodule commit. I made a new PR (https://github.com/pkp/ops/pull/52) that passed in the tests.

**Comment by NateWr** [comment] 2020-07-08 09:10
Thanks @JhonathanLepidus! It looks like the `.gitmodules` got updated by mistake in the PR (https://github.com/pkp/ops/pull/52/files#diff-8903239df476d7401cf9e76af0252622R3). I've replaced that with a new one at https://github.com/pkp/ops/pull/53 which just applies the submodule commit against pkp/pkp-lib.

This can be a headache to get set up right for local dev, but usually I leave the `.gitmodules` as is, and just go directly into `lib/pkp` and set up different git remotes there.

I'm happy to talk you through it if you want but I thought I'd do the PR so that this small bug fix didn't turn into a monumental git headache.

PRs:
https://github.com/pkp/pkp-lib/pull/6063
https://github.com/pkp/ops/pull/53/

**Comment by NateWr** [comment] 2020-07-08 10:18
Merged and backported to `stable-3_2_1`.

**Closed by NateWr** 2020-07-08 10:18 UTC
Labels: Bug

**Comment by JhonathanLepidus** [comment] 2020-07-08 12:25
Thank you very much!
