### ISSUE TITLE
Tag-it submission metadata fields broken in master branch of OMP

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4828] opened 2019-06-12 18:07 UTC
When editing submission metadata fields that are keyword-related, the fields cannot be interacted with. (They appear to be read-only.)

**Comment by asmecher** [comment] 2019-06-13 00:15
Also OJS master, apparently.

**Comment by NateWr** [comment] 2019-06-17 12:00
Recommend not addressing this for now, unless it needs to be fixed in a stable version. In 3.2 the controlled vocab metadata fields will be converted to the new forms system.

I'll keep this pegged to 3.2 so that we make sure it is resolved when the expected changes for versions/publications are in place.

**Comment by asmecher** [comment] 2019-06-17 16:02
:+1: Thanks, @NateWr, that's fine. There are no issues with this in any stable release that I'm aware of.

**Comment by asmecher** [comment] 2019-06-17 16:02
(FYI @defstat, who mentioned this to me in the first place)

**Comment by NateWr** [comment] 2019-10-22 13:31
These fields have been changed in the workflow UI, but we still use the old tag-it fields in the submission process. So I think this will still need to be addressed.

**Comment by NateWr** [comment] 2020-01-08 11:23
Closing as fixed. Editing metadata fields after submission is now handled separately and I couldn't reproduce this issue during submission with current `master`.

**Closed by NateWr** 2020-01-08 11:23 UTC
