### ISSUE TITLE
Published Article and meta data can be changed by authour after published.

### ISSUE THREAD

**Issue by streslibaba** [pkp/pkp-lib#4234] opened 2018-11-14 12:04 UTC
Hi
Published Article and meta data can be changed by authour after published in OJS (3.1.1.4)
There is same problem in all archieves.
How can fixed it?

**Comment by asmecher** [comment] 2018-11-20 18:00
@bozana, would you mind taking a look at this? Thanks!

**Comment by bozana** [comment] 2018-12-10 14:17
Hi @streslibaba, I've just tested it with my local installation, using ojs-stable-3_1_1 branch (which should be the same as the 3.1.1.4 release) and I could not reproduce it :-\ As author I can view the article metadata but the form fields are read-only i.e. I cannot edit/change them.
Could you maybe send me some more explanation and/or a screenshot where you can edit the metadata as author and/or if there is something special about the articles and/or...

**Comment by bozana** [comment] 2019-01-31 09:39
I cannot reproduce this. Can anybody else?
Else, I would close this issue until someone provides more information...

**Comment by asmecher** [comment] 2019-01-31 18:15
Closing -- this needs feedback from someone who can replicate the problem.

**Closed by asmecher** 2019-01-31 18:15 UTC
