### ISSUE TITLE
[OJS 3.3.0.3] Unassigned submission list not working

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#6979] opened 2021-04-22 12:47 UTC
The Unassigned tab is blank, even though I have unassigned submissions in my Active tab.

![image](https://user-images.githubusercontent.com/18707781/115716136-3f9e1280-a34f-11eb-8567-113f92cad7d9.png)

![image](https://user-images.githubusercontent.com/18707781/115716473-986dab00-a34f-11eb-9dab-ef06ef5ecf65.png)

This is happening in all journals, and with every editor.

**Comment by asmecher** [comment] 2021-04-23 16:15
@luizbgomide, were there any administrative actions that resulted in this, e.g. did you recently upgrade?

**Comment by luizbgomide** [comment] 2021-04-23 16:19
I noticed it some weeks ago, a the last thing I've done was the update from OJS 3.3.0.1 (i think, but it was definitely 3.3) to 3.3.0.5 in February.

Before that it was working

**Comment by asmecher** [comment] 2021-04-23 18:05
@luizbgomide, were there any issues with the upgrade? (Did it confirm a successful upgrade at the end of the process?)

Could you try (perhaps on a test machine) updating the code to the latest 3.3.0 release? (It'll be database-compatible with 3.3.0-3, so no need to run the upgrade script again.) I'd like to confirm that the issue still exists in the latest code before debugging further.

**Comment by luizbgomide** [comment] 2021-04-23 18:19
Yes, there were no errors. Attached is the result from the migration.

Is was hoping to wait for 3.4 to update since I don't have another database available for testing, but I could try to setup a temporary installation for testing if the database is compatible.

[ojs upgrade.txt](https://github.com/pkp/pkp-lib/files/6367335/ojs.upgrade.txt)

**Comment by asmecher** [comment] 2021-04-23 19:45
@luizbgomide, that would be helpful -- there are a number of small bugs fixed since 3.3.0-3 that might be related, and I can confirm that 3.3.0-3 and 3.3.0-5 are database-compatible.

**Comment by luizbgomide** [comment] 2021-04-26 11:23
@asmecher, I just tested with 3.3.0-5 and still nothing on the Unsassigned tab. Let me know if you want me to do any more tests...

**Comment by NateWr** [comment] 2021-04-26 11:27
I had a look at the code to see if I could detect any discrepancy between how submissions are put into the unassigned list and how the notice "no editor has been assigned" is shown. But I couldn't find any. They both seem to check against any `ROLE_ID_MANAGER` and `ROLE_ID_SUB_EDITOR` assignments.

@luizbgomide can you inspect the `stage_assignments` database table for one of the submissions to determine what `stage_assignments` exist for that submission. Maybe this will give us a clue as to what's going on under the UI.

**Comment by luizbgomide** [comment] 2021-04-26 11:41
@NateWr, here it is the data on our latests submissions, the ones marked in red are all from the same journal (the one from the screenshots above) and I verified that there is no assignment done to them.
![image](https://user-images.githubusercontent.com/18707781/116076785-12ad7080-a66b-11eb-8b78-3bd1b8078646.png)

**Comment by NateWr** [comment] 2021-04-26 11:54
I can reproduce this issue in the `main` branch by unassigning editors from an active submission..

**Comment by luizbgomide** [comment] 2021-04-26 12:00
@NateWr this is odd, that seems to be the default behaviour in my server when a submission is created (so no assigning then unassigning involved).

**Comment by NateWr** [comment] 2021-04-26 13:03
> this is odd, that seems to be the default behaviour in my server when a submission is created (so no assigning then unassigning involved).

It depends on whether you have section editors assigned to sections. If so, then they will be auto-assigned when the submission is completed. Either way the bug is the same: when no editors are assigned, the submission should appear in the Unassigned list, but it doesn't.

**Comment by asmecher** [comment] 2021-04-26 15:02
@NateWr, see also: https://forum.pkp.sfu.ca/t/ojs-3-3-0-4-new-submission-in-unassigned/67225/7

**Comment by asmecher** [comment] 2021-04-26 18:40
This is a side-effect of https://github.com/pkp/pkp-lib/issues/5982 -- the `assignedTo` parameter when calling the submission query builder's `getMany` used to be `-1` for "unassigned", but now it is `[-1]`. Should be quick to fix.

**Comment by asmecher** [comment] 2021-04-26 19:36
@NateWr, does this look OK?

pkp-lib: https://github.com/pkp/pkp-lib/pull/6996/files
OJS (tests only): https://github.com/pkp/ojs/pull/3121

**Comment by asmecher** [comment] 2021-04-26 19:36
(Others are welcome to confirm the fix by applying https://github.com/pkp/pkp-lib/pull/6996/commits/593797894cf766725bf08c7d4e750128e09facf7 in the `lib/pkp` subdirectory.)

**Comment by primoz-svetek** [comment] 2021-04-27 06:09
@asmecher Thank you for the fast response and the bugfix. I have tested it on my instance and can confirm that it works.

Though it is interesting to me that this bug was present in few versions for a few months already and nobody noticed it. But it is fixed now.

Thank you very much!

**Comment by primoz-svetek** [comment] 2021-04-27 06:26
Hm, maybe to fast fix confirmation:
- it is true that now the unassigned submissions are listed under the Unasssgined tab, which is correct
- but on the contrary with the past version there seems that there are listed also submissions that are in the archive (either published or declined) - so not active

Please let me know your opinion on that.

**Comment by NateWr** [comment] 2021-04-27 09:38
@asmecher yes, this looks good. In hindsight, I don't like mixing types in this way, but that's something I'll fix with the typehinting stuff that I'm working on.

The one thing I might suggest is testing the whole array and returning an error message if they've mixed types (eg - `[23, -1]`). I would normally do that in the API's handler op. So I'd leave the param as-is in the switch-case without forcing the changed type, then after the hook call do:

```
if (isset($param['assignedTo']) && in_array(-1, $param['assignedTo']) && count($param['assignedTo']) > 1) {
  return $response->withStatus(403)->withJsonError('...');
}
```

But I think since I'll try to refactor this mixed types thing in `main` anyway there's no need.

**Comment by NateWr** [comment] 2021-04-27 09:42
> but on the contrary with the past version there seems that there are listed also submissions that are in the archive (either published or declined) - so not active

@primoz-svetek can I confirm: submissions that are declined or published are appearing in the unassigned list? Looking at the code, it should only return submissions with `STATUS_QUEUED` (a `status` of `1` in the database).

**Comment by primoz-svetek** [comment] 2021-04-28 15:40
@NateWr  You are right, I checked the DB and the 'problematic' submissions have the `status` set to `1`. I guess this means the fix is OK and the status of the submissions is inconsistent in our DB. I think they used to 'import' some older/past submissions automatically in the OJS and this might be a side effect of that. Will check.
Sorry to bother you with that and once more thank you for your help.

**Closed** 2021-04-28 18:21 UTC
Labels: Bug
