### ISSUE TITLE
List of volumes not generate by the OJS 3.x LOCKSS gateway plugin

### ISSUE THREAD

**Issue by mjordan** [pkp/pkp-lib#4274] opened 2018-11-30 14:26 UTC
Adam Rusbridge at University of Edinburgh reported this issue with the OJS 3.x LOCKSS plugin (this is for the standard LOCKSS plugin). Here is Adam's report:

> I’ve spotted a bug in OJS3: after selecting the checkbox for LOCKSS archiving, the list of LOCKSS volumes are not generated.  There’s an iterate block in this template that should produce some code: https://github.com/pkp/ojs/blob/0c7aafabcdf12dd896784e2dca77c5c94782c127/templates/gateway/lockss.tpl

> However, no volumes appear.  This can be reproduced by logging into the test-drive instance, selecting the LOCKSS option and navigating to: https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php/journal/gateway/lockss?year=2017

Alexandra Ohlson at Stanford also reported behavior to me that is consistent with this issue.

Unfortunately, when I visit the testdrive journal, I get a "Service temporarily unavailable" response. I can try later but if someone else can replicate, that would be great.

**Comment by asmecher** [comment] 2018-11-30 16:59
@mjordan, marking this a duplicate of https://github.com/pkp/pkp-lib/issues/1908 -- essentially that code hasn't been maintained since the OJS 3.x update, and needs an overhaul.

**Closed by asmecher** 2018-11-30 16:59 UTC
