### ISSUE TITLE
OJS 3.3cr Error on access to another stage has unrelated content

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#6560] opened 2021-01-10 15:21 UTC
**Describe the bug**
Not sure if this is a byproduct of testing in the sandbox. When accessing a stage I don't have access to, an error pops up as it should but it has a long URL that isn't there in the current version.

![image](https://user-images.githubusercontent.com/45104797/104126957-6cdd2c80-532d-11eb-8737-a6246cca1d4d.png)

**What application are you using?**
OJS 3.3cr

**Comment by NateWr** [comment] 2021-01-11 14:26
I can see this is happening on the test instance, but I can't reproduce it locally. 

@israelcefrin do you know if there is any customization or configuration of the test instance that might be adding the request URL to an authorization failure message? It looks like this comes back in the response as part of the `content`, so it's definitely something being added on the server side.

The URL that appears is the requested URL (where the request is sent when you click on a workflow tab).

**Comment by israelcefrin** [comment] 2021-01-11 14:35
@NateWr  I will check the install, but no customization is applied to these installations. Maybe it could be related to this RC, I have to update to the most current master branch.

**Comment by israelcefrin** [comment] 2021-01-11 22:08
@librariam could you please re-run these tests to double-check whether it has been fixed?

**Comment by librariam** [comment] 2021-01-12 02:02
@israelcefrin Yes! I can confirm this is now fixed after you upgraded the 3.3 rc testing

**Comment by israelcefrin** [comment] 2021-01-12 02:06
@NateWr  I will close this issue since it was fixed by deploying the newest code from the master branch.

**Closed by israelcefrin** 2021-01-12 02:06 UTC
