### ISSUE TITLE
Fix submission language/languages metadata

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#5000] opened 2019-08-14 18:40 UTC
The Submission class offers getLanguage/setLanguage methods. This metadata is used occasionally e.g. in exporting to 3rd-party metadata formats. The data is stored non-localized in a plain text form.

The submission metadata form, however, uses a controlled vocabulary offering auto-complete and the selection of several languages.

Reconcile the two so that only one method is used, and remove the other.

**Comment by NateWr** [comment] 2019-08-15 09:20
Yes, this has been one of the questions that arose for me as part of #4863. Should language be a single text field rather than an autocomplete?

**Comment by asmecher** [comment] 2019-08-18 01:30
@AhemNason, this might be a good question for you/the metadata working group. Got a best practice to suggest? Single value or multiple? Autocomplete? If autocomplete, then by what standard? (What about letting language information come from the galley, which already has a locale attribute?)

**Comment by NateWr** [comment] 2019-08-19 13:32
I've put this into the Versioning project because it's very easy to sort out with the new schema/form coming for the controlled vocab. But if we don't get an answer in time we can pull it back off.

**Comment by NateWr** [comment] 2019-08-20 14:14
A future note: when a decision is made the GoogleScholarPlugin metadata may need to be updated to reflect the new data structure.

**Comment by AhemNason** [comment] 2019-09-25 18:31
Hey! I asked Monica Westin at Google Scholar for some feedback here and her commend is as follows: 

> I highly recommend autocomplete rather than a text field for entering language metadata. In terms of standards, ISO 639-1 language codes would be best for indexing. (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

That seems like a solid recommendation. I also intend to dig around a little more for other inputs but consider that a jumping off point.

**Comment by asmecher** [comment] 2019-09-25 19:24
The autocomplete in the submission metadata form already uses ISO639-1, so that's a good nudge in that direction. What about the selection of one vs. several?

**Comment by NateWr** [comment] 2019-09-26 09:34
> What about the selection of one vs. several?

Yeah, this is the key question. Should this field always indicate _one_ language or can it indicate _more than one_ language?

**Comment by AhemNason** [comment] 2019-10-04 16:14
Monica says: 

“ One language, please. :) For indexing purposes, metadata should only be written in one language (the language of the fulltext). Multilinguals in metatags are a common source of indexing errors. I can't think of a use case when it would be a best practice to include metadata for a single article in multiple languages.”

**Comment by NateWr** [comment] 2019-10-04 16:49
Ok, after some chatting with Mike about this, we've established a couple things:

1. Language metadata should only ever be one language code (`en`).
2. This language code should not be a multilingual field. Whether viewing a submission in English or French, the language code should stay the same.

As far as I can tell, that means that the language metadata is obsolete. We already track a `locale` for each submission. Whenever we are using language metadata, it should be derived from this `locale`, rather than a separate language field. So I recommend we get rid of language metadata and convert any usage over to the `locale`.

The downside here is that it will not be possible for one work to be described as being in two languages. That's what Google Scholar wants, but @AhemNason is going to check with Crossref to see if that fits their expectations as well.

@asmecher do you have any thoughts on this?

**Comment by AhemNason** [comment] 2019-10-04 17:07
From Crossref: 

> Hello! We use the ISO 639 standard for flagging language, the alpha 2 code. We have the code in our schema as an enumerated list so it needs to be updated periodically when the standard changes (only happens every 5 years or so)

>There is also an xml:lang attribute that uses ISO 639 values that we use in some places - according to the XML spec xml:lang is used to flag the language used in the XML fields, not the language of the document the XML refers to, but we use it to define the language used in titles, abstracts, etc. within our metadata

**Comment by asmecher** [comment] 2019-10-18 20:05
Using the `submissions.locale` column to replace the various other metadata fields looks like the most promising solution, but it does have a few problems...
- The `submissions.locale` column is not intended to answer the question, "What language is this submission in?" It only defines what the *primary* language of the submission is, i.e. what language the required fields must be completed in. (This subtlety is probably lost on pretty much everyone who uses OJS, so perhaps we can overlook it.)
- Multilingual journals sometimes *do* have one article with a galley for each publication language -- there is a `locale` column in `submission_galleys` (pre-3.2) or `publications` (post-3.2) to identify the language of the full-text.
- Both the `submissions.locale` and `submission_galleys.locale`/`publications.locale` columns are limited to one of the languages that have OJS translations. If we use one of those options, journals that contain articles that are written in some language without an OJS translation will not be able to indicate which language accurately.

**Comment by NateWr** [comment] 2019-10-21 09:31
Hmm, ok... I _think_ that we can safely ignore the second issue as well, since that specifies the galley locale, and the languages metadata as it currently is doesn't apply to galleys at all. If a language is specified for a galley, it is done through the `locale` field.

That leaves us with the last one, which is tricky. So, one option is to leave the Languages metadata in, but change it to a select dropdown so only one language of a specified set can be selected. Then, when a publication is created, we can set the language to the locale (if the metadata is enabled).

That way, in most cases editors don't need to do anything with the language metadata but it's there in cases where the primary language needs to be identified separately.

We can write an upgrade script to set the language metadata for publications without it.

The last thing that needs to happen is the consistent use of this data in metadata distribution. At the moment, the Google Scholar tags use the languages metadata but do not fall back to `locale`. The DataCite and Medra exports seem to use languages but fall back to `locale` if it's not specified. And the DOAJ export uses `locale` and never checks for languages metadata.

At the moment, I'm leaning towards removing this from the 3.2 milestone, because as things currently stand the versioning changes will not affect this. So at the very least 3.2 won't be a regression.

Does that sound alright?

**Comment by NateWr** [comment] 2019-10-25 11:46
> At the moment, I'm leaning towards removing this from the 3.2 milestone, because as things currently stand the versioning changes will not affect this. So at the very least 3.2 won't be a regression.

@asmecher are you alright deferring this to after 3.2?

**Comment by asmecher** [comment] 2019-10-25 17:37
Yes, that's fine with me.

**Comment by isgrim** [comment] 2020-08-12 08:19
Just adding one more use case here. "Ancient" languages:

https://forum.pkp.sfu.ca/t/latin-for-article-language/62245

**Comment by isgrim** [comment] 2020-08-12 08:43
And at least for OMP, we have a submission with multiple equal languages. Each chapter is written in Chinese and French.

**Comment by asmecher** [comment] 2020-08-12 13:51
> "Ancient" languages

There's a recent thread in the forum about this, and a suggested work-around: https://forum.pkp.sfu.ca/t/latin-for-article-language/62245/3

**Comment by isgrim** [comment] 2020-08-13 11:34
Dear Alec @asmecher,

Sorry for the confusion. Daniela Wolf (UBWolf) in the forum, is also working on OJS and OMP in the University Library. That's how I knew about the thread and mentioned it here for the record and future discussions.

**Comment by akerbeltz** [comment] 2020-12-22 14:30
This isn't just about ancient languages. We have a similar issue just now in that one of the academic journals we're moving onto OJS accepts articles in English, Scots Gaelic and Irish. We've done enough of the translations for Scots Gaelic but we can't translate the Irish files just so that we can mark articles which are published in Irish as being in Irish, not got the budget for that.
Site admins should be able to manually add ISO locales for their journals for marking the language a paper/article is in when that's a language not supported otherwise by OJS.

**Comment by asmecher** [comment] 2023-10-17 18:39
@bozana, I think you're already working on those PRs, but just in case.
Thanks, @jyhein!

**Comment by bozana** [comment] 2023-10-19 10:29
Hi @jyhein, I went through the PRs and left just a few comments. 
I think also OPS would need to be adapted (Dc11SchemaPreprintAdapter), and the plugins citationStyleLanguage and quickSubmit (let me know if you could also consider these plugins). 
I am a little bit confused about OMP -- I wrote a question in the chat about that -- that we are not able to find out in which languages a book is published after removing the 'languages' metadata field. Maybe there is also no actual need for it... -- I am wondering how the users use it all... So lets see what the users say...

**Comment by bozana** [comment] 2023-11-22 14:03
Hi @jyhein, I tool a new look, and the changes looks good now.
Would you be able to adapt the CitationStyleLanguagePlugin as well?
Once you rebase pkp-lib and add new submodules (pkp-lib and citationStyleLanguage), and when the tests pass, we can merge... 
Thanks a lot!

**Comment by bozana** [comment] 2023-11-28 17:02
Thanks a lot @jyhein! All merged! :tada: 
I will thus close the issue...

**Closed by bozana** 2023-11-28 17:02 UTC
Labels: Enhancement:1:Minor

**Comment by ajnyga** [comment] 2024-05-04 19:45
probably just an oversight

**Comment by asmecher** [comment] 2024-05-04 20:23
:+1: Rescheduled for 3.5.0 LTS.
