### ISSUE TITLE
[OJS PostgreSQL] Email duplication during user registration by changing lowercase to uppercase

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#7249] opened 2021-09-01 12:44 UTC
**Describe the bug**
In the user registration form (/user/register) with PostgreSQL (or MySQL with binary "collate", for example COLLATE 'utf8_bin') it is possible to register a second user with the same email different only for upper/lower case.

**To Reproduce (use OJS with PostgreSQL)**
1. Go to '/user/register'
2. Register a new user with the same email as an existing user but with the first letter capitalized
3. See that there is no error and that the user is created

**What application are you using?**
 OJS version 3.3.0-6 with PostgreSQL

**Additional information**
I see that in:
https://github.com/pkp/pkp-lib/blob/9d5879142980a9219d0fbce961fb5e16d810f955/classes/user/form/RegistrationForm.inc.php#L58
call method userExistsByEmail at 
https://github.com/pkp/pkp-lib/blob/9d5879142980a9219d0fbce961fb5e16d810f955/classes/user/UserDAO.inc.php#L515-L522
A simple comparison is used there without e.g. the SQL function **lower()**

**Note**: I believe the same problem occurs with the "**username**" field calling the **userExistsByUsername()** method

---
**Current PRs**

**Branch `stable-3_3_0`**
Changes will not be applied.

**Branch `main`**
ojs: pkp/ojs#3525 (MIGRATIONS AND TESTS ONLY)
omp: pkp/omp#1212 (MIGRATIONS AND TESTS ONLY)
ops: pkp/ops#362 (MIGRATIONS AND TESTS ONLY)
pkp-lib: #8227

**Comment by NateWr** [comment] 2021-09-01 14:24
It looks like email addresses _can_ be case-sensitive (see [here](https://stackoverflow.com/questions/9807909/are-email-addresses-case-sensitive)), but I agree it's probably a bad idea. Usernames definitely shouldn't be case-sensitive.

**Comment by defstat** [comment] 2022-08-29 11:37
@asmecher @NateWr 

I was able to reproduce the issue by using a PostgreSQL DB. I am proposing the following changes:

1. The usernames are not allowed, by the form checks, to have uppercase characters. I propose that the emails are also not allowed to contain uppercase characters. I created a new distinct Validation rule for that, to check only for uppercase characters.
2. The `userExistsByUsername` and `userExistsByEmail` could change the provided value to lower case and check against the DB with the lowercase value
3. A migration should be created to change the already existing emails and usernames to lowercase. I am not sure how to deal with possible same email users (after the migration).

**Comment by NateWr** [comment] 2022-08-29 11:40
We shouldn't place limitations on the end-user. If we decide to save emails/usernames in all lowercase, that shouldn't impact the user. They should be able to enter MyEmail@SomeDomain.com and have that work, even if we treat it the same as myemail@somedomain.com.

**Comment by defstat** [comment] 2022-08-29 11:45
I am wondering: if the emails are allowed to be case-sensitive, and we allow the user to enter [MyEmail@SomeDomain.com](mailto:MyEmail@SomeDomain.com), (and decide to keep the email as lowercase) shouldn't we, at least, inform the user that the email that we are keeping is not [MyEmail@SomeDomain.com](mailto:MyEmail@SomeDomain.com) but [myemail@somedomain.com](mailto:myemail@somedomain.com)?

**Comment by NateWr** [comment] 2022-08-29 12:12
To the user it shouldn't matter. Whether they enter MyEmail@SomeDomain.com or myemail@somedomain.com or myemAil@sOmEdomaiN.com we should treat it the same.

> if the emails are allowed to be case-sensitive

They shouldn't be case sensitive. We should ignore case.

**Comment by defstat** [comment] 2022-08-29 12:38
Should the user see in the UI the email, the way he has added it in the first place? I mean he adds MyEmail@something.com in the registration form. Should he see MyEmail@something.com in his contact form, or it's ok to see myemail@something.com. also, where should the system send emails to the user? To MyEmail@something.com or to myemail@something.com.

**Comment by NateWr** [comment] 2022-08-29 13:03
I think it's ok to show them the lower-case email. I think it's pretty rare to see it in the UI.

**Comment by defstat** [comment] 2022-08-31 10:29
@eniocarboni thanks for reporting that. Could you check whether the fixes proposed [here](https://github.com/pkp/pkp-lib/pull/8226) solve your issue?

**Comment by defstat** [comment] 2022-09-19 17:12
@asmecher there are 2 PRs, for `stable-3_3_0` and `main` branches for that in the [top ](https://github.com/pkp/pkp-lib/issues/7249#issue-985106696) comment. for review

**Comment by asmecher** [comment] 2022-09-20 16:08
I've added comments to both main and stable-3_3_0 PRs, but I don't think this one actually needs to be ported to stable-3_3_0 -- especially since we're not doing database changes between builds.

**Comment by defstat** [comment] 2022-09-26 17:18
@asmecher I pushed the review changes for the `main` branch.

**Comment by defstat** [comment] 2022-10-21 07:59
Thanks @asmecher. I have resolved the review issues and PR is ready for another review round.

**Comment by defstat** [comment] 2022-10-22 06:36
@asmecher I corrected the class documentation for both migrations.

**Comment by asmecher** [comment] 2022-10-25 22:43
All merged -- thanks, @defstat!

**Closed by asmecher** 2022-10-25 22:43 UTC
Labels: Bug:1:Low
