### ISSUE TITLE
Unexpected error message after trying to close modal window

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8059] opened 2022-07-01 11:05 UTC
**Describe the bug**
When adding a discussion, if the user types something, then attempt to close the modal by clicking outside it, an error message will be shown whenever he tries to continue the process.

**To Reproduce**
1. Access a submission
2. Click on the button `Add discussion`
3. Fill at least one field
4. Click outside the modal
5. The interface will display a prompt to confirm
6. Click on the `Cancel` button
7. Click on the button `Ok`, `Upload File` or `Select Files`
8. A message `Invalid discussion.` should appear in an alert

**What application are you using?**
OJS 3.3.0

**Comment by NateWr** [comment] 2022-07-20 13:52
@asmecher I'm hitting a test failure with a JS error that should be fixed in the PR. Is there any chance that the tests are not building pkp.min.js?

I noticed that in the travis script `buildjs.sh` is only called for the validation tests, not for the integration tests. Do I need to be committing a compiled copy of `pkp.min.js` to use those changes in the tests?

This is the test failure and the JS error it reports is precisely what the PR fixes:

https://app.travis-ci.com/github/pkp/ojs/jobs/577212857#L13841

**Comment by asmecher** [comment] 2022-07-20 16:48
The javascript build is only necessary in the `validation` phase because `enable_minified` is `Off` in `config.inc.php` -- so OJS should be using the various JS classes directly rather than through the compiled JS. You could verify this by committing an updated version of `pkp.min.js` in your OJS branch (before the submodule commit`).

**Comment by NateWr** [comment] 2022-07-21 07:29
The error message I'm receiving suggests that `pkp.min.js` is being loaded:

https://app.travis-ci.com/github/pkp/ojs/jobs/577212857#L13848-L13857

```
Cannot set properties of undefined (setting 'closePermitted')
at a.pkp.controllers.form.FormHandler.containerCloseHandler (http://localhost/js/pkp.min.js?v=3.3.0.11:214:141)
```

I've tried to use `buildjs.sh` to build `pkp.min.js`, but I get several validation errors that aren't related to any changes I've made. I'm running:

> $ lib/pkp/tools/buildjs.sh

And I get the following output:

[buildjs-output.txt](https://github.com/pkp/pkp-lib/files/9157138/buildjs-output.txt)

This doesn't seem to match what the validation test output looks like:

https://app.travis-ci.com/github/pkp/ojs/jobs/577212851

Any ideas?

**Comment by NateWr** [comment] 2022-08-02 10:37
Thanks @asmecher for the `pkp.min.js` file. The tests are passing now. I've realized that I need to commit a new `pkp.min.js` file to OMP and OPS too, and these are probably slightly different.

When you get a chance, can you generate the `pkp.min.js` files for OMP/OPS based on the pkp-lib change? You can either pass those to me or just commit them directly and merge the OJS PRs. I can then forward-port the changes to `main`.

**Comment by asmecher** [comment] 2022-08-02 19:09
I'll send these to you on Mattermost shortly!

**Comment by NateWr** [comment] 2022-08-04 12:41
All merged to `stable-3_3_0` and the appropriate commits cherry-picked forward to `main`. Thanks @asmecher for the assist!

**Comment by asmecher** [comment] 2022-08-05 20:32
@NateWr, this appears to have broken testing on the `main` branch -- the discussion test is failing. Could you have a look?

**Comment by NateWr** [comment] 2022-08-08 10:25
I've fixed the error reported in the test log. However, the `main` branch is currently failing on the OAI tests and I'm not able to reproduce that test failure. I'll check back on this in a few days, but let me know if the discussions tests are still failing after the OAI tests have been fixed.

**Comment by NateWr** [comment] 2022-08-09 11:11
It seems like discussions are _very_ broken in the `main` branch right now and it's not related to this issue. I've filed that at https://github.com/pkp/pkp-lib/issues/8141 and will close this as fixed.

**Closed by NateWr** 2022-08-09 11:11 UTC
Labels: Bug:1:Low
