### ISSUE TITLE
Switching language during submission process exits from the submission workflow

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#8763] opened 2023-03-08 03:11 UTC
**Describe the bug**
When user toggles the language during the submission process they will redirected to the site-wide initial page, they will even leave the dashboard.

**To Reproduce**
1. Go to any submission
2. Click on  top right profile icon and switch to any other language
3. See error (redirected elsewhere from the submission wizard)

**What application are you using?**
OJS version 3.4.0rc1

**Additional information**

https://user-images.githubusercontent.com/4992902/223610099-37259589-5e01-4abe-af8d-1e2c3d4ecca0.mp4

**Comment by Vitaliy-1** [comment] 2023-03-09 10:17
I'm unable to reproduce this issue on our dataset.
@israelcefrin, is it a clean install or an upgraded instance? Looking at the [PKPUserHandler::setLocale](https://github.com/pkp/pkp-lib/blob/0446b8628322deaf2a810ca6678e38a1a640161c/pages/user/PKPUserHandler.php#L40) such behviour could be observed when:
- Locale isn't valid. E.g., the OJS code regarding locales got mixed up; I recall the most recent issue, that may contribute to such effect: https://github.com/pkp/pkp-lib/issues/8598  
- Locale isn't supported by a context or site, e.g., a bug during upgrade (if it's upgraded instance)

**Comment by asmecher** [comment] 2023-03-23 15:49
@israelcefrin, just a reminder on this one!

**Comment by israelcefrin** [comment] 2023-03-23 15:51
Hi @Vitaliy-1 I was using the OJS 3.4rc testing install, which I assumed it was a clean one.

**Comment by NateWr** [comment] 2023-03-28 16:46
I'll go ahead and close this and we can reopen it if we get reproduction steps.

**Closed by NateWr** 2023-03-28 16:46 UTC
Labels: Bug:1:Low, 3.4.0rc1 Internal Testing
