### ISSUE TITLE
[OJS] update from 3.2 to 3.3 error

### ISSUE THREAD

**Issue by sworld-guy** [pkp/pkp-lib#6709] opened 2021-02-03 09:11 UTC
Please help with this:
[Wed Feb 03 08:49:26.024616 2021] [fcgid:warn] [pid 23030] [client 144.76.3.131:52974] mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to a member function getConnection() on null in /var/www/www-root/data/www/sworldjournal.com/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74
[Wed Feb 03 08:49:26.024656 2021] [fcgid:warn] [pid 23030] [client 144.76.3.131:52974] mod_fcgid: stderr: Stack trace:
[Wed Feb 03 08:49:26.024661 2021] [fcgid:warn] [pid 23030] [client 144.76.3.131:52974] mod_fcgid: stderr: #0 /var/www/www-root/data/www/sworldjournal.com/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php(200): Illuminate\\Database\\Capsule\\Manager::connection()
[Wed Feb 03 08:49:26.024664 2021] [fcgid:warn] [pid 23030] [client 144.76.3.131:52974] mod_fcgid: stderr: #1 /var/www/www-root/data/www/sworldjournal.com/lib/pkp/classes/db/DAO.inc.php(65): Illuminate\\Database\\Capsule\\Manager::__callStatic('raw', Array)
[Wed Feb 03 08:49:26.024667 2021] [fcgid:warn] [pid 23030] [client 144.76.3.131:52974] mod_fcgid: stderr: #2 /var/www/www-root/data/www/sworldjournal.com/lib/pkp/classes/context/ContextDAO.inc.php(63): DAO->retrieve('SELECT * FROM j...', Array)
[Wed Feb 03 08:49:26.024670 2021] [fcgid:warn] [pid 23030] [client 144.76.3.131:52974] mod_fcgid: stderr: #3 /var/www/www-root/data/www/sworldjournal.com/lib/pkp/classes/core/PKPRouter.inc.php(252): ContextDAO->getByPath('en')
[Wed Feb 03 08:49:26.024673 2021] [fcgid:warn] [pid 23030] [client 144.76.3.131:52974] mod_fcgid: stderr: #4 /var/www/www-root/data/www/sworldjournal.com/lib/pkp/classes/core/PKPRequest.inc.php(760): PKPRouter->getContext(Object(Request), 1)
[Wed Feb 03 08:49:26.024676 2021] [fcgid:warn] [pid 23030] [client 144.76.3.131:52974] mod_fcgid: stderr: #5 /var/www/www-root/data/www/sworldjournal.com/classes/core/Request.inc.php(64): PK in /var/www/www-root/data/www/sworldjournal.com/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php on line 74

**Comment by NateWr** [comment] 2021-02-03 10:07
Hi @sworld-guy. This is a duplicate of #6710. Please try the suggestions in that thread and post there with any follow-up.

**Closed by NateWr** 2021-02-03 10:07 UTC

**Comment by sworld-guy** [comment] 2021-02-03 10:34
Nothing from this thread (#6710.) works

**Comment by NateWr** [comment] 2021-02-03 10:43
Sorry, @sworld-guy, the issue I meant to send you to is #6703.

**Comment by sworld-guy** [comment] 2021-02-03 11:07
I read everything. But I could not find what to do.
This was done. 
; Client output/input character set
client_charset = utf-8
; Database connection character set
connection_charset = utf8

But it doesn't work. What to do next?
