### ISSUE TITLE
Decline Submission page's content is unaligned

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8949] opened 2023-04-28 15:07 UTC
**Describe the bug**
Likely misaligned because the decision page doesn't contain steps, only footer panel with buttons
![submission_decline](https://user-images.githubusercontent.com/20665587/235183456-0e099202-1b94-4072-9aeb-448aa66f7fa0.png)

**To Reproduce**
1. Make a submission as a journal manager
2. Log in to a user with a role that allows to make a decision on this submission
3. Press `Decline Submission`
4. See the page with the UI issue

**What application are you using?**
 OJS 3.4

**Comment by asmecher** [comment] 2023-05-30 23:32
I'm open to fixing this in time for 3.4.0-0, but it's not a show-stopper, so I'm deferring it for the moment to 3.4.0-1.

**Comment by Vitaliy-1** [comment] 2023-08-07 12:01
At the time of testing this template was missing from an OJS instance. Sorry, can't find what the reasons were. 

I can't think of a situation when the decision with only 1 step might not include the email but nevertheless I'd prefer it to be aligned without it too, just in case. Although it can wait until 3.5.

**Comment by jardakotesovec** [comment] 2023-11-16 15:42
@asmecher Since we can't reproduce it, I think we can bump it to some higher version, certainly it should not keep current version to be released.

**Comment by asmecher** [comment] 2023-11-16 15:55
Actually, I'm content to close this entirely -- it looks to me like a legacy issue from the dev process that's no longer reproducible. Unless either of you think there's still work to be done!

**Comment by Vitaliy-1** [comment] 2023-12-05 15:15
Still able to reproduce at least in OPS.

**Comment by jardakotesovec** [comment] 2023-12-07 15:30
@Vitaliy-1 Oki, can you give me example?

**Comment by Vitaliy-1** [comment] 2023-12-21 14:08
I've updated reproduction steps

**Comment by jardakotesovec** [comment] 2024-01-02 14:21
@Vitaliy-1 Thanks, added top margin for 'no steps' scenario.

I did not create separate PR for OJS to run tests as its just layout change and would not be catched by tests anyway.

So feel free just to merge it - https://github.com/pkp/ui-library/pull/307

**Comment by jardakotesovec** [comment] 2024-01-18 09:40
Merged to 3.4 and cherry picked in main. Closing

**Closed by jardakotesovec** 2024-01-18 09:40 UTC
Labels: Bug:1:Low
