### ISSUE TITLE
Issue Preview not showing assigned articles

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#5840] opened 2020-05-07 19:00 UTC
In OJS 3.2.0-3, the issue preview function does not show the articles assigned to that issue, it only shows the full article pdf (if uploaded) 

In previous versions of OJS 3 (tested on OJS 3.2.0, the articles are included in the article preview).

OJS 3.2.0 - Issue Preview

![image](https://user-images.githubusercontent.com/50342731/81334053-478b7680-905a-11ea-927a-95bebe34ad63.png)

OJS 3.2.0-3 - Issue Preview.
![image](https://user-images.githubusercontent.com/50342731/81335632-c681ae80-905c-11ea-96f8-26a370284b9c.png)

It was reported in the forum - https://forum.pkp.sfu.ca/t/ojs-3-2-0-3-error-previewing-future-issue/60343 and tested it out myself and had the same issue.

**Comment by asmecher** [comment] 2020-05-08 17:16
@NateWr, is this a result of https://github.com/pkp/pkp-lib/issues/5636?

**Comment by NateWr** [comment] 2020-05-11 11:04
I suspect that this is the result of the introduction of the `STATUS_QUEUED`/`STATUS_SCHEDULED` distinction. Perhaps the preview is not showing submissions that have been properly scheduled?

Either way it needs investigation so I will chuck it onto the next maintenance milestone to get sorted out.

**Comment by NateWr** [comment] 2020-05-20 09:07
Perhaps this is a duplicate of https://github.com/pkp/pkp-lib/issues/5837? @pmangahis is it possible that this issue was published and then unpublished? In such cases #5837 identified that articles did not appear in the preview.

The other possibility is that the articles have not been properly scheduled. @pmangahis can you check to see if the articles that are not being previewed are showing the "Scheduled" status (which would appear in blue at the top and to the left of the article id and title, when looking at the submission workflow page).

**Comment by pmangahis** [comment] 2020-05-21 17:58
Hi Nate,

I think it's related to the other issue. In the test I did, I did not publish and unpublish the article or issue.

The articles are assigned to the issue as seen here.

![image](https://user-images.githubusercontent.com/50342731/82589852-9e607800-9b51-11ea-9979-e67402ea8b71.png)

And within the manuscript itself it does indicate that I assigned it to that issue.

![image](https://user-images.githubusercontent.com/50342731/82589962-be903700-9b51-11ea-8212-9bfe75a3271e.png)

However, when I go to preview the issue only the full-text pdf appears on the page.

![image](https://user-images.githubusercontent.com/50342731/82590044-df588c80-9b51-11ea-9341-4eb60e457b13.png).

Please let me know if you need any more information from me.

**Comment by NateWr** [comment] 2020-05-26 11:30
Thanks @pmangahis! I've confirmed that this is distinct from #5837 and identified a couple of additional fixes with how issue sections are retrieved for unpublished issues and how the "Remove" button in the issue table of contents grid works.

PR:
https://github.com/pkp/ojs/pull/2773

**Comment by NateWr** [comment] 2020-05-27 15:15
Merged to `master` and `stable-3_2_0`.

**Closed by NateWr** 2020-05-27 15:15 UTC
Labels: Bug
