### ISSUE TITLE
[OPS] "Galleys" section doesn't load

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5740] opened 2020-04-15 13:26 UTC
**Describe the bug**
The "Galleys" section in the Publication tab for a given preprint doesn't load.

**Error log**
`[Tue Apr 14 15:14:57.317420 2020] [php7:error] [pid 19209] [client 192.168.1.71:54783] PHP Fatal error: Uncaught Error: Call to a member function getFileId() on null in /var/www/preprints_scielo_org/htdocs/lib/pkp/controllers/api/file/linkAction/FileLinkAction.inc.php:46\nStack trace:\n#0 /var/www/preprints_scielo_org/htdocs/lib/pkp/controllers/api/file/linkAction/DownloadFileLinkAction.inc.php(37): FileLinkAction->getActionArgs(NULL, 5)\n#1 /var/www/preprints_scielo_org/htdocs/controllers/grid/articleGalleys/ArticleGalleyGridCellProvider.inc.php(90): DownloadFileLinkAction->__construct(Object(Request), NULL, 5, ‘PDF’)\n#2 /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/controllers/grid/GridCellProvider.inc.php(56): ArticleGalleyGridCellProvider->getCellActions(Object(Request), Object(ArticleGalleyGridRow), Object(GridColumn))\n#3 /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(1104): GridCellProvider->render(Object(Request), Object(ArticleGalleyGridRow), Object(GridColumn))\n#4 /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/controllers/grid/GridHandler.inc.php(101 in /var/www/preprints_scielo_org/htdocs/lib/pkp/controllers/api/file/linkAction/FileLinkAction.inc.php on line 46, referer: https://preprints.scielo.org/index.php/scielo/workflow/index/52/5`

**What application are you using?**
 Open Journal Systems 3.2.0.1

**Additional information**
![image](https://user-images.githubusercontent.com/4059679/79342378-6f783600-7f03-11ea-9f99-59f001033a4a.png)

**Comment by ajnyga** [comment] 2020-04-15 15:30
Not seeing this in new stable 3.2.0.1 installs. Are you seeing this with all preprints

**Comment by alexxxmendonca** [comment] 2020-04-15 15:41
Hi @ajnyga 

No, it happened with just one preprint. I asked the author to submit again and the new submisssion worked (I can't tell if the author has submitted a new file).

**Comment by ajnyga** [comment] 2020-04-15 16:16
Most likely the author has started to upload a galley, filled in the galley label but the closed the window that is meant to upload the actual file. This results to a situation where you have a galley label without a file and maybe the error that you describe.

@asmecher any ideas how that could be improved. This would of course apply to other places as well where galley grids are used (OJS of course).

**Comment by asmecher** [comment] 2020-04-15 18:18
@ajnyga, were you able to replicate the problem by closing the modal after adding a label? It's odd that the file ID seems to be set -- suggesting that the file *was* uploaded.

**Comment by ajnyga** [comment] 2020-04-16 16:33
yes sorry, that was not the reason. Not sure what happened there.

**Comment by alexxxmendonca** [comment] 2020-04-16 16:34
Just want to report back that the version was upgraded today to 3.2.0.1 beta and the problem persists.

The author submitted a new preprint and the problematic one was deleted.

**Comment by alexxxmendonca** [comment] 2020-04-27 18:47
I just want to report back that we've had other cases where this occurred again. 

It seems to affect a very small portion of submissions.

**Comment by adrianojam** [comment] 2020-04-29 22:22
This happened to me too. Did you find any solution?

**Comment by alexxxmendonca** [comment] 2020-05-11 11:24
Hello!
Just want to report that there is now a case where this happened after creating a new version.

Version 1 was fine, no problem. The problem occurred when creating version 2.

This is how the public page looks like now (notice how the PDF appears duplicated): https://preprints.scielo.org/index.php/scielo/preprint/view/22

**Comment by ajnyga** [comment] 2020-05-12 05:48
@asmecher do you have ideas about this? The galley stuff is pretty much the same as you would have in OJS and I do not recall seeing this there.

**Comment by asmecher** [comment] 2020-05-12 23:10
@alexxxmendonca, would you be able to provide us (privately) with a database dump?

**Comment by alexxxmendonca** [comment] 2020-05-13 11:04
@asmecher yes, I will send it to you by email.

**Comment by asmecher** [comment] 2020-05-15 21:06
We were able to determine steps to replicate this. It affects OJS as well, but hasn't been seen there before probably because editors travel through the system more predictably.

1. Start creating a galley. Give it a label and proceed.
2. Complete step 1 of the file upload wizard. Proceed to step 2.
3. Cancel the file upload wizard.

At this point, attempting to reload the galley list will leave an endless spinner and the error log will contain (for OJS in this case, other apps similar):
```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getFileId() on null in .../lib/pkp/controllers/api/file/linkAction/FileLinkAction.inc.php:46
Stack trace:
#0 .../lib/pkp/controllers/api/file/linkAction/DownloadFileLinkAction.inc.php(37): FileLinkAction->getActionArgs(NULL, 5)
#1 .../controllers/grid/articleGalleys/ArticleGalleyGridCellProvider.inc.php(90): DownloadFileLinkAction->__construct(Object(Request), NULL, 5, 'test')
#2 .../lib/pkp/classes/controllers/grid/GridCellProvider.inc.php(56): ArticleGalleyGridCellProvider->getCellActions(Object(Request), Object(ArticleGalleyGridRow), Object(GridColumn))
#3 .../lib/pkp/classes/controllers/grid/GridHandler.inc.php(1104): GridCellProvider->render(Object(Request), Object(ArticleGalleyGridRow), Object(GridColumn))
#4 /home/asmecher/git/ojs-stable-3_2_0/lib/pkp/classes/co...', referer: http://.../index.php/publicknowledge/workflow/index/20/4
```

**Comment by asmecher** [comment] 2020-05-15 23:34
This only affects OJS, OMP, and OPS 3.2.0 builds (before this fix gets included). Here's what's happening...
- When a file upload gets cancelled, the front end [calls](https://github.com/pkp/pkp-lib/blob/34ce60c3fe2cef15b7e0e6154332b06d3648f064/templates/controllers/wizard/fileUpload/fileUploadWizard.tpl#L27) `ManageFileAPIHandler` to [delete the uploaded file](https://github.com/pkp/pkp-lib/blob/34ce60c3fe2cef15b7e0e6154332b06d3648f064/controllers/api/file/PKPManageFileApiHandler.inc.php#L54).
- [`ManageFileAPIHandler::detachEntities`](https://github.com/pkp/ojs/blob/f4b168d211aafd91a6d1ca24cdc930a25aa7931d/controllers/api/file/ManageFileApiHandler.inc.php#L129) gets called to clean up anything that might be attached to the file, e.g. galleys that point to it.
- `detachEntities` correctly identifies the galley that needs updating, sets its file ID to `null`, and calls `ArticleGalleyDAO::updateObject` to save it.

This was all working in OJS/OMP/OPS prior to 3.2. However, then we [switched](https://github.com/pkp/ojs/commit/88aba9a0cb9a46881fdb0c2b46c3f311d98be7d5) `ArticleGalleyDAO` to extending `SchemaDAO`. `SchemaDAO`'s [`updateObject`](https://github.com/pkp/pkp-lib/blob/master/classes/db/SchemaDAO.inc.php#L130) implementation [only works](https://github.com/pkp/pkp-lib/blob/34ce60c3fe2cef15b7e0e6154332b06d3648f064/classes/db/SchemaDAO.inc.php#L279) with the data that exists in the `DataObject`, i.e. if `$galley->_data['fileId']` is unset, the `UPDATE` statement will not touch that column. This differs from the previous implementation of `GalleyDAO::updateObject`, which [updated everything regardless](https://github.com/pkp/ojs/blob/9ea49c26eba069d68f9410a093a1d0836b3417ad/classes/article/ArticleGalleyDAO.inc.php#L256).

In this bug's case, even though we [call](https://github.com/pkp/ojs/blob/f4b168d211aafd91a6d1ca24cdc930a25aa7931d/controllers/api/file/ManageFileApiHandler.inc.php#L141) `$galley->setFileId(null);` the `fileId` is not set on `$galley->_data` because `DataObject::setData('xyz', null)` [behaves like an unset](https://github.com/pkp/pkp-lib/blob/34ce60c3fe2cef15b7e0e6154332b06d3648f064/classes/core/DataObject.inc.php#L119..L120).

I propose the following solution:
- In the `master` branch, [simplify `DataObject::setData`](https://github.com/pkp/pkp-lib/commit/6a7f5e5cf609e69a54ba05727d74f5cbefd308a4) to just store a `null` when one is passed in. Add a `DataObject::unsetData` function to support cases that expected the old behaviour [see below].
- In the `stable-3_2_0` branch, I don't want to introduce such a profound change without allowing for more time for testing. A quick but imperfect work-around would be to replace
  ```
  $galley->setFileId(null);
  ```
  ...with...
  ```
  // Stable branch work-around for https://github.com/pkp/pkp-lib/issues/5740
  $galley->_data['fileId'] = null;
  ```

*Why was `DataObject::setData` written this way?*
The long-standing remove-nulls behaviour of `DataObject::setData` was [introduced in 2010](https://github.com/pkp/pkp-lib/commit/ec3d9ef488) as [part](http://wayback.archive-it.org/7100/20180507180247/https://pkp.sfu.ca/bugzilla/show_bug.cgi?id=5015) of the Citation Assistant and metadata framework.

As the Citation Assistant has been removed, the most important area to test for regressions is the metadata framework, used primarily in the OAI interface.

@NateWr and @ajnyga -- sorry for the wall of text, I tried to be both brief and comprehensive :) Any objections to the proposal?

**Comment by ajnyga** [comment] 2020-05-18 05:57
No objections, nice detective work.

**Comment by NateWr** [comment] 2020-05-18 11:51
@asmecher No objections to this workaround and a good idea to leave the change to `setData()` for 3.3.

**Comment by asmecher** [comment] 2020-05-20 00:04
Thanks, all -- merged!

**Comment by Vitaliy-1** [comment] 2020-05-20 07:41
@asmecher, removing constructor from the `DataObject` also requires correspondent changes in classes that extend it, I mean removing parental constructor calls.

**Comment by NateWr** [comment] 2020-05-20 09:33
@Vitaliy-1 can you describe in more detail what you mean? I don't think that removing an empty `__construct()` method in a parent class will impact classes which extend it, but maybe I'm missing something. (I presume we're talking about [this](https://github.com/pkp/pkp-lib/commit/58cfc2a1ff4ac9a05d5c17fac129ff1b41386962#diff-5e92ecc3595af53e01da0651586fff1bL37-L42)).

**Comment by Vitaliy-1** [comment] 2020-05-20 09:52
It leads to an error, e.g.:
```
Uncaught Error: Cannot call constructor in /home/doc/OJS/development/ojs/lib/pkp/classes/submission/Representation.inc.php:26
```

**Comment by NateWr** [comment] 2020-05-20 09:54
Ah ok! Good to know. I'll re-open and let Alec sort it.

**Comment by NateWr** [comment] 2020-05-20 12:16
Yeah this has broken `master` so I've gone ahead and restored the constructor to master in https://github.com/pkp/pkp-lib/commit/e38d9de1da14eecd3edb4b02d3bc9238a9860cec and we'll wait for Alec to make a final decision.

**Comment by NateWr** [comment] 2020-05-20 14:44
@asmecher I _think_ this is having a knock-on effect on the unit tests in `master`. https://travis-ci.org/github/pkp/ojs/jobs/689217597#L3833-L3890

**Comment by asmecher** [comment] 2020-05-20 17:59
Whoops, sorry! I've adjusted the tests and am running a build: https://travis-ci.org/github/pkp/ojs/builds/689356306

**Comment by asmecher** [comment] 2020-05-20 22:07
Fixed.

**Comment by asmecher** [comment] 2020-05-20 22:38
For users who are encountering this on OJS or OMP 3.2.0-0 through 3.2.0-3, you can fix it by...
1. Applying [this patch for OJS](https://github.com/pkp/ojs/commit/4a3f22c19673c62b9094bcaf9a0c5b34f9e08105) or [this patch for OMP](https://github.com/pkp/ops/commit/91a6f4b816e551702f945bcd4c2efb4dfd8e37a1) (both in the `lib/pkp` subdirectory)
2. Correct the database by executing:
  ```
  UPDATE publication_galleys SET file_id = NULL WHERE file_id IN (SELECT pg.file_id FROM publication_galleys pg LEFT JOIN submission_files sf ON (pg.file_id = sf.file_id) WHERE pg.file_id IS NOT NULL AND sf.file_id IS NULL);
  ```

**Take a complete backup** before running database statements.

**Comment by asmecher** [comment] 2020-05-25 22:59
Reverted https://github.com/pkp/pkp-lib/commit/ef8636566c999a61693d59c3052ad88b07c9d46e -- this had deeper knock-on effects in the tests and I wasn't comfortable working it through so close to the 3.2.1 release. I've added the work-around to `master` and deferred the rest until 3.3. See
https://github.com/pkp/pkp-lib/issues/5740#issuecomment-629548502 for the quick summary of the solution that'll need to be revisited after `stable-3_2_1` is forked.

**Comment by NateWr** [comment] 2020-11-13 16:13
@asmecher it may be worth re-checking this after the new submission file merge. I don't fully understand your description of [the problem](https://github.com/pkp/pkp-lib/issues/5740#issuecomment-629548502), but if it's related to the `detachEntities` stuff, that has been rewritten a bit so this may not be a problem any more.

**Comment by NateWr** [comment] 2020-11-27 12:48
I've bumped this from the 3.3 release due to time constraints. But it may already be fixed by changes to submission files in 3.3. it would be good to test this on the upcoming release candidate to see if it can be reproduced. Here are the [reproduction steps](https://github.com/pkp/pkp-lib/issues/5740#issuecomment-629484346).

**Comment by carolinatanigushi** [comment] 2021-01-26 18:06
It's still been happening in OPS for us, though less frequently. We had a new case today. If you need error logs or the like, please contact me and we can provide you with it.

**Comment by asmecher** [comment] 2021-01-26 22:04
@carolinatanigushi, what would be most helpful is if someone on your end can look for the URL that displays this error, and check further back in the log to see when the last time was that it was successfully displayed. That will establish the window of time during which the problem was introduced. Then trace the user's path through the system by looking at log entries for their IP address between those two times.

**Comment by carolinatanigushi** [comment] 2021-02-04 12:48
@asmecher we tested these submissions on version 3.3 and it seems like it's been fixed as Nate said, thanks!

**Closed** 2021-02-04 13:25 UTC

**Comment by marcbria** [comment] 2024-12-28 13:16
Fall in this today with an old journal.

Alec's workaround works but the update query didn't in my case.

If there aren't much rows, I prefer select first and doing the update manually:

```
SELECT * FROM publication_galleys as pg1
 WHERE pg1.file_id IN 
 (SELECT pg.file_id 
    FROM publication_galleys as pg 
    LEFT JOIN submission_files as sf 
      ON (pg.file_id = sf.file_id) 
    WHERE pg.file_id IS NOT NULL 
    AND sf.file_id IS NULL);
```

This will show you the offending rows in publicacion_galleys table so you only need to set them to NULL.

**Comment by orcalator** [comment] 2025-07-10 11:05
hi @marcbria,

I just ran into this problem. What do you mean by "you only need to set them to NULL"? Set what to NULL? Thx.

EDIT: ok, it seems you were referring to the file_id field in the publication_galleys table. 

Nino
