### ISSUE TITLE
[OJS] 3.2.1 - Slow or not loading search in "Add Reviewer" form

### ISSUE THREAD

**Issue by KRONWALLED1134** [pkp/pkp-lib#6112] opened 2020-07-23 09:50 UTC
Hi

We recently upgraded our OJS installation to 3.2.1.
Everything works fine except for the Add reviewer form.

The users reported that it loads performs searches very slow or not at all.

I checked the database then and saw very long running queries (about 14-15 minutes) regarding the searches in the Add Reviewer form.

Example (Search for 'he' in the Add reviewer form)
`SHOW FULL PROCESSLIST;` 
```
+-----+------+-----------+------+---------+------+----------+-----------------------+| Id  | User | Host      | db   | Command | Time | State    | Info                  |
+-----+------+-----------+------+---------+------+----------+-----------------------+
| 359 | xxx | 172.20.0.2:58262 | xxx | Query   |    2 | Sending data | select `u`.*, COALESCE(ugl.setting_value, ugpl.setting_value) AS user_given, CASE WHEN ugl.setting_value <> '' THEN ufl.setting_value ELSE ufpl.setting_value END AS user_family, MAX(ra.date_assigned) as last_assigned, (SELECT SUM(CASE WHEN ra.date_completed IS NULL AND ra.declined <> 1 THEN 1 ELSE 0 END) FROM review_assignments AS ra WHERE u.user_id = ra.reviewer_id) as incomplete_count, (SELECT SUM(CASE WHEN ra.date_completed IS NOT NULL AND ra.declined <> 1 THEN 1 ELSE 0 END) FROM review_assignments AS ra WHERE u.user_id = ra.reviewer_id) as complete_count, (SELECT SUM(CASE WHEN ra.declined = 1 THEN 1 ELSE 0 END) FROM review_assignments AS ra WHERE u.user_id = ra.reviewer_id) as declined_count, (SELECT SUM(CASE WHEN ra.cancelled = 1 THEN 1 ELSE 0 END) FROM review_assignments AS ra WHERE u.user_id = ra.reviewer_id) as cancelled_count, AVG(DATEDIFF(ra.date_completed, ra.date_notified)) as average_time, (SELECT AVG(ra.quality) FROM review_assignments AS ra WHERE u.user_id = ra.reviewer_id AND ra.quality IS NOT NULL) as reviewer_rating from `users` as `u` left join `user_user_groups` as `uug` on `uug`.`user_id` = `u`.`user_id` left join `user_groups` as `ug` on `ug`.`user_group_id` = `uug`.`user_group_id` left join `user_settings` as `ugl` on `ugl`.`user_id` = `u`.`user_id` and `ugl`.`setting_name` = 'givenName' and `ugl`.`locale` = 'en_US' left join `user_settings` as `ugpl` on `ugpl`.`user_id` = `u`.`user_id` and `ugpl`.`setting_name` = 'givenName' and `ugpl`.`locale` = 'en_US' left join `user_settings` as `ufl` on `ufl`.`user_id` = `u`.`user_id` and `ufl`.`setting_name` = 'familyName' and `ufl`.`locale` = 'en_US' left join `user_settings` as `ufpl` on `ufpl`.`user_id` = `u`.`user_id` and `ufpl`.`setting_name` = 'familyName' and `ufpl`.`locale` = 'en_US' left join `user_group_stage` as `ugs` on `uug`.`user_group_id` = `ugs`.`user_group_id` left join `user_settings` as `us` on `u`.`user_id` = `us`.`user_id` left join `user_interests` as `ui` on `u`.`user_id` = `ui`.`user_id` left join `controlled_vocab_entry_settings` as `cves` on `ui`.`controlled_vocab_entry_id` = `cves`.`controlled_vocab_entry_id` left join `review_assignments` as `ra` on `u`.`user_id` = `ra`.`reviewer_id` where `ug`.`context_id` = 1 and `ug`.`role_id` in (4096) and `u`.`disabled` = 0 and `ugs`.`stage_id` = 3 and (lower(u.username) LIKE '%he%' or lower(u.email) LIKE '%he%' or (`us`.`setting_name` = 'givenName' and lower(us.setting_value) LIKE '%he%') or (`us`.`setting_name` = 'familyName' and lower(us.setting_value) LIKE '%he%') or (`us`.`setting_name` = 'affiliation' and lower(us.setting_value) LIKE '%he%') or (`us`.`setting_name` = 'biography' and lower(us.setting_value) LIKE '%he%') or (`us`.`setting_name` = 'orcid' and lower(us.setting_value) LIKE '%he%') or lower(cves.setting_value) LIKE '%he%') group by `u`.`user_id`, `user_given`, `user_family` order by `u`.`user_id` desc LIMIT 0,30 |
+-----+------+-----------+------+---------+------+----------+-----------------------+
```

So the query is already running for about 840 seconds right now. It finished about 30 seconds later.
I then run an EXPLAIN on this query.

`EXPLAIN <query>`

```
+----+--------------------+-------+------------+--------+----------------------------------------------------------------------------------+--------------------------------+---------+-----------------------------------+------+----------+----------------------------------------------+
| id | select_type        | table | partitions | type   | possible_keys                                                                    | key                            | key_len | ref                               | rows | filtered | Extra                                        |
+----+--------------------+-------+------------+--------+----------------------------------------------------------------------------------+--------------------------------+---------+-----------------------------------+------+----------+----------------------------------------------+
|  1 | PRIMARY            | ug    | NULL       | ref    | PRIMARY,user_groups_user_group_id,user_groups_context_id,user_groups_role_id     | user_groups_role_id            | 8       | const                             |    1 |    94.44 | Using where; Using temporary; Using filesort |
|  1 | PRIMARY            | ugs   | NULL       | ref    | user_group_stage_user_group_id,user_group_stage_stage_id                         | user_group_stage_user_group_id | 8       | xxx.ug.user_group_id             |    2 |    19.35 | Using where; Using index                     |
|  1 | PRIMARY            | uug   | NULL       | ref    | user_user_groups_pkey,user_user_groups_user_group_id,user_user_groups_user_id    | user_user_groups_user_group_id | 8       | xxx.ug.user_group_id             |  685 |   100.00 | Using where; Using index                     |
|  1 | PRIMARY            | u     | NULL       | eq_ref | PRIMARY                                                                          | PRIMARY                        | 8       | xxx.uug.user_id                  |    1 |    10.00 | Using where                                  |
|  1 | PRIMARY            | ugl   | NULL       | ref    | user_settings_pkey,user_settings_user_id,user_settings_locale_setting_name_index | user_settings_pkey             | 819     | xxx.uug.user_id,const,const      |    1 |   100.00 | NULL                                         |
|  1 | PRIMARY            | ugpl  | NULL       | ref    | user_settings_pkey,user_settings_user_id,user_settings_locale_setting_name_index | user_settings_pkey             | 819     | xxx.uug.user_id,const,const      |    1 |   100.00 | NULL                                         |
|  1 | PRIMARY            | ufl   | NULL       | ref    | user_settings_pkey,user_settings_user_id,user_settings_locale_setting_name_index | user_settings_pkey             | 819     | xxx.uug.user_id,const,const      |    1 |   100.00 | NULL                                         |
|  1 | PRIMARY            | ufpl  | NULL       | ref    | user_settings_pkey,user_settings_user_id,user_settings_locale_setting_name_index | user_settings_pkey             | 819     | xxx.uug.user_id,const,const      |    1 |   100.00 | NULL                                         |
|  1 | PRIMARY            | us    | NULL       | ref    | user_settings_pkey,user_settings_user_id                                         | user_settings_pkey             | 8       | xxx.uug.user_id                  |    3 |   100.00 | NULL                                         |
|  1 | PRIMARY            | ui    | NULL       | ref    | u_e_pkey                                                                         | u_e_pkey                       | 8       | xxx.uug.user_id                  |    4 |   100.00 | Using index                                  |
|  1 | PRIMARY            | cves  | NULL       | ref    | c_v_e_s_pkey,c_v_e_s_entry_id                                                    | c_v_e_s_pkey                   | 8       | xxx.ui.controlled_vocab_entry_id |    1 |   100.00 | Using where                                  |
|  1 | PRIMARY            | ra    | NULL       | ref    | review_assignments_reviewer_id,review_assignments_reviewer_review                | review_assignments_reviewer_id | 8       | xxx.uug.user_id                  |   26 |   100.00 | NULL                                         |
|  6 | DEPENDENT SUBQUERY | ra    | NULL       | ref    | review_assignments_reviewer_id,review_assignments_reviewer_review                | review_assignments_reviewer_id | 8       | func                              |   26 |    90.00 | Using where                                  |
|  5 | DEPENDENT SUBQUERY | ra    | NULL       | ref    | review_assignments_reviewer_id,review_assignments_reviewer_review                | review_assignments_reviewer_id | 8       | func                              |   26 |   100.00 | NULL                                         |
|  4 | DEPENDENT SUBQUERY | ra    | NULL       | ref    | review_assignments_reviewer_id,review_assignments_reviewer_review                | review_assignments_reviewer_id | 8       | func                              |   26 |   100.00 | NULL                                         |
|  3 | DEPENDENT SUBQUERY | ra    | NULL       | ref    | review_assignments_reviewer_id,review_assignments_reviewer_review                | review_assignments_reviewer_id | 8       | func                              |   26 |   100.00 | NULL                                         |
|  2 | DEPENDENT SUBQUERY | ra    | NULL       | ref    | review_assignments_reviewer_id,review_assignments_reviewer_review                | review_assignments_reviewer_id | 8       | func                              |   26 |   100.00 | NULL                                         |
+----+--------------------+-------+------------+--------+----------------------------------------------------------------------------------+--------------------------------+---------+-----------------------------------+------+----------+----------------------------------------------+
```

Stats:
```
mysql> select count(*) from review_assignments;
+----------+
| count(*) |
+----------+
|      939 |
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from users;
+----------+
| count(*) |
+----------+
|     4557 |
+----------+
1 row in set (0.00 sec)
```
If I can provide more information for you just let me know.

Thanks in advance and best regards

**Comment by asmecher** [comment] 2020-07-24 17:56
@KRONWALLED1134, this would probably be a lot easier to tinker with using a reproducible data set; would you be willing to (privately) send me a copy of your database, anonymized as needed?

**Comment by jnugent** [comment] 2020-08-06 14:03
This may be related.  We have a recent installation (3.2.1-1) that also has a large review set.  The Locate Reviewer form returns no displayed results, however the JSON response does indeed contain the record being searched for.  There are no errors in the logs.   @asmecher I can share data with you if you still need it.  The database queries seem fine, this may just be a UI issue.

**Comment by jnugent** [comment] 2020-08-06 14:44
I worked out our issue with Nate and he thinks it's a different problem.  We've fixed it.  I will file a new issue.

**Comment by swapnil88porwal** [comment] 2021-03-18 11:14
Hi,

Can any one share resolution, we are also facing same issue ....Add reviewer form taking too long. Our OJS version is 3.1.2.4.

**Comment by asmecher** [comment] 2021-03-30 16:59
@swapnil88porwal, I would recommend upgrading before anything else; 3.1.2-4 is quite old.

**Comment by swapnil88porwal** [comment] 2021-03-31 07:21
Thanks

**Comment by jonasraoni** [comment] 2021-11-06 08:53
Hi!

This issue might be related to https://github.com/pkp/pkp-lib/issues/7167 (at least for newer installations).
We had an installation timing-out in this interface, after I addressed the issue above the time went down to 7s, which is somehow acceptable.

I'll come up with some query optimizations, which in my machine lowered the time from 7s to < 1s.

**Comment by jonasraoni** [comment] 2021-11-06 21:02
PRs:
Stable 3.3.0
OJS: https://github.com/pkp/ojs/pull/3221
pkp-lib: https://github.com/pkp/pkp-lib/pull/7438

**Comment by jonasraoni** [comment] 2021-11-06 21:04
I'll create PRs for /main later.

**Comment by jonasraoni** [comment] 2021-11-07 20:32
@asmecher I was going to apply these improvements to `/main`, but I saw most of things are already covered.
Let me know if you think it's worth to merge in these pieces:
- The search query (+ breaking words using preg_split)
- The review_assignments query: in my test case, with 11K users and 30K review_assignments, pre-calculating the totals returned the result set in 0.5s while the sub-query for each field (and also an outer left join with a group by) took a little more than 1s (the performance was improved in PostgreSQL as well, from 0.5s to 0.3s).
- Use more of Carbon to deal with dates

**Comment by asmecher** [comment] 2021-11-10 00:24
@jonasraoni, I would much rather see the query construction work that's already in `main` back-ported to `stable-3_3_0` rather than making a whole new implementation just for the 3.3.0-9 build. How do you feel about reconciling the two? Are there improvements in this PR that should be forward-ported to `main`?

**Comment by jonasraoni** [comment] 2021-11-10 09:04
@asmecher Yes, I believe some improvements might be ported to main: https://github.com/pkp/pkp-lib/issues/6112#issuecomment-962676102

As I said in the comment before, I just saw the updates in /main after creating this PR, so yeah, I can merge the changes.

**Comment by jonasraoni** [comment] 2021-11-14 11:40
@asmecher I've updated some things in `/main` (PRs below) and merged down the updates into the older PR.
https://github.com/pkp/ojs/pull/3226
https://github.com/pkp/pkp-lib/pull/7456

**Comment by asmecher** [comment] 2021-11-16 21:17
Thanks, @jonasraoni! I've added a few comments to both `main` and `stable-3_3_0`, but the Travis tests are failing, so those could also use a look.

**Comment by asmecher** [comment] 2021-11-23 23:32
Thanks, @jonasraoni, I've merged the two `main` branch PRs above: https://github.com/pkp/pkp-lib/issues/6112#issuecomment-968274000

Are the `stable-3_3_0` PRs [listed above](https://github.com/pkp/pkp-lib/issues/6112#issuecomment-962509511) synchronized with this code? If so, are they ready for another look?

**Comment by jonasraoni** [comment] 2021-11-24 18:54
@asmecher I've synchronized the changes.

**Comment by asmecher** [comment] 2021-11-26 22:25
Thanks, @jonasraoni! These are definitely more profound changes than we should be merging into a stable branch -- but I'll make an exception this time.

**Comment by jonasraoni** [comment] 2021-11-27 09:20
Totally agree! Better to avoid touching the sleeping dragon :)

**Comment by jnugent** [comment] 2021-12-09 18:15
Hi everyone,

I hate to be the bearer of bad news but the changes introduced here break query discussion creation.  With these modifications in place, if you are not assigned to a submission and attempt to start a new discussion you receive the message

"You must assign at least one participant to this submission before initiating a discussion."

If you then assign yourself to the submission, you can create a discussion but you will be the only participant.

**Comment by asmecher** [comment] 2021-12-09 18:21
@jonasraoni, could you try this out? I'm presuming you're working with `stable-3_3_0`, right, @jnugent?

**Comment by jnugent** [comment] 2021-12-09 18:26
@asmecher Yeah, all of this was merged into the client installation that originally had the performance issues, and we have another ticket open assigned to Jonas for it.  The installation in question is at the tip of `stable-3_3_0`

**Comment by jonasraoni** [comment] 2021-12-10 19:16
Hi! I just checked and there's really a regression here. This is the cause: https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/services/queryBuilders/PKPUserQueryBuilder.inc.php#L467

It should be the last statement... I'd rather avoid such construction without "()", but as it's not present in /master, I'll just add a fast fix.

**Comment by jonasraoni** [comment] 2021-12-10 19:19
About the impact surface, I just found it being used by this piece of code: https://github.com/pkp/pkp-lib/blob/stable-3_3_0/controllers/grid/queries/form/QueryForm.inc.php#L278

**Comment by jonasraoni** [comment] 2021-12-10 19:55
@asmecher
https://github.com/pkp/pkp-lib/pull/7543
https://github.com/pkp/ojs/pull/3249
https://github.com/pkp/ops/pull/207
https://github.com/pkp/omp/pull/1040

**Comment by asmecher** [comment] 2021-12-10 20:45
Thanks, @jonasraoni -- this is the kind of regression I was worried about with big changes to `stable` branches, but the fix looks clean. All merged.

**Closed by asmecher** 2021-12-10 20:45 UTC
Labels: Dev Housekeeping

**Comment by jonasraoni** [comment] 2021-12-11 07:25
Yep, there were too many changes and we don't have tests enough to cover all details :)

**Comment by asmecher** [comment] 2022-01-17 17:26
Did you re-run the Travis tests with the updated PR (https://github.com/pkp/pkp-lib/pull/7456), @jonasraoni? I've added 2 comments there, and once those are addressed this can be merged if the tests are passing.

**Comment by jonasraoni** [comment] 2022-01-17 17:54
@asmecher This issue is already merged/closed, is this a bug/delayed comment? :D

**Comment by asmecher** [comment] 2022-01-17 20:56
Weird, I think I must've wandered into an old Github notification without noticing it. The two comments would be nice to address in `main`, otherwise no need to revisit this, thanks!
