### ISSUE TITLE
Smarty not translating datetime names

### ISSUE THREAD

**Issue by henriquejsfj** [pkp/pkp-lib#9361] opened 2023-09-29 17:54 UTC
**Describe the bug**
Smarty is always using English language when showing month name...
I tried for example:
`{$smarty.now|date_format:"%d DE %B DE %Y"}`
`{$smarty.now|date_format:$dateFormatLong}`

Both shows the month name in English. 

The page `admin/systemInfo` which uses `$dateFormatLong` also shows in English:
![image](https://github.com/pkp/pkp-lib/assets/16216517/2ba53c4e-f65c-4766-9883-304fdcf16147)

**To Reproduce**
Install OJS 3.4 in pt-BR language (my case) and go to `admin/systemInfo` page.

**What application are you using?**
 OJS 3.4

**Comment by asmecher** [comment] 2023-09-29 18:27
@henriquejsfj, I think this is a duplicate of https://github.com/pkp/pkp-lib/issues/9303.

**Closed by asmecher** 2023-09-29 18:27 UTC
