### ISSUE TITLE
Failed to cancel a submission upload

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6642] opened 2021-01-20 19:42 UTC
**Describe the bug**
After uploading and cancelling the submission of some files, then trying to proceed to the next step, the files I've cancelled reappeared and I was asked to choose their type.

**To Reproduce**
Upload some files, cancel the upload process, then try to go to the next step.

**What application are you using?**
 OJS, OMP or OPS version X.X.X

**Additional information**
- Maybe the submission type validation could be done through a script before the submit.
- My slow machine taking too long to process a finished upload might be the culprit 😁

**Comment by NateWr** [comment] 2021-01-21 11:15
I'm  having trouble reproducing this. I've been able to get through the following steps by throttling the connection using the browser's dev tools:

1. Go to file upload during submission.
2. Open browser dev tools (Firefox) > Open device simulator > set throttling to Regular 2G
3. Begin uploading a file.
4. While the progress bar is increasing, click Cancel.
5. Click Save and Continue

I didn't receive any error message. Do these steps look like the same ones you took when encountering this? 

I thought maybe there's a particular timing issue where if it's cancelled right after the last chunk is sent to the server, it can cause this issue. But I've tried to reproduce that by timing my click on the cancel button and still not been able to reproduce it.

**Comment by NateWr** [comment] 2021-01-21 11:19
Ok, yeah, I was able to reproduce this. Effectively, I need to click cancel at the split second between when the last chunk is sent and the display updates.

Since the result of this is just that the user sees a validation error and has an opportunity to remove the file, I think this is a minor UX issue. I'm going to close it as I think it's going to be rare, but if we get reports that it is happening and causing confusion we can revisit it.

**Closed by NateWr** 2021-01-21 11:19 UTC
Labels: Bug

**Comment by jonasraoni** [comment] 2021-01-22 08:18
I'm naturally unlucky 😁
