### ISSUE TITLE
OJS 3.0b: Journal Page Header not on front page

### ISSUE THREAD

**Issue by nmpx** [pkp/pkp-lib#867] opened 2015-11-04 18:48 UTC
After uploading a header image for the journal page (which was kind of wonky in and of itself but I'm not sure how to describe it), this image is not being displayed on the front page. Tried clearing my browser cache, removing and re-uploading the image, it never shows up anywhere.

![bug03 1](https://cloud.githubusercontent.com/assets/5183702/10948202/6fc0828e-82fa-11e5-8058-50e2c6bb3c62.png)

And this is how the front page looks:

![bug03 2](https://cloud.githubusercontent.com/assets/5183702/10948219/84e5d6e6-82fa-11e5-9f65-e2f60186b454.png)

It's *possible* that I haven't look for it in the correct place, but the description for what this element is and where it goes is pretty confusing.

**Comment by asmecher** [comment] 2015-11-04 18:55
This is a duplicate of https://github.com/pkp/pkp-lib/issues/660 -- noted there.

**Closed by asmecher** 2015-11-04 18:55 UTC
