### ISSUE TITLE
Quicksubmit creates empty proposal

### ISSUE THREAD

**Issue by marlara** [pkp/pkp-lib#8061] opened 2022-07-01 13:30 UTC
**Describe the bug**
Using the Quicksubmit, if I start a submission, but don't press on "Cancel" for exiting the submission, but just click on another page and exit throught the browser, it creates a blank incomplete submission.

**To Reproduce**
1. Go to the QuickSubmit plugin
2. Start a submission
3. Leave the page
4. Say "yes" to the browser
5. See error in the Proposal

**What application are you using?**
 OJS 3.3.0.11

**Additional information**
![Schermata da 2022-07-01 15-23-39](https://user-images.githubusercontent.com/12834687/176904251-7a4fc30d-f188-492a-873e-936140bba511.png)

**Comment by NateWr** [comment] 2022-07-04 10:44
Thanks for the great report, @marlara. This is a duplicate of https://github.com/pkp/pkp-lib/issues/7224. I'm going to close this issue, but I've copied over your report to that issue.

You may also be interested in following https://github.com/pkp/pkp-lib/issues/7446, where a number of issues with QuickSubmit are being tracked.

**Closed by NateWr** 2022-07-04 10:44 UTC
