### ISSUE TITLE
Add an option to make a submission file mandatory

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#6241] opened 2020-09-17 17:40 UTC
**Describe the problem you would like to solve**
A journal should not accept a manuscript for consideration unless all required files have been submitted - e.g. Article Text, Data Set, etc. 

These are identified as separate components, however OJS currently does not have a mechanism to designate a component as mandatory and prevent an author from completing the submission if that component is not uploaded. 

As a result a large number of submissions are desk rejected for not having all the mandatory components uploaded.

**Describe the solution you'd like**
An option (checkbox) to designate an article component (file) as mandatory for submission. Submission cannot proceed if it is not uploaded.

These requirements will need to be configured differently for each section. An editorial or review may not require the same submission file components as an article.

**Who is asking for this feature?**
Journal editors (via PKP|PS)
See feature request: [Author must upload file submission](https://forum.pkp.sfu.ca/t/ojs-3-1-author-must-upload-file-submission/48094/10)
This was also brought up in here [https://forum.pkp.sfu.ca/t/make-an-attribute-required/27850](https://forum.pkp.sfu.ca/t/make-an-attribute-required/27850) (partially addressed in [#2684](https://github.com/pkp/pkp-lib/issues/2684) with an option to make metadata fields mandatory).

**Comment by alexxxmendonca** [comment] 2020-09-17 17:43
I second this.

**Comment by NateWr** [comment] 2020-09-21 13:16
Thanks. A couple questions:

1. Can you think of use-cases where the number of components matters? For example, where a submission should be rejected if only one file component is uploaded?

2. Does this need to be configured on a per section basis? For example, do journals want to make a graphical abstract mandatory for research articles but not editorials?

**Comment by ICCLAT** [comment] 2020-09-25 13:22
1.- Yes, in our journal, we require 4 files mandatorily in the submission and review stage, a) PDF file of the manuscript, a) a letter to the editor,   c) a video  abstract and d) graphical abstract.  We cannot proceed further with the revision if any of these files is missing. Just to mention a number, about 50% of total rejection of our journal is early rejection  or desk rejection due to a missing file (about 1000 submissions per year). We really would save hours of work if such a feature would be implemented.
Moreover, During the 2nd or 3rd round of review, we also need another 3 files, also mandatorily: the reply to the reviewers, the PDF file of the manuscript with changes highlighted and a zip file with the editable version of the manuscript. 

2.- As the processing of these files  constitute a policy of the Journal, are applied to any section.

**Comment by alexxxmendonca** [comment] 2020-09-25 13:26
I would just like to add that:

2) I can definitely see cases where a certain file would be required for a section, but not for another. So yes, section-based would be ideal.

**Comment by NateWr** [comment] 2020-09-28 09:54
Thanks everyone, that's helpful. cc @israelcefrin as you begin usability research of the submission process.

**Comment by amandastevens** [comment] 2020-11-19 19:52
I think this is a duplicate of [issue 3100](https://github.com/pkp/pkp-lib/issues/3100).

**Comment by NateWr** [comment] 2020-11-23 10:47
Thanks @amandastevens. I've kept this one and closed the other, since there are more details here. But coders can find an example plugin for requiring submission components in #3100.

**Comment by agustinalc** [comment] 2021-06-16 20:45
I think this options is very much needed.
In my Journal, we also require 3 files mandatorily, for all sections. In our case, the section to which they're applying is not important. It's my belief that authors should not be able to submit their manuscripts if they haven't uploaded all the required files.
I hope this can be implemented in future versions.
It could be an option in "workflow - submission - components", where you can designate an article component as mandatory for submission. Submission cannot proceed if it is not uploaded (as librariam suggested).

**Comment by librariam** [comment] 2021-10-30 22:25
+1 more from PKP|PS

**Comment by NateWr** [comment] 2023-02-02 13:17
The following PRs add an option to make a file type required for new submissions. The file type is the "Component", like "Article Text", of an uploaded file. The setting can be found under Settings > Workflow > Submission > Component. Edit a component and there is a new option:

![require-genre](https://user-images.githubusercontent.com/2306629/216334751-7a085fc0-2a5e-49dd-b952-4836ce4405a2.png)

For now, the setting is simple: it only lets you require 1 file for each type and there is not a separate configuration for each section. When I explored adding section-specific settings, I ran into some UX questions that I didn't have time to resolve within the short time before 3.4 will be released. We can work on having different requirements for each section in a later issue.

@emmauhl this may impact documentation.

PRs:
https://github.com/pkp/pkp-lib/pull/8601
https://github.com/pkp/ojs/pull/3739
https://github.com/pkp/ops/pull/454
https://github.com/pkp/omp/pull/1318

**Comment by NateWr** [comment] 2023-02-02 17:02
All merged to `main`. This will be included in 3.4.

**Closed by NateWr** 2023-02-02 17:02 UTC
Labels: Hosting, Enhancement:1:Minor, Community:1:Common
