### ISSUE TITLE
[OJS]Access denied is shown to author, when section editor chooses revisions required which are subject to new round of peer review

### ISSUE THREAD

**Issue by gireeshcse** [pkp/pkp-lib#6646] opened 2021-01-21 04:39 UTC
OJS Version : ojs-3.2.1-2

When section editor chooses, revisions required which are subject to the new round of peer review as below
![image](https://user-images.githubusercontent.com/6085016/105279555-cebf5100-5bcd-11eb-983d-e95ee1739ea1.png)

Then when user logins, he is shown as below
![image](https://user-images.githubusercontent.com/6085016/105280244-5063ae80-5bcf-11eb-8285-d86d76673034.png)

and when he clicks the upload file to submit the revision, he is shown access denied.
![image](https://user-images.githubusercontent.com/6085016/105280480-e39ce400-5bcf-11eb-953a-5c5e596762ae.png)

PS:
I have even tested with the latest development code of OJS. Even in the present development version, the author is shown access denied.

**Comment by NateWr** [comment] 2021-01-21 12:57
Thanks for reporting @gireeshcse. I think this is a duplicate of https://github.com/pkp/pkp-lib/issues/6529. The fix should go out with the next stable version (3.2.1-3).

**Closed by NateWr** 2021-01-21 12:57 UTC

**Comment by gireeshcse** [comment] 2021-01-22 04:57
Thanks @NateWr  for the info about the fix regarding the issue
