### ISSUE TITLE
Administrator cannot upload Site Logo

### ISSUE THREAD

**Issue by navotera** [pkp/pkp-lib#4279] opened 2018-12-01 09:54 UTC
hi..

Why administrator role cannot upload Main Site Logo ? 

i got this message : The current role does not have access to this operation.
**xhr output : ** {"status":false,"content":"The current role does not have access to this operation.","elementId":"0","events":null}

never touch anything related on role access.

My OJS Version :  3.1.1.4 on Localhost

![image](https://user-images.githubusercontent.com/1424851/49326762-1ae44d00-f592-11e8-9eda-9000e3251640.png)

thanks

**Comment by bozana** [comment] 2018-12-04 12:16
Hmmm... Somehow I cannot reproduce it... :-\ 
When exactly does this message appear? -- When you click on the button "Upload" or later?
Are you 100% sure you are logged in as admin user?
Hmmm....

**Comment by bozana** [comment] 2018-12-04 12:35
Hi @navotera, s. this forum post i.e. you would maybe need to apply the patch...
Also, please first search after an answer in the forum and/or ask there. If it is then a real bug a GitHub Issue can be opened.
Thus, I will close this now...

**Closed by bozana** 2018-12-04 12:35 UTC

**Comment by navotera** [comment] 2018-12-06 00:54
Great. 

This link give me hint : https://github.com/pkp/pkp-lib/commit/9e35b17fd7c7c721ef5de4cf3d57f52b4980288a

i wonder i already install the latest PKP version. 
Current Production Release (September 11, 2018)

    Download OJS 3.1.1-4 (.tar.gz) (24 MB)


but why this script still need to add manually or not being patched ? 

thanks

**Comment by bozana** [comment] 2018-12-06 09:03
That patch came after the release, as a bug fix for that release...

**Comment by navotera** [comment] 2018-12-06 10:53
Ok thank you
