### ISSUE TITLE
Can't Export Issues

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1805] opened 2016-09-08 18:34 UTC
I'm using the Demo Journal installation for this - http://journals.sfu.ca/present3/index.php/demojournal/

Logged in as pkpadmin

Go to Tools > Import/Export > Native XML Plugin > Export Issues

I select the issue and hit Export Issues and get a browser error in Chrome:

The journals.sfu.ca page isn’t working
journals.sfu.ca is currently unable to handle this request.
HTTP ERROR 500

In Firefox, I just get a white screen.

**Comment by bozana** [comment] 2016-09-12 08:06
For some reason, most of the files in that installation have no "uploader_user_id" :-O A user is expected, s. https://github.com/pkp/pkp-lib/blob/master/plugins/importexport/native/filter/SubmissionFileNativeXmlFilter.inc.php#L110 and calling the method getUsername() on that user object (that does not exist) leads to an error.
How are those files uploaded?

**Comment by stranack** [comment] 2016-09-12 14:54
Those files would have been uploaded sometime back in 2005 or 2006, so they pre-date the quick submit plugin or possibly even the expedited submission process. I can't remember for certain, but expect it was done while "logged in as" an author.

If this is a one-time problem for this specific installation, I can figure out a workaround.

**Comment by asmecher** [comment] 2016-09-12 18:49
Those would have come from an OJS 2.x installation via the upgrade process. We don't necessarily have the uploader's user/user group, so there's not an especially good solution, I fear. The `Upgrade.inc.php` script finds a Journal Manager and uses their user ID / user group ID for supplementary content; I suppose we could either do the same for other files, just in order to enforce consistently *having* data (even if it's not good), or we could reexamine in both cases.

**Comment by bozana** [comment] 2016-09-13 11:19
Hmmm... As far as I can see, the files in OJS 2.4.x do not have a user assigned to them, right? Thus the files will have uploader ID = NULL after the migration, except the supplementary files. 
Is there another place in the system where the uploader is needed, except the native export/import?
I believe it would be OK to enforce having data there -- just that all files from 2.4.x would then have a journal manager as an uploader, which is not quite correct, but... maybe better then NULL? To try to map a user based on the file stage would also be not quite right/clear/unique, thus this would probably be as random as assigning a journal manager.
In 3.x there will always be an uploader, also when importing issues, thus just the migration from 2.4.x is a problem.
Again, just my thinking... :-)

**Comment by bozana** [comment] 2016-09-13 12:41
Hmmm...  @asmecher and @stranack, I manually fixed the missing uploader in the DB, but now the export is failing because a lot of files do not have a name which is required by our XML schema. This will be a little bit more difficult to fix. Also, the files in this installation seem not to be clear -- for example, one also cannot see them via the UI. I am not sure if they are all needed, but maybe it would be best to have fresh new OJS 3.0 installation?
@asmecher, are file names also missing from the migration?

**Comment by stranack** [comment] 2016-09-14 01:11
I'm fine with starting with a fresh installation, and we can add the content manually. Let me know, though, as I will ask Janna to stop working with that installation until it is replaced.

**Comment by bozana** [comment] 2016-09-14 12:08
@asmecher, what do you think?

**Comment by asmecher** [comment] 2016-09-16 23:45
If there are upgrade issues -- no surprise, I expect we'll have to tune the upgrade code for a few releases -- better to fix them than to avoid them by cleaning out this installation. @bozana, is this the original filename, or the server filename?

**Comment by bozana** [comment] 2016-09-19 09:33
@asmecher, it is the name of the file that is in the file_settings table i.e. something like "`jmanger1, journal manager, blabla.pdf`" i.e. when function `$file->getName(null)` is used :-) I am not sure if these are only upgrade problems -- for example, why are those (a lots of) files not visible via UI? Also, for example, there are soooooo many users -- are they really needed? But I agree that we should maybe fix the upgrade problems :-)

**Comment by bozana** [comment] 2016-09-19 13:29
@asmecher, it is the name of the file that is in the file_settings table i.e. something like "`jmanger1, journal manager, blabla.pdf`" i.e. when function `$file->getName(null)` is used :-) I am not sure if these are only upgrade problems -- for example, why are those (a lots of) files not visible via UI? Also, for example, there are soooooo many users -- are they really needed? But I agree that we should maybe fix the upgrade problems :-)

**Comment by bozana** [comment] 2016-09-19 13:30
@asmecher, I fixed those file upgrade problems mentioned here, in this issue, s. https://github.com/pkp/ojs/pull/1017.

**Comment by asmecher** [comment] 2016-09-20 02:25
@bozana, I think the number of users is because the installation doesn't/didn't have ReCAPTCHA testing enabled...

**Comment by bozana** [comment] 2016-09-22 10:07
@stranack, the upgrade fix is in the ojs-stable-3_0_0, so if the server would have the recent ojs-stable-3_0_0 branch and if then the DB upgrade `php tools/upgrade.php upgrade` would be executed the export problems should be solved. Please let me know if I should do it or somebody else (who does it more often on the serves)...

**Comment by stranack** [comment] 2016-09-23 20:17
Maybe I tried this too soon?

When I download the issue, it displays the XML in my browser. Is it possible to get a .XML file to download?

When I upload the XML file, I get the following errors:

Validation errors:

    Namespace prefix xsi for schemaLocation on issue is not defined
    Namespace prefix xsi for schemaLocation on issue_galleys is not defined
    Namespace prefix xsi for schemaLocation on articles is not defined
    Namespace prefix xsi for schemaLocation on authors is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on article_galley is not defined
    Namespace prefix xsi for schemaLocation on article_galley is not defined
    Namespace prefix xsi for schemaLocation on authors is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on article_galley is not defined
    Namespace prefix xsi for schemaLocation on article_galley is not defined
    Namespace prefix xsi for schemaLocation on authors is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on article_galley is not defined
    Namespace prefix xsi for schemaLocation on article_galley is not defined
    Namespace prefix xsi for schemaLocation on authors is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on submission_file is not defined
    Namespace prefix xsi for schemaLocation on article_galley is not defined
    Element 'issue': No matching global declaration available for the validation root.

I'm logged in as pkpadmin, downloading XML from the "demojournal" and trying to upload to "boot3".

**Comment by bozana** [comment] 2016-09-23 20:22
@stranack, when XML is displayed in the browser, you can right click with the mouse and then choose "Save Page As...". That should download the XML. 
I don't know what is this import message, but could you please confirm that the same happens when you download the XML file this way? How did you create that XML file for import?

**Comment by bozana** [comment] 2016-09-23 20:24
@asmecher , maybe we should change those exports, not to show the XML, but to provide it for download?

**Comment by bozana** [comment] 2016-09-23 20:34
@stranack, I just did it as described two comments above and it worked. Thus it was probably something with the XML import document -- maybe you copied it from the browser into a file or ... ?

**Comment by asmecher** [comment] 2016-09-23 20:38
> @asmecher, maybe we should change those exports, not to show the XML, but to provide it for download?

Yes -- that was just an oversight (probably on my part).

**Comment by stranack** [comment] 2016-09-23 20:41
Thanks @bozana -- doing the Save Page As worked!

@asmecher I agree that it would be better to provide a downloadable file.

**Comment by bozana** [comment] 2016-09-23 20:42
OK, I will change in the big issue 1709 ;-)

**Comment by bozana** [comment] 2016-09-23 20:44
@stranack, can this issue then be closed?

**Comment by stranack** [comment] 2016-09-23 20:49
One more thing - it looks like the PDFs aren't loading. I just get a blank page:
http://journals.sfu.ca/present3/index.php/boot2/article/download/522/61

**Comment by bozana** [comment] 2016-09-23 20:59
Hmmm... yes, for some reason the PDF file reference (i.e. something like `<submission_file_ref id="485" revision="1"/>`) is missing in the export XML :-O so they of course could not be imported i.e. linked to the imported PDF galleys. I'll have to investigate why...

**Comment by bozana** [comment] 2016-09-23 21:16
@asmecher, could it be, that we forgotten to consider assoc_type and assoc_id for galley files for migration? -- The galley files have NULL in this columns in the DB. They are correctly linked in the galley grid on the production page, probably because the data in the table submission_galleys (e.g. file_id) is there, but for the export the table submission_files is searched after the appropriate assoc_type and assoc_id.

**Comment by bozana** [comment] 2016-09-23 21:21
@stranack, please stop finding bugs! ;-) Thanks! :-)

**Comment by bozana** [comment] 2016-09-23 21:42
PR for galley files fix:
master: https://github.com/pkp/ojs/pull/1025
ojs-stable-3_0_0: https://github.com/pkp/ojs/pull/1026
@asmecher, if you think this is correct, please merge... THANKS!

**Comment by asmecher** [comment] 2016-09-23 22:40
> @asmecher, could it be...

It's entirely possible :)

I think the code (front end, workflow) cares about `galley` entries linking to `submission_files` via the `galleys.file_id` column -- if the import/export tools use `submission_files.assoc_id`/`assoc_type`, then they're outliers. In that case, maybe it would be better for them to stop using `assoc_type`/`assoc_id` entirely and go instead with `galleys.file_id`. Or am I missing the point? Entirely possible.

**Comment by bozana** [comment] 2016-09-26 11:21
Aaaa, OK, I will then change this in the native export accordingly... Thanks!!! :-)

**Comment by bozana** [comment] 2016-09-26 12:03
@asmecher, I changed it and added the change to this PR: https://github.com/pkp/ojs/pull/1025

**Comment by bozana** [comment] 2016-10-12 14:20
@stranack, the fixes are not in the ojs-stable-3_0_0 branch. With the current stable branch and after the `php tools/upgrade.php upgrade` this shouldn't happen any more. The problem is just, that the data from the old import attempts cannot be changed any more i.e. is still there.

**Comment by bozana** [comment] 2016-11-10 13:31
@stranack, could this issue be closed?

**Comment by bozana** [comment] 2017-01-20 20:02
I will then close this issue and if there is something else, we can reopen it i.e. open a new one...

**Closed by bozana** 2017-01-20 20:02 UTC
