### ISSUE TITLE
[OMP] Site index should list all presses

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#5784] opened 2020-04-24 08:47 UTC
Discussion https://forum.pkp.sfu.ca/t/omp-site-index-redirects-to-login-page/43392/6

- if only one `press`, automatic redirect from `index` to `press`
- if more than one `press` index shows press listing, but you can do a redirect from `index` to a specific `press` from `Administration > Site settings > Site setup`

**Comment by ajnyga** [comment] 2020-05-13 07:15
I will move most of the indexHandler and the Handler->getTargetContext() code to the shared library. All three applications will then handle one context / multiple contexts with the same logic as OJS does at the moment.

**Comment by asmecher** [comment] 2020-05-13 17:38
(Another forum thread: https://forum.pkp.sfu.ca/t/show-multiple-presses-on-omp/51253)

**Comment by ajnyga** [comment] 2020-05-15 14:11
@asmecher if this looks ok, I can do a pr for OJS and OPS as well: 
OMP: https://github.com/pkp/omp/pull/799
pkp-lib: https://github.com/pkp/pkp-lib/pull/5881

**Comment by ajnyga** [comment] 2020-05-25 12:13
@asmecher there was a conflict in pkp-lib now, so I rebased and started the tests again.000

If this looks ok, I can do a pr for OJS and OPS as well and we can maybe get this merged for 3.2.1?
OMP: pkp/omp#799
pkp-lib: #5881

**Comment by asmecher** [comment] 2020-05-25 16:11
The tests are failing, but it looks like it's not the pkp-lib conflict... I've added a `master` submodule update to check whether the problem is upstream of these changes.

**Comment by ajnyga** [comment] 2020-05-26 10:27
Restarted tests:
OMP: pkp/omp#799
pkp-lib: #5881

**Comment by ajnyga** [comment] 2020-05-26 15:08
@asmecher the tests worked now.

**Comment by ajnyga** [comment] 2020-05-26 15:09
So if the code above is ok, I can pr this for OPS and OJS as well.

**Comment by asmecher** [comment] 2020-05-26 18:10
Thanks, @ajnyga -- just one tiny comment and then it's all ready. This will be great to include -- a few people have asked about it recently (and it reconciles OJS/OPS/OMP behaviour).

**Comment by ajnyga** [comment] 2020-05-28 14:45
pkp-lib: https://github.com/pkp/pkp-lib/pull/5881
OMP: https://github.com/pkp/omp/pull/799
OPS: https://github.com/pkp/ops/pull/35
OJS: https://github.com/pkp/ojs/pull/2781

@asmecher

**Comment by asmecher** [comment] 2020-05-28 16:19
Thanks, @ajnyga -- all merged! After 3.2.1 is out, let's get rid of the app-specific `Handler` class entirely, and rename `PKPHandler` to `Handler` in `pkp-lib`. Three fewer files :+1:

**Closed by asmecher** 2020-05-28 16:19 UTC
