### ISSUE TITLE
Tasks list empty and does not load recent tasks

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#4744] opened 2019-05-08 22:22 UTC
**Describe the bug**
The tasks list remains empty even though the task list counter is non-zero.

**To Reproduce**
Following the suggestion in the [forum](https://forum.pkp.sfu.ca/t/task-notification-error/40733), we checked the DB for null user_id columns in the notes table. All of the null user_id notes are tied to either Copyediting or Proofreading discussions and the note date_created values correspond to the date of the journal's upgrade from 2.4.3 to 3.1.0, i.e.

`mysql> SELECT DISTINCT nt.note_id, nt.date_created, nt.date_modified, nt.user_id, level, type, nt.assoc_type, nt.assoc_id, nt.title FROM notifications n JOIN queries q ON (n.assoc_type = 1048586 AND n.assoc_id = q.query_id) JOIN notes nt ON (nt.assoc_type = 1048586 AND nt.assoc_id = q.query_id) LEFT JOIN users u ON (nt.user_id = u.user_id) WHERE nt.title RLIKE 'Copyediting';`
```
+---------+---------------------+---------------------+---------+-------+----------+------------+----------+------------------------------------+
| note_id | date_created        | date_modified       | user_id | level | type     | assoc_type | assoc_id | title                              |
+---------+---------------------+---------------------+---------+-------+----------+------------+----------+------------------------------------+
|    1132 | 2018-06-28 14:58:22 | 2018-06-28 14:58:22 |       0 |     3 | 16777250 |    1048586 |      962 | Copyediting                        |
|    1292 | 2018-06-28 14:59:46 | 2018-06-28 14:59:46 |       0 |     3 | 16777250 |    1048586 |     1122 | Copyediting                        |
|    1298 | 2018-06-28 14:59:49 | 2018-06-28 14:59:49 |       0 |     3 | 16777250 |    1048586 |     1128 | Copyediting
```

**What application are you using?**
OJS 3.1.1-4

**Additional information**
The error log includes the following:
`PHP Fatal error:  Call to a member function getFullName() on null in lib/pkp/classes/notification/managerDelegate/QueryNotificationManager.inc.php on line 68`

**Comment by asmecher** [comment] 2019-05-08 22:35
This is a duplicate of https://github.com/pkp/pkp-lib/issues/4674.

**Comment by mfelczak** [comment] 2019-05-08 22:39
Thanks @asmecher! Although the patch at #4674 should address the immediate issue with the tasks display, this looks like it may also be an OJS 2 > OJS 3 upgrade issue, i.e.

```
mysql> SELECT COUNT(*) FROM notes WHERE user_id = 0 and title RLIKE 'Copyediting';
+----------+
| COUNT(*) |
+----------+
|      492 |
+----------+
1 row in set (0.00 sec)

mysql> SELECT COUNT(*) FROM notes WHERE user_id != 0 and title RLIKE 'Copyediting';
+----------+
| COUNT(*) |
+----------+
|       22 |
+----------+
1 row in set (0.00 sec)
```

**Comment by mfelczak** [comment] 2019-05-08 22:50
Re-opening to track possible upgrade issue, but happy to open a separate issue if that's helpful.

**Comment by asmecher** [comment] 2019-05-09 00:39
@mfelczak, I think `user_id=0` in signoffs/tasks migrated from OJS2 may be a necessary evil due to a mismatch in the amount of data tracked in OJS3 compared to OJS2. In OJS3, query content always has a specific author (IIRC); during the upgrade, however, query data is populated from OJS2's signoffs structure, which doesn't always have a specific user attached to it.

**Comment by NateWr** [comment] 2022-09-12 16:47
Closing this as outdated. If you need help with a similar problem, please post in our [community support forum](https://forum.pkp.sfu.ca/c/questions/5).

**Closed by NateWr** 2022-09-12 16:47 UTC
Labels: Hosting, Bug:1:Low
