### ISSUE TITLE
OJS 3.3rc - Delete a journal confirmation modal remains upon confirmation

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#6593] opened 2021-01-14 01:59 UTC
**Describe the bug**
When deleting a journal from a multi-journal installation, the confirmation modal does not disappear and provides no user feedback after clicking OK.

**To Reproduce**
1. As an admin user, go to 'Administration' -> 'Hosted Journals'
2. Click on on a journal and select 'Remove.'
3. Click 'OK' to confirm journal removal.
4. Journal will be deleted but modal will remain indefinitely.

**What application are you using?**
 OJS, OMP or OPS version 3.3rc

**Additional information**
Confirmation modal:
![Screen Shot 2021-01-13 at 5 55 35 PM](https://user-images.githubusercontent.com/20844845/104534219-b4331980-55c8-11eb-8292-0a18c7382e9a.png)

**Comment by NateWr** [comment] 2021-01-14 11:07
Duplicate of https://github.com/pkp/pkp-lib/issues/6577

**Closed by NateWr** 2021-01-14 11:07 UTC
Labels: Bug
