### ISSUE TITLE
[OJS] Wrong submissionUrl in copyedit request

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2383] opened 2017-03-24 16:19 UTC
OJS 3.0.2.

One of our editors noticed that the copyedit request message had a wrong `submissionUrl` in it. The url was a reviewer url and when the copyeditor tried to click it she of course had a error message: http://site.com/journal/reviewer/submission/545454

The reason was a interesting combination of things. The `submissionUrl` is set here:
https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php#L177

And that function defines here if a reviewer url should be used:
https://github.com/pkp/pkp-lib/blob/master/controllers/grid/submissions/SubmissionsListGridCellProvider.inc.php#L241

In this particular case the editor had done a review as well and the code on line 241 has a typo:
`$reviewAssignment = $reviewAssignmentDao->getLastReviewRoundReviewAssignmentByReviewer($submission->getId(), $request->getUser()->getId());` 
should be:
`$reviewAssignment = $reviewAssignmentDao->getLastReviewRoundReviewAssignmentByReviewer($submission->getId(), $user->getId());` 

pr: https://github.com/pkp/pkp-lib/pull/2384/files

**Comment by asmecher** [comment] 2017-03-29 21:05
Good spotting as always, @ajnyga -- merged and cherry-picked to `ojs-stable-3_0_2`.

**Closed by asmecher** 2017-03-29 21:05 UTC

**Comment by asubkhankulov** [comment] 2017-05-22 07:58
OJS 2.x - is same problem. Fix it, please.

**Comment by asmecher** [comment] 2017-05-24 19:17
@asubkhankulov, I'm not sure the issue is exactly the same in OJS 2.x. Can you describe your situation in more detail, i.e. what version of OJS are you using, what email demonstrates the problem, etc?
