### ISSUE TITLE
[OJS] Review marked as (response) overdue even if reviewer has accepted the assignment

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2275] opened 2017-02-09 10:18 UTC
In OJS 3.0.2. when you set a response due date and the reviewer **accepts** the assignment the status is still shown as " Overdue Response due: 2017-02-05".

If I edit the same accepted assignment and set the response date to a future date, the status message shows: "Request Accepted Review due: 2017-03-02".

So clearly there is something wrong there.

**Comment by ajnyga** [comment] 2017-02-09 10:43
This is a pr I did https://github.com/pkp/pkp-lib/pull/2276
@bozana or @asmecher, could you look at this?

**Comment by bozana** [comment] 2017-02-09 16:10
Thanks @ajnyga! Merged. I can cherry-pick it to ojs-stable-3_0_2, maybe even omp-stable-1_2...

**Comment by bozana** [comment] 2017-02-09 16:30
PRs in pkp-lib:
master: https://github.com/pkp/pkp-lib/pull/2276
ojs-stable-3_0_2: https://github.com/pkp/pkp-lib/pull/2277
omp-stable-1_2_0: https://github.com/pkp/pkp-lib/pull/2278

**Comment by bozana** [comment] 2017-02-09 16:31
everything merged, thus the issue can be closed...

**Closed by bozana** 2017-02-09 16:31 UTC

**Comment by Alinex29** [comment] 2017-07-12 11:12
This problem is still happening in my case (version 3.0.2)
Even when the reviewers accept the request, it still shows Overdue

**Comment by bozana** [comment] 2017-07-12 12:07
@Alinex29, yes, I think this was fixed after the release. Did you apply the patch above?

**Comment by Alinex29** [comment] 2017-07-13 13:53
My admin applied the patch (I thought he already did that). It's working now.
Thanks!

**Comment by Talgar** [comment] 2018-02-21 05:03
@bozana Hi, My OJS version is 3.0.2.0, How do I apply the патч? should I update the whole website to the new release or just change the certain PHP file? sorry for the noob question, I don't have a hight developer skill but have to work as an admin/developer.  Thanks.

**Comment by Talgar** [comment] 2018-02-21 05:03
@bozana Hi, My OJS version is 3.0.2.0, How do I apply the patch? should I update the whole website to the new release or just change the certain PHP file? sorry for the noob question, I don't have a hight developer skill but have to work as an admin/developer.

**Comment by bozana** [comment] 2018-02-21 11:58
Hi @Talgar 

You would need to change the code like here: https://github.com/pkp/pkp-lib/pull/2277/commits/ff05bc03d3c6df522b8b013e9e530ce22d6e9844 i.e. to add  `&& !$reviewAssignment->getDateConfirmed()` in that code line in lib/pkp/controllers/grid/users/reviewer/ReviewerGridCellProvider.inc.php. Because it is not a big change, you could do it manually.

In general if you would like to use the `patch` tool, you would use/save the `diff`, e.g. https://github.com/pkp/pkp-lib/commit/ff05bc03d3c6df522b8b013e9e530ce22d6e9844.diff. Patch command should then be executed from your OJS or like in this case form the lib/pkp folder, something like: `patch -p1 < that.diff`. 

In general it would also be good to work with `git` on the server, then you could more easily get the actual commits...

If you would have the possibility, it would be good to update to the new OJS version -- it contains a lots of but fixes and function improvements...

**Comment by oldfrank76** [comment] 2018-02-21 15:54
Hi @bozana, thank you for taking the time to help us and thank you for your hard work.
