### ISSUE TITLE
OJS 3.2.1.1: multi-domain, multi-journal installation: issues from journal A can be accessed from the domain of journal B

### ISSUE THREAD

**Issue by janpieterk** [pkp/pkp-lib#7180] opened 2021-07-12 14:41 UTC
OJS 3.2.1.1. Two journals with a custom domain in one installation:

```
base_url = "https://maindomain.tld"
base_url[index] = https://maindomain.tld/index
base_url[abc] = https://customdomain1.tld
base_url[def] = https://customdomain2.tld
restful_urls = On
```

Let’s say that issue ID 123 belongs to journal abc. This is the correct way to view that issue in the browser:

1. https://customdomain1.tld/view/issue/123

However, the following URL also works:

2. https://customdomain2.tld/view/issue/123

And this shows issue ID 123 as belonging to the wrong journal (def instead of abc). There does not seem to be a check if the isssue being requested actually belongs to the domain in the URL.

Expected behaviour would be to receive a 404 when accessing URL 2.

Same behaviour occurs in OJS 3.3.0.4.

**Comment by NateWr** [comment] 2021-07-13 09:02
@asmecher we've got a row for this in our Roadmap ("Refactor URL routing to prevent cross-journal URLs"), but I don't have a good sense of the problem. I've linked to this in our Roadmap now and assigned it to the Multi-tenant project. Would you be able to provide a brief description of the technical challenges here?

**Comment by asmecher** [comment] 2021-07-16 21:24
@janpieterk, the `base_url` directives in `config.inc.php` instruct OJS in how to generate outgoing links, but it's the `mod_rewrite` side of things (e.g. `.htaccess`) that routes requests into OJS; I think that's the part that needs adjustment here. What `mod_rewrite` / virtual hosting rules are you using?

**Comment by asmecher** [comment] 2021-07-16 21:31
Actually, on closer inspection, this appears to be a duplicate of https://github.com/pkp/pkp-lib/issues/6949.

**Closed by asmecher** 2021-07-16 21:31 UTC
Labels: Bug
