### ISSUE TITLE
Submission and Publication Metadata parse Error

### ISSUE THREAD

**Issue by Eimanatas12987** [pkp/pkp-lib#4144] opened 2018-10-15 08:29 UTC
Hi,

can anyone help, I have error then I try to save Submission and Publication Metadata References then I click Extract and Save References the loader is not stoping but if I refresh page old data is saved. I got js error: SCRIPT5655: JSON.parse Error: Invalid character at position:2

jQuery.parseJSON = function( data ) {
	// Attempt to parse using the native JSON parser first
	if ( window.JSON && window.JSON.parse ) {
		// Support: Android 2.3
		// Workaround failure to string-cast null input
		return window.JSON.parse( data + "" );
	}

**Comment by asmecher** [comment] 2018-10-15 15:31
@Eimanatas12987, OJS is sending your browser some invalid JSON. I'd suggest using the browser's developer tools to inspect the JSON response, and look for unexpected content in it. It seems to be right at the beginning of the response.

**Comment by Eimanatas12987** [comment] 2018-10-16 05:04
I got this 2 response:

> {"status":true,"content":"","elementId":"0","events":null}

> {"status":true,"content":"\n<script type=\"text\/javascript\">\n\t\/\/ Attach the JS file tab handler.\n\t$(function() {\n\t\t$('#newIssueEntryTabs').pkpHandler(\n\t\t\t\t'$.pkp.controllers.tab.issueEntry.IssueEntryTabHandler',\n\t\t\t\t{\n\t\t\t\t\tselected:2,\t\t\t\t\ttabsUrl:'https:\/\/journals.vgtu.lt\/index.php\/TEDE\/$$$call$$$\/modals\/submission-metadata\/issue-entry\/fetch-format-info?submissionId=5837&stageId=5',\t\t\t\t\ttabContentUrl:'https:\/\/journals.vgtu.lt\/index.php\/TEDE\/$$$call$$$\/tab\/issue-entry\/issue-entry-tab\/galley-metadata?submissionId=5837&stageId=5',\t\t\t\t\temptyLastTab: true\n\t\t\t\t});\n\t});\n<\/script>\n<div id=\"newIssueEntryTabs\">\n\t<ul>\n\t\t<li>\n\t\t\t<a name=\"submission\" href=\"https:\/\/journals.vgtu.lt\/index.php\/TEDE\/$$$call$$$\/tab\/issue-entry\/issue-entry-tab\/submission-metadata?tab=submission&amp;submissionId=5837&amp;stageId=5&amp;tabPos=0\">Submission<\/a>\n\t\t<\/li>\n\t\t<li>\n\t\t\t<a name=\"catalog\" href=\"https:\/\/journals.vgtu.lt\/index.php\/TEDE\/$$$call$$$\/tab\/issue-entry\/issue-entry-tab\/identifiers?tab=identifiers&amp;submissionId=5837&amp;stageId=5&amp;tabPos=1\">Identifiers<\/a>\n\t\t<\/li>\n\t\t\t\t\t<li>\n\t\t\t\t<a name=\"citations\" href=\"https:\/\/journals.vgtu.lt\/index.php\/TEDE\/$$$call$$$\/tab\/issue-entry\/issue-entry-tab\/citations?tab=citations&amp;submissionId=5837&amp;stageId=5&amp;tabPos=2\">References<\/a>\n\t\t\t<\/li>\n\t\t<\/ul>","elementId":"0","events":null}

**Comment by asmecher** [comment] 2018-10-16 15:09
Hi @Eimanatas12987 -- those are both valid JSON responses. Do they both appear together in one response to one request, or are they from two different AJAX requests?

**Comment by Eimanatas12987** [comment] 2018-10-17 05:09
Yes its together in one request but 2 response.  
![capture_01](https://user-images.githubusercontent.com/26573537/47063496-eab03d00-d1e3-11e8-92f8-bafcb0972542.JPG)
![capture_02](https://user-images.githubusercontent.com/26573537/47063497-eab03d00-d1e3-11e8-8104-e2aae46b1ed2.JPG)

**Comment by bozana** [comment] 2018-10-17 10:28
I cannot reproduce that exact error, but I see there is a problem which the display of your citations URLs: We try to automatically figure out if a citation contains links. If it contains we will leave it as it is. If it does not contain we will search it for the URL pattern, in order to create/display the link. We are looking if the citation contains "<a href", i.e. we do not support other attributes of the HTML element "a" (in your case the "target" attribute). That's why your URLs are not found and displayed twice. 
We could improve this to consider the target attribute as well, but for the moment you would need to remove it, if OK...

**Comment by Eimanatas12987** [comment] 2018-10-17 10:30
But if I type only "123" I get same error

**Comment by bozana** [comment] 2018-10-17 10:55
yes, maybe this has nothing to do with your error -- I couldn't reproduce your error... :-(

**Comment by Vitaliy-1** [comment] 2018-10-17 11:02
Related to: https://github.com/pkp/pkp-lib/issues/4072

**Comment by asmecher** [comment] 2018-10-17 23:54
@Eimanatas12987, what version of OJS are you using? (Is it the master branch of the git repo?)

**Comment by Eimanatas12987** [comment] 2018-10-18 04:48
3.1.1-4

**Comment by NateWr** [comment] 2022-08-25 09:13
Closing this as outdated. If you need help with a similar problem, please post in our [community support forum](https://forum.pkp.sfu.ca/c/questions/5).

**Closed by NateWr** 2022-08-25 09:13 UTC
