### ISSUE TITLE
Recommend By Similarity Plugin doesn't work as expected

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#6122] opened 2020-07-27 10:01 UTC
Related to: https://forum.pkp.sfu.ca/t/related-articles-not-showing/61917/3

The plugin doesn't show similar articles or shows those that aren't related. Tested on OJS 3.2.0 and 3.2.1
While inspecting plugin's code I found that:

- `ArticleSearch::getSimilarityTerms` passes article id to the `SubmissionKeywordDAO::getKeywords` as a first parameter instead of publication id. https://github.com/pkp/ojs/blob/0d27077682624f672ce8bc353de271337afdf792/classes/search/ArticleSearch.inc.php#L313 (if method's annotation is correct here: https://github.com/pkp/pkp-lib/blob/89cd8101bbbcc78d2c576921c4c3f6be9fbe6c1d/classes/submission/SubmissionKeywordDAO.inc.php#L43)

- I think it worth checking `SubmissionSearch::_getMergedKeywordResults`, in particular, this part: https://github.com/pkp/pkp-lib/blob/89cd8101bbbcc78d2c576921c4c3f6be9fbe6c1d/classes/search/SubmissionSearch.inc.php#L145-L158. Although each phrase gives a bunch of items in the `$results`, they often all are being unset for a given submission. I don't know the logic behind that, thus, it may be expected.

**Comment by NateWr** [comment] 2020-07-27 11:12
I didn't think this plugin was supported at the moment, but it looks like it survived the cull of deprecated plugins Alec did a while ago: https://github.com/pkp/ojs/commit/d18ef7393b2ac928dc7d88836601b36640195213#diff-645d5526e2d5b0927e876cf0774f1046.

@asmecher is this a working plugin that we're maintaining?

**Comment by asmecher** [comment] 2020-07-27 21:52
It looks like this plugin was excluded from builds for a while, which means we weren't maintaining it. I removed it from the build exclusion but didn't fix the plugin, which I suspect was a mistake.

I see two options:
- Remove the plugin from github and return to it if/when it's a priority and there's community demand for it, or
- Fix the plugin and continue to maintain it going forward.

I'm leaning towards removing the plugin, especially since it seems to have never been released (except accidentally in 3.2.x), and the inquiries on the forum look exploratory.

**Comment by mfelczak** [comment] 2021-11-17 19:42
Hi @asmecher, just wanted to confirm that the Recommend By Similarity plugin will in fact be deprecated and not included in the upcoming 3.4 release? We've received a couple inquiries about it.

**Comment by asmecher** [comment] 2021-11-18 20:44
@mfelczak, no, I hadn't made that decision. I tested the plugin, fixed the issue noted by @Vitaliy-1, and it works well enough -- I've committed the fix and will include it in 3.4.0.

**Closed by asmecher** 2021-11-18 20:44 UTC

**Comment by mfelczak** [comment] 2021-11-19 13:57
Thanks for the confirmation @asmecher!

**Comment by jnugent** [comment] 2021-11-24 15:18
Hi @asmecher I think I found another bug in the plugin.  This line here:

https://github.com/pkp/ojs/blob/main/plugins/generic/recommendBySimilarity/RecommendBySimilarityPlugin.inc.php#L89

Creates that array but uses a null value as an array key.  We couldn't get this plugin to return any search results in OJS 3.2 and I looked at what the SearchHandler was getting back here:

https://github.com/pkp/ojs/blob/stable-3_2_1/pages/search/SearchHandler.inc.php#L113

And what is there is an array like `array('' => $keywords)` rather than `array(null => $keywords)` in the plugin.  I am not sure if this is a subtle change in PHP behaviour but changing the line in the plugin to use an empty string as the array key (after applying your other fixes in this issue) get the plugin returning results again.

Cheers,
Jason

**Comment by asmecher** [comment] 2022-01-07 23:58
@jnugent, I back-ported the fix to `stable-3_3_0` (https://github.com/pkp/ojs/commit/80a5d563830a50bd6f6a14a563c97f8a66c92fc1) and confirmed that it works, but I'm hesitant to go any further back than that. Can you confirm whether or not `stable-3_3_0` is working as you expect with the above commit (already merged) in place?
