### ISSUE TITLE
"Log out as user" has unresolved {$username} variable on public interface

### ISSUE THREAD

**Issue by jmvezic** [pkp/pkp-lib#6488] opened 2020-12-16 14:50 UTC
**Describe the bug**
The user dropdown menu on the public-facing interface (not editorial/backend interface) has an unresloved {$username} variable when logged in as another user, appearing as:

"Log out as {$username} username"

The link appears correctly in the editorial/backend interface, though.

**To Reproduce**
1. Have journal manager role
2. Go to Users and Roles
3. Login as some other user
4. Go to public interface of the journal
5. In the top right corner under the user dropdown there is an unresloved {$username} variable

**What application are you using?**
 OJS 3.3.0.1. (latest master)

**Comment by asmecher** [comment] 2020-12-16 17:58
Thanks for testing and reporting, @jmvezic! I think that's a duplicate of https://github.com/pkp/pkp-lib/issues/6472.

**Closed by asmecher** 2020-12-16 17:58 UTC
