### ISSUE TITLE
Description of Paperbuzz Plugin in Plugin Gallery talks about Hypothes.is plugin

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#5137] opened 2019-10-09 10:03 UTC
In the OJS Testdrive install, when you click on the Paperbuzz Plugin in the Plugin Gallery, the description is about the Hypothes.is plugin

**Comment by asmecher** [comment] 2019-10-09 14:03
Did you search for the plugin before clicking on it, or find it in the full list?

**Comment by jalperin** [comment] 2019-10-09 14:06
searched

**Comment by asmecher** [comment] 2019-10-09 15:47
That's a duplicate of https://github.com/pkp/pkp-lib/issues/4636.

**Closed by asmecher** 2019-10-09 15:47 UTC
Labels: Dev Housekeeping

**Comment by jalperin** [comment] 2019-10-09 16:24
ack! Sorry, I should have searched.
