### ISSUE TITLE
[OMP] Publication can not be saved without selecting a Series ID

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6477] opened 2020-12-13 17:15 UTC
### Description

In OMP  3.2.1 under Workflow in Publication  metadata:  

After removing the cover image of a submission, saving is not possible.

The  issue is reported in https://forum.pkp.sfu.ca/t/omp-3-2-problem-with-cover-image/61861/8

A temporary workaround  has been suggested too.

### Reason

If  no series is specified, the PUT Request form payload seriesId defaults to 0

e.g.http://localhost/omp/index.php/publicknowledge/api/v1/submissions/12/publications/9

`datePublished=2020-11-29&seriesId=0&seriesPosition=&urlPath=&coverImage%5Ben_US%5D=&coverImage%5Bfr_CA%5D=`

Correctly, the payload should be a non-string, cause the  API seriesId  validates for emptyness and non-zero digits.

`datePublished=2020-11-29&seriesId&seriesPosition=&urlPath=&coverImage%5Ben_US%5D=&coverImage%5Bfr_CA%5D=`

Attachments 

![omp](https://user-images.githubusercontent.com/1921992/102018696-1fda5a80-3d6f-11eb-9139-cf184b5e4cab.gif)

**Comment by NateWr** [comment] 2021-01-14 15:33
After some investigation Dulip and I couldn't reproduce this in 3.3 and for 3.2.x the user can workaround this by selecting the empty series. I'm going to close this, unless anyone thinks this needs to be fixed in the 3.2.x line.

**Closed by NateWr** 2021-01-14 15:33 UTC
Labels: Bug
