### ISSUE TITLE
[OJS] Missing breadcrumbs in static page

### ISSUE THREAD

**Issue by GrazingScientist** [pkp/pkp-lib#4273] opened 2018-11-30 07:51 UTC
When creating a static page in the navigation menu configuration, no breadcrumbs are displayed on the created page.
This was [mentioned in the forum before](https://forum.pkp.sfu.ca/t/breadcrumb-missing-on-sites-created-via-navigation-menu-or-static-sites/42082), but I also stumbled across this issue just now.

## Update (2019-10-07)
All pages in the default theme should have a breadcrumb + a title. See https://github.com/pkp/pkp-lib/issues/4273#issuecomment-539083628

**Comment by asmecher** [comment] 2018-11-30 19:09
@GrazingScientist, I'm ambivalent about breadcrumbs (and we've been relying on them a lot less in OJS 3.x than OJS 2.x). I do note that we're still using them in the reader front end in some cases. @NateWr, do we have a consistent policy on these?

@GrazingScientist, are you proposing that the navigation menu system should impose a hierarchy that's also displayed as breadcrumbs?

**Comment by GrazingScientist** [comment] 2018-12-02 11:06
@asmecher, all I ask for is consistency. :) When I click any of the standard "About us" dropdown links (e.g. "Submission" or "Contact"), there are breadcrumps at the top of the respective page (so "Home / Submission" or "Home / Contact", respectively). But when I create a static custom page (in my case this was necessary to give an overview on "Ethic Guidelines"), these breadcrumps do not appear. I solved this simply by including the breadcrumbs template into the static pages template, but this should be standard, not?

**Comment by asmecher** [comment] 2018-12-06 18:51
When static content appears in the nav menu hierarchy, it is possible for us to assign meaningful breadcrumbs, though I suspect in almost all cases that'll be `Home > Page Title` as per @NateWr 's screenshots, or maybe as good as `Home > Level A > Page Title`, which at least does provide one additional piece of information.

@GrazingScientist, how would yours look by this approach?

**Comment by GrazingScientist** [comment] 2018-12-06 20:53
My version would look just like you proposed. But it keeps the look consistent when you change directly between different links of the "About Us" menu and a static page.

**Comment by NateWr** [comment] 2018-12-13 14:41
I don't think we should use the nav menu hierarchy for breadcrumbs. A single page can appear in different hierarchies in different nav menus on the same site (eg - primary nav and a list of links in the footer).

I'm happy to look at a PR that adds the `Home > Current Page` breadcrumbs to the pages where it's missing.

**Comment by ctgraham** [comment] 2019-09-17 16:41
Bootstrap theme's search page also diverges from the consistent use of breadcrumbs:
https://github.com/NateWr/bootstrap3/blob/b946fd59aa2f535bda3986eed9a7bc5e629d2340/templates/frontend/pages/search.tpl#L21-L25

Noted here:
https://forum.pkp.sfu.ca/t/how-to-insert-hyperlinking-anchors-throughout-an-ojs-3-1-2-site-system-links-inclusive/54263/38?u=ctgraham

**Comment by NateWr** [comment] 2019-10-07 15:59
An accessibility audit that we undertook did not like the use of `<h1>`s inside of the breadcrumbs, so that's a solid reason for us to include breadcrumbs + titles on every page.

**Comment by ctgraham** [comment] 2019-10-07 16:07
> include breadcrumbs + titles on every page

Yes, and getting the `h1` out of the `li` will also enable a cleaner fix for https://github.com/pkp/pkp-lib/pull/5072#issuecomment-534066111 .

**Comment by NateWr** [comment] 2019-10-18 11:10
Hi everyone, thanks for your work on this. A few more things need to happen and I want to make sure they don't get forgotten.

- [ ] The `<h1>` for each page needs to be taken out of the [`breadcrumbs.tpl` file](https://github.com/pkp/pkp-lib/blob/stable-3_1_2/templates/frontend/components/breadcrumbs.tpl#L39). This needs to live inside of each template because it is out of scope for the breadcrumb component.
- [ ] This issue also needs to be addressed in the `breadcrumbs_issue.tpl` and the `breadcrumbs_catalog.tpl` files.
- [ ] This needs to be ported to `master`. 

Generally speaking, I prefer not to merge anything to `stable` until it can be merged to `master` at the same time. If that's not possible, it needs to be assigned to the next major milestone, otherwise it will be forgotten. If we forget to port to `master` we will introduce a regression. For now I've assigned this to the 3.2 milestone so that it is not forgotten.

**Comment by ctgraham** [comment] 2019-10-18 13:09
@NateWr, the `h1` in the breadcrumbs templates is bad, but moving it to each page level template would be far worse.  We are virtually guaranteeing inconsistencies in presentation that way.

My opinion is that the breadcrumbs and `h1` both belong at the end of [header.tpl](https://github.com/pkp/pkp-lib/blob/b61877cc2bc2ba6a5793c495a420851d68da60e5/templates/frontend/components/header.tpl#L102), but that seemed like to large of a jump for a stable or patch release.  I can make that change, if y'all think it appropriate.

My proposal, however, is to continue to live with the unwanted presence of the `h1` in the breadcrumbs templates for 3.1.x, and port a better layout change for 3.2.  If you are ok with moving the breadcrumbs and headers to the minor release, I'll write up PRs for that.

**Comment by israelcefrin** [comment] 2019-10-18 19:21
@NateWr I was about to port this PRs to master branch, I will hold all the porting for the moment. I had merge to stable though. Please, let me know whether you would like from me to remove this modification though.

**Comment by ctgraham** [comment] 2019-10-18 19:24
@israelcefrin , this is only partly merged to stable.  The open PR https://github.com/pkp/ojs/pull/2493 addresses @NateWr 's second task: "This issue also needs to be addressed in the breadcrumbs_issue.tpl and the breadcrumbs_catalog.tpl files."  We're at an inconsistent state currently.

**Comment by NateWr** [comment] 2019-10-21 09:47
@ctgraham I take your point that by moving the `<h1>` into each page template we open the door to inconsistencies. But I think the risk is low. Since I first created the inconsistency in a rash decision several years ago, there's been very little churn on the breadcrumbs/titles and once we resolve it here I doubt there will be much more in the next few years.

I am hesitant to put the `<h1>` in the breadcrumbs or move it all into the `header.tpl` (though this approach also makes sense). That's because each of our templates encapsulates one "unit" of customization. 

When I make a child theme, I can override _just_ the `breadcrumbs.tpl` file or _just_ the `submissions.tpl` file. If the `<h1>` moves in or out of these files, I am faced with a breaking change. But if changes are restricted to these components it also reduces the scope of the breaking changes.

For that reason, I'd prefer to keep the `<h1>` where it is, inside of the page templates, for now, and take these lessons forward to a future default theme.

Having said that, one possible alternative would be to wrap the `breadcrumb.tpl` and the `edit_link.tpl` files into a `page_heading.tpl`, or something like that. That would preserve any single-template overrides while providing more consistency across pages. Something like:

```
<!-- submissions.tpl -->
<div class="page page_submissions">
  {include file="frontend/components/page_heading.tpl" title=$title editLink=$editUrl}
  ...
</div>
```

```
<!-- page_heading.tpl -->
{include file="frontend/components/breadcrumbs.tpl" ...}
<h1>{$title}</h1>
{include file="frontend/components/edit_links.tpl" ...}
```

The downside here is that we're introducing a greater level of abstraction. I tend to think of themes as a simple application and try to avoid too much abstraction. But I'd be comfortable with this as a middle-ground that reinforced consistency while minimizing disruption to existing template customizations.

**Comment by NateWr** [comment] 2019-10-23 10:39
Here are some new PRs against `stable_3_1_2` that make a few adjustments:

- The last item in the breadcrumb is not linked so that we don't have a link to the page we're already on.
- `<h1>` elements are visible everywhere, so every page has breadcrumbs + h1.
- Adds breadcrumbs for announcements and custom pages.
- Adds support for OMP.

PRs:
https://github.com/pkp/pkp-lib/pull/5214
https://github.com/pkp/ojs/pull/2513
https://github.com/pkp/omp/pull/718

@israelcefrin and @ctgraham would one of you be able to port this to `master` for me?

**Comment by ctgraham** [comment] 2019-10-23 12:57
@israelcefrin asserted that moving the `aria-current` attribute from an `a` to the `li` would be [ineffective for screen readers](https://github.com/pkp/pkp-lib/pull/5142#discussion_r335557649), so we might need to add the current page breadcrumb link back in?

**Comment by NateWr** [comment] 2019-10-23 14:28
Ah ok... well I don't think we should add a `<a>` back in, because we don't want a link that leads to the page we're already on.

@israelcefrin can you test the screen reader result with this:

```
<nav>
  <ul>
    <li><a href="#">Home</a></li>
    <li><span aria-current="page">About</span></li>
  </ul>
</nav>
```

Another option is to leave `aria-current` out for stable, since I think a release is imminent, and figure out a solution for `master` at a later date.

**Comment by israelcefrin** [comment] 2019-11-01 18:05
@NateWr this techinique seems to solve it. I have tested using NVDA screenreader on Opera, Edge and Chrome Canary browers. It results on a software speech which says:

> Bullet, link, Home.
> Bullet, current page, About.

It states that the first item ins a link labelled "Home" and the second is a item, no link, which is the current page. At first glance, it is ok.
However, I am not blind and I know what to expect. Maybe a real screenreader user doesn't recongnize it, maybe does. For the moment I think is suffice.

I've also tested this HTML structure against W3C HTMLchecker and no error reported. Yet, they recommend that "aria-current" element should be used with A elements, it doesn't affect HTML validation though.

**Comment by NateWr** [comment] 2019-11-04 12:14
Thanks @israelcefrin! I've rebased the PRs for stable and will merge them when the tests pass. I've also ported it to the `master` branch.

PRs for the `master` branch:
https://github.com/pkp/pkp-lib/pull/5244
https://github.com/pkp/ojs/pull/2524
https://github.com/pkp/omp/pull/726

**Comment by NateWr** [comment] 2019-11-04 16:50
Merged to stable and master. Thanks everyone!

**Closed by NateWr** 2019-11-04 16:50 UTC
