### ISSUE TITLE
[OJS] Automatic review request reminders should be sent in the same language as the original invitation

### ISSUE THREAD

**Issue by fgnievinski** [pkp/pkp-lib#7662] opened 2022-01-31 05:50 UTC
**Describe the bug**
If reviewers don't respond to an invitation to review, they'll get an automatic reminder. The problem is the language will be the journal's default language, which might be different than the language manually selected in the original review invitation.

**To Reproduce**
N/A

**What application are you using?**
 OJS 3.3.0.8

**Additional information**

- This behavior might affect the journal reputation among reviewers who might think the editors are careless and unprofessional.
- It's been reported in the [forum](https://forum.pkp.sfu.ca/t/language-of-the-prepared-email-automated-submission-review-reminder/22629/3?u=fgnievinski), first back in 2016 and most recently in 2020.
- Related issue: https://github.com/pkp/pkp-lib/issues/562

**Comment by asmecher** [comment] 2022-01-31 16:12
This is a duplicate of https://github.com/pkp/pkp-lib/issues/3525.

**Closed by asmecher** 2022-01-31 16:12 UTC
