### ISSUE TITLE
[OMP] Upgrade script for OMP 3.1.1 halts at checkPhpVersion

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#3552] opened 2018-04-05 07:22 UTC
Hi! We are upgrading from OMP 3.1.0 to 3.1.1 and get an error when running the database upgrade script. The full output is this:

```
[pre-install]
[load: upgrade.xml]
[version: 3.1.1.0]
[code: Installer Installer::checkPhpVersion]
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'Upgrade' does not have a method 'checkPhpVersion' in /usr/local/omp/lib/pkp/classes/install/Installer.inc.php on line 415
ERROR: Upgrade failed:
```
Any ideas? We are using git to upgrade.

Edit: I realised that maybe the forum is a better fit for this question, sorry about that.

**Comment by asmecher** [comment] 2018-04-05 14:33
@martinpub, are you sure your `lib/pkp` submodule is on the right branch/tag (to match the OMP repository)?

**Comment by martinpub** [comment] 2018-04-05 16:54
Oh yes, @asmecher, that's most likely the problem, I forgot that. Will try it when I'm back at work, thanks!

**Comment by asmecher** [comment] 2018-04-05 17:07
Pretty sure that's the cause, so I'll close this issue!

**Closed by asmecher** 2018-04-05 17:07 UTC

**Comment by martinpub** [comment] 2018-04-06 06:17
I can confirm this was the issue. Thanks @asmecher.
