### ISSUE TITLE
[OMP] Fatal error when trying to view metadata of a newly added publication format

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8847] opened 2023-03-26 10:54 UTC
**Describe the bug**
When trying to view the metadata tab of a newly added publication format, a fatal error happens:

```php
PHP Fatal error:  Uncaught Exception: PublicationFormatMetadataForm was instantiated without required dependencies. in controllers/grid/catalogEntry/form/PublicationFormatMetadataForm.php:72
Stack trace:
#0 controllers/grid/catalogEntry/PublicationFormatGridHandler.php(639): APP\controllers\grid\catalogEntry\form\PublicationFormatMetadataForm->__construct(Object(APP\submission\Submission), Object(APP\publication\Publication), NULL)
#1 [internal function]: APP\controllers\grid\catalogEntry\PublicationFormatGridHandler->editFormatMetadata(Array, Object(APP\core\Request))
#2 lib/pkp/classes/core/PKPRouter.php(333): call_user_func(Array, Array, Object(APP\core\Request))
#3 lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#4 lib/pkp/classes/core/Dispatcher.php(165): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#5 lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#6 index.php(21): PKP\core\PKPApplication->execute()
#7 {main}
  thrown in controllers\grid\catalogEntry\form\PublicationFormatMetadataForm.php on line 72
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the `Publication tab` of a submission.
2. Go to the `Publication Formats` from the left side tabs.
3. Click on `Add publication format`.
4. Click on the `Metadata` tab of the modal window

**What application are you using?**
OMP 3.3.0/3.4.0rc1/main

**PRs**

[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1465 [Stable-3.4.0]
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1472 [Main]
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1473 [Stable-3.3.0]

**Comment by nils-stefan-weiher** [comment] 2023-09-07 07:52
We also can reproduce the error with the latest `stable-3_4_0` branch in OMP.

**Comment by asmecher** [comment] 2023-09-07 20:42
This actually appears to affect 3.3.0-x as well. @touhidurabir, would you be able to have a look?

**Comment by asmecher** [comment] 2023-09-07 20:43
In the meantime, @nils-stefan-weiher, a work-around is to create a new publication format and *then* return to the metadata tab.

**Comment by touhidurabir** [comment] 2023-09-08 13:06
The cause of issue is we are trying to update/edit the metadata when adding a new publication format that has not yet added from the option `Add publication format` . It's trying to load information about the publication format that not yet exists in the DB . when editing a publication format from the existing list, it works fine .

@asmecher question is do we need to provide the `metadata`  tab in the modal when just adding a new publication as in that case , it has no details yet to edit for metadata ? when editing a new one, it make sense .

**Comment by asmecher** [comment] 2023-09-28 19:41
@touhidurabir, this part of the code is using the old UI toolset, and I don't want to invest much effort into refining it -- so I think for the moment it would be best to hide/disable the `Metadata` tab for newly-created publication formats, and require users to go back into it afterwards with `Edit` if they want to enter that tab.

**Comment by touhidurabir** [comment] 2023-10-02 08:17
@asmecher please review the PR at https://github.com/pkp/pkp-lib/issues/8847#issue-1640861145 . If all ok, need to forward port to main and back port to `stable-3.3.0` .

**Comment by touhidurabir** [comment] 2023-10-09 12:20
@asmecher PRs are done for main, stable-3.4.0 and stable-3.3.0 .

**Comment by asmecher** [comment] 2023-10-12 16:57
Merged, thanks!

**Closed by asmecher** 2023-10-12 16:57 UTC
