### ISSUE TITLE
Suggestion Improvement: Restrict categories to editors

### ISSUE THREAD

**Issue by geniusdesignbrasil** [pkp/pkp-lib#7956] opened 2022-05-27 13:41 UTC
SCENARIO
The categories creation on 3.x version was really amazing, specially to multidisciplinar journals. It was very hard to group submissions by knowledge areas, not by section, without categories. It is very helpful to thematic issues too.

On thematic issues case, after it is published, categories remains available to new submissions, even after the issue has been published. It could be possible to hide selected categorias on submission proccess.
Example: Our editors need a way to [...]

SOLUTION
Enable the function to restrict sections only to editors to the categories.

REQUESTER
Editors

**Comment by NateWr** [comment] 2022-05-30 10:42
Hi @geniusdesignbrasil. Thanks for your suggestion. This is a duplicate of https://github.com/pkp/pkp-lib/issues/6306. Please follow any progress there.

**Closed by NateWr** 2022-05-30 10:42 UTC
