### ISSUE TITLE
[OJS] QuickSubmit in OJS3 breaks custom_section_orders

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2376] opened 2017-03-23 06:32 UTC
Hi,

Tagging @defstat here.

I do not have a detailed description of this yet (I will have more time to look into this new week), but it seems that when adding new articles via quicksubmit plugin the custom section ordering is somehow damaged. 

Basically what happens is that saving a new order for the sections is not always possible. The old order is returned after saving.

I suspect (not confirmed) that what is happening here is that the journals that have encountered the problem have first submitted a few articles and have then done some ordering the issue toc. After this they have proceeded in submitting the remaining articles.

The result is that only a few of the sections are mentioned in the custom_section_orders table for that issue and the ordering is not working. There is maybe se resequence command missing somewhere? I do not know yet. It could even be that this is not a Quicksubmit problem at all.

**Comment by defstat** [comment] 2017-03-23 15:47
@ajnyga I tried to reproduce the issue. 
I reordered the toc of an issue (both sections and articles). After that I imported a new submission using the QuickSubmit plugin, and adding the submission to the issue I had previously reordered. The ordering of sections and articles was as expected. 

I tried that using the master branch of ojs and pkp-lib.
Maybe an older version reacts differently to QuickSubmit plugin submission. I will check with the released branches as well.  

@asmecher 
By the way I found an error on the current master branch of QuickSubmit Plugin - a DAO function has been renamed. As there was no Issue for that I changed it and made a PR pkp/quickSubmit#5

**Comment by asmecher** [comment] 2017-03-23 15:54
Thanks, @defstat -- I merged that. I had made the change locally but forgot to commit/push.

**Comment by ajnyga** [comment] 2017-03-23 17:30
Thanks @defstat 

At the moment I do not have further details about this. We are using 3.0.2 and the latest quicksubmit. I have had two separate journals contact me about not being able to reorder the toc and in both cases they have been using quicksubmit. What they have actually done, I do not know yet. I figured that it could be connected to the scenario I described because in both cases there have been some sections mentioned in the custom_section_order table, but not all of the sections in the toc. 

In both cases the problem is solved simply by removing all the entries concerning the issue from the custom_section_order table and after that the reordering is working fine. Weird stuff.

**Comment by defstat** [comment] 2017-03-23 17:48
@ajnyga I tried to reproduce that scenario on ojs3.0.2, but couldn't. It worked as it supposed to. 

If we have more info on that, we can check again. (not that it matters, but are they using MySql or PostgreSQL?)

**Comment by ajnyga** [comment] 2017-03-31 04:13
Some else experienced the same problem, again with quicksubmit: http://forum.pkp.sfu.ca/t/ojs-3-articles-appearing-in-the-wrong-section-in-the-table-of-contents/29831

**Comment by defstat** [comment] 2017-03-31 06:50
PR pkp/quickSubmit#6

**Comment by ajnyga** [comment] 2017-03-31 06:56
Great, thanks @defstat! I will patch that to our quicksubmit and see if these problems end.

**Comment by defstat** [comment] 2017-03-31 07:31
@ajnyga let me know.

**Comment by ajnyga** [comment] 2017-03-31 07:36
I will, but I could not reproduce the original problem so we will probably know within the next couple of months.

**Comment by defstat** [comment] 2017-03-31 07:59
@ajnyga Well the problem I show and tried to solve with the PR goes as follows:

Let's say you have 2 Sections, and you have reordered them (at issue's TOC let's say issueId=1)
2 rows are added in custom_section_order.

Then try make another Section ("newSection"). 
Go to QuickSubmitPlugin and add a new submission, declaring the newSection as it's section, and declaring it as published to the issueId=1.

After that, go to issueId=1 edit page -> TOC, and reorder the sections there. 

Before the patch the reordering will cause an unexpected behavior, both on articles parent section, and on sections ordering. That seems to be because the reordering procedure of the TOC sections want's the custom_section_order table to have no or all the involved sections. 

You will see that before the patch, there will be no row for the "newSection".

**Comment by asmecher** [comment] 2017-04-03 19:03
Merged, thanks, @defstat -- @ajnyga, let me know how/whether this works for you when you get the chance!

**Closed by asmecher** 2017-04-03 19:03 UTC

**Comment by ajnyga** [comment] 2017-05-03 18:42
Hi @defstat and @asmecher 
One of our journals just reported this issue again, so it seems that the pr above did not fix it.

They described that they first added articles to one section and then reordered those in the issue toc. After that they returned to quicksubmit and added articles to other sections and upon returning to issue toc to reorder function did not work anymore - after saving the original order was restored.

**Comment by ajnyga** [comment] 2017-05-04 06:42
EDIT: Hah, turned out that the patch I made a month ago had failed for some reason and we were still using the original code.

But I was able reproduce the original problem based on the description above and can at least confirm that @defstat's patch here does fix the problem :) So carry on.

**Comment by defstat** [comment] 2017-05-04 07:36
@ajnyga Nice to hear it worked.
