### ISSUE TITLE
[Sprint/UIUX] New Submission Workflow

### ISSUE THREAD

**Issue by robertbeanstalk** [pkp/pkp-lib#4735] opened 2019-05-07 22:00 UTC
**Describe the bug**
User can navigate back to “step one” from “step two” using the submission steps at the top of the viewport to fill out the Submission Requirements form again.

**To Reproduce**
Make a new submission and get to step 2. Then, click on the link for step one.

**What application are you using?**
 OJS 3.2

**Additional information**

**Comment by NateWr** [comment] 2019-05-08 09:53
This is intentional to allow the author to change details they have previously entered. Closing as not a bug.

**Closed by NateWr** 2019-05-08 09:53 UTC
