### ISSUE TITLE
Can't update user biography

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#7545] opened 2021-12-14 16:58 UTC
**Describe the bug**
Bio updates in user profile are not being saved.

**To Reproduce**
1. Go to "Edit profile" -> "Public" tab
2. Change the user bio. 
3. Save changes.
4. Log out.
5. Log in again,
6. Navigate to the "Edit profile" -> "Public" tab.
7. Notice how the update it's no longer saved.

![Profile _ Revista Demonstração](https://user-images.githubusercontent.com/4059679/146043643-6fd5cb1b-b4a7-4feb-a9f6-94483f503d11.gif)

**What application are you using?**
 OJS 3.3.0.8

**Additional information**
Video demo here: https://watch.screencastify.com/v/yjKaBmWdAH9Gh8VFMeQk

**Comment by asmecher** [comment] 2021-12-14 17:04
@alexxxmendonca, I can't reproduce this locally and we haven't had other reports of the same problem; is it possible that one of the 3rd-party plugins is interfering or something? Could you also check the PHP error log for any warnings that appear during the time these actions are taking place?

**Comment by alexxxmendonca** [comment] 2021-12-14 17:20
@asmecher we don't have as much 3rd-party plugins in OJS as we do in OPS. But still, I disabled the ones we do have and the problem persists.

I have requested the PHP error log.

**Comment by alexxxmendonca** [comment] 2021-12-14 17:25
The only error that appears on the error log is this one but the time doesn't match:

[Tue Dec 14 11:46:22.171335 2021] [negotiation:error] [pid 11526] [client 10.81.234.11:64054] AH00690: no acceptable variant: /var/www/submission_scielo_br/htdocs/index, referer: https://submission-bolha.scielo.br/index.php/index/user/profile

**Comment by alexxxmendonca** [comment] 2021-12-14 18:02
@asmecher I am not sure if this error log is the one you need, but it's not showing any errors either:

![image](https://user-images.githubusercontent.com/4059679/146054269-3e032a6e-82b9-4d7e-ac6b-252183a5f062.png)

And I noticed that you don't need to log out of the system to see the error, if you just refresh the page after saving it, the bio is gone/not saved.

**Comment by asmecher** [comment] 2021-12-14 18:44
@alexxxmendonca, can you check the `user_settings` table in the database for that user and see what the entries for `setting_name='biography'` are? In particular I'm curious if the `locale` field is unset or garbled.

**Comment by NateWr** [comment] 2021-12-15 10:03
Confirming that I could not reproduce this in the [3.3.0-8 Test Drive](https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php/testdrive-journal/) site. I'm going to close this as not a bug, but feel free to continue investigating the issue on your site here or on the forum.

**Comment by alexxxmendonca** [comment] 2021-12-15 12:31
Hi @asmecher

> can you check the user_settings table in the database for that user and see what the entries for setting_name='biography' are? In particular I'm curious if the locale field is unset or garbled.

![image](https://user-images.githubusercontent.com/4059679/146187028-979bd88d-6a13-43dc-959c-663d94d13ad6.png)

The "hkjhkj..." is the random keyboard smash that I did.

**Comment by asmecher** [comment] 2021-12-16 21:33
@alexxxmendonca, I'll bet the `0` / `NULL` discrepancy in the `assoc_id` column is to blame. Assuming `user_id=8173` is your test user, can you try the following?
```SQL
DELETE FROM user_settings WHERE user_id=8173 AND setting_name='biography`;
```
This will clear out all entries. After this you should be able to enter a biography again without the `0` / `NULL` entries being in conflict.

If you can confirm that this is the case, I'll look further into the source of the conflicting entries.

**Comment by alexxxmendonca** [comment] 2021-12-17 14:36
Hi @asmecher 

The command was ran and this was the result:

![image](https://user-images.githubusercontent.com/4059679/146560431-3da9561b-c09d-4826-b6f2-d322b7731030.png)

However I tested it again and the behavior is the exact same as before.

**Comment by alexxxmendonca** [comment] 2021-12-17 18:14
@asmecher apologies! It _**did**_ work after the command you suggested.

**Closed** 2021-12-20 10:05 UTC

**Comment by asmecher** [comment] 2021-12-20 20:08
@alexxxmendonca, thanks, that helps; I think that confirms that the issue you're running into is this one: https://github.com/pkp/pkp-lib/issues/7167

**Comment by alexxxmendonca** [comment] 2021-12-21 12:10
@asmecher thanks a lot!
