### ISSUE TITLE
OAI Earliest Datestamp in Identify response showing current timestamp

### ISSUE THREAD

**Issue by marcoblancas** [pkp/pkp-lib#6829] opened 2021-03-05 16:47 UTC
The **Earliest Datestamp in Identity request**  should show the oldest modified date record and is displaying the current date.

We are registering our journal in openarchives.org we get this error in validation step 2.

REQUEST:
https://www.tecnologia-ciencia-educacion.com/index.php/TCE/oai?verb=ListRecords&metadataPrefix=oai_dc&until=2020-03-05T11:50:09Z
GET
FAIL: Failed to extract error code from the response to request:
verb=ListRecords&metadataPrefix=oai_dc&until=2020-03-05T11:50:09Z The request
specified a date one year before the earliestDatestamp given in the Identify
response. There should therefore not be any records with datestamps on or
before this date and a noRecordsMatch error code should be returned.

You can see detailed log errors in http://www.openarchives.org/Register/ValidateSite?log=W76P9VU3

The test failing expect to receive a code error. They try to force the error requesting articles until a year before the first article  and none records are expected. 

![2021-03-05_17-43](https://user-images.githubusercontent.com/5545390/110146063-683b6e80-7dda-11eb-9ec4-9542ec4ae48e.png)

OJS VERSION: 3.3.0.3 (February 20, 2021 - 09:14 PM)

**Comment by asmecher** [comment] 2021-03-05 16:55
This is a duplicate of https://github.com/pkp/pkp-lib/issues/6807.

**Closed by asmecher** 2021-03-05 16:55 UTC
