### ISSUE TITLE
Reviewer stats(?) inaccurate (3.3 testing)

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#6624] opened 2021-01-18 23:59 UTC
As editor in 3.3, when you select your reviewer for an article you get a dialogue with information about the reviewers you're selecting. I'm not totally sure what this is _supposed_ to say because there isn't a test script for it, but what I'm seeing here says this reviewer has been assigned 2 reviews and then a little clock icon that says "never assigned". It seems like "days since assigned" isn't updating... or maybe because it's less than a day it's not counting. I'll check again tomorrow. 

<img width="781" alt="Screen Shot 2021-01-18 at 7 51 35 PM" src="https://user-images.githubusercontent.com/504276/104972255-95b58f80-59c7-11eb-8832-dfcb701abc75.png">

**Comment by NateWr** [comment] 2021-01-19 10:25
Thanks! Yeah, you've sussed it: the days since assigned won't be accurate on the day of the very first assignment. Duplicate of https://github.com/pkp/pkp-lib/issues/4312.

**Closed by NateWr** 2021-01-19 10:25 UTC
Labels: Bug
