### ISSUE TITLE
Metadata page cluttered with section policies

### ISSUE THREAD

**Issue by shubhash** [pkp/pkp-lib#4934] opened 2019-07-18 20:37 UTC
**Describe the bug**
The metadata page is cluttered with section policies of all sections that are defined in the system. It should only display the section policy of the section that the article belongs to or the section that has been chosen in the drop-down menu.

**To Reproduce**
1. Create at least two sections in the journal. Add some text on the section policy field to make sure that they are non-empty.

2. Open any article in the system as an editor.

3. Click on the "Metadata" link near the top of the page.

4. The metadata page will display policies for all available sections.
    
**What application are you using?**
 OJS 3.1.2.1

**Additional information**
Screenshot. 
![metadata](https://user-images.githubusercontent.com/11508412/61490070-5557fa00-a969-11e9-98c5-42b3fcff41f3.png)

**Comment by asmecher** [comment] 2019-07-18 21:08
@shubhash, is this content (e.g. section policies) for a journal that was upgraded from OJS 2.x to OJS 3.x?

**Comment by shubhash** [comment] 2019-07-18 21:37
The sections were created in OJS 2, but the policies were added after the upgrade.

**Comment by ViRuSTriNiTy** [comment] 2019-07-19 13:01
@shubhash This is a duplicate of https://github.com/pkp/pkp-lib/issues/2638#issuecomment-500979705

**Comment by asmecher** [comment] 2019-07-19 16:50
Good spotting, @ViRuSTriNiTy -- I'll leave it for resolution over there.

**Closed by asmecher** 2019-07-19 16:50 UTC
