### ISSUE TITLE
Unassigned JM/JE/Site Admin can't make publication changes when having lower-level roles (OJS 3.3.0.14)

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#9104] opened 2023-06-19 15:30 UTC
**Describe the bug**
Pre 3.3.0.14, a user in JM/JE role NOT assigned to a submission used to be able to take publication-related actions. They still can, but it appears that having additional lower-level roles in that account (e.g. assistant editor-level roles) causes them to face a number of access restrictions, such as:
- not being able to unpublish a submission ("no access to stage" error)
- being able to assign submission to an issue, but not being able to publish it ("no access to stage" error)
- being able to assign a DOI to a submission but not being able to save it 

These restrictions affect an unassigned Site Admin as well who has lower-level roles enabled in addition to JM/JE. 

The problem is solved by either unchecking the lower-level roles in the account OR assigning the account to a submission in a JM/JE role.

**To Reproduce**
1. Log in as JM/JE with additional lower-level (e.g. assistant editor/copyeditor) roles enabled in account 
2. Go to a submission in which you're not assigned (another editor is assigned)
3a. Try scheduling a submission to an issue and publishing
3b. For a published submission - try unpublishing it
4. See "no access to stage" error
5. Go to your user account and uncheck all roles other than JM/JE
6. Return to the submission without assigning yourself to it
7. Repeat 3a/3b - now the actions work and there's no error

![image](https://github.com/pkp/pkp-lib/assets/45104797/52c4e1fb-8249-49bf-8dbb-ae6f0e81d734)

**What application are you using?**
 OJS 3.3.0.14 (the changes was introduced between 3.3.0.11 and 3.3.0.14)

**Additional information**
We have received a number of tickets in PKP|PS related to this issue since 3.3.0.14, mostly from editors who were previously able to make changes without being assigned to a submission and expect to continue to be able to do so.

**Comment by jnugent** [comment] 2023-06-23 17:09
I'm debugging a similar problem for a hosted client and wanted to share some additional insight.  We have an installation running 3.3.0.14 where there is a Section Editor (with role id 17) who is also a reviewer on some other submissions, but not this one.  This Section Editor can perform work within the submission, including work on review rounds, like assigning reviewers, sending emails, etc, but when they attempt to download a review file they are presented with the API black screen of:

![Screenshot at 2023-06-23 14-03-34](https://github.com/pkp/pkp-lib/assets/218719/d26a9719-c098-4312-9aed-9ec256f6e20f)

I've started digging into the role policy code here, which is always eye watering, and noticed that the displayed message is coming from `RoleBasedHandlerOperationPolicy.inc.php`.  The `effect` method calls several private helper methods, which is all fine.  What I don't understand is why a single URL call to download a file, e.g. 

`/index.php/AT-TIJ/$$$call$$$/api/file/file-api/download-file?submissionFileId=2455&submissionId=563&stageId=3`

results in many different applications of that policy.  I've added debugging statements and the `effect` method is called *seven* times, each time with a different set of allowed roles passed in. Why is this?  I'd expect it to be called once, to see if a user has the role needed, and then perhaps add further refinements based on settings for the user role or whether a section editor is allowed to  do certain things.

It feels like there's been a regression made here at some point, although I can't see where since the modification dates on the policies are quite old.

**Comment by Vitaliy-1** [comment] 2023-06-28 13:25
The described problem arises from `StageRolePolicy` logic. The exact line is: https://github.com/pkp/pkp-lib/blob/2c005dedd6914ce4f4f2eb56b5f6912771dc24a8/classes/security/authorization/StageRolePolicy.php#L90
`$userAccessibleStages` isn't empty when Admin/Manager additionally has lower-level roles. E.g., if selecting layout editor (on our test dataset), it has the following values
```php
  1 => [
    16,
    1,
  ],
  3 => [
    16,
    1,
  ],
  4 => [
    16,
    1,
  ],
  5 => [
    16,
    1,
  ],
```

According to the comment above "A manager is granted access when they are not assigned in any other role" and it haven't changed since this policy creation ([initial commit](https://github.com/pkp/pkp-lib/commit/718ad72e597285d2899932efbd1d87635b90efe7#diff-18bfcd7ea939a89af22df58909f3197f7b343cd3ecb5e2fe7e8c83263c2e2cdf) in 2019), meaning that stable-3_2_0 contained that modification and it's for quite long time in the code. 

I can't find any related discussion and intend is not completely clear to me. If assuming that the manager is assigned to a submission with a lower level role that doesn't have access to certain stages and the idea is to restrict access anyway, then it looks like a bug. 

@asmecher, does this ring a bell for you?

**Comment by jnugent** [comment] 2023-06-28 14:29
Hi @Vitaliy-1 thanks for having a look here.  In my case, the section editor in question still could not download a review file on a submission to which they were assigned as editor even after I removed their reviewer role from their user account. 

The line of code you've mentioned seems to apply to a single submission, that is, a manager "in general" will be restricted if they have another lower-privilege role on a submission. That part makes sense and seems to be the case. What we are concerned about is that it seems that managers who possess other roles within the journal get restricted unless these roles are removed from their user accounts.  However in my case doing that didn't make a difference.

**Comment by Vitaliy-1** [comment] 2023-06-28 19:24
Thanks, @jnugent. That sounds like a problem with another policy. I'm looking into it but unable to reproduce neither on main nor stable 3.3.0. Can you open a new issue with reproduction steps?

**Comment by jnugent** [comment] 2023-06-28 19:36
Hi @Vitaliy-1  Mariya provided reproduction steps in her ticket, mine is harder - I cannot reproduce it outside of this particular installation which leads me to believe that it's a combination of data and code.  I can provide you with a link to the installation and access to the server it is on if that would be useful.

**Comment by Vitaliy-1** [comment] 2023-06-28 20:13
Is this a case of failing [SubmissionFileAccessPolicy](https://github.com/pkp/pkp-lib/blob/stable-3_3_0/controllers/api/file/FileApiHandler.inc.php#L48), in particular here: https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/security/authorization/SubmissionFileAccessPolicy.inc.php#L84, and the user has also manager role in the journal?

**Comment by jnugent** [comment] 2023-06-28 20:16
Hi @Vitaliy-1  I figured out my particular problem.  What seems to have happened is that the user was assigned to a submission as one role, and then their user was edited and that role was removed and replaced with a lower editor role.  This creates a weird situation where they can do some things but not others.  To reproduce:

1.  Assign a full journal editor to a submission and put it in the review stage.
2.  Edit this user and remove the JE role but assign them a SE role
3.  Attempt to download files from the submission.  This will fail.  
4.  Remove them from the submission and re-assign them as a Section Editor.
5. They will now be able to download files.

**Comment by ajnyga** [comment] 2023-11-21 19:32
Is this duplicate or related to https://github.com/pkp/pkp-lib/issues/6875

**Comment by librariam** [comment] 2023-11-21 20:12
@ajnyga I don't believe it's a duplicate. This issue is specific to unassigned JM/JE being blocked from making publication changes when they have lower roles enabled. Removing a lower role OR assigning a JM/JE allows them to make publication changes.

It doesn't look like this use case was covered in https://github.com/pkp/pkp-lib/issues/6875 - but could it be a side effect of those changes? We only started seeing this unassigned-specific issue in 3.3.0.14

**Comment by ajnyga** [comment] 2023-11-22 05:45
by "have lower roles enabled" do you mean that they have for example a layout editor role or that they are assigned as a layout editor to the submission?

**Comment by Vitaliy-1** [comment] 2023-12-01 13:31
Should be fixed by https://github.com/pkp/pkp-lib/issues/9131

**Closed by Vitaliy-1** 2023-12-01 13:31 UTC
