### ISSUE TITLE
No access granted for non-expiring subscription

### ISSUE THREAD

**Issue by crowesn** [pkp/pkp-lib#7596] opened 2022-01-06 19:13 UTC
**Describe the bug**

Users with non-expiring subscription are not granted access to subscription content in OJS3.

**To Reproduce**

1. Login as admin
2. Navigate to Payments > Subscription types > Create New Subscription Type
3. Fill out required fields, duration=blank, under __Subscriptions__, check radio button `Individual (users are validated via login)`
4. Click save
5. Navigate to __Settings__ in left sidebar navigate to Distribution > Access
6. Select radio button `The journal will require subscriptions to access some or all of its contents.`
7. Select appropriate number of months to restrict back issues to subscribers under __Delayed Open Access__
8. Navigate to __Payments__ in sidebar and under __Individual Subscriptions__, add subscriber-user with open ended subscription
9. Login as subscriber-user and navigate to subscription-only content.
10. Subscriber-user is rerouted to current page when attempting to access articles (no access to article)

**What application are you using?**

 OJS 3.2.1.1 and __reproduced on the testdrive back-end demo [site](https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php/testdrive-journal) provided by PKP__

OS platform Linux
PHP version 7.3.20
Apache version Apache/2.4.37 (Oracle Linux) mod_fcgid/2.3.9
Database driver mysqli
Database server version 10.3.28-MariaDB

[database]
driver mysqli
port 3306
persistent Off
debug Off

**Additional information**

I think I've identified the line in `IndividualSubscriptionDAO.inc.php` affecting this bug:
https://github.com/pkp/ojs/blob/stable-3_2_1/classes/subscription/IndividualSubscriptionDAO.inc.php#L494

When I change from int 0,1 to "true" or "false" in this literal sql statement, the bug is resolved.
```php
	$result = $this->retrieve('
		SELECT	s.subscription_id
		FROM	subscriptions s
			JOIN subscription_types st ON (s.type_id = st.type_id)
		WHERE	s.user_id = ?
			AND s.journal_id = ?
			AND s.status = ' . SUBSCRIPTION_STATUS_ACTIVE . '
			AND st.institutional = 0
-- change from int to boolean ↓↓
                        AND ((st.non_expiring = "true") OR (st.non_expiring = "false" AND (' . $dateSql . ')))
			AND (st.format = ' . SUBSCRIPTION_TYPE_FORMAT_ONLINE . '
			OR st.format = ' . SUBSCRIPTION_TYPE_FORMAT_PRINT_ONLINE . ')',
		array(
			(int) $userId,
			(int) $journalId
		)
	);
```

https://forum.pkp.sfu.ca/t/non-expiring-indivudal-subscriptions-no-access-to-pdfs-ojs-3-2-1-3/65531

**Comment by crowesn** [comment] 2022-01-06 19:16
Related #6510
Related #3483

**Comment by asmecher** [comment] 2022-01-06 20:24
See also: https://forum.pkp.sfu.ca/t/non-expiring-indivudal-subscriptions-no-access-to-pdfs-ojs-3-2-1-3/65531/2

**Comment by asmecher** [comment] 2022-01-06 20:46
@crowesn, I think swapping the `0` and `1` with `"false"` and `"true"` respectively doesn't fix the problem -- the database column is a `SMALLINT` so I think you're probably just confusing the boolean logic by adding a string to numeric comparison.

The issue is that the `non_expiring` column is no longer populated from the subscription type form since we're now depending on a `null` value in `duration` to identify non-expiring subscriptions. The queries still looking at `non_expiring` can be adapted to check `duration` instead in the following PR:

https://github.com/pkp/ojs/pull/3268

If you could take a look at this and see if it resolves the problem, I can get it committed for the next release.

**Comment by crowesn** [comment] 2022-01-07 01:37
This works, thanks.

**Comment by asmecher** [comment] 2022-01-07 03:43
Thanks for confirming! Merged to `stable-3_3_0` and forward-ported to `main`.

**Closed by asmecher** 2022-01-07 03:43 UTC
