### ISSUE TITLE
"Users" tab always shown when selcting from "Users & Roles" drop-down

### ISSUE THREAD

**Issue by eocarragain** [pkp/pkp-lib#6309] opened 2020-11-02 23:36 UTC
**Describe the bug**
If "Roles" or "Site Access Options" are selected from "Users & Roles" on the left-hand navigation, the "Users" tab is loaded. The user then has to click on the desired tab to access it. I'd expect to be brought directly to the correct tab.

**To Reproduce**
1. Go to the admin area
2. Select "Users & Roles"
3. Select "Roles"
4. You are brought to the "Users" tab

**What application are you using?**
 OJS 3.2.1-1 
Can be replicate in the PKP public testdrive demo instance

_Apologies if this is a duplicate - I couldn't find it either in the forum or on github issues._

Thanks!

**Comment by NateWr** [comment] 2020-11-03 10:12
Thanks @eocarragain. You're right this would be expected behaviour. This will go away with the UI refactor in 3.3, which won't use the dropdown menus anymore. I'm going to flag close this as something we won't fix, just because it's not a big priority and a fix will come with the next major version. Thanks for reporting, though!

**Closed by NateWr** 2020-11-03 10:12 UTC

**Comment by eocarragain** [comment] 2020-11-03 10:57
Good to know re 3.3. thanks
