### ISSUE TITLE
Error log file bloat because of missing some plugin from upgrading to OJS 3.4

### ISSUE THREAD

**Issue by rahmanramsi** [pkp/pkp-lib#9619] opened 2024-01-16 03:17 UTC
**Describe the bug**
error log file is always increasing in size for every request.

**To Reproduce**
1. Upgrade OJS from version 3.3 to 3.4
2. There will be some plugin that is currently not compatible for OJS 3.4. Remove it.
3. For every plugin that's been removed every request it will log an error 

**What application are you using?**
 OJS 3.4.0-4

**Additional information**
Error log that has been bloated by log from OJS
![image](https://github.com/pkp/pkp-lib/assets/48276043/00740e89-ef57-4a71-9679-8f4691895329)

Stack trace
```
[16-Jan-2024 02:28:06 UTC] Exception: Plugin custom expected to inherit from CustomThemePlugin, actual type NULL in /home/royallit/public_html/lib/pkp/classes/plugins/PluginRegistry.php:203
Stack trace:
#0 /home/ojs3404/public_html/lib/pkp/classes/plugins/PluginRegistry.php(219): PKP\plugins\PluginRegistry::_instantiatePlugin()
#1 /home/ojs3404/public_html/lib/pkp/classes/plugins/PluginRegistry.php(112): PKP\plugins\PluginRegistry::_loadFromDatabase()
#2 /home/ojs3404/public_html/lib/pkp/classes/template/PKPTemplateManager.php(1392): PKP\plugins\PluginRegistry::loadCategory()
#3 /home/ojs3404/public_html/lib/pkp/classes/plugins/Plugin.php(403): PKP\template\PKPTemplateManager::getManager()
#4 /home/ojs3404/public_html/lib/pkp/classes/plugins/Plugin.php(137): PKP\plugins\Plugin->_registerTemplateResource()
#5 /home/ojs3404/public_html/lib/pkp/classes/plugins/LazyLoadPlugin.php(34): PKP\plugins\Plugin->register()
```

**Comment by jonasraoni** [comment] 2024-01-16 07:58
Hi @rahmanramsi,

The get rid of this message, the plugin should be disabled at the `plugin_settings` table (after filtering the entries by the `plugin_name` there will be a setting `enabled`, which should be `0`).

I'll close this as a duplicate of https://github.com/pkp/pkp-lib/issues/9573.

**Closed by jonasraoni** 2024-01-16 07:58 UTC
