### ISSUE TITLE
[OPS] Ability to filter submissions by Moderator

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#7175] opened 2021-07-08 13:49 UTC
**Describe the problem you would like to solve**
In OJS 3.3.x, it's possible to filter the submission list by assigned Editor:

![image](https://user-images.githubusercontent.com/4059679/124932860-ccb14900-dfd9-11eb-8626-245fa4dd8ab0.png)

That same feature is not available in OPS 3.3.0-6, however:

![image](https://user-images.githubusercontent.com/4059679/124932984-e488cd00-dfd9-11eb-8f76-fc4a58e8084c.png)

**Describe the solution you'd like**
Having the ability to filter by assigned moderator. 

We work with multiple moderators and it would be extremely helpful to being able to filter down by assigned moderator.

**Who is asking for this feature?**
Preprint Server Administrators.

**Comment by NateWr** [comment] 2021-07-12 12:42
I was unable to reproduce this in `stable-3_3_0`. I see the option to filter by moderator.

![filter-moderator](https://user-images.githubusercontent.com/2306629/125289212-e672c900-e316-11eb-91dd-d5a70d28b3d4.png)

I'll close this for now but let me know if you identify reproduction steps.

**Closed by NateWr** 2021-07-12 12:42 UTC

**Comment by alexxxmendonca** [comment] 2021-07-12 12:49
I was looking at the "My Queue" tab. I realize now it only appears on the "Active" and"Archive" tabs.
