### ISSUE TITLE
Performance issue using LIMIT and OFFSET in search users query

### ISSUE THREAD

**Issue by sourcedump** [pkp/pkp-lib#5288] opened 2019-11-20 13:52 UTC
Hello everyone,
I don't know if this is a bug, but I have performance problems due to a query. I'm using OJS 3.1.2.1 on php 7.3, with more than 27 thousand users, and Postgresql 9.6.15 running on different servers (the one that runs Postgresql has 2CPU and 8GB of RAM). 
When you search for users to enlist them in a journal this query is performed:
```
SELECT DISTINCT u.*,
COALESCE(ugl.setting_value, ugpl.setting_value) AS user_given,
CASE WHEN ugl.setting_value <> '' THEN ufl.setting_value ELSE ufpl.setting_value END AS user_family
FROM users AS u
LEFT JOIN user_settings us ON (us.user_id = u.user_id AND us.setting_name = 'affiliation')
LEFT JOIN user_interests ui ON (u.user_id = ui.user_id)
LEFT JOIN controlled_vocab_entry_settings cves ON (ui.controlled_vocab_entry_id = cves.controlled_vocab_entry_id)
LEFT JOIN user_user_groups uug ON (uug.user_id = u.user_id)
LEFT JOIN user_groups ug ON (ug.user_group_id = uug.user_group_id)
LEFT JOIN user_settings ugl ON (u.user_id = ugl.user_id AND ugl.setting_name =  \$1 AND ugl.locale =  \$2)
LEFT JOIN user_settings ugpl ON (u.user_id = ugpl.user_id AND ugpl.setting_name =  \$3 AND ugpl.locale =  \$4)
LEFT JOIN user_settings ufl ON (u.user_id = ufl.user_id AND ufl.setting_name =  \$5 AND ufl.locale =  \$6)
LEFT JOIN user_settings ufpl ON (u.user_id = ufpl.user_id AND ufpl.setting_name =  \$7 AND ufpl.locale =  \$8)
LEFT JOIN user_settings usgs ON (usgs.user_id = u.user_id AND usgs.setting_name =  \$9)
LEFT JOIN user_settings usfs ON (usfs.user_id = u.user_id AND usfs.setting_name =  \$10)
WHERE 1=1 ORDER BY user_family, user_given LIMIT 25 OFFSET 0;
```

I think from 'lib/pkp/classes/security/UserGroupDAO.inc.php'. This query takes several minutes to finish due to the 'LIMIT 25 OFFSET 0'. I know that because I've made some performance tests and when there is no 'LIMIT OFFSET' the execution time drops to 2 seconds. This behavior causes the repeated submission of the query since users, not seeing results, continue to repeat the selection.

Maybe some index optimization can help? Anyone has reported a similar issue?
Attached the result of explain analyze.

Thank you
![explain](https://user-images.githubusercontent.com/20353276/69244184-cc65ff00-0ba4-11ea-92bd-bf6f6ef821ee.png)
[Analyze.txt](https://github.com/pkp/pkp-lib/files/3869511/Analyze.txt)

**Comment by jonasraoni** [comment] 2019-11-20 17:02
Hi @sourcedump!

Thanks for the report, the limit clause is a performance killer when you have many records, the more you skip the worse it gets. It's possible to fix it, but we've got to discuss the possible approaches with the team, my favorite one is to replace numbered pages by a "previous/next" and control the paging using a reference value (e.g. "where id > id of last record in the current page"). I didn't watch the query yet (I'm typing from a mobile), so maybe an extra index could help as well.

**Comment by tessiof** [comment] 2020-01-29 13:53
We have a bunch of those slow queries on our MariaDB as well. The server load is skyrocketing, and those queries are the ones taking most time to complete.

> Command: Query
    Time: 508
   State: Copying to tmp table
    Info: SELECT DISTINCT u.*,
                                COALESCE(ugl.setting_value, ugpl.setting_value) AS user_given,
                        CASE WHEN

**Comment by asmecher** [comment] 2020-01-29 16:29
This forum thread appears to be related: https://forum.pkp.sfu.ca/t/user-search-query-take-a-long-time/57418

**Comment by defstat** [comment] 2020-03-16 21:20
Hi all.

Analyzing the query, it seems that it performs a series of full table scans on the `user_settings` table, which could become really big at DBs with lots of users. The overall `Query cost` at that point is **182.02**.

![Annotation 2020-03-16 215705](https://user-images.githubusercontent.com/560456/76797607-980ef200-67d6-11ea-94d1-4ab462e5f292.jpg)

The table `user_settings` does not index `setting_name` column.
By creating the index:
`CREATE INDEX user_settings_setting_name_index ON user_settings (setting_name);`

we are getting the following results (`Query cost` -> **8.37**)

![image](https://user-images.githubusercontent.com/560456/76800434-53865500-67dc-11ea-81e7-4dfe3d4932eb.png)

I can proceed with the PR for that change. @sourcedump could you check how that index performs on your database?

**Comment by asmecher** [comment] 2020-03-16 21:28
@defstat, how about both `user_settings` and `user_id`? I would expect all uses to involve both columns. (Really happy to hear this might have an easy solution!)

**Comment by defstat** [comment] 2020-03-16 21:33
@asmecher even though I get the same cost with the addition of the user_id (same with just the setting_name), it could worth adding it.

**Comment by asmecher** [comment] 2020-03-16 21:35
As you like, @defstat!

**Comment by defstat** [comment] 2020-03-16 21:40
We still have the full table scan for users table. If the query is for a users display/management table, ordering by the columns the query is ordering by now, I don't thing we can avoid it.

**Comment by djolemc** [comment] 2020-03-17 07:09
I just tried this query on my DB. With index, execution time drops from 27s to 7s.  But there is no performance improvment when searching for users with no roles (users&roles page). On my local server, execution time is about 1min (I have about 19000 users in test database)

**Comment by defstat** [comment] 2020-03-17 07:13
Thanks for the feedback @djolemc, I will check that page also..

**Comment by djolemc** [comment] 2020-03-17 07:33
Thanks. I just checked on my production server (which is much faster than localhost) ,with 26000 users, search query takes from 30s to 1min, or even never finishes.  This is a huge problem when trying to find user not registered in current journal, or when someone wants to check if user is registered before adding a new user.

I would really appreciate it if you could speed up this query

**Comment by defstat** [comment] 2020-03-17 07:42
@djolemc could you please send me exactly the page that executes the query you are referring to? (a url would be helpful)

**Comment by djolemc** [comment] 2020-03-17 07:55
Sure, 
index.php/vsp/management/settings/access#users

**Comment by sourcedump** [comment] 2020-03-17 08:45
Hello!
I've created the index as suggested by @defstat and I confirm that the execution time now is dropped to few seconds.

Thanks

**Comment by djolemc** [comment] 2020-03-19 07:28
@defstat 

Have you maybe made any progress? Thanks

**Comment by defstat** [comment] 2020-03-19 18:55
@djolemc could you please try 
`CREATE INDEX user_settings_locale_setting_name_index ON user_settings (locale, setting_name);`

**Comment by djolemc** [comment] 2020-03-19 19:57
@defstat 
I just did. No difference at all. About 62 seconds on dev server, about 32 seconds on production server.

![ksnip_20200319-205627](https://user-images.githubusercontent.com/14848370/77109435-304de680-6a24-11ea-8493-a7cae76b80d3.png)

**Comment by defstat** [comment] 2020-03-19 20:47
In fact the cost of the query is dropped from 138 to 19, but that does not always mean a difference into execution time.. with so many users, and the inevitable full scan on the users table, the 30 secs response could be a relatively acceptable time for that query

**Comment by djolemc** [comment] 2020-03-19 21:34
Thanks @defstat 

That's not really encouraging :(  Execution time wil get worse with new users registered.

**Comment by defstat** [comment] 2020-05-12 13:35
@asmecher 

Following the [https://github.com/pkp/pkp-lib/issues/5288#issuecomment-601357665] 

**PRs**
[pkp-lib]: #5859
[OJS]: pkp/ojs#2742
[OMP]: pkp/omp#811
[OPS]: /pkp/ops#22

**Comment by asmecher** [comment] 2020-05-12 15:34
@defstat, thanks, I've merged all this. As part of https://github.com/pkp/pkp-lib/issues/2493 I'm refactoring all the schema descriptors, so this change will need to be reflected there, but I'll take care of that separately. All merged! I'll cherry-pick this back to `stable-3_2_0` as well.

**Closed by asmecher** 2020-05-12 15:34 UTC
Labels: Community Priority

**Comment by gustavotonini** [comment] 2020-10-20 17:33
Hi,
we are using OJS 3.2.1.1 and the user list is very slow even with the "user_settings_locale_setting_name_index" index. We have 40 journals with more than 150k users registered.

Analyzing the query plan, I noticed that if we replace the left joins with user_settings by inner joins, the query cost is reduced dramatically. Query time is reduced from 12s to 0.2s!

I have also noticed that all fields retrieved by user_settings joins are required. So, in my understanding, these left joins could be perfectly replaced by inner joins. Am I right?

**Comment by asmecher** [comment] 2020-10-20 17:37
@gustavotonini, could you open a draft pull request to show where you replaced the joins? I could review them to see whether the change will cause data problems or not.

**Comment by gustavotonini** [comment] 2020-10-21 14:52
@asmecher I was able to make the user list faster by changing the joins in "lib/pkp/classes/user/UserDAO.inc.php", but the user search in all journals is still a big problem. It's taking 30s to complete. I'm trying to find a way to optimize it.


![image](https://user-images.githubusercontent.com/11355672/96737148-b738b800-1393-11eb-8d64-b438bc8d9d26.png)

**Comment by luizbgomide** [comment] 2021-04-23 17:55
Is this actually closed? On 3.3.0.3 the user queries (from `/management/settings/access`) still take a long time, somewhere around 30-40 seconds to query a single journal (4783 users) and a whole lot more (just tested and it took 8: minutes 11 seconds) to get all 27839 users is searching for all journals.

I'm using MySQL 8.0.23 and tables are all InnoDB. I could not run the query above on phpMyAdmin because it complained about the backslashs as unrecognized.

**Comment by asmecher** [comment] 2021-04-23 18:03
@luizbgomide, this issue identified one of the causes of poor performance and resolved it, and since the release of 3.2.1 the query at the top of the issue is no longer accurate. If you're encountering a performance issue with a later release, I'd suggest filing it as a new issue and using the `debug` option in `config.inc.php` to identify the exact query that's being used.

**Comment by luizbgomide** [comment] 2021-04-23 18:21
Thanks @asmecher, the output from degub is just in the httpd.log, right? I got this, but that failed due to the `?` lost in the middle of the code, probably something that wasn't expoted to the appache log!?

```sql
SELECT COUNT(*) AS row_count FROM (SELECT DISTINCT u.*,     COALESCE(ugl.setting_value, ugpl.setting_value) AS user_given,    CASE WHEN ugl.setting_value <> '' THEN ufl.setting_value ELSE ufpl.setting_value END AS user_family    FROM users AS u     LEFT JOIN user_settings us ON (us.user_id = u.user_id AND us.setting_name = 'affiliation')     LEFT JOIN user_interests ui ON (u.user_id = ui.user_id)     LEFT JOIN controlled_vocab_entry_settings cves ON (ui.controlled_vocab_entry_id = cves.controlled_vocab_entry_id)     LEFT JOIN user_user_groups uug ON (uug.user_id = u.user_id)     LEFT JOIN user_groups ug ON (ug.user_group_id = uug.user_group_id)     LEFT JOIN user_settings ugl ON (u.user_id = ugl.user_id AND ugl.setting_name = ? AND ugl.locale = ?)    LEFT JOIN user_settings ugpl ON (u.user_id = ugpl.user_id AND ugpl.setting_name = ? AND ugpl.locale = ?)    LEFT JOIN user_settings ufl ON (u.user_id = ufl.user_id AND ufl.setting_name = ? AND ufl.locale = ?)    LEFT JOIN user_settings ufpl ON (u.user_id = ufpl.user_id AND ufpl.setting_name = ? AND ufpl.locale = ?)     LEFT JOIN user_settings usgs ON (usgs.user_id = u.user_id AND usgs.setting_name = ?)     LEFT JOIN user_settings usfs ON (usfs.user_id = u.user_id AND usfs.setting_name = ?)     WHERE 1=1 AND ug.context_id = ? ORDER BY user_family, user_given) AS count_subquery ["givenName","pt_BR","givenName","pt_BR","familyName","pt_BR","familyName","pt_BR","givenName","familyName",56]
```

**Comment by asmecher** [comment] 2021-04-23 19:25
(Last conversation moved to: https://github.com/pkp/pkp-lib/issues/6991)
