### ISSUE TITLE
[OJS 3.1.2] When switching to english language name and given name of users are not displayed

### ISSUE THREAD

**Issue by Potomac54** [pkp/pkp-lib#4675] opened 2019-04-12 12:41 UTC
Hello,

I use OJS 3.1.2,

I notice a bug when users have been created when primary language of OJS is set to something different than english (for example french) : 

- after creation of users : if the admin selects "english" for translating OJS GUI then if he goes to "Users and roles" section in the backend he will notice that the family name and the given name of each user are not displayed in the "users" tab, it is this page of ojs : 

http://<base_url>/<your_journal>/management/settings/access#users

the bug occurs if the primary language of the OJS installation is not english (for example french), in french all is Ok, but if the admin switches OJS to the second language (english) then the names of the users are not displayed in http://<base_url>/<your_journal>/management/settings/access#users page, I hope my description of the bug is clear

**Comment by asmecher** [comment] 2019-04-17 22:35
@Potomac54, can you confirm whether this matches the description at https://forum.pkp.sfu.ca/t/user-names-missing-in-english-version-after-updating-to-ojs-3-1-2/52174?

**Comment by Potomac** [comment] 2019-04-17 23:23
yes your page matches the description of the bug,

the bug occurs on the page "users and roles",  when users have been created on an OJS installation where primary language is not english, if I switch to english (installed as additional languages) then the family name, the given name, the prefered public name will be not displayed on this page "users and roles",

this bug is easily reproducible, and occurs since OJS 3.1.2

**Comment by bozana** [comment] 2019-04-25 09:39
@Potomac54, what is your installation/site wide primary locale (you can see this only as admin)? Would it maybe be possible for you to see in the database table user_settings for which locale the names exist? Thanks!

**Comment by Potomac** [comment] 2019-04-25 15:25
@asmecher @bozana : as I said the primary locale used is : french (France), and the additional locale is english, no matter if it's an upgrade of an existing OJS installation or a new installation, the bug will occur as soon I switch to the additional language (english), and the bug will instantly disappear if I switch to the primary language,

in the user_settings table the locale field has the value : fr_FR,  if I create a new user when using english language (as secondary primary locale) then the bug is still here and the locale field value in user_settings table is always "fr_FR", the bug will occur everytime when switching to the secondary locale (no matter if it's a new user or an old user),

as I said the bug is easily reproducible, so  you should be able to reproduce the bug, by following these steps : 

- install OJS 3.1.2 (new database) with primary language other than english (for example fr_FR, aka "french from France"), and english as additional locale
-  create your users,  at this step the OJS GUI uses french as locale, and family name, given name, prefered public name are still visible on "users and roles" page
-  then switch to english (click on "English" on the menu, on the top right side of the screen)
- go to "Users and roles" page : you will notice that family name, given name and prefered public name are not displayed
- then switch to "french" with the menu
- go to "Users and roles" page : the bug will disappear, family name, given name and prefered public name are displayed

I don't know if it's a database problem, but the bug could be just a typo in the PHP pages related to the display of "User and roles"  page, I think you should check if PHP statements/algorithm are ok in the source code related to "User and roles --> Users tab" page

**Comment by bozana** [comment] 2019-04-25 19:51
:+1: Thanks @Potomac! I'll take a look...

**Comment by NateWr** [comment] 2019-05-13 15:36
PRs:
https://github.com/pkp/pkp-lib/pull/4758
https://github.com/pkp/pkp-lib/pull/4759 (stable)

Tests:
https://github.com/pkp/ojs/pull/2394
https://github.com/pkp/ojs/pull/2395 (stable)

**Comment by NateWr** [comment] 2019-05-15 11:07
Merged.

**Closed by NateWr** 2019-05-15 11:07 UTC

**Comment by vasmedv** [comment] 2019-05-28 09:53
Good day! I have the same problem not solved. After updating from OJS 3.1.1.4 to OJS 3.1.2.0
on page "users & roles" given name and (lastname) are empty for all users, however in 3.1.1.4 they are filled. It is the same for english and for russian locales.
Install was made manually by deleting old files, except  /files/,  /public/, /config.inc.php/ and copying new files. and then after inputting install form data pressing install button.
I change file DataObjectGridCellProvider.inc.php as in https://github.com/pkp/pkp-lib/pull/4759/files,
but nothing changed.

**Comment by vasmedv** [comment] 2019-05-29 08:11
what changes should i make from #4758, #4759 (stable), pkp/ojs#2394, pkp/ojs#2395 (stable)? Or only #4759?
How many files to change?

**Comment by Potomac** [comment] 2019-05-29 08:58
probably 2 files : 
classes/controllers/grid/DataObjectGridCellProvider.inc.php
classes/core/PKPString.inc.php

**Comment by vasmedv** [comment] 2019-05-30 02:14
Nope, not working.

**Comment by Potomac** [comment] 2019-05-30 02:24
@vasmedv : did you follow the upgrade procedure for the database ? (3.1.1.4 to 3.1.2)

https://pkp.sfu.ca/ojs/UPGRADE

```
- Edit config.inc.php and change "installed = On" to "installed = Off"
- Run the following command from the OJS directory (not including the $):
	`$ php tools/upgrade.php upgrade`
- Re-edit config.inc.php and change "installed = Off" back to
	 "installed = On"
```

**Comment by vasmedv** [comment] 2019-05-31 06:16
Yes i did follow the upgrade procedure for the database. Looks like some error when installing.
Because after install in table users there is no  "first_name", "middle_name", "last_name" fields. And no findings of data that is in "first_name" field (in all database).

**Comment by vasmedv** [comment] 2019-05-31 06:36
Making install once again. When running web script
in "If you are upgrading an existing installation of OJS, click here to proceed." clicking on "click here".
then on upgrade button. Immediately:
 Errors occurred during installation:
    A database error has occurred: Statement violates GTID consistency: CREATE TABLE ... SELECT.

**Comment by asmecher** [comment] 2019-05-31 15:17
@vasmedv, that's a MySQL message; see https://stackoverflow.com/questions/40724046/mysql-gtid-consistency-violation for details.

**Comment by vasmedv** [comment] 2019-06-03 07:00
> @vasmedv, that's a MySQL message; see https://stackoverflow.com/questions/40724046/mysql-gtid-consistency-violation for details.
I saw this page, but it didn't guide me somehow. 
I'm not creating any table and not useing  GTID-based replication. I am only go through  installation procedure. Copy database and files, then press the upgrade button.
Now i made clean copy of ojs3.1.2.0 files. Change in config.inc.php database settings (driver = mysqli
by the way, driver mysql gets error {Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/htdocs/_site2019test/lib/pkp/lib/adodb/drivers/adodb-mysql.inc.php:456}).
Turn on debug options. Set connection_charset = utf-8,database_charset = utf-8.
When opening the installation web page, there is *)Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/htdocs/_site2019test/cache/t_compile/e8ea13aa559bf8604ca823015b397a28d8666486^28682bb3d6b6e750ebd3d458abc8f92b4da9ea9f_0.app.headerusernav.tpl.php on line 136
*)line 136:	<?php if (count($_smarty_tpl->tpl_vars['supportedLocales']->value)) {?>
When pressing upgrade button, the same error: Statement violates GTID consistency.

**Comment by vasmedv** [comment] 2019-06-03 09:01
After install with 2 locales, i tried to edit user given name, but it showed error:
"A given name is required. (Русский)"

**Comment by Potomac** [comment] 2019-06-03 09:08
@vasmedv : if you try a new installation of OJS (and let ojs create the database) do you have again errors ?

**Comment by vasmedv** [comment] 2019-06-03 09:15
Do i need to change files
classes/controllers/grid/DataObjectGridCellProvider.inc.php
classes/core/PKPString.inc.php
before clean install?

**Comment by Potomac** [comment] 2019-06-03 09:26
@vasmedv : no, you can change these 2 files after the installation

**Comment by vasmedv** [comment] 2019-06-03 10:11
Clean install with new database gives no error without changing files in classes.

**Comment by vasmedv** [comment] 2019-06-06 09:55
Is there a possibility, that with new release this problem would vanish, or i need to extract data from old database and put it in new database?

**Comment by NateWr** [comment] 2019-06-06 10:04
This fix for this issue was merged and released in v3.1.2-1.

**Comment by vasmedv** [comment] 2019-06-07 09:48
The same problem with release v3.1.2-1.

**Comment by ajnyga** [comment] 2019-07-11 09:59
I have a similar experience.

Upgraded from 3.1.1.4 to 3.1.2-1.

Our main locale is fi_FI

When I select a journal using just English and go to users & roles and edit an user, the name fields are empty and I can not save the form. If I click on for example the Given name field, the name is visible in an extra field below. I have to copy these names from the field below to the one in the top to make it work.

With journals using Finnish as their main locale, there are no problems. 

What is happening of course is that the conversion has probably used the site default locale as a fallback for saving the names for specific locale. Not sure if there is much to do about but wanted to report this anyway. I will probably just prepare a script that will copy the fi_FI names to en_US fields for all users that do not have name saved using that locale.

**Comment by carzamora** [comment] 2019-07-17 00:47
I did have the same issue on OJS 3.1.2-0, so I did thinking the update to 3.1.2-1 would resolve this problem, but not. I believe the Given name is the problem but no Family name. Maybe you can compare these two fields and looks for the differences, to correct the issue. My config is with Spanish as the second locale, and English as the primary locale.

**Comment by carzamora** [comment] 2019-10-26 00:30
@NateWr hi, can you double-check if this problem is jet in the last release? because I think, the problem just was fixed with Family name but the Given name has problems jet! I need to put (when I create a user) the Given name two times, one in English and others in Spanish. 

I am using OJS 3.1.2-1.

thanks!

**Comment by vasmedv** [comment] 2021-08-04 09:12
After Upgrading FreeBSD to 12.2, Mysql to 8.0.25, Php to 7.4.21, i managed to upgrade OJS from 3.1.1.4 to 3.3.0.7.
(by the way it solved the problem with GTID consistency). And everithing seems working. The only bug i could see for now is when i try to edit old user, there is no Given Name  and Family Name, however it appers in Users & Roles list. The reason i brought out is that in the table 'user_settings' in field 'locale' the value is "ru_RU" instead "en_US" for  Given Name  and Family Name for the current user. It is left from the previous installations. (Now the only language in the system is English). The solution is to change values to  "en_US" for needed users.
