### ISSUE TITLE
Selectively permit author metadata changes after submission

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3758] opened 2018-05-30 19:21 UTC
See the discussion at https://forum.pkp.sfu.ca/t/ojs-3-1-how-to-get-an-author-to-update-metadata-in-submission-or-review-phase/37056.

Proposals there (by my read):
- Always allow authors to edit metadata while the submission is in the Submission and Review stages. [source](https://forum.pkp.sfu.ca/t/ojs-3-1-how-to-get-an-author-to-update-metadata-in-submission-or-review-phase/37056/7)
- Always allow authors to edit metadata while the submission is in the Submission stage, but not Review stage. [source](https://forum.pkp.sfu.ca/t/ojs-3-1-how-to-get-an-author-to-update-metadata-in-submission-or-review-phase/37056/7)
- Add a control to allow the Editor to [lock metadata changes](https://forum.pkp.sfu.ca/t/ojs-3-1-how-to-get-an-author-to-update-metadata-in-submission-or-review-phase/37056/13) by authors.

Also a suggestion to [avoid additional email notifications](https://forum.pkp.sfu.ca/t/ojs-3-1-how-to-get-an-author-to-update-metadata-in-submission-or-review-phase/37056/12.)

There is a [suggested temporary work-around](https://forum.pkp.sfu.ca/t/ojs-3-1-how-to-get-an-author-to-update-metadata-in-submission-or-review-phase/37056/19).

**Comment by NateWr** [comment] 2018-05-30 19:39
I would throw in a vote for @ajnyga's suggestion for a [review/update request](https://forum.pkp.sfu.ca/t/ojs-3-1-how-to-get-an-author-to-update-metadata-in-submission-or-review-phase/37056/9). Although it is more manual than just deciding what stages to keep it unlocked, I see a few benefits:

- Editors are never "surprised" by Author changes and editors retain control.
- We don't have to decide when to cut off access, or add another option which journals must learn and configure.
- A three-step invite-reply-approve process gives us information we can use to feedback status updates to things like the submissions list, so an editor can know when a submission is waiting for author input.
- It will interact well with versioning, since editors can request author contributions on a specific version before publication. 
- Eventually someone will ask for a one-click feature to send a request to an author for review anyway (for example, please approve your submission info before galley production). We'll get that feature for free this way.

**Comment by bozana** [comment] 2018-05-30 19:53
The only thing that this last suggestion maybe does not consider is if an author would like to change something without being asked by the editor to do so, but I am not sure if this should be allowed anyway i.e. if this is wished...

**Comment by t4x0n** [comment] 2018-05-30 22:37
Is not wished author can edit metadata at any time, I think what @NateWr propose have a lot of good points. Really, for me and other editors (who I work with and others that I know), just the chance to author can edit the metadata in submission stage is a great feature, others features will be grateful too! Thanks!

**Comment by bozana** [comment] 2018-06-18 16:08
In this forum post https://forum.pkp.sfu.ca/t/ojs-3-1-how-to-get-an-author-to-update-metadata-in-submission-or-review-phase/37056/27 the editing of the article metadata by the author is wished for the editing stage as well -- just a note to eventually consider or discuss it here as well...

**Comment by t4x0n** [comment] 2018-06-18 19:05
Ok, have sense too because one time the manuscript is accepted, the metadata depends on the last version and the last version probably has been changed through workflow

**Comment by markagregory** [comment] 2018-08-18 09:25
Hi, I've implemented the code from the forum thread and cannot get it to work in the review and copyedit phases. the authors still have read only. I would appreciate help to get this to work. The code changes implemented are.

1- /lib/pkp/classes/controllers/modals/submissionMetadata/SubmissionMetadataHandler.inc.php
![one](https://user-images.githubusercontent.com/26024430/44297881-57aa7200-a31c-11e8-8c7d-ec56e7d5e73e.png)

2- /lib/pkp/controllers/grid/users/author/AuthorGridHandler.inc.php
![two](https://user-images.githubusercontent.com/26024430/44297882-62fd9d80-a31c-11e8-9c49-497f0b63b2da.png)

3- /lib/pkp/classes/core/PKPApplication.inc.php
![three](https://user-images.githubusercontent.com/26024430/44297886-6ee95f80-a31c-11e8-86fb-82e22eb5236b.png)

**Comment by asmecher** [comment] 2018-08-21 15:05
@markagregory, I see this is also posted on [our support forum](https://forum.pkp.sfu.ca/t/ojs-3-1-how-to-get-an-author-to-update-metadata-in-submission-or-review-phase/37056/27). Please don't post the same content in two places -- it divides the conversation.

**Comment by asmecher** [comment] 2018-10-15 19:14
Reviewed over in https://github.com/pkp/pkp-lib/pull/4143#pullrequestreview-164847200, thanks!

**Comment by defstat** [comment] 2018-10-30 00:16
@asmecher I added the changes at the same PRs. (all changes are in pkp-lib)

The features added are:
- each role can be permitted/denied access to submission metadata edits (managers have permission to edit, and that permission can't be revoked). There is a new checkbox under the edit of each role.
- At the submission level, each participant can be permitted/denied access to submission metadata edits, overriding its "role permits". There is also a new "edit" action under every participant.

**Comment by asmecher** [comment] 2018-11-08 22:06
A few more comments over here: https://github.com/pkp/pkp-lib/pull/4143#pullrequestreview-172767878

**Comment by defstat** [comment] 2019-02-15 18:38
@asmecher I have applied the changes on stable-3_1_2 branch. 

New PRs [stable-3_1_2]
[pkp-lib]: #4505
[ojs]: pkp/ojs#2294
[omp]: pkp/omp#643

**Comment by asmecher** [comment] 2019-02-15 18:53
@defstat, I've reviewed this briefly from a code perspective and it looks excellent!

It's quite a bit of code to add so close to the 3.1.2 release, so maybe I'll ask a couple of follow-ups...
- @jmacgreg, is this something that you think is important to the hosting group for this release? Do you have some capacity to test it next week?
- @defstat, what's your level of confidence based on your own internal testing?

Thanks!

**Comment by jmacgreg** [comment] 2019-02-15 19:08
@asmecher I don't think this is an issue on our radar - so, not important for us for 3.1.2, but we can test it next week if you like.

**Comment by defstat** [comment] 2019-05-13 14:27
@asmecher 

PRs
[pkp-lib]: #4753
[OJS]: pkp/ojs#2390
[OMP]: pkp/omp#673

**Comment by asmecher** [comment] 2019-05-14 22:47
Thanks for carrying this along, @defstat! Just a few comments on the above PR. Very happy to see so much of this going into pkp-lib, especially given the preprint server fork will be created soon!

**Comment by defstat** [comment] 2019-05-15 17:38
@asmecher I pushed the review changes - 

I also changed the place where the upgrade script runs `<code function="changeUserRolesAndStageAssignmentsForStagePermitSubmissionEdit" />` because it seems that it should run regardless the installation version.

**Comment by asmecher** [comment] 2019-05-15 23:23
@defstat, I just had one small comment -- otherwise this looks good. Please go ahead and merge when you're ready.

**Comment by defstat** [comment] 2019-05-22 15:46
@asmecher Everything merged.

**Comment by NateWr** [comment] 2019-05-22 15:54
@amandastevens this will effect documentation.

**Comment by defstat** [comment] 2019-05-31 14:39
@NateWr @amandastevens @asmecher I leave that issue open until documentation done?

**Comment by asmecher** [comment] 2019-05-31 15:13
@amandastevens can confirm, but I think we're in the habit of closing issues and letting the documentation group work on it separately.

**Comment by NateWr** [comment] 2019-06-03 11:17
@defstat @asmecher Should this line be moved inside of the `2.4.0.0` to `3.1.9.9` upgrade set?

https://github.com/pkp/ojs/blob/master/dbscripts/xml/upgrade.xml#L249

**Comment by amandastevens** [comment] 2019-06-03 13:16
Yes, you can close the issue.  We're keeping track of it in a separate documentation-needed list.  

The milestone for the issue is 3.3.  Is that still accurate?

**Comment by asmecher** [comment] 2019-06-03 16:24
@NateWr wrote:
> Should this line be moved...

Yes, absolutely! Good catch. @defstat, leaving that to you.

**Comment by asmecher** [comment] 2019-06-03 19:30
> The milestone for the issue is 3.3. Is that still accurate?
When @defstat merges it, it'll be in the `master` branch, and the next release for that will be 3.2. So I'll move it there, unless @defstat intends to live in rebase hell for a long time :)

**Comment by defstat** [comment] 2019-06-05 02:38
@asmecher 

PRs
OJS: pkp/ojs#2415
OMP: pkp/omp#681

I don't remember having added a PR without changes on the lib-pkp repository. Should I add the lib/pkp submodule commit in order for the tests to start, and if yes, should I add it with the related ##defstat/master## comment, or a "Submodule Update" comment is sufficient? (for those PRs I added the submodule commit and I tried both approaches to see which will fail)

**Comment by NateWr** [comment] 2019-06-05 09:16
If there's no changes in pkp-lib then you don't need to add a submodule commit. The tests will check out the `master` branch and that will work fine.

(A couple of the OMP tests fell over so I've restarted them.)

**Comment by asmecher** [comment] 2019-06-05 22:19
@defstat, looks good -- please go ahead (and accept your trophy for the longest PHP function name).

**Comment by defstat** [comment] 2019-06-06 10:09
@asmecher :)

All merged. I am closing the issue for now.

**Comment by asmecher** [comment] 2019-06-06 16:17
:+1:! Thanks, @defstat.

**Comment by NateWr** [comment] 2019-06-24 11:49
I believe these changes have caused a regression. `SubmissionMetadataHandler::getUserAllowEditMetadata()` only checks a user's stage assignments. But there are a few additional cases where we allow users to edit metadata even if they do not have a stage assignment. For example an admin should always be able to edit metadata. And an editor who is _not assigned as an author_ should be able to, even if they are not assigned as an editor.

This kind of access is complicated and a more complete flowchart is available in this comment: https://github.com/pkp/pkp-lib/issues/3130#issuecomment-357675761.

I'm not sure if it's a good idea to have two different implementations of the access logic. But we can't reuse the workflow access `Policy` in this case. Perhaps it is possible to invert the logic in `SubmissionMetadataHandler::getUserAllowEditMetadata()` so instead of finding if any user is allowed to edit the metadata, it finds if an _author_ is _not allowed_ to edit it.

In this way the workflow `Policy` should guard access to the metadata forms and the grid in general. And we only place an additional restriction when the user is assigned and their assignment is explicitly set to not be able to change metadata.

**Comment by asmecher** [comment] 2019-06-25 17:10
Thanks for writing this up so clearly, @NateWr!

**Comment by defstat** [comment] 2019-06-26 17:12
@NateWr are you referring to Authors in particular? I am asking because the feature allows the editor to give access to that feature to any Role, or revoke access to Roles that are not administrative.

Furthermore the feature can add or revoke access to metadata edit to individual participants.

**Comment by NateWr** [comment] 2019-06-27 09:58
> Could we change the SubmissionMetadataHandler::getUserAllowEditMetadata so that for certain roles, we don't care about the stageassignments, but check the role access to the EditMetadata explicitly?

There's an extra layer to it. The logic runs something like this:

```
if (user is assigned any role) {
  allow if assignment is allowed to edit metadata
} else {
  allow if user has manager role
}
```

So even if someone is a `ROLE_ID_MANAGER` in the journal, they may be assigned in a different role to the submission. In that case, they should be given permissions based on their assigned role.

If a user does not have an assigned role on the submission, they should be denied access, _unless_ they are a `ROLE_ID_MANAGER` or `ROLE_ID_SITE_ADMIN`, in which case they should be treated the same as if they were assigned in a manager role.

So I _think_ that the logic I described earlier should work:

> Perhaps it is possible to invert the logic in SubmissionMetadataHandler::getUserAllowEditMetadata() so instead of finding if any user is allowed to edit the metadata, it finds if an author is not allowed to edit it.

So in this case it wouldn't be only the author. It would check all the user's assignments and if all of them were not allowed to edit it would block access. Otherwise it would allow it.

**Comment by defstat** [comment] 2019-07-15 16:15
@NateWr 
PRs
[pkp-lib]: #4923
[ojs]: pkp/ojs#2431
[omp]: pkp/omp#691

**Comment by defstat** [comment] 2019-07-24 17:18
@NateWr Tests have passed. Is it ok to get merged?

**Comment by NateWr** [comment] 2019-07-24 17:24
Thanks @defstat! There are still a couple of uses of `journal` need to be changed to `context` in the `pkp-lib` PR.

Also, is this feature in `stable-3_1_2`? If so, we'll need to port it there as well.

**Comment by asmecher** [comment] 2019-10-15 18:07
@defstat, @NateWr, can you confirm whether this code was ever merged?

**Comment by ajnyga** [comment] 2019-10-16 06:16
Copy pasting the things I just wrote to Alec in Slack here:

There are two levels of edit permissions. The userGroup level and the stageAssigment level. Basically you can now allow whole userGroup edit metadata or just a single user within that user group or allow a whole usergroup to edit metadata but take that permission away from a single user. So very flexible.

The userGroup settings works as a default when you do a stageAssignment. So the checkbox is readily checked if the userGroup has the feature enabled.

**All this works well expect with the manager roles**. If you look at https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/stageParticipant/form/AddParticipantForm.inc.php you can not check the edit permit for managers in stageAssigment because it is prevented here: https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/stageParticipant/form/AddParticipantForm.inc.php#L124.

**So we have two options**: 1) have the manager rights hardcoded in the code the same way we allow access for site admins now. Or 2) in the add stageParticipants form automatically add the permission for the manager. There is a difference here. With the firs one you basically allow managers to edit metadata without stageAssignment (something they are used to) and with the second one the manager of course needs a stage assigment to edit.

**Note that the feature is broken with for example the author grids**. There the managers can not gain access in any way at the moment because there is an override only for site admins: https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/author/AuthorGridHandler.inc.php#L249

Also, I think what is still missing is a default setup of permission. I believe that when you now install a new OJS from master, the section editor will not have permission to edit metadata by default. So what we need I think is the OJS install script to set some default settings for the user groups it creates. I think it makes most sense to allow metadata edits for section editors (and perhaps assistants ) by default. These roles used to have edit permissions. If we do not do that, the forum will be filled when OJS 3.2 is released :slightly_smiling_face: 

But overall this is a very good concept also when thinking of PPS. I do not have do any special tricks to allow authors to edit metadata. I just give them that permission in the userGroup settings.
But a question: should the metadata edit permission apply to the galleys grid as well? It is part of the publication forms now so it would make sense I think.

**Comment by ajnyga** [comment] 2019-10-16 06:20
Issue #2: If I now sign in as a section editor, I can edit my own stage assigment. Meaning that I can allow myself to edit metadata if I want. I can also change the "This participant is only allowed to recommend an editorial decision and will require an authorised editor to record editorial decisions." setting.

**Comment by ajnyga** [comment] 2019-10-16 06:23
Issue 3: should the metadata edit permission apply to the galleys grid as well? It is part of the publication forms now so it would make sense I think. At the moment it only applies to the authors grid.

I already have the changes ready for it to apply to the publication metadata save buttons, so once I get the answers for the questions here, I can finalize the work.

**Comment by NateWr** [comment] 2019-10-16 08:11
Sorry I haven't been able to read the full report here, but just reminder that the manager permissions are slightly complicated due to the case when editors are assigned as authors/reviewers. It is _supposed_ to work like this:

1. If a manager has a stage assignment, they are treated according to the role they have in the stage assignment. Same with a review assignment.
2. If a manager has no stage assignment or review assignment for the submission, they are treated as a manager with access to everything.

So when we selectively allow/disallow access to edit metadata, this should _only_ work against the stage assignment. If a manager has no stage assignment, it should not be possible to block them from editing metadata.

**Comment by ajnyga** [comment] 2019-10-16 08:43
The current situation is mixed in master branch:

Few cases:

Journal manager without stage assignment: can edit metadata, **can not** edit contributors grid, can publish
Journal manager with journal editor stage assignment: can edit metadata, **can not** edit contributors grid, can publish
Journal manager with section editor stage assignment and edit permission turned _off_: can edit metadata, **can not** edit contributors grid, can publish
Journal manager with section editor stage assignment and edit permission turned _on_: can edit metadata, can edit contributors grid, can publish

So at the moment I think that either the contributors grid or the publication metadata save are working the way they should.

**Comment by ajnyga** [comment] 2019-10-16 08:48
ahah, I see that this never made it to the master branch. It deals with the situation Nate mentions above: https://github.com/pkp/pkp-lib/compare/27eeff555bdcfa6da9f787d259184b1cfacff025...7a67f94ec26293e5ed80326cac6fbc45e8019f01#diff-e0efaf3dc7b195a253d9b1a294dc15da

**Comment by ajnyga** [comment] 2019-10-16 14:24
Issue 4: currently you can end up with a situation where the section editor does not have the ability to edit the publication metadata, but they can publish the submission nevertheless.

Not sure though if we want to tie these two capabilities together though?

**Comment by NateWr** [comment] 2019-10-25 15:08
I've just had a look at @ajnyga's latest work on #4877 and it seems like the feature to allow/disallow author edits of the publication details is working as it should. 

I'm going to close this as fixed. Thanks for everyone's work on this. The editor-assigned-as-author case is definitely a tricky one to deal with.

**Closed by NateWr** 2019-10-25 15:08 UTC
Labels: Community Priority, Enhancement, Hosting

**Comment by asmecher** [comment] 2019-10-25 22:45
> Issue 4: currently you can end up with a situation where the section editor does not have the ability to edit the publication metadata, but they can publish the submission nevertheless.

It's a little bit of a niche, but I don't mind this. I suspect section editors will rarely be prevented from editing metadata in practice, and editors that make use of this functionality may have a colourful and nonstandard set of expectations for associated abilities like publishing. Off the top of my head I think it's more sensible to tie the ability to publish to the "recommend only" setting -- you can think of publishing as an editor decision.

**Comment by asmecher** [comment] 2019-10-25 22:45
(^ sorry for hopping onto this so late! And thanks to you both for working through this.)

**Comment by NateWr** [comment] 2019-10-28 09:17
> Off the top of my head I think it's more sensible to tie the ability to publish to the "recommend only" setting -- you can think of publishing as an editor decision.

Good idea! https://github.com/pkp/pkp-lib/issues/5234
