### ISSUE TITLE
Improve Filename Conventions for Downloaded Files as Part of Submission

### ISSUE THREAD

**Issue by alex-wreschnig** [pkp/pkp-lib#4957] opened 2019-07-30 19:52 UTC
**As an** editor, reviewer, or copyeditor who works with multiple submissions--possibly across multiple journals
**I want to be able to** understand what files I've downloaded are for what journal, which submission in that journal, and whether they are up to date or not.
**so that I** know what files correspond to what submissions, **and so that** I can compare downloaded files against the OJS records for that submission and know that I am working on the latest version of the file.

### Background
Downloading a single file gets us a file with a filename formatted as:
Submission # for the server. - Content Type - File Submission Number for the server - Version Number - (File stage? We think?) - Date (with no separators)

Separately, downloading a group of files gets us a zip file with a filename of files.zip.

If you're dealing with multiple submissions, this rapidly gets unwieldy. The existing filename convention for single files is very difficult to parse and parts of the filename were completely inscrutable even to developers.
A user needs to be able to track files back to the submission they came from so they know what file they're looking at. If this problem is solved without including revision or date information, it may reveal another problem in terms of users working on old copies of files.

### Solutions
The UI/UX group identified some possible solutions:
- Easy solution: label the fields in the filename so that users understand what each stands for.
- More difficult/involved solution: allow journal managers to define custom filename formats and standards for each journal.

When discussing this issue with experienced users, the fields we identified as useful were:

- Journal Abbreviation
- First few words of the article title
- Editorial Workflow Stage
- Date
- No author identifying information? (Might be useful for single-blind review but should not be in double-blind)
- Content type -- article text, research instrument, etc.
- Version/Revision Number

**From PKP Sprint Pittsburgh (2019/07): UI/UX group**
[UI/UX group notes from the Pittsburgh sprint](https://docs.google.com/document/d/1oWcsyHX2Ww5tHPpSN_-c2KaIhmAdaGYcZn3gFHjMEpc/edit?usp=sharing)

**Comment by asmecher** [comment] 2019-08-01 15:01
@alex-wreschnig, one frequently-requested approach on the forum is that the download simply re-use the same filename that was present on the client's machine when the file was uploaded. Did the UI/UX group consider that kind of approach?

**Comment by alex-wreschnig** [comment] 2019-08-05 15:16
@asmecher We talked a little bit about it. There are a few challenges with that approach. If OJS _doesn't_ control the filename, we'd lose some protection against violating the rules of a double-blind review process. If you kept the existing approach to protect double-blind reviews but let journals with other review settings keep the original filename, that suggests that you're then maintaining _two_ filename conventions, which seemed like a lot of work for something so simple. And for cases where you kept the original filename, there's no guarantee that authors would submit files using the recommended filenames.

Retaining the original filename might still be a viable solution, but those difficulties led us to not consider the idea as a strong candidate.

**Comment by carzamora** [comment] 2019-08-06 05:31
About this topic, I have been a lot of issues when I download the images for a paper. Some times I download all image files, but then I need to figure out what Figure correspond to what image downloaded. So, almost all the time, I have to download all files again, and in the process rename one by one before download the next image.

For Editors who work in more than one journal, I think you can improve the codification in the filename with journal abbreviation, this is good! But for solving the problem I describe, I think the best solution is the possibility of renaming the files inside OJS, just by adding a suffix.

For example, for this file:
133-Figure-1058-1-4-20190708.tif

I could be added Fig-1 as a suffix:
133-Figure-1058-1-4-20190708-Fig-1.tif

I don't know if this is difficult to implement, but is an idea.

**Comment by NateWr** [comment] 2020-08-24 15:26
As part of work that is going into #6057, we're going to be making some changes to the file download names. Now, files will be downloaded with a name that reflects the file's name as displayed in the editorial workflow. For example, if you have three .docx files in copyedited with the following names:

- Nathan Wright, Article submission FINAL COPYEDIT
- Research methods statement
- Author licensing agreement (Journal of Public Knowledge)

Downloading those files will result in the following files:

- nathan-wright-article-submission-final-copyedit.docx
- research-methods-statement.docx
- author-licensing-agreement--journal-of-public-knowledge.docx

The main benefit of this approach is that filenames will reflect the files as they are described by editors, assistants and authors throughout the system. Names can be changed during the editorial workflow and these will be reflected in the downloaded file names.

The downside is that the file is not directly tied back to the journal or submission. In that sense, it does not satisfy the recommendations described in this issue. But I hope that it will be easier to manage than the current convention.

As much as possible, I'd like to minimize the "mental overhead" of attaching ids to filenames, particularly for authors who only interact with their submissions. By including the ids in the downloaded filenames, they're likely to persist when editors and assistants upload revisions. And ideally each file should have a common name shared between editors, authors and assistants so that discussions happen with shared knowledge.

Having said that, I'm open to feedback that this is not going to work for editors and assistants who work with lots of submissions. Perhaps we can explore alternatives like attaching ids to just the "download all" options, or finding a minimal set of ids which can be useful for editors/assistants but not confusing to authors.

**Comment by asmecher** [comment] 2020-08-25 16:44
@NateWr, I'm 95% with you on this, but have a couple of thoughts...
- If we're essentially going with the upload filename, why not just preserve it entirely as-is?
- What about filenames that reveal author or reviewer names? In that situation, a synthetic filename is actually a good thing.
- I worry that this change will reveal a segment of our community who are perfectly happy with the status quo and weren't aware we were considering changing it; how do you feel about making filenames configurable in some form? (I could picture something like a format string like we use for date formats.) Since the filenames are applied only at the time of download, and we're free to use synthetic filenames on the server filesystem, the configuration can be changed at will without causing inadvertent chaos.

**Comment by NateWr** [comment] 2020-08-26 08:51
> If we're essentially going with the upload filename, why not just preserve it entirely as-is?

The goal is to use a name that reflects the name that appears in the UI. This is an editable and localized name field, so users can do whatever they want with it, even if it ends up as an invalid filename. So what I've chosen to do is to derive a safe filename from that localized name (code [here](https://github.com/NateWr/pkp-lib/blob/i6057_submission_uploads/classes/services/PKPFileService.inc.php#L136)):

```
$safeFilename = \Stringy\Stringy::create($filename)->dasherize()->toLowerCase()->regexReplace('[^a-z0-9\-\_.]', '');
```

We could use the original upload filename and preserve it. But one of the comments we got (from Dulip about books in OMP with dozens of files) is that being able to name the files is an important way of organizing them. If editors named files, but then got the original filename when it was downloaded, I think that would cause confusion.

> What about filenames that reveal author or reviewer names? In that situation, a synthetic filename is actually a good thing.

In such cases I'm delivering an anonymised filename (code [here](https://github.com/NateWr/pkp-lib/blob/i6057_submission_uploads/controllers/api/file/FileApiHandler.inc.php#L87-L103)). It uses the journal acronym, the submission id, the genre localized name, and the file id. So it will come out like:

```
JPK-review-assignment-21-article-text-341.docx
```

> how do you feel about making filenames configurable in some form?

We could do that. The default could be `{$filename}` but we could offer a set of replaceable params, a little bit like a localized string. Another option is to pass the filename through a hook and leave it to plugins to handle these cases.

**Comment by asmecher** [comment] 2020-08-26 15:51
Thanks, @NateWr! I'm still on the fence about a configurable field for file naming; it'll likely allow us to handle some feedback about the change fairly easily, but on the other hand it would be a pretty specialized thing to add and that way lies UI bloat. I'm content to leave it to your judgment.

**Comment by luizbgomide** [comment] 2021-02-25 09:55
We migrated to OJS 3 in October and now we are starting to receive complains regarding the new formatting scheme. 

The editors really want the old naming scheme (submission id - fileID) back, as this brings uniformity to the journals (we handle 20 journals).

Is there a way to revert back to the old naming scheme?

**Comment by NateWr** [comment] 2021-02-25 10:08
@luizbgomide No, but changes have been made in OJS 3.3 which mean the download filename uses the name of the file as shown in OJS, rather than the hard-to-understand string used in OJS 3.2.x. You can see what filenames will look like in [this comment](https://github.com/pkp/pkp-lib/issues/4957#issuecomment-679195764). I'd recommend upgrading to OJS 3.3 and waiting a few months to see if editors are able to adapt to this format.

**Comment by luizbgomide** [comment] 2021-02-25 10:22
@NateWr I am on OJS 3.3, and the scheme in your comment is **not** the naming scheme that I'm getting when downloading PDFs.

I invite you to take a look at some of our journals like: 
- https://periodicos.fclar.unesp.br/alfa/issue/view/745 
- https://periodicos.fclar.unesp.br/iberoamericana 
- https://periodicos.fclar.unesp.br/cadernos/issue/view/803.

The first name is NOT the author, but I think the editor and then it lists the original filename (which is not desirable). The convention you mentioned in the referenced comment is not working.

**Comment by NateWr** [comment] 2021-02-25 14:32
Hi @luizbgomide,

The filenames I am getting are like `andersoncruz-0-id-14558-apresentao-dossi-ft-rev.pdf`. This is probably the filename that existed when the file was uploaded and attached to the galley. When uploading a file to the galley, there is a chance to set the name, and the download filename will depend on that name.

You can check the names in the database with the following SQL query (change the submission ID):

```
select * from submission_file_settings where setting_name="name" and submission_file_id=1;
```

**Comment by luizbgomide** [comment] 2021-02-25 14:47
That is not what is happening, this article `https://periodicos.fclar.unesp.br/alfa/article/view/11313/9108` downloads as `berlinck-revista-alfa-v64-portugus-artigo-a-11313.pdf`.

"berlinck" is an Editor of the journal, it was me who uploaded this file to the system and not this user. So "berlinck" has no place being here, it is neither the uploader, nor the author of the file. The original filename was indeed: "Revista Alfa v64 - português - artigo a) 11313.pdf".

**Comment by luizbgomide** [comment] 2021-02-25 14:49
Also, `andersoncruz`, is also an editor, and not the author of the papers...

**Comment by NateWr** [comment] 2021-03-01 08:55
Hi @luizbgomide, the filename would have been set when the file was uploaded. Have you tried uploading a new file and looking at what the name is after it is downloaded? Have you checked the name in the database as I mentioned in my last comment?

**Comment by luizbgomide** [comment] 2021-03-01 10:35
Hello Nate, yes, I've checked. Files uploaded after OJS 3.3 shows just the filename at time of the upload. But the files uploaded previously (before OJS 3) shows the username of the editor (not the uploader and not even the editor of the article, I'm not sure how that name was got) concatenated with the original filename.

This is awful, because we have thousands of articles published before OJS 3 that now shows the **username of an editor that wasn't even in the journal when the article was published** (probably added as the result of some migration). I would really like the file names to be like they were (with submission and file ID), my editors, authors and users where used to that format for more than a decade. A change like that now caught everyone by surprise and we are having many complaints since this is not what they expected and the original filename was never public to anyone.

**Comment by NateWr** [comment] 2021-03-01 11:07
@luizbgomide your best bet is going to be to change the name of the existing files in the database. Since the downloaded file name is taken directly from the name in the database now, you can set it to whatever you want.

**Comment by luizbgomide** [comment] 2021-03-01 11:13
@NateWr how can I even change those names? This table has 77 thousands entries, and even filtering just by name it would be impossible to be sure that it is correct for the 15000 submissions I have.

Can't I just patch somewhere to use the old file scheme?

**Comment by luizbgomide** [comment] 2021-03-01 11:14
Again, this is disclosing usernames of editors. And that is clearly a security concern at the minimum, not just to me, but to everyone that uses OJS and migrated to 3.3.

**Comment by NateWr** [comment] 2021-03-04 10:50
@luizbgomide we don't consider usernames to be private information. If you want to rename the files that are attached to galleys, you can use something like the following SQL query:

```
UPDATE submission_file_settings sfs JOIN submission_files sf ON (sfs.submission_file_id = sf.submission_file_id) SET sfs.setting_value=CONCAT(sf.submission_id, '-', sf.submission_file_id, '.', SUBSTRING_INDEX(sfs.setting_value, '.', -1)) WHERE sfs.setting_name='name';
```

Beware this has not been tested. Try it out on a copy of your database first before running it against your production database.

This query will turn all of the filenames into something like `213-321.pdf`.

**Comment by luizbgomide** [comment] 2021-03-04 11:19
Thanks Nate, I will try this SQL. 

Even if you don't consider it a security concern, it is also an irrelevant or misleading one. I think that either something went wrong previously for the file names to be set using first alphabetically available editor manager. In our 20 journals I already identified the following problems:
- usernames of manager assistants being attributed to thousands of files.
- username of editors that worked for 4 years (2016-2020) being assigned to every article from 2009 up to the upgrade to 3.3.
- username of editors that aren't the chief editor being assigned to all files.

**Comment by luizbgomide** [comment] 2021-03-04 11:25
Also, what would happen if the file name information is missing? I noticed that from OJS 3 onwards, our bilingual and trilingual journals creates 2-3 `name` settings and only one of them is filled and the others are left blank (since this is automatically filled i don't think it could ever be filled by the user). If there is no information would it generate a filename on the fly?

**Comment by NateWr** [comment] 2021-03-08 10:41
@luizbgomide over the years there have been many different ways that OJS has automatically generated filenames. It does not surprise me that you'll find big differences in filenames. The inability to settle on a common naming pattern that works for everyone is part of the motivation for switching now to using the uploaded name and not automatically generating one.

> Also, what would happen if the file name information is missing?

The filename can be localized to different languages, so it will fall back to any available language. At least one language should be defined. If there is not a name in at least one language that might cause a problem.

**Comment by davidjb** [comment] 2021-03-31 09:30
Just to add some additional context here, I'm the system administrator for a university multi-journal OJS instance, associated with several journals out of administrative necessity (so I've got access to assist users because despite having system admin access, one needs to be a Journal Manager on each journal to change its settings) - and my details have been attached to submissions.  Given our install of OJS uses single-sign on this means my _email address_ gets attached to downloads.

As @luizbgomide has described, that's firstly misleading since I have no involvement with these files at all, indicating to a downloader that I might be the author or have some influence on the content.  From a personal standpoint, having my identity heading out publicly like this is a shock, not so much from a security point of view (as it's already public in contact lists etc) but just that my name is used in random contexts that I have no control over and don't want it associated with (articles and publications I had no involvement with).

@NateWr  What's the current naming standard for OJS? I'm on the latest stable release of 3.3.0-4 - just wondering if I'll see the same issue recurring later and I need to modify the source code at all. Recent uploads look to be different now either post 3.2 or 3.3, but it would be good to confirm - I appreciate your help.

----

For note, I ended up using the following SQL to cleanup my database (thanks @NateWr for the inspiration):
```sql
UPDATE submission_file_settings sfs SET sfs.setting_value=SUBSTRING_INDEX(sfs.setting_value, ', ', -1) WHERE sfs.setting_name='name' and sfs.setting_value like '%@example.edu, %';
```

to fix up situations where filenames were like originally `my.name@example.edu, 2020.1.1 Filename.pdf` (user ID separated by a comma and space) to just strip out these specific prefixes.

**Comment by NateWr** [comment] 2021-03-31 11:22
Hi @davidjb, from 3.3 onwards we are no longer modifying the filenames (except to perform basic sanitization). So the filename reflects the name as it was uploaded. However, files that were uploaded before 3.3 still have the names that were generated at the time that they were uploaded.

The username that was attached to files in versions before 3.3 should be the name of the user who uploaded the file. I have not been able to reproduce the issue described where a filename includes a user that was not the uploader. If anyone can provide reproduction steps and we can locate the source of that problem, we may be able to address it in some way (for example, identify the effected files and rename them during an upgrade).

**Comment by davidjb** [comment] 2021-04-02 00:18
Thanks for the confirmation @NateWr - that's reassuring to know about filenaming from now on.

> @NateWr, like I explained previously this file name issue was done probably at the migration from 2.X to 3.X. I can only guess that somewhere in the file migration it was decided to attach the file name to one of the editors of the journal and here it did something awful, he picked the first manager login alphabetically to put in front of the regular filenames. It was DEFINITELY not the uploader's username, or even one of the assigned editors to the file.

This is my read of the situation as @luizbgomide has described -- most 2.x to 3.x content seems to be affected by the addition of a journal manager's user ID being added.  In the cases where my ID was added, my ID was first alphabetically; for other journals that had another's ID added, it was theirs that is first alphabetically.

However, there were some other patterns that were present too:

* `[alphabetically-first journal manager's user ID], filename.ext` (as above)
* `[uploader's user ID], filename.ext`
* `, filename.ext` (nothing before the comma)
* `[Category], filename.ext` - such as `Article Text`, `Data Set`, `TEXT` and `Other` etc

It's possible that any of these files might have just been the name the uploader supplied since our upgrade to 3.3, but we only just upgraded to 3.3 and most content is older. 

A few carefully-crafted SQL statements later and all the filenames with prefixes have been cleaned up - had to work through some parts by hand because new uploads since 3.3 have legitimate filenames with formatting matching some of the above patterns.

**Comment by NateWr** [comment] 2021-04-08 09:57
In 3.3.0-6 there will be a slight change to the filenames when downloading a submission file. In short, we are no longer "dasherizing" them (eg - `this-example-file.docx`) because of problems with diacritics and non-Latin characters. More details and an example at https://github.com/pkp/pkp-lib/issues/6898#issuecomment-815624269.

**Comment by NateWr** [comment] 2022-10-03 09:56
Closing this as the new file naming convention in 3.3 seems to be working ok. If you are using 3.3.0-6 or higher and want to change how file names are generated, please post on our [feature request forum](https://forum.pkp.sfu.ca/c/feature-requests/8).

**Closed by NateWr** 2022-10-03 09:56 UTC
