### ISSUE TITLE
[OPS] DOI points to unpublished version

### ISSUE THREAD

**Issue by diegoabadan** [pkp/pkp-lib#7001] opened 2021-04-27 19:46 UTC
**Describe the bug**
DOIs are being generated with a link to an unpublished version of the preprints. Only published preprints are expected to be linked.

**To Reproduce**
1. In a preprint with active DOI, create a version and do not publish it
2. Export this submission in Crossref XML to view the generated link
3. You will be able to view the link to an unpublished version

**What application are you using?**
OPS version 3.2.1.0 and 3.3.0-5

**Comment by NateWr** [comment] 2021-04-28 11:19
@ajnyga are you able to reproduce this?

**Comment by ajnyga** [comment] 2021-04-28 11:43
Did not try, but can see from the code how it could happen. It is an easy fix, just have to add a status check to the export filter.

**Comment by ajnyga** [comment] 2021-04-28 12:50
(just a little delay here, OPS main seems to be broken since the last commit. I will wait for a fix first)

**Comment by NateWr** [comment] 2021-04-28 13:02
We want this against `stable-3_3_0`. Can you create the fix against that branch and Alec can cherry-pick forward to later branches? He may release 3.3.0-6 today or tomorrow so it would be great to get this in.

**Comment by asmecher** [comment] 2021-04-28 14:54
Sorry, I forgot to push up the crossref plugin changes for OPS -- I've pushed them now and hopefully the tests will pass.

**Comment by asmecher** [comment] 2021-04-29 02:19
^ The OPS tests should be passing now, but Nate's right, this should go into 3.3.0-6 -- I can take care of forward-porting from there, since the instability is mine :sweat_smile:

**Comment by ajnyga** [comment] 2021-04-29 08:13
OPS: https://github.com/pkp/ops/pull/150

**Comment by asmecher** [comment] 2021-04-29 16:22
Thanks, @ajnyga! Merged to `stable-3_3_0`, cherry-picked to `stable-3_3_1`, and forward-ported to https://github.com/pkp/crossref-ops for `main` (3.4 release).

**Closed by asmecher** 2021-04-29 16:22 UTC
Labels: Bug
