### ISSUE TITLE
Convert email templates to the new Repository/DAO/Map pattern.

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7124] opened 2021-06-15 12:35 UTC
The `emailTemplate` entity needs to be converted to use the new pattern for DAOs, Maps and Repositories introduced in #5328. This requires the following:

- [x] Convert the DAO to extend `EntityDAO` and use type hints.
- [x] Convert the `EmailTemplateService` to a repository .
- [x] Convert `EmailTemplateService::getProperties()` to a Map that extends `PKP\core\maps\SchemaMap`. 
- [x] Add any necessary methods to `emailTemplates\Repository` so that direct access to the DAO is not required.
- [x] Refactor existing uses of `DAORegistry::getDAO('EmailTemplateDAO')` to use the repository instead.

**Comment by Vitaliy-1** [comment] 2021-10-14 18:13
>  Add any necessary methods to EmailTemplateService so that direct access to the DAO is not required

Created `Repository` class that implements methods to manage email templates

**Comment by Vitaliy-1** [comment] 2021-10-20 12:47
@NateWr, are filtering parameters `limit` and `offset` needed for email templates? They aren't mentioned in the API docs but present in the old query builder (although aren't implemented in the email template handler).

**Comment by NateWr** [comment] 2021-10-20 13:11
I think if they exist and it's not much work to keep them, lets keep them. I can see it being useful in the future when email sending is better and (hopefully) people create lots more custom email templates.

**Comment by Vitaliy-1** [comment] 2021-10-31 19:03
Hmm, 2 tests are failing in OMP and I'm unable to reproduce the error locally. The script that fails is `CompetingInterests` and it seems to be unrelated to email templates.

**Comment by NateWr** [comment] 2021-11-01 09:19
Looks like maybe a database column error with MySQL. I found the error in the tests' [raw log](https://api.travis-ci.com/v3/job/545934085/log.txt).

```
[31-Oct-2021 17:51:51 UTC] Slim Application Error:
Type: Illuminate\Database\QueryException
Code: 42S22
Message: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'et.email_id' in 'on clause' (SQL: (select `etd`.`can_disable`, `etd`.`can_edit`, COALESCE(etd.email_key, et.email_key) as email_key, `etd`.`from_role_id`, `etd`.`to_role_id`, `etd`.`stage_id`, `et`.`email_id`, `et`.`context_id`, COALESCE(et.enabled, 1) as enabled from `email_templates_default` as `etd` left join `email_templates` as `et` on `etd`.`email_key` = `et`.`email_key` and `et`.`context_id` = 1 where (`et`.`context_id` is null or `et`.`context_id` = 1) and `etd`.`email_key` in (select `etd`.`email_key` from `email_templates_default` as `etd` inner join `email_templates_default_data` as `etddata` on `etd`.`email_key` = `etddata`.`email_key` left join `email_templates_settings` as `ets` on `et`.`email_id` = `ets`.`email_id` where LOWER(et.email_key) LIKE CONCAT('%', LOWER(), '%') or LOWER(etd.email_key) LIKE CONCAT('%', LOWER(), '%') or LOWER(etddata.subject) LIKE CONCAT('%', LOWER(), '%') or LOWER(etddata.body) LIKE CONCAT('%', LOWER(), '%') or LOWER(etddata.description) LIKE CONCAT('%', LOWER(), '%') or (`ets`.`setting_name` = subject and LOWER(ets.setting_value) LIKE CONCAT('%', LOWER(), '%')) or (`ets`.`setting_name` = body and LOWER(ets.setting_value) LIKE CONCAT('%', LOWER(), '%'))) order by `email_key` asc) union (select `etd`.`can_disable`, `etd`.`can_edit`, COALESCE(etd.email_key, et.email_key) as email_key, `etd`.`from_role_id`, `etd`.`to_role_id`, `etd`.`stage_id`, `et`.`email_id`, `et`.`context_id`, COALESCE(et.enabled, 1) as enabled from `email_templates` as `et` left join `email_templates_default` as `etd` on `etd`.`email_key` = `et`.`email_key` where (`et`.`context_id` is null or `et`.`context_id` = 1) and `et`.`email_id` in (select `et`.`email_id` from `email_templates` as `et` inner join `email_templates_settings` as `ets` on `et`.`email_id` = `ets`.`email_id` where LOWER(et.email_key) LIKE CONCAT('%', LOWER(), '%') or (`ets`.`setting_name` = subject and LOWER(ets.setting_value) LIKE CONCAT('%', LOWER(), '%')) or (`ets`.`setting_name` = body and LOWER(ets.setting_value) LIKE CONCAT('%', LOWER(), '%')))) limit 30 offset 0)
File: /home/travis/build/pkp/omp/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php
Line: 671
Trace: #0 /home/travis/build/pkp/omp/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php(631): Illuminate\Database\Connection->runQueryCallback('(select `etd`.`...', Array, Object(Closure))
```

**Comment by asmecher** [comment] 2021-11-01 19:59
Just FYI, Vitaliy and I tracked this down to the "lateral derived tables" feature in recent MySQL releases; it's part of the SQL standard and also available in PostgreSQL. 

Unfortunately it doesn't appear to be available in MariaDB yet; see https://jira.mariadb.org/browse/MDEV-19078.

It is likely that MariaDB currently supports sloppier checks on derived tables than MySQL, which is why the current query fails on Travis but not our local dev installs:
```SQL
(
  SELECT etd.can_disable, etd.can_edit, COALESCE(etd.email_key, et.email_key) AS email_key, etd.from_role_id, etd.to_role_id, etd.stage_id, et.email_id, et.context_id, COALESCE(et.enabled, 1) AS enabled
  FROM email_templates_default AS etd
    LEFT JOIN email_templates as et on etd.email_key = et.email_key and et.context_id = 1
    WHERE (et.context_id is null or et.context_id = 1) AND etd.email_key IN (
      SELECT etd.email_key
      FROM email_templates_default as etd
        INNER JOIN email_templates_default_data as etddata on etd.email_key = etddata.email_key
        LEFT JOIN email_templates_settings as ets on et.email_id = ets.email_id where LOWER(et.email_key) LIKE CONCAT('%', LOWER(''), '%') or LOWER(etd.email_key) LIKE CONCAT('%', LOWER(''), '%') or LOWER(etddata.subject) LIKE CONCAT('%', LOWER(''), '%') or LOWER(etddata.body) LIKE CONCAT('%', LOWER(''), '%') or LOWER(etddata.description) LIKE CONCAT('%', LOWER(''), '%') or (ets.setting_name = 'subject' and LOWER(ets.setting_value) LIKE CONCAT('%', LOWER(''), '%')) or (ets.setting_name = 'body' and LOWER(ets.setting_value) LIKE CONCAT('%', LOWER(''), '%'))
    ) ORDER BY email_key asc
) UNION (
  SELECT etd.can_disable, etd.can_edit, COALESCE(etd.email_key, et.email_key) as email_key, etd.from_role_id, etd.to_role_id, etd.stage_id, et.email_id, et.context_id, COALESCE(et.enabled, 1) as enabled
  from email_templates as et
    left join email_templates_default as etd on etd.email_key = et.email_key
  where (et.context_id is null or et.context_id = 1) and et.email_id in (
  select et.email_id from email_templates as et
    inner join email_templates_settings as ets on et.email_id = ets.email_id
    where LOWER(et.email_key) LIKE CONCAT('%', LOWER(''), '%') or (ets.setting_name = 'subject' and LOWER(ets.setting_value) LIKE CONCAT('%', LOWER(''), '%')) or (ets.setting_name = 'body' and LOWER(ets.setting_value) LIKE CONCAT('%', LOWER(''), '%'))
  )
)

**Comment by asmecher** [comment] 2021-11-01 20:46
I think the following needs to be done:
- Now that the Laravel bug referred to in `getCompiledQuery` in 3.3.x is no longer relevant, merge `getCustom` and `getDefault` into a single `getQueryBuilder` (for consistency with the other `Collector` classes)
- Add checks to the first half of the `UNION` to make sure that it only returns matches when there *is not* a journal-specific query.
  -  When there is both a default and a journal-specific template, both halves of the `UNION` will match. The reason we're not seeing duplicates is because `UNION` suppresses them (as opposed to `UNION ALL`, which includes them).
  - If we explicitly exclude results from the 1st half that would also match the 2nd, we can remove the `email_template_settings` parts of the 1st query, including the problem match on `et.email_id`.

**Comment by Vitaliy-1** [comment] 2021-11-04 13:44
I've rewritten the way how SQL is formed. The default query builder now returns default templates without those that were customized, e.g.:
```sql
SELECT 
	email_key, can_disable, can_edit, from_role_id, to_role_id, stage_id, email_id, 1 as enabled, NULL as context_id
FROM 
	email_templates_default AS etd
WHERE 
	etd.email_key NOT IN (SELECT et.email_key FROM email_templates AS et)
AND...
	// filters here
```
Custom query builder returns only custom or modified email templates. This excludes the possibility of dubplicates SQL looks like:
```sql
SELECT 
	et.email_key, etd.can_disable, etd.can_edit, etd.from_role_id, etd.to_role_id, etd.stage_id, et.email_id, et.enabled, et.context_id
FROM 
	email_templates AS et
LEFT JOIN
	email_templates_default as etd
ON 
	et.email_key = etd.email_key
WHERE 
	et.email_id IN 
    	(SELECT ets.email_id FROM email_templates_settings AS ets
         WHERE ets.setting_name = 'body' AND ets.setting_value LIKE '%word%')...
// Other filters
```
Filters seem to work as expected. I'm doing tests locally and planning to renew the PR soon

**Comment by Vitaliy-1** [comment] 2021-11-04 19:36
I squashed commits in the PR. 
Some tests are failing but I suspect it's because of a recent commit in the `pkp-lib`.
@asmecher, can you take a look at the changes in the email template `Collector`?

**Comment by Vitaliy-1** [comment] 2021-11-05 13:46
Finally, tests are passing. 
@asmecher, I'm ready to merge this unless you think there is something left that should be done/changed here.

**Comment by asmecher** [comment] 2021-11-05 15:44
Merged -- thanks and congratulations, @Vitaliy-1! It even ended up being a net reduction in code.

**Closed by asmecher** 2021-11-05 15:44 UTC
Labels: Dev Housekeeping
