### ISSUE TITLE
NativeImportExportPlugin CLI import crashes without user on request [OJS 3.3]

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7603] opened 2022-01-10 16:45 UTC
**Describe the bug**
Starting with OJS 3.3, using the `importExport.php` CLI tool encounters a fatal error when it reaches a line like this: https://github.com/pkp/pkp-lib/blob/aedcd5a19a3bea7aa9d759cad159536287ca4ede/classes/services/PKPSubmissionFileService.inc.php#L321

**To Reproduce**
1. Run `php lib/pkp/tools/importExport.php NativeImportExportPlugin import ...`
2. Results in `PHP Fatal error:  Uncaught Error: Call to a member function getUsername() on null`

**What application are you using?**
 OJS 3.3 (`stable-3_3_0`), but applicable to any application using submission files.

**Comment by jonasraoni** [comment] 2022-05-30 11:46
Closing this issue as a duplicate of https://github.com/pkp/pkp-lib/issues/7190

**Closed by jonasraoni** 2022-05-30 11:46 UTC
Labels: Bug:1:Low
