### ISSUE TITLE
Permit declined reviews to be reinitiated

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4789] opened 2019-05-22 16:23 UTC
**Describe the problem you would like to solve**
Example: Our editors need a way to respond to reviewers who decline reviews, but later indicate that they are willing to undertake it.

**Describe the solution you'd like**
After the review is declined by the reviewer, an editor should be able to either reset its status (so the reviewer can accept it themselves) or accept it on the reviewer's behalf.

**Who is asking for this feature?**
@ajnyga :)

Migrated from https://github.com/pkp/pkp-lib/issues/2508#issuecomment-494640952

**PRs**

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9896
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4246 [TEST ONLY]
[omp](https://github.com/touhidurabir/omp) --> https://github.com/pkp/omp/pull/1704 [TEST ONLY]
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/789 [TEST ONLY]

This is for the additional enhancement proposed at https://github.com/pkp/pkp-lib/issues/4789#issuecomment-2014034378

**Comment by codybennett** [comment] 2019-08-01 19:32
I also support this feature request!!

**Comment by ChristieHurrell** [comment] 2019-09-18 15:47
Just adding a +1 to this feature request, one of our journals requested this feature today.

**Comment by librariam** [comment] 2019-09-19 14:12
Adding a similar requested from a hosted client as well. For additional details of the use case: a reviewer declined, stating they can't make the review due date, but the editor actually has flexibility with the timelines and can accommodate the reviewer's schedule.

**Comment by nim0x** [comment] 2019-09-23 09:30
Imo either permit reinviting or communicate that reinviting reviewers is not possible better - I keep getting requests from editors who think they are doing something wrong, when in fact it is by design.

**Comment by beitzel** [comment] 2020-08-17 18:14
As an editor, right now I have need of changing a reviewer's decline decision to Accepted.  But I see this is not (yet) possible in OJS 3 without database access (which I do not have).

**Comment by pmangahis** [comment] 2021-03-29 19:02
+1 from a Hosted journal

**Comment by librariam** [comment] 2021-04-14 16:51
+1 more from PKP|PS

**Comment by asmecher** [comment] 2021-04-14 17:58
Hi all -- in recent releases reviewers can be cancelled and reinstated, but reinstating a declined review does not currently reset the review request.

I propose the following workflow:
- A reviewer accidentally declines a review.
- The reviewer contacts the editor, wishing to undo this action.
- The editor cancels the review.
- The editor reinstates the review, contacting the reviewer in the process. This resets the decline/accept decision so that reviewer can choose again.

Would this workflow be OK? (@librariam and @pmangahis in particular?)

**Comment by librariam** [comment] 2021-04-14 19:17
@asmecher this sounds good, I just wonder in this case which email template will be used to let the reviewer choose again? Right now you can cancel and reinstate after the reviewer has already accepted and even submitted a review. Those scenarios call for different templates - unless we could use one that generic enough and just includes a direct review link?

BTW, out of curiosity I just tested in the 3.3 sandbox which template is used on reinstate and it's blank.

**Comment by asmecher** [comment] 2021-04-14 23:10
@librariam, I'm not sure about the admin history of the sandbox, but here's the template that comes up for me:
![image](https://user-images.githubusercontent.com/200411/114791748-dd845280-9d3b-11eb-86f7-26ab5ac57050.png)

**Comment by librariam** [comment] 2021-05-03 14:38
+ 1 more from PKP | PS

**Comment by librariam** [comment] 2022-02-28 13:38
+1 more from PKP|PS

**Comment by diegoabadan** [comment] 2022-02-28 14:15
We also receive this request from editors of journals we host.

**Comment by touhidurabir** [comment] 2022-09-08 12:28
@NateWr PRs to review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8242
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3538

I will start testing it for `OMP` as we have `Internal Review` system, so some extra modification may require for `OMP` .

**Comment by touhidurabir** [comment] 2022-09-12 10:06
@NateWr updated PRs

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8242
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3538
[omp](https://github.com/touhidurabir/omp) --> https://github.com/pkp/omp/pull/1201

**Comment by NateWr** [comment] 2022-09-12 16:07
Hi everyone, @touhidurabir has just about implemented this but we still need to answer a question: what exactly is the editor doing when they permit a declined review to be reinstated? Are they re-sending the review request to the reviewer, and the review should accept/decline the assignment again? Or are they simply changing the reviewer's decision from decline to accept, and the reviewer should move to the "completing review" step?

This matters because of how we will communicate this action in the UI and the message in the email that will be sent to the reviewer. For example, if we are re-sending the request to the reviewer, we would have an email like this:

> Dear Julie Janssen,
> 
> You have recently declined our request for you to review a submission, Sodium butyrate improves growth performance of weaned piglets during the first period after weaning, for Journal of Public Knowledge. We would like to request you to reconsider that decision and we hope that you are still able to conduct the review.
> 
> If you are able to assist with this journal's review process, you can login to the journal to view the submission, upload review files, and submit your review request.
> 
> If you have any questions, please contact me.
> 
> Kind regards,
> 
> {$signature}

However, if the editor is accepting this review request on the reviewer's behalf, then the email would need to be different. And we would probably need to log that an editor changed a reviewer's response from decline to accept.

Does anyone have some insight here? Especially pinging @librariam, @pmangahis, and @diegoabadan, but I'd invite comments from anyone who has been active on this issue.

**Comment by librariam** [comment] 2022-09-13 22:13
Hi @NateWr. Patricia and I and the team chatted about this today. It looks like both scenarios are possible, but it would be preferable to resend an invitation to the reviewer so they could accept the privacy statement and check the review deadlines – which it seems they won’t be able to if the editor were to accept on their behalf.

**Comment by asmecher** [comment] 2022-09-14 01:13
IMO it's important that the reviewer be the one to accept/decline the invitation, rather than letting the editor do it on their behalf. I would favour something that reverts a reviewer's previous Decline and invites them to Accept the review themselves.

**Comment by touhidurabir** [comment] 2022-09-14 06:54
> it would be preferable to resend an invitation to the reviewer so they could accept the privacy statement and check the review deadlines

> IMO it's important that the reviewer be the one to accept/decline the invitation, rather than letting the editor do it on their behalf

In that case, should we let editor the sent the request to reconsider it only once or as many time as the editor want to ? current PR implementation let the reconsider request to sent only once as that seems like an appropriate behaviour rather than sending it many times if the reviewer keep declining it . So basically if the reviewer declined the reconsider request/invitation , no more reconsider request/invitation can be sent . But would like to know if we want to make it more flexible and such requirement(multiple reconsider request/invitation if reviewer keep declining it) may seems necessary .

**Comment by NateWr** [comment] 2022-09-14 09:43
Thanks @librariam and @asmecher, that makes sense.

> should we let editor the sent the request to reconsider it only once or as many time as the editor want to ?

I'd say as many times as they want. An abusive editor is a human problem and one that should be resolved within the editorial team. Editors can already create users and do other potentially abusive things as much as they want.

@touhidurabir in light of these comments, can we update the naming of the classes and the terminology used in buttons and emails to reflect "Resend Request". Right now, it's written around language like "Reconsider Reviewer", but it's really the reviewer who is reconsidering. So I think from an editor's perspective the action that's happening is to resend the request to review. Once you've taken a pass at that, I'll do a final review and copyedit the email. :+1:

**Comment by ChristieHurrell** [comment] 2022-09-14 14:00
Agree with comments from @librariam and @asmecher -- scenarios for us where this has come up are
(1) when reviewer has accidentally declined
(2) when reviewer has declined because of logistical reasons (e.g. timeframe) that were able to be adjusted
So I think that allowing the editor to resend the request as many times as they want is the best and clearest solution, and agree with terminology proposed by @NateWr .
Thanks all!

**Comment by touhidurabir** [comment] 2022-09-15 07:11
@NateWr PRs to review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8242
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3538
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/215

Once we finalise the changes for the `OJS`, I will port the changes for `OMP` .

**Comment by touhidurabir** [comment] 2022-09-16 13:49
@nate PR updates to review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8242
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3538
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/215

**Comment by NateWr** [comment] 2022-09-19 11:19
Looks good. Happy to merge once OMP is ready. :+1:

**Comment by touhidurabir** [comment] 2022-09-19 15:31
@NateWr `OMP` PR updated . Final PRs

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8242
[ui-library](https://github.com/pkp/ui-library) --> https://github.com/pkp/ui-library/pull/215
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3538
[omp](https://github.com/touhidurabir/omp) --> https://github.com/pkp/omp/pull/1201

if test pass, it's good to merge.

**Comment by NateWr** [comment] 2022-09-20 08:45
All merged to `main`. :tada: Thanks @touhidurabir!

**Comment by asmecher** [comment] 2022-09-20 15:19
Excellent work, @touhidurabir, and thanks for the assist, @NateWr!

**Comment by Devika008** [comment] 2024-03-21 23:22
Hello Everyone,

Our attempt to redo the Submission Lists (#7495), often leads us through rabbit holes we didn't expect to glide through. One such rabbit hole came when we were working on redoing the review assignment details and progress trackers (#4172). Currently in the system, if the reviewer declines the invitation and or its overdue, the editor has an opportunity to resend the review request. On resending the review request however, it shows no other data other than the tag that the request has been resent. Even the due date remains unchanged even if it was months ago.

![image](https://github.com/pkp/pkp-lib/assets/112014397/3a6ed0b3-597c-4ba2-8e6c-1256590ac82f)
![image](https://github.com/pkp/pkp-lib/assets/112014397/ec9a197f-d15a-4ab7-8143-ef7d9752f2ab)
![image](https://github.com/pkp/pkp-lib/assets/112014397/6f1068cb-1194-4340-ac4e-1d60da633a5d)

The dates can be modified through edit due date however the information the editor wants to see to manage the review and the cycle of a manuscript seems a bit shorthanded at this moment 

### Proposal

When resending the review request, it should allow to set a due date for the request resent and treat it as a new request sent inspite the indication on the tag that states Request Reshared. I think this will help to effectively manage the workflow and give the editors the correct data points. With new request I mean that the countdown to show the due date and indicate overdue when the due date is passed.

![image](https://github.com/pkp/pkp-lib/assets/112014397/120a14ff-7f59-4a34-8f27-c24a4bcdb6aa)

@jardakotesovec please cover anything you think I might have missed

**Comment by touhidurabir** [comment] 2024-04-18 11:53
@Vitaliy-1 can you review the PRs 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/9896
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/4246

This is for the additional enhancement proposed at https://github.com/pkp/pkp-lib/issues/4789#issuecomment-2014034378

**Comment by Vitaliy-1** [comment] 2024-04-30 16:21
@touhidurabir, sorry for the late reply. I did a review an left a minor comment

**Comment by touhidurabir** [comment] 2024-10-10 10:07
Enhancement proposed at https://github.com/pkp/pkp-lib/issues/4789#issuecomment-2014034378 is resolved by https://github.com/pkp/pkp-lib/pull/9896 .

**Closed by touhidurabir** 2024-10-10 10:07 UTC
Labels: Community:2:Priority, Hosting, Enhancement:2:Moderate
