### ISSUE TITLE
[OMP] review file selection is unclear

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1144] opened 2016-02-16 20:19 UTC
From #1127, against `HEAD`:

It’s not obvious that review files have to be selected before the review process starts. A naïve user assumes that the submission files will be reviewed.

**Comment by crism** [comment] 2016-02-16 20:19
I don’t have (yet) a proposed solution, however… will keep thinking about it.

**Comment by asmecher** [comment] 2016-02-23 18:56
@crism, I think all files are selected by default, and you can spin out the selection grid to limit them only if you need to; are you seeing something different?

**Comment by crism** [comment] 2016-02-25 17:25
@asmecher, I think you’re right. Maybe this was broken when we tested? I can’t reproduce it now, so I’ll close it.

**Comment by crism** [comment] 2016-02-26 19:31
Here’s how to reproduce it:

1. Send a submission to internal review.
1. Don’t submit any revisions in response to the review.
1. Send the submission to external review.

The submission now has no review files. Selecting “Upload/Select Files” brings up an empty list; the user needs to check “Include all files…” to see useful things.

**Comment by asmecher** [comment] 2016-02-26 22:34
That's expected behavior, @crism, the "Select Files" area should show files from the previous stage by default, with the checkbox permitting the additional listing of files from stages before that.

**Comment by crism** [comment] 2016-02-26 23:01
Understood, @asmecher—but there’s a breakdown in the process here. I would expect at least one of these things to be possible:
* In “Internal Review,” select Review Files to promote to Revisions. (Currently, Revisions can only be populated by uploading files.)
* In “Send to External Review,” have the opportunity to select from among Review Files as well as Revisions. (Currently, the Revisions section is presented, but with no files, it’s not obvious that here is where I could select files if there were any.) This should be true even if there were Revisions; an author might only submit revisions for some parts of a monograph, for instance.
* In “External Review,” when uploading or selecting “Review Files,” offer all the Internal Review Review Files and Revisions for selection by default. (Currently, only the I.R. Revisions are offered, an empty list if there were none; checking “Include all files…” shows _all_ files ever.)

This all applies to moving from External Review to Production, too.

**Comment by NateWr** [comment] 2016-03-02 17:28
I agree there's an issue here that probably needs sorting out. I see a few different issues:

1. It's not clear to the user what they're selecting the files for in the Request Revisions/Send to External Review/Resubmit for Review modals. It seems like these files are going to be emailed to the author, which doesn't seem appropriate (and I don't think that's what actually happens). There's no indication that we are forwarding files for use in the next stage.

2. *Are* the files going to be sent to the author? Why are the Reviewer's Attachments available here? In a double-blind situation, should they be there?

3. We probably need to add the Review Files grid as an option to select here in addition to the Revisions grid, for the reasons @crism outlined.

For (1) a sentence describing the file selection might be enough (ideally we'd have a way to group things visually and provide a title/description, but I got rid of this in the existing FBV because it was applied really inconsistently).

For (2) and (3) we just need a decision and then adding/removing should be straightforward. I'm tagging @stranack in this to see if he has any insights from the user testing he's done.

A reminder of what the modal looks like (this is the Resubmit for Review but others are similar).

![selection_168](https://cloud.githubusercontent.com/assets/2306629/13468747/1fc24e2a-e09c-11e5-8536-56a38b22be9a.png)

**Comment by beghelli** [comment] 2016-03-02 18:44
@NateWr We have this problem with all editorial decisions modals, I think. And I think that the problem is that we are mixing two tasks in one place: user communication and files management.

Maybe we could breakdown this modal into two steps? Something like two tabs, one for "Files selection" and another one for "User notification".

**Comment by bozana** [comment] 2016-03-03 10:59
That is the place where both happens, the authors notification and forward to the next workflow step. Thus, the chosen files above should/are meant to be sent to the authors -- they can contain any kind of further instruction for the authors, but probably mostly they will contain the original text with the reviewer comments and could be the files the authors should further work with, I believe. And if reviewers are cautious, they will pay attention, that the comments and file are anonymized. Else, the editor has the possibility to upload the anonymized file i.e. the the editor should have an overview about that and make decisions.

**Comment by NateWr** [comment] 2016-03-03 11:14
Ok, in that case then the modals do what the seem like they are going to do, so that's good! In that case, I've completely hijacked this issue for no good reason.

I think the only thing that needs to be actioned is @crism's initial complaint that the review files need to be selectable here too.

I suspect we'll see a certain amount of confusion here. I am partial to what @beghelli suggested about breaking it into two steps, but I'd rather wait for the user tests to see how much confusion there really is.

**Comment by beghelli** [comment] 2016-03-03 12:58
@bozana When you say files are sent, this doesn't mean via email. They are made visible to authors and other users, but inside the system. No email attachment is happening here, and that's the confusion.

That's why I suggest we break down these into two steps, to clear out this attachment confusion.

**Comment by asmecher** [comment] 2016-03-23 22:54
Deferring to post-1.2, barring outcry. Everything is currently working as intended, though there's definite room for improvement. In "promote" boxes (e.g. "send to external review"; "send to copyediting", etc) the file lists only show what's available in the stage you're leaving, though it's possible to use the Select modal in the new stage to pull files from further back. The motivation for this is that it keeps the lists uncluttered and suits most use cases.

One option would be to add a "show files from previous rounds" checkbox as we've already done for the "select" modals. But I'd rather not cram that in so close to 1.2 being released.

**Comment by crism** [comment] 2016-03-23 22:56
@asmecher: understood. We can educate our users on the intended approach, I think.

**Comment by NateWr** [comment] 2016-03-28 09:18
I'm fine pushing this to after OMP 1.2 since the way it works is already in existing versions. But I'm definitely nervous about the UI being a source of unintentional information leak in the blind review process. See #1300, which caught me off guard even though we discussed this exact interaction just a few weeks ago.

I don't think the file selection is an issue, so much as clarity over where those files are going to be sent/shared. Splitting the process into two as @beghelli says could be a good way to address this. 

I'll put the OJS 3.0 milestone on this because I think this is one area where user testing might not flag up a problem, because users might not even notice the files are being shared in unexpected ways.

**Comment by NateWr** [comment] 2016-05-12 10:37
This is just a note for whenever we turn back to this issue: there are some more UX issues that came out of the usability testing that should probably be addressed alongside this issue.

**Comment by asmecher** [comment] 2016-07-18 23:19
I'm satisfied with this for OJS 3.0 -- deferring, barring outcry. It would also be good to review the problematic area again since I think we've gotten better with default selections since this was filed.

**Comment by NateWr** [comment] 2017-08-23 16:38
I've made some changes to address the requests in this issue as well as #1258 and other feedback from our UI/UX testing. These changes include:

1. The Request Revisions and Resubmit for Review buttons have been combined into a single button, with the decision selection in the modal.

![request-revisions](https://user-images.githubusercontent.com/2306629/29627167-0b1af306-8829-11e7-90f2-9181801f55dc.gif)

2. Email notification and the sharing of review files with the author is a bit clearer.

![email-notifications](https://user-images.githubusercontent.com/2306629/29627207-3cd89628-8829-11e7-9dfe-dedfb48295fd.gif)

3. The promotion of a submission from one stage to another has been broken into a two-step form. The first step deals with author notification. The second with promoting files to the subsequent stage. When promoting from Copyediting to Production, it's now possible to select from the Draft files grid, but these files are not selected by default.

![two-stage-promotion](https://user-images.githubusercontent.com/2306629/29627271-74bd6230-8829-11e7-9e30-6ad39c6d9ca8.gif)

My sense is that this is an improvement in clarity. But since it's such a critical part of the workflow, it'd be good to get a sense from others whether or not this addresses the requests or if there is any confusion introduced with these changes.

PRs:
https://github.com/pkp/pkp-lib/pull/2733
https://github.com/pkp/ojs/pull/1503
https://github.com/pkp/omp/pull/432

**Comment by alexxxmendonca** [comment] 2017-08-23 17:21
I really like this. It looks very straightforward and it gives a sequential feeling to it.

I just have one suggestion: in the first modal windown, after clicking on "Request Revisions", I think it would make more sense the default option to be "Revisions will be subject to a new round of peer review".

Chances are that revisions will go through peer review again so I would consider the "Not going to peer review" as an exception.

This could pottentially avoid the more inattentive Editors from committing mistakes. 

If the other way around happens (ie: the editor mistakenly marks the option to send the revision for peer review), I assume it would be easy to skip that part once they realise it's not necessary?

**Comment by NateWr** [comment] 2017-08-24 12:20
@alexxxmendonca I think you're right that a new round of peer review is the better default option. However, I'm nervous about prior conditioning.

We used to have two buttons: Request Revisions and Resubmit for Review. Those have been combined to Request Revisions. In the past, Request Revisions has been the button for _not_ requiring a new round of reviews.

Since existing users have learned that Request Revisions is the button for no new review round, I wonder if it's a good idea to have a different behaviour be the default.

Perhaps we can combat this by tweaking the language of the button. Maybe "Revisions Required". That may not be enough to dislodge old expectations. 

I wonder if anyone else has thoughts about which option should be default?

**Comment by NateWr** [comment] 2017-08-29 12:49
Tests are passing. But I'm going to wait until #2433 is merged, so that I can implement these changes on the recommend form.

**Comment by NateWr** [comment] 2017-09-04 10:03
Based on some external discussions about the `isViewable` flag, we should make sure the selectable copyedited files are selectable regardless of the `isViewable` flag. And this change should be backported to `ojs-stable-3_0_2`.

**Comment by NateWr** [comment] 2017-09-14 14:12
@bozana The tests were passing before the test issue that cropped up today. Would you be able to code review these PRs?

https://github.com/pkp/pkp-lib/pull/2733
https://github.com/pkp/ojs/pull/1503
https://github.com/pkp/omp/pull/432

**Comment by bozana** [comment] 2017-09-15 10:52
@NateWr, :+1, just a few minor changes needed and I had just a few questions... :-)

**Comment by bozana** [comment] 2017-09-20 06:49
I've rebased this and made a new PRs in order to be able to merge it:
omp master: https://github.com/pkp/omp/pull/441
ojs master: https://github.com/pkp/ojs/pull/1537
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2795

**Comment by bozana** [comment] 2017-09-20 06:52
Everything merged, thus closing....

**Closed by bozana** 2017-09-20 06:52 UTC
Labels: UI/UX Review
