### ISSUE TITLE
3.3.0 installs a locale column in the publications table that should have been removed

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7958] opened 2022-05-27 20:21 UTC
**Describe the bug**
We've noticed a discrepancy in the schema between a fresh install of stable-3_3_0 and an upgraded stable-3_3_0.  The former has a locale column on the publications table but the upgraded one does not.

The PKPPublicationDAO in 3.3 sets the locale on the publication object by fetching it from the submission associated with it:

https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/publication/PKPPublicationDAO.inc.php#L54-L58

But that's marked as a deprecated field:  https://github.com/pkp/pkp-lib/blob/stable-3_3_0/xml/schema/submissions.xml#L27

We are concerned that a column seems to be missing after an upgrade and the field that contains the locale for a submission is deprecated.  It would be unfortunate  if an upgrade later on assumed 3.3.0 databases had a populated locale column in the publications table and dropped the submissions one.

**To Reproduce**
1. Begin with an installation of 3.2.1, and verify that the publications table has a locale column.
2. Upgrade to stable-3_3_0
3. After the upgrade, examine the publications table again.  It will no longer have a locale column.

**What application are you using?**
OJS stable-3_3_0

**Comment by NateWr** [comment] 2022-05-30 08:53
The `locale` column should not be on the publications table. The bug is with the install code. This line should be removed:

https://github.com/pkp/ojs/blob/stable-3_3_0/classes/migration/OJSMigration.inc.php#L188

And I guess now we'll need an upgrade script in 3.4 to remove it again.

**Comment by jnugent** [comment] 2022-05-30 13:04
PR against `stable-3_3_0`: https://github.com/pkp/pkp-lib/pull/7959

**Comment by asmecher** [comment] 2022-06-02 12:39
Shifting this one to 3.4. Since it isn't actively causing problems, adding a migration to remove the column with 3.4.0 will mean just fixing it once.

**Comment by asmecher** [comment] 2022-06-02 12:41
In fact, this is a duplicate of https://github.com/pkp/pkp-lib/issues/7463, which has already been resolved against 3.4.

**Closed by asmecher** 2022-06-02 12:41 UTC
Labels: Bug:1:Low
