### ISSUE TITLE
Not able to install plugins as admin on OMP 3.4.0 RC

### ISSUE THREAD

**Issue by joshnoronha** [pkp/pkp-lib#8772] opened 2023-03-10 18:41 UTC
**Describe the bug**
OK button does nothing.

**To Reproduce**
1. Go to 'website settings / plugin gallery'
2. Click on 'any plugins / install / OK button'
3. Nothing happens, modal screen only disappears after clicking on it.

**What application are you using?**
 OMP 3.4.0 RC

**Additional information**
Error log:

```
PHP Fatal error:  Uncaught UnexpectedValueException: Cannot create phar '/tmp/pluginoHAwYV', file extension (or combination) not recognised or the directory does not exist in /var/www/html/lib/pkp/classes/plugins/PluginHelper.php:67\nStack trace:\n#0 /var/www/html/lib/pkp/classes/plugins/PluginHelper.php(67): PharData->__construct('/tmp/pluginoHAw...')\n#1 /var/www/html/lib/pkp/controllers/grid/plugins/PluginGalleryGridHandler.php(318): PKP\\plugins\\PluginHelper->extractPlugin('/tmp/pluginoHAw...', 'betterPassword-...')\n#2 [internal function]: PKP\\controllers\\grid\\plugins\\PluginGalleryGridHandler->installPlugin(Array, Object(APP\\core\\Request))\n#3 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\\core\\Request))\n#4 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\\core\\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\\core\\Request), Array)\n#5 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\\core\\PKPComponentRouter->route(Object(APP\\core\\Request))\n#6 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\\core\\Dispatcher->dispatch(Object(APP\\core\\Request))\n#7 /var/www/html/index.php(21): PKP\\core\\PKPApplication->execute()\n#8 {main}\n  thrown in /var/www/html/lib/pkp/classes/plugins/PluginHelper.php on line 67, referer: https://omp.testing.publicknowledgeproject.org/
```

**Comment by asmecher** [comment] 2023-03-10 18:50
This is a duplicate of https://github.com/pkp/pkp-lib/issues/8723.

**Closed by asmecher** 2023-03-10 18:50 UTC
