### ISSUE TITLE
OMP 3.4.0.0: unable to add a cover image to a book

### ISSUE THREAD

**Issue by felixhelix** [pkp/pkp-lib#7792] opened 2022-03-24 15:18 UTC
**Describe the bug**
When trying to add a cover image to a book, OMP throws an error:

```
[Thu Mar 24 15:03:53 2022] PHP Warning:  Undefined array key "uploadName" in D:\xxx\omp\classes\publication\Repository.inc.php on line 251
[Thu Mar 24 15:03:53 2022] PHP Warning:  Undefined array key "uploadName" in D:\xxx\omp\classes\publication\Repository.inc.php on line 254
[Thu Mar 24 15:03:53 2022] PHP Warning:  Undefined array key "extension" in D:\xxx\omp\classes\publication\Repository.inc.php on line 390
[Thu Mar 24 15:03:53 2022] PHP Warning:  Undefined array key "extension" in D:\xxx\omp\classes\publication\Repository.inc.php on line 406
[Thu Mar 24 15:03:53 2022] Slim Application Error:
Type: Exception
Message: Can not build thumbnail because the file was not found or the file extension was not recognized.
```

The cover image is uploaded in the /temp directory, and also deleted after the failed attempt. But obviously it cannot be referred to by the omp instance. 

**What application are you using?**
OMP 3.4.0.0

---
PRs

OJS: pkp/ojs#3598 (***TESTS ONLY***)
OPS: pkp/ops#384 (***TESTS ONLY***)
OMP: pkp/omp#1237
pkp-lib: #8391

**Comment by defstat** [comment] 2022-10-24 10:53
@asmecher @NateWr I have added a PR for that [here](https://github.com/pkp/pkp-lib/issues/7792#issue-1179665538).

**Notes:** 
1. The code for the `coverImage` seems to be added to both `lib-pkp` and `omp` publication edit function. I suppose that this tried to reconcile with possible differences between the implementation of the cover image for OJS and OMP. I moved and changed a little bit the code to lib-pkp, thinking that the entity that we are considering for coverImage is the publication.

**Comment by NateWr** [comment] 2022-10-24 14:14
The problem is that cover image thumbnails are not supported in OJS or OPS. That's why the implementation is distinct. I don't think we should try to add them to OJS/OPS at this late stage of 3.4. Adding them will require we think through a lot more things: how they are used in themes, how the thumbnail size is configured, how we produce thumbnails from existing cover images, etc.

**Comment by defstat** [comment] 2022-10-25 09:37
So should I move all related code to OMP only? Should we consider plugins like QuickSubmitPlugin (which adds a cover image)?

**Comment by NateWr** [comment] 2022-10-25 09:45
I would say if the bug is only in OMP then let's just solve it there for now. At least the thumbnail stuff needs to stay in OMP for now.

I'm not really sure about QuickSubmit. But if it's thumbnail-related then QuickSubmit shouldn't matter. It doesn't support OMP.

**Comment by defstat** [comment] 2022-11-02 07:29
@bozana, [here](https://github.com/pkp/pkp-lib/issues/7792#issue-1179665538) I am proposing a fix for that. This takes care of both issues described:
1. Not being able to create a coverImage thumbnail in OMP
2. Not being able to delete a cover image. 
3. It also changes the `Alternate text`'s validation rule, so that it's not mandatory.

The deletion bug existed also in OJS (submission -> publication -> issue -> cover image) and it seems fixed there also.

The tests are failing with an (probably) unrelated error at unit tests. 

Fixing this I came across a UI problem which I filed here: #8393

**Comment by bozana** [comment] 2022-11-07 11:19
Hi @defstat, I think you can rebase and provide the new submodule updates for all 3 applications, and when tests pass we can merge...

**Comment by defstat** [comment] 2022-11-09 10:00
@bozana, all rebased and tests have passed.

**Comment by bozana** [comment] 2022-11-09 10:32
Thanks a lot @defstat! All merged :tada: :-)

**Closed by bozana** 2022-11-09 10:32 UTC
Labels: Bug:1:Low
