### ISSUE TITLE
oaiJats should not appear in site-wide plugins

### ISSUE THREAD

**Issue by ZahraMousavi** [pkp/pkp-lib#6137] opened 2020-07-23 08:52 UTC
Hi. I am trying to install oaiJats on a OJS3.2.1-1. When I am trying to enable the plugin it breaks and I get the following error message in the logfile:
_Fatal error:  Uncaught Error: Call to a member function getId() on null in /srv/ojs/ojs3-devel/webroot/plugins/oaiMetadataFormats/oaiJats/OAIMetadataFormatPlugin_JATS.inc.php:78
Stack trace:
#0 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.inc.php(246): OAIMetadataFormatPlugin_JATS->setEnabled()
pkp/oaiJats#1 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/core/PKPRouter.inc.php(391): PluginGridHandler->enable()
pkp/oaiJats#2 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()
pkp/oaiJats#3 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/core/Dispatcher.inc.php(143): PKPComponentRouter->route()
pkp/oaiJats#4 /srv/ojs/ojs3-devel/webroot/lib/pkp/classes/core/PKPApplication.inc.php(279): Dispatcher->dispatch()
pkp/oaiJats#5 /srv/ojs/ojs3-devel/webroot/index.php(68): PKPApplication->execute()_

I appreciate any help!

**Comment by ZahraMousavi** [comment] 2020-08-03 07:23
My pleasure! And thank you for helping me understand the issue. 

Best regards

**Comment by asmecher** [comment] 2020-08-12 13:47
This is actually a duplicate of https://github.com/pkp/pkp-lib/issues/1923 -- closing this in favour of that one!

**Comment by asmecher** [comment] 2020-08-14 23:24
@ZahraMousavi, I'm just getting around to trying this out, but it looks like the plugin enable button is disabled for this plugin in the site-wide plugin area, as it should be. (I'm working with OJS 3.2.1-1.) Are there any particular steps you followed to enable the plugin site-side?

**Comment by ZahraMousavi** [comment] 2020-08-18 10:22
@asmecher I am trying this on a test-server with OJS 3.2.1-1. I haven't done anything specific to make it available there. I browse to [servername]/index.php/index/admin/settings, and upload the zip file using Upload A New Plugin button, reload the page and scroll to the section 'OAI Metadata Format Plugins' and trying to enable 'JATS Metadata Format' and it breaks (no reaction until I refresh). 
By the way, a dummy question, is the standard way of adding plugins via git or via plugin gallery ([servername]/index.php/index/admin/settings)?

**Comment by asmecher** [comment] 2021-09-20 20:44
If anyone is able to share steps to replicate this problem on a fresh installation, please do!

**Comment by asmecher** [comment] 2022-02-04 20:25
It doesn't look like anyone has been able to reproduce this; closing.

**Closed by asmecher** 2022-02-04 20:25 UTC
Labels: Bug
