### ISSUE TITLE
[OJS] Upgrading to OJS3: authors can not download the revisions they have uploaded

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2187] opened 2017-01-12 05:24 UTC
Authors can not access the uploaded files in the revisions grid: {"status":false,"content":"The current role does not have access to this operation.","elementId":"0"}

The reason is that the migration rewrites ownership of submission files. Chancing the file owner enables the author to open the files.

Should the logic in the grid be changed or would it be possible to preserve file ownership better during the migration?

Also, any ideas how to fix this now that we have upgraded our production server are welcome.

Mentioned here: https://github.com/pkp/pkp-lib/issues/2159#issuecomment-271789283

**Comment by bozana** [comment] 2017-01-12 12:20
Hmmm... Theoretically, an editor could/should be able to upload a revision file as well, right? Thus, I would say that the author could access the revision files regardless who uploaded them, but I am not sure if I overlook something :-\ @asmecher, what do you think?

**Comment by ajnyga** [comment] 2017-01-12 12:27
Maybe I am overlooking something.

Basically the authors sees the revision in the grid, but can not open it or push the edit button.

The only way I could fix that was by changing the owner.

**Comment by bozana** [comment] 2017-01-12 13:38
Yes, yes, but if we would maybe change the author access policy for the revisions files... so that the author could access those files regardless of the uploader...

**Comment by ajnyga** [comment] 2017-01-12 19:15
ah ok, I read you wrong, sorry.

I also noticed that when the author uploads a new file, in same cases the file uploader has both the author revision file and the review file in the dropdown menu where you can choose for which file you are submitting a revision. 

Does the file upload list all files from the same uploader there? This would explain why I see the review file there as well.

**Comment by bozana** [comment] 2017-01-16 18:46
@ajnyga, as far as I can see, author (but also editor) gets there the list of the files that are uploaded in that stage i.e.  those files in the grids "Review Files" and "Revisions", no matter who is the uploader.

**Comment by bozana** [comment] 2017-01-16 20:34
PRs:
pkp-lib ojs-stable-3_0_1: https://github.com/pkp/pkp-lib/pull/2204

**Comment by bozana** [comment] 2017-01-16 20:34
@asmecher, could you take a look at the PR above?

**Comment by ajnyga** [comment] 2017-01-16 20:38
@bozana, the fact that the author is seeign both the review file versions and her own revisions in the upload dialog has to be a migration issue.

If I add a new submission using OJS3 a similar situation does not occur. 

I am only worried what happens if an author picks the review file from the pull down uploads a new version of that file?

**Comment by bozana** [comment] 2017-01-16 20:40
OK, I''ll take a look on that too :-)

**Comment by bozana** [comment] 2017-01-16 20:41
But maybe a question: what do you mean by "review file"? The files from the grid "Review Files"?

**Comment by ajnyga** [comment] 2017-01-16 20:53
Yes exactly. The author does not see the review files in the revisions grid, only in the upload dialog in the pulldown menu.

**Comment by bozana** [comment] 2017-01-17 11:29
@ajnyga, I believe this is intended to be so (the selection of the files from that stage) i.e. it is OK so: in that case a new revision file will be created (the original review file will not be overwritten) and in the DB table `submission_files` the new file will have `source_file_id` = the original file ID. I think this is how it is meant to be.

**Comment by ajnyga** [comment] 2017-01-17 13:05
It's just that I can not reproduce this with a submission that I have started using OJS3. This only happens with the migrated submissions. The review file and the author revision file seem to have separete file_id's. Therefore it seems odd that the author would be able to upload a new version of the review file. That would mean that the new version would not be included in the revisions panel at all but would be loaded to the review file panel of the ongoing round? This sounds very confusing. Of course this is a theoretical problem as long as the authors do not select the review file from the pulldown. What happens after that, I am not sure.

**Comment by bozana** [comment] 2017-01-17 13:11
I can reproduce it with my OJS 3 installation i.e. without migration.
The new file, based on the original review file, would be loaded in the revisions grid, where the author also tries to upload it.
I wonder why you cannot reproduce that with a submission started using OJS 3?

**Comment by bozana** [comment] 2017-01-24 11:32
Everything merged, so closing...

**Closed** 2017-01-24 11:32 UTC

**Comment by ajnyga** [comment] 2017-01-26 13:35
There is still a problem with what the author sees when uploading revision files and this happens only the migrated articles.

Here are screenshots of what happens with submission done in OJS3, this is what should happen:

First, a view from the editorial side. Two files visible 65003 (review file) and 65004 (author revision)
![screenshot_83](https://cloud.githubusercontent.com/assets/16347527/22332970/537c3912-e3dc-11e6-8895-d94263735edd.png)

Same submission from the author side. Only the author revision visible in the grid as it should:
![screenshot_84](https://cloud.githubusercontent.com/assets/16347527/22333017/80b94af0-e3dc-11e6-8db2-32aae7751287.png)

And when author uploads a file, **again** only the **author revision**  visible in the list, **not**  the review file (65003): 
![screenshot_85](https://cloud.githubusercontent.com/assets/16347527/22333062/bcd9ea12-e3dc-11e6-9c86-dfe250f22d8c.png)

**But**, as I described above, this is not the case with the migrated submission. In the migrated submissions the author also sees the review file in the file uploads.

So something has to be wrong here and I am worried of what happens if the author chooses to upload a revision of the review file?

**Comment by bozana** [comment] 2017-01-26 13:56
@ajnyga, when you in OJS 3 assign a reviewer with the review file 65003-1 above, than the author will get that file for selection too. Could you please check and confirm it?

**Comment by bozana** [comment] 2017-01-26 13:57
Then, if the author select that file and uploads a revision based on that file, the original review file will not be changed i.e. just a new revision will be added, right?

**Comment by ajnyga** [comment] 2017-01-26 14:10
No, assigning the review file 65003-1 does not change anything. The pull down is still only showing the author revision - not two files.

The original review file is visible in the pull down only when there are no earlier author revisions available. Once an author revision is added, the original review file is not there any more.

However, with the migrated files I can still see both the original review file and the first author revision.

**Comment by bozana** [comment] 2017-01-26 14:15
hmmm... I am currently on master branch and I can see both:
![bildschirmfoto von 2017-01-26 15 12 43](https://cloud.githubusercontent.com/assets/378421/22334206/23a71e5c-e3da-11e6-802b-28a19baa1ac9.png)

**Comment by bozana** [comment] 2017-01-26 14:15
Can you then tell me what happens when you choose that review file? Or can you not test it because in production?

**Comment by ajnyga** [comment] 2017-01-26 14:15
A new test submission started in OJS3. A started a review round, added a reviewer, made a request for changes and submitted a revision as the author. The end result:
![screenshot_88](https://cloud.githubusercontent.com/assets/16347527/22334087/010830f4-e3e2-11e6-84f3-24d761cbd524.png)

Only the author revision in the author's grid, as it should:
![Uploading Screenshot_89.png…]()

Only the revision available here as well, not the the original review file:
![screenshot_90](https://cloud.githubusercontent.com/assets/16347527/22334246/af910f7e-e3e2-11e6-8b71-c6b38d01bc2c.png)

**Comment by ajnyga** [comment] 2017-01-26 14:17
Ok, I am basically in OJS 3.0.1 stable. Could that make the difference?

**Comment by bozana** [comment] 2017-01-26 14:19
I will try in OJS 3.0.1 stable too...

**Comment by ajnyga** [comment] 2017-01-26 14:20
In OJS 3.0.1. I mean the version you provide in your webpage, not the Github version with the cherry picks

**Comment by bozana** [comment] 2017-01-26 14:21
@asmecher, are review files (the files in Review Files grid) supposed to be provided for selection in the Revisions grid ("If you are uploading a revision of an existing file, please indicate which file.")?

**Comment by bozana** [comment] 2017-01-26 14:21
Lets see what Alec says -- he will surely know if this should or should not be :-)

**Comment by bozana** [comment] 2017-01-26 14:29
Also: if the editor uploads a file in Review Files grid, that file will also be provided for the selection in Revisions grid, but the author cannot then upload a file: "The current role does not have access to this operation.". -- probably because he/she was not the uploader...

**Comment by ajnyga** [comment] 2017-01-26 14:31
I found a migrated submission where I could test this!

Basically what happens is that a new file is created with a new file id and now there are two separate files visible in the revisions grid.

Also after uploading the new file the original review file is no longer in the pull down menu. So some kind of linking is happening there that has not been migrated correctly.

But then again, I do not know why you can not reproduce this with your system. In my opinion, what you are seeing is not right.

**Comment by ajnyga** [comment] 2017-01-26 14:44
Just to make clear, the way this works now for me with 3.0.1 is that with no earlier author revisions in the round the author sees the original review file in the pull down. After uploading an author revision, the only file visible there is the revision file (except for the migrated submissions).

If the review file would be always available in the pull down menu, and choosing that file when uploading always creates a new file, then the whole revision system is not working as it should be. The end result could be that there would be several separate files in the revisions grid.

**Comment by bozana** [comment] 2017-01-26 15:04
@ajnyga, this is correct behavior: if someones uploads a revision of a file, then only that file i.e. the last revision will be provided for selection, s. https://github.com/pkp/pkp-lib/blob/master/controllers/wizard/fileUpload/form/PKPSubmissionFilesUploadBaseForm.inc.php#L234. 
Thus, are maybe your revision files actually the revisions of the review file? -- There where you can select only the revision file? Could you take a look in the DB? Else, I do not know why you see it like that, and me differently. 
I am looking further in the code to try to understand how is this functioning and to see if that changed since release...

**Comment by bozana** [comment] 2017-01-26 15:17
And if I understand this correctly: all the files from that review round are provided:
I think they are collected here: https://github.com/pkp/pkp-lib/blob/master/controllers/wizard/fileUpload/form/PKPSubmissionFilesUploadBaseForm.inc.php#L149 i.e. the function `getRevisionsByReviewRound` gets only `reviewRound` as parameter and not also the `fileStage`.

**Comment by bozana** [comment] 2017-01-26 15:32
Maybe it does make sense: the Review Files are usually the files author submitted i.e. the editor prepared for review. Thus they are the last submission version to work with. I.e. if revisions are required, the author could say "This is the revision of that file". Except one thing: author does not see the Review Files grid and cannot download those files there.
Hmmm... lets see what Alec says...

**Comment by ajnyga** [comment] 2017-01-26 18:33
So I installed a fresh 3.0.1 which I downloaded from PKP and it does not show two files in the pull down menu like your master branch does.

What happens is exactly what I described above:
- When sending the first revision, the pull down shows the original review file (file nr. 1)
- After uploading the first author revision, a new file_id is created (file nr. 2) and if the author goes on to add a new revision, the pull down menu only shows the earlier author revision (nr. 2) not the original review file (nro. 1).

**Comment by ajnyga** [comment] 2017-01-26 18:36
Ok, I think I know what is happening here:
@bozana, when you uploaded the first author revision, did you choose that it is a revision of the origianl review file (Author, 1-2-1-RV.doc) mentioned in the pull down menu? Or did you choose that it is a new file? I think it was the latter?

**Comment by ajnyga** [comment] 2017-01-26 18:57
The linking factor here is the source_file_id field in submission_files.

For the migrated articles the author revision files do not have the source_file_id set, it is NULL.

For the submission started in OJS3, when the author uploads the first revision and chooses that it is a revision of the original review file, the source_file_id is set as the file_id of the review file. This apparently clears to original review file from the pull down menu?

**Comment by bozana** [comment] 2017-01-27 08:37
Yes, that is what I was also thinking and looking into the code this is meant to be so... but I'll double check with Alec...
