### ISSUE TITLE
OJS 3.3 - Issue importing is not working in terminal

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#6589] opened 2021-01-13 19:09 UTC
**Describe the bug**
Importing XML issues is crashing and doesn't import issues from this format.

**To Reproduce**
1. Go to 'OJS folder.'
2. Run PHP  `tools/importExport.php NativeImportExportPlugin import issue-file.xml [JOURNAL_ACRONYM] [USERNAME]`
3.  See the error

**What application are you using?**
 OJS version 3.3

**Additional information**

Log error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function starts_with() in testing-3_3/plugins/importexport/native/          NativeImportExportPlugin.inc.php:489
Stack trace:
#0 testing-3_3/plugins/importexport/native/NativeImportExportPlugin.inc.php(329): NativeImportExportPlugin->parseOpts(Array,    Array)
#1 testing-3_3/tools/importExport.php(63): NativeImportExportPlugin->executeCLI('tools/importExp...', Array)
#2 testing-3_3/tools/importExport.php(69): importExport->execute()
#3 {main}
  thrown in testing-3_3/plugins/importexport/native/NativeImportExportPlugin.inc.php on line 489
```

**Comment by asmecher** [comment] 2021-01-13 20:06
This will be a duplicate of https://github.com/pkp/pkp-lib/issues/6590.

**Closed by asmecher** 2021-01-13 20:06 UTC
Labels: Bug
