### ISSUE TITLE
Submission searching in postgresql

### ISSUE THREAD

**Issue by eniocarboni** [pkp/pkp-lib#4599] opened 2019-03-13 22:48 UTC
OJS-3.1.2
With reference to issue #3807, in PostgreSQL no search now works anymore.
In fact, the problem is in the new query that uses the SQL reserved word "as" as a table alias without the right quotes. In MySQL it works but in PostgreSQL it doesn't.
https://github.com/pkp/pkp-lib/blob/stable-3_1_2/classes/services/queryBuilders/PKPSubmissionListQueryBuilder.inc.php#L340-L344
To understand better in PostgreSQL if I run the query:
```
select lower(as.username) from users as "as";
ERRORE:  errore di sintassi a o presso "as"
LINE 1: select lower(as.username) from users as "as";
                     ^
```
The working query is:
`select lower("as".username) from users as "as";`

**Comment by asmecher** [comment] 2019-03-15 16:53
@eniocarboni, thanks -- I see the problem is that we're using `as` as a table alias, when it's an SQL reserved keyword. I suspect rather than wrapping it in quotes we should probably just change the name of the alias altogether -- it's likely to cause us problems elsewhere down the line, e.g. we're working with a third party to add MS SQL Server support, and I wouldn't be surprised if SQL server refused to work with `as` in a different way. Is this something you've got the time to adjust?

**Comment by eniocarboni** [comment] 2019-03-15 17:04
@asmecher, I really like the idea of changing the name of the table but quoting his name and that of the column is still right to do.
I could try it in my spare time, thanks.

**Comment by eniocarboni** [comment] 2019-03-16 09:06
Hi @asmecher, I added a second commit on the same Pr, could you check, please?

**Comment by asmecher** [comment] 2019-03-19 02:19
(Thanks, @eniocarboni -- assigned to @NateWr on the pull request!)

**Comment by asmecher** [comment] 2019-05-15 18:59
I've merged this as https://github.com/pkp/pkp-lib/commit/cdc81fa1ad34034a1f76d6d0e500dd8add86cb2e -- thanks for contributing, @eniocarboni!

**Closed by asmecher** 2019-05-15 18:59 UTC
