### ISSUE TITLE
Porting of Lucene Plugin to OJS 3

### ISSUE THREAD

**Issue by Stefanvdb** [pkp/pkp-lib#4611] opened 2019-03-18 12:23 UTC
Hello,

I am new as a developer to OJS, so I hope I am using the right channel to ask these questions.

I am working on porting the Lucene/Solr plugin to OJS 3, and was pointed to this github-repo as a starting point: 
https://github.com/asmecher/lucene

Alec, which code/repo did you take as a starting point for this? I noticed for example that in your repo, there is the possiblity to rebuild the index from the plugins settings form, but I couldn't find this code in any of the lucene plugin repositories on https://github.com/pkp/ojs
Did I miss something, or have you added this code?

Then I found this option on the genre-form: 
"Mark files of this type as dependent files (e.g. not to be listed with published content)"

Does that mean, that galley-files of these genres should be excluded from the search index?

Thanks 
Stefan

**Comment by asmecher** [comment] 2019-03-18 15:35
@Stefanvdb, OJS 2.x used to ship with a Lucene plugin. That code persisted into the `master` branch but unsupported/unreleased. It should only have received occasional tweaks for coding style in that time. I used that for the basis of the https://github.com/asmecher/lucene repository. (We're gradually shifting plugins out of the main repo into their own repos, plus that plugin isn't complete/ready for use yet, so it's better that it lives separately.)

I adapted it for some basic OJS 3.x compatibility (e.g. so that the setup interface works). Otherwise it's still the OJS 2.x code and will need some basic review before it'll work in OJS 3.x. I didn't add/remove any functionality.

You could include dependent files if you wish, but when showing a result, you should present the galley the dependent file belongs to rather than just the file itself. That way e.g. if you have an image with embedded metadata that gets indexed by the search engine, and the file matches a search, then you can present it in the context of the HTML article it appears within.

Tagging @lilients, as I believe she's interested in working on this plugin too.

**Comment by asmecher** [comment] 2019-03-18 15:35
(See also https://github.com/pkp/pkp-lib/issues/2575)

**Comment by ajnyga** [comment] 2019-03-19 09:23
(so great you are working on this! I have it on my todo list, but have not been able to find the time for it.)

**Comment by Stefanvdb** [comment] 2019-03-21 15:45
@asmecher 
I am now working on displaying the facet block, and getting to know the OJS code. And I have the following problem that I hope you might give me a hint for. 
In the OJS2 version of the plugin, in file facetBlock.tpl a extrasOnDemand template is loaded: 

`{include file="controllers/extrasOnDemand.tpl" id=$facetCategory|concat:"Category"
					moreDetailsText="plugins.generic.lucene.faceting."|concat:$facetCategory
					lessDetailsText="plugins.generic.lucene.faceting."|concat:$facetCategory
					extraContent=$categoryFacetsMarkup}`

This is not possible in OJS3 anymore, cause it leads to a javascript error $ is not defined, because jQuery is now added in the footer instead of in the header. 
This is caused by this code snippet in that template file: 
`<script>
	// Initialise JS handler.
	$(function() {ldelim}
		$('#{$id}').pkpHandler(
			'$.pkp.controllers.ExtrasOnDemandHandler');
	{rdelim});
</script>`

Could you point me to any documentation or example how I can load this or other smarty templates that start with adding a PKPHandler to a frontend template?

**Comment by asmecher** [comment] 2019-03-21 16:17
@Stefanvdb, at a glance, the issue is that we no longer load our Javascript controllers (or even JQuery, IIRC) in the application front-end, only in the back end. Rather than using ExtrasOnDemandHandler, I would suggest avoiding our Javascript controller infrastructure in general, because we're gradually deprecating it in favour of other tools (including e.g. vue.js templates in the back end). The faceting block shouldn't be doing anything complex using Javascript.

**Comment by Stefanvdb** [comment] 2019-04-10 08:54
@asmecher
In the section form, there is a setting "Will not be included in the indexing of the journal".
It's not clear to me yet, what this means, and more important, if it affects the search-indexing of articles in this section? Should they be excluded from search results?

**Comment by ajnyga** [comment] 2019-04-10 09:00
Just a general notice that I know another OJS3 users who is porting/has ported Lucene for OJS3. I have asked them to come comment here (since I do not know the details), but it seems that they have not done so at least yet. I will probably hear about their work on Friday when I attend a video meeting.

**Comment by asmecher** [comment] 2019-04-10 15:01
@Stefanvdb, that setting is used to identify the section as something like "Editorials" or "Notes from the Publisher", i.e. content that's published with the issue but not, strictly speaking, part of the peer-reviewed science. I don't think it has any impact on search indexing.

**Comment by Stefanvdb** [comment] 2019-05-02 14:05
@asmecher 
I want to have a look at automatic testing for the lucene plugin. Could you point me to current documentation about automated testing in OJS 3 if this exists? As I understand so far, there is a mix of PHPUnit tests and selenium tests (triggered by PHPUnit)?

**Comment by asmecher** [comment] 2019-05-02 19:29
@Stefanvdb, this is a work in progress and a little cantankerous to set up, but have a look e.g. at the static pages plugin: https://github.com/pkp/staticPages

It includes a `.travis.yml` script that tells the Travis service how to run the scripts. As you'll see, it borrows some of OJS's scripting environment to get it installed and set up, then kicks off its own tests.

**Comment by Stefanvdb** [comment] 2019-05-24 13:00
@asmecher 
I am currently testing the lucene plugin, and now run into the question: With which release/branch should it be compatible? I tried running it against ojs master, but it breaks for example because the function  PublishedArticleDAO::getByArticleId() doesn't exist anymore in master - haven't tested yet if more problems occur when using ojs master.
So far I've developed and testet it against the (upcoming) 3.1.2-1 release. 
How is version compatibility handled for plugins? And where will the plugin live when it's ready? I understand that it won't be part of the ojs project anymore?

**Comment by asmecher** [comment] 2019-05-24 15:31
@Stefanvdb, the Lucene plugin currently needs rewriting and will not work until that happens. We're gradually moving plugins out of the main OJS repository into their own repositories, and Lucene has already been moved out; for now the not-yet-rewritten plugin has been moved to https://github.com/asmecher/lucene.

**Comment by Stefanvdb** [comment] 2019-05-28 09:01
Hi @asmecher 
I know, what I meant is that i am testing my rewrite of the Lucene Plugin. After this testing phase, i hope to be able to release it soon - and there I am not sure which branch of OJS it shoud be compatible with. Many of the changes that were needed in OJS have been cherry-picked for the OJS 3.1.2-1. 
Does my question above make more sense now?

**Comment by asmecher** [comment] 2019-05-28 19:24
@Stefanvdb, sorry, I misunderstood your question. It's clear now.

I'd suggest coding against `ojs-stable-3_1_2`, e.g. the 3.1.2-0/3.1.2-1 releases. These will be maintained stable for a while. The `master` branch will be released eventually as OJS 3.2, but it's currently undergoing heavy work e.g. due to the recently-merged support for metadata versioning.

It is possible to code in a way that's compatible with both, but it'll require some conditional statements, e.g.:
```
if (method_exists($publishedArticleDao, 'getByArticleId')) {
    ...
} else {
    ...
}
```
Generally we save breaking changes like this for big releases, e.g. 3.3 vs. 3.2 vs. 3.1, and try to maintain close compatibility across minor releases, e.g. 3.1.1, 3.1.2, 3.1.3, etc. (The 3.1.2 release did include a few breaking changes, but it was unusual.)

Regards,
Alec Smecher
Public Knowledge Project Team

**Comment by Stefanvdb** [comment] 2019-11-20 16:45
Hello @asmecher,
we are currently finishing testing on the lucene plugin for OJS3 and Solr 8. 
Currently, if we first install a site and afterwards add the lucene plugin by cloning the dev-branch of my repository, I have the problem that the plugin settings are not read from the settings.xml. I have implemented getInstallSitePluginSettingsFile, but as I understand it, it will only be called on installation of the site. At which time, the Lucene Plugin was not available yet. 
Is there a way to read the settings.xml file at the moment the plugin is installed?

After we finished testing, in which Repository should the plugin code live?

Greetings,

Stefan

**Comment by asmecher** [comment] 2019-11-28 20:27
@Stefanvdb, that's excellent news (and I already passed it along to someone at our conference last week)!

The `settings.xml` file will be installed when the plugin is either uploaded to the plugin installer in OJS, or when the Plugin Gallery is used to install it. So don't worry that you haven't seen that behaviour on your dev install.

The plugin code should live in its own repository, much like e.g. the [Custom Header plugin](https://travis-ci.org/asmecher/customHeader) does (and numerous others). Then we can work on getting it added to the Plugin Gallery so it's easy for others to find and install.

Please let me know if I can help e.g. with testing and code review!

**Comment by Stefanvdb** [comment] 2020-01-29 10:12
Hello @asmecher,
the plugin can now be found here: 
https://github.com/ojsde/lucene

If you'd like to test it, that would be great. 

Stefan

**Comment by asmecher** [comment] 2020-01-30 23:29
Brilliant, @Stefanvdb! I've added a small pull request to manage my own obsessions (https://github.com/ojsde/lucene/pull/2) -- before I dig into this further, how much have you tested it yourselves? Is all the far-flung functionality working, or just the main functionality? Are things like unit tests also adapted/working?

**Comment by Stefanvdb** [comment] 2020-01-31 08:37
@asmecher, all/most functionality has been tested, but as far as I know not so much on a windows server environment. But unit tests have not been adapted.

**Comment by asmecher** [comment] 2020-01-31 20:12
Great, @Stefanvdb! I have it installed and working here. I've sent another small PR (https://github.com/ojsde/lucene/pull/3) adjusting a few small details.

Once we're both satisfied that tweaks on the current `master` branch are OK for compatibility with OJS 3.1.2, I suggest creating a `stable-3_1_2` branch, then working on the `master` branch towards OJS 3.2 compatibility. I can help with that.

**Comment by asmecher** [comment] 2020-01-31 23:48
Thanks for merging, @Stefanvdb. Are you still working on the plugin or shall we package up a release for 3.1.2 and move on to master branch support?

**Comment by Stefanvdb** [comment] 2020-02-01 16:47
I've finished working on the plugin, so yeah, you could do that, @asmecher

**Comment by asmecher** [comment] 2020-02-07 23:41
Thanks, @Stefanvdb -- how do you feel about granting me privileges to work with that repository directly? I can build a release package and set up the branches and tags for consistency with the rest of our codebase.

**Comment by NateWr** [comment] 2021-11-18 09:58
Closing this as a plugin for this has been released at https://github.com/ojsde/lucene. If more work remains to be done, please file a new issue.

**Closed by NateWr** 2021-11-18 09:58 UTC
