### ISSUE TITLE
importexport fails filling the locale column in submissions table. Users can't edit metadata in submissions.

### ISSUE THREAD

**Issue by marcoblancas** [pkp/pkp-lib#7636] opened 2022-01-19 18:17 UTC
**Describe the bug**
Users can't edit metadata in issues previously imported with importexport tool. They get this error:

![imagen](https://user-images.githubusercontent.com/5545390/150188057-1fa80323-c5cc-46b6-aac9-6db8ee65a9a3.png)

but no field missing is marked as required. Even if user fill all the fields the error persist and user can't save the updated issue.

**To Reproduce**
1. Create a new issue in a journal.
2. Create two issues (I used quicksubmit).
3. Look at the submission table and confirm the locale is filled in your submissions.
4. export the full issue with importexport tool.
5. Look at the xml. I can see a locale set on the the issues in issue > articles > article > publication (<publication xmlns="http://pkp.sfu.ca" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" locale="es_ES" version="1" status="5" primary_contact_id="1566" url_path="" seq="0" section_ref="EST" access_status="0" xsi:schemaLocation="http://pkp.sfu.ca native.xsd">
6. In the same journal impor the xml with the importexport tool
7. Look at the submissions table to confirm the locale column is null in the imported issues.
8. Try to edit the title in the imported submissions and you got the error.

**What application are you using?**
 OJS 3.3.0.8

**Related forums about this problem:
https://forum.pkp.sfu.ca/t/error-when-editing-metadata-on-imported-number/71478/
https://forum.pkp.sfu.ca/t/doesnt-save-changes-articles/70804/

**Comment by NateWr** [comment] 2022-01-20 11:04
Hi @marcoblancas, I suspect this is happening because the submissions have metadata in a language that is not enabled for submissions. This is the most common cause of seeing a form error but where the error message doesn't appear in any field.

Can you check your database and see if this is the case?

**Comment by marcoblancas** [comment] 2022-01-20 12:07
@NateWr , thank you for your answer. I think that's not the problem. In my tests environment I have Spanish as primary locale and English is enabled for other uses (included submissions). This is my screenshot.

![imagen](https://user-images.githubusercontent.com/5545390/150334222-675be9a4-cf9e-48cd-9c0d-026555f31fa0.png)

The tests were done in the same instance and in the same journal so the settings in the source (export) and destinations (import) are the same.

Now I'm not sure but I believe I tested it with just English as the only language available in the journal and the same happened.

I tried to review the code but I'm not php expert and there is a lot of code in this module for me.

The workaround for us, at the moment, is to update the locale in the submissions table every time editors run a massive import in the journal we are migrating.

Thank you.

**Comment by NateWr** [comment] 2022-01-24 15:04
I tried following your reproduction steps in the `stable-3_3_0` branch but I did not encounter any errors. It may be that there is a particular piece of metadata, language configuration, or other configuration that is causing the issue. 

Can you try to reproduce the problem using the [test drive demo](https://pkp.sfu.ca/ojs/ojs_demo/) of OJS? If you can reproduce it, try to note down precisely what submission metadata you entered, what the language configuration is before export/import, and any other changes you make to the settings.

**Comment by NateWr** [comment] 2022-01-25 10:15
Thanks @jonasraoni. If it's ok, I've assigned this to you. Maybe see if you can reproduce this and then check if the bug fix addresses it. If it turns out to be different, I can unassign you and we can work again on reproducing it.

**Comment by marcoblancas** [comment] 2022-01-25 16:18
Hi @NateWr,

> Can you try to reproduce the problem using the [test drive demo](https://pkp.sfu.ca/ojs/ojs_demo/) of OJS? If you can reproduce it, try to note down precisely what submission metadata you entered, what the language configuration is before export/import, and any other changes you make to the settings.

I've recorded this screencast in the test drive demo site.

https://youtu.be/7xzctoyoy8o 

Does it help?

**Comment by NateWr** [comment] 2022-01-26 10:35
Thanks @marcoblancas! Yes, that's helpful. I will leave it to Jonas for the moment, but if his work doesn't fix the issue then we'll revisit this and your video will help us reproduce the problem.  :+1:

**Comment by jnugent** [comment] 2022-02-24 19:19
@jonasraoni thanks for tagging this other ticket - let me know if you want help with this, I have XML that can reproduce the problem and was able to break it and then fix it manually by editing records in the database.

**Comment by jonasraoni** [comment] 2022-02-24 19:27
My [old PR](https://github.com/pkp/pkp-lib/pull/7201/files), addresses this issue, it was missing a review, but after so much time, I'll probably have to rebase it and add some extra fixes :)

**Comment by jonasraoni** [comment] 2022-05-24 09:03
Just confirming this issue will be addressed by the https://github.com/pkp/pkp-lib/issues/7190, so I'm closing this one as a duplicate.

**Closed by jonasraoni** 2022-05-24 09:03 UTC
Labels: Bug:1:Low
