### ISSUE TITLE
Empty notification pop-up

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#7669] opened 2022-02-02 12:39 UTC
**Describe the bug**
Since I've migrated to 3.x (I'm now at 3.3.0-8) I've seem those empty notifications popup in the dashboard. Several other users complained about the same problem. I've tried to track it down but I don't know where else to look.

![image](https://user-images.githubusercontent.com/18707781/152154676-756bf992-e501-4629-afd0-495a90ca8286.png)

The source code for the notification doesn't offer any help, neither does the error logs:

```
<span>
<div class="pkpNotification pkpNotification--notice pkpNotification--canDismiss app__notification-enter-to">
	<button class="pkpNotification__closeButton"><span aria-hidden="true">×</span><span class="-screenReader">Fechar</span></button></div>
<div class="pkpNotification pkpNotification--notice pkpNotification--canDismiss app__notification-enter-to">
	<button class="pkpNotification__closeButton"><span aria-hidden="true">×</span><span class="-screenReader">Fechar</span></button></div>
</span>
```

Any ideas on how to track this down and solve this issue?

**What application are you using?**
 OJS 3.3.0.8

**Comment by NateWr** [comment] 2022-02-03 10:49
It looks to me like text is coming back as an empty string. Is it possible that you have some translation entries that are empty?

If a locale key, like `notification.some.message`, is missing from a locale file (eg - `locale/pt_BR/manager.po`), it will output the key like this:

```
##notification.some.message##
```

If the locale key exists, but the `msgstr` is empty, it will return an empty string:

```po
# Example of a locale key that exists but has an empty translation
msgid "notification.some.message"
msgstr ""
```

The `msgstr` can be multi-line, so the following shouldn't cause any problems:

```po
msgid "notification.some.message"
msgstr ""
"My message here"
```

But if you see anything like this, it could lead to the problem in your screenshot:

```po
msgid "notification.some.message"
msgstr ""

msgid "a.new.locale.key.started"
msgstr "My message here"
```

**Comment by luizbgomide** [comment] 2022-02-03 12:15
I never messed with those files, so they are as they came. Just checked the `manager.po` and the only "pseudo-empty" are the multi-line strings. I have the "Default Translation Plugin" enabled, not sure if that could be affecting it somehow. I will try to keep my interface in english and disable the mentioned plugin, maybe I can see something in English that helps shed a light.

Any more ideas or places to look?

**Comment by luizbgomide** [comment] 2022-02-04 12:39
@NateWr I left my interface on English and got the same problem today:
![image](https://user-images.githubusercontent.com/18707781/152530553-83b519c0-a25e-4f9a-a6c2-fd1cd9033958.png)

So the issue probably isn't some translation string missing, is something else.

**Comment by NateWr** [comment] 2022-02-07 11:08
No idea. Have you tried reproducing it in the 3.3 test drive install? https://pkp.sfu.ca/ojs/ojs_demo/

I'll close this for now since we don't have any reproduction steps. But if you can reproduce it in the 3.3 test drive install and provide some reproduction steps I'll reopen it. Otherwise, I'd suggest trying out the support forum since it seems to be a local issue. Maybe someone else has run into this there... https://forum.pkp.sfu.ca/

**Closed by NateWr** 2022-02-07 11:08 UTC

**Comment by luizbgomide** [comment] 2022-02-07 12:06
@NateWr I disagree that this is a local issue, I know of at least 4 other installations that have this issue (all migrated from 2.x to 3.x) and I already mentioned this issue on the forum years ago and there 2 other people also said they had the same issue: https://forum.pkp.sfu.ca/t/null-notifications-what-are-those-supposed-to-be/64832

It is very hard (or even impossible) to reproduce this is a test install, because a test install wasn't migrated. Just dismissing the issue is ignoring a lot of possible affected users.

Where are those notifications being generated? Can I log what info/db entry they use to generate those? Maybe this way I can track this down. What DB tables are related to this that I can investigate?

**Comment by luizbgomide** [comment] 2022-02-07 12:19
@NateWr as a follow-up, last year on that post I mentioned above, I asked about some notification codes that showed up on my installation that was also showing up on the table of another user, namely notification `type`: `369098754`.

What is that? That wasn't in the list of notification codes that you posted on the forum. This could be very well be the thing that is showing up empty, since they are still being created (me most recent one in my DB is from yesterday and I have 370 of those):
![image](https://user-images.githubusercontent.com/18707781/152786938-7383c233-790c-405f-952b-fe870a55f0f9.png)

**Comment by NateWr** [comment] 2022-02-07 12:24
We're making an effort to keep GitHub issues for confirmed bug reports and clear feature requests. I've been going through our backlog and closing old issues too.

I've posted in the forum thread so we can continue discussing it there. If/when we find a clear source of the problem, I'm happy to get it filed in GitHub.
