### ISSUE TITLE
Add direct "Unsubscribe" link to notification emails

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#5048] opened 2019-09-06 14:24 UTC
**Describe the problem you would like to solve**

Notification emails (eg. new issue published, announcements, author submission notifications, etc.) don't have any direct link to unsubscribe. Users can unsubscribe from these notifications by going to Profile > Notifications, but they don't necessarily know this, and it's prohibitive to have them assume this knowledge. 

**Describe the solution you'd like**

Ideally, users should be able to click a link, and without logging in (but with confirming their email address or using a special URL key or something similar), be able to unsubscribe to all simply by loading the page; or at least, by clicking a clearly labeled "Unsubscribe to all notifications" button. 

Failing that, at the very least there should be a a direct link to the user's Profile > Navigation page, labeled "Manage Email Subscriptions". 

**Who is asking for this feature?**

Folks who are concerned about Canada's Anti-Spam Legislation ([CASL](https://laws-lois.justice.gc.ca/eng/acts/E-1.6/page-3.html#docCont)).

**Additional information**

* [Legislation Requirements](https://laws-lois.justice.gc.ca/eng/acts/E-1.6/page-3.html#docCont)
* [Relevant forum thread](https://forum.pkp.sfu.ca/t/ojs-3-x-automatically-emailing-all-members/)

**Comment by NateWr** [comment] 2019-09-23 10:27
@asmecher how do you feel about adding this to 3.2? I think it was bumped from earlier GDPR work that went into 3.1.x.

In terms of which emails this should support: an unsubscribe email should appear in every email listed under Profile > Notifications.

**Comment by defstat** [comment] 2019-09-24 21:31
Hi all.

I have prepared this PR:
[pkp-lib]: pkp/pkp-lib#5091

I am not sure of the approach, so I have not yet added the OJS and OMP commits. 

I started by trying to implement something like that: "https://laravel-news.com/signed-routes", by introducing a new "SignedRouter" router at OJS. It turned out that it became too complicated, too close to the core functionality, so I decided to take the encoding/decoding staff out of the SignedRouter and put it in the NotificationManager.

In sort, the implementation handles the emails produced from `notifications`. A url can be created for every notification, which follows the pattern "Notification/unsubscribe?validate={token}&id={notificationId}". The {token} is produced by using a new configuration secret key (added at the config file) and encoding a string with the following pattern `unsubscribe-{contextId}-{userId}-{notificationId}`. 

That URL is attached on the bottom of the body of the email that is send, and if the receiver of the email hits it, the `{notificationId}` is being used to get the requested notification, and the `{token}` is used to validate it. After the validation, the user is unsubscribed from all email notifications.

**Comment by NateWr** [comment] 2019-09-25 11:28
I just left a comment on the PR. Looking good. Having read this now, I think the URL can be just:

```
/notification/unsubscribe?token={token}
```

The notification ID should be embedded in the token already, right?

**Comment by defstat** [comment] 2019-09-25 14:56
@NateWr it is embedded in the token. I am using the id to get the notification, and then use the token to check if the id corresponds to the correct token. But yes, the `{token}` part is sufficient to get the notification (and the user)

**Comment by defstat** [comment] 2019-09-25 16:48
@NateWr I added the review changes on the PR with some additional changes

**Comment by defstat** [comment] 2019-09-25 18:30
PRs
[OJS]: pkp/ojs#2475
[pkp-lib]: pkp/pkp-lib#5091

**Comment by NateWr** [comment] 2019-09-30 16:50
This looks good, @defstat, but you still need to implement email-by-email opt-outs, and the email confirmation field as mentioned here: https://github.com/pkp/pkp-lib/pull/5091#pullrequestreview-293000299.

So that means after following the unsubscribe link, they should have to confirm the email address they want to be unsubscribed. They should also have a list of emails (like in the profile form) they can opt out of, with options for each one:

- [x] Unsubscribe from emails about new announcements.
- [x] Unsubscribe from emails about new submissions.
- [x] ....

These should be checked by default and the user can un-check any that they want to remain subscribed to.

**Comment by defstat** [comment] 2019-09-30 16:59
@NateWr It's implemented like that (unsubscribing to all notifications), because of the initial requirement. (https://github.com/pkp/pkp-lib/issues/5048#issue-490356570). Should I change that?

**Comment by NateWr** [comment] 2019-10-01 08:57
Yeah, please add the email confirmation and the option to de-select notifications to unsubscribe to.

**Comment by defstat** [comment] 2019-10-21 14:39
@NateWr I have added a new page that allows the user to unsubscribe individually from each email notification

**Comment by NateWr** [comment] 2019-10-22 15:52
@defstat Can you give me some steps to reproduce this. I see I need a validation token to view the unsubscribe forms, and that this is generated relative to a notification. Just some steps I can take to generate a notification, find the token, and visit the unsubscribe to see the process.

**Comment by defstat** [comment] 2019-10-23 14:46
@NateWr I am using the `create new submission` flow to test that. If you mean how I am getting the email, I have installed `https://archive.codeplex.com/?p=smtp4dev` tool on my dev machine, and I configured ojs to send the emails there.

**Comment by NateWr** [comment] 2019-10-24 10:08
When I create a new submission, the submission acknowledgement email doesn't contain an unsubscribe link. I don't think it should... Is there another way to trigger a notification that generates the unsubscribe link for me?

**Comment by NateWr** [comment] 2019-10-31 18:14
Thanks @defstat! I was able to get it working. I've opened a PR that you should be able to merge onto your branch with some minor adjustments to the text and layout of the unsubscribe form and results:

https://github.com/defstat/pkp-lib/pull/3

When I first tried, I got a bad unsubscribe link because I hadn't yet set a `signed_page_key_secret` in my config file. I think we need to handle this error better. Can we exclude the unsubscribe link when no `signed_page_key_secret` is set? Alternatively, we could still reuse the `api_key_secret`. Both of these are, in effect, a general secret key that could be reused for different purposes. 

Some screenshots of the changes I made. Please test them out in case I missed something.

![Selection_154](https://user-images.githubusercontent.com/2306629/67974345-3294dd00-fc0a-11e9-91f6-e6c0a0af42a8.png)
![Selection_153](https://user-images.githubusercontent.com/2306629/67974344-3294dd00-fc0a-11e9-8990-6fc7ac34478c.png)
![Selection_155](https://user-images.githubusercontent.com/2306629/67974348-332d7380-fc0a-11e9-88a7-53de7b3bba18.png)

**Comment by defstat** [comment] 2021-02-19 11:13
@asmecher 

**PRs**
pkp-lib: #5091
ojs: pkp/ojs#3046

**Comment by asmecher** [comment] 2021-02-19 23:06
Thanks, @defstat, just a couple of comments. Also, don't hesitate to use the modern array syntax `[]` for new code.

**Comment by asmecher** [comment] 2021-02-26 18:17
Thanks, @defstat, just a few additional comments -- I don't think this will need another round of review, so please go ahead when you're ready.

**Comment by defstat** [comment] 2021-03-03 08:16
Thanks @asmecher! I think I have resolved the review comments

**Comment by asmecher** [comment] 2021-03-03 22:17
OK, please go ahead and merge!

**Comment by defstat** [comment] 2021-03-04 09:04
@asmecher rebased and merged

**Comment by asmecher** [comment] 2021-03-04 18:15
Excellent, thanks!

**Comment by defstat** [comment] 2021-03-05 14:21
@asmecher 

Reopening because of https://github.com/pkp/ojs/commit/60c3a9358715454e24f96c9f44a120892ef244f6#r47886665

@Vitaliy-1 could you check if the following solves the issue?

**PRs**
ojs: pkp/ojs#3066
omp: pkp/omp#940
ops: pkp/ops#129

**Comment by Vitaliy-1** [comment] 2021-03-05 14:50
Yes, solves!

**Comment by asmecher** [comment] 2021-03-05 18:33
@defstat, this also breaks the unit tests (see e.g. https://travis-ci.com/github/pkp/ojs/jobs/488511616):
```
There were 2 errors:

1) PKPNotificationManagerTest::testCreateNotificationEmailed with data set #0 (Notification Object (...))
Error: Call to a member function url() on null

/home/travis/build/pkp/ojs/lib/pkp/classes/notification/PKPNotificationOperationManager.inc.php:474
/home/travis/build/pkp/ojs/lib/pkp/classes/notification/PKPNotificationOperationManager.inc.php:388
/home/travis/build/pkp/ojs/lib/pkp/classes/notification/PKPNotificationOperationManager.inc.php:154
/home/travis/build/pkp/ojs/lib/pkp/tests/classes/notification/PKPNotificationManagerTest.php:193
/home/travis/build/pkp/ojs/lib/pkp/tests/classes/notification/PKPNotificationManagerTest.php:95

2) PKPNotificationManagerTest::testCreateNotificationEmailed with data set #1 (Notification Object (...), array('param1Value'))
Error: Call to a member function url() on null

/home/travis/build/pkp/ojs/lib/pkp/classes/notification/PKPNotificationOperationManager.inc.php:474
/home/travis/build/pkp/ojs/lib/pkp/classes/notification/PKPNotificationOperationManager.inc.php:388
/home/travis/build/pkp/ojs/lib/pkp/classes/notification/PKPNotificationOperationManager.inc.php:154
/home/travis/build/pkp/ojs/lib/pkp/tests/classes/notification/PKPNotificationManagerTest.php:193
/home/travis/build/pkp/ojs/lib/pkp/tests/classes/notification/PKPNotificationManagerTest.php:95
```

Could you have a look at that?

**Comment by defstat** [comment] 2021-03-10 12:26
@asmecher 

**PRs**
pkp-lib: #6845

also from previous comment 
**PRs**
ojs: pkp/ojs#3066
omp: pkp/omp#940 -> Added missing api_key in config.template
ops: pkp/ops#129

**Comment by asmecher** [comment] 2021-03-10 19:40
@defstat, could you file and fix the missing API key thing in a separate issue and target `stable-3_3_0`? Otherwise please go ahead and merge and close this issue, thanks!

**Comment by defstat** [comment] 2021-03-12 07:12
@asmecher I removed the api_key parameter from the config and added [this](https://github.com/pkp/pkp-lib/issues/6858) for the api key update.

**Comment by asmecher** [comment] 2021-03-12 18:43
Thanks -- all merged!

**Comment by asmecher** [comment] 2021-12-03 12:20
@defstat, I just noticed that this is using the old "`<data>` toolset in `dbscripts/xml/upgrade.xml` instead of a migration; can you convert the upgrade step to the new migration toolset? Thanks!

**Comment by defstat** [comment] 2022-02-14 16:26
@asmecher 

Do I just run upgrade for testing that, or should I do something else to invoke the migrations?

**PRs**
pkp-lib: #7700
OJS: pkp/ojs#3299
OMP: pkp/omp#1065
OPS: pkp/ops#233

**Comment by NateWr** [comment] 2022-02-14 16:42
cc @Vitaliy-1 we'll need to test this with the new email stuff.

**Comment by asmecher** [comment] 2022-02-14 19:53
> Do I just run upgrade for testing that, or should I do something else to invoke the migrations?

The upgrade tests passed on OMP and OPS; they were skipped on OJS because one of the earlier test stages failed, but I've queued them so they should run too. You can see that the migration ran OK in the upgrade test output, e.g. from https://app.travis-ci.com/github/pkp/omp/jobs/559618036:
<pre>
$ php tools/upgrade.php upgrade
2022-02-14 19:16:47 [pre-install]
2022-02-14 19:16:47 [load: upgrade.xml]
2022-02-14 19:16:47 [version: 3.4.0.0]
2022-02-14 19:16:47 [code: Installer Installer::checkPhpVersion]
2022-02-14 19:16:47 [code: Installer Installer::installDefaultNavigationMenus]
2022-02-14 19:16:47 [code: Installer Installer::migrateStaticPagesToNavigationMenuItems]
2022-02-14 19:16:47 [data: dbscripts/xml/upgrade/3.2.1_update.xml]
2022-02-14 19:16:47 [code: Installer Installer::installEmailTemplate]
2022-02-14 19:16:47 [migration: PKP\migration\upgrade\PKPv3_2_1SubeditorCategoriesMigration]
2022-02-14 19:16:47 [note: docs/release-notes/README-3.2.1]
2022-02-14 19:16:47 [migration: APP\migration\upgrade\OMPv3_3_0UpgradeMigration]
2022-02-14 19:16:49 [note: docs/release-notes/README-3.3.0]
2022-02-14 19:16:49 [migration: APP\migration\upgrade\v3_4_0\PreflightCheckMigration]
2022-02-14 19:16:49 [migration: APP\migration\upgrade\v3_4_0\I6093_AddForeignKeys]
2022-02-14 19:16:49 [migration: PKP\migration\install\FailedJobsMigration]
2022-02-14 19:16:49 [migration: PKP\migration\upgrade\v3_4_0\UpgradeMigration]
2022-02-14 19:16:49 [migration: PKP\migration\upgrade\v3_4_0\I4904_UsageStatsTemporaryRecords]
2022-02-14 19:16:49 [migration: APP\migration\upgrade\v3_4_0\I6807_SetLastModified]
2022-02-14 19:16:49 [migration: APP\migration\upgrade\v3_4_0\I7132_AddSourceChapterId]
2022-02-14 19:16:49 [migration: PKP\migration\upgrade\v3_4_0\I7167_RemoveDuplicatedUserSettingsAndDeprecatedFields]
2022-02-14 19:16:50 [migration: APP\migration\upgrade\v3_4_0\I7264_UpdateEmailTemplates]
<strong>2022-02-14 19:16:50 [migration: PKP\migration\upgrade\v3_4_0\I5048_AddUnsubscribeLinkToEmailTemplate]</strong>
2022-02-14 19:16:50 [note: docs/release-notes/README-3.4.0]
2022-02-14 19:16:50 [code: Installer Installer::addPluginVersions]
2022-02-14 19:16:50 [post-install]

Release Notes
----------------------------------------
(etc)
</pre>

**Comment by defstat** [comment] 2022-08-29 05:22
There is [this](https://github.com/pkp/pkp-lib/issues/8127) related issue. Will revisit it after it's finished. (@asmecher @NateWr @Vitaliy-1)

**Comment by NateWr** [comment] 2022-12-14 10:43
@Vitaliy-1 is this issue complete now that #7874 is merged?

**Comment by Vitaliy-1** [comment] 2022-12-14 16:07
Yes

**Closed by Vitaliy-1** 2022-12-14 16:07 UTC
Labels: Enhancement:2:Moderate
