### ISSUE TITLE
PublicationFormat::getReadableDates() not returning readable dates

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#846] opened 2015-10-28 16:44 UTC
I haven't had much time to look into this, but as far as I can tell the `getReadableDates` method does not return a valid date.

The relevant code in the template files is [here](https://github.com/pkp/omp/blob/master/templates/frontend/objects/monograph_full.tpl#L243-L268) and can be viewed on most book pages in the Smithsonian test data. Example:

![bad-date](https://cloud.githubusercontent.com/assets/2306629/10795735/15019a34-7d93-11e5-836b-647a3d81f7aa.png)

**Comment by asmecher** [comment] 2015-10-28 17:04
Fixed by https://github.com/pkp/pkp-lib/commit/df7dd55dad8e310c4b777458ec5995cb348b65fe; caused by unintended consequences of http://pkp.sfu.ca/bugzilla/show_bug.cgi?id=8634

**Closed by asmecher** 2015-10-28 17:04 UTC
Labels: Open Monograph Press
