### ISSUE TITLE
SPF fixes should be reverted and altered

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#1433] opened 2016-05-09 18:39 UTC
The current SPF fixes introduced in OJS 2.4.6 and subsequently ported to other branches have resulted in a few problems with email.  Current mailings appear to be from the principal contact from the journal, which makes it difficult to filter in email MUAs, as well as the email logs built into each PKP application.  The bigger problem is that the changes do not really affect SPF.  SPF tests performed by MTAs examine the Return-Path header, not From or Reply-To.  

The pull requests in this Issue revert the old changes and add a Return-Path header if the configuration options are set.

See: https://github.com/pkp/ojs/pull/832 for commits that address this.

**Comment by asmecher** [comment] 2016-05-09 23:56
@ctgraham, I think you were following this thread pretty closely; do you think you'll have a chance to review Jason's proposals to see if they match up against your expectations and setup?

**Comment by ctgraham** [comment] 2016-05-10 14:17
I am cloning our Scholarly Exchange service to a development server today.  If the update passes testing there, I will apply it to the live instance for further testing.

**Comment by asmecher** [comment] 2016-05-10 15:03
Many thanks as always, @ctgraham!

**Comment by ctgraham** [comment] 2016-05-10 15:23
@jnugent, shouldn't there always be a return-path set with the new scheme?

I have `default_envelope_sender` set in config.inc.php.

When I checkout your branches, login as Admin, navigate to a journal, select Prepared Emails, then select and send a template.  If `force_default_envelope_sender` is set, I get a return-path of the `default_envelope_sender`.  If `force_default_envelope_sender` is not set, I get no return-path header.  I expected one (perhaps mistakenly?)

**Comment by jnugent** [comment] 2016-05-10 15:34
We only want to set one if force is on.  The last thing I want to do is force changes on a systems admin who has already made tweaks at the MTA level within the OS.

**Comment by vnen** [comment] 2016-05-18 18:33
I'm having problem with some emails that are not being sent and I believe it's because of this. Only some specific OJS functions are not sending it though (namely the submission ack), while others send the email with no problem (such as the rejection email).

I can see an error in the PHP error log: `OJS SMTPMailer: Did not receive expected 250 or 251`

But I'm not aware how to debug this further (like how to see the payload is sent to the SMTP server). If someone can point me how to do this I might be able to give some better info.

**Comment by ctgraham** [comment] 2016-05-18 18:41
@vnen, check out this post on the support forum: http://forum.pkp.sfu.ca/t/upgraded-to-2-4-6-and-submission-acknowledgement-email-is-not-sent-anymore/798/46?u=ctgraham

I suspect what you are seeing is a rejected message due to a null reply-to.

You are also welcome to test out this fuller SPF fix, if you are comfortable with git and with testing bleeding edge code.

**Comment by vnen** [comment] 2016-05-20 19:51
It seems that the problem is indeed an empty *reply-to* header: `Reply-To: "" <>`. That's what I'm getting in my local dev environment.

pkp/ojs#832 solves it with a caveat: it sends an empty *From* header (`Form: "" <>`) unless I activate `force_default_envelope_sender`. Just as a note, I tested the patch on top of 2.4.8.0 release, not an any dev branch.

**Comment by vnen** [comment] 2016-05-20 20:51
No help on the live server though, still getting the cryptic message: `OJS SMTPMailer: Did not receive expected 250 or 251`.

**Comment by ctgraham** [comment] 2016-05-23 12:28
@ven, do you get this message after applying the changes from https://github.com/pkp/pkp-lib/pull/1182, https://github.com/pkp/ojs/pull/832, and https://github.com/pkp/pkp-lib/issues/1433?

**Comment by vnen** [comment] 2016-05-23 14:11
@ctgraham well, #1433 is this issue itself. I applied #1182 too, but it gave me error in `array_key_exists` receiving wrong arguments besides the same error about SMTP.

**Comment by ctgraham** [comment] 2016-05-23 18:25
@ven, sorry, that third link should have been this pull: https://github.com/pkp/ojs/pull/337

**Comment by dtwardy** [comment] 2016-05-26 16:02
Hi!

One of our clients stumbled upon a similar issue regarding specific servers (namely freenet.de) rejecting mails sent via OJS. Due to the fact that "ReplyTo:" is at times set to "null" some mails are being rejected. After inspecting the code I've encountered an error in function "setReplyTo" in "Mail.inc.php": there's a "return" missing after that if-clause. 

When testing with a permanent address being inserted when "$email" is set to "null" the messages sent to freenet.de-addresses are being delivered. So I guess by default "ReplyTo:" should always be set to the principal contact's address by default if not specified else.

That should solve the bug.

**Comment by jnugent** [comment] 2016-05-26 16:10
Hi @dtwardy 

Thanks for the note.  We've actually committed fixes to the OJS and PKP-lib code bases that address the null replyTo address.  They aren't part of the this issue and mentioned pull requests, but they are there.  This issue is meant to address the fact that the SPF fixes currently in place alter the From: header for all mail and make them all appear as though they are coming from the journal principal contact.

**Comment by vnen** [comment] 2016-05-26 16:30
Well, I forgot to reply to this, sorry.

@ctgraham I applied those patches and it seems to be working fine now. Though I also moved to Gmail as SMTP server. It seems to reject the bulk mail sent when trying to notify readers that a new issue was published, but that's another problem. The submission acknowledgement is being sent fine now.

**Comment by dtwardy** [comment] 2016-05-26 17:47
Sorry, my bad. Looking for those patches then.

**Comment by asmecher** [comment] 2016-06-22 04:19
(To be done before closing: https://github.com/pkp/ojs/pull/832#issuecomment-227639086)

**Comment by asmecher** [comment] 2016-06-30 23:57
@jnugent, I think that covers it! I've merged the 3 master branch PRs -- anything left?

**Closed** 2016-07-04 22:00 UTC
Labels: Open Journal Systems, Open Monograph Press

**Comment by vnen** [comment] 2016-07-04 23:25
Cool :smile: Any expected date for the 2.4.8.1 release?

**Comment by asmecher** [comment] 2016-07-04 23:43
@vnen, I would guess 1-2 weeks.
