### ISSUE TITLE
Plugin upgrade hangs

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3315] opened 2018-01-24 23:45 UTC
When logged in as the Site Admin, and go to Settings > Plugins > Plugin Gallery, hitting the Upgrade button for an out of date plugin brings up the confirmation modal, but hitting OK hangs the system.

I can close the modal to return to the interface.

http://vpstest2.lib.sfu.ca/index.php/njst/management/settings/website

**Comment by NateWr** [comment] 2018-02-07 16:40
I tried with the Hypothes.is plugin but was unable to reproduce the issue. It sounds like it might be a file permissions issue on the server, so you might follow up with James.

If it is a file permissions issue, it would be good to report this back rather than having it stall.

**Comment by asmecher** [comment] 2019-08-29 14:53
Closing unless there's more follow-up!

**Closed by asmecher** 2019-08-29 14:53 UTC
Labels: Enhancement
