### ISSUE TITLE
Workflow participants receive more than one email about the same thing

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#5095] opened 2019-09-25 18:14 UTC
We've had a report from a hosted site asking if it would be possible to disable the "You have a new notification" email that is sent along side the more specific workflow email when e.g. a copyeditor is assigned.  In that case, the copyeditor receives the "Copy Editing Request" email, but also the task notification email.  They would like to be able to disable the second email.  We can currently do this by disabling the notification email template but this disables all notifications.

**Comment by asmecher** [comment] 2019-09-25 19:23
@jnugent, what version of OJS is experiencing this?

**Comment by jnugent** [comment] 2019-09-25 19:24
Whoops, this is 3.1.2-1.

**Comment by defstat** [comment] 2020-05-25 14:56
@NateWr @asmecher 

**PRs**
[pkp-lib]: #5911
[OJS]: pkp/ojs#2769

The change suppresses the Notification email if the respective user email succeeds.

After reviewing, I will make the PRs for OMP, OPS and backport to `stable-3.1.2`

**Comment by NateWr** [comment] 2020-05-25 16:22
The code looks good to me, @defstat! 

I looked back at the initial bug report and I'm not sure I understand it. Your code looks like it handles cases where an editor uses the "Notify" button in the participants list. The original report sounds like the problem is when a new participant is assigned to a submission.

I didn't see duplicate emails sent out in _either case_. Your code definitely looks right, but can you help me understand what I'm missing?

**Comment by defstat** [comment] 2020-05-25 16:53
@NateWr check if your database already has a notification attached for the particular reason, for the particular user. If the `Notifications` table is, let's say, empty, and you try to assign a user to a submission's stage, the user is getting 2 emails, one from https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php#L183 and one from https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.inc.php#L190-L203

**Comment by NateWr** [comment] 2020-05-26 10:03
Ah ok! I get it now. It only sends a duplicate email when you select one of those specific email templates. That was my confusion.

Ok, looks good. Just need to get that submodule commit for the tests and we're good to go. :+1:

**Comment by defstat** [comment] 2020-05-26 10:58
@NateWr 

**PRs**

**[master]**
[pkp-lib]: #5911
[OJS]: pkp/ojs#2769
[OMP]: pkp/omp#823
[OPS]: pkp/ops#31

**[3.1.2]**
[pkp-lib]: #5916
[OJS]: pkp/ojs#2772
[OMP]: pkp/omp#824

**Comment by NateWr** [comment] 2020-05-28 13:03
All merged! :sweat_smile:

**Closed by NateWr** 2020-05-28 13:03 UTC
