### ISSUE TITLE
[OJS] Journal content not properly displayed in Google Chrome

### ISSUE THREAD

**Issue by gunthermaier** [pkp/pkp-lib#303] opened 2015-01-28 11:24 UTC
In our journal (http://openjournals.wu.ac.at/ojs/index.php/region/issue/view/1/showToc) the TOC displays correctly in Firefox (35.0.1). In google Chrome the PDF links and page numbers are NOT properly aligned (see screenshot).
![screenshot1](https://cloud.githubusercontent.com/assets/10740435/5936818/8de225ea-a6e8-11e4-8f0a-817dfc61d4c8.jpg)

**Comment by ctgraham** [comment] 2015-01-28 14:14
This link appears as expected to me in Chrome 40 under Windows and Android.  What version and OS are you using?

**Comment by ctgraham** [comment] 2015-03-02 18:55
Cannot reproduce.  Propose closing this issue.

**Closed** 2015-03-24 21:18 UTC
