### ISSUE TITLE
[OJS] Issue data doesn't save

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1539] opened 2016-06-21 10:29 UTC
Issues have settings for Date Published and Open Access Date. When entered, these settings don't appear to be getting saved.

**Comment by NateWr** [comment] 2016-06-21 10:40
I believe this is related to running a multi-lingual journal. The checkboxes under Issue > Cover also don't save.

When trying to save any of the data that doesn't save, I get a long stream of these errors, which I believe are related to expectations of multi-lingual settings:

```
[Tue Jun 21 11:38:11.043836 2016] [:error] [pid 9380] [client 192.168.0.8:45194] PHP Warning:  Cannot use a scalar value as an array in /var/www/html/ojs/lib/pkp/classes/core/DataObject.inc.php on line 133, referer: http://192.168.0.8/ojs/index.php/publicknowledge/manageIssues
```

**Comment by bozana** [comment] 2016-06-23 09:51
I've just checked one thing: the setting "showCoverPage" is not localized in the web form, but in the Issue and IssueDAO class.

**Comment by NateWr** [comment] 2016-06-23 12:07
@bozana on an unrelated call with Alec yesterday he mentioned that this was maybe part of an old, overly-complex set of locale-specific display options that were likely to get cleared out for OJS 3.

I may have misinterpreted that, but I think I'd go to Alec first before looking into this further, as he may have a clear idea of what to do with it.

**Comment by bozana** [comment] 2016-06-23 12:10
Yes, OK, I just wanted to note why is it happening -- because I saw it looking at another problem I had -- but will leave all decisions to Alec :-)

**Comment by asmecher** [comment] 2016-06-27 21:30
I would suggest we stick with our long-ago decision not to support multilingual checkboxes (i.e. checkbox controls that have different states for different languages). UI/UX-wise these are problematic, but also the cases where we use them are confusing and not widely used. We should pick the value for those settings corresponding to the journal's primary locale,and discard the setting values for other locales.

**Comment by asmecher** [comment] 2016-06-29 21:13
This is a dupe of https://github.com/pkp/pkp-lib/issues/1336

**Closed** 2016-06-29 23:48 UTC
Labels: Open Journal Systems
