### ISSUE TITLE
Can not delete journal, SQL Error

### ISSUE THREAD

**Issue by loadbrain** [pkp/pkp-lib#9615] opened 2024-01-12 10:10 UTC
**Trying to delete a journal from backend as admin throws an error**

**To Reproduce**
1. Login as admin in backend
2. Go to Administration -> Hosted Journals
3. Choose the journal to delete, click Remove
4. Nothing happens
5. ErrorLog:
`PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ojsproddb.highlights' doesn't exist in /var/www/ojs.nomos-journals.de/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Connection.php:414`

**What application are you using?**
 OJS, version 3.4.0.4

**Additional information**
Clean and fresh installation of OJS, so no update/upgrade data

**Comment by jonasraoni** [comment] 2024-01-12 18:39
Thanks for the report @loadbrain! Closing as a duplicate of https://github.com/pkp/pkp-lib/issues/9590

**Closed by jonasraoni** 2024-01-12 18:39 UTC
