### ISSUE TITLE
[OPS] Invalid stage WORKFLOW_STAGE_ID_SUBMISSION

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#7599] opened 2022-01-09 09:03 UTC
**Describe the bug**
In a successful build log I got this warning:
`Undefined offset: 1 in /home/travis/build/pkp/ops/lib/pkp/classes/workflow/WorkflowStageDAO.inc.php on line 86`

**What application are you using?**
OPS /main (3.4 pre-release)

**Additional information**
- The problem is probably located in the file `registry/userGroups.xml`, which assigns two stages to some roles, while the application supports only the `WORKFLOW_STAGE_ID_PRODUCTION`.

- When adding a new submission, it's created with the WORKFLOW_STAGE_ID_PRODUCTION, therefore looks like the submission stage is really not being used.

**Possible solution**
- Update the `registry/userGroups.xml`.
- Add a migration script to remove the database entries.

**PRs**
- https://github.com/pkp/ops/pull/215

**Comment by jonasraoni** [comment] 2022-01-09 10:06
There's already code to address the `submissions.stage_id` here: https://github.com/pkp/ops/blob/main/classes/install/Upgrade.inc.php#L84

**Comment by NateWr** [comment] 2022-01-12 10:52
@ajnyga do you remember if the submission stage ID is necessary? I feel like maybe it was necessary to handle the submission wizard, but I can't remember.

**Comment by jonasraoni** [comment] 2022-01-12 14:03
I didn't tag anyone yet because the build is failing at this moment and I'm watching other things, but I'd definitely enjoy to have a confirmation meanwhile =]
There was another issue in the build log (when creating folders), but I didn't investigate it yet.

**Comment by ajnyga** [comment] 2022-01-27 05:56
The submission wizard in OPS moves the submission to production stage when step 1 is executed: https://github.com/pkp/ops/blob/main/classes/submission/form/SubmissionSubmitStep1Form.inc.php#L178

It means that before that the submission is on WORKFLOW_STAGE_ID_SUBMISSION

**Comment by jonasraoni** [comment] 2022-01-27 06:46
Thanks! I'll take a look and investigate if it's possible to adjust this later, otherwise, I'll just address the warnings...

**Comment by asmecher** [comment] 2022-03-31 22:55
@jonasraoni, I think the fix you proposed in https://github.com/jonasraoni/ops/commit/280f697fb08ee19ee93de089719b068413fbf8e6 and https://github.com/jonasraoni/ops/commit/c668d23f6484eabfe34af7b12ff122623d5ee900 won't pass tests because the submission stage assignment is required in order for a role to be listed on page 1 of the submission process.

I think PHP8.1 promoted this warning to a fatal error, so it's actually a duplicate of https://github.com/pkp/pkp-lib/issues/7783, which I already committed a fix for.

**Closed by asmecher** 2022-03-31 22:55 UTC
Labels: Bug

**Comment by jonasraoni** [comment] 2022-04-01 09:05
Yeah, I was just going to check how coupled this constant is to the rest of code, [like you did](https://github.com/pkp/pkp-lib/issues/7783#issuecomment-1075774932), before silencing the error.
