### ISSUE TITLE
Citation Style Language plugin DOI prefix

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#2961] opened 2017-10-26 12:53 UTC
For now, when using this plugin DOI prefix looks like this in citations (OJS 3.1):
`https://doi.org/https://doi.org/...`

**Comment by bozana** [comment] 2017-10-26 13:07
It seems to be the problem only with APA and Chicago...

**Comment by zuphilip** [comment] 2017-10-31 10:39
Well, that is nowadays the recommended display for a DOI, see for example http://blog.apastyle.org/apastyle/digital-object-identifier-doi/ . The CSL styles are updated by https://github.com/pkp/citationStyleLanguage/pull/7 which include the change from CMoS (Chicago) v16 to v17.

**Comment by amandastevens** [comment] 2018-01-30 14:54
The DOI prefix is also displaying twice with MLA style.

**Comment by larsvilhuber** [comment] 2018-02-26 02:16
I don't believe the issue is with the CSL library. I am no expert, but as far as I can ascertain from https://github.com/citation-style-language/styles , CSL expects the "naked" DOI to be fed to it, which is then prepended either "doi:" (old and un-updated styles) or "https://doi.org/" (updated newer styles). In all cases, feeding the CSL processor the full string "https://doi.org/10.1234/something/here" will ALWAYS lead to a doubling of the https://doi.org part. 

The correct solution is to strip out the "https://doi.org/" in OJS before feeding the citation data into CSL. This is a OJS/PKP problem, not a CSL problem.

**Comment by bozana** [comment] 2018-02-26 09:33
I think this is a duplicate issue of this one: https://github.com/pkp/pkp-lib/issues/3212, correct? Thus closing....

**Closed by bozana** 2018-02-26 09:33 UTC
Labels: Hosting
