### ISSUE TITLE
Submission files under production stage are returning error for no privileges granted 

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#5134] opened 2019-10-09 01:27 UTC
**Describe the bug**
Layout editor is not able to download production files from submissions that are on Production Stage. 
Clicking on the file to download it returns an JSON error related "no privileges to download.
If "More information" is clicked it ends up showing spinning circle only.

**To Reproduce**
1. Log as a Layout Editor and 
3. Go to 'Dashboard > Submissions > Active > Filter by Production'
2. Click on any submission under Production Stage
3. Click to download the file
4. See the error

**What application are you using?**
 OJS version 3.1.2-1

**Additional information**
It is a fresh upgrade from OJS 2.4.x to OJS 3.1.2-1

**More info**
If the files were moved from copyediting to production through OJS the Layout Editor can’t download them.
If the document is upload directly to the production draft files this seems to work.

**Comment by jnugent** [comment] 2020-04-21 12:33
Following up on this because it is probably related.

Describe the bug:

If a file is attached to a note in the review stage, and then promoted to copyediting (where it appears in the draft files grid), a copy editor is unable to download it. The error is the JSON message for insufficient permissions.   Editors have no problem.

The file in question has an assoc_type of 520 (ASSOC_TYPE_NOTE).  It took me a while to figure out what the assoc_id of this note referred to, because it looks like the file that ended up in the draft files grid on the copyediting stage was promoted there from the submission stage.  I figured that out by looking up the note_id -> query_id relationship and realized that it wasn't coming from the discussion in the review stage, but rather the submission stage.

Is this just a case of someone promoting the wrong file to the copyediting stage and the copyeditor does not have access? Or is it case of copy editors not having access to files of ASSOC_TYPE_NOTE?

This is also in OJS 3.1.2-1

**Comment by asmecher** [comment] 2020-04-21 14:52
Hmm, this is a question that needs to be clarified at the user/policy level before it can be fixed at the code level... Because files attached to discussions (queries) have specific user permissions associated with them (i.e. the users assigned to the discussion), it makes sense that users outside that group shouldn't be able to see them... however, the "Promote" action suggests that an explicit broadening of permissions is intended.

Off the top of my head, I think the Promote action could make a copy of the file, with the new copy having the broader access permissions...

**Comment by jnugent** [comment] 2020-05-06 12:45
@asmecher  Could we perhaps (temporarily?) solve this by either making files attached to notes unavailable for promotion, or perhaps make them available only if the user doing the promoting was involved in the original query?  The former is probably easy to do, by a quick check of the file's assoc_type.  We'd essentially be making the rest of the OJS privilege system enforce the original user access, since an editor would need to explicitly download and then re-upload, which makes it a conscious decision.

**Comment by librariam** [comment] 2020-07-28 20:47
+1 from U of T. In our case the copyeditor experiences an issue with Draft Files (as described by Israel), not with discussion files (as described by Jason). Also on 3.1.2-1. 

Unassigning the copyeditor and then assigning them again, as someone suggested on the Forum, did not help. Here is the related Forum thread https://forum.pkp.sfu.ca/t/copyeditor-may-download-some-files-and-some-not-dont-understand-why/46345

**Comment by NateWr** [comment] 2020-08-04 09:01
By coincidence I happen to be doing some refactoring work on the submission files now, so I should be able to address this. @asmecher I like your idea here:

> I think the Promote action could make a copy of the file, with the new copy having the broader access permissions

You ok with me implementing this? I'd only apply it to the Editor Decision actions where a file is promoted from one stage to another.

**Comment by asmecher** [comment] 2020-08-05 16:19
> You ok with me implementing this?

Yes! Particularly if the new submission files schema means that the files aren't physically duplicated any more.

**Comment by NateWr** [comment] 2020-08-24 09:55
This is addressed as part of https://github.com/pkp/pkp-lib/issues/6057. Once it's merged, I'd recommend testing again before closing this. I found that it was not always possible to promote a file from a discussion to one of the file stages (review files, revisions, copyediting, copyedited, etc). The following case allowed me to reproduce this:

1. Move a submission to copyediting.
2. Create a copyediting discussion and upload a file.
3. Click Upload/Select File in Copyedited Files.
4. The discussion file will appear in the list. Click the checkbox and click ok to add it to copyedited files.
5. Click Send to Production and select the file to promote it to Production Ready Files.
6. Assign a Layout Editor (they should not have already been assigned to the submission) and see if they can access this file.

**Comment by NateWr** [comment] 2020-11-27 13:01
Closing this as fixed. I've made a note to cover it during our testing process.

**Closed by NateWr** 2020-11-27 13:01 UTC
Labels: Bug, Hosting
