### ISSUE TITLE
[OJS] DB upgrade script gives fatal error in upgrade from 3.0.2 to 3.1.0

### ISSUE THREAD

**Issue by martinpub** [pkp/pkp-lib#2934] opened 2017-10-24 08:27 UTC
Hi!

I'm upgrading from OJS 3.0.2 to OJS 3.1.0, and when running the db upgrade script, I get the following fatal error:

```
PHP Strict Standards:  Only variables should be passed by reference in /usr/local/ojs-3.1.0/lib/pkp/lib/adodb/adodb-xmlschema.inc.php on line 267

Strict Standards: Only variables should be passed by reference in /usr/local/ojs-3.1.0/lib/pkp/lib/adodb/adodb-xmlschema.inc.php on line 267
[data: dbscripts/xml/indexes.xml]
[code: Installer Installer::installEmailTemplate]
[data: dbscripts/xml/upgrade/3.1.0_update_a.xml]
[code: Installer Installer::fixGenreIdInFileNames]
PHP Strict Standards:  Declaration of SubmissionFileDAO::fromRow() should be compatible with PKPSubmissionFileDAO::fromRow($row, $fileImplementation) in /usr/local/ojs-3.1.0/classes/article/SubmissionFileDAO.inc.php on line 23

Strict Standards: Declaration of SubmissionFileDAO::fromRow() should be compatible with PKPSubmissionFileDAO::fromRow($row, $fileImplementation) in /usr/local/ojs-3.1.0/classes/article/SubmissionFileDAO.inc.php on line 23
PHP Fatal error:  Call to a member function getId() on null in /usr/local/ojs-3.1.0/classes/install/Upgrade.inc.php on line 2476

Fatal error: Call to a member function getId() on null in /usr/local/ojs-3.1.0/classes/install/Upgrade.inc.php on line 2476
```

It is preceded by repeated messages like the first two lines.

Thanks in advance for fixing or pointing me in the right direction.

**Comment by asmecher** [comment] 2017-10-24 16:25
I think this is a duplicate of https://github.com/pkp/pkp-lib/issues/2506#issuecomment-339037699.

**Closed by asmecher** 2017-10-24 16:25 UTC
