### ISSUE TITLE
Sync the values of editorial decision constants across all applications

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#7725] opened 2022-02-23 10:44 UTC
**Describe the problem you would like to solve**
Editorial decision types are tracked by constants like `Decision::ACCEPT`. However, many of the same constants have different values in OJS and OMP. Examples:

| Constant | OJS Value | OMP Value |
| --- | --- | --- |
| Decision::ACCEPT | `1` | `2` |
| Decision::PENDING_REVISIONS | `2` | `4` |

As a result, these constants must be defined separately in each application, resulting in duplicate code. It also makes it harder to interpret database records from one app or another.

**Describe the solution you'd like**
- Make the values of editorial decision constants the same across all applications. 
- Add an upgrade migration that changes existing records to match the new values.
- Move all editorial decision constants into lib/pkp.
- Remove deprecated constants from OPS.

**Additional information**
This work depends on #7265.

**Comment by touhidurabir** [comment] 2022-08-25 13:21
> Move all editorial decision constants into lib/pkp.

@NateWr we have and will still have some `CONSTANTS` specific to `OMP`. you think it's a good idea to move those to `lib/pkp` when we have those some decisions related to those only in OMP ? I don't see a problem with it but we were trying not to out only some specific details in the shared lib unless it's used by multiple apps .

**Comment by touhidurabir** [comment] 2022-08-29 11:30
@NateWr please review

[pkp-lib](https://github.com/pkp/pkp-lib) --> [pkp/pkp-lib#7725 Decision constants sync up](https://github.com/pkp/pkp-lib/pull/8218)
[ojs](https://github.com/pkp/ojs) --> [pkp/pkp-lib#7725 Decision constants sync up](https://github.com/pkp/ojs/pull/3520)
[omp](https://github.com/pkp/omp) --> [pkp/pkp-lib#7725 Decision constants sync up](https://github.com/pkp/omp/pull/1188)
[ops](https://github.com/pkp/ops) --> [pkp/pkp-lib#7725 Decision constants sync up](https://github.com/pkp/ops/pull/339)
[orcidProfile](https://github.com/pkp/orcidProfile) --> [pkp/pkp-lib#7725 decision class path update](https://github.com/pkp/orcidProfile/pull/220)

**Comment by NateWr** [comment] 2022-08-29 12:09
Sorry for the delay in replying to your previous questions, @touhidurabir. I've reviewed the code now.

> we were trying not to out only some specific details in the shared lib unless it's used by multiple apps

Yes, and Alec might not like me recommending this. But I think it's much easier to have all of the constants defined here in one place. It will prevent us from accidentally getting them out of sync again.

> better to make the constant value fully sequential, right ?

I like how you've done it. I'm sure that was a mind-numbing bit of work. :+1:

 > Bit confused about all these global constants `SUBMISSION_EDITOR_DECISION_INTERNAL_REVIEW` as found no use of those . any where they have been used that I am missing ?

This is the old constant for `Decision::INTERNAL_REVIEW`. So any code for 3.3 or below will use `SUBMISSION_EDITOR_DECISION_INTERNAL_REVIEW`. We keep these constants around, for now, to ease the migration of third-party code, which may rely on these constants.

**Comment by asmecher** [comment] 2022-08-29 16:52
> Alec might not like me recommending this

Not enough to bother mentioning it; there are benefits to both approaches. We might actually move to enums later, and those would require us to specify them all in pkp-lib; it'll be impossible to extend them in the apps. So no objections here.

**Comment by touhidurabir** [comment] 2022-08-30 07:27
@NateWr updated PR

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8218
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3520
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1188
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/339

**Comment by NateWr** [comment] 2022-08-30 11:26
All merged to `main`. Thanks @touhidurabir!

**Comment by asmecher** [comment] 2022-08-31 05:15
@touhidurabir, could you have a look at the Travis builds? This appears to have broken the tests for all 3 apps.

**Comment by touhidurabir** [comment] 2022-08-31 05:25
@asmecher I looked into the Travis build. it passed for `OJS` and `OPS`. The build for `OMP` was canceled after a failed build and we discover that that was due to a typo into the `upgrade.xml` so I guess once that fixed, we canceled the test for `OMP` and merged it . can you provide the details where it's breaking or the `travis log` ?

**Comment by asmecher** [comment] 2022-08-31 05:30
Sure, these are the 3 builds where i7725_main were merged:
- https://app.travis-ci.com/github/pkp/ojs/builds/254979579
- https://app.travis-ci.com/github/pkp/omp/builds/254979582
- https://app.travis-ci.com/github/pkp/ops/builds/254979584

The previous builds all appear to pass.

They all appear to fail on the application's API.spec.js. (Actually, I wonder if it's https://github.com/pkp/pkp-lib/issues/7366 that caused the failures?)

**Comment by touhidurabir** [comment] 2022-08-31 06:02
@asmecher the build failing is not related to this issue but related to https://github.com/pkp/pkp-lib/issues/7366 . it's failing for the `cypress/tests/integration/API.spec.js` with following error 

```
API tests
       Configures an author's API key:
     AssertionError: Timed out retrying: Expected to find element: `form[id="apiProfileForm"] button:contains("Create API Key")`, but never found it.
      at Context.eval (http://localhost/__cypress/tests?p=cypress/tests/integration/API.spec.js:27:8)
```
but at the same time passing for similar one lies at `lib/pkp/cypress/tests/integration/API.spec.js` is passing . So I think build failing is not related to the PR of this issue . 

weirdly I can not generate the screenshots for the `log` file using the command `uudecode /path/to/log.txt | tar xvz` as getting error such as 

```
uudecode: cypress-failed-log.txt: stdout: character out of range: [33-96]
tar: Error opening archive: truncated gzip input
```
@asmecher  can you generate the screenshots ? also may be better to move this discussion to https://github.com/pkp/pkp-lib/issues/7366 and reopen it .

**Comment by NateWr** [comment] 2022-08-31 08:41
Yeah I merged this yesterday and can confirm all three app's tests were passing on the PR before merge.

**Comment by touhidurabir** [comment] 2022-08-31 08:44
@NateWr yes , the problem is not related to this one but I think related to https://github.com/pkp/pkp-lib/issues/7366 . I have filed as issue https://github.com/pkp/pkp-lib/issues/8223 and made PR that has updated test (only for OJS now). Hope that fix the build failing issue . Weird part is when the PR made for https://github.com/pkp/pkp-lib/issues/7366, we had no issue with build passing .

**Comment by asmecher** [comment] 2022-08-31 15:38
OK, thanks to you both! Closing this again in favour of https://github.com/pkp/pkp-lib/issues/8223.

**Closed by asmecher** 2022-08-31 15:38 UTC
Labels: Housekeeping:1:Todo
