### ISSUE TITLE
TinyMCE toolbar cut off when editing in two languages

### ISSUE THREAD

**Issue by mooselybased** [pkp/pkp-lib#7535] opened 2021-12-08 10:08 UTC
**Describe the bug**
When editing a journal in the backend and clicking on a secondary language to edit alongside the primary language (effectively cutting the size of textboxes etc in half), the TinyMCE toolbar doesn't adjust in size, but there's too many buttons so the last few are cut off from use. The only way we can currently reach the source code button is by inspecting the element in the browser and manually adjusting the size.

**To Reproduce**
1. Go to any journal that uses more than one language (for more than just UI)
2. In the backend, visit (for example), Website > Appearance > Setup
3. Activate two-language edit view by clicking on your secondary language
4. Scroll down to the Page Footer edit box - the toolbar should look like the screenshot below

**What application are you using?**
 OJS 3.3.0.8

**Additional information**
![grafik](https://user-images.githubusercontent.com/95747530/145189752-e06b0bf6-0ed6-4ed7-b30b-4419ef5e415d.png)

**Comment by NateWr** [comment] 2021-12-08 10:19
Thanks for reporting @mooselybased! This is a duplicate of #6039 so you can follow progress on a solution there.

**Closed by NateWr** 2021-12-08 10:19 UTC

**Comment by mooselybased** [comment] 2021-12-08 10:22
> Thanks for reporting @mooselybased! This is a duplicate of #6039 so you can follow progress on a solution there.

Ah, thanks! I was using only tinymce as a search term when checking the open issues so I overlooked that one, sorry.

**Comment by NateWr** [comment] 2021-12-08 10:30
No worries, there are too many issues to easily find what you're looking for. :)
