### ISSUE TITLE
OJS 3.3.0.8: Anomalous error message using CrossRef XML export plugin

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/pkp-lib#7442] opened 2021-11-08 18:00 UTC
**Description of issue or problem I’m having:**
The CrossRef XML Export Plugin is behaving anomalously. Automatic deposit upon publication failed but the status read “Not Deposited.”

When trying to deposit the submissions manually, some succeed and show the Active status ([example](https://doi.org/10.25071/2561-5467.183)), some succeed and show the Not Deposited status ([example](https://doi.org/10.25071/2561-5467.157)), and others fail with the error message shown below but show the Not Deposited status.

I contacted CrossRef and they say there’s no problem on their end. They confirmed that DOI 10.25071/2561-5467.174 (the second example, above) had deposited even though the status says Not Deposited. I have confirmed that this DOI did successfully deposit because it resolves successfully. However, I can confirm that other submissions have not successfully deposited.

**Steps I took leading up to the issue:**
Automatic deposit of XML with CrossRef plugin, then manual deposit.

**What I tried to resolve the issue:**
Re-running the deposit. Contacting CrossRef

**Application Version - e.g., OJS 3.1.2:**
OJS 3.3.0.8

**Additional information, such as screenshots and error log messages if applicable:**
Error message:

> HTTP Status 500 - Request processing failed; nested exception is ojs.crossref.qs.security.ExceededConcurrentLimit
> User has reached the maximum allowed number of concurrent uses: identify=xxxx;xxxx;currentCount=16;maximumCount=10

![crossref-error](https://user-images.githubusercontent.com/2306629/141276274-a98d0703-4fa3-480f-b8b9-1cc4c1105615.png)

**Comment by NateWr** [comment] 2021-11-09 09:44
Hi @tmrozewski-york, can you provide more detailed reproductions steps. These usually include step-by-step instructions on what you clicked in the UI, like this:

Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Comment by tmrozewski-york** [comment] 2021-11-10 17:44
Sure.

Steps to reproduce the behavior:

1. Go to CrossRef XML Export Plugin
2. Click on Articles tab
3. Select submissions to deposit to CrossRef
4. Click Deposit
5. See error message (screenshot below)

I can't copy and paste the error message because it disappears as soon as I click on it.

![140793711-93398bd5-a136-41fb-a979-28668bffafec](https://user-images.githubusercontent.com/68435195/141165268-156009e5-eb08-4c45-b046-cd69e8361b04.png)

**Comment by NateWr** [comment] 2021-11-11 09:31
Thanks, @tmrozewski-york. So that's pretty straightforward. I suspect if we go and try to reproduce this we won't get the error, because it appears to only occur with some submissions. We'll need to identify how to set up a submission so that the deposit will fail.

Are you able to run SQL queries to look in the database? If so, the Crossref response may be saved in the `publication_settings` table. Can you try looking into that table for columns that have a setting name `LIKE '%crossref%'`?

**Comment by NateWr** [comment] 2021-11-11 09:34
Oh you know what, I think I can see enough of the error message in your screenshot! I can see the following text:

> User has reached the maximum allowed number of concurrent uses: identity=yorkul;yorkul;currentCount=16;maximumCount=10

@bozana or @ewhanson do either of you recognize this error message? It seems like maybe the issue is that on our end we don't identify correctly which submissions were deposited and which weren't?

**Comment by NateWr** [comment] 2021-11-11 09:48
@tmrozewski-york apologies if you got some noise from me editing your posts. I thought that the `identity=` string in the error message exposed your institution's crossref password, so I removed the images, but it turns out that's just your username twice. I've restored the images as they were.

**Comment by bozana** [comment] 2021-11-11 10:30
Hi all, 
that sounds to be an error connected with that specific installation or user. I have not seen it till now. It sounds like there is a limit of requests set by Crossref for you installation/IP/user. It does not sound like it is an error of the DOI deposit. It also seems to return Crossref 500 error which we do not save -- we only save requests errors, and returned 403 Crossref errors -- that's why the statuses of such DOIs are 'Not deposited' (and not 'Failed'). (Could it be that Crossref however deposits those DOIs, although the error message is returned? -- I don't think so.) Maybe to ask Crossref what does that message exactly mean?
Can it be that you have registered some DOIs manually/without the system, so that the system (OJS) does not know that they deposited? (The error message also sounds like there were several 'concurrent uses'... Whatever that means...) -- this is the only (other) way I can explain why the status is 'Not deposited', although they are successfully deposited.

**Comment by tmrozewski-york** [comment] 2021-11-24 16:37
> It sounds like there is a limit of requests set by Crossref for you installation/IP/user.

@bozana I spoke with CrossRef support and they said there's nothing wrong on their end to do with this.

> Are you able to run SQL queries to look in the database? If so, the Crossref response may be saved in the publication_settings table. Can you try looking into that table for columns that have a setting name LIKE '%crossref%'?

@NateWr do you still want me to do this? Your response fell through the cracks in the past few weeks, my apologies.

**Comment by NateWr** [comment] 2021-11-25 10:34
Yes, if you can recover the full error message that will be necessary to move forward on this.

> I spoke with CrossRef support and they said there's nothing wrong on their end to do with this.

There may be nothing wrong on their end, but we will still need an explanation from them regarding the error message in [this comment](https://github.com/pkp/pkp-lib/issues/7442#issuecomment-966149686).

**Comment by tmrozewski-york** [comment] 2021-12-10 19:04
@NateWr I cannot recover the full error message. The error message disappears when I try to click on it.

> There may be nothing wrong on their end, but we will still need an explanation from them regarding the error message in this comment.

CrossRef says: "Thanks for your question.  Our concurrent user limit is 10,000 deposits for a given username at a given point in time, and 'yorkul' has definitely not exceeded that limit.  So, I'm guessing that error pertains to something on the OJS end, not the Crossref end."

I feel like I'm the broken telephone in the middle of all this.

**Comment by NateWr** [comment] 2021-12-13 11:07
Unfortunately, unless we can reproduce this, there's not much we can do to help. I have searched our codebase for key words in the error response (`ExceededConcurrentLimit`, `maximumCount`) and not found anything. The error message comes from Crossref and includes information that suggests the `maximumCount` is `16` not `10,000`. So for now I'm of the opinion that this is on Crossref's side.

I have reached out internally to see if we have contacts at Crossref that can provide us with a better response. But in the meantime I will close this. If we get any new information that suggests a bug on our side, we'll be happy to reopen it.

**Closed by NateWr** 2021-12-13 11:07 UTC

**Comment by AhemNason** [comment] 2021-12-13 14:11
@tmrozewski-york can I ask what happens if you just deposit _one_ of these DOIs that hasn't been registered? Does the error change if it's just one at a time? I ask because in a chat with Crossref support folks they mentioned the following: 

> That is odd.  I’ve seen that “maximum allowed number of concurrent uses” error, but never in a metadata deposit context.  I’ve only seen it when trying to access depositor reports when something somewhere has run out of disk space. That shouldn’t have anything to do with deposit process, especially not the route that the OJS plugin uses.

> I checked the deposit history for user ‘yorkul’ (which corresponds to the prefix in their screenshot).   They submitted 78 deposits between Dec 10th and 12th, and every one of them failed with a regular old timestamp error.

The timestamp error occurs when there's an existing DOI record with a more recent timestamp than the one the you're putting up. "More recent" is a bit misleading, though, because then length/encoding of a timestamp can change based on your environment. To Crossref "bigger is newer". When we run into that error with Crossref we have to request a timestamp reset on their end by giving them a list of all the dois you need to wipe timestamps for. 

The question is why they can see that error and why it isn't what came back from Crossref. 

So, if you could let me know what happens when you deposit a single DOI from this list that would be great.

**Comment by tmrozewski-york** [comment] 2021-12-14 21:24
@AhemNason 
> can I ask what happens if you just deposit one of these DOIs that hasn't been registered? Does the error change if it's just one at a time?

I was getting the same error message when uploading them one at a time. However, at some point in the past month, the problem seems to have resolved itself because all of the submissions for that issue have DOIs that resolve properly and show as "Active" in the plugin. What concerns me is that I don't have any way of telling if the errors were due to, say, an intermittent problem with CrossRef, will recur with the next issue from this journal.

> I checked the deposit history for user ‘yorkul’ (which corresponds to the prefix in their screenshot). They submitted 78 deposits between Dec 10th and 12th, and every one of them failed with a regular old timestamp error.

Fuck. This is a different journal and a different error and, yes, I've run into this problem before. Thank you for letting me know about this one in particular so I can remediate. 

(Can I just take a moment to bemoan the decisions that led be to inherit 50+ separate instances of OJS?)

**Comment by AhemNason** [comment] 2021-12-14 22:18
It sounds at least, @tmrozewski-york, that these were sorted out in the long run. Crossref had a few issues with data centres in the last month and change. My guess is that it was related to that outage. That's a guess! But I'll let folks at Crossref know this sorted itself out. It sounds like this is probably the case and it might explain why we'd not seen that particular error message before?
