### ISSUE TITLE
Improvements for mobile and tablet in the administrative panel

### ISSUE THREAD

**Issue by mundodama** [pkp/pkp-lib#9578] opened 2023-12-18 19:18 UTC
## Issue Description
When accessing the administrative panel via cell phone, the menu takes up a lot of screen space and several elements exceed the screen size.

## How to reproduce / Current behavior
To simulate, using your cell phone, log in to the administrative panel and access any menu, such as: SUBMISSIONS.

## What application are you using?
 OJS - version 3.4.0.3

## Stack used 
- Device: mobile / iphone
- OS: android and iOS
- Browser: chrome, arc, safari, firefox

## Action
I suggest that on cell phones you use a hamburger toggle menu to have space for the content to all fit on the screen.

## Additional information
![Captura de Tela 2023-12-18 às 16 14 31](https://github.com/pkp/pkp-lib/assets/25888347/c4b5073f-50d8-4bd9-936f-7048fdffdcdb)

**Comment by asmecher** [comment] 2023-12-18 20:05
@mundodama, I'm going to close this as a duplicate of https://github.com/pkp/pkp-lib/issues/7497, but feel free to add your feedback on that issue.

**Closed by asmecher** 2023-12-18 20:05 UTC
Labels: Accessibility
