### ISSUE TITLE
[OJS] OJS3.0.2. showing "Review Due" even when the review assignment is not accepted

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2323] opened 2017-03-01 10:16 UTC
This is related to https://github.com/pkp/pkp-lib/issues/2275 but is an independent issue.

Basically OJS 3.0.2. does not check whether the reviewer has accepted the request and shows "review due" anyway. 

I will post  pr in a minute.

**Comment by ajnyga** [comment] 2017-03-01 10:27
@bozana @asmecher the pr is here https://github.com/pkp/pkp-lib/pull/2324

After the pr the logic here https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/reviewer/ReviewerGridCellProvider.inc.php#L54-L66 is:
```
if review is not completed{

	if review is due AND review **is** confirmed
		return overdue
		
	if response is due AND review **is not** confirmed
		return overdue_response
		
	else
		if review is not confirmed
			return waiting
		else
			return accepted
}
```
Basically this means that if the assignment _is not confirmed_, this will first return `overdue_response` and only if it is confirmed it will return `overdue`. So basically the reminders that the reviewer get come in the correct order.

This is already the second time I am looking trough these few lines, so please check this as well in detail if I am missing some case (like I did the last time I made a fix).

**Comment by bozana** [comment] 2017-03-02 15:10
HI @ajnyga, the e-mail template is always the same (REVIEW_REMIND), in both cases (when review respond is due as well as when review is due)., s. https://github.com/pkp/pkp-lib/blob/master/controllers/grid/users/reviewer/form/ReviewReminderForm.inc.php#L67. Thus this change would not change that. Thus, I would leave it as it is -- it is not quite wrong to display the last overdue date/action (meaning that the time overdue is even worse and the editor should finally do something). Or maybe to ask @NateWr, if it would make more sense to display the first overdue date/action, in this case that the reviewer haven't responded yet?

**Comment by ajnyga** [comment] 2017-03-02 16:53
Thanks @bozana 

This is not really about the email templates. I am talking only about the review assignment status that is shown to the editors in the review stage.

I think it is not logical for a review to be late if the reviewer has not even responded yet. In my opinion something can be late only if something has been promised.

Also, why should we show the same status for these cases:
- no response, review due -> Review Due
- response given, review due -> Review Due
I mean, the editor now has to go and edit the review assignment to find out what the exact status is, when with this change there would be a clear difference. 

The issue was originally a feedback from one of our journals. The editor did not understand why the status was the same for both those cases. IMHO this is a clear bug.

**Comment by NateWr** [comment] 2017-03-02 16:56
That sounds right @ajnyga. I think the original idea was that a lapsed review due date is more serious, and therefore a higher priority, than a lapsed response due date. But you're right that it ends up presenting misleading information.

I can only think of one other case to account for in your logic. If the response due date is _after_ the review due date, and the review is not confirmed, your logic will return `waiting`, when it should probably return `overdue`.

If the response due date is _after_ the review due date, probably something's gone wrong on the user end, but we should still make sure we're showing an `overdue` message if anything is overdue.

Ideally, we should add a form validation check that doesn't allow a response due date after a review due date.

**Comment by ajnyga** [comment] 2017-03-02 17:40
Hmm, maybe then something like this
```
if (!$reviewAssignment->getDateCompleted()) {
	if (!$reviewAssignment->getDateConfirmed()){
		if($reviewAssignment->getDateResponseDue() < Core::getCurrentDate(strtotime('tomorrow'))) {
			return 'overdue_response';
		} else {
			return 'waiting';
		}
	} else {
		if ($reviewAssignment->getDateDue() < Core::getCurrentDate(strtotime('tomorrow'))) {
			return 'overdue';
		}  else {
			return 'accepted';
		}
	}
}
```

**Comment by NateWr** [comment] 2017-03-06 10:33
That looks good @ajnyga, and for me at least that logic is a lot easier to follow. I'll copy it for some refactoring I'm doing related to some new submissions list stuff I'm doing. :+1:

**Comment by bozana** [comment] 2017-03-06 13:49
@ajnyga, I can then change it that way, if you want... :-)

**Comment by ajnyga** [comment] 2017-03-06 13:58
Hi,

@bozana @NateWr thanks, I am just suggesting stuff, it is really up to you what you choose to merge and I realize that I am only presenting one way of thinking. But if that looks logical then It would be nice to have that change there!

**Comment by NateWr** [comment] 2017-03-07 18:06
I integrated this logic with some changes I'm making to the ReviewAssignment status code in a PR that's connected to the new submission list component:

https://github.com/pkp/pkp-lib/pull/2339/commits/5dfcd1ebc88ff0f0c506339a498836094740953c#diff-f66bf03a819f6fa88df1860150054f1eR491

We hope that will go into 3.1, in which case this will get fixed alongside that.

**Comment by ajnyga** [comment] 2017-03-07 18:18
thanks, I will stick with a local change till then.

**Comment by asmecher** [comment] 2017-03-16 00:18
@NateWr, assigning to you since it's already more or less on your plate.

**Comment by NateWr** [comment] 2017-07-27 10:18
This made it in with the JS/API merge at 9809cedd1c7a568ddd430b05e52fac423295db77

**Closed by NateWr** 2017-07-27 10:18 UTC

**Comment by mczirfusz** [comment] 2018-04-03 12:08
A question regarding this issue. _Is this behaviour the one which was intended?_ 
- The message in the Reviewers block is that a response is overdue.
- The message in the Round Status remained as it was before the patch: "A review is overdue".
![image](https://user-images.githubusercontent.com/16511307/38247614-3ea6c0c0-3746-11e8-9214-9af711423da7.png)
- As the latter information is used in the Active Submissions list (reworked for OJS 3.1), it is misleading, as not the review, but the response is overdue.
![image](https://user-images.githubusercontent.com/16511307/38247718-876d4f5e-3746-11e8-9609-1bc5a8d125dc.png)

The incoherence as I understand that [`REVIEW_ASSIGNMENT_STATUS_RESPONSE_OVERDUE`](https://github.com/pkp/pkp-lib/blob/5dfcd1ebc88ff0f0c506339a498836094740953c/classes/submission/reviewAssignment/ReviewAssignment.inc.php#L37) exists but [`REVIEW_ROUND_STATUS_RESPONSE_OVERDUE`](https://github.com/pkp/pkp-lib/blob/e61d1bbd5a8a6230a2093caf5d10956a74007771/classes/submission/reviewRound/ReviewRound.inc.php#L33) not.
