### ISSUE TITLE
[OJS] Sword missing file in ZIP

### ISSUE THREAD

**Issue by paschty** [pkp/pkp-lib#4177] opened 2018-10-24 11:20 UTC
I tried to ingest something with the sword plugin to my mycore repository.
If i inspect the zip which was sent from OGS, i only see a mets file and the linked files from the mets file is missing.

**Comment by asmecher** [comment] 2018-10-24 16:52
Try patching https://github.com/asmecher/sword/commit/cca076dbf1715075f9fcd750bd3095c5f36398a5; if you're using filenames that aren't supported by your local filesystem, this should address it. Please confirm if this solves the problem.

**Comment by paschty** [comment] 2018-10-25 10:02
@rochpaul applied the patch, but the zip still only contains he zip file.

**Comment by asmecher** [comment] 2018-10-25 17:54
Hmm; are you getting any warnings in your PHP log about missing files or file permissions when you make the deposit?

**Comment by rochpaul** [comment] 2018-11-06 16:45
Yes, we get some informations about missing files:

`[Tue Nov 06 15:40:01.663142 2018] [:error] [pid 18654] [client 92.117.35.169:42546] PHP Warning:  copy(/tmp/swordimyNbW/files/Zeitschriftenverwalter/in, Trump_Mueller_and_the_US_Constitution.pdf): failed to open stream: Datei oder Verzeichnis nicht gefunden in /ojs/ojs-3.1.0/plugins/generic/sword/classes/OJSSwordDeposit.inc.php on line 117, referer: https://ojs.ub.uni-due.de/TJ/workflow/index/281/4`

**Comment by asmecher** [comment] 2018-11-06 17:03
Thanks, @rochpaul, that helps -- could you also try patching 113d601?

**Comment by paschty** [comment] 2018-11-07 12:41
The copy warning is gone no, but still no pdf.

`unzip -l /var/folders/2t/1r76p55d7ds1rhlzsjnb94hh0000gn/T/swordv2_
swordv2_8152583822235586643deposit.zip  swordv2_9215077302706103601deposit.zip  
sebastian@Sebastians-MacBook-Pro-2:~$ unzip -l /var/folders/2t/1r76p55d7ds1rhlzsjnb94hh0000gn/T/swordv2_8152583822235586643deposit.zip 
Archive:  /var/folders/2t/1r76p55d7ds1rhlzsjnb94hh0000gn/T/swordv2_8152583822235586643deposit.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
     2796  11-07-2018 12:44   mets.xml
---------                     -------
     2796                     1 file`


`unzip -c /var/folders/2t/1r76p55d7ds1rhlzsjnb94hh0000gn/T/swordv2_8152583822235586643deposit.zip 
Archive:  /var/folders/2t/1r76p55d7ds1rhlzsjnb94hh0000gn/T/swordv2_8152583822235586643deposit.zip
  inflating: mets.xml                
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<mets ID="sort-mets_mets" OBJID="sword-mets" LABEL="DSpace SWORD Item" PROFILE="DSpace METS SIP Profile 1.0" xmlns="http://www.loc.gov/METS/" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.loc.gov/METS/ http://www.loc.gov/standards/mets/mets.xsd">
	<metsHdr CREATEDATE="2008-09-04T00:00:00">
		<agent ROLE="CUSTODIAN" TYPE="ORGANIZATION">
			<name>Sonja Hendriks</name>
		</agent>
	</metsHdr>
<dmdSec ID="sword-mets-dmd-1" GROUPID="sword-mets-dmd-1_group-1">
<mdWrap LABEL="SWAP Metadata" MDTYPE="OTHER" OTHERMDTYPE="EPDCX" MIMETYPE="text/xml">
<xmlData>
<epdcx:descriptionSet xmlns:epdcx="http://purl.org/eprint/epdcx/2006-11-16/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://purl.org/eprint/epdcx/2006-11-16/ http://purl.org/eprint/epdcx/xsd/2006-11-16/epdcx.xsd">
<epdcx:description epdcx:resourceId="sword-mets-epdcx-1">
<epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/type" epdcx:vesURI="http://purl.org/eprint/terms/Type" epdcx:valueURI="" />
<epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/title">
<epdcx:valueString>Der Titel</epdcx:valueString>
</epdcx:statement>
<epdcx:statement epdcx:propertyURI="http://purl.org/dc/terms/abstract">
<epdcx:valueString>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam</epdcx:valueString>
</epdcx:statement>
<epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/creator">
<epdcx:valueString>Neumann, Kathleen</epdcx:valueString>
</epdcx:statement>
<epdcx:statement epdcx:propertyURI="http://purl.org/eprint/terms/isExpressedAs" epdcx:valueRef="sword-mets-expr-1" />
</epdcx:description>
<epdcx:description epdcx:resourceId="sword-mets-expr-1">
<epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/type" epdcx:valueURI="http://purl.org/eprint/entityType/Expression" />
<epdcx:statement epdcx:propertyURI="http://purl.org/dc/elements/1.1/type" epdcx:vesURI="http://purl.org/eprint/terms/Type" epdcx:valueURI="http://purl.org/eprint/entityType/Expression" />
</epdcx:description>
</epdcx:descriptionSet>
</xmlData>
</mdWrap>
</dmdSec>
	<fileSec>
		<fileGrp ID="sword-mets-fgrp-1" USE="CONTENT">
			<file GROUPID="sword-mets-fgid-0" ID="sword-mets-file-0" MIMETYPE="application/pdf">
				<FLocat LOCTYPE="URL" xlink:href="/tmp/swordKNbZTj/files/Trump_Mueller_and_the_US_Constitution.pdf" />
			</file>
		</fileGrp>
	</fileSec>
	<structMap ID="sword-mets-struct-1" LABEL="structure" TYPE="LOGICAL">
		<div ID="sword-mets-div-1" DMDID="sword-mets-dmd-1" TYPE="SWORD Object">
			<div ID="sword-mets-div-2" TYPE="File">
				<fptr FILEID="sword-mets-file-0" />
			</div>
		</div>
	</structMap>
</mets>
`

**Comment by kkrebs** [comment] 2019-01-25 09:08
Is there anything we can do, to help resolving this issue?

**Comment by asmecher** [comment] 2019-01-26 05:18
@kaitlinnewson, could you test the patch in https://github.com/pkp/pkp-lib/issues/4177#issuecomment-436329399 to see if it resolves the issue?

**Comment by kaitlinnewson** [comment] 2019-01-28 19:51
@asmecher did you meant to tag me in this or @kkrebs?

**Comment by asmecher** [comment] 2019-01-28 23:57
Sorry, yes, I meant to tag @kkrebs.

**Comment by rochpaul** [comment] 2019-01-29 12:31
Hi,

i have spoken with @kkrebs and @paschty.

For a better debugging in code i have add some logs.
I prepared the code this way:

     public function _addFile($submissionFile) {
        error_log('Try to log failure on _addFile(submissionFile) in /ojs/ojs-3.1.0/plugins/generic/sword/classes/OJSSwordDeposit.inc.php');
        
                $targetFilename = $this->_outPath . '/files/' . $submissionFile->getOriginalFileName();
                
                error_log('value of $submissionFile:');
                error_log(print_r($submissionFile,true));
                
                error_log('value of $targetFilename:');
                error_log(print_r($targetFilename,true));
                
                copy($submissionFile->getFilePath(), $targetFilename);
        $this->_package->addFile($targetFilename, $submissionFile->getFileType());
        }

Maybe this could help better to find the problem. I have attached the dependent log.

Kind regards, Paul
[dependent_log.txt](https://github.com/pkp/pkp-lib/files/2807645/dependent_log.txt)

**Comment by paschty** [comment] 2019-01-29 12:54
The FLocat look like this now:
`<FLocat LOCTYPE="URL" xlink:href="/tmp/sword6TFw0X/files/Trump_Mueller_and_the_US_Constitution.pdf" />`

**Comment by asmecher** [comment] 2019-01-30 21:49
@paschty, try also applying this patch:
https://github.com/asmecher/sword/commit/baac36d64291655e2484125cca6aa26b64b8974f.diff

It'll resolve an error message in your log, which will hopefully result in something more helpful being logged when you try a deposit.

**Comment by asmecher** [comment] 2019-03-05 02:00
@paschty, I've just done some work with the Sword plugin to get it going for OJS 3.1.2, and ran across the missing file problem. Can you try this patch?

https://github.com/asmecher/sword/commit/a03d2990ce801c877ce83079e4aa8e40210f421e

If you're able to confirm that this resolves the problem, I'll put together a new release for OJS 3.1.1. (There's a new release for OJS 3.1.2 that already contains this and is tested working.)

**Comment by rochpaul** [comment] 2019-03-05 12:55
@asmecher, I have installed the following patches:

https://github.com/asmecher/sword/commit/baac36d64291655e2484125cca6aa26b64b8974f.diff
https://github.com/asmecher/sword/commit/a03d2990ce801c877ce83079e4aa8e40210f421e

@paschty have tested the sword plugin and the problem is solved.

Thank you very much @asmecher for the patches.

**Comment by asmecher** [comment] 2019-03-05 16:02
Released v1.0.1-1 for OJS 3.1.1 with this fix included. Thanks, @rochpaul!

**Closed by asmecher** 2019-03-05 16:02 UTC
