### ISSUE TITLE
Register Site for Indexing Revisions

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#1789] opened 2016-09-01 18:49 UTC
Site Admin > Site Settings > Site Setup > Register Site for Indexing

We should remove this section altogether from Site Setup. We want to have journals registered individually in the PKP Index -- and I'm not sure how much this is used for other purposes.

Can we instead include something specific for the individual journals under Settings > Indexing (under Search Engine Indexing):

PKP Index

Registering with the PKP Index (http://index.pkp.sfu.ca) will add your journal and its contents to our growing database of OJS journals, raising its global visibility.

Click here to register (http://index.pkp.sfu.ca/index.php/user/register) and enter http://journals.sfu.ca/uiux/index.php/jpk/index under Site URL, and http://journals.sfu.ca/uiux/index.php/jpk/oai under Base URL for OAI Archive.

**Comment by asmecher** [comment] 2017-03-16 00:50
Dupe of https://github.com/pkp/pkp-lib/issues/2211

**Closed by asmecher** 2017-03-16 00:50 UTC
