### ISSUE TITLE
[OJS] legacy emails deleted from emailTemplates.xml may still appear in installs upgraded from 2.x

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#3202] opened 2017-12-19 23:01 UTC
This is a legacy upgrade issue, but it also ties in with Issue #3193. A number of emails that were in OJS 2 but deleted from OJS 3 are still in upgraded OJS 2->3 databases, and appear in some contexts. In some contexts, they are semi-broken. I'll use COPYEDIT_ACK as an example. 

COPYEDIT_ACK was used in OJS 2.x to provide an acknowledgement email as part of the copyedit process. This discrete process no longer exists in OJS 3.x, and the email was deleted from `locale/en_US/emailTemplates.xml` (see https://github.com/pkp/ojs/commit/1c86f9329997a1339a9eb0f8f2f04074e47e70a5#diff-ede2aeb2dfb88eecd563b9c5fef5209b). 

The email is still included in the database for journals that have upgraded from OJS 2.x, and still appears in Settings -> Workflow -> Emails. More problematically, they are also available from the "Predefined Message" dropdown when assigning or notifying participants. In these cases, the email is available to be chosen, but the message body is blank.

I am unsure what to propose as a solution. There is no way to delete one of these emails from the system - you can only disable them, or reset them, and I'm not sure what happens if you try to reset an email when it's not in `emailTemplates.xml`. I'd be hesitant to use the "Reset all Templates" option, especially if a journal has made customizations to templates that are still in use in the system. I'd advocate for a cleanup process on upgrade to delete all obsolete templates or templates that are not included in `emailTemplates.xml`, except I've advocated elsewhere for the option to create new templates (to be used in separate workflows - see Issue #3193). 

I wonder if one option would be to simply add more context and control to the Prepared Emails listing, showing the following: 

- whether the email is part of the current set of prepared emails (ie. in `emailTemplates.xml`); 
- whether it has been modified; 
- an option to delete, if it's not in the current set of prepared emails.

**Comment by asmecher** [comment] 2017-12-20 19:22
@jmacgreg, are you sure `COPYEDIT_ACK` appears in the drop-down in the workflow? I can't see any reference to it (at least in 3.1.0-x).

I figured it was best not to flat-out remove those templates during upgrade, as managers might want to rescue some of the wording used in those if they've been customized.

**Comment by jmacgreg** [comment] 2017-12-20 19:53
@asmecher yep - see attached screenshots (and I can provide access if necessary, just DM me). The issue here is that this is a journal that's been upgraded from 2.x, so even though there isn't reference to it in 3.1.x it's still presumably being drawn from the DB. 

This probably deserves a bit more discussion, but I'd personally prefer some strict pruning over potential for future confusion. 

![image](https://user-images.githubusercontent.com/201446/34225734-aea7dc6a-e584-11e7-8b5b-e97a348a5bc2.png)
![image](https://user-images.githubusercontent.com/201446/34225752-bcd8826c-e584-11e7-97b0-d996c332e9e7.png)

**Comment by diegoabadan** [comment] 2017-12-20 20:27
> This probably deserves a bit more discussion, but I'd personally prefer some strict pruning over potential for future confusion.

Maybe keep, but add a suffix like: [legacy - OJS 2.x]

**Comment by pkel** [comment] 2018-03-05 17:14
We also have these disturbing templates appearing in some places. How can I get rid of them? I already tried to use the *Reset All Templates* button on `/management/settings/publication` > *Emails*  but they are still there.

**Comment by asmecher** [comment] 2018-03-06 19:05
@pkel, I'd suggest checking the `email_templates_default` and `email_templates_default_data` tables for them, and removing what you don't want. (Make sure you remove them from both tables -- look in `email_templates_default_data` first, identify the email key there, and then remove from `email_templates_default`.)

**Comment by pkel** [comment] 2018-03-14 09:54
@asmecher, the `_default` templates where fine, but I found 37 entries in `email_templates` while `email_templates_data` was empty. There might be an error with ojs2 -> 3 migration or the *Reset All Templates* function. I purged `email_templates` and everything looks fine now. Thanks.

**Comment by NateWr** [comment] 2021-12-08 10:07
The email template management UI has changed significantly since this issue was filed. I'm going to close this, but in order to reopen it we'd like to see a sample database that reproduces the problem.

**Closed by NateWr** 2021-12-08 10:07 UTC
Labels: Hosting
