### ISSUE TITLE
Retrieving publications in alphabetically ordered category when changing language

### ISSUE THREAD

**Issue by AlineLepidus** [pkp/pkp-lib#7419] opened 2021-11-01 17:58 UTC
**Describe the bug**
About the categories sorting by title, when choosing the current locale and the publications didn't have a translated title, it isn't showing in the category same having title in primary locale.

More about the problem, can know in [forum](https://forum.pkp.sfu.ca/t/category-does-not-list-all-articles-when-sorting-by-title-is-selected/69168).

**To Reproduce**
The steps are:
1. Have 2 languages in your system, e.g. English and Portuguese
2. Have a category with order of articles by title
3. Create 2 preprint or articles with title in one language (e.g. Portuguese) and another make blank
4. Add both for the category
5. Go to the site, choice the language of the preprint and the created category
6. When change the language (e.g. for the English), the preprint isn't showing in the category

**What application are you using?**
OJS and OMP  stable 3_3_0 branch 

**Additional information**
In the [link](https://teste.ojs3.emnuvens.com.br/kamilla/catalog/category/Resumosexpandidos), for example, if you change the language for English in the `Resumos expandidos` category, the articles don't be showing.

**Comment by AlineLepidus** [comment] 2021-11-01 17:59
https://github.com/pkp/pkp-lib/pull/7323

**Comment by bozana** [comment] 2021-11-02 22:51
Hmm... The problem is maybe elsewhere: when an article in a language other than journal primary language is submitted, there are only entries for that article locale in the publication_settings table. In contrary, when an article in the journal primary language is submitted, there are entries for all journal locales in the publication_settings table, just that they are empty ('').

**Comment by bozana** [comment] 2021-11-03 10:52
PR:
stable-3_3_0: https://github.com/pkp/pkp-lib/pull/7427

**Comment by bozana** [comment] 2021-11-03 10:56
@jonasraoni, could you please take a look? If OK, it would be a simpler way to solve it...
@AlineLepidus, thanks a lot for the PR and contribution!

**Comment by AlineLepidus** [comment] 2021-11-03 15:15
@bozana, I tested your PR, and it retrieves all articles for the category. However, when accessed by the current locale (second language), it does not respect the alphabetical order in case the current locale is empty ('').

**Comment by AlineLepidus** [comment] 2021-11-04 14:42
@bozana 
So, we take look your PR and add a new line for the case of the title empty in second language.

PR: https://github.com/pkp/pkp-lib/pull/7323

**Comment by bozana** [comment] 2021-11-05 10:24
Oh, yes, I have forgotten that COALESCE considers empty string... Great! Thanks a lot!
If no objections, @jonasraoni, I could merge and provide other PRs, for submodule updates and other branches...

**Comment by jonasraoni** [comment] 2021-11-05 13:30
Hi @bozana! I just checked the PR, I didn't see anything suspect, so I just left a few comments. As you've already tested, great =]

**Comment by bozana** [comment] 2021-11-12 10:41
Here all PRs:

stable_3_3_0:
pkp-lib: 
https://github.com/pkp/pkp-lib/pull/7323
https://github.com/pkp/pkp-lib/pull/7427
ojs: https://github.com/pkp/ojs/pull/3225 (only submodule update)
omp: https://github.com/pkp/omp/pull/1029 (only submodule update)
ops: https://github.com/pkp/ops/pull/197 (only submodule update)

main:
pkp-lib:

**Comment by bozana** [comment] 2021-11-12 12:57
I think we have considered everything... ?
Merged... 
Closing...

**Closed by bozana** 2021-11-12 12:57 UTC
Labels: Bug
