### ISSUE TITLE
Mailables, jobs and scheduled tasks throw fatal errors

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8022] opened 2022-06-21 17:49 UTC
**Describe the bug**
Fatal errors are occurring with emails that are sent in jobs. We're not clear on the cause, but this may be related to scheduled tasks. @Vitaliy-1 discovered potential problems with calls to `$request->getDispatcher()`. He also suggested that the `Locale` facade may be missing, causing calls to `getLocalizedData()` to fail.

**To Reproduce**
Reproduction is still uncertain. But problems were encountered with the PRs in https://github.com/pkp/pkp-lib/issues/6126#issuecomment-1162080408. There are some reproduction steps in that comment for how to run the scheduled tasks to create the jobs.

**What application are you using?**
`main` branch, 3.4 pre-release

**Comment by asmecher** [comment] 2022-07-11 18:49
@touhidurabir, this is skimpy on reproduction steps, but something to keep in the back of your mind as you start looking through queue-related issues.

**Comment by touhidurabir** [comment] 2022-08-04 09:55
A PR has been made which includes solution for this issue , [check it here](https://github.com/pkp/pkp-lib/issues/7105#issuecomment-1205015287).

> @Vitaliy-1 discovered potential problems with calls to $request->getDispatcher()

Indeed that is one of the core problem and the cause of it was following calls 
```php
Application::get()->getRequest()->getDispatcher()
```

so patch in the `PKPRequest::getDispatcher` added to address that issue in the [PR](https://github.com/pkp/pkp-lib/pull/8133/files#diff-aba3ab700056f12927bbd81ff51e4431a9fcad560295c6b162b16e998bb60556)

> He also suggested that the Locale facade may be missing, causing calls to getLocalizedData() to fail.

Based on my digging, this is mostly happening when email templates are not installed and no such check in place to determined if email templates found or not . For example , in the `PKP\Jobs\Email\EditorialReminder::handle()`, the same error will happen for the following code if email templates are not installed

```php
$mailable = new MailablesEditorialReminder($context);
$emailTemplate = Repo::emailTemplate()->getByKey($context->getId(), $mailable::getEmailTemplateKey());

$mailable
    ->setOutstandingTasks($outstanding, $submissions, $submissionIds->count())
    ->from($context->getContactEmail(), $context->getLocalizedName(Locale::getLocale()))
    ->recipients([$editor])
    ->subject($emailTemplate->getLocalizedData('subject'))
    ->body($emailTemplate->getLocalizedData('body'));
```

@Vitaliy-1 can you provide a case or confirmed that failure for jobs at `getLocalizedData()` is causing even when email templates are installed .

**Comment by Vitaliy-1** [comment] 2022-08-04 14:48
I was able to debug the problems I've encountered with running jobs from scheduled tasks and I remember that one of them was indeed related to the dispatcher. 
I recall Nate used the approach to set needed locale globally during job execution; @NateWr, is this related to that, do you remember more details?

**Comment by NateWr** [comment] 2022-08-08 09:26
Sorry I can't remember exactly. But if you want to test localized data, probably inside of the email variable classes is the best place to do it, since they rely on the request and sometimes the dispatcher.

@touhidurabir when a variable is passed into a mailable, like `new MailablesEditorialReminder($context)`, this is converted to a related email variable, such as `ContextEmailVariable`, which produces the variables used in emails, like `{$contextUrl}`. Looking at an email that receives a submission should involve enough localized variables to cause the problem -- if it still exists.

**Comment by touhidurabir** [comment] 2022-08-17 11:16
Testing trough the job classs `PKP\Jobs\Email\EditorialReminder` which use the mailable class `MailablesEditorialReminder` internally , it seems working so hopefully the `localisation` related issue already got fixed by other commits . Now once the PR made for pkp/pkp-lib#7105 get merge, the `$request->getDispatcher` related issue will also get resolved .

**Comment by touhidurabir** [comment] 2022-09-23 07:26
@NateWr I think this can be closed at this fixed by https://github.com/pkp/pkp-lib/issues/7105 . see the comment at https://github.com/pkp/pkp-lib/issues/8022#issuecomment-1205028996 .

**Closed** 2022-10-03 08:39 UTC
Labels: Bug:3:Critical
