### ISSUE TITLE
[UI] Help on-off toggle

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#1047] opened 2016-01-14 13:53 UTC
It doesn't actually work at the moment. I believe we used a class name to just `display:none;` the help content, but I may have removed this class unwittingly while refactoring. At least it doesn't appear around the grid description text.

What's the likelihood that we'll be able to replace inline help with the contextual help panel in #1032 in time for OMP 1.2? If so that would be great and we can actually remove the Help toggle.

If that's too ambitious we'll need to get it working again (or just leave the help text in place until we can offload it).

**Comment by asmecher** [comment] 2016-01-14 15:53
The code is easily merged in time for OMP 1.2, the problem is content. It'll be tough to write up much in Markdown before OMP 1.2 is released. Maybe we can talk basics with @stranack sometime soon?

**Comment by asmecher** [comment] 2016-01-14 15:54
(I don't think the current built-in help is useful enough to maintain and would rather see it removed.)

**Comment by asmecher** [comment] 2016-01-15 01:26
@NateWr, if you think this is a good approach, I've got a PR that removes the grid "description" fields (that were previously shown/hidden by the help toggle) entirely. And the help toggle. This will (slightly) reduce the complexity of grids, and prep us for markdown-based help, and clean out the broken help toggle. Downsides: the content that used to be there will be chucked, and we may not have a replacement in time for OMP 1.2.

Pulls:
https://github.com/pkp/omp/pull/195
https://github.com/pkp/pkp-lib/pull/1055

If those look reasonable, I'll also need to port to OJS before merging.

**Comment by stranack** [comment] 2016-01-15 01:39
Yes, even if we just start with some placeholder text. Friday next week?


On 2016-01-14 7:53 AM, Alec Smecher wrote:
> The code is easily merged in time for OMP 1.2, the problem is content.
> It'll be tough to write up much in Markdown before OMP 1.2 is released.
> Maybe we can talk basics with @stranack <https://github.com/stranack>
> sometime soon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pkp/pkp-lib/issues/1047#issuecomment-171680521>.
>

-- 
--
Kevin Stranack, MLIS, MAEd
Learning and Development Consultant
Email: kevin@stranack.ca
Twitter: @stranack
Skype: kstranack
Web: http://stranack.ca

**Comment by NateWr** [comment] 2016-01-15 14:38
I suspect we'll hit a number of places where users will get stuck. But if we have Kevin on the user testing we'll be able to surface and address those in time for OJS 3.0. And OMP 1.2 users will by-and-large have a familiar set of controls, so I'm in favor.

@asmecher would you like me to check out your PRs and test them myself first? Or just take a look after you've merged the changes? I suspect it's a-ok with me.

**Comment by asmecher** [comment] 2016-01-15 19:44
@stranack, Friday next week is perfect.

@NateWr, don't worry, just double-checking that it's not just me who's OK with nuking the existing stuff. Will merge, thanks.

**Closed** 2016-01-15 19:54 UTC
Labels: Open Journal Systems, Open Monograph Press

**Comment by NateWr** [comment] 2016-01-18 11:05
:+1:
