### ISSUE TITLE
[OJS] Simpler HTTP Address?

### ISSUE THREAD

**Issue by thumos333** [pkp/pkp-lib#6329] opened 2020-11-11 00:58 UTC
Hello,

The journal where I work is moving to PKP OJS platform and the system administrator who supervises this move says it is impossible to create a simpler address for the publication, without "index.php" in the address line. Just as an example, Cultural Anthropology journal has the address "https://journal.culanth.org/index.php/ca". Is there a way to make it "https://journal.culanth.org/ca"? Thank you.

**Comment by NateWr** [comment] 2020-11-11 10:15
Hi @thumos333, yes you can use Apache's mod_rewrite along with `.htaccess` rules to remove the `index.php` in the URL. Most web servers should be able to accommodate this without any problems (for example, this is how WordPress works).  

I just went looking for documentation on this at our [Administrator's Guide](https://docs.pkp.sfu.ca/admin-guide/en/) but didn't find any. I'll try to track down where we have this documented. In the meantime, here's the `.htaccess` file I use which should suffice for most cases:

```
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php/$1 [QSA,L]
</IfModule>
```

I'm going to close this as it's not a bug or feature request, but feel free to follow up anyway.

**Closed by NateWr** 2020-11-11 10:15 UTC

**Comment by NateWr** [comment] 2020-11-11 10:24
Also, if you want to run a single journal at a root domain, look at the optional path additions to the `config.inc.php` file described in this comment: https://github.com/pkp/pkp-lib/issues/4919#issuecomment-511459058.

**Comment by thumos333** [comment] 2020-11-11 12:57
@NateWr many thanks for this info - I will tell the administrator.

**Comment by thumos333** [comment] 2020-11-19 08:35
@NateWr Your method has worked just fine for the journal's homepage. Is it possible, though, to delete "index.php" completely from all address lines generated by the engine? For example, right now the issue address is "http://journals.institute.org/index.php/journalname/issue/view/3". The same useless "index.php" seems to be present everywhere except the homepage.

**Comment by NateWr** [comment] 2020-11-19 11:54
The regex that I posted above does this for me. It removes the `index.php` from the entire site. Are you able to visit that issue page by removing the `index.php`? If the URLs on the site still include it, you may need to clear the cache from the Administration area in the backend.

**Comment by thumos333** [comment] 2020-11-19 22:11
> Are you able to visit that issue page by removing the `index.php`?

Yes, there seems to be no difference, with or without `index.php`.

> If the URLs on the site still include it, you may need to clear the cache from the Administration area in the backend.

But yes, that's the case: all generated URLs include `index.php`.

**Comment by NateWr** [comment] 2020-11-23 10:49
What is the `base_url` in your config file?

**Comment by thumos333** [comment] 2020-11-29 21:47
@NateWr Thanks! I told the admin to take a look at this value and he fixed it. No more 'index.php' in address lines.
