### ISSUE TITLE
[OMP] multiple accessiblity issues

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1071] opened 2016-01-19 20:22 UTC
Using the [AInspector plugin](https://addons.mozilla.org/en-US/firefox/addon/ainspector-sidebar/) for Firefox, multiple issues are reported against the OMP default home page (and subsidiary pages).

The most critical violations are:
1. content outside landmarks
2. no `main` landmark
3. insufficient color contrast in text
4. form controls without labels
5. forms without submit buttons

On the dashboard, there are additional violations reported:
1. landmarks are not uniquely identifiable
2. headings are not properly nested
3. `<a href>` links have unsupported `role` values
4. buttons without content
5. labels without controls
6. non-unique labels
7. events without roles
8. widgets without labels or non-descriptive labels

Other warnings and manual-check recommendations are present, too.

**Comment by asmecher** [comment] 2016-01-19 22:35
@crism, what version of OMP are you using? Master branch, or latest stable?

**Comment by crism** [comment] 2016-01-19 23:11
This is against `HEAD`, sorry.

**Comment by asmecher** [comment] 2016-01-20 00:29
@NateWr, quick thoughts?

**Comment by NateWr** [comment] 2016-01-20 10:31
I'd need to look at the specific recommendations. I'll install the addon and take a look next week. Quick thoughts:

- Landmarks are an easy win I've been meaning to do for a bit (at least the basic roles)
- Color contrast: I suspect it's the block titles in the sidebar. They're just below AA. I was able to ask an accessibility expert specifically about this kind of thing and I was told that the AA standard is excessively conservative, and that if we're close, but not quite there, we're probably ok.
- Forms: the frontend are a couple of things I forgot around the search form but should be ok once I fix those. Our backend is and will remain a problem until we rebuild the FBV, and probably until we rethink some of our form elements.
- Headings: on the backend it can be difficult to have a perfectly formatted `<h*>` nesting, because we're combining elements in different ways. But a quick look shows that we are missing `<h1>` on most pages and that needs to get worked out.

**Comment by NateWr** [comment] 2016-01-25 16:33
Ok I've spent some time with that browser plugin today. It's much more useful than others I've seen. Thanks for pointing it out @crism.

I've made a number of changes detailed in PRs:

https://github.com/pkp/pkp-lib/pull/1084
https://github.com/pkp/omp/pull/199
https://github.com/pkp/ojs/pull/721

Broadly speaking, these commits do the following:

- Add aria landmark roles in backend and frontend
- Add a few missing form labels/attributes on the frontend
- Improve heading order on the frontend (h1->h2->h3->h4)

There are a few things I'm not addressing:

- It's throwing a warning that the `h1` on the homepage is missing text. But I think this is a false positive, since I was unable to find any information suggesting that `alt` text is not picked up as part of an `h1`. This exposes another issue though: users may neglect to add `alt` text and then they'd have an empty `h1`. Worth considering an alternative.
- It's throwing a warning about duplicate labels and landmark roles because we list our search form twice. As far as I'm concerned, this is a user-friendly duplication and not a problem unless an accessibility expert can tell me otherwise.
- Color contrast: we're just below AA in a couple places, but as described above I'm not worried about this. Also, based on some discussions we've had recently, @asmecher, the places that are on the borderline may be changed, making this irrelevant. We can revisit later if we need to.
- The user group labels on the registration form are throwing duplicate label warnings, which doesn't make any sense to me, since they're not duplicate. As far as I'm aware, these are marked up in the most correct fashion.

On the backend, we're throwing tons of problems primarily related to our ad-hoc and inappropriate use of form labels. This is to be solved when we redo the FBV.

We're also getting a bunch of warnings related to table cell headers, which has me confused because our grids do implement headers. I'm not really sure precisely what's going on here.

The following issues were raised on the backend but require more investigation or consideration:

- The jQuery UI tabs are throwing some role errors. I looked and they use `role=presentation`, which is usually what you would expect when interaction is implemented separately or in a particularly unique way. I don't really know how accessible these tabs are to be honest, but they clearly have had thought put into them as they're packed full of `aria` attributes.
- One of the warnings that's thrown a lot is when an `<h*>` element appears out of order (eg - jump from `h1` to `h3`). This is primarily caused by our grids. I don't really know how to address situations where we have duplicate content (grids) appearing in multiple places. We could add hidden `h*` elements descrbining a grid and remove them from the grid. Or we could add a grid parameter. Either way is pretty resource-intensive and prone to error as development moves forward. I'm not sure how critical this warning is, really. As far as I'm aware, it degrades the experience but doesn't necessarily make it unusable, when you skip a heading.
- Our modals are causing an error because hte checker wants all content to exist within a landmark role. I'm not sure what the appropriate landmark role is for such content and I'm hesitant to go adding one on just to pass a test. These are very meaningful designations that shouldn't be abused.

**Comment by asmecher** [comment] 2016-01-25 16:41
@NateWr, good to have you on this. Watch out for JSLint's very inflexible rules on whitespace -- they're breaking the validation phase of the builds.

**Comment by NateWr** [comment] 2016-01-25 20:40
Woops. WordPress code style is very white-space-happy so I'm always struggling to switch contexts at the start of the week. Tests running again.

I looked at the file running the linting to see if I could easily run it as a grunt task locally, but lots of stuff in there I didn't really understand...

**Comment by asmecher** [comment] 2016-01-25 20:47
It's a PITA to set up, fairly version-sensitive, and takes more than a moment to run locally as well. Frankly I've been happy to have Travis work on it while I go and do something else for 20 minutes.

**Comment by NateWr** [comment] 2016-01-26 15:41
The OJS tests passed but the [OMP tests failed](https://github.com/pkp/omp/pull/199). Looks unrelated to me as I'm pretty sure I didn't touch anything relating to grids in these commits.

While investigating it raised a couple other issues that I will report in #983.

**Comment by asmecher** [comment] 2016-01-26 16:53
@NateWr, it looks like one of the two integration tests had a hiccough (the other passed). I've restarted the failed test and expect it'll probably complete just fine.

**Comment by asmecher** [comment] 2016-01-26 16:58
@NateWr, I've merged/cherry-picked your PRs above. Leaving the issue open as there's still unaddressed items.

**Comment by crism** [comment] 2016-01-26 17:30
This is great progress. Thanks, @NateWr! I’ll bring up some of your questions and quibbles with our local accessibility SIG, and see what their opinions are.

**Comment by crism** [comment] 2016-03-02 19:49
@NateWr, I’m trying to write this up for our accessibility SIG, and I’m having trouble coming up with simple, clear descriptions of the remaining questions and quibbles. Can you help me with that? If so, drop me an e-mail; it’s this same username at Illinois dot edu.

I’ll be talking with some of the folks who developed that browser plugin, so your feedback is really helpful, thanks.

**Closed** 2021-10-21 09:24 UTC
