### ISSUE TITLE
Automatic e-mail to thank the reviewers

### ISSUE THREAD

**Issue by adrianojam** [pkp/pkp-lib#6823] opened 2021-03-04 17:18 UTC
**Describe the problem you would like to solve**
Currently, the editor has to click on a button to thank the reviewer.

**Describe the solution you'd like**
One idea would be to have an option, when the reviewer sends his opinion, an email will automatically be triggered thanking him, without having to click to do so.

**Who is asking for this feature?**
Journal Editors and Journal Administrators

**Comment by asmecher** [comment] 2021-03-04 18:22
This is a duplicate of: https://github.com/pkp/pkp-lib/issues/1661
Please add your feedback there if some element isn't already captured!

**Closed by asmecher** 2021-03-04 18:22 UTC
