### ISSUE TITLE
[OPS] Sort list of available preprints by date of posting

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#6187] opened 2020-08-18 12:55 UTC
**Describe the problem you would like to solve**
Currently, the list of public preprints is sorted by the Submission Date, which makes newly posted preprints sometimes appear below other preprints, depending on their submission date.

**Describe the solution you'd like**
The list should either be sorted having the posting date as default, or allowing the Server Admin or Reader to determine how they want to sort the list.

**Who is asking for this feature?**
As a reader, it would be important to show newly posted preprints at the very top of the list, otherwise newly posted preprints with older submission dates might get lost in the "crowd" of preprints.

**Comment by NateWr** [comment] 2020-08-19 10:14
I think this is important so I am tentatively assigning it to 3.3.

@alexxxmendonca is this the way it is sorted on the homepage as well as the full preprints archive pages?

**Comment by alexxxmendonca** [comment] 2020-08-19 11:08
Hi @NateWr,

Yes, the behavior is the same on both.

**Comment by ajnyga** [comment] 2020-12-07 07:22
OPS: https://github.com/pkp/pkp-lib/issues/6187
No changes to pkp-lib required

Note that for Categories the order is defined in the category settings.

**Comment by NateWr** [comment] 2020-12-07 11:40
Merge, thanks!

**Closed by NateWr** 2020-12-07 11:40 UTC
Labels: Enhancement

**Comment by alexxxmendonca** [comment] 2021-06-02 19:03
I think this has not been fixed.

This preprint was posted on June 2: https://preprints.scielo.org/index.php/scielo/preprint/view/2401

And yet, in the "Latest preprints" home page feed it is appearing below preprints that have been posted on June 1:

![image](https://user-images.githubusercontent.com/4059679/120537737-04661900-c3bc-11eb-8d63-947ea8100e2f.png)

The one that appears directly above it was posted on May 27: https://preprints.scielo.org/index.php/scielo/preprint/view/2389

**Comment by NateWr** [comment] 2021-06-03 12:28
It looks like Scielo's preprints list is being sorted by the submitted date instead of the posted date. I was unable to reproduce this with the `stable-3_3_0` branch, so I suspect it's a customization in the Scielo install. It looks like the theme has been customized so I'd look there for possible differences with the templates in the `stable-3_3_0` branch.

**Comment by alexxxmendonca** [comment] 2021-06-07 13:08
@diegoabadan do you think this could be related to the theme developed by Lepidus?

**Comment by diegoabadan** [comment] 2021-06-07 13:34
From what I could see in the theme code, it is without this fix. I asked our team to generate a corrected version.

**Comment by alexxxmendonca** [comment] 2021-06-07 13:35
@diegoabadan thank you!
