### ISSUE TITLE
[OJS]

### ISSUE THREAD

**Issue by rajeevrnt** [pkp/pkp-lib#6523] opened 2021-01-02 12:13 UTC
Why don't you sent reset password link on registered email id? This practice is commonly used by banks or other institutions.

**Comment by asmecher** [comment] 2021-01-03 16:40
@rajeevrnt, please include all the information we might need to understand your bug report or feature request; see the templates here: https://github.com/pkp/pkp-lib/issues/new/choose

**Comment by NateWr** [comment] 2021-01-04 12:44
Duplicate of https://github.com/pkp/pkp-lib/issues/6524.

**Closed** 2021-01-04 12:44 UTC
