### ISSUE TITLE
Fatal Error during upgrade from OJS 3.2.1.3 to 3.3.0 RC2

### ISSUE THREAD

**Issue by drugurkocak** [pkp/pkp-lib#6692] opened 2021-01-28 21:24 UTC
**Describe the bug**
Hi,
I am testing OJS 3.3.0RC2 obtained from https://forum.pkp.sfu.ca/t/ojs-omp-ops-3-3-community-testing/64628.
Clean install runs very well. I am able to install themes from plugin gallery, and perform all editorial processes.

I tried to upgrade a clone of live ojs 3.2.1.3 journal. 
Both on command line and web interface, I get the following error; 

> [29-Jan-2021 00:11:39 Europe/Istanbul] PHP Fatal error:  Uncaught Error: Call to a member function getConnection() on null in /home/adlitip/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php:74
> Stack trace:
> #0 /home/adlitip/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php(200): Illuminate\Database\Capsule\Manager::connection()
> #1 /home/adlitip/public_html/lib/pkp/classes/db/DAO.inc.php(65): Illuminate\Database\Capsule\Manager::__callStatic('raw', Array)
> #2 /home/adlitip/public_html/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(106): DAO->retrieve('SELECT setting_...', Array)
> #3 /home/adlitip/public_html/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(86): PluginSettingsDAO->getPluginSettings('0', 'defaulttranslat...')
> #4 /home/adlitip/public_html/lib/pkp/classes/cache/GenericCache.inc.php(63): PluginSettingsDAO->_cacheMiss(Object(FileCache), 'enabled')
> #5 /home/adlitip/public_html/lib/pkp/classes/plugins/PluginSettingsDAO.inc.php(57): GenericCache->get('enabled')
> #6 /home/ad in /home/adlitip/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Capsule/Manager.php on line 74
> 

It might have been reported before but I couldn't find a solution yet.

Operating system | CentOS Linux 7.9.2009
Perl version | 5.016003
Apache version | 2.4.6
PHP versions  7.4.14
MySQL version | 10.4.17
php runs as cgi-wrapper

Regards,

**Comment by asmecher** [comment] 2021-01-28 22:04
@drugurkocak, this seems like a duplicate of: https://github.com/pkp/pkp-lib/issues/6587
Could you try that resolution?

**Closed by asmecher** 2021-01-28 22:04 UTC

**Comment by drugurkocak** [comment] 2021-01-29 18:24
Dear @asmecher 
Thank you very much. After applying that fix, the upgrade started properly. Now, I am getting the error in that page https://github.com/pkp/pkp-lib/issues/6565#issue-783579910. Before opening a new issue,  I am double checking if it was reported before :)
Best regards,

**Comment by asmecher** [comment] 2021-01-29 18:35
@drugurkocak, if you're able to work with the git repository directly, the current `master` branch has all these fixes and more :)

**Comment by drugurkocak** [comment] 2021-01-29 18:55
Dear @asmecher 
Thank you very much, your support is motivating me. I previously started wit git install, but I get a different error after install. The error was;
Fatal error: Cannot redeclare __() (previously declared in /home/adlitip/public_html/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php:893) in /home/adlitip/public_html/lib/pkp/classes/i18n/PKPLocale.inc.php on line 923
I had an error during  composer (submodule) update related to laravel, but I didn't note it down.
Since I couldn't find a quick fix for it, I switched to archive install method. 
Thanks again.

**Comment by asmecher** [comment] 2021-01-29 19:01
The Composer installer should apply a patch that resolves this; watch the output of `composer install` (executed in `lib/pkp`) to see if the patch is applied successfully.

**Comment by drugurkocak** [comment] 2021-01-29 19:41
Dear @asmecher 
The error message I remember was actually "Could not apply patch! Skipping. The error was: Cannot apply patch lib/laravel-helper-4017.diff". I found this from Safari search history. 

I can apply the fixes if explained in detail, but I can't make any action if not explained anywhere.
So, I couldn't fix the error that "composer couldn't apply the patch" :)
I don't want to consume your energy so much, I will go on following the forum and the issues here.
Best regards,

**Comment by drugurkocak** [comment] 2021-01-31 18:43
Hi,
Just to give you information, the error that I faced which composer couldn't apply the patc;
 "Could not apply patch! Skipping. The error was: Cannot apply patch lib/laravel-helper-4017.diff"
has also been reported in;
https://github.com/pkp/pkp-lib/issues/6413
The error was resolved after installing the patch command via yum.
I'm again sorry for the confusion.
Regards,
