### ISSUE TITLE
Possible hook regression from function signature changes

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4612] opened 2019-03-18 18:10 UTC
One minor regression in 3.1.2 to look out for, introduced with #3578, is that arguments were removed from the `formclassname::execute` hook. 

The change removes arguments from the `execute` method signature in forms, like here:

https://github.com/pkp/ojs/blame/master/controllers/grid/settings/sections/form/SectionForm.inc.php#L124 

That means that `func_get_args()` will never get an argument in `Form::execute()` here:

https://github.com/pkp/pkp-lib/blob/master/classes/form/Form.inc.php#L311

Use cases are probably pretty rare, but this is the cause of https://github.com/pkp/browseBySection/issues/16.

Filing for your attention @asmecher, just in case you know of other places where this change might impact negatively on plugins. Feel free to close if not.

**Comment by asmecher** [comment] 2019-03-19 01:54
Thanks, @NateWr. This is also the cause of https://github.com/pkp/pkp-lib/issues/4601.
I suggest we stick with the new hook conventions and fix plugins where needed -- depending on the dynamically-passed arguments will be unreliable in general and the fix was necessary for better PHP compliance (e.g. to fix numerous warnings where function calling conventions were inconsistent).

**Comment by asmecher** [comment] 2019-03-19 01:57
This also breaks the OpenAIRE plugin.

**Comment by isgrim** [comment] 2019-03-20 08:01
The problem that for many forms now there is no way to access the dataobject that was created (look at RegistrationForm.inc.php for example) from a plugin hook. This is currently preventing me from implementing the registration with ORCID correctly #4601 .

This has to be a member variable of the form object, so that plugins can change/add data during Form::execute.

**Comment by NateWr** [comment] 2019-03-20 10:45
> there is no way to access the dataobject that was created

I think the preferred solution here is to attach the object to the `RegistrationForm` class so that it is available from the hook.

Beware that the hook is fired _before_ the user is saved to the database. If you need to do anything after they've been added, we'll need to add a separate hook.

**Comment by isgrim** [comment] 2019-03-20 10:48
Thanks @NateWr for the fast response.

> Beware that the hook is fired before the user is saved to the database.
Yes, this is no problem in this case.

**Comment by asmecher** [comment] 2019-03-20 19:47
Hi all -- so...
- the Browse By Section impacts of this are resolved in https://github.com/pkp/browseBySection/issues/16,
- the ORCID impacts are (soon to be) resolved at https://github.com/pkp/pkp-lib/issues/4601,
- the Immersion theme impacts will be resolved at https://github.com/pkp/immersion/issues/10, and
- OpenAIRE impacts are fixed here for release in the next build (this plugin isn't packaged separately): https://github.com/pkp/ojs/commit/7f34cc48e01c6c1577747d3a2b3953beec5d66a8

That takes care of everything I'm aware of.

**Closed by asmecher** 2019-03-20 19:47 UTC
