### ISSUE TITLE
OJS 3.3 rc - Duplicate username in lougout as message - Logout as {$username} username

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#6561] opened 2021-01-10 21:51 UTC
**Describe the bug**
When logged in as another user, I see a "Logout as {$username} username" - with an unresolved variable and an actual username.

![image](https://user-images.githubusercontent.com/45104797/104136419-f27bcf00-5363-11eb-8d41-fca3f23791d2.png)

**To Reproduce**
1. Log in as another user
2. Navigate to a submission workflow
3. See the "Logout as {$username} username" message in the right-hand sidebar.

**What application are you using?**
OJS 3.3rc

**Comment by NateWr** [comment] 2021-01-11 11:58
Duplicate of https://github.com/pkp/pkp-lib/issues/5390.

**Closed by NateWr** 2021-01-11 11:58 UTC
Labels: Bug
