### ISSUE TITLE
Native Import/export: Unexpected error when importing

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#5960] opened 2020-06-03 16:47 UTC
**Describe the bug**
see also https://forum.pkp.sfu.ca/t/error-when-importing-using-native-xml-import-plugin-in-3-2-0-3/60948

**What application are you using?**
 OJS version 3.2.X

**Additional information**
That's an issue related to import filter execution failure. The failure is not getting handled, and a `null` `Submission` object is getting returned.

**Comment by defstat** [comment] 2020-06-26 15:50
@asmecher This fixes some problems regarding possible general errors with publications imports. 

**PRs**
**[master]**
[pkp-lib]: #6051
[OJS]: pkp/ojs#2829

**Comment by asmecher** [comment] 2020-06-26 16:33
@defstat, does any of the publication import/export stuff in https://github.com/pkp/ojs/pull/2829 need porting to OMP?

**Comment by eddoff** [comment] 2020-10-02 06:23
I have still problems with the Native Import. I have made a fresh install of ojs 3.2.1-1 and made the above corrections. I can import a file that has been exported from the same version, but when I try to make my own import file I get similar problem as I described in https://forum.pkp.sfu.ca/t/error-when-importing-using-native-xml-import-plugin-in-3-2-0-3/60948 

I also tried to use the XML proposed in this thread: https://forum.pkp.sfu.ca/t/httperror-while-importing-native-xml-issue-ojs-3-2-0-2/60197/12 but that does not work either. I get a blank screen. 

This is a Fatal Error I have got (settings in my config.inc.php is client_charset = utf-8 and connection_charset = utf8 Could it relate to that the database_charset variable is removed in the later versions?): 
[Fri Oct 02 06:14:59.849365 2020] [php7:error] [pid 19857] [client xx.xx.xx.xx:xxx] PHP Fatal error:  Uncaught Exception: DB Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' Query: SELECT\ts.*\n\t\t\tFROM\tsections s, section_settings l\n\t\t\tWHERE\tl.section_id = s.section_id AND\n\t\t\t\tl.setting_name = ? AND\n\t\t\t\tl.setting_value = ? AND\n\t\t\t\ts.journal_id = ? in //lib/pkp/classes/db/DAO.inc.php:703\nStack trace:\n#0 /path-to-ojs/lib/pkp/classes/db/DAO.inc.php(103): DAO->handleError(Object(ADODB_mysqli), 'SELECT\\ts.*\\n\\t\\t\\tF...')\n#1 /path-to-ojs/classes/journal/SectionDAO.inc.php(101): DAO->retrieve('SELECT\\ts.*\\n\\t\\t\\tF...', Array)\n#2 /path-to-ojs/plugins/importexport/native/filter/NativeXmlPublicationFilter.inc.php(40): SectionDAO->getByAbbrev('\\xD1\\x81\\xD1\\x82', 1)\n#3 /path-to-ojs/lib/pkp/plugins/importexport/native/filter/NativeImportFilter.inc.php(60): NativeXmlPublicationFilter->handleElement(Object(DOMElement))\n#4 /path-to-ojs/lib/pk in /path-to-ojs/lib/pkp/classes/db/DAO.inc.php on line 703, referer: https://domain.com/index.php/test/management/importexport/plugin/NativeImportExportPlugin

**Comment by asmecher** [comment] 2020-10-02 19:47
@eddoff, I don't think that's relevant to this issue, and I see you've also posted it at https://forum.pkp.sfu.ca/t/error-when-importing-using-native-xml-import-plugin-in-3-2-0-3/60948/15. Please just try to pick one place to post a question; otherwise support effort might end up getting duplicated.

**Comment by eddoff** [comment] 2020-10-02 20:21
Ok, I'm sorry! I will post on one place in the future!
I have now got an import file to work. However I got wrong encoding even though I have used UTF-8. I saw that the database_charset variable was removed from config.inc.php. Could that be related?

By the way, it should be great if you can get the sample xml files to work with the latest version!

**Comment by asmecher** [comment] 2020-12-08 20:31
@defstat, I'm not sure where these PRs stand since the summer; could you review and rebase if needed? Thanks/sorry!

**Comment by jnugent** [comment] 2021-03-18 14:18
Hi everyone, I wanted to comment with my own experiences here. We've had problems with imports using Native XML breaking installations because submissions get created with no corresponding entry in the publications table. @defstat's commits here prevent the corruption from occurring, so for us that's a big positive.  I suspect that this change here:

https://github.com/defstat/ojs/commit/23c1b3baab0e04db9f035632dd4d29a816b4eb4b#diff-980e964aad3318cd57a3848c1f0618b99fe9dfb38a4cb54d0d7189ef1ce2739fR140

Prevents the corrupted XML from being generated in the first place since it fixes the typo in the filter.  However, I don't think that this specific change will be sufficient to fix broken XML from being generated unless the record is changed in the database as well.

**Comment by jnugent** [comment] 2021-03-18 14:42
It looks like the corresponding filterConfig entry that builds the Native XML also needs an adjustment, since in `stable-3_2_1` it is still just a single Publication object on input:

https://github.com/pkp/ojs/blob/stable-3_2_1/plugins/importexport/native/filter/filterConfig.xml#L132

**Comment by jnugent** [comment] 2021-03-22 17:50
Hi again, everyone.  I'm back with some more information.  First, @defstat if you want the XML file I'm using for this test, just ping me on slack. 

So, with a fresh pull of stable-3_2_1, things do import correctly in the following circumstances:

1. The exported XML is correct
2. The journal the data is being imported into has a) all of the required "uploader" users and also all of the sections specified by the `section_ref` attribute.  
3.  Using my test XML file I was able to successfully import all three of the articles in it as long as 1 and 2 were met. After doing that, I deleted these three submissions, and then changed one of the sections in the journal so there'd be a problem.  Running the import again, rather than the import backing out of the failed article, I ended up with three entries in the submissions table, but only two in the publications table, and a fatal error in the log. Stack trace:


```
PHP Fatal error:  Uncaught Error: Call to a member function getData() on null in /var/www/html/ojs-3.2.1/classes/search/ArticleSearchIndex.inc.php:38

Stack trace:
0 /var/www/html/ojs-3.2.1/plugins/importexport/native/filter/NativeXmlArticleFilter.inc.php(61): ArticleSearchIndex->submissionMetadataChanged()
1 /var/www/html/ojs-3.2.1/lib/pkp/classes/filter/Filter.inc.php(449): NativeXmlArticleFilter->process()
2 /var/www/html/ojs-3.2.1/plugins/importexport/native/NativeImportExportPlugin.inc.php(312): Filter->execute()
 /var/www/html/ojs-3.2.1/plugins/importexport/native/NativeImportExportPlugin.inc.php(147): NativeImportExportPlugin->importSubmissions()
```
Because it's a fatal error, nothing gets shown to the user on the import results tab, but now the submissions grids are broken with spinning progress wheels.

The concern here (for us, I suppose) is that migrating clients will export content from their own journals and then break their new installs because they don't remember to create the sections, and this gets especially bad if it's a shared installation since cleaning the database requires more than just a restore.

Please let me know if you'd like more details.

**Comment by defstat** [comment] 2021-04-02 11:24
@jnugent @asmecher 

I have prepared those commits for main branch:

PRs 
[main]
pkp-lib: #6907
OJS: pkp/ojs#3092
OMP:  pkp/omp#954

Those changes are made against main branch and can be applied to ojs/omp 3.3

**Comment by asmecher** [comment] 2021-04-07 01:19
@defstat, I think those might be too invasive for the `stable-3_3_0` branch -- certainly for 3_3_0-5 -- and maybe should be kept for `stable-3_3_1` (and `main`) instead. Changes for the current stable release (`stable-3_3_0`) should be coded against that branch and forward-ported, rather than coded against `main` and back-ported; that helps prevent regressions on the stable branches.

So if they test OK for @jnugent, please go ahead and merge for `stable-3_3_1` and `main`; however, I don't think we should add them to `stable-3_3_0` or earlier unless we're 100% sure they don't cause regressions.

**Comment by asmecher** [comment] 2022-04-08 15:45
At this point I'd recommend moving these to `main` instead of `stable-3_3_0`. @jnugent, if you're needing this for `stable-3_3_0`, feel free to try them -- we'd appreciate the feedback.

**Comment by asmecher** [comment] 2022-05-09 23:36
Thanks, @defstat, I've merged those!

**Closed by asmecher** 2022-05-09 23:36 UTC
