### ISSUE TITLE
Components - Restore Defaults Doesn't Work

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#2036] opened 2016-11-25 18:38 UTC
I removed a couple of the default components, and then hit Restore Defaults to bring them back.

It doesn't appear to have done anything to restore those.

**Comment by NateWr** [comment] 2021-11-11 10:30
A duplicate of https://github.com/pkp/pkp-lib/issues/1672.

**Closed by NateWr** 2021-11-11 10:30 UTC
