### ISSUE TITLE
OJS 3.2.1 - Unable to pick a year in the advanced filters of the search form 

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#7168] opened 2021-07-02 14:46 UTC
**Describe the bug**
Enabling the search for a multi-journal install and making a search returns the results page with empty advanced filters. They only shows "0" as an option for year.
It affects every theme.

**To Reproduce**
1. Run a search
2. Go to the results page
3. Attemp to select an year (star or end)

**What application are you using?**
 OJS version 3.2.1

**Additional information**
![image](https://user-images.githubusercontent.com/4992902/124291661-caa34200-db22-11eb-9d4d-46cf527a8430.png)

**Comment by israelcefrin** [comment] 2021-07-02 14:59
This issus is similar to this one which affected OJS 3.3 - https://github.com/pkp/pkp-lib/issues/6406

**Comment by NateWr** [comment] 2021-07-12 12:36
What version of 3.2.1 are you using? It looks like the fix was ported to `stable-3_2_1` in December 2020, so should be fixed in 3.2.1-4.

**Comment by wangra8** [comment] 2021-07-13 21:17
Hi Everyone, I'm also confirming that on OJS 3.3.0.6 was have also encountered this bug as well. I checked that the bug fixes from https://github.com/pkp/pkp-lib/issues/6406 were ported over. I'm not sure what's the root of the issue yet.

**Comment by NateWr** [comment] 2021-07-14 07:51
I'm not able to reproduce this on the `stable-3_3_0` branch. So there is likely some combination of configuration or published article dates that is causing this problem. (You've all got published articles with valid publication dates, right?) If anyone can provide reproduction steps on a clean install that would be great.

**Comment by NateWr** [comment] 2021-09-21 09:14
It looks like we were assuming a context in part of the search handler.

PRs:
https://github.com/pkp/ojs/pull/3186
https://github.com/pkp/ops/pull/181

**Comment by NateWr** [comment] 2021-09-22 08:48
Merged to `stable-3_3_0` and applied to `main`.

**Closed by NateWr** 2021-09-22 08:48 UTC
Labels: Hosting, Bug
