### ISSUE TITLE
Journal Summary, Editorial Team and About the Journal field is not writable (nor clickable) (OJS3.4rc2 testing) 

### ISSUE THREAD

**Issue by shantanu198713** [pkp/pkp-lib#8902] opened 2023-04-10 10:29 UTC
**Describe the bug**
Unable to edit the journal summary, editorial team, and about the journal.
If I am clicking on the text box area to enter text then editing/entering text is not allowed.
If I try Sections/Categories -> Create Section/Add Category -> Cancel without saving, then go back to the "Masthead" and click on the textbox area for the Journal Summary, Editorial Team and About Journal, which appear to edit/enter enabled to enter text can be entered.

**I think every long text box field is not writable (nor clickable).**

**To Reproduce**
1. Go to 'Journal'
2. Click on 'Masthead'
3. Scroll down to 'Journal Summary, Editorial Team and About the Journal'

**What application are you using?**
 OJS-3.4.0
![OJS3 4 Journal Summary, Editorial Team and About the Journal](https://user-images.githubusercontent.com/108086810/230884878-0ff4bf6d-aad3-45ad-a14d-3ac63b58cab3.jpg)

**Comment by Vitaliy-1** [comment] 2023-04-10 11:51
Hi @shantanu198713,

I'm unable to reproduce it, are there any associated errors in PHP log or browser console?

**Comment by NateWr** [comment] 2023-04-10 13:39
Thanks @shantanu198713. There are a couple of similar reports. I'll close this and continue investigating the issue at https://github.com/pkp/pkp-lib/issues/8901.

**Closed by NateWr** 2023-04-10 13:39 UTC
