### ISSUE TITLE
Revised Author files not appearing in files from all accessible workflow stages

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#7296] opened 2021-09-15 19:18 UTC
Issue is reported on an OJS 3.2.1.2 hosted journal and duplicated on OJS 3.3.0.6 local install.

**Summary of Steps:**
1) Author uploads revised files
2) Editor accepts manuscript follows the prompts, sending email, selecting files.
3) Editor unselects some of the revised files (accidental or at the time on purpose).
4) Editor is unable to add the revised files using the Upload/Select function.
5) Editor will either need to manually download and re-upload or re-record the decision.

The author had uploaded a number of revised files:

![image](https://user-images.githubusercontent.com/50342731/133494867-07d6cae8-f279-45be-a841-a111f9152520.png)

If an Editor unselects these files (accidentally or on purpose) when moving the manuscript from Review to Copyediting.

![image](https://user-images.githubusercontent.com/50342731/133494988-46408548-f34c-4412-9dde-84f6e48550df.png)

The remaining files cannot be added in the Copyediting Stage using the Upload/Select function within the 'Draft Files' box

![image](https://user-images.githubusercontent.com/50342731/133495117-825d5cb1-3e99-409d-a32c-1b1ecb00d31e.png)

![image](https://user-images.githubusercontent.com/50342731/133495224-4038abfe-101c-4577-936b-e18299804f8f.png)

It seems an editor only way to move these files would be to 

1) Manually save the file from the Review Stage and upload them to the Copyediting stage
2) Go back to the Review stage and re-record the decision to prompt the file selection again.

Journal user has pointed out that from a workflow perspective, the journal will usually have the most relevant/final reviewed files in the revisions section of the review stage.

**Comment by asmecher** [comment] 2022-09-14 22:32
@NateWr, unless you have any objections, I'll defer this to 3.3.0-13.

**Comment by NateWr** [comment] 2023-01-17 15:13
I believe this is a duplicate of #4087. In both cases, the problem is that Revision Files can not be added to Files for Copyediting from the copyediting stage.

**Closed by NateWr** 2023-01-17 15:13 UTC
Labels: Hosting, Bug:1:Low
