### ISSUE TITLE
[Ojs 2.4.x] Statistics considerably reduced

### ISSUE THREAD

**Issue by atarix83** [pkp/pkp-lib#2634] opened 2017-07-04 10:20 UTC
Hi, 

I've noted that after [this commit](https://github.com/pkp/ojs/commit/91d7c72df58c7410806f1009d3ffd82f21a63574) journals statistics are considerably reduced. In my case total access are four times smaller than before the update of the plugin "usageEvent".
There is a reason of this? Should I consider the statistics before update not reliable? 

Thanks
Giuseppe

**Comment by bozana** [comment] 2017-07-04 10:45
Hi @atarix83, unfortunately yes, in a way: before that commit the access to files other than full text, e.g. CSS and images, were considered as well, which is not COUNTER compliant :-(
However, I wonder how come that the counts are that much considerably reduced because of that :-O
Would it be maybe possible for you to test the current usage stats logging in your installation: to look if everything is being correctly logged (in the current log file in your files_dir/usageStats/usageEventLogs/ folder) while you access you journal i.e. article pages?

**Comment by atarix83** [comment] 2017-07-04 11:08
Hi @bozana 
I've already made some test, for example with an article page, and I've seen that with old code download event was logged two times, one while viewing the page and one on download of the pdf file, instead now is logged only one time.
However I'm able to make other test

**Comment by bozana** [comment] 2017-07-04 11:22
Do you mean logged two times when viewing the same page? If so, this was also not correct -- it should be logged only one. 
Else, there should be one log entry when viewing an article abstract page and one when viewing the PDF page.
The CSS and images are only relevant for HTML galleys. Do you have HTML galleys?

**Comment by atarix83** [comment] 2017-07-04 13:56
Yes for the same PDF page there were two download entry log, now only one as for the abstract page.

Unfortunately I can't detect how many HTML Galleys there are

**Comment by atarix83** [comment] 2017-07-12 10:52
Hi @bozana 

I'd ask your opinion about what percentage I could considerate wrong the statistics before the plugin update.

Thanks

**Comment by bozana** [comment] 2017-07-12 11:40
Hi @atarix83, I cannot tell that -- it all depends. For example: although the access to a PDF file was logged twice, it could be that it is however counted only 1, because the plugin could consider it as a double click, if the time between those entries/clicks is less than 30 seconds.
Thus, I can only recommend to test and watch the current counts for some time now, if they are correct, and if possible not to compare them with the older ones.

**Comment by bozana** [comment] 2017-07-12 11:42
I will also close this issue -- because it is not a bug or so. This kind of questions better suits for the forum: http://forum.pkp.sfu.ca/.

**Comment by atarix83** [comment] 2017-07-12 14:38
Ok thank you so much!!

**Comment by atarix83** [comment] 2017-07-19 08:33
Hi @bozana 

I know that the issue is closed, but I think that I've found what cause my problem.
Practically the event for the download of the pdf it's not logged when you click on download link in the article page. 
This doesn't cause an issue with browser like chrome or edge which can show pdf in the article page (with browser plugin) and this generate a download entry log. But with firefox which has adobe reader plugin disabled and doesn't show pdf in the article page this is a problem, because no download entry log is generated.

**Comment by bozana** [comment] 2017-07-19 10:46
Hi @atarix83 
Do you mean that there is no log entry when you click on the link "Download this PDF file" on the article view page?
Or do you mean there is no log entry when you visit the article view page?

**Comment by atarix83** [comment] 2017-07-19 10:49
@bozana 
yes when I click the link I have no entry log

**Comment by bozana** [comment] 2017-07-19 11:53
Hmmm... This is strange -- for me, locally, there is a log entry... -- I'll take another look...
Have you maybe change anything in OJS code?

**Comment by atarix83** [comment] 2017-07-19 12:30
yes I've done some customization, but I don't think they should be affect this problem.

If can be useful in my debug session I've found that when I click on pdf download link at [this line](https://github.com/pkp/ojs/blob/91d7c72df58c7410806f1009d3ffd82f21a63574/plugins/generic/usageEvent/UsageEventPlugin.inc.php#L223) $args[2] is undefined, while when visit article page is properly setted

**Comment by atarix83** [comment] 2017-08-01 08:37
Hi @bozana sorry for insistence, but I'm still trying to understand more about this problem.

In your opinion, is it possible that using GeoLiteCite database like is described in the [docs](https://github.com/pkp/ojs/blob/ojs-stable-2_4_8/docs/README#L212) could is the cause of my problem?
I've added the database when I've done the upgrade.

Thanks.

**Comment by bozana** [comment] 2017-08-01 09:25
Hi @atarix83, sorry for not responding. You were right -- the fileId parameter is missing for the ArticleHandler::downloadFile hook -- that's why the PDF download was not logged :-( The link to a PR is coming below...
I do not think that GeoLiteCite should be the reason -- it only connects counts with geo location -- the counts should not change.

**Comment by bozana** [comment] 2017-08-01 09:27
PR:
ojs-stable-2_4_8: https://github.com/pkp/ojs/pull/1475

**Comment by bozana** [comment] 2017-08-01 09:30
@atarix83, thanks a lot for finding this!

**Comment by atarix83** [comment] 2017-08-01 09:53
@bozana 

Thank you I'm going to patch immediately

**Comment by bozana** [comment] 2017-08-10 13:10
@atarix83, do you think this solves the problem?

**Comment by atarix83** [comment] 2017-08-28 09:49
@bozana yes now pdf donwload is logged

**Comment by bozana** [comment] 2017-08-28 11:13
@atarix83, thanks a lot! Is also everything else OK now?

**Closed by bozana** 2017-08-28 11:13 UTC

**Comment by atarix83** [comment] 2017-08-28 12:09
@bozana I'll keep track of the statistics of the next months to have a report, thanks
