### ISSUE TITLE
OPS 3.3 - Galleys uploaded to submission but notification says "Awaiting Galleys"

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#6514] opened 2020-12-29 13:36 UTC
I'm testing OPS 3.3. I made a submission as an author and uploaded one PDF galley file. When I log in as a Moderator and view the submission, above the Production tab it says "Notification: Awaiting Galleys." However, when I go to the Preprints tab and Galleys, there is a galley file there.

![Awaiting galleys](https://user-images.githubusercontent.com/35044512/103287583-7919cf00-49a8-11eb-8b8c-d10e18c84fa1.png)

**Comment by NateWr** [comment] 2021-01-12 16:47
I'm not able to reproduce this exactly. When I make a submission, then login as moderator, I see a notification telling me to assign a user to upload a galley. I haven't been able to get the Awaiting Galleys notification to appear. Can you share the URL to the test instance in Slack and I'll see if I can reproduce it there.

I went ahead and removed the production stage notice advising to add a participant to create galleys. I think it's only meaningful in OJS, not OMP. Does that sound right @ajnyga?

PR:
https://github.com/pkp/ops/pull/104

**Comment by ajnyga** [comment] 2021-01-13 10:25
Yes I think it can be removed because you do not have layout editors in OPS.

**Comment by NateWr** [comment] 2021-01-13 10:40
Thanks! I've merved that PR. I'll leave this issue open until we can reproduce and fix the "Awaiting Galleys" message that Amanda found.

**Comment by amandastevens** [comment] 2021-01-21 01:05
I tried this again and I don't see the "Awaiting Galleys" message on the submission. The test site was updated and I had to create all new data.

**Comment by NateWr** [comment] 2021-01-21 10:21
Thanks Amanda! I'll close this for now and we can open a new issue if the problem resurfaces.

**Closed by NateWr** 2021-01-21 10:21 UTC
Labels: Bug
