### ISSUE TITLE
Convert the users grid to a ListPanel that uses the REST API and implement at the context and site level

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#2860] opened 2017-10-11 10:49 UTC
s. https://github.com/pkp/pkp-lib/issues/440

*Edit (2021-11-23) -- This issue is on hold until an invite-a-user feature is implemented. See [this comment](https://github.com/pkp/pkp-lib/issues/2860#issuecomment-388906925).*

**Comment by NateWr** [comment] 2017-10-11 15:33
This should be fairly straightforward once we implement a `/users` API endpoint.

**Comment by NateWr** [comment] 2017-10-27 14:00
I'm going to pre-emptively defer this to 3.2 since it requires a new API endpoint. Ok?

**Comment by asmecher** [comment] 2017-10-27 15:01
Yup, go ahead!

**Comment by NateWr** [comment] 2017-11-03 12:48
Currently the user selection grid returns disabled users when searching for a new participant to assign. This is something that could get fixed when we introduce a `ListPanel` for users.

I'm working on the `/users` API as part of #2965 so that should go some way towards this issue.

**Comment by NateWr** [comment] 2018-04-19 14:38
I've converted the existing users grid to a ListPanel and now I'm looking at implementing the site-wide users list for admins. I've read through #440 and I have a few questions about use-cases and typical data. Can a few of you check my assumptions and answer questions here?

1. The most common use-case is an admin with no context-specific roles who wants to login as a Journal Manager to perform administrative activities (reset password, grant roles, investigate problems, etc).

2. The admin area has no easy route into journal-specific settings. This seems like a broader problem (maybe to be addressed in relation to SaaS features), so I'll leave it for another day.

3. We want a place for site-wide user management, to make it more apparent that the user database is shared across the site. We also think that forcing admins to go into a journal-specific context to manage users is too much of a burden.

4. When thinking of site-wide user management, what does user data look like in a typical multi-journal site? How common is it for a user to have a role in more than one journal? How will admins go looking for users (with information about the journal, the role/user group, with identifying details like name/email)?

5. How much time do we want to invest in the site-wide user management list right now?

Pinging @bozana, @asmecher, @jmacgreg and @mfelczak on this. Anyone else  working with multi-journal installs is welcome to contribute as well.

**Comment by asmecher** [comment] 2018-04-19 17:58
All correct, @NateWr, with just a few comments on point 4 (and implications for point 3). It's impossible to answer that question in a single way; consider the following very different but valid deployments:
- SaaS: Administrator will generally be service provider and will only log in to debug/provide support. Journal managers etc. will probably only be active in one journal and will not want to be reminded that others exist. Journals will often have their own domains, and more than likely their own branding.
- Small publisher. Administrator will probably be the publisher; managers/editors will share a common imprint and will not mind knowing the other journals exist. If the publisher has a specialty, the journals may well share editors, reviewers, authors, and readership.
- Institutional host: Same as above, but less likely that users will be active in several journals.
- And of course the single journal, where the invisible pool of users without any roles is occasionally an annoyance.

**Comment by ajnyga** [comment] 2018-04-19 18:25
Just want to point out that https://forum.pkp.sfu.ca/t/ojs3-editing-user-roles-in-multi-journal-installations/28711 / https://github.com/pkp/pkp-lib/issues/3022 has a lot of requests and is fairly close to this issue.

I do a lot of enrolling for journals as site admin in a multijournal install. For me personally having to go to a context to do that is not a problem, it takes the same amount of time if I do it from within a context or from the site level. But the journal managers are forced to first send us email and then wait for us to do the enrolling for them. So something that could take a couple of seconds turns into taking maybe even a full day. That is the real problem.

To comment 4, at least we seem to have fairly high amount of users registered in several journals. For example we have four journals connected to Finno-Ugric language studies and there are a lot of authors, reviewers and editors working in two or more of them. That is why https://github.com/pkp/pkp-lib/issues/3022 and https://github.com/pkp/pkp-lib/issues/2297 are such big issues.

**Comment by NateWr** [comment] 2018-04-23 16:33
Thanks, that's helpful! A couple more technical questions/assumptions:

1. There will only ever be one `ROLE_ID_SITE_ADMIN` account and that account will have the role assignment on every context?

2. Only `ROLE_ID_SITE_ADMIN` should have access to the site-wide user list?

3. When a user is disabled, they are disabled from all contexts or just the "current" one? If the latter, should disabling from the site-wide context automatically disable from all contexts?

4. An admin should be able to _revoke_ a group assignment for any user. In terms of GDPR, are they allowed to add a group assignment if the user is notified? Should they only have the option to "invite" a user to a new group, and the user must confirm?

5. When a user is merged, this happens for all contexts, right?

**Comment by ajnyga** [comment] 2018-04-23 18:11
My own views:
1. In a multijournal installation it could be handy to have more than one, but not a big deal at least for us. The site admin should have a role assignment in every context, but it would not require things like task notifications for new submissions from every context.

2. Probably a good idea to limit the access for just site admins. 
But for situations where a journal manager wants to enroll a user that is registered to another journal there should be  a clear way of doing that without having the "search from all contexts" selection in the user search. 
I am seeing a process where the journal manager tries to add a new user => "user with same email exists" warning appears => "click here to invite the user to this context with this role". 

3. Is disabling the same thing as removing all user roles? If so, then there should be no site wide disabling unless it means removing users roles from all contexts?

4. Usually the situations where site admins add user roles are either because the user has made a request or another member of an editorial staff has made a request. Especially the latter is probably a grey area. I have to say I really really like the "invite" solution. It also makes sure that no unnecessary user group assignments are being made because the user has to "activate" the assignment. But on the other hand I do think that all systems have a admin user that can do virtually anything and in some cases it could be a feature just to be able to add the role without consent. Can we have both? "Invite to user group" and "add to user group"?

5. The most common case at least for us in user merger is that the user has registered to journal A with one email and to journal B with another email, so I think the "merge users" should definitely happen for all contexts.

**Comment by bozana** [comment] 2018-04-25 14:56
Maybe just one comment on the first item:

> There will only ever be one ROLE_ID_SITE_ADMIN account and that account will have the role assignment on every context?

It is so per default, using the system functions i.e. the only admin user is created at the installation. But there are lots of cases where the users add another "admin" user manually in the DB.

**Comment by NateWr** [comment] 2018-05-02 15:33
I've converted the users grid to a list panel and implemented a new site-wide admin user list.

PRs:
https://github.com/pkp/pkp-lib/pull/3656
https://github.com/pkp/ui-library/pull/18
https://github.com/pkp/ojs/pull/1946
(no OMP yet)

I'll introduce the changes in this lengthy post, but please bear with me. These changes have **significant implications for many of our largest publishers**. First the fun stuff.

Our new users list at Users & Roles > Users:
![userlist](https://user-images.githubusercontent.com/2306629/39530552-22414530-4e21-11e8-93b8-815df0c33252.png)

The expanded view for a user:
![userlist-expanded](https://user-images.githubusercontent.com/2306629/39530657-512e5266-4e21-11e8-8a3c-be5e85121cd2.png)

User groups with `ROLE_ID_SITE_ADMIN` or `ROLE_ID_JOURNAL_MANAGER` are highlighted so site admins can quickly spot them for logging in as:
![userlist-highighted-roles](https://user-images.githubusercontent.com/2306629/39530728-7b2e5084-4e21-11e8-9697-72b76153c17e.png)

And for us devs/site admins, one-click login-as that appears on hover:
![loginas](https://user-images.githubusercontent.com/2306629/39530824-aae530ea-4e21-11e8-9148-d3497b73a94d.gif)

In a journal context, you can filter by status and user group:
![userlist-filters](https://user-images.githubusercontent.com/2306629/39530877-cebbcce0-4e21-11e8-8f21-778e7e0456c6.png)

In the site-wide context, the filters are similar, except you filter by the underlying roles, and it will match users assigned to user groups with that role:
![userlist-admin-filters](https://user-images.githubusercontent.com/2306629/39530957-011201a0-4e22-11e8-84d4-1286a7670745.png)

The list displays the journal acronym to help identify which journal a user group is attached to:
![userlist-admin-roles](https://user-images.githubusercontent.com/2306629/39530998-15a6a88c-4e22-11e8-9c2a-2ef09a5fb4a8.png)

And in the site-wide context, you can filter by context, which uses an autosuggest input field since the list could run into the hundreds:
![userlist-admin-filter-by-context](https://user-images.githubusercontent.com/2306629/39531065-44ef98d8-4e22-11e8-85c9-c00c01e645e5.gif)

The site-wide context complicates user group assignment when adding or editing a user. Since we could have hundreds of journals with a dozen or more user groups each. In the site wide context, we now have an Assign Roles workflow, that has the admin first select a context, and then assign roles (the add user workflow is now a three-step process in the site admin:
![userlist-assign-roles](https://user-images.githubusercontent.com/2306629/39531185-89c86764-4e22-11e8-8182-4bebd3adda15.gif)

And, finally, the list when merging:
![userlist-merge](https://user-images.githubusercontent.com/2306629/39531316-c9d9b2ae-4e22-11e8-8c50-9ec4fbc3bb1e.png)

That's the good news. Now the caveats. This work exposed a lot of questions about how users should be managed across multiple contexts, particularly with the conversations that have been had around SaaS features. I'll post some of those questions in a separate issue. But there are a few things to discuss here:

1. It is no longer possible for a Journal Manager to search for users with no role in the current journal. This seems appropriate, but it means that it is not possible for a Journal Manager to enrol an existing user who is not assigned to their journal. I don't see any way around this that protects the users' privacy, other than to allow Journal Manager's to invite such a user to accept a role in their journal. This is _not implemented_ in the current PR. Is it a must-have? (I'm thinking of some big install admins who may have to take on this load until such a feature exists.)

2. Currently, a Journal Manager can not do anything with a user that has a role in another journal. That makes sense for actions like Enable/Disable. But they can't even send an email, or add/remove roles in their own journal. Was there a reason for this? I'm thinking for some actions, the `Validation::canAdminister($target, $admin)` maybe needs a third option arg for `$contextId`, which would check if the user can administer context-specific things.

3. [Technical] I've implemented [this Vue.js autosuggest component](https://github.com/Educents/vue-autosuggest) which takes WAI-ARIA compliance as it's main selling point. I'm not entirely confident in it, so for the moment I have kept it limited to this use-case. But I haven't seen a similar component which takes WAI-ARIA compliance seriously.

4. [Technical] The autosuggest for contexts loads all the context names and IDs into JS. I've tested this and found it performant up to about 4,000 journals, but I have a fast computer. I'd appreciate it if someone with access to a slow computer could test. I can give you some code to generate up to 1,000. Long term, we'll probably search directly in  a `/contexts` API, but I'm hoping this will do for now without choking anyone's computer.

5. [Technical] I've implemented the journal user list, admin user list, and merging user list all in one ListPanel. It's a bit unwieldy, but separating them out led to a lot of code duplication. It may be worth reconsidering this later as they diverge.

6. [Technical] I left the `UserGridHandler` class around for now, because it's still serving the forms for handling user interactions. When we have a way to integrate Vue.js, forms and our API, I can convert those and get rid of the grid.

7. [Technical] I renamed the `UserAction::mergeUsers` hook to `User::mergeUsers`, to make the UserService hooks consistent. Is that a Bad Idea™?

Phew! We made it! :raised_hands:

**Comment by bozana** [comment] 2018-05-03 09:32
Phew... @NateWr, you are a magician! :-) 
What do you mean with "But they can't even send an email, or add/remove roles in their own journal. " in 2. above?
I can take a look at your PRs -- I would also like to know what is waiting for me when merging with my multilingual user names changes :-) But maybe @asmecher can also take a look from his magician perspective :-)

**Comment by NateWr** [comment] 2018-05-03 09:50
You spoke up, so now you own it! I'll give you the code review, but I've still got tests and things to work through for now.

> What do you mean with "But they can't even send an email, or add/remove roles in their own journal. " in 2. above?

None of the actions in the user list can be performed by a Journal Manager for one journal, when the user has any role in another journal. Example:

1. Person A is a Journal Manager in Journal of Public Knowledge.
2. Person B is a Reviewer in Journal of Public Knowledge and a Reader in Journal of Private Knowledge.
3. Person A does not have permission to send an email or add/remove roles for Person B in their own journal.

This isn't a change that was introduced but appears to be how it works in `master`. All of the `UserGridHandler` actions require the `Validation::canAdminister()` check.

**Comment by asmecher** [comment] 2018-05-04 00:10
@bozana, the phrase that comes to mind is "you bit it, you bought it" :)

@NateWr, on one specific question:
> I renamed the UserAction::mergeUsers hook to User::mergeUsers, to make the UserService hooks consistent. Is that a Bad Idea™?
The Action classes are fossilized and ancient and the code there should be moved elsewhere. I'm not sure `User` is the best place, though -- I think `UserDAO` could be a good home.

**Comment by NateWr** [comment] 2018-05-04 13:58
> I'm not sure User is the best place, though -- I think UserDAO could be a good home.

It's actually in the `UserService` class, not the `User` class itself. The DAO could work, but I think the purpose of a Service class is to organize other DAOs and classes like this, so it seems the best place for it to me.

**Comment by NateWr** [comment] 2018-05-14 17:57
> It is no longer possible for a Journal Manager to search for users with no role in the current journal. This seems appropriate, but it means that it is not possible for a Journal Manager to enrol an existing user who is not assigned to their journal. I don't see any way around this that protects the users' privacy, other than to allow Journal Manager's to invite such a user to accept a role in their journal. This is not implemented in the current PR. Is it a must-have? (I'm thinking of some big install admins who may have to take on this load until such a feature exists.)

After some discussions in the team, we decided invite-a-user (#3022) is a must-have feature alongside these changes, so I'll be working on that in tandem with this.

> Currently, a Journal Manager can not do anything with a user that has a role in another journal.

There was some uncertainty about whether or not this is true. I'll do some further testing in `master` to see if I can reproduce it.

**Comment by NateWr** [comment] 2021-12-15 10:34
The work done on this issue is now obsolete and can't be easily ported forward when the prerequisites are in place. Screenshots of the new design and features can be found in [this comment](https://github.com/pkp/pkp-lib/issues/2860#issuecomment-386020241). I'm closing this for now and a new issue should be opened if/when the users grid is converted.

**Closed by NateWr** 2021-12-15 10:34 UTC
Labels: Enhancement
