### ISSUE TITLE
Multijournal. If i load custom CSS stylesheet, this CSS is loaded in another journals

### ISSUE THREAD

**Issue by gurumelo** [pkp/pkp-lib#6436] opened 2020-11-21 11:23 UTC
**Describe the bug**
OJS 3.2.1-2
Multijournal. If i load custom CSS stylesheet, this CSS is loaded in another journals

**To Reproduce**
Multijournal: 
- Journal 1. default theme
- Journal 2. default theme
- Index. Health Sciences theme

- admin: Dashboard → Administration → Site settings → Appearance → Site style sheet → Load your custom CSS

This CSS is loaded on Journal 1 and Journal 2. It rewrites styles.

Thanks.

**Comment by Vitaliy-1** [comment] 2020-12-06 15:21
Hi @gurumelo,

I've transferred the issue, as it looks like not specific to the Health Sciences theme.
Hmm, I would expect such behavior, I mean apply Site level CSS to all journals on the OJS instance. @NateWr, am I mistaken when thinking that this behavior is implemented deliberately? Also, I think there was a similar topic but can't find any.

**Comment by NateWr** [comment] 2020-12-07 10:50
I recall a discussion about this. I agree that it's not intuitive, but it is the way it has worked for such a long time and has become a part of some people's workarounds. 

For example, some institutional hosts will have a custom footer on all of their journals, and use the site-wide stylesheet to style it. So they expect the site-wide CSS file to work across all sites.

I'm on the fence about whether to change this or not. A workaround can be done by making a small child theme of the Health Sciences theme that load the stylesheet. That approach would only load the stylesheet at the site level.

**Comment by kaitlinnewson** [comment] 2024-10-30 17:59
Closing as duplicate of https://github.com/pkp/pkp-lib/issues/5973

**Closed by kaitlinnewson** 2024-10-30 17:59 UTC
Labels: Enhancement:1:Minor
