### ISSUE TITLE
Implement CRUD API for DOAJ

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#850] opened 2015-10-29 15:59 UTC
See https://doaj.org/api/v1/docs for details.

**Comment by asmecher** [comment] 2016-09-16 23:08
@bozana, I think you were interested in working on this.

**Comment by ajnyga** [comment] 2016-09-27 15:27
@bozana, I was planning of doing something similar as well. Basically I was thinking of taking of course the current DOAJ plugin as a starting point and maybe check the functionality in the Crossref plugin if the automatic deposits function could be used or at least some part of it.

**Comment by bozana** [comment] 2016-09-27 16:44
@ajnyga, great! Yes, I think you could orient yourself on Crossref or DataCite or mEDRA plugin. All of hem share a lot of code/functions and it is similar with DOAJ. Crossref has a slightly different registration -- more complex. When would you start to work on this? I am happy to help!

**Comment by ajnyga** [comment] 2016-09-27 17:56
I already had to postpone this once, but I have it scheduled now for next week. I could perhaps have something ready on Tuesday. I will let you know.

**Comment by bozana** [comment] 2016-10-01 15:46
@ajnyga, I was hoping to work on this on the PKP sprint, that is tomorrow and the day after tomorrow, but lets see if I will be able to or if I will chose to work on another topic. However, I restructured the shared code for those export plugins, s. https://github.com/bozana/ojs/commit/13d513e16affbebba0ea7d2b5e73dcffb02dad0a. Thus, the next and major step would be to implement the depositXML function in DOAJExportPlugin.inc.php, s. https://github.com/bozana/ojs/blob/850fix/plugins/importexport/doaj/DOAJExportPlugin.inc.php#L95.
As far as I could quickly see, the DOAJ API expects a JSON, that has to be constructed. Eventually we could use the filter framework for that, similar to the filter for the export in XML (s. https://github.com/bozana/ojs/tree/850fix/plugins/importexport/doaj/filter), but I am not sure i.e. will have to take a further look.
When you find some time to work on this, please use my 850fix branch (https://github.com/bozana/ojs/tree/850fix) to build on that. If you eventually have some time the next two days, during the sprint, you could participate remotely i.e. we could eventually work together on this. Else, I will keep you informed about any further step I undertake.

**Comment by ajnyga** [comment] 2016-10-02 13:05
Hi @bozana,

I am planning to participate in the sprint. However, due to the time difference it is a bit difficult for me to work at the same time as most of the sprinters. It is 4 already 4 PM here when the work starts in Canada. So, maybe I could suggest the DOAJ API as a project to the sprint in a while and do my work while you guys sleep.

I was just wondering the basic functionality of the plugin. Namely the question when the plugin connects with DOAJ. Should it be automatic once an article is published? Or should it be something that happens only if you go to the export plugin and ask the plugin to send the information to DOAJ?

**Comment by bozana** [comment] 2016-10-02 16:57
Hi @ajnyga, we are both apparently working on other topics during the spring, but that's ok, we can come to this issue any time later :-)
Those export issues, and so DOAJ, provide both options: to register manually, going to the export plugin, and automatically, using a Cron Job i.e. Acron Plugin. I believe we should do step by step and thus first implement the first option -- the second is then just a few minimal additions. The function depositXML would be the function where the connection with DOAJ happens and should thus be implemented next.

**Comment by ajnyga** [comment] 2016-10-03 13:48
I'll just paste here some resources I found
https://github.com/DOAJ/harvester/tree/master
https://github.com/DOAJ/harvester/blob/9b59fddf2d01f7c918429d33b63ca0f1a6d3d0d0/service/tests/fixtures/article.py

**Comment by ajnyga** [comment] 2016-10-04 03:34
I did a pull request on this and will check the JSON next, maybe today already. I have received a permission from one of our journals to use their DOAJ API key to test this.

**Comment by ajnyga** [comment] 2016-10-05 08:19
@bozana, I have been looking how things work in `PubObjectsExportPlugin `and `DOAJExportPlugin`. In `executeExportAction `you have two options: to download an XML file (and upload that at the DOAJ website) or you can use the API. Now the problem is that if you choose to upload your article information to the DOAJ website you need the XML, but if you choose to use the API you need the JSON. 

So, if I understand correctly, we need a filter for the XML which is already there, but besides that we need another filter for the JSON. However, I am not sure if this can be done in `PubObjectsExportPlugin`? I guess `executeExportAction `would then have to be rewritten in `DOAJExportPlugin `so that the `EXPORT_ACTION_DEPOSIT` option there would have a custom filter and other function than `exportXML` outputting `JSON`?

Other option is to convert the already created XML to JSON (bibjson) in `DOAJExportPlugin/depositXML` just before the actual deposit. I actually asked DOAJ already if they would have tools for this already done. We can of course do this ourselves. I guess it would fairly straight forward while there are not that many fields involved, but I do not know whether this is a solution you would want to use here? 

Any thoughts?

**Comment by bozana** [comment] 2016-10-05 13:12
@ajnyga, thanks a lot for all that work! Yes, the export action needs XML and the deposit action needs JSON. I think that we should overwrite the function `executeExportAction`, if the action is `EXPORT_ACTION_DEPOSIT`, and use another filter (that returns JSON) for that. I am not 100% sure, but from a very quick look at JSON that DOAJ expects, it seems that it is a little bit different than the XML? :-(
@asmecher, if we would write a filter that returns JSON, what would be its `output_type`? `primitive::string`?

**Comment by ajnyga** [comment] 2016-10-05 14:39
I have not heard from DOAJ if they would have something. It seems that they have done similar conversions, but with Python: https://github.com/DOAJ/doaj/issues/102

I was thinking how the two filters would work. One solution would be to have something like this in `DOAJExportPlugin`:
> function getSubmissionFilter() {
> 		return array('xml' => 'article=>doaj-xml', 'json' => 'article=>doaj-json');
> 	}
> 
And
> $exportXml = $this->exportXML($objects, $filter['xml'], $context);
> $exportJson = $this->exportJSON($objects, $filter['json'], $context);

But that would probably mean changes in other places as well.

The second solution would be to define the filter in `executeExportAction` after `EXPORT_ACTION_DEPOSIT`.

In both cases we would of course rewrite `executeExportAction` in `DOAJExportPlugin`.

**Comment by bozana** [comment] 2016-10-05 14:48
@ajnyga, lets go with the second solution for now -- to just overwrite/redefine the filter in the `executeExportAction `for `EXPORT_ACTION_DEPOSIT`. Thanks!!!

**Comment by ajnyga** [comment] 2016-10-05 18:35
@bozana, I did another commit and started to implement the JSON filter. However, I am not familiar enough with the filter framework to be sure that the steps I took are to the right direction.

All the other filters seem to use XML so there could be big problems with `exportJSON` I wrote. Even if it works we still need to write the actual filter. When you have time check the pull request I did. If there are no problems, I will proceed on writing the actual filter.

**Comment by dommitchell** [comment] 2016-10-06 09:49
> I have not heard from DOAJ if they would have something.

Did you want me to ask our developers something? What's the question?

**Comment by ajnyga** [comment] 2016-10-06 14:08
Hi, @dommitchell 
I was just asking if DOAJ would happen to have some ready tools for DOAJ XML to BibJSON conversion. But we are probably taking another approach to this where such tool may not be needed.

**Comment by dommitchell** [comment] 2016-10-06 14:24
OK! Let me know if/when we can help!

**Comment by bozana** [comment] 2016-10-06 15:00
@ajnyga, on the first glance everything looks OK. I will not be available and will not have internet till Tuesday but then I will have time for this issue as well. In the meantime, if you would like to proceed, you could maybe implement the function that returns that JSON in the plugin class and try to test it all. And when I am back I will try to figure out and construct that filter, ok? THANKS!!!

**Comment by ajnyga** [comment] 2016-10-13 12:08
@bozana, I am working on this again and will try to get this work to the point where we only need to add the filter. I already have some changes to my original commits and will upload at least those today.

**Comment by bozana** [comment] 2016-10-14 13:17
@dommitchell, I would have one question: how to provide multiple languages (e.g. for title and abstract) in DOAJ JSON? Could you give us an example? Or is this not possible i.e. only one title and abstract should be registered?

**Comment by ajnyga** [comment] 2016-10-14 14:17
@bozana, DOAJ has `"language" : ["EN", "FR"]`  set in this example, but this is related to the journal: https://github.com/DOAJ/harvester/blob/9b59fddf2d01f7c918429d33b63ca0f1a6d3d0d0/service/tests/fixtures/article.py

I have a feeling that DOAJ does not support multilingual metadata for articles?

**Comment by bozana** [comment] 2016-10-14 15:01
Thanks a lot @ajnyga! I also think so -- so I will only provide title, abstract, ... only in the article locale for now.

**Comment by dommitchell** [comment] 2016-10-20 09:56
> I have a feeling that DOAJ does not support multilingual metadata for articles?

Hello, sorry for the delay. This is correct. We can ingest multiple languages but can only display the first one that is present in the xml.

**Comment by bozana** [comment] 2016-10-20 10:01
@dommitchell, but in JSON there is also no possibility to submit multiple titles, just one, right?

**Comment by dommitchell** [comment] 2016-10-20 11:10
Correct.

**Comment by ajnyga** [comment] 2016-11-08 19:23
@bozana, whats the situation with this? If I understood correctly, the filter is pretty much ready.

**Comment by bozana** [comment] 2016-11-09 12:25
@ajnyga, yes, the filter is ready, but I haven't had time to test it properly, i.e. to test the actual registration yet... :-\

**Comment by ajnyga** [comment] 2016-11-09 13:01
Hi,
I could do some basic testing. I have an api key from one of our journals.

**Comment by bozana** [comment] 2016-12-05 15:52
Hi @ajnyga, I finally managed to test the registration and it worked well. I will now make some refinements and cleaning and will then push everything again. If you could then maybe test it as well, it would be great! I will let you know... THANKS!!!

**Comment by ajnyga** [comment] 2016-12-05 18:53
Hi, good to know. I did a couple of test as well around a week ago and everything worked fine at least with the test server. Let me know when you are done cleaning and I will test again. It would be great to have this in 3.0.2

**Comment by bozana** [comment] 2016-12-05 19:48
@ajnyga, I pushed the new version, so it's all yours for testing :-))) /* I squished all the commits into 3, for an easier code review later */

**Comment by ajnyga** [comment] 2016-12-05 20:16
Great, it is a public holiday tomorrow in Finland, but I will take a look on Wednesday.

**Comment by bozana** [comment] 2017-01-20 20:18
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/2214
ojs master: https://github.com/pkp/ojs/pull/1202

**Comment by bozana** [comment] 2017-01-20 20:19
@asmecher, could you code review this?

**Comment by asmecher** [comment] 2017-01-20 22:02
Looks good, @bozana! Some comments -- I'm not sure how feasible the change from arrays to iterators will be, so if it looks like a large amount of work, feel free to defer it to a later bit of development.

**Comment by bozana** [comment] 2017-01-23 17:24
@asmecher, I added most of the changes you suggested, thanks a lot! I created a new issue for the check if I can use iterator instead of array, s. https://github.com/pkp/pkp-lib/issues/2221. And there is one more comment I am not sure about -- the filter display names... THANKS a lot!!!

**Comment by bozana** [comment] 2017-01-24 13:57
Merged, thus closing...

**Closed by bozana** 2017-01-24 13:57 UTC
