### ISSUE TITLE
Re-add sent review request email data into the email log 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#9991] opened 2024-05-28 09:39 UTC
**Describe the bug**
Described on the forum https://forum.pkp.sfu.ca/t/review-request-emails-no-longer-logged-in-ojs-3-4-intentionally/88499

In 3.3, when sending a review request email, the email information was recorded in the `email_log` table. It didn't have a specific `event_type` for that action. 

**To Reproduce**
1. Go to the submission on the review stage
2. Click on `Add Reviewer`
3. Fill the form and send email
4. See the email data wasn't logged in the `email_log` table 

**What application are you using?**
 OJS 3.4, OJS main

**Additional information**

1. Create a submission event type constant, i.e., `SUBMISSION_EMAIL_REVIEW_REQUEST` and `SUBMISSION_EMAIL_REVIEW_REQUEST_SUBSEQUENT`
2. The actual email sending is performed in `PKP\submission\action\EditorAction::addReviewer()`, use `PKP\log\SubmissionEmailLogDAO::logMailable()` to record the data.

**Comment by jim13731** [comment] 2024-07-05 03:41
@Vitaliy-1 Thank you for the sharing the files path.  

I have added functionality to log email data for the "Add Reviewer" action in OJS 3.4. Below are the changes made:

Files Modified
lib/pkp/classes/log/event/PKPSubmissionEventLogEntry.php
lib/pkp/classes/submission/action/EditorAction.php

Changes

1. lib/pkp/classes/log/event/PKPSubmissionEventLogEntry.php

Added new constants for email events: 

`class PKPSubmissionEventLogEntry extends EventLogEntry
{
    // ... existing constants ...

    public const SUBMISSION_EMAIL_REVIEW_REQUEST = 0x50000001;
    public const SUBMISSION_EMAIL_REVIEW_REQUEST_SUBSEQUENT = 0x50000002;

    // ... existing methods ...
}
`
2. lib/pkp/classes/submission/action/EditorAction.php

Modified the addReviewer method to include email logging:

`public function addReviewer($request, $submission, $reviewerId, &$reviewRound, $reviewDueDate, $responseDueDate, $reviewMethod = null)
{
    // ... existing code ...

    if (!$assigned && isset($reviewer) && !Hook::call('EditorAction::addReviewer', [&$submission, $reviewerId])) {
        // ... existing code ...

        // Send mail
        if (!$request->getUserVar('skipEmail')) {
            $context = PKPServices::get('context')->get($submission->getData('contextId'));
            $emailTemplate = Repo::emailTemplate()->getByKey($submission->getData('contextId'), $request->getUserVar('template'));
            $emailBody = $request->getUserVar('personalMessage');
            $emailSubject = $emailTemplate->getLocalizedData('subject');
            $mailable = $this->createMail($submission, $reviewAssignment, $reviewer, $user, $emailBody, $emailSubject, $context);

            try {
                Mail::send($mailable);

                // Log email
                $eventType = ($reviewRound->getRound() == 1) ? PKPSubmissionEventLogEntry::SUBMISSION_EMAIL_REVIEW_REQUEST : PKPSubmissionEventLogEntry::SUBMISSION_EMAIL_REVIEW_REQUEST_SUBSEQUENT;
                $submissionEmailLogDao = DAORegistry::getDAO('SubmissionEmailLogDAO');
                $submissionEmailLogDao->logMailable($eventType, $mailable, $submission, $user);

            } catch (TransportException $e) {
                $notificationMgr = new PKPNotificationManager();
                $notificationMgr->createTrivialNotification(
                    $user->getId(),
                    PKPNotification::NOTIFICATION_TYPE_ERROR,
                    ['contents' => __('email.compose.error')]
                );
                trigger_error('Failed to send email: ' . $e->getMessage(), E_USER_WARNING);
            }
        }
    }
}

Summary

These changes ensure that email data is logged whenever a reviewer is added.`

![image](https://github.com/pkp/pkp-lib/assets/123406238/0b5c2a73-24d0-49dd-b853-42e9cfa842e8)

![image](https://github.com/pkp/pkp-lib/assets/123406238/b6dd4219-6d89-4956-beb1-a7e92f69639b)

**Comment by taslangraham** [comment] 2024-07-20 18:02
@Vitaliy-1 I've created PRs for this. Please take a look.

PRs:
pkp-lib (main) - https://github.com/pkp/pkp-lib/pull/10229
pkp lib (stable 3.4) - https://github.com/pkp/pkp-lib/pull/10230

ojs (main) - https://github.com/pkp/ojs/pull/4373
ojs (stable 3.4) - https://github.com/pkp/ojs/pull/4374

omp (main) - https://github.com/pkp/omp/pull/1651
omp (stable 3.4) - https://github.com/pkp/omp/pull/1652

**Comment by asmecher** [comment] 2024-09-06 19:11
@taslangraham, I've had a report (SciELO) that this is also happening for review reminders, i.e. they are being sent but not logged in the email log. Can you verify and add to the fix as needed?

**Comment by taslangraham** [comment] 2024-09-07 01:59
@asmecher I'll look into it

**Comment by taslangraham** [comment] 2024-09-12 16:46
@asmecher I've identified and applied a fix for the issue you mentioned [above](https://github.com/pkp/pkp-lib/issues/9991#issuecomment-2334664521)

**Comment by asmecher** [comment] 2024-09-12 19:17
Thanks, @taslangraham! Since a couple of templates were missing logging, could you take a bit of a survey of other review related emails to see if it's a wider spread problem? Look in `registry/emailTemplate.xml` for a list of email templates; the relevant ones start with `REVIEW_`.

**Comment by taslangraham** [comment] 2024-09-20 17:14
@asmecher Sorry for the delay. I found a few other reviewer-related emails that were missing logging. I've added logging for them on the pr for main(see [commit](https://github.com/pkp/pkp-lib/pull/10229/commits/6dbcb103dc2ebe2230fc5914b82992e36440d954)). If those all make sense then I'll port it over to 3.4

**Comment by asmecher** [comment] 2024-09-20 17:19
Sounds good, thanks, @taslangraham! In general it's best to code against the stablest branch you're targeting first, then forward-port from there -- that way you're less likely to introduce regressions. But let me know when it's ready for a look.

**Comment by taslangraham** [comment] 2024-09-26 15:07
Ready for review @asmecher. PRs listed [here](https://github.com/pkp/pkp-lib/issues/9991#issuecomment-2241246267)

**Comment by asmecher** [comment] 2024-09-26 15:42
Excellent work, @taslangraham! All merged.

**Closed by asmecher** 2024-09-26 15:42 UTC
Labels: Bug:1:Low, Try Me
