### ISSUE TITLE
Enable editors to send custom email to all authors of a submission

### ISSUE THREAD

**Issue by heike-r** [pkp/pkp-lib#3472] opened 2018-03-13 09:37 UTC
It would be useful if an editor could send an email to the submitting author and all co-authors. We would use this feature to inform authors when their article is published online. Since we use the _publish as you go_ model, the 'new issue published' notification does not suffice. Also, the discussion tool does not work for this, since I can not add co-author email addresses and these co-authors also do not have an OJS account and could not check the discussion. 
In rare cases, we would also use this feature if we have a serious issue with a manuscript such as fraudulent practices and need to inform all co-authors.

**Comment by NateWr** [comment] 2018-03-13 15:36
This is an interesting case to keep in mind when we improve support for publish-as-you-go.

**Comment by NateWr** [comment] 2018-06-04 11:04
Comment from https://github.com/pkp/pkp-lib/issues/3701

> It would be useful to have an email notification to all authors of a submission the moment this submission appears online. We do publish-as-you-go with OJS 3.1.0. This notification would give the authors a closure with the publishing of their work. We currently do this notification via the discussion tool but can only address the submitting author, not the co-authors.The text could be something like this:

The issue contains a sample email.

**Comment by fgnievinski** [comment] 2020-06-22 03:36
a quick & dirty solution would be simply offering a new field for carbon-copy recipients in the author notification dialog:
![image](https://user-images.githubusercontent.com/5018500/85246146-3509a880-b420-11ea-9a25-d82cb7387049.png)

**Comment by fgnievinski** [comment] 2020-06-22 03:45
this issue seems a duplicate of #743

**Comment by NateWr** [comment] 2020-06-22 12:03
I'd like to keep this issue open separately from #743. Yes, we plan on adding support for CC (maybe BCC for some/all users) to emailing _as a general solution_. But we may also want to offer a way to contact all authors in the future -- for example it may be important to get sign-off from authors when we implement CReDIT.

**Comment by NateWr** [comment] 2022-08-04 08:43
Closing this as outdated. If you feel this is still important, please consider making a proposal in the [feature request category](https://forum.pkp.sfu.ca/c/feature-requests/8) of our community forum.

**Closed by NateWr** 2022-08-04 08:43 UTC
Labels: Enhancement:1:Minor
