### ISSUE TITLE
[OJS3] Only tiny area clickable for tick boxes in tasks popup

### ISSUE THREAD

**Issue by pkel** [pkp/pkp-lib#2098] opened 2016-12-14 09:52 UTC
![ojs3-tick-box](https://cloud.githubusercontent.com/assets/11337857/21177227/82394cea-c1ea-11e6-9d8e-d7a9f079aae1.jpg)

The tick boxes which are used to select items for deletion in the tasks notification popup are only clickable in the upper left part.

**Comment by pkel** [comment] 2016-12-14 22:30
This is a test setup. I can provide access, if necessary. Version is 3.0.1

**Comment by NateWr** [comment] 2016-12-19 15:33
Confirmed. Element overlap due to hacky workarounds on the task grid layout.

![tasks-grid-overlap](https://cloud.githubusercontent.com/assets/2306629/21318266/618e4d3c-c600-11e6-964c-b3812dbd3f8d.png)

**Comment by NateWr** [comment] 2017-01-24 16:28
PR:
https://github.com/pkp/pkp-lib/pull/2230

TESTS ONLY:
https://github.com/pkp/ojs/pull/1213

The workaround for this is kinda hacky but I hope it will do for now anyway. Tests running.

**Comment by NateWr** [comment] 2017-01-31 11:24
@asmecher I think this one is pretty much ready to go, but I'm having some trouble with the tests. A couple of them are failing when trying to checkout a submodule:

https://travis-ci.org/pkp/ojs/jobs/194874523#L296
https://travis-ci.org/pkp/ojs/jobs/194874526#L282

It seems inconsistent:

https://travis-ci.org/pkp/ojs/builds/194874520

I've rebased and restarted again, but maybe you know more definitively if this is unrelated?

**Comment by asmecher** [comment] 2017-02-01 18:33
Merged, thanks -- agreed, the test problem isn't related to your change.

**Closed by asmecher** 2017-02-01 18:33 UTC
