### ISSUE TITLE
Author self-selection of categories during submission is not presented

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4864] opened 2019-07-02 19:53 UTC
**Describe the bug**
In OMP 1.1.x, authors could self-select categories on Step 3 of the submission process. The list is not presented anymore as of OMP 3.1.2-1.

See https://forum.pkp.sfu.ca/t/missing-categories-when-author-is-submitting-a-manuscript-omp-3/54422 for details.

## Acceptance Criteria
- [x] When the journal has one or more categories, and as an author I am making a submission, I can select one or more categories for this submission.
- [x] As an editor, can I change the categories of a publication after submission.
- [x] When the journal has no categories, the category selection does not appear in either of the cases mentioned above.

**Comment by tgc** [comment] 2019-07-03 06:43
After applying this, step 3 now shows a blank screen and this error in the log:
```
[03-Jul-2019 08:31:35 Europe/Copenhagen] PHP Fatal error:  Uncaught Error: Class 'PKP\components\listPanels\ListPanel' not found in /srv/omp/omp3-stage/webroot/lib/pkp/classes/submission/form/PKPSubmissionSubmitStep3Form.inc.php:91
Stack trace:
#0 /srv/omp/omp3-stage/webroot/classes/submission/form/SubmissionSubmitStep3Form.inc.php(56): PKPSubmissionSubmitStep3Form->fetch(Object(Request), NULL, false)
#1 /srv/omp/omp3-stage/webroot/lib/pkp/pages/submission/PKPSubmissionHandler.inc.php(126): SubmissionSubmitStep3Form->fetch(Object(Request))
#2 /srv/omp/omp3-stage/webroot/lib/pkp/classes/core/PKPRouter.inc.php(390): PKPSubmissionHandler->step(Array, Object(Request))
#3 /srv/omp/omp3-stage/webroot/lib/pkp/classes/core/PKPPageRouter.inc.php(231): PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(Request), Array, false)
#4 /srv/omp/omp3-stage/webroot/lib/pkp/classes/core/Dispatcher.inc.php(134): PKPPageRouter->route(Object(Request))
#5 /srv/omp/omp3-stage/webroot/lib/pkp/classes/core/PKPApplication.inc.php(252): Dispatcher->dispatch(Object(Request))
#6 /srv/omp/ in /srv/omp/omp3-stage/webroot/lib/pkp/classes/submission/form/PKPSubmissionSubmitStep3Form.inc.php on line 91
```

This is with php 7.3.6.

**Comment by NateWr** [comment] 2019-07-03 10:37
@tgc what version of OMP are you running?

**Comment by tgc** [comment] 2019-07-03 12:49
We're running 3.1.2. Since the bugreport in the forum was explicitly about 3.1.2 I assumed the patch could be applied to 3.1.2.

**Comment by NateWr** [comment] 2019-07-03 13:13
That's a reasonable assumption! :+1: 

In this case, the commit is against `master` and there have been some changes to the related component between the stable version and our `master` branch. @asmecher will probably port it to stable at some point in the near future.

**Comment by NateWr** [comment] 2019-07-03 13:34
On a separate note: I have pegged this agains 3.2 and assigned to the versioning project. The submission form will need to be updated to save categories against the publication, not the submission.

**Comment by asmecher** [comment] 2019-07-04 23:20
PR for master (notwithstanding @NateWr's notes above):
- https://github.com/pkp/pkp-lib/pull/4865

I'll see if this can be quickly back-ported to `stable-3_1_2`.

**Comment by asmecher** [comment] 2019-07-04 23:26
@tgc, here is an equivalent PR back-ported to the `stable-3_1_2` branch (e.g. for OJS 3.1.2-1): https://github.com/pkp/pkp-lib/pull/4897

Please confirm whether that helps; if so, I'll commit it for the next 3.1.2-x release.

**Comment by tgc** [comment] 2019-07-05 09:15
@asmecher Thank you. #4897 works and is exactly what we need.

**Comment by asmecher** [comment] 2019-07-09 01:53
Merged or 3.1.2-2, thanks, @tgc! Leaving open for 3.2.

**Comment by jmacgreg** [comment] 2019-10-23 19:17
Hi @NateWr, @asmecher, I've tested this against master, and items 1 and 3 work as expected. Item 2 is a little wonky though - if I enable categories, the following happens: 

1) if I _don't_ select a category when I submit an article, the Category option does NOT appear in the Publication tab; 
2) if I _do_ select a category when I submit an article, the Publication tab displays as follows, and is more or less broken: 

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/201446/67426433-1957b500-f5a8-11e9-9b6b-124ac6e13bc7.png">

I can provide a link to the system and server access if you like. I'm not seeing anything in the error log, FYI.

**Comment by NateWr** [comment] 2019-10-24 09:52
Thanks @jmacgreg! I'll investigate the first item further. With the second one, it looks like you're in the Author Dashboard. The work on the author dashboard is almost but not yet merged (#4877).

**Comment by jmacgreg** [comment] 2019-10-24 14:04
Hi Nate - thanks, I didn't catch that. And it turns out that I think everything is good here. Since I didn't catch the fact that I was on the author dashboard, I thought what I saw was an attempt to insert a new tab into the Publication metatab - I didn't realize that Categories were available from the Journal Entry tab. I can confirm now that: 

Regarding issue 1) - I do indeed see Category options, under Journal Entry; 

Regarding issue 2) - I can indeed update these as an editor. 

So all the issues here are checked off - I think this can be closed, but will leave to you for confirmation.

**Comment by jmacgreg** [comment] 2019-10-24 14:04
Ah jeez, and there I go pressing "Close and comment" instead of "Comment"

**Comment by NateWr** [comment] 2019-10-24 14:25
Feel free to close an issue if it's passed all acceptance criteria. :+1:

**Closed by NateWr** 2019-10-24 14:25 UTC
