### ISSUE TITLE
setLocale ignores source parameter if HTTP_REFERER exists

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#1116] opened 2016-02-04 15:11 UTC
See: http://forum.pkp.sfu.ca/t/ojs-may-be-rejecting-url-from-an-outside-website/7721

OJS 2.x prefers an HTTP_REFERER over the passed in source parameter when switching locales.  If a user specifies the source parameter as a redirect target, it should be honored.

Blindly trusting the HTTP_REFERER is risky.  If the referrer was this OJS system, it makes sense to send the user back to the referring page if no source is specified.  If the referrer was an external system, it is unlikely the link was really intended to redirect back to the external system.

**Comment by asmecher** [comment] 2016-02-04 18:38
@ctgraham, I can't think OTOH of a way to abuse this. It's intended to have the "set locale" operation bounce back to the OJS page it was invoked from.

**Comment by ctgraham** [comment] 2016-02-04 18:40
I don't mean risky in a sense of security.  I mean risky in a sense of unexpected consequences.

I don't think it's an abuse vector... just a WTF vector.

**Comment by asmecher** [comment] 2016-02-04 18:41
Ah, OK. Thanks for the fix!

**Comment by mfelczak** [comment] 2019-01-11 22:19
Re-opening for inclusion in OJS 3.x/OMP 3.x

**Comment by asmecher** [comment] 2019-01-15 21:48
Merged https://github.com/pkp/pkp-lib/pull/4356 and back-ported to `stable-3_1_2`. Thanks, @mfelczak!

**Comment by ctgraham** [comment] 2019-02-08 21:07
@mfelczak, this change seems to direct me from the application's user navigation languages to the JSON response instead of refreshing the current page with the new locale.

E.g.: in `ul#navigationUser > li.languages`, the link:
`/ojs/index.php/index/user/setLocale/en_US?source=%2Fojs%2Findex.php%2Findex%2F%24%24%24call%24%24%24%2Fpage%2Fpage%2Fuser-nav-backend%3F_%3D1549659289091`
results in the UA being redirected to:
`/ojs/index.php/index/$$$call$$$/page/page/user-nav-backend?_=1549659289091`

**Comment by mfelczak** [comment] 2019-02-13 21:12
@asmecher, re-opening ahead of the 3.1.2 release

@ctgraham, is this via the site-level language switcher?

**Comment by ctgraham** [comment] 2019-02-14 13:28
Yes, it is.

**Comment by mfelczak** [comment] 2019-02-19 18:18
@asmecher, please ignore the last commit, that was a WIP. Any suggestions for how we could limit the source redirect to only public-facing pages? ATM, the previous fix works for the front-end language switcher but breaks the back-end language switcher as per Clinton's last msg, i.e.

![screen shot 2019-02-19 at 1 17 02 pm](https://user-images.githubusercontent.com/200793/53037653-bde98c00-3448-11e9-8a39-75e6ac9baf07.png)

vs

![screen shot 2019-02-19 at 1 17 18 pm](https://user-images.githubusercontent.com/200793/53037665-c80b8a80-3448-11e9-9bed-3fdf783ba04e.png)

**Comment by asmecher** [comment] 2019-02-19 22:26
@mfelczak, the problem is that the `usernav.tpl` template is referring to `$smarty.server.REQUEST_URI` (which is $_SERVER['REQUEST_URI']`) to determine the page to redirect the user to. Since the back-end navigation is generated via an AJAX sub-request, the URL to that sub-request is what it's getting, not the URL to the entire page. I'd suggest removing the `source=...` URL parameter from that template entirely, e.g.:

```
diff --git a/templates/header/usernav.tpl b/templates/header/usernav.tpl
index 555e81f..4e59631 100644
--- a/templates/header/usernav.tpl
+++ b/templates/header/usernav.tpl
@@ -96,7 +96,7 @@
 				{foreach from=$supportedLocales item=localeName key=localeKey}
 					{if $localeKey != $currentLocale}
 						<li>
-							<a href="{url router=$smarty.const.ROUTE_PAGE page="user" op="setLocale" path=$localeKey source=$smarty.server.REQUEST_URI}">
+							<a href="{url router=$smarty.const.ROUTE_PAGE page="user" op="setLocale" path=$localeKey}">
 								{$localeName}
 							</a>
 						</li>
```

**Comment by mfelczak** [comment] 2019-02-21 22:27
Thanks @asmecher!

PRs:
master: https://github.com/pkp/pkp-lib/pull/4527
stable-3_1_2: https://github.com/pkp/pkp-lib/pull/4528

**Comment by asmecher** [comment] 2019-02-21 23:05
All merged -- thanks, @mfelczak!

**Closed by asmecher** 2019-02-21 23:05 UTC
Labels: Bug
