### ISSUE TITLE
Assigned articles missing from future issues after upgrade to OJS 3.3.0-8

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#7266] opened 2021-09-07 20:35 UTC
**Describe the bug**
After the upgrade from OJS 3.1.2 to OJS 3.3.0-8, previously assigned articles to future issues are no longer assigned to the issues. All future issues show 0 items.

**To Reproduce**
1) Assign articles to future issues
2) Upgrade OJS from 3.1.2 to 3.3.0-8
3) Go to Issues > Future Issues
4) All future issues show 0 items

**What application are you using?**
 OJS 3.3.0-8

**Additional information**
For journals that don't publish frequently, article re-assignment to future issues can be manually redone as a workaround. For journals that publish many articles and prepare many future issues across several editors manual re-assignment is more difficult.

This looks to have been reported earlier in the [forum](https://forum.pkp.sfu.ca/t/after-upgrading-from-3-1-1-4-to-3-2-0-3-no-items-in-future-issues/61333) with the OJS 3.2.x upgrade process.

**Comment by NateWr** [comment] 2021-09-08 10:40
I think this is a hangover from the introduction of article _scheduling_? From 3.2, an article can be assigned to an issue but not scheduled for publication. In such cases, the article will show as assigned in the publication tab, but not from the issue UI.

The reason here is that it's possible for someone to assign a submission to an issue early in the editorial workflow. That submission will then appear if someone filters the submission lists by issue. But if the issue is published the submission won't be published with it, unless it's been explicitly scheduled for publication. The publish validation checks are completed and the status in the database is changed to `STATUS_SCHEDULED`.

I had a look at the code, and we do not modify the submission status during the 3.2 upgrade migration. We can introduce this change for upgrades from 3.1.x, but we need to think carefully about whether this will have any negative impact.

1. Setting a submission to `STATUS_SCHEDULED` during upgrade will mean that it has not passed the publishing validation checks, which check that the submission is in the copyediting or production stages and is not declined ([pkp-lib](https://github.com/pkp/pkp-lib/blob/main/classes/publication/Repository.inc.php#L257-L274). In OJS there is an additional payment check ([ojs](https://github.com/pkp/ojs/blob/main/classes/publication/Repository.inc.php#L116)). Nothing in OMP and OPS not effected.
2. Once a submission is scheduled for publication, it's publication details are locked. Editors will need to go in and unschedule it to make changes.

I'm trying to think of other potential negative consequences, but none come to mind. If I recall, in 3.1.x, assigning a submission to an issue was effectively scheduling it for publication. Is that right? If so, I think we can do the following:

- [ ] Apply `STATUS_SCHEDULED` to submissions AND publications during upgrade when a submission is: a) assigned to an issue, b) has `STATUS_QUEUED`, c) in the copyediting or production stages.
- [ ] Apply the migration script only for upgrades from < 3.2. We can only assume issue assignment means a submission is ready to publish for versions before 3.2. Once a journal is running 3.2, we can't make this assumption.

@mfelczak is this something that PS could take on?

**Comment by mfelczak** [comment] 2021-09-08 21:57
Yes, @ewhanson is currently working on the outstanding OJS 2.x to 3.2.x supp file upgrade issue and should be able to tackle this alongside that work.

**Comment by ewhanson** [comment] 2021-12-07 00:32
Hi @NateWr, could you have a look at these PRs? I've tested it both on `main` and `stable-3_3_0` using both MySQL and Postgres and didn't come across anything out of the ordinary. Thanks!

PRs:

`main`: pkp/ojs#3243
`stable-3_3_0`: pkp/ojs#3244

**Comment by asmecher** [comment] 2021-12-13 20:36
I've added datasets for OJS 3.1.x; see e.g.: https://github.com/pkp/datasets/tree/main/ojs/3.1.0

**Comment by ctgraham** [comment] 2022-01-07 16:21
I've also successfully tested the patch from pkp/ojs#3244 on 3.2.1 under mysql.

**Comment by asmecher** [comment] 2022-01-07 17:21
Thanks, all! I think the next step is an OK from @NateWr?

**Comment by NateWr** [comment] 2022-01-10 12:30
Looks good to me! @ewhanson I'm happy to merge this in but will wait for a final OK from you in case anything has changed since you posted the PRs.

**Comment by ewhanson** [comment] 2022-01-10 16:26
Thanks, @NateWr. Nothing's changed on my end. All ready to go from me.

**Comment by NateWr** [comment] 2022-01-10 16:28
Merged to `stable-3_3_0` and `main`. :tada:

**Closed by NateWr** 2022-01-10 16:28 UTC
Labels: Hosting, Bug
