### ISSUE TITLE
OJS 3.3 doesn't upload the images properly 

### ISSUE THREAD

**Issue by salmanm2003** [pkp/pkp-lib#6195] opened 2020-08-19 14:49 UTC
Hi,
I am trying to upload few images in:
```Website settings > appearance > setup > logo```
but I cannot see them in the db which means that the form is not uploading them properly.
Any ideas about this.

I am using:
 OJS 3.3.0

Regards
Salman

**Comment by asmecher** [comment] 2020-08-19 18:18
@salmanm2003, OJS 3.3.0 hasn't been released yet -- are you trying to use this in a production environment?

**Comment by salmanm2003** [comment] 2020-08-19 19:25
> @salmanm2003, OJS 3.3.0 hasn't been released yet -- are you trying to use this in a production environment?

Hi @asmecher,
It is for testing env, as I am building a new plugin compatible with ojs 3.3.0 using custom uploading file fields and thought it might be good to point out the issue.

**Comment by asmecher** [comment] 2020-08-20 00:02
Gotcha, @salmanm2003, just making sure :+1:

**Comment by NateWr** [comment] 2020-08-20 09:45
I'm unable to reproduce this myself. I'll close this issue for now but follow up with @salmanm2003 directly. We can reopen it if we discover it's reproducible.

**Closed by NateWr** 2020-08-20 09:45 UTC
Labels: Bug
