### ISSUE TITLE
Add integrity checks before upgrade process

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#3351] opened 2018-02-06 17:35 UTC
Add some checks to be executed before running an upgrade, in order to provide better guidance for common upgrade failures.
- Running upgrade script when `installed` is `on` (Should this be tolerated another way?)
- A partial upgrade has failed; restore from backup
- Review rounds duplicate entries
- Section ID missing from articles
- ... others?

**Comment by ajnyga** [comment] 2018-02-06 17:49
- submissions or any other data linked to a context that does not exist anymore (https://forum.pkp.sfu.ca/t/solved-upgrading-3-0-2-to-3-1-01-movereviewerfiles-fails/37278)
- submission_files linked to submissions that do not exist anymore
- missing default genres (https://github.com/pkp/pkp-lib/issues/2506)

**Comment by asmecher** [comment] 2018-02-07 03:52
See https://forum.pkp.sfu.ca/t/how-to-check-if-you-db-is-ready-for-ojs3/37746/5 for a suggested query on the review rounds dupe check.

**Comment by marcbria** [comment] 2018-02-08 11:58
If this is very OT or crazy suggestion, let me know, but what about letting upgrade.inc.php make a backup of your journal before starting touching things? At least, a DB backup... 

I know is not our fault (is commented in UPGRADE indications and in the forum, an a sysadmin needs to know this is a must for every system) but I have pain in my soul thinking in those that run the script without a backup.

**Comment by marcbria** [comment] 2018-02-14 09:03
If you get a warning like this:
`"WARNING: Unable to find a match for "478-959-1-RV.rtf" in "/var/www/files/journals/1//articles/478/". Skipping this file."
`
Probably the problem it's not just the pointed file... it could be a general issue caused by missing all files in your private files folder.

BTW, upload.php is not really skipping the file. It asks for the same file in a infinite loop.

**Comment by marcbria** [comment] 2018-02-14 12:39
I found other situations where this error raises:
- https://forum.pkp.sfu.ca/t/ojs-3-0-upgrade-fails-to-move-rename-some-supplementary-files/20520
- https://github.com/pkp/pkp-lib/issues/1924
- https://forum.pkp.sfu.ca/t/ojs-2-4-8-to-3-0-2-upgrade-error/32687

Possible error rephrasing with an interactive question.
`"WARNING: Unable to find "/var/www/files/journals/1//articles/478/478-959-1-RV.rtf". **Check the file and the permissions.** (S)kip this file, (R)etry or (C)ancel the upgrade operation?."

**Comment by asmecher** [comment] 2018-02-19 17:36
> BTW, upload.php is not really skipping the file. It asks for the same file in a infinite loop.

What version have you tried with? I think this infinite loop situation was resolved in the current release.

**Comment by marcbria** [comment] 2018-02-20 10:28
The last one released: 3.1.0.1

**Comment by asmecher** [comment] 2018-02-20 19:33
>>> BTW, upload.php is not really skipping the file. It asks for the same file in a infinite loop.

>> What version have you tried with? I think this infinite loop situation was resolved in the current release.

> The last one released: 3.1.0-1

Are you sure it's OJS 3.1.0-1 and not OJS 3.1.0-0? This should have already been fixed by https://github.com/pkp/pkp-lib/issues/2942 (the solution added [this single line of code](https://github.com/pkp/ojs/blob/d3518404b36e61d9d4a3bb07284bae7bf6ff6ddf/classes/install/Upgrade.inc.php#L117)).

**Comment by marcbria** [comment] 2018-02-20 21:15
Pretty sure... :-)

1) It's what docker-compose says:
`    image: marcbria/docker-pkp-ojs:ojs-stable-3_1_0-1

2) To be sure, I rised the container and checked inside running this:
```
$ cat docs/README | grep Version
=== Version: 3.1.0-1
```

So yes... It's a 3.1.0-1

I checked the patched file (classes/install/Upgrade.inc.php) this is what I found:
```
                                        // No filenames matched. Skip migrating.
                                        error_log("WARNING: Unable to find a match for \"$globPattern\" in \"" . $submissionFileManager->getBasePath() . "\". Skipping this file.");                            $fileResult->MoveNext();
                                        continue;
```

**Comment by asmecher** [comment] 2018-02-21 17:59
@mtub, is that around line 115, or around line 982? Around line 115, OJS 3.1.0-1 should include a call to `$fileResult->MoveNext()`, but I don't see it in the code you've quoted.

**Comment by marcbria** [comment] 2018-02-22 01:06
It's around 115, as in the patch you pointed in former post.
Move the horizontal scrollbar and you will find the milling call to MoveNext() method.
This is why I say that "A new line is missed, but code looks fine".

**Comment by asmecher** [comment] 2018-02-22 16:15
Per issue 3412, all results for this query should be deleted:

    SELECT n.notification_id FROM notifications n LEFT JOIN announcements a ON (n.assoc_id = a.announcement_id) WHERE a.announcement_id IS NULL AND n.assoc_type = 522;

**Comment by marcbria** [comment] 2018-02-26 12:28
Not sure if it's an infinite... same error, asking for same file appeared 100 times before I stopped the process. ;-) 

If you like I can send you a tarball with the DB and the files, but it's around 1GB.

**Comment by bozana** [comment] 2018-03-02 14:56
It happen ones that revised_file_id is the same as review_file_id for an article: SELECT * FROM articles WHERE revised_file_id = review_file_id

**Comment by marcbria** [comment] 2018-03-05 12:52
@asmecher forget about the infinite loop. As bozana pointed, it was related with an issue in my DB.

BTW, issues to test are mixed in this tread. I created a titanpad to keep them sorted:
https://pad.riseup.net/p/ojs3-upgrade-integrity-checks

Extend or modify the list if you like.

**Comment by jmacgreg** [comment] 2019-10-17 16:25
Consider also checking for some common systems misconfigurations: 

- "mysql" instead of "mysqli" driver when upgrading to a PHP7-requiring install
- files_dir is web-accessible (soft check, not a blocker - we can't account for all systems configurations, some of which will require the files_dir to be in the web root and made inaccessible in other ways)
- secret keys/salts? 
- missing or obsolete config.inc.php parameters?

**Comment by marcbria** [comment] 2019-10-18 11:58
Adding some thoghts in terms of security list:
- File checking: Nextcloud implements "file integrity check" that warns (or blocks upgrade) if you have unknown files in the app folders. 
- Permissions: I know we have a lot of different scenarios, but may be we can improve the folder/file permission checking (even adding a "fixPermissions.sh" script).
- Installation wizard security page: It's just about "how it looks" but been explicit with the security check phase (for instance, with a specific page during installation) will show we are taking security seriously.
- Banner showing security warns: Show in admin's pages a "your system is not secure" banner with the list of patches to apply to be up to date.

**Comment by NateWr** [comment] 2021-12-09 10:53
A pattern for pre-flight checks on an upgrade was added as part of #6093. See https://github.com/pkp/pkp-lib/blob/main/classes/migration/upgrade/v3_4_0/PreflightCheckMigration.inc.php. Further improvements should be filed separately in new issues.

**Closed by NateWr** 2021-12-09 10:53 UTC
Labels: Enhancement
