### ISSUE TITLE
Categories aren't saved for new submissions in OMP

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#9405] opened 2023-10-12 17:53 UTC
**Describe the bug**
A client reported that assigned category editors were not being assigned to new submissions or notified in OMP. I created several test submissions and noticed that the stage and notification assignment code in PKPSubmissionsStep4Form for categories ws not running, and  the categoryIds publication_setting for these submissions was empty:

![Screenshot at 2023-10-12 14-44-43](https://github.com/pkp/pkp-lib/assets/218719/22069aeb-7055-46f1-a281-deb28d189118)

Looking at the first form in the wizard,  series are being read from the form but not submitted category information:

https://github.com/pkp/omp/blob/stable-3_3_0/classes/submission/form/SubmissionSubmitStep1Form.inc.php#L93

and it looks like the Publication object is only being updated with this as well:

https://github.com/pkp/omp/blob/stable-3_3_0/classes/submission/form/SubmissionSubmitStep1Form.inc.php#L123

Once a submission is made, the chosen categories are not set in the Publication area of the workflow:

![Screenshot at 2023-10-12 14-51-28](https://github.com/pkp/pkp-lib/assets/218719/42fe149f-bf59-4838-8408-1181ff453295)

**To Reproduce**
1. Create some categories in OMP
2. Create a submission and choose at least one of these categories
3. Submit the submission and then edit as a Manager.  They will not be present.

**What application are you using?**
OMP 3.3.0.15

**Comment by jnugent** [comment] 2023-10-12 18:13
After some more review I see that the parent class of the first form in lib/pkp does seem to perform work with categories.  They are still not being saved though.

**Comment by jnugent** [comment] 2023-10-13 12:50
Some further research on this. Categories are indeed being read off of the form of Step 1 in the submission wizard.  The form does get into this loop:

https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php#L424

However, the `CategoryDAO` is not putting the categories in the `publication_categories` table as expected. I created another test record, submission 14, and this is the submission record in the `submissions` table after saving step 1:

![Screenshot at 2023-10-13 09-43-16](https://github.com/pkp/pkp-lib/assets/218719/f8342bea-8aa5-463c-9d87-796e231ad62b)

Based on that, I should have categories  in the `publication_categories` table for a publication with an id of 14.  I do not:

![Screenshot at 2023-10-13 09-43-33](https://github.com/pkp/pkp-lib/assets/218719/041e353f-35cc-4bd5-9fd9-d50f2a67597c)

I do, however have an empty `categoryIds` setting for publication 14 in the `publication_settings` table:

![Screenshot at 2023-10-13 09-41-40](https://github.com/pkp/pkp-lib/assets/218719/f43c882d-faad-45ce-8073-c19509f93f69)

So, it sounds like either the `CategoryDAO` save isn't working as expected, or else it is and then it's being reset elsewhere in the step 1 process.  These screenshots are after saving step 1, with no further work being done on the submission.

**Comment by jonasraoni** [comment] 2023-10-19 20:29
@asmecher here's a small PR (looks like it's ok in 3.4, but I had another issue while I was testing)
- https://github.com/pkp/omp/pull/1477
- https://github.com/pkp/pkp-lib/pull/9432

**Comment by jnugent** [comment] 2023-10-19 21:09
Hi everyone, confirming that @jonasraoni 's fix here solves the problem.  It does lead to another conversation about what the CategoryDAO is doing in this form since it doesn't look like the publication_categories table is part of all of this now.

I know this bug was marked as low priority but it's actually a big deal since if categories are not saved in the submission wizard, the category editor is never assigned nor notified of the new submission.

**Comment by asmecher** [comment] 2023-10-19 21:17
@ajnyga, could you review this? It looks like it's related to https://github.com/pkp/pkp-lib/issues/5694.

**Comment by ajnyga** [comment] 2023-10-20 11:37
Hi,

Storing data with CategoryDAO to the publication_categories table dates back to 2019 https://github.com/pkp/pkp-lib/commit/718ad72e597285d2899932efbd1d87635b90efe7

My changes were not about selecting categories but about automatically assigning submissions based on them. Of course it could be that the changes broke something.

However, what I could not yet figure out is why I can not reproduce this in OJS 3.3. There the data is correctly stored to publication_categories and the assignments work as well. So for me it looks like a OMP issue, but the fix above applies to pkplib?

**Comment by ajnyga** [comment] 2023-10-20 11:46
@jonasraoni I can see that you fix does work. Can you figure out why it worked before that change in OJS 3.3?

The other issue here is what @jnugent referred to. The data is now stored both to `publication_settings` as an array named categoryIds and to the `publication_categories` table. 

I can see that in OJS 3.3 the data was being store correctly to the `publication_categories` table but also an empty categoryIds was stored to `publication_settings`. I think that is something that just went unnoticed when the Publication object was introduced back in 2019.

**Comment by jnugent** [comment] 2023-10-20 11:46
Hi @ajnyga 

I wondered why this did not affect OJS 3.3 also.  I noticed that the SubmissionStep1 form in both OJS and OMP repositories do things a bit differently.  The OMP version of the form has an `execute` method where as the OJS version does not.  The OMP `execute` method edits the Publication object to set the seriesId, where as the OJS version of the form sets the seriesId via the `setPublicationData` method.  Is there a reason for doing this differently in each application?  Can this possibly explain why OMP is not getting categories set?

**Comment by ajnyga** [comment] 2023-10-20 11:49
Probably it is due to differences in SubmissionStep1, but could not understand yet why. Why they are different is just probably something that has happened over time and no one put in the effort to minimize the differences. I think in 3.4 they are overhauled anyway?

**Comment by jonasraoni** [comment] 2023-10-20 11:52
The problem is here:
https://github.com/pkp/omp/blob/7c8030265e241c8652959b4208bb7aaeeaf2476b/classes/submission/form/SubmissionSubmitStep1Form.inc.php#L123-L128

The `Services::get('publication')->edit()` uses the `getData('categoryIds')` from the publication, which at this point is empty.

**Comment by jonasraoni** [comment] 2023-10-20 11:54
Yeah, for me it doesn't make sense to store the same data in two places, I didn't check, but I hope it has been fixed in 3.4.

**Comment by ajnyga** [comment] 2023-10-20 11:54
(In 3.4 I could not figure out how to select Categories in the Wizard at all :)

**Comment by jonasraoni** [comment] 2023-10-20 13:07
I was taking a look in 3.4, and this field became an auto-complete with fixed values:
![image](https://github.com/pkp/pkp-lib/assets/361921/c4003d15-db2c-4387-b72c-b20bd61fe36e)

**Comment by jonasraoni** [comment] 2023-10-20 13:41
Hmm, on OPS it's different, maybe it's based on the number of items 😁
![image](https://github.com/pkp/pkp-lib/assets/361921/2178cd86-089d-4b4a-a2b3-cacb85ef28bc)

**Comment by ajnyga** [comment] 2023-10-20 16:04
Were you able to select categories also in OJS 3.4?

**Comment by jonasraoni** [comment] 2023-10-20 18:04
@ajnyga Yep, I've just checked on the [OJS 3.4 test drive](https://ojs34.testdrive.publicknowledgeproject.org/), and it worked 👌

FYI I've merged the PR, and created another issue to handle the data unification here (just to not delay this important fix): https://github.com/pkp/pkp-lib/issues/9448

**Closed by jonasraoni** 2023-10-20 18:04 UTC
Labels: Hosting, Bug:2:Moderate

**Comment by ajnyga** [comment] 2023-10-20 18:17
Ok thanks! Yes I can see it is working on the test drive with stable 3.4. With the current main branch of OJS I did not see the Categories though.
