### ISSUE TITLE
[OPS] Link to published paper (version of record) in Crossref/Datacite metadata

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#7283] opened 2021-09-13 19:39 UTC
**Describe the problem you would like to solve**
Currently the Crossref/Datacite metadata does not contain a link to the published paper (version of record) of a preprint, making it difficult for metadata holders to know the relationship between a preprint and its version of record.

**Describe the solution you'd like**
Link a preprint to its version of record in the DOI metadata.

**Who is asking for this feature?**
Authors, Server Admins, Journals

**Additional information**
bioRxiv does it. 
Example: https://www.biorxiv.org/content/10.1101/2020.08.10.245241v5
[DOI Metadata](https://api.crossref.org/v1/works/10.1101/2020.08.10.245241).

**Comment by NateWr** [comment] 2021-09-14 10:18
@ajnyga just checking to see if this has been implemented already in the Crossref export plugin. I have a vague memory of you working on something like this before.

**Comment by ajnyga** [comment] 2021-09-14 10:23
Yes, most of this is ready here https://github.com/pkp/ops/pull/103 I think there are a couple of open issues in the pr, I will check them this week.

**Comment by NateWr** [comment] 2021-09-14 14:17
Looks like this is a duplicate of https://github.com/pkp/pkp-lib/issues/6251. I'm closing this in favor of that issue.

**Closed by NateWr** 2021-09-14 14:17 UTC
Labels: Enhancement
