### ISSUE TITLE
When refusing submission the screen does not update

### ISSUE THREAD

**Issue by matheusotoni** [pkp/pkp-lib#6270] opened 2020-10-06 22:21 UTC
When refusing a submission, the screen is not updated, you need to reload the page with F5 so that the status of the submission appears to the user.

Follow the steps to reproduce the behavior:

1. Access the administration of a magazine
![image](https://user-images.githubusercontent.com/13783007/95265622-e5e95700-0807-11eb-96ec-e9249e12364a.png)

2. Enter the submissions menu
![image](https://user-images.githubusercontent.com/13783007/95265678-0d402400-0808-11eb-989a-a23880f7998a.png)

3. Edit a submission
![image](https://user-images.githubusercontent.com/13783007/95265765-44163a00-0808-11eb-8263-c23fc0764082.png)

4. Reject a submission
![image](https://user-images.githubusercontent.com/13783007/95265832-6445f900-0808-11eb-96c4-80889004e781.png)

![image](https://user-images.githubusercontent.com/13783007/95265906-85a6e500-0808-11eb-912a-2b47121fe2a8.png)

5. The page does not load after clicking the button
![image](https://user-images.githubusercontent.com/13783007/95265977-a66f3a80-0808-11eb-8c7e-be2fa0c6f564.png)

6. If the user updates the page, the status appears changed
![image](https://user-images.githubusercontent.com/13783007/95266117-f3eba780-0808-11eb-8df0-23a54629d09d.png)

**What application are you using?**
 OJS version 3.2.0-3

**Comment by NateWr** [comment] 2020-10-08 11:02
I was unable to reproduce this in OJS 3.2.1. Can you try updating your instance (or set up a test instance with 3.2.1) and see if you can reproduce the problem? I think we may have worked on this recently but can't remember precisely what version got the fix.

Here are the steps I took:

1. Create a submission.
2. View the submission and go to the Submission stage.
3. Click decline and confirm the decline.

When I did this, the page reloaded to update the view without me doing anything.

I'm going to close this as already fixed, but if you can reproduce this in 3.2.1 I'll be happy to reopen it to investigate further.

**Closed by NateWr** 2020-10-08 11:02 UTC
