### ISSUE TITLE
Recommend-only option disappears when looking for editors to assign 

### ISSUE THREAD

**Issue by kshuttle** [pkp/pkp-lib#7894] opened 2022-04-28 16:16 UTC
**Describe the bug**
Some section editors can make decisions even though the role setting is turned on for them to only make recommendations. It seems to happen when assigning a section editor if there is a need to click “Load More” in the list of names.

**To Reproduce**
In a journal that has recommendation-only abilities turned on in the role settings for section editors:
1. Go to a submission, assign a participant, and look at list of section editors. Notice that the role settings appear, including the setting (checked off) for section editors to make recommendations only.
2. If the list of section editors is long, you'll need to click "load more" to see names further down the list. Notice that the role settings disappear
3. Assign a section editor to assign from further down the list (after "load more"). This section editor can make decisions rather than recommendations only on the submission.

**What application are you using?**
OJS 3.3.0.8

**Additional information**
<img width="260" alt="Ska_rmavbild 2022-04-26 kl  16 25 50" src="https://user-images.githubusercontent.com/59741486/165797830-abdd4517-bc99-4ca3-b5a3-4243441b3a43.png">
<img width="294" alt="Ska_rmavbild 2022-04-26 kl  16 26 42" src="https://user-images.githubusercontent.com/59741486/165797835-6026cf01-785f-4a10-a189-e0b5867ea473.png">

**Comment by withanage** [comment] 2022-08-26 06:48
Locally tested on Chrome and FF in 3.3.0-11   with the same workflow described by @kshuttle and the issue seems to be fixed and @kshuttle   confirms the workflow steps are as described in the issue .

@NateWr shall we then close the issue  and re-open if needed?

[Demo](https://user-images.githubusercontent.com/1921992/186838999-f00a17e3-a925-4143-9d46-3fa0eeadb8b2.mp4)

**Comment by NateWr** [comment] 2022-08-29 11:16
@withanage I notice that you select a user before you click Load More. Can you double-check this with the following order?

1. Click Assign Participant
2. Select Section Editor
3. Click Search
4. Click Load More
5. Then see if the field goes away?

**Comment by NateWr** [comment] 2022-08-29 11:21
Yeah I was able to reproduce this only when I clicked on one of the entries that was shown _after_ I clicked Load More. And only if I did this _first_. Once I click one of the earlier users, the field showed up.

**Comment by withanage** [comment] 2022-08-29 12:09
@NateWr  thanks for looking. I was also able to reproduce as you described. Will  try to  find the cause.

**Comment by withanage** [comment] 2022-08-31 22:37
Hi @NateWr ,

Could you have a look at the follwing  PRs?

PKP-lib
- https://github.com/pkp/pkp-lib/pull/8229

OJS
- https://github.com/pkp/ojs/pull/3527

**Comment by NateWr** [comment] 2022-09-01 08:38
Merged to `stable-3_3_0` and cherry-picked to `main`. Thanks @withanage!

**Closed by NateWr** 2022-09-01 08:38 UTC
Labels: Bug:1:Low
