### ISSUE TITLE
The review form’s result is displayed in one line

### ISSUE THREAD

**Issue by 01Kuzma** [pkp/pkp-lib#9337] opened 2023-09-28 12:23 UTC
The review form works fine. It’s created with select, radio buttons and other elements.

But there is an issue, once the author opens the provided review form all provided data is displayed in one line! Without any breaks, it ignores all formatting and HTML elements!

The review is placed in

```
<div class="email_entry">
```
div element.

OJS 3.3.0.8 version

**To Reproduce**
1. Login as author
2. Open the review form
3. See error

As I can’t show the real review text, I’ve swapped the text with “Lorem”

This is how it looks:
![image(1)](https://github.com/pkp/pkp-lib/assets/569504/62059084-437f-4799-aac4-8105f27d1619)

**Comment by asmecher** [comment] 2023-11-11 02:45
Duplicate of https://forum.pkp.sfu.ca/t/the-review-forms-result-is-displayed-in-one-line/81764.

**Closed by asmecher** 2023-11-11 02:45 UTC
