### ISSUE TITLE
When using multilingual inputs, it is not clear which language goes in which field

### ISSUE THREAD

**Issue by jalperin** [pkp/pkp-lib#2763] opened 2017-09-01 17:32 UTC
When using a multi-lingual input, there is no clear indication of which language goes in which form. I found this confusing on first pass. 

The assumption is that the language of the UI is on top, which is logical, but probably needs to be made explicit somehow. 

![screenshot 2017-09-01 10 27 31](https://user-images.githubusercontent.com/129638/29980943-b2abb988-8f00-11e7-8b3c-1ac7e310387d.png)

**Comment by asmecher** [comment] 2017-09-01 18:18
Dupe of https://github.com/pkp/pkp-lib/issues/2556

**Closed by asmecher** 2017-09-01 18:18 UTC
Labels: UI/UX Review
