### ISSUE TITLE
announcements types cannot be removed OJS 3.3.0-3

### ISSUE THREAD

**Issue by promedacademy** [pkp/pkp-lib#6791] opened 2021-02-25 07:19 UTC
**Describe the bug**
on the admin dashboard announcement section , announcement types , cannot delete or edit announcement types after creation with message access denied 
**To Reproduce**
1. Go to 'dashboard- announcement- announcement type'
2. Click on 'edit or remove'
3.See  access denied 

**What application are you using?**
 OJS,  version 3.3.0-3

**Additional information**
code of the section `<a href="#" id="component-grid-announcements-announcementtypegrid-row-1-remove-button-6036bd756a067" class="pkp_controllers_linkAction pkp_linkaction_remove pkp_linkaction_icon_delete" disabled="disabled">Remove</a>`

Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by NateWr** [comment] 2021-02-25 15:29
I was not able to reproduce this. Can you tell me what roles the user has that you are logged in as?

**Comment by promedacademy** [comment] 2021-02-25 16:45
Admin user as journal  manager  with full permissions

**Comment by NateWr** [comment] 2021-02-25 18:03
I was logged in with the same role and I could not reproduce this. You'll need to check your error log or try to discover the conditions under which it happens so that we can reproduce them.

**Comment by asmecher** [comment] 2021-02-25 18:17
This may have already been resolved here: https://github.com/pkp/pkp-lib/issues/6748#issuecomment-778557739

**Comment by NateWr** [comment] 2021-03-01 08:56
Great, closing this as fixed.

**Closed by NateWr** 2021-03-01 08:56 UTC
