### ISSUE TITLE
Lack of notifications after the author uploads revisions

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6643] opened 2021-01-20 19:50 UTC
**Describe the bug**
During the review stage, there was no notification warning about new revisions uploaded by the author.

**To Reproduce**
After reaching the review stage, upload a revision using the author role, then log in as a manager/editor/reviewer and there will be no new notifications.

**What application are you using?**
OJS 3.3

**Comment by NateWr** [comment] 2021-01-21 12:55
Can you provide more specific reproduction steps? What notifications did you expect to appear that didn't? What editorial actions were taken in the review stage before or after the revisions were uploaded?

**Comment by jonasraoni** [comment] 2021-01-22 08:17
Here I'm not sure if/what notifications should appear here (I was going to inspect the code to get a clue, but didn't), this is the description of my assignment: "Notifications update when revisions uploaded by author".

**Comment by NateWr** [comment] 2021-01-25 11:05
Can you try to reproduce this and let me know specific reproduction steps? Especially the order of editor decisions , which editor decisions are taken, and what steps you take as an author?

**Comment by asmecher** [comment] 2021-01-30 01:37
@jonasraoni, I'm deferring this to 3.3.0-1 because we're releasing 3.3.0 shortly, but if you're able to include reproduce steps ASAP that'll help!

**Comment by jonasraoni** [comment] 2021-01-30 20:08
I've forgotten the steps, so I've re-executed everything after pulling some updates 👀
1. Logged in with all accounts using private tabs/different browsers.
2. Author: Created a submission
3. Manager: Assigned an editor to the submission
4. Manager: Sent to review
5. Manager: Assigned reviewer
6. Reviewer: Sent review
7. Editor: Requested revision
8. Author: Sent revision + uploaded new files

At this point I was expecting to receive notifications in the profile of the manager/editor: "The author has sent a revision", but I didn't...

ps: In fact, I've tried more times while I was writing the line above and got 1 notification :)

I didn't inspect much, but looks like the notification isn't sent if I'm just "replacing" a file (it didn't reach my breakpoint at the `PKPSubmissionFileService::add`, which is the only place I saw the email `REVISED_VERSION_NOTIFY`)...
Only inserting a new file ("This is not a revision of an existing file") triggered my breakpoint, but the email wasn't sent due to [recipient validations](https://github.com/pkp/pkp-lib/blob/master/classes/services/PKPSubmissionFileService.inc.php#L416).

**Comment by bozana** [comment] 2021-02-02 15:42
PR: https://github.com/pkp/pkp-lib/pull/6706

**Comment by bozana** [comment] 2021-02-02 15:47
@NateWr, could you please take a look? -- I believe this was the problem i.e. what @jonasraoni meant. The notification did not change from "Revisions have been requested. ' to 'Revisions have been submitted.'.
Eventually another (minor) thing left: the notifications changes in the UI only after the page reload. Should this be different? I am not sure I would know to fix that, but... maybe with your help... :-)

**Comment by NateWr** [comment] 2021-02-03 09:38
Good catch @bozana! Can you also backport it to the `stable-3_3_0` branch?

> Eventually another (minor) thing left: the notifications changes in the UI only after the page reload. Should this be different?

Maybe in an ideal world, but unless there's a regression from when it was working in 3.2.x, I wouldn't worry about it. Typically the author will upload revisions so the editor's UI won't need to change, and if the editor uploaded revisions at least they'll know what happened.

**Comment by bozana** [comment] 2021-02-03 21:32
everything merged, so closing...
@jonasraoni, if this is not solving your problem, please reopen...

**Closed by bozana** 2021-02-03 21:32 UTC
Labels: Bug
