### ISSUE TITLE
Error 404 when addNavigationMenuItem

### ISSUE THREAD

**Issue by EmuAGR** [pkp/pkp-lib#3403] opened 2018-02-19 12:04 UTC
Version: 3.1.0-1 (upgraded from 2.4.8-2)

Steps to reproduce:
1. Create a new navigation item, remote URL.
2. Save.

Console throws error 404 Not Found when POST to this GET:
component=grid.navigation-menus.navigation-menu-items-grid&op=update-navigation-menu-item

PHP message: PHP Warning:  assert(): Assertion failed in /home/xxx/www/lib/pkp/classes/core/PKPComponentRouter.inc.php on line 179

It seems OJS has some kind of problem with the operation "update-navigation-menu-item". This forum post is related: https://forum.pkp.sfu.ca/t/navigation-menu-items-in-ojs-3-1/35154/4

P.S. Also, in the Spanish (Spain) translation of this menu, the strings are too long and the UI breaks.
Edit: Adding the menu entries to the DB manually works as expected.

**Comment by defstat** [comment] 2018-02-20 08:38
@EmuAGR 
- Could you attach a print-screen with the UI (that is broken due to the long locale)?
- Is the problem you are reporting only happening when trying to save a "remote url" navigation menu item?

**Comment by EmuAGR** [comment] 2018-02-20 20:13
Thank you for your quick reply, I'll try to test the backend fix later. In the meantime, this is the screenshot you requested:
![ojscreen](https://user-images.githubusercontent.com/4166199/36446734-8bf08ec2-1682-11e8-8b13-7f8b13d2bc2c.png)

**Comment by defstat** [comment] 2018-02-20 20:42
@EmuAGR How did you install OJS? Did you download the code through GitHub? If yes, which branch?

**Comment by EmuAGR** [comment] 2018-02-20 20:46
It was the stable release 3.1.0-1, AFAIK. Do you recommend installing from source instead?

**Comment by defstat** [comment] 2018-02-20 20:49
No, it just seems like a javascript issue. If you have not done that already, could you clear the cache and try again? Could you check if you get any javascript errors?

**Comment by EmuAGR** [comment] 2018-02-20 20:55
I already cleared all the caches, and I don't get any JS error when loading that menu.

**Comment by defstat** [comment] 2018-02-20 21:13
Thank you. Do you get any errors on your browser console? Like build.css or build.js missing, or any other?
Furthermore, could you tell me the contents of [ojs-root-folder]/js and [ojs-root-folder]/styles? (not including inner folder contents.)

**Comment by EmuAGR** [comment] 2018-02-20 21:19
Nope, no errors. As you requested:
$ ls js/
build.js  controllers  load.js  pkp.min.js
$ ls styles/
build.css  citationEditor.less  index.less

**Comment by defstat** [comment] 2018-02-20 21:25
Thank you! Can you send your PHP version and whether you get any PHP errors, apart from the getPath() one? Are you on site level or on journal level when you are getting the UI issue?

**Comment by EmuAGR** [comment] 2018-02-20 21:44
PHP 5.6

But I don't get that getPath() error, just the warning from assert() when I try to POST a new item, I still have to apply the fix though. From the JS issue there isn't any error.

**Comment by EmuAGR** [comment] 2018-02-21 01:00
The styling issue was fixed when I migrated the website from a nginx+CloudFlare installation to an Apache one, maybe something was wrong with my nginx settings. Next I'll try to apply the fix to the menu.

**Comment by defstat** [comment] 2018-02-21 05:32
@EmuAGR Nice! Can you try whether the webserver change helps on the other issue you have, without apply the patch?

**Comment by EmuAGR** [comment] 2018-02-21 05:43
It didn't work for the 404 issue.

**Comment by defstat** [comment] 2018-03-05 17:37
@EmuAGR Any news on that?

**Comment by EmuAGR** [comment] 2018-03-05 17:56
Hi, sorry for spacing out. Is there an easy way to apply all the little commits of the fix in one single patch? If there isn't, I'll do it manually.

**Comment by EmuAGR** [comment] 2018-03-06 11:02
I replaced
 	templates/controllers/grid/navigationMenus/form/navigationMenuForm.tpl
 	templates/controllers/grid/navigationMenus/form/navigationMenuItemsForm.tpl
with the latest version from master, but the problem persists. When I save the changes made in the form, I still get a 404 error.

**Comment by defstat** [comment] 2018-03-08 19:30
@EmuAGR I am not sure about the state of your code right now. Please replace the above mentioned 3 files with the originals of your code base. 

Could you please tell me whether the problem happens at the site level or at the journal level?

**Comment by EmuAGR** [comment] 2018-03-08 19:39
Returning them back to 3.1.0-1 . I have only one journal in my site, so I can't really tell.

**Comment by defstat** [comment] 2018-03-08 20:08
@EmuAGR Thank you. Unfortunately, downloading the code from https://pkp.sfu.ca/ojs/ojs_download/ I can not reproduce the 404 error. Could you somehow send me your code base in order to try to reproduce it? You could zip the code folder from your server, and send that somehow?

**Comment by defstat** [comment] 2018-03-09 19:49
@EmuAGR If it's OK with you I am closing the issue for now, but please feel free to send me your code base in order to check the problem you are facing.

**Comment by tfluhr** [comment] 2018-03-15 21:32
Hi there.

We are experiencing a very similar issue with our OJS instance.  We're not able to edit existing website settings (settings->website->navigation menus).

I've attached of the console and edit window pop up.

We are running v 3.1.0.1 and php v 5.6.34-1+ubuntu14.04.1+deb.sury.org+1

Any help would be appreciated!

Thanks.

-tim

![console](https://user-images.githubusercontent.com/35077186/37492053-d68a6730-286d-11e8-877a-189d0747c367.PNG)
![edit_popup](https://user-images.githubusercontent.com/35077186/37492054-d6976048-286d-11e8-9c4b-c2f9990ad2fe.PNG)

**Comment by tfluhr** [comment] 2018-04-09 19:16
Hi. 

We're still experiencing this issue. I have been able to edit nav menus by querying the database directly but still can not edit them through the UI.

Is there any additional info I can provide to help troubleshoot this?

Thanks!

-tim

**Comment by EmuAGR** [comment] 2018-05-31 01:14
While I was testing restful_urls, I got and endless redirection loop. I've been looking for a fix for that, and I read that setting "disable_path_info = Off" (since I had it enabled for nginx) would do the trick.

This change didn't fix the endless loop, but it fixed this issue at last! :)

**Comment by defstat** [comment] 2018-05-31 04:37
@EmuAGR Thanks for sharing that! 

I will check for inconsistencies regarding that setting. 

Thanks!

**Comment by EmuAGR** [comment] 2018-05-31 07:16
This also seems to have fixed a "create reviewer" problem where the corresponding settings didn't show after pressing the button. I think the button triggered a 404 error, but I don't remember well.

**Comment by asmecher** [comment] 2018-08-29 20:34
@defstat, yes, that makes sense to me.

**Closed by asmecher** 2018-08-29 20:34 UTC
