### ISSUE TITLE
No current issue when current issue is unpublished

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2267] opened 2017-02-07 10:57 UTC
If the current issue is unpublished, but another issue exists, the current issue doesn't get set. Going to the Current Issue page displays nothing and the Current Issue isn't displayed on the homepage, even though issues exist in the archive.

**Comment by asmecher** [comment] 2017-02-08 21:47
We should make it possible to choose which issue is current. See e.g. http://forum.pkp.sfu.ca/t/order-of-publishing-issues-i-e-current-i-ojs-3x/28452.

**Comment by NateWr** [comment] 2017-02-09 09:25
Do Issues have published dates? If so, can we use that? If not, should they?

**Comment by asmecher** [comment] 2017-02-22 23:34
Issues do have publication dates, but they're stamped when the issue is published in the workflow, and I suspect they won't reliably reflect the issue's _actual_ publication date for many users. See e.g. http://forum.pkp.sfu.ca/t/sorting-issues-by-year-ojs-3-0-2-0/28879.

**Comment by defstat** [comment] 2017-03-10 11:12
I can see two approaches to that:
1. We could change the https://github.com/pkp/ojs/blob/master/classes/issue/IssueDAO.inc.php#L239 function to reflect the same order of issues as the https://github.com/pkp/ojs/blob/master/classes/issue/IssueDAO.inc.php#L579 function. we could call the https://github.com/pkp/ojs/blob/master/classes/issue/IssueDAO.inc.php#L579 function and get the top 1 issue from the response. 
Not sure if we need to change the current flag in the issues table too. Is so, we could call the https://github.com/pkp/ojs/blob/master/classes/issue/IssueDAO.inc.php#L261 as soon as we find the top 1 issue. 

2. We could give the user a way (a popup maybe) upon unpublishing the "current" issue, to check another one as "current". But that way we can not be sure that the user will indeed make the selection.

**Comment by asmecher** [comment] 2017-03-11 00:15
Another option would be to add a row action in the issue lists ("current issues" / "back issues") allowing the user to pick an issue from the grid and set it "current".

**Comment by defstat** [comment] 2017-03-11 10:58
@asmecher PR #1310

I think that there is a problem with the refresh function of the grid. I get a Javascript error

Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.jQuery.parseJSON (jquery.js:8517)
    at Object.success (TabHandler.js:278)
    at fire (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at done (jquery.js:9310)
    at XMLHttpRequest.callback (jquery.js:9720)

when 'unpublish' and 'setCurrent' functions are returned. I will try to fix it.

**Comment by asmecher** [comment] 2017-03-13 22:44
That PR is https://github.com/pkp/ojs/pull/1310.

**Comment by asmecher** [comment] 2017-03-14 15:53
Merged -- thanks, @defstat!

**Closed by asmecher** 2017-03-14 15:53 UTC
Labels: Critical Issue
