### ISSUE TITLE
Adding reviewer does not include required country field for created user.

### ISSUE THREAD

**Issue by ewhanson** [pkp/pkp-lib#7310] opened 2021-09-21 01:19 UTC
**Describe the bug**
When a reviewer is created via `ReviewerForm.inc.php` or `CreateReviewerForm.inc.php`, the newly created user is never assigned a country, which leads to a fatal PHP error when trying to localize the user's country, e.g. `PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Sokil\IsoCodes\Database\Countries::getByAlpha2() must be of the type string, null given` as identified in [forum post](https://forum.pkp.sfu.ca/t/uncaught-typeerror-argument-1-passed-to-sokil-isocodes/69862).

**To Reproduce**
1. Go to the review workflow stage of a submission.
2. Add reviewer and create new reviewer.
3. Attempt to access created user anywhere country would be localized.
4. See error above.

**What application are you using?**
 OJS 3.3.0-7

**Comment by withanage** [comment] 2022-08-23 08:53
I have checked this failure OJS 3.3.0-11 on both PHP 7.4 and PHP 8.0 and could not reproduce  this erro.
Database has a empty string in the field and also setting a null  manually did not allow reproducing it.

Asked the user in [form#69892](https://forum.pkp.sfu.ca/t/uncaught-typeerror-argument-1-passed-to-sokil-isocodes/69862/4)  to clarify again.

**Comment by withanage** [comment] 2022-08-24 11:43
Hi @asmecher and @NateWr ,

The base-lying problem for the above error was that the country was not an mandatory field. I adde a PR for that for review.

pkp-lib
- https://github.com/pkp/pkp-lib/pull/8196

OJS
- https://github.com/pkp/ojs/pull/3504

**Comment by NateWr** [comment] 2022-08-24 13:17
I'm not sure if we want to make country a required field for reviewers. I think the person who creates the reviewer user will often not know that information. I'd prefer to solve this problem by not trying to localize a country that doesn't exist.

**Comment by withanage** [comment] 2022-08-24 13:39
Was thinking that too, just implemented, cause was a small addition. Would you recommend  setting an empty string explicitly, as the user suggests? I tried  reprouding the error with the null set as in the current impmlementation , but  couldn't in both 7.4 or 8 as the user describes here and asked him to calrify [form#69892](https://forum.pkp.sfu.ca/t/uncaught-typeerror-argument-1-passed-to-sokil-isocodes/69862/4)

**Comment by NateWr** [comment] 2022-08-24 13:59
The error message that they posted does not appear to be related to reviewers. It's related to a search request variable here:

https://github.com/pkp/ojs/blob/fd6dac4c83a5e1ab5d0ec3a35c188f3e1c2db6b2/pages/search/SearchHandler.inc.php#L206

We should fix this by checking if `$country` is not empty before calling this line:

https://github.com/pkp/ojs/blob/fd6dac4c83a5e1ab5d0ec3a35c188f3e1c2db6b2/pages/search/SearchHandler.inc.php#L276

**Comment by withanage** [comment] 2022-08-25 07:19
Hi @NateWr ,

Updated the PR to validate the input variable. Could you have a look ?

- https://github.com/pkp/ojs/pull/3509

**Comment by NateWr** [comment] 2022-08-25 08:37
Merged to `stable-3_3_0`. The related code has been removed from the `main` branch so nothing was ported over. Thanks @withanage!

**Closed by NateWr** 2022-08-25 08:37 UTC
Labels: Bug:1:Low
