### ISSUE TITLE
Missing multilingual values not being added to REST API responses

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#6153] opened 2020-08-06 15:25 UTC
**Describe the bug**
When a multilingual property is returned in the REST API, if it is not set, the API should return an object containing empty values based on the schema. So a multilingual string should return:

```
{
  en_US: '',
  fr_CA: ''
}
```

This is handled by PKPSchemaService::addMissingMultilingualValues(). But for some reason it was not working with the affiliation, leading to #6151.

**To Reproduce**
1. Add a user without an affiliation
2. Inspect the API response for that user.
3. It should have `affiliation` as an object with each supported locale. Instead it is `null`.

**What application are you using?**
3.3 (`master` pre-release)

**Comment by touhidurabir** [comment] 2023-06-16 14:49
I think this has been resolved by some other commit as I could not reproduce it . both for the `stable-3.3.0` and `main` . For `stable-3.3.0` 
```json
"affiliation": {
  "en_US": "",
  "fr_CA": ""
}
```
and for `main`
```json
"affiliation": {
  "de_DE": "",
  "en": "",
  "fr_CA": "",
  "pt_BR": "",
  "pt_PT": ""
}
````

**Comment by asmecher** [comment] 2023-06-16 23:21
Thanks, @touhidurabir! I couldn't reproduce this either.

**Closed by asmecher** 2023-06-16 23:21 UTC
Labels: Housekeeping:1:Todo
