### ISSUE TITLE
Custom Page can't be saved if disable_path_info is set to on

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#4413] opened 2019-02-01 13:34 UTC
OJS version: 3.1.1-4
To reproduce:
in config.inc.php: `disable_path_info = On`
`Settings -> Webiste -> Navigation Menus -> Add item -> Custom Page -> Save`

Browser's console output on my test instance:
```
Request URL: http://ojs-3.1.1-4.test/index.php?journal=psp&component=grid.navigation-menus.navigation-menu-items-grid&op=update-navigation-menu-item
Request Method: POST
Status Code: 404 Not Found
Remote Address: 127.0.0.1:80 
```
Nothing related in the PHP error log.
Related to: https://forum.pkp.sfu.ca/t/cant-add-item-custom-page-to-navigation-menu-items-in-3-1-1-4/51067

**Comment by asmecher** [comment] 2019-02-01 16:31
The issue is the use of a parameter called `path`, which is reserved for the router when `disable_path_info` is turned on. This appears in a few forms...

- `plugins/generic/staticPages/templates/editStaticPageForm.tpl`
- `lib/pkp/templates/controllers/grid/settings/category/form/categoryForm.tpl`
- `lib/pkp/templates/controllers/grid/navigationMenus/form/navigationMenuItemsForm.tpl`
- `templates/admin/contextSettings.tpl`

**Comment by asmecher** [comment] 2019-02-01 17:08
@defstat, the reqiured change is https://github.com/asmecher/pkp-lib/commit/87a132a5c6767fb9997915bae9c7783e608ec19d -- but I'd like your confirmation that this was actually dead code. I can't find it used anywhere and suspect it was from an earlier iteration of the custom nav menu item form.

**Comment by asmecher** [comment] 2019-02-15 17:29
Closing, thanks!

**Closed by asmecher** 2019-02-15 17:29 UTC
