### ISSUE TITLE
OMP 3.3 Unable to grant reviewer access to Files for review

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#6538] opened 2021-01-06 20:40 UTC
**Describe the bug**
If a press manager forgets to select files for review during the intitial request, they are unable to grant reviewers access to these (as well as additional files)

**To Reproduce**
1. Send Reviewer request (without files by accident)
2. Click on blue Reviewer name
3. Click edit 
4. Select files and press save
5. Return to edit screen, files are unselected again

**What application are you using?**
OMP 3.3 r2

**Additional information**

https://user-images.githubusercontent.com/50342731/103817798-3ac18700-501c-11eb-8c57-1fb6987f4405.mp4

**Comment by asmecher** [comment] 2021-01-06 22:37
This is a duplicate of https://github.com/pkp/pkp-lib/issues/6540 (i.e. the fix there resolves this as well) -- but thanks as always for the comprehensive reports!

**Closed by asmecher** 2021-01-06 22:37 UTC
Labels: Bug
