### ISSUE TITLE
[OJS] ORCID Profile Plugin prevents article publication

### ISSUE THREAD

**Issue by mabere** [pkp/pkp-lib#5572] opened 2020-03-01 04:47 UTC
After successfully installing fresh ojs 3.2.0 I created future issues, I try to publish one issue but the circle icon keep loading for long time (not stop).
![Screenshot_2020-03-01 Issues](https://user-images.githubusercontent.com/29719586/75619742-5b29e500-5bb2-11ea-9310-c9618cb0623b.png)

[Edit: One cause for this is the ORCID Profile Plugin as released with OJS 3.2.0/3.2.0-1. It still references `PublishedArticleDAO`, as noted here: https://github.com/pkp/pkp-lib/issues/5572#issuecomment-604047918]

**Comment by asmecher** [comment] 2020-03-01 17:44
Hi @mabere -- check your PHP error log for details.

**Comment by alexxxmendonca** [comment] 2020-03-02 12:53
it must be due to the option to send a notification e-mail.

depending on the number of users you have, this might take a long time,

We've been having some big problems with that, to the point of reaching gmail's daily quota, causing all e-mails to cease sending. We are advising journals to uncheck that box before publishing an issue.

**Comment by KarwanJacksi** [comment] 2020-03-25 19:45
Hi,
I now have the same problem, the PHP log file says
_`ojs2: Unrecognized DAO PublishedArticleDAO!`_

**Comment by asmecher** [comment] 2020-03-25 19:59
@KarwanJacksi, I don't think this is the same issue, but turn on the `show_stacktrace` option in `config.inc.php` and try again. The error message should include more information.

**Comment by KarwanJacksi** [comment] 2020-03-25 20:04
Hi @asmecher ,
It is already on, but does not show anything, I try to publish an issue but the circle icon keeps loading, and when I check PHP log file it gives me that..

**Comment by asmecher** [comment] 2020-03-25 20:07
@KarwanJacksi, try disabling the ORCID Profile plugin and see if that helps.

**Comment by KarwanJacksi** [comment] 2020-03-25 20:10
OMG!
That was the problem! It is working now and the issue is published!
Many thanks @asmecher  :)

**Comment by defstat** [comment] 2020-03-27 16:56
@asmecher @NateWr 

The PR ports OrcidProfile plugin to v3.2

**PR**
[orcidPlugin]: pkp/orcidProfile#102

**Comment by withanage** [comment] 2020-03-30 19:30
Hi @alexxxmendonca  and @KarwanJacksi 

This issue is fixed by the  plugin release  v1.1.2-1 from  30.03.2020

**Comment by alexxxmendonca** [comment] 2020-03-30 19:42
Hi @withanage,

thanks!

How can I upgrade it?

![image](https://user-images.githubusercontent.com/4059679/77954694-6ea99800-72a5-11ea-90ff-3019fbfd8414.png)

**Comment by withanage** [comment] 2020-03-30 19:45
Hi @alexxxmendonca ,
I see your version is 3.1.2,  The ticket  problem refers to 3.2.0+  or did you also have it in 3.1.2 ?

**Comment by alexxxmendonca** [comment] 2020-03-30 19:47
@withanage my mistake!

Will wait for when we upgrade to 3.2.0+.

Thanks!

**Comment by defstat** [comment] 2020-04-01 14:01
Can we close that issue?

**Comment by withanage** [comment] 2020-04-01 14:10
I think yes. I have tested it in OJS 3.2.0  and OPS 3.2.0

**Comment by asmecher** [comment] 2020-04-01 17:18
Thanks, all!

**Closed by asmecher** 2020-04-01 17:18 UTC
