### ISSUE TITLE
Unexpected redirect produced by the LOCKSS gateway plugin.

### ISSUE THREAD

**Issue by mjordan** [pkp/pkp-lib#4275] opened 2018-11-30 14:32 UTC
Alexandra Ohlson at Stanford reports

> [...] the expected manifest url redirects back to the journal index page for the journal.  I’m not sure if this is a symptom of not having tried to turn on LOCKSS support [...] or if this is some other issue. These are all 3.1.x sites. 

I can get some examples from her if that would help.

**Comment by asmecher** [comment] 2018-11-30 16:59
@mjordan, marking this a duplicate of https://github.com/pkp/pkp-lib/issues/1908 -- essentially that code hasn't been maintained since the OJS 3.x update, and needs an overhaul.

**Closed by asmecher** 2018-11-30 16:59 UTC
