### ISSUE TITLE
Test the database migration to split submissions and publications

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#4856] opened 2019-07-02 17:07 UTC
Significant database changes will be introduced in 3.2 that split data from the submissions out into publications. We need to test these changes on a diverse set of installations, with different publishing models, plugins and settings, to ensure data is getting moved properly.

Upgrade tests should be run from stable installations using the versioning branches described here: https://github.com/pkp/pkp-lib/projects/15#card-23489465

Things to check for after running an upgrade:

- [ ] All keys stored in `submission_settings` should be moved to `publication_settings`. If you think there should be an exception, let me know.
- [ ] Authors should be assigned correctly to publications instead of submissions.
- [ ] Galleys should be assigned correctly to publications instead of submissions.
- [ ] Content in plugins that relates to submissions should relate to publications _if_ it is related to the public data of an article/monograph.

The following content has not yet been migrated so should not be expected to work after updating:

- cover images

The following content _should_ be migrated but has not been tested at all:

- [ ] DOIs and other pub ids
- [ ] category assignments

When testing, you can look directly in the database to make sure the content has been ported. You should also see it in the API, and the following endpoints will help you test the content:

```
/submissions
/submissions/{submissionId}
/submissions/{submissionId}/publications
/submissions/{submissionId}/publications/{publicationId}
```

From there, you should be able to see that every piece of data that existed before the upgrade is available. If it is related to the workflow, it should be attached to the submission object. If it is related to the public data of an article/monograph (title, abstract, metadata, authors, galleys) it should be attached to the publication object.

In the submission workflow, you should see a new Publication tab. Not all the forms have been implemented, but those that have should show the correct data.

In the frontend, the article landing page and issue table of contents should show the correct data for the submission.

**Comment by ajnyga** [comment] 2019-07-12 12:58
Will break this into two posts. This first one concerns the upgrade process and the errors encountered. The upgrade test was done with a larger OJS installation, around 80 journals and multilingual. The second post which I will send later will have answers to the questions in the issue description.

## Solved upgrade problems

### Subquery returns too many rows
Some submissions might have more than one primary contact which causes an error here: https://github.com/NateWr/ojs/blob/i2072_versioning/dbscripts/xml/upgrade/3.2.0_versioning.xml#L27-L35, simply adding `LIMIT 1` will fix this.

### Duplicate key errors
Some of the subqueries in the upgrade cause duplicate entry errors. This is in some cases connected to old corrupted data, but easily fixed. `ERROR: Upgrade failed: DB: Duplicate entry '0--issueId' for key 'publication_settings_pkey'`

This error occurs at least in
https://github.com/NateWr/ojs/blob/i2072_versioning/dbscripts/xml/upgrade/3.2.0_versioning.xml#L101-L108 and https://github.com/NateWr/ojs/blob/i2072_versioning/dbscripts/xml/upgrade/3.2.0_versioning.xml#L109-L115 probably also in https://github.com/NateWr/ojs/blob/i2072_versioning/dbscripts/xml/upgrade/3.2.0_versioning.xml#L144-L151 and https://github.com/NateWr/ojs/blob/i2072_versioning/dbscripts/xml/upgrade/3.2.0_versioning.xml#L153-L159

These require a `WHERE s.current_publication_id IS NOT NULL` clause to the end so that no NULL values are returned which could cause a duplicate key error.

### Duplicate entry error in `controlled_vocab_symbolic`
`ERROR: Upgrade failed: DB: Duplicate entry 'submissionLanguage-1048588-0' for key 'controlled_vocab_symbolic'`

Caused by https://github.com/NateWr/ojs/blob/i2072_versioning/dbscripts/xml/upgrade/3.2.0_versioning.xml#L166-L175, needs a replacing.

The first three problems are fixed by a pr here: 

## Still needs checking

### MigrateSidebarBlocks gives a notice on array to string conversion
`[code: Installer Installer::migrateSidebarBlocks]
Notice: Array to string conversion in /Applications/XAMPP/xamppfiles/htdocs/ojs-32test/lib/pkp/classes/install/Installer.inc.php on line 837`
Have not checked whether this causes any problems, probably not.

**Comment by NateWr** [comment] 2019-07-17 15:17
Thanks @ajnyga! I've merged those fixes.

> MigrateSidebarBlocks gives a notice on array to string conversion

This isn't related to the new publications stuff. Probably worth filing separately. I can't seem to figure out what would cause it by a quick look at the code.

**Comment by NateWr** [comment] 2019-08-14 13:42
When upgrading from an older version of OJS, the preupdate script fails because the `submission_categories` table doesn't yet exist:

```
[data: dbscripts/xml/upgrade/3.2.0_preupdate_versioning.xml]
ERROR: Upgrade failed: DB: Table 'jidc.submission_categories' doesn't exist
```

**Comment by NateWr** [comment] 2019-08-14 15:33
After an upgrade, the `author_settings` table still contained a `setting_type` column, even though this has been removed from the schema: https://github.com/NateWr/pkp-lib/blob/i2072_versioning/xml/schema/submissions.xml#L51-L73.

More testing needs to be done to see if this gets removed as appropriate, or if it needs to be manually removed.

**Comment by jnugent** [comment] 2019-10-03 18:01
Hi @NateWr  - Just discovered one small thing.  The upgrade runs quite smoothly, but at the moment the orcidProfile plugin version in master is 1.1.1.0 and in stable-3_1_2 it's 1.1.1.1, so you get the "attempting to downgrade" error message just as the upgrade finishes.  Because of that you never actually get to 3.2.

**Comment by asmecher** [comment] 2019-10-03 19:12
@jnugent (and @NateWr), I've bumped the version in the ORCID plugin `master` branch to 1.1.1.1 to avoid this. (We'll increment versions formally as part of the release process.)

**Comment by NateWr** [comment] 2020-02-05 17:47
A couple of things found with a recent round of updates.

PRs:
https://github.com/pkp/ojs/pull/2608
https://github.com/pkp/omp/pull/759

**Closed** 2020-02-10 17:16 UTC
