### ISSUE TITLE
Top right link to profile is invisible (text in white, over a white background)

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#5605] opened 2020-03-10 13:15 UTC
**Describe the bug**
On a clean OJS 3.2.0-0, when you visit a journal's homepage, you can't see the profile link because text is in white, over a white background.

![imagen](https://user-images.githubusercontent.com/2779168/76315842-c9208b80-62d9-11ea-8e13-fa378cf32383.png)

Sample URL: http://revistes.uab.cat:8082/demo

@sssoz please, do you mind to take a look?

**Comment by asmecher** [comment] 2020-03-10 21:29
I think that's something custom to your install, @marcbria -- if I disable the `inline style sheet #3` using the inspector tools, the header appears normally and the links are visible.

![image](https://user-images.githubusercontent.com/200411/76361079-77790080-62db-11ea-9f4c-342bb63ac969.png)

**Comment by marcbria** [comment] 2020-03-11 09:08
I was astonished because it's a clean installation... but it make sense.

The problem appears when you enable the "Show the homepage image as the header background" but you don't upload any background image. 

I suggest making the image mandatory when you enable the background or just ignore the check if no image is upload.

@asmecher do you mind to reopen the issue?

**Comment by asmecher** [comment] 2020-03-11 18:44
Hmm, interesting... Reopening.

**Comment by asmecher** [comment] 2020-03-11 18:50
@NateWr, would you mind looking at this?

**Comment by NateWr** [comment] 2020-03-12 10:30
Confirmed! It looks like the background color is being overridden by this line: https://github.com/pkp/ojs/blob/master/plugins/themes/default/DefaultThemePlugin.inc.php#L208

I think this can be fixed by using `inherit` to ensure the pre-set background color is used. So:

```
'.pkp_structure_head { background: center / cover no-repeat url("' . $homepageImageUrl . '"); }',
```

Should be:

```
'.pkp_structure_head { background: inherit center / cover no-repeat url("' . $homepageImageUrl . '");}',
```

@thinkbulecount2 can you drop what you're working on right now and try this out? See if that fixes it and, if it does, make PRs for OJS and OMP.

@ajnyga This may need to be addressed in OPS as well.

**Comment by thinkbulecount2** [comment] 2020-03-16 15:17
PRs:
[OJS](https://github.com/pkp/ojs/pull/2683)
[OMP](https://github.com/pkp/omp/pull/785)

cc: @NateWr

**Comment by NateWr** [comment] 2020-03-16 15:21
Thanks!

**Comment by NateWr** [comment] 2020-03-16 17:23
Needs to be ported to OMP.

**Closed** 2020-03-18 11:19 UTC
Labels: Bug
