### ISSUE TITLE
SSL redirect ignores base_url[<journal_name>]

### ISSUE THREAD

**Issue by jprk** [pkp/pkp-lib#276] opened 2015-01-10 14:48 UTC
Hello,

I have a OJS 2.4.5 installation with maybe non-standard single journal setup (that is, the base url http://ojs.nnw.cz goes directly to the journal homepage, not to the OJS/index homepage). With a bit of URL rewriting and `restful_urls=On` in the configuration file, it works flawlessly until I try to force SSL for logins by setting `force_login_ssl=On`. For the time being I am ignoring the links to the OJS/index parts as _My Journals_, this can be handled by another set of URL rewriting rules.

Now, although I have set up `base_url[nnw]=http://ojs.nnw.cz` in the configuration file, and all the HTTP links are generated correctly (e.g. http://ojs.nnw.cz/about and so on), the correct login link http://ojs.nnw.cz/login gets redirected to https://ojs.nnw.cz/nnw/login instead of assumed https://ojs.nnw.cz/login.

I am not very familiar with the design of OJS, but my guess is that while handling the `force_login_ssl` configuration option in [PKPLoginHandler.index()] (https://github.com/pkp/pkp-lib/blob/abd8adfe791498379c7c7aa46d6475956a1566eb/pages/login/PKPLoginHandler.inc.php#L37), the internal request value shall be once again remapped using `base_url[<journal_name>]`.

It is not something crucial, it can be handled by yet another set of rewrite rules that redirect the incorrect redirect once again, but it is not very convenient ... 

-- jprk

**Comment by ctgraham** [comment] 2015-01-12 20:06
I tested this in dev-2_4 with rewrites of:
```
RewriteEngine On
RewriteCond %{REQUEST_URI} !/index.php/
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-f
RewriteRule ^/index/(.*)$ /index.php/index/$1 [L]

RewriteCond %{REQUEST_URI} !/index.php/
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} !-f
RewriteRule ^(.*)$ /index.php/testjournal$1 [L]
```

and a config.inc.php of:
```
base_url = "http://my.test.journal/index"
base_url[testjournal] = "http://my.test.journal/"
```
and either `force_ssl` or `force_login_ssl` set to `On`.

My experience verifies the issue.  I haven't gotten down to the cause or fix yet.

**Comment by ctgraham** [comment] 2015-01-12 20:43
Why would protocol redirects (https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/classes/core/PKPRequest.inc.php#L108 and https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/classes/core/PKPRequest.inc.php#L120) allow for the redirect to be anything other than $_SERVER['REQUEST_URI] with $_SERVER['QUERY_STRING'] appended?

**Comment by jprk** [comment] 2015-01-12 21:56
Dne 12. 1. 2015 21:43 "Clinton Graham" <notifications@github.com> napsal(a):
>
> Why would protocol redirects (
https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/classes/core/PKPRequest.inc.php#L108
and
https://github.com/pkp/pkp-lib/blob/ojs-dev-2_4/classes/core/PKPRequest.inc.php#L120)
allow for the redirect to be anything other than $_SERVER['REQUEST_URI]
with $_SERVER['QUERY_STRING'] appended?

I guess that REQUEST_URI is at this moment already remapped to a stateful
URI by simply taking everything after index.php in the original request.
It is just a guess though, I would have to test it (and I will, but
probably not sooner than on Thursday).

I am just wondering whether plain HTTP redirects work in my setup, as the
code for both redirects is almost the same. Also something I will have to
test...

-- Jan

**Comment by ctgraham** [comment] 2015-01-13 13:28
Possible URI variants include:
* index.php + querystring
* index.php + PATH_INFO
* mod_rewrite RESTful URL

Regardless of the above cases, I think the REQUEST_URI should be preserved on a protocol redirect.

In OJS 2.4.5, protocol redirects seem to be limited to:
* Login:
 * https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_5/pages/login/PKPLoginHandler.inc.php#L34
 * https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_5/pages/login/PKPLoginHandler.inc.php#L69
 * https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_5/pages/login/PKPLoginHandler.inc.php#L118
* Post login:
 * https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_5/pages/login/PKPLoginHandler.inc.php#L134
* HTTPS Policy: 
 * https://github.com/pkp/pkp-lib/blob/ojs-stable-2_4_5/classes/security/authorization/HttpsPolicy.inc.php#L31

That set still makes me think that the redirect should not be based on REQUEST_URI and not on the URI variants.  We're really just changing the protocol, not reconstructing the request.  I haven't looked at OJS master, or the other PKP products which share lib-pkp, so I'm hoping one of the PKP devs with more experience can chime in.

**Comment by asmecher** [comment] 2015-02-03 20:36
Thanks for the detailed investigation, @ctgraham and @jprk -- Clinton, your list of redirects looks correct to me.

The reasons for not using REQUEST_URI are lost in the mists of time, but I suspect it has something to do with that variable not always being available/accurate -- http://stackoverflow.com/questions/12772846/how-reliable-is-serverrequest-uri-at-capturing-query-strings rings a bell for me. This now looks to be a non-issue, however, so I think using REQUEST_URI in these few cases makes a lot of sense.

**Comment by asmecher** [comment] 2015-02-03 20:37
(There are probably lots of general opportunities to introduce the use of protocol-relative URLs, by the way.)

**Comment by asmecher** [comment] 2015-02-06 17:16
Merged, thanks!

**Closed by asmecher** 2015-02-06 17:16 UTC

**Comment by asmecher** [comment] 2015-02-06 17:18
Also cherry-picked to pkp-lib omp-dev-1_1 and master branches.
