### ISSUE TITLE
Uploading submission files through the drag and drop is unstable

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#6641] opened 2021-01-20 19:32 UTC
**Describe the bug**
When adding multiple files using the drag and drop feature, I had these issues:
- The cursor switches from the copy to the move icon intermittently
- After releasing the files there's three situations:
1. Everything works
2. Nothing happens
3. Opens the dragged file in a new tab

**To Reproduce**
Select some files, drag them into the container and release.

**What application are you using?**
OJS 3.3

**Additional information**
Chrome

**Comment by NateWr** [comment] 2021-01-21 11:05
Duplicate of https://github.com/pkp/pkp-lib/issues/6537

**Closed by NateWr** 2021-01-21 11:05 UTC
Labels: Bug
