### ISSUE TITLE
[OJS 3.3.0.8] Cannot save edits to Subscription Information

### ISSUE THREAD

**Issue by tmrozewski-york** [pkp/pkp-lib#7409] opened 2021-10-28 19:10 UTC
I cannot edit the Subscription Information Field (Payments > Subscription Policies). All edits are replaced by a left angle bracket.

**To Reproduce**
1. Go to Payments > Subscription Policies
2. Edit the Subscription Information field (either the via the WSYWIG editor or the source code)
3. Save changes
4. Navigate to another tab or page in Dashboard
5. Return to Subscription Policies tab
6. See all changes have reverted to a single left angle bracket.

**What application are you using?**
 OJS 3.3.0.8 (occurs on two different instances)

**Additional information**
This is what replaces any saved edits
![subscription info bug](https://user-images.githubusercontent.com/68435195/139320229-041b77e5-d0af-459d-9073-56ed491f3fdb.PNG)

**Comment by NateWr** [comment] 2021-11-01 10:14
I was unable to reproduce this on `stable-3_3_0`. I also failed to reproduce it on the [Test Drive](https://pkp.sfu.ca/ojs/ojs_demo/) demo, which is running 3.3.0-8.

@tmrozewski-york, can you try to use the test drive instance to reproduce the problem? It may be related to specific language configurations or subscription settings of some kind.

**Comment by NateWr** [comment] 2021-11-04 10:07
I think the next step is going to be diving into the code to figure out what's happening. I think this is the related class that is executing the form:

https://github.com/pkp/ojs/blob/main/classes/subscription/form/SubscriptionPolicyForm.inc.php

And this is the template:

https://github.com/pkp/ojs/blob/main/templates/payments/subscriptionPolicyForm.tpl

This is the code that's pulling the data into the form:

https://github.com/pkp/ojs/blob/main/classes/subscription/form/SubscriptionPolicyForm.inc.php#L118-L134

And this is the code that's saving the data from the form to the journal object:

https://github.com/pkp/ojs/blob/main/classes/subscription/form/SubscriptionPolicyForm.inc.php#L158-L182

I'm going to close this issue, but feel free to reply if you find an issue or need another hint as you dig deeper into it.

**Closed by NateWr** 2021-11-04 10:07 UTC
