### ISSUE TITLE
 OPS 3.3 upgrade error

### ISSUE THREAD

**Issue by elton557** [pkp/pkp-lib#6713] opened 2021-02-03 12:56 UTC
**Describe the bug**
When updating ops I am facing the following error:

PHP Warning:  array_values() expects parameter 1 to be array, null given in /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php on line 187
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Illuminate\Database\Query\Builder::cleanBindings() must be of the type array, null given, called in /var/www/preprints_scielo_org/htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 919 and defined in /var/www/preprints_scielo_org/htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:3088
Stack trace:
#0 /var/www/preprints_scielo_org/htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(919): Illuminate\Database\Query\Builder->cleanBindings(NULL)
#1 /var/www/preprints_scielo_org/htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(946): Illuminate\Database\Query\Builder->whereIn('js.locale', NULL, 'and', true)
#2 /var/www/preprints_scielo_org/htdocs/lib/pkp/classes/migration/upgrade/PKPv3_3_0UpgradeMigration.inc.php(191): Illuminate\Database\Query\Builder->whereNotIn('js.locale', NULL)
#3 /var/www/preprints_scielo_org/htdocs/lib/pkp in /var/www/preprints_scielo_org/htdocs/lib/pkp/lib/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php on line 3088

**To Reproduce**
cd /var/www/preprints_scielo_org/htdocs/tools
php upgrade.php upgrade

**What application are you using?**
OPS 3.3

**Comment by NateWr** [comment] 2021-02-03 14:07
Duplicate of #6710. @elton557 can you try the solutions discussed in that thread and post there if you find it works or doesn't?

**Closed by NateWr** 2021-02-03 14:07 UTC
