### ISSUE TITLE
Copyeditor cannot publish if their account is also assigned JM or JE role

### ISSUE THREAD

**Issue by kshuttle** [pkp/pkp-lib#8275] opened 2022-09-19 16:49 UTC
**Describe the bug**
If a user is assigned as CE on a submission, they will not be able to publish if their user account is also a "manager" in the journal (JM or JE). Doesn't matter if you are assigned that role to the submission or not. Simply having both roles assigned to a user prevents the user from publishing when they are assigned as a CE on the submission. 

**To Reproduce**
1. Assign a copyeditor to a submission and ensure they have both a CE and JM or JE role in the journal. Make sure they aren't assigned as a participant with another role on the submission - only copyeditor.
2. Try to publish an article from that account and notice the "you do not have access to that stage of the workflow" error
3. Adjust the user account settings so they *only* have a CE role, removing JM and JE
4. Try to publish the article again from the account - note that they are able to publish

**What application are you using?**
 OJS 3.3.0-11

**Additional information**
Screen recording reproducing the issue: https://user-images.githubusercontent.com/59741486/191070294-fba10064-c0e1-4d32-a04c-7e6cf4b631bb.mp4

**Comment by ajnyga** [comment] 2022-09-24 13:22
Duplicate of #6875

**Comment by asmecher** [comment] 2022-09-28 18:54
Closing as a duplicate.

**Closed by asmecher** 2022-09-28 18:54 UTC
