### ISSUE TITLE
Unable to Order Issue's inside Journal

### ISSUE THREAD

**Issue by PR91** [pkp/pkp-lib#2680] opened 2017-08-01 09:51 UTC
When I try to change the issue order, it doesn't work. Sometimes, it stays the same as before, sometimes it completely shuffles the issue order when I press "Done".

I attached a short video that shows the problem.

I tested it in two different OJS installations and on at least 4 browsers. (Firefox, Chrome, Safari and IE), the problem is consistent across browsers.

[ojs_export_issue.zip](https://github.com/pkp/pkp-lib/files/1190167/ojs_export_issue.zip)

**Comment by bozana** [comment] 2017-08-01 10:00
@PR91, what OJS version do you use? Also, have you already take a look in the support forum (https://forum.pkp.sfu.ca/), if there is maybe already a solution for your problem? -- That would be the first place to see and ask and only if it is a real bug/issue, a GitHub Issue should be created/opened...

**Comment by PR91** [comment] 2017-08-01 10:17
Sorry about that. I am using OJS 3.0.2.0. I found a forum [topic](https://forum.pkp.sfu.ca/t/ojs-3-cannot-order-articles/23629) but its related to articles and an older OJS version. I noticed that you replied there and provided the solution. I tried changing the publishing date but I wasn't successful. Is there anyway to change the "sorting value" in the database? Thank You.

**Comment by bozana** [comment] 2017-09-28 12:35
I will close the issue, because I cannot reproduce it i.e. maybe not a bug -- if it happens to happen again/for someone else as well, we can reopen the issue...

**Closed by bozana** 2017-09-28 12:35 UTC
