### ISSUE TITLE
[OJS 3.3] All file downloaded has "download-file + extension" as name

### ISSUE THREAD

**Issue by pilasou** [pkp/pkp-lib#7095] opened 2021-05-31 17:46 UTC
As an editor, when I clic on a file name in a submission to download the file, it is always downloaded with the same name (ex: download-file.docx). This is happening no matter the stage (Submission, Review, etc.) or the Element (Text, Image, etc.).

This is happening in our own installment (Open Journal Systems 3.3.0.6) as well as on OJS Test Drive (Open Journal Systems 3.3.0.5)

**To Reproduce**

1. Go to OJS Test Drive Journal (https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php)
2. Click on Connect and use Admin credentials
3. Open a Submission (ex: 975 / Allie et al. / Investigating perceived barriers to the use of open educational resources in higher education in Tanzania)
4. Clic on a file to download it
5. The file is dowloaded with the name "download-file + extension" 

**Additional information**
A generic name as file name is a major issue. In previous OJS version, file were name like this 10458-Texte de l'article-11513-2-2-20210330.pdf (submission number + Element + File ID + Date + Extension).

Thanks!
Pierre

**Comment by asmecher** [comment] 2021-05-31 18:33
I think this is probably a duplicate of https://github.com/pkp/pkp-lib/issues/6898#issuecomment-844901761. Can you see if this change resolves the issue (applied in the `lib/pkp` subdirectory)? https://github.com/pkp/pkp-lib/commit/27ecd4cd9fa3645020c967f1f907f828228ee2ef

**Comment by pilasou** [comment] 2021-05-31 18:38
OK, I look into it! I will confirm if it solve the issue. Thanks.

**Comment by pilasou** [comment] 2021-06-01 18:41
Hi, so applying [ #6898 (comment)](https://github.com/pkp/pkp-lib/issues/6898#issuecomment-844901761) changed things, but did not get them back to normal. Now, when a file is downloaded, OJS uses the name of the file as uploaded. It is better than the generic download-file name but not as better as it was in 3.1 (the former version we used) where file names contained submission ID (ex: 10458-Texte de l'article-11513-2-2-20210330.pdf (submission number + Element + File ID + Date + Extension).) Were there any uses cases that encourage this change in file naming conventions? I forgot to mention that when using the "Download all file" button, this problem does not happen.

**Comment by asmecher** [comment] 2021-06-01 18:52
Hi @pilasou! Thanks for the confirmation on the "bug" part of this. For the greater question of how files ought to be named, there's a lot of discussion here: https://github.com/pkp/pkp-lib/issues/4957

The short version is that we haven't been able to identify a filename form that has been satisfactory for everyone, and every change makes part of our community unhappy. Have a look at the proposed solution there and see if it's workable, and if you like, add your thoughts.

**Closed by asmecher** 2021-06-01 18:52 UTC
Labels: Bug
