### ISSUE TITLE
[OJS2] User registration validation_timeout for deletion not honoured

### ISSUE THREAD

**Issue by Ianvdl** [pkp/pkp-lib#4914] opened 2019-07-11 13:45 UTC
**Describe the bug**
The [documentation](https://docs.pkp.sfu.ca/admin-guide/en/email) states the following (about halfway down the page):

> The second parameter is validation_timeout, which is set to 14 by default. This parameter only works when the require_validation is enabled, and means that a user has 14 days to activate their new account or the account will be removed from the system automatically when the time limit is reached.

But the user isn't actually deleted (at least not on OJS2), only the access key that is generated. This means either the documentation is wrong, or the feature hasn't been implemented completely. Personally I would prefer if the user record is also deleted, because we see thousands of accounts being created over a few weeks/months, and most of them are spam bots who don't validate their accounts.

**To Reproduce**
1. Register an account
2. Don't validate it
3. Wait two weeks (or whatever the validation_timeout is set)
4. User account remains in database

**What application are you using?**
 OJS 2.4.8-4, with email validation turned on.

**Additional information**
So I took a look at the code and found the following:

`lib/pkp/classes/security/AccessKeyManager.inc.php:78`
```php
	/**
	 * Periodically clean up expired keys.
	 */
	function _performPeriodicCleanup() {
		if (time() % 100 == 0) {
			$accessKeyDao =& DAORegistry::getDAO('AccessKeyDAO');
			$accessKeyDao->deleteExpiredKeys();
		}
	}
```
Which then calls:
`lib/pkp/classes/security/AccessKeyDAO.inc.php:222`
```php
	/**
	 * Delete expired access keys.
	 */
	function deleteExpiredKeys() {
		return $this->update(
			sprintf(
				'DELETE FROM access_keys WHERE expiry_date <= %s',
				$this->datetimeToDB(Core::getCurrentDate())
			)
		);
	}
```

Proving that only the key gets deleted.

**Comment by Ianvdl** [comment] 2019-07-15 06:24
I'd like to propose that the records resulting from the following query be deleted as well (replace 14 with whatever the validation_timeout is set as):
```
SELECT * FROM ojs.users
WHERE date_validated is null
AND disabled = true
AND date_registered <= DATE_SUB(CURDATE(), INTERVAL 14 DAY);
```
The disabled check ensures that we don't delete users whose accounts were manually activated by the administrator. Should we also be checking relationships with other tables for e.g. publications or comments, or are there constraints that would just prevent those users from being deleted?

**Comment by asmecher** [comment] 2019-07-16 00:15
Thanks for all the detail here, @Ianvdl! Are you sure that the SQL syntax you describe works for both MySQL and PostgreSQL in the various releases we need to support (see `docs/README` or `docs/README.md`, depending on what release you're using)?

**Comment by Ianvdl** [comment] 2019-07-16 06:13
Hi @asmecher 

Thanks for the feedback. The following should work for Postgres:
```
SELECT * FROM ojs.users
WHERE date_validated is null
AND disabled = true
AND date_registered <= (NOW() - interval '14 day');
```

Looks like the datetime functions haven't changed significantly between versions [9.1](https://www.postgresql.org/docs/9.1/functions-datetime.html) and [9.6](https://www.postgresql.org/docs/9.6/functions-datetime.html).

We're running mysql [5.7](https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html) and the queries work fine. I can't find docs for 4.1 online at the moment, if you have docs somewhere maybe you can double check that the functions used in my example existed back then. 

I checked for constraints between the tables on mysql, but there aren't any. This means that deletions on only the users table could cause issues if there are e.g. publications linked to a user, so that needs to be taken into account first.

**Comment by Ianvdl** [comment] 2019-07-16 06:58
So I went to take a look at the tables that reference user_id by checking the schema for any columns named user_id. There are no foreign keys, so there doesn't seem to be an automatic way to determine this otherwise. If the referenced user_id is given a different name then this method wouldn't have picked it up. 

Checking the full list would result in the following monstrosity:

```sql
SELECT * FROM ojs.users
WHERE date_validated is null
AND disabled = true
AND date_registered <= DATE_SUB(CURDATE(), INTERVAL 14 DAY)
AND ojs.users.user_id not in (select user_id from article_event_log)
AND ojs.users.user_id not in (select user_id from article_notes)
AND ojs.users.user_id not in (select user_id from articles)
AND ojs.users.user_id not in (select user_id from books_for_review)
AND ojs.users.user_id not in (select user_id from comments)
AND ojs.users.user_id not in (select user_id from completed_payments)
AND ojs.users.user_id not in (select user_id from email_log_users)
AND ojs.users.user_id not in (select user_id from event_log)
AND ojs.users.user_id not in (select user_id from group_memberships)
AND ojs.users.user_id not in (select user_id from notes)
AND ojs.users.user_id not in (select user_id from notification_subscription_settings)
AND ojs.users.user_id not in (select user_id from notifications)
AND ojs.users.user_id not in (select user_id from object_for_review_assignments)
AND ojs.users.user_id not in (select user_id from roles)
AND ojs.users.user_id not in (select user_id from section_editors)
AND ojs.users.user_id not in (select user_id from signoffs)
AND ojs.users.user_id not in (select user_id from subscriptions)
AND ojs.users.user_id not in (select user_id from temporary_files)
AND ojs.users.user_id not in (select user_id from user_interests);
```

But I think we can narrow that down to the following for a start:

```sql
SELECT * FROM ojs.users
WHERE date_validated is null
AND disabled = true
AND date_registered <= DATE_SUB(CURDATE(), INTERVAL 14 DAY)
AND ojs.users.user_id not in (select user_id from article_event_log)
AND ojs.users.user_id not in (select user_id from article_notes)
AND ojs.users.user_id not in (select user_id from articles)
AND ojs.users.user_id not in (select user_id from books_for_review)
/*AND ojs.users.user_id not in (select user_id from comments)*/
AND ojs.users.user_id not in (select user_id from completed_payments)
/*AND ojs.users.user_id not in (select user_id from email_log_users)*/
/*AND ojs.users.user_id not in (select user_id from event_log)*/
/*AND ojs.users.user_id not in (select user_id from group_memberships)*/
/*AND ojs.users.user_id not in (select user_id from notes)*/
/*AND ojs.users.user_id not in (select user_id from notification_subscription_settings)*/
/*AND ojs.users.user_id not in (select user_id from notifications)*/
AND ojs.users.user_id not in (select user_id from object_for_review_assignments)
/*AND ojs.users.user_id not in (select user_id from roles)*/
AND ojs.users.user_id not in (select user_id from section_editors)
AND ojs.users.user_id not in (select user_id from signoffs)
AND ojs.users.user_id not in (select user_id from subscriptions)
/*AND ojs.users.user_id not in (select user_id from temporary_files)*/
/*AND ojs.users.user_id not in (select user_id from user_interests)*/;
```

I'm not sure what the performance impact of this would be on a large system. A `WHERE NOT EXISTS` query might be faster for this kind of thing, although I suspect the very first table that matches will invalidate the whole query and skip the rest of the tables, so we could order them according to the likelihood that they might match up.

**Comment by asmecher** [comment] 2019-08-05 18:46
@Ianvdl, that's a bit of a wild goose chase... How do you feel about assuming that a user who has not validated their account will not have any scholarly records associated with their account? I think that's a defensible approach because they won't have been able to log in, and we don't yet have any import/export processes (I don't think) that can create accounts that have not been validated yet.

**Comment by Ianvdl** [comment] 2019-08-15 08:44
@asmecher Thanks for your response. I'm thinking that if a user was manually enabled then there would not be any validation date. The disabled check in the original query would catch that, unless a user was enabled for a time and then disabled later. I'm not sure how common that would be, but there's still a chance I guess. I'll run a test query against our own production journals to see whether there are any users that have no activation date, which are disabled and have links to other tables mentioned above.

**Comment by NateWr** [comment] 2022-09-13 08:50
Closing this as outdated. If you can reproduce this on a recent stable version, please provide reproduction steps and we can re-open this.

**Closed by NateWr** 2022-09-13 08:50 UTC
Labels: Bug:1:Low, Try Me
