### ISSUE TITLE
Refactor AuthPlugin

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#2443] opened 2017-04-13 22:00 UTC
The code is exactly identical between OMP and OJS, differing only in comments; core functionality should be moved to `pkp-lib` instead.

**Comment by asmecher** [comment] 2017-05-03 20:10
PRs:
- https://github.com/pkp/pkp-lib/pull/2486
- https://github.com/pkp/ojs/pull/1369
- https://github.com/pkp/omp/pull/408

@crism, before I can merge these, you'll need to change all import statements that referred to the `AuthPlugin` class in its old location to refer to the new one. For example, in `plugins/auth/ldap/LDAPAuthPlugin.inc.php`, you'd need to change

    import('classes.plugins.AuthPlugin');

...to...

    import('lib.pkp.classes.plugins.AuthPlugin');

**Comment by crism** [comment] 2017-05-03 20:32
Oops… thanks, @asmecher. #2486 and pkp/ojs#1369 are fixed. I didn’t find any references in pkp/omp.

**Comment by asmecher** [comment] 2017-05-03 21:22
Thanks, @crism. Note that the Travis tests are failing, presumably because the `pkp-lib` submodule isn't getting checked out from your branch. Try adding a submodule commit instructing the checkout script to grab the code from your branch -- there are instructions here: https://pkp.sfu.ca/wiki/index.php?title=Github_Documentation_for_PKP_Contributors#PKP_library_submodule_changes

Hopefully that'll get the Travis testing working.

**Comment by crism** [comment] 2017-05-03 21:44
Ah, thanks, @asmecher. I wasn’t sure how to fix that.

**Comment by asmecher** [comment] 2017-05-03 22:02
Close, thanks -- but it looks like you'll need to rebase; try pulling from the official repo and then rebasing your branch on it. Otherwise there's a merge conflict and the Travis testing doesn't get kicked off.

**Comment by crism** [comment] 2017-05-03 23:22
@asmecher, is there a way to get at the Travis screenshots to see what the actual error message is?

**Comment by asmecher** [comment] 2017-05-03 23:53
@crism, you can see the full Travis log by looking at each build, e.g. https://travis-ci.org/pkp/ojs/jobs/228530204. It looks to me like the checkout still isn't getting your branch:

> $ ./tools/startSubmodulesTRAVIS.sh
> 1 - Retrieving git user:
>     Gituser: pkp
> 2 - Verifying if we have a merge commit in HEAD:
>     Merge commit message: 50ec991420410c07236db227e032ff2eccf28f85 Merge 3c7aeed5f8cf704b8cd497a9309cfc397446b67f into e0bf24b45afafd898d1e70766942457b3737d28e
>     HEAD points to a merge commit.
>     HEAD^ points to a common commit with hash 3c7aeed5f8cf704b8cd497a9309cfc397446b67f
> 3 - Verifying if last non merge commit is a subproject commit:
>     Subproject commit hash: 9366f8e7077d77d80129fdb1ee227f0910c6c57c
>     Last non merge commit is subproject commit.
> 4 - Trying to get user and branch from commit message:
>     User and branch: PublishingWithoutWalls/issue/2443 - User: PublishingWithoutWalls - Branch: issue
>     Found user and branch in commit message.
> 5 - Reseting the subproject commit in application.
> HEAD is now at b29ed09 pkp/pkp-lib#2443: fixing AuthPlugin import statements
> 6 - Initializing and updating submodule from official.

I think the problem is that you've got a `/` in your branch name -- the script isn't prepared to handle that. I'll try out a renamed branch on my own account and let you know how it goes shortly.

**Comment by asmecher** [comment] 2017-05-04 00:22
Yup, that appears to have done it: https://travis-ci.org/asmecher/ojs/builds/228556252
I'll merge your branches and ensure that the master branch tests OK, but I don't expect problems. Obviously it would be better not to fail on branches with `/` in the names, but for now I'd suggest avoiding them.

**Comment by asmecher** [comment] 2017-05-04 00:22
Merged, thanks!

**Closed by asmecher** 2017-05-04 00:22 UTC

**Comment by crism** [comment] 2017-05-04 04:24
Thanks, @asmecher. I was about to blame [GitFlow](http://nvie.com/posts/a-successful-git-branching-model/) for my use of slashes… but I see he uses hyphens. I don’t know where I acquired that habit, and I’ll at least consider reforming my ways. `(-:`
