### ISSUE TITLE
[OJS] change locale in main view doesn't change language of items in header

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#3292] opened 2018-01-19 09:07 UTC
Hello

I install OJS with 2 languages : English and French.
When you change locale in main view, items in nav menu (headerNavigationContainer) don't change (except "Search" item) : they stay in primary locale selected during install. And that, even if you change primary locale after.
I test this with 3.1.0 and 3.1.0_1.

Do you have the same behavior ?

**Comment by asmecher** [comment] 2018-01-19 16:59
Assigning @defstat -- but @forgive38, next time the support forum (https://forum.pkp.sfu.ca) is the better place to post questions. If the question turns out to identify a bug, that's a good time to create an issue.

**Comment by forgive38** [comment] 2018-01-29 09:11
@asmecher 
I think this is a bug like #3156 , because I have to translate menu  items in the WebUI  ( Navigation Menus) in order to make the translation available.

**Comment by asmecher** [comment] 2018-01-29 22:11
@forgive38, in fact I think this is a duplicate of https://github.com/pkp/pkp-lib/issues/2987.

**Closed by asmecher** 2018-01-29 22:11 UTC

**Comment by forgive38** [comment] 2018-01-30 08:29
I updated OJS to the last ojs-stable-3_1_0, and now, it works
Thank you
