### ISSUE TITLE
Error Smarty: Unable to load template since upgraded to OJS 3.3.0.14

### ISSUE THREAD

**Issue by mayolag** [pkp/pkp-lib#8942] opened 2023-04-24 17:08 UTC
I recently upgraded to OJS 3.3.0.14 and now some links are not working in the backend: Issues, Journal, Distribution and Workflow. I’m using PHP 7.4.33. I'm getting the following errors in the log:

[14-Apr-2023 20:48:55 UTC] PHP Fatal error: Uncaught → Smarty: Unable to load template ‘app:management/context.tpl’ ←
thrown in /home/customer/www/revistalatinoamericanadepoblacion.org/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195
[14-Apr-2023 20:49:00 UTC] PHP Fatal error: Uncaught → Smarty: Unable to load template ‘app:manageIssues/issues.tpl’ ←
thrown in /home/customer/www/revistalatinoamericanadepoblacion.org/public_html/lib/pkp/lib/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 195

**Comment by jonasraoni** [comment] 2023-04-24 18:23
Hi @mayolag,

It seems to be working fine on the latest release of OJS (there's a demo here: https://pkp.sfu.ca/software/ojs/demo/), so it could be an installation, theme, ... issue. Therefore, I'll close this issue unless you're able to provide reproduction steps.

Also, you might try to search for a similar issue and ask for support in the forum https://forum.pkp.sfu.ca/search?q=unable%20to%20load%20template

Best,
Jonas

**Closed by jonasraoni** 2023-04-24 18:23 UTC

**Comment by mayolag** [comment] 2023-04-24 18:31
I downloaded the OJS 3.3.0.14 package, uploaded via FTP, changed the
directory to public_html, changed the config.inc.php file to "installed =
Off" with the old database settings. Then clicked on "update OJS" in the
dashboard. After that Issues, Journal, Distribution and Workflow links
stopped working. Everything else works fine. What can I do?
Please help me.

**Comment by jonasraoni** [comment] 2023-04-25 09:12
@mayolag, you can send a message to the forum, there are many people who may help with your situation there, including PKP staff.
I don't think it's a problem in the software, otherwise **many** people would have complained about it by now, including our own staff, which undertakes such upgrades on a daily basis.

**Comment by mayolag** [comment] 2023-04-25 12:37
I already asked in the forum but nobody is answering and I really need to
solve it.
