### ISSUE TITLE
Creating a galley with Quicksubmit renders galley edit/view unaccessible in OJS 3.3

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#9820] opened 2024-03-22 08:12 UTC
**Describe the bug**

When trying to edit/view a galley from "Submissions -> Publication -> Galleys" that has been created with  Quicksubmit the "View Galley" and "Download Galley" actions report the error "The current role does not have access to this operation.". This happens for all accounts, even with the admin account.

Nothing found in the PHP error logs. With OJS 3.4 this error doesn't occur.

Galleys directly created from "Submissions -> Publication -> Galleys" don't have this issue.

**To Reproduce**
1. Create a submission with a galley with Quicksubmit
2. Go to "Submissions -> Publication -> Galleys" and try to edit or view and see the error "The current role does not have access to this operation."
3. Create a galley directly from "Submissions -> Publication -> Galleys"
4. Try to edit or view => no error

**What application are you using?**
 OJS 3.3.0-15

**Additional information**
![grafik](https://github.com/pkp/pkp-lib/assets/54445456/fac264ea-fdbf-4dbc-a1b4-d80eb0700512)

**Comment by jnugent** [comment] 2024-03-28 13:36
Confirming that this still exists in 3.3.0.17

**Comment by ronste** [comment] 2024-03-28 14:35
With 3.3.0-17 the "View Galley" diaglog is working.

However, clicking on the Galley file directly I still get the same error from the browser window (which I unfortunately didn't mention before):

![grafik](https://github.com/pkp/pkp-lib/assets/54445456/54ffd73c-6230-422a-80c1-99d978a54e3e)

**Comment by jnugent** [comment] 2024-03-28 14:37
In our 3.3.0.17 install, clicking "Edit" on an HTML galley created via quicksubmit generates the error.  The problem stems from not being able to load the dependent files grid.

**Comment by taslangraham** [comment] 2024-08-09 17:52
I followed the steps I've provided but couldn't reproduce the issues. I successfully uploaded a submission with a Galley using QuickSubmit, and I could edit and view the Galley without any problems. @ronste @jnugent are there any other steps/info you could provide that you think might be useful?

**Version Info**
OJS - `3.3.0.17`
QuickSubmit Plugin - [`1.0.6-2`](https://github.com/pkp/quickSubmit/releases/tag/v1_0_6-2)

**Comment by jnugent** [comment] 2024-08-09 18:08
@taslangraham the bug was specifically for HTML galleys, and the uploaded file needed a text/html mime type in order to get the Dependent Files grid to load.  But I just tested this in 3.3.0.18 and I can't duplicate it now.  I wonder if any of the work on this issue had an impact?

https://github.com/pkp/pkp-lib/issues/9131

**Comment by taslangraham** [comment] 2024-08-09 19:12
@jnugent  No issues faced when testing with HTML galleys

**Comment by taslangraham** [comment] 2024-08-12 13:43
@jnugent Closing this issue given that it is no longer present in 3.3

**Closed** 2024-08-13 01:43 UTC
Labels: Bug:2:Moderate
