### ISSUE TITLE
OJS 3.3rc Can't mark task notifications as "New" or "Read" or "Delete"

### ISSUE THREAD

**Issue by librariam** [pkp/pkp-lib#6559] opened 2021-01-10 15:15 UTC
**Describe the bug**
Task notifications have an option to be selected and marked as "New" or "Read" or to be deleted. But when "Mark New" or "Mark Read" or "Delete" buttons are clicked, nothing happens - there is no change to the notifications.

**To Reproduce**
1. Receive a task notification (e.g. new article submitted or assigned)
2. Select one or more notifications by checking the checkbox
3. Click to "Mark New" or "Mark Read" or "Delete" buttons

![image](https://user-images.githubusercontent.com/45104797/104126769-6c906180-532c-11eb-8356-1a47bf3d2b1c.png)

**What application are you using?**
OJS 3.3cr

**Comment by NateWr** [comment] 2021-01-11 12:08
Confirmed. Nothing in the error log but the style does not change and the `unread` class is still applied after marking read.

**Comment by NateWr** [comment] 2021-01-12 16:25
PR:
https://github.com/pkp/pkp-lib/pull/6575

Tests:
https://github.com/pkp/ojs/pull/2986

**Comment by NateWr** [comment] 2021-01-13 10:08
Merged.

**Comment by janiosarmento** [comment] 2021-11-01 16:03
Hi @NateWr

I'm reopening this issue because on 3.3.0-8 the issue still appears. I've tested both with a recently upgraded Journal and in a fresh install.

The screen recording below shows the Browser Tools on "Network" tab.

https://user-images.githubusercontent.com/7367281/139702462-ea2669b0-20bc-4bad-a057-0d38435ad9b8.mov

Thank you!

**Comment by asmecher** [comment] 2021-11-01 18:54
@janiosarmento, is this `3.3.0-8` from the tarball or from the `stable-3_3_0` branch? I recently added some changes (https://github.com/pkp/pkp-lib/issues/7371) to the stable branch that involved changes to the compiled Javascript.

**Comment by janiosarmento** [comment] 2021-11-18 12:22
Sorry, @asmecher, I didn't see your mention in the notification ocean.

Always `stable-3_3_0`, we never use tarballs.

**Comment by asmecher** [comment] 2021-11-18 18:15
This is probably a duplicate of #7371. Could you update from `stable-3_3_0` and try again? Meanwhile, I'll close this.

**Comment by asmecher** [comment] 2021-11-18 18:16
Sorry, I mean https://github.com/pkp/pkp-lib/issues/7450.

**Closed by asmecher** 2021-11-18 18:15 UTC
Labels: Bug
