### ISSUE TITLE
Multi-locale date and time options not displayed

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#8814] opened 2023-03-15 22:34 UTC
**Describe the bug**
When multiple locales are enabled in OPS, date and time options are displayed for the primary locale but not for the secondary locale.

**To Reproduce**
1) Enable multiple locales (UI, Forms, Submission)
2) Go to Settings > Website > Setup > Date & Time
3) Select the secondary, non-primary locale from the locale tabs at the top of the page
4) Date & time settings are not displayed for the secondary locale

**What application are you using?**
OPS 3.4 RC1

**Additional information**
Screenshot below.

![Screen Shot 2023-03-15 at 6 26 23 PM](https://user-images.githubusercontent.com/200793/225458540-aa944847-e047-4955-955e-4aecf78e2888.png)

**Comment by NateWr** [comment] 2023-03-16 08:58
@mfelczak can you share the section of the `config.inc.php` file that defines date and time formats?

**Comment by jonasraoni** [comment] 2023-03-16 12:46
```ini
[general]
time_zone = UTC
date_format_short = "Y-m-d"
date_format_long = "F j, Y"
datetime_format_short = "Y-m-d h:i A"
datetime_format_long = "F j, Y - h:i A"
time_format = "h:i A"
```

**Comment by NateWr** [comment] 2023-03-16 14:15
I was unable to reproduce it with that config file and with the `en` and `fr_CA` languages enabled everywhere. Based on your screenshot, I suspect that this might be a JavaScript error which is preventing a component from rendering. Can you look at the console and share any error messages?

**Comment by mfelczak** [comment] 2023-03-16 17:15
Hello @NateWr, I'm also now unable to reproduce this issue using the same test install. I've confirmed that our local `main` branches haven't been pulled up to include recent bug fixes. The date/time display for the second locale is now working.

**Comment by NateWr** [comment] 2023-03-16 17:36
Thanks! I'll close this for now.

**Closed by NateWr** 2023-03-16 17:36 UTC
Labels: Bug:2:Moderate
