### ISSUE TITLE
[OJS 3.3.0.3] Request the ability to delete an Incomplete Submission

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#7055] opened 2021-05-12 12:58 UTC
Currently there is no way to delete an unfinished submission, I think this would be an useful feature.
![image](https://user-images.githubusercontent.com/18707781/117978791-9f615b00-b308-11eb-830b-5f6eaae7df37.png)

**Comment by asmecher** [comment] 2021-05-12 14:34
I think this is a duplicate of: https://github.com/pkp/pkp-lib/issues/4540

**Closed by asmecher** 2021-05-12 14:34 UTC

**Comment by luizbgomide** [comment] 2021-05-12 15:45
I meant giving the author the ability to delete incomplete submissions.

**Comment by asmecher** [comment] 2021-05-13 14:55
Authors can delete their incomplete submissions from the submissions list (testing with 3.3.x); see bottom right:
![image](https://user-images.githubusercontent.com/200411/118143815-97fd8880-b3c0-11eb-85a8-e37d9974e082.png)

**Comment by luizbgomide** [comment] 2021-05-13 15:56
Ohh, my bad, in this case, the issue is that Submissions created as **Journal Manager** or **Journal Editor** don't have the **Delete** button, as can be seem in the screenshot below:
![image](https://user-images.githubusercontent.com/18707781/118151891-84671780-b3ea-11eb-83e3-d78df9a7ad79.png)

**Comment by asmecher** [comment] 2021-05-13 16:11
Ah, I see; that is an oversight, but should be corrected when we get to https://github.com/pkp/pkp-lib/issues/4540.
