### ISSUE TITLE
PKPAuthorForm: required locale for author metadata is UI instead of submission locale

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#8202] opened 2022-08-24 12:20 UTC
**Describe the bug**
Start a new submission using EN as UI locale. Choose another language as submission locale, e.g. DE. When adding authors, the author given name is required in the UI locale (EN) instead of the submission locale (DE).

**To Reproduce**
1. Start a new submission using EN as UI locale.
2. Choose another language as submission locale, e.g. DE.
3. Add contributor form will require given name in the UI locale instead of submission locale.

**What application are you using?**
 OJS stable-3_3_0

**Additional information**
This error might have impacts on other parts of the system, above all metadata distribution -- the author given name could be missing in the submission locale.

**Comment by bozana** [comment] 2022-08-24 12:35
PRs:
pkp-lib: https://github.com/pkp/pkp-lib/pull/8203
ojs: https://github.com/pkp/ojs/pull/3507
omp: https://github.com/pkp/omp/pull/1184
ops: https://github.com/pkp/ops/pull/335

**Comment by asmecher** [comment] 2022-08-24 22:51
@bozana, can you check if https://github.com/pkp/pkp-lib/issues/4818 is a duplicate of this issue? Thanks!

**Comment by bozana** [comment] 2022-08-25 09:40
@asmecher, it is a little bit different: It seems in that old version 3.1.2 the author given name was required for all locales. This is not the case in 3.3, which is good so. In 3.3 the given name was required only in UI locale. This issue is about that -- the required locale should be the submission locale.
Thus, that other issue can be closed for branches > 3.3 (I only tested it in 3.3 and main). Or, if we shall fix it in the old branches as well, then the issue can stay, but only for the old branches...

**Closed** 2022-08-25 09:44 UTC
Labels: Bug:3:Critical
