### ISSUE TITLE
Error for custom blocks in side bar due to automatic name addition

### ISSUE THREAD

**Issue by heike-r** [pkp/pkp-lib#6148] opened 2020-08-06 08:45 UTC
This happened after update of OJS from 3.1.2.4 to 3.2.1.1, multi-journal installation on journal level and on the main page.

Custom blocks cannot be activated for the side bar. In the dashboard at settings -> website -> appearance in the lower part 'side bar', all of our blocks (3 custom and the web feed plugin) are listed. However, when I select them for display and want to save, the error message "this can only contain numbers and letters" appears and prevents saving. This is probably due to the naming of the blocks, because the custom blocks have an added (custom) to their name. The brackets are likely the problem. However, I cannot change this since the addition of this (custom) to the actual block name is generated automatically by OJS. When I only select the web feed plugin as block for the side bar, I can save and the block is displayed. This problem only concerns the custom blocks.

Possibe solution: either remove the brackets from the automatically added (custom) or remove the "only numbers and letters" restriction for the side block naming.

**Comment by NateWr** [comment] 2020-08-10 14:53
I'm unable to reproduce this myself. The (Custom) text that you refer is not sent with the save request and so won't be causing the error that you describe.

Have you tried re-saving the custom block titles under Settings > Website > Plugins > Custom Blocks > Manage Custom Blocks? There is a restriction in place there that should prevent the titles from being saved if they are invalid.

If that doesn't get things working for you, can you provide a screenshot showing the sidebar blocks you have and the error you're receiving?

**Comment by heike-r** [comment] 2020-08-11 08:29
After some testing, I have to correct my post above. The problem was an underscore in the custom block name. The custom block plugin allows for letters, numbers, hyphens and underscores in the name, but the side bar is more strict and only works with letters and numbers in the block name. Maybe this should be harmonized?

**Comment by NateWr** [comment] 2020-08-11 09:29
That's it! Thanks for tracking that down @heike-r. I've got PRs for this fix backporting it to to the 3.2.1 stable branch (so it will go out with the next maintenance release).

PRs:
https://github.com/pkp/pkp-lib/pull/6161
https://github.com/pkp/pkp-lib/pull/6162 (stable)

Tests:
https://github.com/pkp/ojs/pull/2853
https://github.com/pkp/ojs/pull/2854 (stable)

**Comment by NateWr** [comment] 2020-08-20 08:52
Merged and backported to `stable-3_2_1`.

**Closed by NateWr** 2020-08-20 08:52 UTC
Labels: Bug
