### ISSUE TITLE
User ID filter in PKPContextQueryBuilder selects duplicate contexts if user has multiple roles 

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#8602] opened 2023-02-02 15:23 UTC
**Describe the bug**
One of the consequences is a bug leading to displaying duplicates of journals list in the dashboard header navigation dropdown menu:
![duplicate_context](https://user-images.githubusercontent.com/20665587/216366692-da4d6368-ab1a-4bc5-940d-b5dd4e2ad18b.png)

**To Reproduce**
1. Create a second journal
2. Register a user in both journals having the reader and reviewer roles
3. Log in and click on a journal dropdown menu on the left upper side of the screen
4. See duplicates in a journals list

**What application are you using?**
 OJS main branch

**Additional information**
The example of query that is causing a problem with applied user ID filter:
```sql
select `c`.* from `journals` as `c` 
left join `user_groups` as `ug` on `ug`.`context_id` = `c`.`journal_id` 
left join `user_user_groups` as `uug` on `uug`.`user_group_id` = `ug`.`user_group_id` where (`uug`.`user_id` = 37 and (`ug`.`role_id` = 16 or `c`.`enabled` = 1))
```
The result of joined table if all columns selected looks like:

journal_id | path | seq | primary_locale | enabled | current_issue_id | user_group_id | context_id | role_id | is_default | show_title | permit_self_registration | permit_metadata_edit | user_group_id | user_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | publicknowledge | 1.00 | en_US | 1 | 1 | 16 | 1 | 4096 | 1 | 1 | 1 | 0 | 16 | 37
1 | publicknowledge | 1.00 | en_US | 1 | 1 | 17 | 1 | 1048576 | 1 | 1 | 1 | 0 | 17 | 37
2 | sj | 1.00 | en_US | 1 | NULL | 33 | 2 | 4096 | 1 | 1 | 1 | 0 | 33 | 37
2 | sj | 1.00 | en_US | 1 | NULL | 34 | 2 | 1048576 | 1 | 1 | 1 | 0 | 34 | 37

**Comment by touhidurabir** [comment] 2023-02-05 07:09
@asmecher PRs

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8608
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3742 [TEST ONLY]

**Comment by asmecher** [comment] 2023-02-06 20:01
@touhidurabir, have you tested this with the reproduction steps? I don't think this is the same query that is being referred to in the issue; the cause involves joins on the `user_user_groups` table.

**Comment by touhidurabir** [comment] 2023-02-06 20:05
> I don't think this is the same query that is being referred to in the issue

@asmecher it's the same query as I tested. I think what @Vitaliy-1 posted in the issue description is the part of final generated sql statement via laravel query builder . Following the reproduce step in issue description, removing the `distinct` will have same effect as mentioned in issue description as I tested .

**Comment by asmecher** [comment] 2023-02-06 20:38
@touhidurabir Gotcha -- but I think this isn't solving the underlying problem, which is that the [`$userId` constraint](https://github.com/pkp/pkp-lib/blob/4ea05d123e244fa25c9b9b43058599ac55e9b0d1/classes/services/queryBuilders/PKPContextQueryBuilder.php#L153) can result in potentially several duplicate rows being returned by accident. I think the solution will be to reformulate those `LEFT JOIN` queries as a `WHERE` ... `IN` query instead, something like [this](https://github.com/pkp/pkp-lib/blob/4ea05d123e244fa25c9b9b43058599ac55e9b0d1/classes/userGroup/Collector.php#L244).

**Comment by touhidurabir** [comment] 2023-02-14 12:43
@asmecher PR updated . Please check now.

**Comment by asmecher** [comment] 2023-02-14 20:42
That's perfect, thanks! I've merged it.

**Closed by asmecher** 2023-02-14 20:42 UTC
Labels: Bug:2:Moderate
