### ISSUE TITLE
getByControlledVocabId() SQL does not work with PostgreSQL

### ISSUE THREAD

**Issue by tgc** [pkp/pkp-lib#1856] opened 2016-09-28 07:14 UTC
OJS 3.0.0-stable branch running on PHP 7.0.11 with PostgreSQL 9.5.4.

I found this in the log:
DB Error: ERROR:  column "cve.controlled_vocab_entry_id" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT cve.*\n               ^

I don't know how to reproduce but the offending SQL is in getByControlledVocabId().

**Comment by asmecher** [comment] 2016-09-28 18:59
Hi @tgc -- hmm, but no `getByControlledVocabId` implementation contains a `GROUP BY` clause. If you're able to reproduce this message consistently, could you try turning on `debug` in your `config.inc.php` just before triggering the message? That'll dump all SQL queries to the browser; the last one should be the offending query.

**Comment by tgc** [comment] 2016-09-29 07:35
Looking at lib/pkp/classes/user/InterestEntryDAO.inc.php from the OJS 3.0.0 tarball the getByControlledVocabId function most definitely contains a GROUP BY clause.

AFAICT this is the GROUP BY causing the issue:
https://github.com/pkp/pkp-lib/blob/master/classes/user/InterestEntryDAO.inc.php#L67

Below was taken verbatim from the OJS 3.0.0 tarball.

```
function getByControlledVocabId($controlledVocabId, $rangeInfo = null, $filter = null) {
...
                $result = $this->retrieveRange(
                        'SELECT cve.*
                        FROM    controlled_vocab_entries cve
                                JOIN user_interests ui ON (cve.controlled_vocab_entry_id = ui.controlled_vocab_entry_id)
                                ' . ($filter?'JOIN controlled_vocab_entry_settings cves ON (cves.controlled_vocab_entry_id = cve.controlled_vocab_entry_id)':'') . '
                        WHERE cve.controlled_vocab_id = ?
                        ' . ($filter?'AND cves.setting_name=? AND cves.setting_value LIKE ?':'') . '
                        GROUP BY cves.controlled_vocab_entry_id ORDER BY seq',
                        $params,
                        $rangeInfo
                );
```
Unfortunately I do not know how to reproduce, I just noticed the error in the log and found what looks like the only matching SQL in the source.

**Comment by asmecher** [comment] 2016-09-29 23:37
@NateWr, mind taking a look at this? It's related to...
https://github.com/pkp/pkp-lib/commit/55379de73202f9b957f5b158829e28b66916a7aa

PostgreSQL is pickier than MySQL in this regard.

**Comment by NateWr** [comment] 2016-10-24 16:49
@asmecher I spent some time looking into this today, but I'm not sure I understand the problem well enough to propose a good solution.

As I understand it, older versions of PostgreSQL won't `GROUP BY` a single column from the query. Newer versions should be able to do it on a Primary Key (which is what's being done here), but older versions won't know which row to pluck out.

Some people have suggested simply specifying the columns in the `SELECT` part of the query and then reproducing that selection in the `GROUP BY` clause. But I'm not sure if that will work in our case because we're joining a settings table with potentially arbitrary numbers of rows per ID? Other suggestions are to write a sub-query, but I'll admit my SQL isn't that strong for this kind of thing.

**Comment by NateWr** [comment] 2016-11-18 12:47
I'm officially handing this one off, @asmecher. Check the previous comment for details.

**Comment by asmecher** [comment] 2016-11-18 16:45
Yup, thanks -- it's already waaaay up my to-do list.

**Comment by asmecher** [comment] 2016-12-07 21:09
Committed using a `cve.controlled_vocab_entry_id` GROUP BY.

**Closed by asmecher** 2016-12-07 21:09 UTC
