### ISSUE TITLE
Select language when using email templates

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#3525] opened 2018-03-27 09:45 UTC
When sending an email template, it should be possible to send an email template in the language appropriate for the recipient.

- Ability to determine and auto-select recipient language where possible.
- Override the default with the language we'd like.
- All variables used in the email should be rendered in the correct language.

There is an existing setting under the user profile for "Working Languages" that could be used.

See https://forum.pkp.sfu.ca/t/ojs-3-x-x-choice-to-pick-language-for-forms-and-templates-when-sending-e-mails/31849 and #3523.

**Comment by AhemNason** [comment] 2019-09-30 10:17
I was going to add a new ticket but it seems like it might be a bit of a dupe of this one. Currently, if a user wants to send email out in another user's language they need to switch languages themselves to do so. See forum post: https://forum.pkp.sfu.ca/t/bilingual-email/55970/6 

Nate mentioned the following: 

> Looking at that forum thread, it seems like we should probably be sending emails in the recipient's working language, rather than the sender's language. If that's not the case it would probably be worth filing an issue. 

Just to confirm that all emails go out in the sender's language, currently.

**Comment by ahmedgad-it** [comment] 2020-05-09 15:32
It should be receiver-language based not sender language, i think!

**Comment by NateWr** [comment] 2020-05-11 11:09
Yes, sending an email in the receiver's language is a good default. We have to be careful about situations where an email comes _from_ someone though. For example, when an editor assigns a reviewer, they need to be able to preview and modify the email that is sent to the reviewer. 

In such cases, we need some flexibility since the editor may not be able to read an email in the preferred language of the reviewer. The editor needs to be told what language the reviewer prefers. But the editor still needs to be able to choose which language they prefer to send the email in.

**Comment by ahmedgad-it** [comment] 2020-05-11 12:27
So, email preview is in sender's language; an on sending, email is sent in receiver's language.

**Comment by NateWr** [comment] 2020-05-11 14:14
If an editor is sending an email, they need to know what is being sent. Switching out the language would be an unwelcome surprise and would not work in cases where the editor has customized the email before sending.

This is a case where an automated decision should not be made, but tools should be built to help users make the most appropriate decision for their needs.

**Comment by forgive38** [comment] 2021-11-26 08:30
Hello

Regarding the problem of sending emails in the right language, maybe the smartest and easiest way is to send emails by concatenating different languages in one email.


For example:

if French is the primary locale and English is selected too, the email will be composed with the 2 languages separated by a line .....

>>French subject / English subject

French template
------
English template

**Comment by forgive38** [comment] 2022-02-14 13:53
> 
> Regarding the problem of sending emails in the right language, maybe the smartest and easiest way is to send emails by concatenating different languages in one email.
> 

This proposal may not be the best solution.

Ideally, users' preferred languages should be stored in the database (and not just in a cookie as shown on https://github.com/pkp/pkp-lib/issues/7293 ).
And we could use this user setting to define the locale of the email template (which can be changed later or not).

Today, the "Working languages" parameter is a multi-value parameter (checkbox), I think it could be replaced by a form with radio buttons, to impose only one choice.
When a user registers, he can choose this setting, which could be set to the browser language by default (if this language is available in the enabled locales for the forms, otherwise it is set to the default locale of the log).

Actually, I don't see where and how the "working languages" setting is used. Can you explain me @natewr or @asmecher?
Thanks in advance

And the problem persists when registering a new evaluator: by default, there is no way to know which language he will prefer.
Maybe we could add the language choice setting when registering a new evaluator (and creating a new user).

I currently have time to develop this feature - and our journals need it - so let me know if this is the way I should go.
Thank you

**Comment by NateWr** [comment] 2022-02-14 15:37
@forgive38 the working languages feature is not currently used. If you're interested in working on this, I have some thoughts and I think that we'd be open to a PR. Can you open a new issue and make a proposal with some use cases, keeping #6221 in mind as well? I think the key will be getting right the workflow when a user should be asked to provide it. Existing data shows that very few users have selected a working language, which isn't a surprise since they'd have to go looking for it.

**Closed** 2022-03-07 14:34 UTC
Labels: Community Priority, Enhancement
