### ISSUE TITLE
OPS -- last check box on first Submit form missing

### ISSUE THREAD

**Issue by anton-vrba** [pkp/pkp-lib#8013] opened 2022-06-19 15:25 UTC
**Describe the bug**
This Bug is browser dependant that is it appears in Chrome and MS Edge, works correctly in Firefox and Opera browsers
Chrome: Version 102.0.5005.115 (Official Build) (64-bit)
Edge: Version 102.0.1245.44 (Official build) (64-bit)
Firefox: Version 101.0.1 (64-bit)
Opera: Version: 88.0.4412.40

**To Reproduce**
On a virgin installation using PHP 7.3, create a user and the submit a paper. The checkbox for "Yes, I agree to have my data collected and stored according to the privacy statement" is missing

**What application are you using?**
  OPS version 3.2.1-2 through 3.3.0-19

**Additional information**
see attached screenshot:
![Clipboard01](https://user-images.githubusercontent.com/34773801/174487793-82f8e7b6-0cac-4b78-a2f6-b533425500a0.png)

**Comment by NateWr** [comment] 2022-06-23 12:14
Unfortunately, I was unable to reproduce this using Chromium version 103.0.5060.53 on the `stable-3_3_0` branch or the [3.2 test drive install](https://pkp.sfu.ca/ops/demo/). I’m going to close this issue for now. Please feel free to provide more details if you are able to find the specific conditions to reproduce the bug.

I would encourage you to post in our [[support forum](https://forum.pkp.sfu.ca/c/questions/5)](https://forum.pkp.sfu.ca/c/questions/5). You will find more help there than we are able to provide here.

I was unable to reproduce . @anton-vrba I'm going to close

**Closed by NateWr** 2022-06-23 12:14 UTC
