### ISSUE TITLE
Numbers on Submission List Tabs

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3395] opened 2018-02-17 19:34 UTC
Consider adding numbers to the tabs on the submission list.

For example:

My Assigned (22)  Unassigned (0)  All Active (56)  Archives (124)

This is particularly important for highlighting any unassigned submissions which may be getting overlooked if no one decides to visit that tab to check, but also provides a nice "at a glance" overview of the overall work in progress.

**Comment by NateWr** [comment] 2018-03-06 14:58
Duplicate of #2617

**Closed by NateWr** 2018-03-06 14:58 UTC
Labels: UI/UX Review
