### ISSUE TITLE
Improve internal submission data reporting

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#2820] opened 2017-09-27 08:37 UTC
The 2017 sprint produced a document proposing two reports (submissions and reviewer reports), which detailed the fields required, set priorities and noted errors in the existing data set.

https://docs.google.com/spreadsheets/d/e/2PACX-1vS9mypS4nXwcQcsdVUv0kmjjHFhLKJY21jWUUIPs0CT20dla825Z7ACxfGMMOC2FuKYHqVxLnRV6N_i/pubhtml#

Further information can be found in the sprint report post:

https://pkp.sfu.ca/2017/09/26/pkp-2017-sprint-report-internal-statistics/

There are three broad tasks:

1. Add missing data to existing reports, or create reports where missing.
2. Correct faulty data in existing reports.
3. Add some kind of visual display of key internal stats.

Related issues: #1265, #2061

**Comment by Baytan** [comment] 2018-11-06 08:07
I learned that the submission and last decision dates will be added to the article reports. It is very good and thanks. But, I think first decision date is also important as some journals report the first decision date to authors to express how fast they process.

In short, I think additional to the submission and final decision dates, first decision date should be added to the reports. Thank you all.

**Comment by bozana** [comment] 2018-12-03 13:10
Review Report now contains the following columns:
```
Stage
Round
Submission Title
Submission ID
Reviewer
Given Name
Family Name
ORCID iD
Country
Affiliation
Email
Reviewing interests
Date Assigned
Date Notified
Date Confirmed
Date Completed
Date Acknowledged
Unconsidered
Date Reminded
Response Due Date
Response Overdue Days
Review Due Date
Review Overdue Days
Declined
Recommendation
Comments On Submission
```
The report row represents, as till now, one reviewer assignment, which I think is correct. Because of that, the assigned editors as well as decision do not make much sense in this report -- they will just be repeated for each row of a submission. Furthermore, this data is considered in the article report, so I believe there is not need to consider it here?
The following additional reviewer data are added, as wished: e-mail, ORCID, country, affiliation. We do not have gender any more, so this is not possible to consider.
I hope, all wished dates are now considered? -- Eventually I do not understand some terms from the google doc correctly...
What exactly do those "# Times ..." for a reviewer review mean?
@jmacgreg (and eventually @NateWr), could you take a look at this new columns list and the one from the google doc i.e. from the requirements and tell me if you think that something is missing or should be differently or ...?

**Comment by alexxxmendonca** [comment] 2018-12-03 13:15
> Because of that, the assigned editors as well as decision do not make much sense in this report -- they will just be repeated for each row of a submission. Furthermore, this data is considered in the article report, so I believe there is not need to consider it here?

I'm not so sure about this. One would have to cross data between reports if one needs to find out which editors were assigned and what was the final decision.

> What exactly do those "# Times ..." for a reviewer review mean?

It stands for "Number of times". Just replace the # to "Number of" ;)

**Comment by bozana** [comment] 2018-12-03 13:22
> It stands for "Number of times". Just replace the # to "Number of" ;)
But if a report row is only for one submission and one reviewer: a reviewer will only once be invited/acknowledged etc.
If this is a general reviewer information of the reviewer, it will be again duplicated for each row with one and the same reviewer.
Thus, maybe @jmacgreg and @NateWr and/or other could also tell what they think about those duplication of information in reports... i.e. if there could eventually be a better way... depending on the most requirements...

**Comment by jmacgreg** [comment] 2018-12-03 14:48
Hi @bozana, this looks great! I'll review it myself, and will be having Minnesota review it as well. They can probably get any comments back within a week. 

In terms of use cases, I think there's a case to be made, over time, for a high-level Production report (ie. the current Articles report) that provides information on the submission's activity per stage, including dates; and a more detailed Reviews report, which is what we have here. In both cases, some duplication of content will be inevitable. In the case of the Reviews report, I think it's important for the managing editor/editorial team to see the assigned reviewer and the decision from that review stage, if available. But less important than the content already included.

**Comment by alexxxmendonca** [comment] 2018-12-03 15:10
> To determine whether we should put the assigned editors and final decision information into the reviewer report, I think we need to decide what use-cases we want to support. Are the reports meant to be a raw data dump that will be processed in some way? Or do we treat them as something for non-technical end users to look through line by line?

I think it's best if we go for a data dump approach. OJS itself shouldn't necessarily provide highly elaborated reports since it is not its core purpose. However, it should provide enough data to be exported and imported in a tool that was designed specifically for data manipulation (for example, Excel).

I am in favor of providing as much data as possible and the journal can just get rid of the columns/data that they are not interested.

**Comment by bozana** [comment] 2018-12-03 15:42
The article report will now contain the following columns:
```
Submission ID
Title
Abstract
Given Name (Author X)
Family Name (Author X)
ORCID iD (Author X)
Country (Author X)
Affiliation (Author X)
Email (Author X)
URL (Author X)
Bio Statement (e.g., department and rank) (Author X)
Given Name (Editor X)
Family Name (Editor X)
ORCID iD (Editor X)
Email (Editor X)
Editor Decision Y (Editor X)
Date decided Y (Editor X)
Date submitted
Last modified
Section title
Language
Status
```
Gender is again not there, because we do not have this information.
Having all decisions + corresponding date decided for each editor (editor = editor + sub editor) provides really all decisions made + the information by whom + showing if it is just a recommendation or a decision.
Status corresponds to the "Current task" from the google document, I think.
Here again, the review information is not included, as there is the review report for that.
Regarding the dates: the last decision date is not explicitly displayed (because all decisions and their dates are listed), as well as "Days since..." because I thought the user can calculate them then in Excel.

Note: we export the data in CSV format, that can be included in Excel or Calc and calculated/managed further as wished...

To all (@jmacgreg, @NateWr, @alexxxmendonca): OK so?

**Comment by alexxxmendonca** [comment] 2018-12-03 15:46
I understand not adding all the information regarding peer review rounds, but perhaps just a "# of reviews" field?

**Comment by bozana** [comment] 2018-12-03 15:53
PRs:
https://github.com/pkp/reviewReport/pull/19
https://github.com/pkp/ojs/pull/2201
https://github.com/pkp/pkp-lib/pull/4280

**Comment by bozana** [comment] 2018-12-03 15:53
i.e. the changes are in my repositories, branch 2820... -- for testing...

**Comment by asmecher** [comment] 2018-12-17 19:51
@bozana, could you back-port this to the `ojs-stable-3_1_1` branch/repos as well? Thanks!

**Comment by asmecher** [comment] 2018-12-17 19:55
(Rescheduled tentatively so I don't forget -- not confirmed!)

**Comment by bozana** [comment] 2019-01-13 11:51
@jmacgreg and @asmecher, I've rebased the changes with the current stable-3_1_2 branch -- s. the PRs above. 
@jmacgreg, is the branch stable-3_1_2 enough for Minnesota to be able to review it?

When all OK, I will then rebase with the current master as well...

**Comment by jmacgreg** [comment] 2019-01-14 14:34
Hi @bozana, yep, that will be perfect! I'll be setting up a new review branch for them this week. We'll get any comments back ASAP.

**Comment by jmacgreg** [comment] 2019-02-11 14:42
FYI I've reviewed these, with Minnesota, and all looks good! This can be closed AFAIK.

**Comment by bozana** [comment] 2019-02-11 17:49
Thanks a lot @jmacgreg! I will then rebase and merge with stable-3_1_2 and cherry-pick to master...

**Comment by bozana** [comment] 2019-02-14 09:18
merged, thus closing...

**Closed by bozana** 2019-02-14 09:18 UTC
Labels: Hosting, Major Feature, Sponsored Development
