### ISSUE TITLE
[OJS] registration form  field " Reviewing interests" wrongly open on ORCID

### ISSUE THREAD

**Issue by promedacademy** [pkp/pkp-lib#6789] opened 2021-02-24 18:14 UTC
I have OJS 3.3.0-3
in the registration form when the field " Reviewing interests" is filled it does not retrieve a list of interest , and on click it wrongly open a new window on ORCID website the HTML section shows the following code:
<fieldset class="reviewer"> <div class="fields"> <div id="reviewerOptinGroup" class="optin"> <label> <input type="checkbox" name="reviewerGroup[16]" value="1"> Yes, I would like to be contacted with requests to review submissions to this journal. </label> </div> <div id="reviewerInterests" class="reviewer_interests is_visible"> <label> <span class="label"> Reviewing interests </span> <input type="text" name="interests" id="interests" value=""> </label> </div> </div> </fieldset>

**Comment by asmecher** [comment] 2021-02-24 20:32
Duplicate of: https://github.com/pkp/pkp-lib/issues/6788

**Closed by asmecher** 2021-02-24 20:32 UTC
