### ISSUE TITLE
Infinite spinning circle when editing journal section and clicking on save

### ISSUE THREAD

**Issue by israelcefrin** [pkp/pkp-lib#8751] opened 2023-03-07 01:22 UTC
**Describe the bug**
When editing a journal section the action "save" remains as a infinite spinning circle and doesn't return as a success. It saves the selected options though.

**To Reproduce**
1. Go to 'Dashboard > Journal > Sections'
2. Click on 'Edit' any section
3. Check any option from 'Section Options' 
4. Scroll down and click 'save' button
5. See the error

**What application are you using?**
OJS version 3.4.0rc1

**Additional information**
[journal-section-edit.webm](https://user-images.githubusercontent.com/4992902/223294557-cf3b1a1b-fe67-41a9-a6e0-764b1d15b66f.webm)

**Comment by touhidurabir** [comment] 2023-03-07 09:51
I think the core of the problem is what mentioned at https://github.com/pkp/pkp-lib/issues/8737 . I have tested and for other settings selection, it works fine . I am closing this one as issue https://github.com/pkp/pkp-lib/issues/8737 has better mentioning of core problem .

**Closed by touhidurabir** 2023-03-07 09:51 UTC
Labels: Bug:2:Moderate
