### ISSUE TITLE
Context navigation menu entries can be blank

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4462] opened 2019-02-08 14:07 UTC
3.1.1 and 3.1.2:

In a multicontext install, if one context uses a primary locale disparate with other context's primary locale, and if the user selects a UI language which is different than both the primary locale of the current context, and the supported locales of the other contexts, the assignment of [`$contextsNameAndUrl` in `PageHandler::setupHandler`](https://github.com/pkp/pkp-lib/blob/7c479d9beef84b3bf902133ca47c919af32d7932/controllers/page/PageHandler.inc.php#L192-L195) will provide null localized names.

`Context::getLocalizedSetting()` uses the current application locale, and the current primary locale, but both of these may not exist in the targeted context:
https://github.com/pkp/pkp-lib/blob/7c479d9beef84b3bf902133ca47c919af32d7932/classes/context/Context.inc.php#L330-L341

This will not happen in 3.2 because of the "fetch first available" fallback of `DataObject::getLocalizedData()`:
https://github.com/pkp/pkp-lib/blob/6de0632d594609dd4631dbbd9606390c4ff5f09d/classes/core/DataObject.inc.php#L61-L68

**Comment by ctgraham** [comment] 2019-02-08 20:41
An alternate approach to the above pull request might be to change `Context::getLocalizedName()` so that it tries `$this->getLocalizedSetting('name', $this->getPrimaryLocale())` if `$this->getLocalizedSetting('name', $preferredLocale)` returns `null`.

**Comment by asmecher** [comment] 2019-02-08 22:33
@defstat, would you mind reviewing this?

**Comment by defstat** [comment] 2019-02-17 17:38
@ctgraham Could you provide some steps in order to reproduce the issue?

I made the following steps:
1. created 2 contexts on an OJS installation
2. The first context has the following language configuration:
![image](https://user-images.githubusercontent.com/560456/52916625-a6948c80-32ea-11e9-9d3f-497d30ef03b4.png)
3. The second context has the following language configuration:
![image](https://user-images.githubusercontent.com/560456/52916641-cd52c300-32ea-11e9-8bb1-a9e93d1c849a.png)

So that the first context uses a primary locale disparate with other context's primary locale. Now the user selects English as a UI language:
![image](https://user-images.githubusercontent.com/560456/52916673-2b7fa600-32eb-11e9-9e9d-68a30c08284c.png)
which is different than both the primary locale (Ge) of the current context (first one), and the supported locales of the other contexts (the second context does not support English for any of the UI, Forms, Submissions). After those steps, should the navigation menus be blank?

**Comment by ctgraham** [comment] 2019-02-18 15:33
Using OJS 3.1.1-4

Site settings: enable German, English, Spanish, French.
![image](https://user-images.githubusercontent.com/7001322/52960991-f49ba580-3367-11e9-949c-e7b8b6f62989.png)

Spanish journal: supports English and Spanish:
![image](https://user-images.githubusercontent.com/7001322/52961048-14cb6480-3368-11e9-9eb6-46dd2c73a992.png)

German journal: supports English and German
![image](https://user-images.githubusercontent.com/7001322/52961119-36c4e700-3368-11e9-8ef6-389d5ac3831a.png)

English journal: enable only English
![image](https://user-images.githubusercontent.com/7001322/52961177-56f4a600-3368-11e9-9e39-c5c73ebb3bbb.png)

Now, navigate to the Spanish journal, and switch the language to Spanish.  German and English journal names are lost.
![image](https://user-images.githubusercontent.com/7001322/52961291-9b804180-3368-11e9-9c04-ab4b973a5f55.png)

**Comment by defstat** [comment] 2019-02-19 17:50
@ctgraham Thanks! I see now. I thought that you were referring to the Site's navigation menu items (not the administrative pages ones, I was looking for the wrong thing). 

At you configuration, and by using the fix, should the site menu display all three journal name?

**Comment by ctgraham** [comment] 2019-02-21 20:32
Yes, cherry-picking this commit into ojs-stable-3_1_1 causes the menu to show the journal name for each:
![image](https://user-images.githubusercontent.com/7001322/53199675-b9120d00-35ed-11e9-86ff-610b7e791f93.png)

**Comment by defstat** [comment] 2019-02-22 16:53
Yes on 3.1.2, the above mentioned configuration shows only the spanish one I think.
Otherwise the code seems fine.
In any case, that fix shows more journals than the current stable branch. Have you checked the code against OMP?  

@ctgraham have you made any pull requests regarding that so the tests can run on OJS and OMP?

@asmecher if we are ok with the above mentioned functionality (which is better that the current one, but some journals are missing with that fix too), the fix can be merged, after the tests are passed.

**Comment by asmecher** [comment] 2019-02-22 20:20
Looks good, @defstat, I've merged that. Leaving open as it still looks like you're working with @ctgraham on other details.

**Comment by asmecher** [comment] 2019-02-28 20:25
@defstat and @ctgraham, it looks like the 3.1.2 work for this one is done, but I'm not sure if there is more work to be done e.g. on the `master` branch. Punting to 3.2 pending your feedback.

**Comment by ctgraham** [comment] 2019-02-28 20:29
There is something NQR about the ability for the current code being able to leave a blank menu item (Spanish journal in Spanish missing the German name), but it is substantially improved over having all blank navigation.

There is no need to forward port to 3.2, unless we want to improve the logic of selecting a desired translation.  3.2 will universally fill in the first available translation if the translation for the requested locale is not present.

**Comment by asmecher** [comment] 2019-02-28 20:41
OK, thanks. I'll consider this a WONTFIX for 3.1.2 if it's almost-but-not-quite-right, as it already sounds resolved in 3.2. Barring a lot of confusion from users, or a sudden interest on someone's part in sending in a PR :)

Thanks, @ctgraham!

**Closed by asmecher** 2019-02-28 20:41 UTC

**Comment by ctgraham** [comment] 2019-03-01 16:29
The issue with my Spanish view of the German journal was the the German journal didn't have any data in the German locale for the Journal Title.  I'm not sure how the data entry error occurred, but the functional change of this PR is correct when the German journal has a title in the journal's default locale.
