### ISSUE TITLE
Make a preview link in OMP

### ISSUE THREAD

**Issue by neffe** [pkp/pkp-lib#5299] opened 2019-11-26 13:46 UTC
In OJS you have the opportunity to see a preview of your issue before you actually publish it. It would be nice if the same opportunity existed in OMP.
Best 
Niels Erik

**Comment by pmangahis** [comment] 2021-03-31 20:20
+1 from hosting

**Comment by ajnyga** [comment] 2021-04-30 10:39
+1 we also got this request.

@asmecher can you assign this for me, I will take a closer look

**Comment by asmecher** [comment] 2021-04-30 16:01
Absolutely, thanks!

**Comment by ajnyga** [comment] 2021-05-03 12:53
ping @asmecher 
OMP: https://github.com/pkp/omp/pull/970
pkp-lib: https://github.com/pkp/pkp-lib/pull/7011

I will do a pr for OJS if the concept is ok. 

Not especially the change to OmpPublishedSubmissionRequiredPolicy.inc.php. It should be ok, because the published status is checked in the catalog handler. The other option is of course to change the authorization policies to match the ones in OJS article handler. 

Do we want to move the `submission.viewingPreview` translation string to pkp-lib? Some translations mention "article", the en_US does not. We could of course have an own translation in OMP as well.

**Comment by NateWr** [comment] 2021-05-03 14:16
Thanks @ajnyga. I'll let Alec do the code review. Can I request that we write some tests for this? We had a regression in the past with this feature in OJS, and accidentally exposed some unpublished items, so let's write an automated test to try to catch problems with this in the future.

Here is the test for OJS as a basis: https://github.com/pkp/ojs/blob/main/cypress/tests/data/60-content/AmwandengaSubmission.spec.js#L195-L219

**Comment by asmecher** [comment] 2021-05-03 14:48
Thanks, @ajnyga! This essentially moves part of the preview implementation from OJS's `IssueAction` class into pkp-lib; that's great but can the relevant parts of OJS use these too instead of repeating the implementation?

**Comment by ajnyga** [comment] 2021-05-03 16:25
@asmecher yes that is the plan when I do a pr for OJS as well here.

**Comment by ajnyga** [comment] 2021-05-03 16:30
what about the translation string `submission.viewingPreview`? Should I move it to pkp-lib and add fuzzy to other locales?

**Comment by asmecher** [comment] 2021-05-03 16:51
> Should I move it to pkp-lib and add fuzzy to other locales?

Yes, that would be perfect, thanks!

> yes that is the plan when I do a pr for OJS as well here.

You're ahead of me as usual :) Please go ahead!

**Comment by ajnyga** [comment] 2021-05-06 15:41
OJS: https://github.com/pkp/ojs/pull/3125
OMP: https://github.com/pkp/omp/pull/970
lib: https://github.com/pkp/pkp-lib/pull/7011

Still missing the new test for OMP

**Comment by ajnyga** [comment] 2021-05-06 20:20
> Thanks @ajnyga. I'll let Alec do the code review. Can I request that we write some tests for this? We had a regression in the past with this feature in OJS, and accidentally exposed some unpublished items, so let's write an automated test to try to catch problems with this in the future.
> 
> Here is the test for OJS as a basis: https://github.com/pkp/ojs/blob/main/cypress/tests/data/60-content/AmwandengaSubmission.spec.js#L195-L219

D. Barnes is an editor right? When the test above turns the publication unpublished, why would the page `index.php/publicknowledge/article/view/9` return 404 like it seems to be expected in the tests - because the editor would just see the preview version from that url, right? Or does `cy.request` fetch the page without the user's session?

**Comment by ajnyga** [comment] 2021-05-07 12:08
So this OJS test https://github.com/pkp/ojs/blob/main/cypress/tests/data/60-content/AmwandengaSubmission.spec.js#L206 has an url pointing to a different submission than `AmwandengaSubmission`. The submission with ID 9 is `FpaglieriSubmission` and it is not yet in the system when that test is run.

Also, if we change the url to `/index.php/publicknowledge/article/view/1 ` which will then point to `AmwandengaSubmission`, it will return 200, because dbarnes is logged in.

But in case I have misunderstood something, I will not create a pr for OJS yet.

**Comment by NateWr** [comment] 2021-05-10 10:02
Yep, that all sounds right. Use `submission.id` instead of `9` and log `dbarnes` out. You can log out by adding `cy.logout()` in the test.

**Comment by asmecher** [comment] 2021-05-14 19:34
Fixed the issue with the assumed submission ID in the URL: https://github.com/pkp/ojs/commit/a3bc974a2a7e50c703cdbb8b9030dd275a9657ba

**Comment by pmangahis** [comment] 2021-08-24 17:41
+ 1 from another hosted press

**Comment by alexdryden** [comment] 2022-03-10 18:01
I've also received a request for a preview feature. Checking to see if there is any work remaining on this feature or its tests and offering my assistance.

**Comment by asmecher** [comment] 2022-03-10 21:08
@ajnyga, I see PRs above (https://github.com/pkp/pkp-lib/issues/5299#issuecomment-833625351) -- what was their latest status?

**Comment by nils-stefan-weiher** [comment] 2022-08-30 08:18
Hi everyone,

is this part of the 3.4 release? The issue seems not to be part of the milestone, but PRs are already there?

**Comment by ajnyga** [comment] 2022-11-30 07:24
pkp-lib: https://github.com/pkp/pkp-lib/pull/7011
OJS: https://github.com/pkp/ojs/pull/3125
OMP: https://github.com/pkp/omp/pull/970
OPS: https://github.com/pkp/ops/pull/397

This is for both https://github.com/pkp/pkp-lib/issues/5299 and https://github.com/pkp/pkp-lib/issues/8090

**Comment by asmecher** [comment] 2022-12-08 00:32
I think I see one fatal error for OMP and OPS -- otherwise this looks good. https://github.com/pkp/pkp-lib/pull/7011/files#r1042809567

**Comment by ajnyga** [comment] 2022-12-09 19:55
@asmecher made the changes and rerun the tests

**Comment by asmecher** [comment] 2022-12-13 16:03
All merged, thanks!

**Closed by asmecher** 2022-12-13 16:03 UTC
Labels: Hosting, Enhancement:1:Minor
