### ISSUE TITLE
Uploaded article CSS file for HTML galley doesn't work

### ISSUE THREAD

**Issue by jmacgreg** [pkp/pkp-lib#296] opened 2015-01-20 05:24 UTC
Uploaded article CSS files don't seem to be correctly referenced by OJS, so their styles aren't applied to the article page. You can see this in the following example: 

http://barnboken.net/index.php/clr/article/view/185/html_4

This article has had a CSS file uploaded (originally titled clr_stylesheet.css, and referenced in the original HTML file). It is linked to within the OJS header as: 

http://barnboken.net/index.php/clr/article/viewFile/185/html_4/717

... but isn't picked up/used. I don't know if this is because it doesn't end in ".css" or what.

**Comment by ctgraham** [comment] 2015-01-20 14:06
The stylesheet is being ignored because it is being transferred with a text/plain MIME type.  https://github.com/pkp/pkp-lib/pull/165 was intended to mitigate this.  If you article_files.file_type specifies "text/plain" for this file_id, and if https://github.com/ulsdevteam/pkp-lib/commit/8ec7dfa4402b222e4df499965f85c01869d57009 was in place at the time of upload, I'd be curious as to how the logic missed it.

**Comment by asmecher** [comment] 2015-02-13 21:42
That install still uses OJS 2.4.3. This is a dupe of #165.

**Closed by asmecher** 2015-02-13 21:42 UTC
Labels: Open Journal Systems
