### ISSUE TITLE
OAI Article datestamps not always updated after modification/republish

### ISSUE THREAD

**Issue by emmauhl** [pkp/pkp-lib#7713] opened 2022-02-17 18:45 UTC
**Describe the bug**
The datestamp of an article record is not always updated after it has been modified and republished, but it should because the record is modified.
There are 2 cases when an article is modified and republished in OJS.

1. Only the article is unpublished > modified > republished. In this case, the `datestamp`  of the article is not updated

2. The issue is unpublished > the article is modified > the issue is republished. In this case the `datestamp`  is updated

This is a problem for C-Joe (Erudit's harvesting tool) since harvesting works based on a record's `datestamp` . So, if a journal makes corrections to an article (example, updated the PDF), but only unpublished/published the article and not the issue, the changes will go undetected.

**To Reproduce**
1. Unpublish an existing article
2. Modify the article
3. Republish the article
4. The `datestamp` will not be updated.

**What application are you using?**
OJS 3.3.0-4 (Coalition Publica test instance)

**Additional information**
I'm reporting this on behalf of our friends at Erudit as it's impacting record harvesting for Coalition Publica. I will ask one of the Erudit technical staff to keep an eye on this issue so that they can field any questions since I am mostly acting as a messenger here. :) This was also [previously reported on the forum](https://forum.pkp.sfu.ca/t/ojs-3-3-0-7-oai-doesnt-update-the-datestamp-to-the-date-of-the-last-update-to-allow-metadata-harvest/69677) with a potential solution but it doesn't look like the poster opened an issue.

**Comment by NateWr** [comment] 2022-02-21 11:29
> If a journal makes corrections to an article (example, updated the PDF), but only unpublished/published the article and not the issue, the changes will go undetected.

This is working as intended. Journals should _always_ create new versions when making a change to an article. Trying to hide these changes by unpublishing/republishing is a misuse of the software and bad practice.

**Comment by pigeonm** [comment] 2022-02-22 19:13
Hi Nate,

Thanks for your answer.

We raised the problem because we need the datestamp to change when corrections are made to an article. 

Since OJS allows to do it and there is no warning that tells the user not to do it, I don't see why a user should avoid doing this (especially since there is only the notion of “articles” in the OAI). Under these circumstances, unpublish > correct > republish an article is not done with the intention of hiding the changes made to the article, it is done because OJS allows it. 

So would it be possible to disable this functionality (unpublish/republish an article) or to update the datestamp when someone unpublish/republish an article?

Thanks again

**Comment by NateWr** [comment] 2022-02-23 09:50
It would be possible to write a plugin to disable the unpublish API endpoint. But I wouldn't advise doing this. A publication might need to be unpublished due to human error when publishing it or when an article is retracted/removed due to harm caused. 

I would have loved to have made unpublishing harder/impossible, in order to enforce a more honest editorial record, but when I proposed this there was strong pushback from the community. :shrug:

**Comment by pigeonm** [comment] 2022-02-23 14:23
So, why not simply update the datestamp?

**Comment by NateWr** [comment] 2022-02-23 15:07
Apologies, I may have made a bad assumption here. I'm not that familiar with OAI. I assumed we were talking about an article's publication date. 

@asmecher is the "datestamp" in an OAI record different from publication dates? After a quick look, I tracked it down to the `last_modified` column, but this should be getting updated when a publication is re-published:

https://github.com/pkp/ojs/blob/main/classes/oai/ojs/OAIDAO.inc.php#L255

**Comment by pigeonm** [comment] 2022-02-23 15:16
No problem! Emma's initial post describes the problem well, but if you need I can try to provide more information / context. 
Thanks again!

**Comment by asmecher** [comment] 2022-03-01 17:52
Re-opening so this doesn't get lost -- but I believe it's a duplicate of https://github.com/pkp/ojs/pull/3197, which has already been fixed. The fix will be released in 3.3.0-9 shortly.

**Comment by asmecher** [comment] 2022-03-01 17:53
@emmauhl, can you confirm that https://github.com/pkp/ojs/pull/3197 appears to match what you've seen?

**Comment by asmecher** [comment] 2022-03-03 20:51
Closing unless there is further feedback!

**Closed by asmecher** 2022-03-03 20:51 UTC
