### ISSUE TITLE
[OMP] author can’t indicate revisions are complete

### ISSUE THREAD

**Issue by crism** [pkp/pkp-lib#1150] opened 2016-02-16 20:48 UTC
From #1127, against `HEAD`:

There does not seem to be a way for the author to indicate that revisions are complete. They can upload files… but how does the editor know they’re done?

**Comment by crism** [comment] 2016-02-16 20:58
This also applies to copy edits; how does the copyeditor signal completion?

**Comment by asmecher** [comment] 2016-02-16 21:00
The new "discussions" area is where communication about copyediting takes place. They would use that to compose a message to the editor.

**Comment by crism** [comment] 2016-02-16 21:27
Thanks, @asmecher. That was definitely not clear to our role-playing group; at a minimum, this needs to be addressed via the on-screen documentation. It does seem like a hand-off process to us, though.

**Comment by asmecher** [comment] 2018-01-06 01:35
Duplicate of https://github.com/pkp/pkp-lib/issues/2665.

**Closed by asmecher** 2018-01-06 01:35 UTC

**Comment by bozana** [comment] 2018-02-13 06:36
This will be solved together with https://github.com/pkp/pkp-lib/issues/3278
