### ISSUE TITLE
Displaying the catalog's file fails

### ISSUE THREAD

**Issue by defstat** [pkp/pkp-lib#6425] opened 2020-12-04 14:53 UTC
**Describe the bug**
Displaying the catalog's file fails

**To Reproduce**
1. Go to a Monograph's page
2. Click on the button that refers to the monograph's file, in order to view it
3. The page `catalog/view` page is shown but it is empty
4. Browser report javascript error

**What application are you using?**
 OMP 3.3

**Additional information**
The problem seems to be related to the version of `pdf.js`. The current implementation uses v2.0. Check bellow
`https://github.com/mozilla/pdf.js/issues/10289`
`https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html`

There is a composer package that could be probably used `https://packagist.org/packages/clean-composer-packages/pdf-js`

**Comment by defstat** [comment] 2020-12-04 14:56
@NateWr @asmecher 

**PR**
OMP: pkp/omp#892

**Comment by NateWr** [comment] 2020-12-04 16:07
I'm not able to reproduce this myself. Presumably it depends on the PDF being shown? Can you share the PDF (privately if it's not public)?

**Comment by defstat** [comment] 2020-12-04 16:17
I have send you the PDF on slack, but I don't think it is that. The javascript error was `Uncaught ReferenceError: PDFJS is not defined`.

On the other hand it could be a Windows error, because of the native `\` backslashes - it could be a case that the script's source is not getting loaded because of the `\` not being escaped. I will check again.

**Comment by defstat** [comment] 2020-12-22 12:07
@asmecher @NateWr 

**PR**
[OMP]: pkp/omp#902

This PR fixes the "PDF not getting displayed". 

I am still getting the `Uncaught ReferenceError: PDFJS is not defined` error on my Chrome console, but with no obvious consequences. If you are not getting the same JS error, it could be my installation.

**Comment by asmecher** [comment] 2021-01-05 00:07
@defstat, are you seeing backslashes in the plugin's URL on Windows? I think the proposed change will at least stop it from breaking the string, but that still seems wrong to me -- backslashes shouldn't appear in the URLs.

**Comment by defstat** [comment] 2021-01-08 16:08
@asmecher yes. The "problem" is that the code is mixing filepaths and urls to create urls. Most of the time the code uses `DIRECTORY_SEPARATOR` for concatenating paths together (and urls also). On Windows `const DIRECTORY_SEPARATOR = \;`. That is introducing the backslash in the url path. 

For example, regarding this issue, there is [https://github.com/pkp/omp/blob/b05abbbc624ec642ede1f8d88422b715ccef0677/plugins/generic/pdfJsViewer/PdfJsViewerPlugin.inc.php#L79] where the plugin url is being set for the `display.tpl` page. I have changed the "pkp/omp#902" PR to remove the backslashes. (the `Uncaught ReferenceError: PDFJS is not defined` remains though, without causing apparent problems to the display of the file)

**Comment by NateWr** [comment] 2021-01-11 11:12
:+1: 

Presumably this code, which defines `DIRECTORY_SEPARATOR`, can be removed now? https://github.com/pkp/pkp-lib/blob/master/includes/bootstrap.inc.php#L28-L31

**Comment by asmecher** [comment] 2021-01-11 20:59
Ah, I see the problem (and the fix). @defstat, that looks good, but there's an unnecessary change to `plugins/generic/pdfJsViewer/templates/display.tpl`; could you remove that?

**Comment by defstat** [comment] 2021-01-13 18:22
@asmecher removed.

**Comment by asmecher** [comment] 2021-01-13 18:31
Merged -- thanks, @defstat!

**Closed by asmecher** 2021-01-13 18:31 UTC
Labels: Bug
