### ISSUE TITLE
Can't delete a component type

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#8782] opened 2023-03-11 02:04 UTC
When you try to delete a component type in OJS 3.4 (testing), nothing happens.

**To Reproduce**
1. Go to Workflow Settings > Components
2. Click Delete below a component type'
3. Confirm you want to delete it
4. See that nothing happens

**Comment by jonasraoni** [comment] 2023-03-11 05:26
Closing as duplicate of https://github.com/pkp/pkp-lib/issues/8735

**Closed by jonasraoni** 2023-03-11 05:26 UTC
Labels: Bug:2:Moderate
