### ISSUE TITLE
Search within Plugin Gallery leads to wrong plugin

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#4636] opened 2019-03-25 14:42 UTC
### Description:
When searching within the Plugin Gallery, the search results are filtered, reindexing the rowid within the grid, but this reindexing is not considered when clicking through the link.  E.g. `$$$call$$$/grid/plugins/plugin-gallery-grid/view-plugin?rowId=1` will always represent the first plugin on the unfiltered list.
### Steps to reproduce:

1. Settings -> Website -> Plugins -> Plugin Gallery (Note the plugin listed first, e.g. `Hypothes.is`)
2. Search of a specific plugin: "Quick" (Note one or more results, the first of which may be `QuickSubmit`)
3. Click on the first link (`$$$call$$$/grid/plugins/plugin-gallery-grid/view-plugin?rowId=1`)

### Expected Results
Plugin described is the first of filtered results (e.g. QuickSubmit).

### Actual Results
Plugin described is the first of the unfiltered results (e.g. Hypothes.is)

**Comment by asmecher** [comment] 2019-03-25 20:50
@ctgraham, I can't duplicate this behavior on OJS 3.1.2-0; what version are you testing with?

**Comment by ctgraham** [comment] 2019-03-26 12:06
Reported to me on a locally modified 3.1.1-4; confirmed there and then reproduced on stable-3_1_2 ([9b9dc0a](https://github.com/pkp/ojs/commit/9b9dc0adb575e93e60bed6a5bd6afae0e04bcac4)).

**Comment by asmecher** [comment] 2019-03-26 18:09
Yes, so at a glance, what you describe makes sense -- but oddly it's opening the right plugin for me. I'll investigate further.

**Comment by asmecher** [comment] 2019-03-26 18:12
Sorry, I mean no, the rowIds are renumbered starting from 1, so I would expect the behaviour you describe (e.g. presenting information for the wrong plugin), but instead I see the correct behavior.

**Comment by Vitaliy-1** [comment] 2019-03-26 18:27
Can reproduce on OJS 3.1.2 that I've installed from the official release and on the master branch (also it's quite outdated). 
![screencapture-ojs-3-1-2-test-index-php-psp-management-settings-website-2019-03-26-20_26_41](https://user-images.githubusercontent.com/20665587/55023470-89e42680-5005-11e9-936b-7525fb900208.png)

**Comment by asmecher** [comment] 2019-05-13 19:41
Looks good and clear to me, @NateWr -- but were you able to reproduce the problem? I can't figure out why it wouldn't reproduce on my own machine; it clearly should have by my read.

**Comment by NateWr** [comment] 2019-05-14 09:18
Merged. :+1: 

> I can't figure out why it wouldn't reproduce on my own machine

It's confusing, because the title is correct but the description is not. At first I didn't notice, so I'm guessing the same happened with you.

**Closed by NateWr** 2019-05-14 09:18 UTC

**Comment by asmecher** [comment] 2019-05-14 16:22
Ah, that could well be the case. Thanks, @ctgraham and @NateWr!
