### ISSUE TITLE
Strange behavior when using 2+ plugins with the same hook

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#2527] opened 2017-05-15 16:58 UTC
see: http://forum.pkp.sfu.ca/t/empty-publishedarticle-object-for-most-of-the-published-articles/30927
also: http://forum.pkp.sfu.ca/t/making-a-plugin-for-ojs3/30899/16?u=ajnyga
The problem was seen when using recommend by author plugin + embedGalley https://github.com/ajnyga/embedGalley
OR recommend by author + plugin, that I am developing, but on the same hook (I have changed it already) https://github.com/Vitaliy-1/JATSParserPlugin/blob/master/JatsParserPlugin.inc.php#L29

 "symptoms":

- PHP Fatal error: Uncaught Error: Call to undefined method Article::getGalleys() in plugins\generic\embedGalley\EmbedGalleyPlugin.inc.php:147` when trying to call this method with: 
```
$articleArrays = $smarty->get_template_vars('article');
foreach ($articleArrays->getGalleys() as $galley) {
```
- print_r on $articleArrays shows different articles for one article with different locale. For example in English locale I see data from article with id 19 and for Ukrainian - with id 26 (article is the same).

- $smarty->get_template_vars('publishedArticle') becomes empty for most of the articles

Note: this behavior is inconsistent. When using recommend by author + embedGalley I had such problems only in 10% of articles, but when using recomend by author + jatsParser plugin (that I am developing) - in near 70% of articles.

**Comment by asmecher** [comment] 2018-01-05 17:40
@Vitaliy-1, sorry for the lack of response -- is this still an issue?

The most likely cause, I think, is variable clobbering where references are used. For example...

    $templateMgr->assign_by_ref('article', $article);

...then sometime later...

    foreach ($articles as $article) {
        ...
    }

This will clobber the template's copy of the article. I suspect it's one plugin that's behaving badly, and the problem is only apparent in a particular combination of conditions.

For what it's worth, we're decreasing reference use and this will reduce the likelihood of this kind of bug arising.

**Comment by Vitaliy-1** [comment] 2018-01-09 16:58
Hi @asmecher 
Hmm, didn't use recommended by author plugin from that time. It requires additional testing. But think this problem had disappeared after adding a possibility for establishing hook download priority.

**Comment by asmecher** [comment] 2018-01-09 17:02
OK, thanks! I'll close this for now, but let me know if you see something similar again.

**Closed by asmecher** 2018-01-09 17:02 UTC

**Comment by Vitaliy-1** [comment] 2018-01-17 04:58
Hi @asmecher 
There is more information about this problem by the reference.

**Comment by asmecher** [comment] 2018-04-11 22:44
@Vitaliy-1, I'm having trouble replicating this locally, but I think what's probably happening is that one of the other plugins is assigning something different to the `$article` template variable, then the Recommend By Author plugin is using

    $articleArrays = $smarty->get_template_vars('article');

...to fetch what thinks is going to be a `PublishedArticle` object assigned by OJS, but it's turning out to be the `Article` assigned by the other plugin instead. I can't spot where that's happening but I don't know this code well.

**Comment by bozana** [comment] 2018-04-12 11:53
@Vitaliy-1, I also tested this locally with two simple plugins an did not have any problems, neither with `Templates::Article::Main` nor with `Templates::Article::Footer::PageFooter` hook. Thus, maybe to see what other plugins are using that hook in your installation and what are they doing with the `article` object? Or also to test it somehow step-by-step with your plugin, e.g. starting with a very simple situation where you only get `$article = $smarty->get_template_vars('article');` (which should be PublishedArticle object), do not change it and output something very simple, e.g. '<p>bla bla</p>' and so forth? Hmmmm...
