### ISSUE TITLE
I am unable to use html tags in tinyMCE. 

### ISSUE THREAD

**Issue by imaazahmed** [pkp/pkp-lib#6740] opened 2021-02-09 22:05 UTC
Hello mate!

 I am unable to use HTML tags in TinyMCE. I have installed text editor extras but still no result.
 
 I am trying to give line breaks in my abstract but it doesn't work. It's not showing bold or italic text, not working <br/> in my abstract.

Can someone please guide me? I am really stuck. Please see snapshot. In red mark i want to give line break.
![asdasdads](https://user-images.githubusercontent.com/78767924/107434580-c1eaa900-6b4c-11eb-9f11-3fd9e926f861.png)

Thank you!

**Comment by imaazahmed** [comment] 2021-02-09 22:10
When i save this article so it's coverting <br/> into <p></p>. I can't even bold the text. 

![br](https://user-images.githubusercontent.com/78767924/107435078-7dabd880-6b4d-11eb-9fc7-cc3219ead075.PNG)

**Comment by asmecher** [comment] 2021-02-09 22:13
This is a duplicate of https://github.com/pkp/pkp-lib/issues/6734. Please don't post the same issue in several places -- the support forum (where you already have a thread on this) is the best place to get help.

**Closed by asmecher** 2021-02-09 22:13 UTC

**Comment by imaazahmed** [comment] 2021-02-09 22:14
@asmecher  I am not getting reply anywhere. Can you please help me out here?
