### ISSUE TITLE
[OJS] User fields languages displayed for a single language journal on a multi language website

### ISSUE THREAD

**Issue by hcoussy** [pkp/pkp-lib#4855] opened 2019-07-02 14:55 UTC
Hi,

I firstly [posted this issue on PKP forum](https://forum.pkp.sfu.ca/t/ojs-3-1-2-1-user-fields-languages-displayed-for-a-single-language-journal-on-a-multi-language-website/54060)

We are using OJS 3.1.2-1 at University of Bordeaux for several journals.
On website level we have defined 2 languages: French and English and default language is French.
Some of journal are in English only, some are in French only and some in both languages with English or French as primary.

When we edit datas of a user of a journal which is in English only,
the French form fields are also displayed and are mandatory.

Then if I change the default language on website level from French to English, it doesn’t happen any more for this journal but when we edit datas of a user of a journal which is in French only, the English form fields are also displayed and are mandatory.

So we noticed that default language defined on website level has an impact on user fields languages which are displayed in journal level settings.

Is it a problem that could be fixed ?

Thanks in advance for your answer.
Best regards.
Helene

**Comment by asmecher** [comment] 2019-07-10 00:11
Hi @hcoussy! Because user profiles are shared across journals, the required fields are defined based on the site's primary locale, not the journal's. Otherwise you could imagine this scenario...

1. Journal A is primarily English; journal B is primarily French.
2. User registers in Journal A with the required fields filled in English.
3. Editor in Journal B wants to enroll User in Journal B as well. But the fields are not entered in French, so required data is missing.

**Comment by hcoussy** [comment] 2019-07-19 13:00
Hi @asmecher,
I understand your explanation and why you did this. It doesn't fit us because it's not very often that an editor wants to enroll a User from an other journal. 
In everyday use, Editors of Journal B don't understand why they have to fill in fields in English while their journal is in French only and vice versa for Editors of Journal A. I suppose we will have to explain them why they have to do that.
Thanks for your answer.
Best regards.
Helene

**Comment by NateWr** [comment] 2022-09-13 08:46
This is a duplicate of https://github.com/pkp/pkp-lib/issues/6291. Please follow that issue to see discussion on this topic.

**Closed by NateWr** 2022-09-13 08:46 UTC
