### ISSUE TITLE
[OJS] Reading discussion, list of participants missing

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2560] opened 2017-06-02 09:33 UTC
Hi,

OJS3.0.2.

In some cases the `participantsListPlaceholder` here https://github.com/pkp/pkp-lib/blob/master/templates/controllers/grid/queries/readQuery.tpl#L30 is not getting populated. This does not depend on the submission, because the same submission may have both open discussions where you see the participants and also ones where you do not see. Also the amount or role of the participants is not something that seems the affect this. 

This is only an issue with the readQuery.tpl. If you edit the same discussion, the names appear in the editing template.

**Comment by asmecher** [comment] 2017-06-02 15:49
Is there anything relevant in the PHP error log? My first suspicion would be that a PHP error is preventing the JSON message containing the replacement DOM elements from replacing the placeholder.

**Comment by ajnyga** [comment] 2017-06-02 16:06
Hi,

Opening a single discussion from the grid does not cause any errors. However, when I acces the page with the discussion grid, I get these:

```
[Fri Jun 02 19:03:54 2017] [error] [client 192.168.175.49] PHP Fatal error:  Call to a member function getFullName() on a non-object in public_html/cache/t_compile/b8e94e7452f0ac345b40417a528b0eab6ae76dc7^%%B3^B37^B37A62EB%%participants.tpl.php on line 8, referer: https://site.fi/journal/workflow/index/58847/5
[Fri Jun 02 19:04:09 2017] [error] [client 192.168.175.49] PHP Warning:  assert(): Assertion failed in public_html/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.inc.php on line 153, referer: https://site.fi/journal/workflow/index/58847/5
[Fri Jun 02 19:04:09 2017] [error] [client 192.168.175.49] PHP Fatal error:  Call to a member function getLocalizedTitle() on a non-object in public_html/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.inc.php on line 155, referer: https://site.fi/journal/workflow/index/58847/5
```

**Comment by asmecher** [comment] 2017-06-02 16:13
@ajnyga, what do you see in the two quoted lines of code? Looking at OJS 3.0.2, NotificationsGridCellProvider.inc.php is shorter than 155 lines.

**Comment by ajnyga** [comment] 2017-06-02 16:23
ah sorry, there was an old debugging attempt of this same issue there, some escaped print_r commands. This is the same errors with the 3.0.2 stable code:

```
[Fri Jun 02 19:20:15 2017] [error] [client 192.168.xxx] PHP Warning:  assert(): Assertion failed in public_html/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.inc.php on line 150, referer: https://site.fi/journal/workflow/index/58847/5
[Fri Jun 02 19:20:15 2017] [error] [client 192.168.xxx] PHP Fatal error:  Call to a member function getLocalizedTitle() on a non-object in public_html/lib/pkp/controllers/grid/notifications/NotificationsGridCellProvider.inc.php on line 152, referer: https://site.fi/journal/workflow/index/58847/5
[Fri Jun 02 19:20:20 2017] [error] [client 192.168.xxx] PHP Fatal error:  Call to a member function getFullName() on a non-object in public_html/cache/t_compile/b8e94e7452f0ac345b40417a528b0eab6ae76dc7^%%B3^B37^B37A62EB%%participants.tpl.php on line 8, referer: https://site.fi/journal/workflow/index/58847/5
```

**Comment by ajnyga** [comment] 2017-06-07 05:25
I have 111 hits with that query. Most of them are referring to user `0`. 

There are other cases as well (I will look at these later), but clearly something in the code is creating references to '0' user when you add a discussion. The discussions I am looking were created using the 3.0.2. release.

What probably happens is that when you click add participant, you get the pull down with the names:
![screenshot_26](https://user-images.githubusercontent.com/16347527/26863338-b9708b66-4b5a-11e7-99a1-c0c063894cab.png)
BUT if you do not choose any and just click somewhere else, you get this:
![screenshot_27](https://user-images.githubusercontent.com/16347527/26863349-c9cf6f18-4b5a-11e7-912d-8e49002a9b4a.png)

I bet that ends up as user '0' in the database.

I will now just run a query to remove all rows from the query_participants that have user_id = 0.

**Comment by asmecher** [comment] 2017-06-07 15:41
Ooh, interesting, that does sound like a likely cause. @ajnyga, can you confirm whether clearing those out resolves the original problem flagged in this issue?

**Comment by ajnyga** [comment] 2017-06-08 09:34
I will check when I get back, I am pretty sure it will.

**Comment by NateWr** [comment] 2017-06-16 15:35
Just a heads up that the recipient selection process will change in 3.1: https://github.com/pkp/pkp-lib/issues/1447#issuecomment-307835364

**Comment by t4x0n** [comment] 2018-05-04 17:42
Hi, maybe the @ajnyga problem is mine too. A lot of time ago (OJS 3.0.2) I found some discussión with problems, like without user assigned, I assume that was correct with the updates but today I found the problem:

If you open a discussion without assigning an author you receive the error message, but if you don't assign a user and close the windows, and then reload the page, you have this:
![issueojs](https://user-images.githubusercontent.com/5422984/39642707-eb2fd23a-4fa8-11e8-9bd4-d2df47f5f611.png)

the discussion is created but without user assigned... my intention was create a discussion just for my self because I need an textarea for write notes for my self, maybe you can think about that option too ;)

**Comment by ajnyga** [comment] 2018-05-04 18:55
Yes I have noticed that as well. It does not cause any problems, but is a bit annoying. 
I think I have seen it mentioned in another issue somewhere here. Maybe part of a larger issue. But if it can not be found, maybe it is a good idea to start a new issue regarding that bug. 

(and maybe I should check whatever I promised to check in my last message last June(!) :D)

**Comment by asmecher** [comment] 2018-05-04 19:04
I'm pretty quick at fixing these if you can identify a set of steps to reproduce the problem!

**Comment by ajnyga** [comment] 2018-05-04 19:07
If I remember correctly, just start a new discussion but instead of submitting the form just close the modal window with the X button. Then reload the page where you were and you should see  an empty discussion like the in the screenshot.

**Comment by asmecher** [comment] 2018-05-04 19:13
I've fixed a few of these over the last releases -- if there are one or two cases left, they'll probably be specific to the place in the workflow the discussion appears.

**Comment by t4x0n** [comment] 2018-05-04 21:59
I have the 3.1.1 and some patches installed, and the issue appears...  

ok, I know exactly appears!  When you create a discussion, but you need to submit the discussion form with subject and message but without users assigned. 

Try @ajnyga and tell us if you can reproduce it. It seems not cause problems but all Participants can see the discussion empty.

**Comment by ajnyga** [comment] 2018-05-05 05:38
@t4x0n true! If I just will the subject and message and then press submit I get an error for missing participants and if I then just leave the form the empty discussion has appeared to the form. 

The thing you noticed in the update is taken into account here: https://github.com/pkp/pkp-lib/pull/3548. Basically after those changes the active user will always be shown as a discussion participant even if the user is not a stage participant in that submission. This includes admins and editors.

**Comment by NateWr** [comment] 2021-11-18 09:53
Closing this as outdated, but if there is still a problem in `stable-3_3_0` go ahead and file an issue with reproduction steps.

**Closed by NateWr** 2021-11-18 09:53 UTC
