### ISSUE TITLE
[OJS] Configurable options not showing for journals that are not live

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5838] opened 2020-05-07 17:46 UTC
**Describe the bug**
Some tabs in the settings area for journals that were once live but are no longer live are showing empty contents.

**To Reproduce**
1. Have a journal that was once live in OJS 2.x, then changed to no longer live and imported to OJS 3
2. Click on 'Website' - > Settings
3. Navigate through its sub-tabs
4. Notice empty contents

If I try to turn the journal live again on the Administrator list of journals, the modal window doesn't load.

1. Go to Administrator -> Hosted Journals
2. Search for any not-live journals
3. Click "Edit"
4. Modal window doesn't load.

Error log:

```
build.js?v=3.2.0.1:14 TypeError: Cannot read property 'length' of null
    at o.Se (build.js?v=3.2.0.1:8)
    at o.e._render (build.js?v=3.2.0.1:14)
    at o.i (build.js?v=3.2.0.1:14)
    at ri.get (build.js?v=3.2.0.1:14)
    at new ri (build.js?v=3.2.0.1:14)
    at In (build.js?v=3.2.0.1:14)
    at o.Li.$mount (build.js?v=3.2.0.1:14)
    at o.Li.$mount (build.js?v=3.2.0.1:14)
    at init (build.js?v=3.2.0.1:14)
    at h (build.js?v=3.2.0.1:14)
ot @ build.js?v=3.2.0.1:14
at @ build.js?v=3.2.0.1:14
it @ build.js?v=3.2.0.1:14
e._render @ build.js?v=3.2.0.1:14
i @ build.js?v=3.2.0.1:14
ri.get @ build.js?v=3.2.0.1:14
ri @ build.js?v=3.2.0.1:14
In @ build.js?v=3.2.0.1:14
Li.$mount @ build.js?v=3.2.0.1:14
Li.$mount @ build.js?v=3.2.0.1:14
init @ build.js?v=3.2.0.1:14
h @ build.js?v=3.2.0.1:14
p @ build.js?v=3.2.0.1:14
b @ build.js?v=3.2.0.1:14
p @ build.js?v=3.2.0.1:14
(anonymous) @ build.js?v=3.2.0.1:14
An.e._update @ build.js?v=3.2.0.1:14
i @ build.js?v=3.2.0.1:14
ri.get @ build.js?v=3.2.0.1:14
ri @ build.js?v=3.2.0.1:14
In @ build.js?v=3.2.0.1:14
Li.$mount @ build.js?v=3.2.0.1:14
Li.$mount @ build.js?v=3.2.0.1:14
e._init @ build.js?v=3.2.0.1:14
Li @ build.js?v=3.2.0.1:14
init @ build.js?v=3.2.0.1:8
(anonymous) @ VM1358:2
m @ jquery.min.js?v=3.2.0.1:2
Re @ jquery.min.js?v=3.2.0.1:2
append @ jquery.min.js?v=3.2.0.1:2
(anonymous) @ jquery.min.js?v=3.2.0.1:2
z @ jquery.min.js?v=3.2.0.1:2
html @ jquery.min.js?v=3.2.0.1:2
success @ pkp.min.js?v=3.2.0.1:429
u @ jquery.min.js?v=3.2.0.1:2
fireWith @ jquery.min.js?v=3.2.0.1:2
k @ jquery.min.js?v=3.2.0.1:2
(anonymous) @ jquery.min.js?v=3.2.0.1:2
load (async)
send @ jquery.min.js?v=3.2.0.1:2
ajax @ jquery.min.js?v=3.2.0.1:2
a.fn.pkpAjaxHtml @ pkp.min.js?v=3.2.0.1:429
a.pkp.controllers.modal.AjaxModalHandler.modalOpen @ pkp.min.js?v=3.2.0.1:326
a.pkp.controllers.modal.ModalHandler @ pkp.min.js?v=3.2.0.1:312
a.pkp.classes.ObjectProxy.parent @ pkp.min.js?v=3.2.0.1:124
a.pkp.controllers.modal.AjaxModalHandler @ pkp.min.js?v=3.2.0.1:325
a.pkp.classes.ObjectProxy.parent @ pkp.min.js?v=3.2.0.1:124
b @ pkp.min.js?v=3.2.0.1:122
a.pkp.classes.Helper.objectFactory @ pkp.min.js?v=3.2.0.1:120
(anonymous) @ pkp.min.js?v=3.2.0.1:429
each @ jquery.min.js?v=3.2.0.1:2
each @ jquery.min.js?v=3.2.0.1:2
a.fn.pkpHandler @ pkp.min.js?v=3.2.0.1:429
a.pkp.classes.linkAction.ModalRequest.activate @ pkp.min.js?v=3.2.0.1:146
a.pkp.controllers.linkAction.LinkActionHandler.activateAction @ pkp.min.js?v=3.2.0.1:335
a.pkp.classes.Handler.handleEvent @ pkp.min.js?v=3.2.0.1:129
dispatch @ jquery.min.js?v=3.2.0.1:2
y.handle @ jquery.min.js?v=3.2.0.1:2
Show 8 more frames
```

**What application are you using?**
Open Journal Systems 3.2.0.1

**Additional information**
Here is the problem within the journal settings:
![Website Settings](https://user-images.githubusercontent.com/4059679/81326746-a2c86380-9070-11ea-9a36-0b97752960f6.gif)

Here is the problem at the Hosted Journals section:
![Revistas](https://user-images.githubusercontent.com/4059679/81327224-516ca400-9071-11ea-8302-193843d62f5e.gif)

**Comment by asmecher** [comment] 2020-05-07 17:48
This is likely a duplicate of https://github.com/pkp/pkp-lib/issues/5690.

**Closed** 2020-05-14 21:53 UTC
