### ISSUE TITLE
OMP Catalog returns errors: Add Entry and selecting books to Featured and New Releases

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#9313] opened 2023-09-20 10:37 UTC
**Describe the bug**
The Catalog page in OMP returns at least two kinds of errors, when adding an entry and when selecting books to New Releases or Featured.

**To Reproduce**
1. Go to Catalog
2. Click on for example New Release checkbox
3. See error "The requested URL was not recognized."

-

1.  Go to Catalog
2. Click Add Entry
3. Find a book, for example "Kennepohl"
4. Select Kennepohl's book, see error in console: build.js?v=3.5.0.0:317 TypeError: Cannot read properties of undefined (reading 'length')
5. Press save, see error in console build.js?v=3.5.0.0:317 TypeError: Cannot read properties of undefined (reading 'findIndex')

**What application are you using?**
OMP current main branch, possibly the same in 3.4

**Comment by asmecher** [comment] 2023-09-21 19:04
Confirmed in `stable-3_4_0` as well; @Vitaliy-1, could you take a look at this?

**Comment by jardakotesovec** [comment] 2024-02-13 14:10
3.4
ui-library: https://github.com/pkp/ui-library/pull/329
omp (only tests): https://github.com/pkp/omp/pull/1524

**Comment by Vitaliy-1** [comment] 2024-02-13 19:32
Thanks! 
Can you take a look also at `allowCustom` prop: https://github.com/pkp/ui-library/blob/main/src/components/Form/fields/FieldBaseAutosuggest.vue#L122

**Comment by jardakotesovec** [comment] 2024-02-13 20:27
@Vitaliy-1 Sure, do you have some context to it - is something not working with allowCustom? After the change I made in the PR above I don't see any errors with the steps above.

**Comment by Vitaliy-1** [comment] 2024-02-13 21:10
Should it be declared in the `FieldBaseAutosuggest` in the data()?
```js
data() {
  return {
    allowCustom: false,
  };
},
```

**Comment by jardakotesovec** [comment] 2024-02-13 21:20
@Vitaliy-1 It would be nicer, yes. I guess that being undefined works same to allowCustom:false, or is it causing some troubles?
I see that it was probably added because of FieldControlledVocab some specific functionality.

**Comment by Vitaliy-1** [comment] 2024-02-14 07:39
Yes, I see that it's defined in the class `FieldControlledVocab` that extends `FieldBaseAutosuggest` but not in the latter. 
Leaving it up to you whether it requires fixing. 
The above PR solves the issue for me, it also requires porting to the main branch.
Thanks!

**Comment by jardakotesovec** [comment] 2024-02-14 15:23
@asmecher @Vitaliy-1 Fix merged to 3.4 and cherry picked to main. I think this can be closed.

**Closed** 2024-02-14 19:43 UTC
