### ISSUE TITLE
Add Category to article page in OJS

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#4991] opened 2019-08-12 15:47 UTC
The Categories feature was recently added to OJS, allowing Editors and Journal Managers to add a submission to a thematic category and display articles on category pages. A PKP|PS hosted client has requested these additional features:

1. When an author makes a submission they can select a category or categories for the submission
2. The category is displayed with other article metadata on the article page

This would basically amount to Categories operating similarly to other metadata fields in OJS.  Perhaps it could be added to the list of configurable metadata fields under Workflow Settings > Submission Metadata.

**Comment by NateWr** [comment] 2019-08-20 09:50
The first item is a bug. The category selection should appear. See #4864. 

Second item is not addressed elsewhere. We should display it, but I'm hesitant to make it part of metadata. So far, the configurable metadata specifically relates to downstream consumers (indexing services, etc). Categories aren't mapped to metadata in that way and are mostly intended to be an arbitrary grouping device for presentation on the site, so it might be good to keep these separate.

**Comment by NateWr** [comment] 2020-06-08 15:03
Requested in the community forum at https://forum.pkp.sfu.ca/t/categories-on-article-landing-pages/59124/9.

**Comment by thinkbulecount2** [comment] 2020-06-09 20:24
PR: https://github.com/pkp/ojs/pull/2798

cc @NateWr

**Comment by NateWr** [comment] 2020-06-11 08:35
Merged!

**Closed by NateWr** 2020-06-11 08:35 UTC
Labels: Enhancement, Hosting

**Comment by asmecher** [comment] 2020-07-24 22:48
@NateWr and @thinkbulecount2, FYI, part of this didn't get fully back-ported to `stable-3_2_1`: https://github.com/pkp/ojs/commit/c2171d2e6e317e776b40a87d89f12d4eb5327da6 (see https://forum.pkp.sfu.ca/t/ojs-3-2-browse-block-entries-missing-title-and-link/61727/4 for a report in the forum).

**Comment by NateWr** [comment] 2020-07-27 09:02
I think that's a separate issue? I'm not sure any of the work here was intended to be backported. Just flagging that in case there are other dependencies missing, but I think the commit you backported works ok stand-alone.
