### ISSUE TITLE
Add reviewer modal expanding reviewer details javascript error

### ISSUE THREAD

**Issue by procky** [pkp/pkp-lib#6024] opened 2020-06-19 09:36 UTC
In the modal when you click the expand arrow for more details on a reviewer nothing happens and an error appears in the console.

Javascript Error
`TypeError: "e is null" `
in build.js

I have found in the data given to the smarty template if the biography for a reviewer is null it will fail but if it is an empty string or array of locales it works.

Error reproducible on our journal (OJS 3.2.0.1) and also tested using a fresh docker-ojs install.

Reproduce the behaviour:
1. Install OJS. Only noteworthy thing is that I set it up to use 2 locales.
2. Setup an author by registering like a real external author would (/user/register)
3. Logged in as admin I made an editor user too
4. Submit a new submission as the author
5. As admin assign the editor
6. Move the submission to review
7. Open the add reviewer modal and the reviewer will not expand

**Comment by NateWr** [comment] 2020-06-30 13:12
@procky I'm looking into this now but I'm unable to reproduce the issue. It looks like this was addressed as part of the 3.1.2-4 release: https://github.com/pkp/ui-library/commit/1d174448a805e038e0a7bbb9e1079e5681dc9b2d

Specifically, it is this line https://github.com/pkp/ui-library/blob/master/src/components/ListPanel/users/SelectReviewerListItem.vue#L175-L180 where the biography is loaded and that `localize()` call should work correctly even if `biography` is `null`.

I'd recommend trying with a newer release to see if this resolves your issue.

**Comment by awecancer** [comment] 2020-07-02 07:40
@NateWr thank you for looking at it. Helped point me in the right direction.

Disclosure: I am Procky but I am now using this GitHub account.

I can reproduce this error with fresh installs of OJS and can now see the problem. We have users created from registration and they do not get given a biography in the user_settings table. We upgrade our OJS journal using the tar.gz files and in the latest version (3.2.1-1) the localize function is:

`localize:function(e,t){if("undefined"===typeof e)return"";if(void 0!==t)return e.hasOwnProperty(t)?e[t]:"";if(e.hasOwnProperty($.pkp.app.currentLocale)&&e[$.pkp.app.currentLocale])return e[$.pkp.app.currentLocale];if(e.hasOwnProperty($.pkp.app.primaryLocale)&&e[$.pkp.app.primaryLocale])return e[$.pkp.app.primaryLocale];for(var n in e)if(e[n])return e[n];return""}`

From what I can tell this matches https://github.com/pkp/ui-library/blob/master/src/mixins/global.js#L104
and unfortunately not the localize function you linked.

From debugging build.js I can see the code does as expected. First localized call is for affiliation and the first param is an object with the locale affiliation string. The second call the param is null and is called for biography. It fails when checking the third if statement. 

Your localize function's null check looks good to solve this issue.

**Comment by NateWr** [comment] 2020-07-02 09:29
:+1: Good detective work, @awecancer aka Procky. It looks like this has changed between `stable-3_2_0` and `master`, due to #5865. 

This is the function as it appears in 3.2.0 and 3.2.1, with the `typeof` check rather than the `!multilingual`, which babel will compile down to include a `null` check: https://github.com/pkp/ui-library/blob/stable-3_2_0/src/mixins/global.js#L70.

I'll file this to be fixed for our next 3.2.1.x release.

If you're willing, we'd love to have a PR against the `stable-3_2_1` branch of UI Library that addresses this. I think changing the first `if` conditional to match what's in `master` would do the trick.

If you wanted to fix it in your local install by editing the build.js file directly, you can probably do it by changing:

```
if("undefined"===typeof e)
```

To:

```
if("undefined"===typeof e || "null"===typeof e)
```

**Comment by NateWr** [comment] 2020-07-13 15:22
PR:
https://github.com/pkp/ui-library/pull/109 (`stable-3_2_1`)

Tests:
https://github.com/pkp/ojs/pull/2836 (`stable-3-2_1`)

**Comment by awecancer** [comment] 2020-07-14 07:53
Thanks @jnugent. Also while improbable anyone will need this, the direct change to the build.js file would be:

`if("undefined"===typeof e || null===e) `

**Comment by NateWr** [comment] 2020-07-14 11:44
Thanks everyone, that's been merged to the `stable-3_2_1` branch now.

**Closed by NateWr** 2020-07-14 11:44 UTC
Labels: Bug
