### ISSUE TITLE
Consider using recaptcha.net URL for CAPTCHA 

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6083] opened 2020-07-10 16:17 UTC
We've had requests from hosted journals who have users in China that are unable to sign up due to google.com being unavailable in China.  Our workaround thus far has been to edit classes/form/validation/FormValidatorReCaptcha.inc.php and classes/template/PKPTemplateManager.inc.php and switch the www.google.com references to www.recaptcha.net which works in China.  If this was permanently added to pkp-lib the only other modification would be to switch enable_cdn to off.  The recaptcha.net domain is owned by Google so it probably isn't going anywhere.

**Comment by asmecher** [comment] 2020-07-10 16:23
@jnugent, this is a dupe of https://github.com/pkp/pkp-lib/issues/2993 -- can you add this proposal over there?

**Closed by asmecher** 2020-07-10 16:23 UTC
Labels: Hosting
