### ISSUE TITLE
Unify the storage of category IDs

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#9448] opened 2023-10-20 18:03 UTC
**Describe the bug**
The category IDs are currently stored on the entity `publication_categories`, and also as a setting `categoryIds` on the `publication_settings` entity, this issue is supposed to unify the data, to avoid issues such as https://github.com/pkp/pkp-lib/issues/9405.

- I think the preference should be given to the `publication_categories` entity.
- A migration to clean up the duplicated data must be introduced, probably at the 3.5, to avoid introducing regressions/touching the database without a good reason.

**To Reproduce**
1. Create a submission with categories, and see the data is persisted in both places.

**What application are you using?**
OJS 3.3

**Comment by asmecher** [comment] 2024-07-15 17:09
Duplicate of: https://github.com/pkp/pkp-lib/issues/10158

**Closed by asmecher** 2024-07-15 17:09 UTC
Labels: Enhancement:1:Minor
