### ISSUE TITLE
OMP submission "work type" not preserved during upgrade

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7434] opened 2021-11-05 17:24 UTC
**Describe the bug**
A client is using OMP 3.1.2 and after upgrading a test installation to 3.3.0.8, all submissions have reverted to not having a stored submission_setting for "workType", which determines if the submission is a Monograph or an Edited Volume.  Examining the submission_settings for any submission shows that the workType setting is missing, and the drop down on the workflow UI has both Monograph and Edited Volume in blue indicating neither is chosen:

![Screenshot at 2021-11-05 14-14-06](https://user-images.githubusercontent.com/218719/140552431-745cc10e-91c1-427f-910f-51c9e502dedb.png)

At this point, choosing one or the other correctly creates the workType submission_setting in the database.

**What application are you using?**
OMP 3.3.0.8

**Additional information**

Before the upgrade, the Catalog entry in 3.1.2 for this looked like:

![Screenshot at 2021-11-05 14-14-34](https://user-images.githubusercontent.com/218719/140552597-8044e6fc-d59d-43b0-a292-ff47a5c56e53.png)

**Comment by NateWr** [comment] 2021-11-08 17:36
@jnugent can you create some reproduction steps for this from a brand new 3.1.2 install that is upgraded to 3.3? Seems like if this problem were common we would have heard of it before, but maybe not since there may not be many OMP installs running on 3.3.

**Comment by jnugent** [comment] 2021-11-08 17:55
Hi @NateWr 

Sure, I just confirmed it in a fresh start with a clean 3.1.2 install, then upgraded to 3.3.0.8.  To reproduce:

1.  Start with 3.1.2.  Create a new submission, choosing "Edited Volume" as the work type:
![Screenshot at 2021-11-08 13-43-02](https://user-images.githubusercontent.com/218719/140792908-ea7b46ab-28a1-4f71-82f8-c68ab8f3130e.png)

Then confirm it in the interface and the database:

![Screenshot at 2021-11-08 13-45-21](https://user-images.githubusercontent.com/218719/140792973-53e75d1e-408d-406d-aaa2-0af72005634a.png)
![Screenshot at 2021-11-08 13-46-34](https://user-images.githubusercontent.com/218719/140792995-5ead4a0a-224a-49f5-ac2b-5d188c46d711.png)

Then upgrade this installation to 3.3.0.8 and then find the same submission in the workflow.  Notice that the top tool bar says "Monograph" again, but nothing is actually chosen, they are still both blue:

![Screenshot at 2021-11-08 13-49-18](https://user-images.githubusercontent.com/218719/140793084-7a0f0330-f39e-4ce0-b274-689ecb5a9348.png)

Confirm in the submission_settings table that there is no "workType" setting:

![Screenshot at 2021-11-08 13-49-42](https://user-images.githubusercontent.com/218719/140793122-8ad33b3a-e9bb-4350-b2c3-32bf30d5c1de.png)

Choose one of the values in the Monograph/Edited Volume toggle.  Choosing Edited Volume creates the submission setting in the database, with the correct value of "1":

![Screenshot at 2021-11-08 13-49-56](https://user-images.githubusercontent.com/218719/140793182-e52f8de3-1d46-4a49-906d-522c70caaf55.png)

**Comment by NateWr** [comment] 2021-11-09 11:17
Thanks @jnugent. It turns out the data is all still there. The `workType` is stored in the `submissions` table at `submissions.work_type`. The problem is that the `SubmissionDAO` didn't know to grab it from the main table, so it is looking for it in the `submission_settings` table. When it saves the data, it saves it back into the `submission_settings` table.

A simple PR will fix this for `stable-3_3_0` by telling the DAO to read/write the data to the `submissions table`. I've back-ported the fix to `stable-3_2_1` since that's where the bug was introduced. However, any submissions made under 3.2.x or 3.3.0 to 3.3.0-8 will have the `workType` stored in the wrong place. So I've prepared another PR to migrate this data back to the correct place in 3.4.

Stable PRs:
https://github.com/pkp/omp/pull/1024 (`stable-3_3_0`)
https://github.com/pkp/omp/pull/1025 (`stable-3_2_1`)

The `main` branch requires two changes:
1. Cherry-pick the commit in the PR above to `main`.
2. Fix and merge the migration in this draft PR: https://github.com/pkp/omp/pull/1026

**Comment by jnugent** [comment] 2021-11-09 12:53
Thanks, @NateWr. Our OMP 3.1.2 client was getting ready to upgrade to 3.3 - I assume it is probably better to ask them to delay until 3.4? They have a large collection of submissions.

**Comment by jnugent** [comment] 2021-11-09 13:58
Great, thank you.

**Comment by NateWr** [comment] 2021-11-17 12:19
PRs merged for `stable-3_2_1`, `stable-3_3_0`, and `main`.

**Closed by NateWr** 2021-11-17 12:19 UTC
Labels: Bug
