### ISSUE TITLE
Auther full name exposed to reviewers via editorial descision email templates in double blind review

### ISSUE THREAD

**Issue by ronste** [pkp/pkp-lib#8241] opened 2022-09-08 11:59 UTC
**Describe the problem you would like to solve**
When sending an editorial decision to the auther the option can be enabled to send a bcc copy to selected reviewers. Since all default e-mail templates contain the full name of the auther, the reviewer can see the authers name even when a double blind review is enabled.

**Describe the solution you'd like**
Change the language around the option to bcc reviewers in order to warn the editor that this will expose the author's name.

**Who is asking for this feature?**
Journals that don't want the author's identity to be exposed while recording an editorial decision.

**Additional information**
This description has been changed from the original, which is below:

> **Describe the bug**
> When sending an editorial decision to the auther the option can be enabled to send a bcc copy to selected reviewers. Since all default e-mail templates contain the full name of the auther, the reviewer can see the authers name even when a double blind review is enabled.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Create a review round including a reviewer which already submited a review.
> 2. Click on "Request Revisions" (or any other button used to inform the auther about edirorial decisions)
> 3. Select "Send an email notification to the author(s)" and enable the checkbox for the assigned reviewer under "Send to Reviewers"
> 4. Submit the decision
> 5. See the e-mail sent to the reviewer
> 
> To circumvent the issue one could obviously edit all related e-mail templates. But generally this shoudn't be necessary with the default configuration.
> 
> **What application are you using?**
>  OJS 3.3.0-11
>

**Comment by NateWr** [comment] 2022-09-12 16:38
I consider this a poor design choice, but not a bug. When bcc'ing a recipient, the sender should know that the recipient will see the email as-is. This is the standard way that email works. For this reason, we have moved away from this approach in 3.4. Reviewers are now sent a separate email rather than BCC'd on the author's email. 

We don't have any plans to change this behavior for 3.3. We don't typically change how a feature works in a stable version or remove features. This BCC feature in particular has been there for several major versions, so removing it from a stable version would only be done if there were overwhelming demand.

Unfortunately, that means I'm going to close this issue. But I'd encourage you to post in our [feature requests](https://forum.pkp.sfu.ca/c/feature-requests/8) if you feel this should be changed for the 3.3.x line. You can work with other community members to figure out a proposal that would be minimally disruptive to existing use cases.

**Comment by ronste** [comment] 2022-09-13 08:40
Hi @NateWr ,

I fully understand that it's not a good idea to change how features work in a stable version. I appreciate this behaviour is revised in version 3.4. However, for all older versions editors might not easily make the connection between bcc-ing the mail and exposig the authers names to the reviewers.
I think at least a warning could be placed in the description on the form, that using this feature might expose the authors name.

For those who come accross this issue:
One can use the Custom Locale Plugin to alter the description on the form. The loacle file is "lib/pkp/locale/en_US/reviewer.po" and the key "submission.comments.sendCopyToReviewers".

**Comment by NateWr** [comment] 2022-09-13 08:55
Thanks @ronste. I think we'd be open to a language change. Can you suggest better language that fits into the form there?

**Comment by ronste** [comment] 2022-09-13 09:12
To keep it simple I would suggest something like 

"Send a copy of this email notification (might include auther names) by BCC to the following reviewers."

**Comment by NateWr** [comment] 2022-09-14 08:55
Thanks @ronste. I opted for a slightly longer message to be a little bit clearer. Also, I think the email will _always_ expose the user's identity -- at least their email address -- even if they remove the name from the email.

![bcc](https://user-images.githubusercontent.com/2306629/190108970-eaa59518-5a85-4729-946a-4a2fd7a46aed.png)

@asmecher this locale key was missing from almost all of the locales. That can't be right, can it?

PR:
https://github.com/pkp/pkp-lib/pull/8255

Tests:
https://github.com/pkp/ojs/pull/3542

**Comment by ronste** [comment] 2022-09-14 09:03
Thanks @NateWr ,

"Also, I think the email will always expose the user's identity -- at least their email address -- even if they remove the name from the email."

Ohh, sure. I didn't think of this. The normal recipients will be visible to the reviewers too ... good you changed that with 3.4!

**Comment by asmecher** [comment] 2022-09-14 15:50
> this locale key was missing from almost all of the locales. That can't be right, can it?

Unfortunately yes -- that does appear to be correct. Probably a reflection of the short time the Weblate installation spent on the `stable-3_3_0` branch before moving on to `main` -- an error on my part that's dogged me since then!

**Comment by NateWr** [comment] 2022-09-15 08:45
Ok, I've merged to `stable-3_3_0` and the translations can get updated later. Thanks @ronste!

**Closed by NateWr** 2022-09-15 08:45 UTC
Labels: Enhancement:1:Minor
