### ISSUE TITLE
[OJS 3.1.2] Production Discussions --> Edit = Failed Ajax request

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#4629] opened 2019-03-22 12:15 UTC
Hi! When the user (Journal Manager or Admin) tries to edit the 'Production Discussion', s/he gets the error 'Failed Ajax request or invalid JSON returned'.
Might be related:
https://forum.pkp.sfu.ca/t/discussions-not-working/46662

**Comment by asmecher** [comment] 2019-03-22 15:12
This is a duplicate of https://github.com/pkp/pkp-lib/issues/4607 -- try the patch over there.

**Closed by asmecher** 2019-03-22 15:12 UTC
