### ISSUE TITLE
Alphanumeric validator and UTF8 supported characters in usernames

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#4053] opened 2018-09-12 10:03 UTC
Hi,

The Finnish language includes letters like ä, ö and å. For Finnish users these are part of the definition of "alphanumeric". 

However, the validator here does not seem to take into account these letters: https://github.com/pkp/pkp-lib/blob/master/classes/form/validation/FormValidatorUsername.inc.php#L31

Also I think the registration form should have a description under the username field that would show the requirements for the username. This also applies to the password field.

(or just remove usernames altogether and just use email as a username. I mean what is it good for anyway?)

**Comment by asmecher** [comment] 2018-09-14 08:30
@ajnyga, I think this is essentially a dupe of https://github.com/pkp/pkp-lib/issues/906. Essentially the conventions have evolved far enough away from `[a-zA-Z]+` that I'm open to both proposals -- relaxing the allowed characters, and moving to email-based logins.

**Closed** 2018-09-14 08:31 UTC

**Comment by ajnyga** [comment] 2018-09-14 09:39
There are many sides to this.

Login by email is good, but I did realize that the username is a handy shortname to have around the workflow. 

I do think the current username rules are too strict, but we should not allow whole names as usernames either. It beats the purpose imho.
