### ISSUE TITLE
[OJS] Option to hide title of section from issue table of contents broke in default theme

### ISSUE THREAD

**Issue by pmangahis** [pkp/pkp-lib#4930] opened 2019-07-16 16:03 UTC
When a user selects the option “Omit the title of this section from issues’ table of contents” for a section, the title of the first article in this section is on or above the separator.

![image](https://user-images.githubusercontent.com/50342731/61310129-85a46a80-a7a8-11e9-9e81-f4e5be4c27b9.png)

As described in https://forum.pkp.sfu.ca/t/default-theme-design-issue-section-title/54611

**Comment by eocarragain** [comment] 2020-11-11 23:44
Confirming this bug on OJS 3.2.1-1. 

However, this ticket appears to be a duplicate of #6107 where it was fixed and scheduled for release as 3.2.1-2

**Comment by NateWr** [comment] 2020-11-12 09:42
In #6107 the feature was fixed so that the section title would be hidden. In this issue, I think the problem is that when the section title is hidden the layout/styling is off. The first article's title rises up to overlap with the section divider line.

**Comment by eocarragain** [comment] 2020-11-12 22:34
thanks @NateWr . Right you are

**Comment by NateWr** [comment] 2020-11-17 15:41
This was fixed as part of work in https://github.com/pkp/pkp-lib/issues/5187.

**Closed by NateWr** 2020-11-17 15:41 UTC
Labels: Bug
