### ISSUE TITLE
"Mark as Read" in Notifications doesn't do anything. (3.3 testing)

### ISSUE THREAD

**Issue by AhemNason** [pkp/pkp-lib#6623] opened 2021-01-18 23:48 UTC
If you open notifications and click one of the checkboxes on a new one, and click on "mark as read", nothing changes. If you close the notification window, you still see the same number of unread notifications. You need to actually click on the notification itself to clear it. 
 
This is in 3.3 on the hosted testing instance. 

(Small as bugs go, but worth reporting I think).

**Comment by NateWr** [comment] 2021-01-19 10:23
Thanks @AhemNason! Duplicate of https://github.com/pkp/pkp-lib/issues/6559.

**Closed by NateWr** 2021-01-19 10:23 UTC
Labels: Bug
