### ISSUE TITLE
In OJS 3.3.0.13. button 'Confirm' for review is not working after reading review. When I klik 'Confirm', button 'Thank reviewer' does not appear

### ISSUE THREAD

**Issue by memes1987** [pkp/pkp-lib#8568] opened 2023-01-25 10:33 UTC
**Describe the bug**
Please tell us what happens, what you expected to happen, and why you think it is a bug in the software.

**To Reproduce**

**What application are you using?**
 OJS, OMP or OPS version X.X.X

**Additional information**
Please add any screenshots, logs or other information we can use to investigate this bug report.

**Comment by asmecher** [comment] 2023-01-25 15:59
@memes1987, I think this is a duplicate of https://github.com/pkp/pkp-lib/issues/7486.

**Closed by asmecher** 2023-01-25 15:59 UTC
