### ISSUE TITLE
Section editors are not added to their own recommendation discussions

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#7903] opened 2022-05-04 17:54 UTC
**Describe the bug**
When a section editor (or a role with SE privileges) is added to a submission with only the ability to recommend an editorial decision, and they create a recommendation and also check the box that says "create a discussion", they cannot see it in the discussion area. This is because they are not added as a participant.

**To Reproduce**
1.  Assign an SE to a submission, but limit them to recommendations only.
2. As that SE, create a recommendation and also create a discussion for it.
3. When the modal for the recommendation closes, you will not see a discussion thread.
4. Log out of the SE account, and view the submission as a full editor.  The discussion is visible. 
5. Edit the discussion and add the SE to it.  It will become visible to the SE.

**What application are you using?**
OJS 3.3.0.10

**Comment by asmecher** [comment] 2022-05-04 18:39
@touhidurabir, this might be a good intro to an issue with the workflow.

**Comment by touhidurabir** [comment] 2022-05-05 06:42
@asmecher working on it .

**Comment by NateWr** [comment] 2022-05-09 09:46
Are we sure that this is a bug? This may be the way it was intended. Internally, we call this query a "discussion between the deciding editors", and this behaviour was copied over in my work on 3.4.

I think we need to investigate the original use case before adding the recommending editor.

**Comment by touhidurabir** [comment] 2022-05-09 09:59
So this is happening for any kind of Editors, not Just SE but Guest or Journal Editors if they do not given the other permissions but only able to recommend . And from reviewing the code , it does not seems like a bug but rather an intended behaviour based on which the implementation is done as @NateWr has mentioned . 

So question is should we allow other editors to be add as the participants when a recommendation made by an editor who only have recommendation ability or not . I can think of following approaches for this enhancement 
1. do nothing and leave it as it is as all those editors have permission , they will be added as participants with current implementation .
2. only add the editor who has made the recommendation as the participant if do not have permissions .
3. add all editors assigned to submission as participants to that recommendation discussion . 

@NateWr what you think ?

**Comment by jnugent** [comment] 2022-05-09 10:20
This issue was filed because a PKP PS hosted client reported that their section editors were creating these discussions and then not being able to follow up in them with further comment, or even knowing that the discussion was created.  There's no UI feedback that the creation of the discussion worked. If the intention is for Section Editors to be able to create a discussion to go along with a recommendation (but not be added to it) I think there should be something indicating that the discussion was created.

**Comment by NateWr** [comment] 2022-05-09 10:52
Personally, I don't know what _should_ happen. I think we would need to dig up the original use case and find out what the expectation is. I don't think this is high enough priority right now to invest that time. But if PS wants to do the research on how ti should work, making the change is fairly simple.

> If the intention is for Section Editors to be able to create a discussion to go along with a recommendation (but not be added to it) I think there should be something indicating that the discussion was created.

The new editorial decision UI in 3.4 includes such indications.

**Comment by NateWr** [comment] 2022-05-10 10:31
I had a read through the initial discussion about [recommendations](https://github.com/pkp/pkp-lib/issues/2433) and there was no clear indication of whether recommending editors ought to be part of the discussion.

I'm going to close this and suggest we take it to the feature requests forum for further discussion.

**Closed by NateWr** 2022-05-10 10:31 UTC
Labels: Enhancement:1:Minor, Team:Workflow
