### ISSUE TITLE
STATISTICS_REPORT_NOTIFICATION email is being sent on dates that do not match those specified in the scheduledtasks.xml file.

### ISSUE THREAD

**Issue by salmanm2003** [pkp/pkp-lib#9220] opened 2023-08-10 00:53 UTC
The issue arises from the inconsistency between the `scheduledtasks.xml` configuration and OJS behavior. According to `scheduledtasks.xml`, the `STATISTICS_REPORT_NOTIFICATION` is meant to be sent on the 1st of each month. However, in some cases, OJS sends it on the 31st of the month instead of the 1st. This problem is tied to how PHP calculates the day one month before, particularly when the current month has 31 days.

The root of the problem lies in the code snippet within the "ScheduledTaskHelper.inc.php" file:

```php
if ($passTimestamp > $lastTimestamp) {
    $isValid = true;
}
```

Here, the variables are defined as follows: `$passTimestamp = strtotime('-1 month')`, and `$lastTimestamp` represents the first day of the previous month. The mismatch between these timestamps leads to the issue. For example, if the last date is the 1st of May, then `$passTimestamp > $lastTimestamp` evaluates to true on the 31st of May.

The version I'm using is OJS 3.3.0.14.

**Comment by jonasraoni** [comment] 2023-08-10 12:37
As the problem happens in OJS 3.3, it makes sense to come up with a fast fix.

For the 3.4+, I think it's better to discard the code and move to the Laravel scheduler, which supports better configurations and the usage of a CRON syntax.

**Comment by salmanm2003** [comment] 2023-08-15 13:13
Thank you, @jonasraoni, for informing me. Regarding the matter, should I proceed with submitting a pull request for version 3.3, @asmecher?

**Comment by asmecher** [comment] 2023-08-15 18:53
If there's a small (low risk) intervention that would work for 3.3, I'd suggest starting there, and forward-porting to `stable-3_4_0` and `main`. A replacement for the whole toolset might have to wait for 3.5 (`main`), as it could be a pretty big change.

I don't think much of that code has changed between `stable-3_3_0`, `stable-3_4_0`, and `main`, so if there is a low risk fix, it might make sense to commit more or less the same fix to all 3 branches, and separately file/consider a scheduler replacement.

**Comment by jnugent** [comment] 2024-01-05 18:10
This is probably a duplicate of my original issue https://github.com/pkp/pkp-lib/issues/8921

**Comment by jonasraoni** [comment] 2024-01-31 14:22
I'm closing in favor of #8921, which still needs a PR :)

**Closed by jonasraoni** 2024-01-31 14:22 UTC
