### ISSUE TITLE
ORCID invalid notification needs HTML stripped

### ISSUE THREAD

**Issue by rcgillis** [pkp/pkp-lib#6550] opened 2021-01-07 18:27 UTC
**Describe the bug**
When one doesn't enter in the ORCID info correctly into the Author Profile. It produces an error notification. The notification is fine, it's just that it doesn't have the HTML stripped from it. Haven't seen this occurring for other notifications.

**To Reproduce**
When entering the author information in the contributor information in the author information (name, affiliation etc.), it's in the ORCID field.

**What application are you using?**
OJS 3.3.0.1 

**Additional information**
<img width="328" alt="ORCID-HTML-error-Quicksubmit" src="https://user-images.githubusercontent.com/5053214/103928957-ef2ddc80-50f2-11eb-9ce5-f5147b34f758.png">

**Comment by asmecher** [comment] 2021-01-07 19:06
This is a duplicate of https://github.com/pkp/pkp-lib/issues/6449.

**Closed by asmecher** 2021-01-07 19:06 UTC
Labels: Bug
