### ISSUE TITLE
Automated Review Reminder not sent when the Reviewer already got an automated Request Reminder

### ISSUE THREAD

**Issue by ohilbig01** [pkp/pkp-lib#7715] opened 2022-02-18 11:23 UTC
**Describe the bug**

There are two types of automatic reminders:  Request Reminder and Submission Review Reminder.
I believe OJS sends the automatic reminders to reviewers only once. 
If a reviewer has already received a Request Reminder, he doesn't receive the Submission Review Reminder even though it is due.
It seems the reminder types are treated the same way: If there was already a reminder, there is no new one, regardless of which one came before.
In lib/pkp/classes/task/ReviewReminder.inc.ph setDateReminded() and setReminderWasAutomatic() are called in both cases.
Or is the way it was intended?

**To Reproduce**
1. Add a reviewer in the workflow
2. The reviewer does nothing and gets the first automated Article Request Reminder

**What application are you using?**
 OJS 3.3.07

**Comment by NateWr** [comment] 2022-02-21 11:33
Probably, this was intended to prevent a reviewer from receiving two reminders if they don't respond to the first. For example:

1. I assign a reviewer.
2. They never respond.
3. They receive a reminder.
4. They never respond.

At this point, a further reminder may constitute harassment, especially if the reviewer has not opted into their role.

However, I agree with you that in the following case a second email should be sent out:

1. I assign a reviewer.
2. They never respond.
3. They receive a reminder.
4. They respond and accept the review but do not complete it.

In this case, they should receive the review reminder email, since there has been at least a response.

@Vitaliy-1 since you've been working with this code recently, do you think this is an easy improvement?

**Comment by Vitaliy-1** [comment] 2022-02-21 18:45
On the top of my head, additionally compare the `date_confirmed` and  `date_reminded`: https://github.com/pkp/pkp-lib/blob/480c1515b4d5db219ceb6f9699a3cfb5f658fda6/classes/task/ReviewReminder.inc.php#L144 and if `date_confirmed` is after the `date_reminder`, send another one. But I really didn't dive into the logic of those reminders, only the part with sending emails.

**Comment by forgive38** [comment] 2022-03-03 23:09
Maybe issue https://github.com/pkp/pkp-lib/issues/6904 is related to this one.

so now, in main, reviewer can receive 2 reminders: 
first if he's late to accept, and a second if he accepts but he's late to post the review.

**Comment by NateWr** [comment] 2022-03-07 11:58
Thanks @forgive38! That does look like it fixes the problem. I'll close this as it should be fixed for 3.4.

**Closed by NateWr** 2022-03-07 11:58 UTC
Labels: Enhancement, Try Me
