### ISSUE TITLE
[front end] User search interface sends multiple requests causing extreme slowness

### ISSUE THREAD

**Issue by lpanebr** [pkp/pkp-lib#8809] opened 2023-03-14 13:11 UTC
**Describe the bug**
When searching for users to add as reviewer the system sends multiple requests as shown below:

![image](https://user-images.githubusercontent.com/129185/225008847-8f83b4e1-0a0a-4f51-92ef-4479c48d0429.png)

**The payload for each request was:**
 1. `an`
 2. `ana`
 3. `ana m`
 4. `ana ma`
 5. `ana mari`
 6. `ana maria`

**To Reproduce**
1. Go to submission
7. Click on add reviewer
8. Open the developer tools
9. Type for a name 
10. See the requests sent

**What application are you using?**
`Open Journal Systems 3.3.0.13`

**Comment by jonasraoni** [comment] 2023-03-14 16:20
Hi @lpanebr! I'll close this as a duplicate of https://github.com/pkp/pkp-lib/issues/6675

We can cancel the requests at the client-side, but they will be processed at the server-side anyway (PHP doesn't manage the HTTP connection directly, therefore it cannot detect the connection dropped unless we keep sending data). I think it's possible to do workarounds (e.g. save the database's connection id on the session, then kill it on a next request), but we're unlikely to follow this route.

**Closed by jonasraoni** 2023-03-14 16:20 UTC

**Comment by lpanebr** [comment] 2023-03-15 15:25
Thanks. I'll follow up there
