### ISSUE TITLE
[OJS] Uploading a new Galley file and selecting "Change file" corrupts the uploaded file

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2922] opened 2017-10-23 07:20 UTC
OJS 3.0.2. This happens at least when using the quicksubmit plugin, most likely with other similar file uploads as well.

1. Add new article
2. Enter metadata
3. "Add galley"
4. Enter a galley label and save
5. Enter article component
6. Upload a new file
7. Click "Change file" and upload the same file again
8. The system asks you if this is a new file or revision, leave the default selection and continue
![2017-10-23 10 10 21 am](https://user-images.githubusercontent.com/16347527/31876394-210fa79c-b7db-11e7-8e23-2f3e16f84132.png)
9. The file is uploaded and the modal window closes. The "PDF" is shown in the grid.
10. Publish the article and the go to the workflow of that article => The galley grid is not loading
![2017-10-23 10 10 59 am](https://user-images.githubusercontent.com/16347527/31876476-6594d4f0-b7db-11e7-9b45-a3c8b3e91c89.png)

Related errors:

```
[23-Oct-2017 10:07:10 Europe/Helsinki] PHP Warning:  assert(): Assertion failed in /home/c2teihrj/public_html/ojs/lib/pkp/classes/notification/managerDelegate/EditingProductionStatusNotificationManager.inc.php on line 188
[23-Oct-2017 10:07:10 Europe/Helsinki] PHP Warning:  assert(): Assertion failed in /home/c2teihrj/public_html/ojs/lib/pkp/classes/notification/managerDelegate/EditingProductionStatusNotificationManager.inc.php on line 188
[23-Oct-2017 10:09:56 Europe/Helsinki] PHP Warning:  assert(): Assertion failed in /home/c2teihrj/public_html/ojs/lib/pkp/classes/notification/managerDelegate/EditingProductionStatusNotificationManager.inc.php on line 188
[23-Oct-2017 10:09:56 Europe/Helsinki] PHP Warning:  assert(): Assertion failed in /home/c2teihrj/public_html/ojs/lib/pkp/classes/notification/managerDelegate/EditingProductionStatusNotificationManager.inc.php on line 188
[23-Oct-2017 10:10:33 Europe/Helsinki] PHP Warning:  assert(): Assertion failed in /home/c2teihrj/public_html/ojs/lib/pkp/controllers/api/file/linkAction/FileLinkAction.inc.php on line 42
[23-Oct-2017 10:10:33 Europe/Helsinki] PHP Fatal error:  Call to a member function getFileId() on null in /home/c2teihrj/public_html/ojs/lib/pkp/controllers/api/file/linkAction/FileLinkAction.inc.php on line 46
[23-Oct-2017 10:10:50 Europe/Helsinki] PHP Warning:  assert(): Assertion failed in /home/c2teihrj/public_html/ojs/lib/pkp/controllers/api/file/linkAction/FileLinkAction.inc.php on line 42
[23-Oct-2017 10:10:50 Europe/Helsinki] PHP Fatal error:  Call to a member function getFileId() on null in /home/c2teihrj/public_html/ojs/lib/pkp/controllers/api/file/linkAction/FileLinkAction.inc.php on line 46

```

**Comment by bozana** [comment] 2017-11-09 14:42
@ajnyga, I cannot reproduce this any more. Could you please try in your installation, if this still happens? THANKS!!!

**Comment by ajnyga** [comment] 2017-11-09 15:20
Hmm, interesting. On my own server I have a OJS installation for test purposes. I installed it with 3.0.2 and upgraded that to 3.1 a while ago.

After the upgrade the quicksubmit plugin is missing (I replaced all the files when upgrading and the 3.1 package does not have that included). But now that I try to go to the plugin gallery and download the quicksubmit plugin, it says that my quicksubmit plugin is up to date. So without ftp access I would be stuck. This is probably not the way this should work with upgrades?

**Comment by bozana** [comment] 2017-11-09 15:24
@ajnyga, maybe this fix solves the problem: https://github.com/pkp/pkp-lib/issues/2956 ?

**Comment by ajnyga** [comment] 2017-11-09 15:27
I get the same problem described above with 3.1 and the latest quicksubmit:

![2017-11-09 05 26 20 pm](https://user-images.githubusercontent.com/16347527/32613290-30ade6a0-c573-11e7-92f0-f593ccb3c8f7.png)

Do you have more than one locale active when you test it?

**Comment by bozana** [comment] 2017-11-09 15:28
Hmm... Do you mean production discussion or galley files?

**Comment by ajnyga** [comment] 2017-11-09 15:32
Yes exactly, the galleys grid does not load.

**Comment by bozana** [comment] 2017-11-09 15:42
Hmmm... I cannot reproduce it in that way -- everything is fine in such a case, but when I cancel the file upload then I get that problem...

**Comment by ajnyga** [comment] 2017-11-09 15:55
Do you upload the same file again and get the "possible duplication" modal?

I can reproduce this consistently.

**Comment by bozana** [comment] 2017-11-09 15:56
Strange -- I do upload the same file and do not get that "possible duplication" modal :-O -- my file seems to be just replaced...

**Comment by bozana** [comment] 2017-11-09 16:00
I belive I figured out where the problem is -- the file is assigned to the galley too early -- and in your case maybe the wrong fileId -- that then does not exist any more, but it stays in the submission_galleys table...

**Comment by ajnyga** [comment] 2017-11-09 16:01
I think I tested this with a png file, a screen shot. Could that be related?

**Comment by bozana** [comment] 2017-11-09 16:01
I'll check that too...

**Comment by ajnyga** [comment] 2017-11-09 16:04
oh but, originally I had a htm file. I think I've seen a variable somewhere that is used to define if a file is regarded as a copy of the same file. In config.inc.php I think. But do not have a clue how it works.

**Comment by bozana** [comment] 2017-11-09 16:43
PRs:
pkp-lib master: https://github.com/pkp/pkp-lib/pull/3034
ojs master: https://github.com/pkp/ojs/pull/1675

**Comment by bozana** [comment] 2017-11-09 16:45
@ajnyga, these PRs solve my problem. It could be that this would solve your problem as well -- if for example the function deleteFile is called also in your case... Would it be possible for you to test? And I will continue to try to reproduce that case and to get that "possible duplication" modal... THANKS!!!

**Comment by bozana** [comment] 2017-11-09 16:53
Ah, wait, I will have to do a correction...

**Comment by ajnyga** [comment] 2017-11-09 17:34
Ok, let me know if there is something I can test.

**Comment by bozana** [comment] 2017-11-09 17:46
OK, I think I figured it out: your case happens when there are already old files with the same file name in the DB associated with that galley, for some reason -- maybe because it was functioning wrong till now i.e. these cases found here were not considered.
In that case, first the new file is created and associated with the galley, but then, when one chooses the file to be the revision of the existing, the file id and revision changes, but the galley file id does not. 
Now everything should work ok, I hope...
@ajnyga, could you please test it now? Sorry... and THANKS!

**Comment by bozana** [comment] 2017-11-09 17:48
I checked the galley files, but the review rounds should be also tested, s. function _attachEntities here: https://github.com/pkp/pkp-lib/blob/master/controllers/wizard/fileUpload/PKPFileUploadWizardHandler.inc.php#L322

**Comment by ajnyga** [comment] 2017-11-09 19:00
The pr's solve the original issue @bozana!

**Comment by bozana** [comment] 2017-11-10 16:15
@asmecher, could you review the PRs above?
Note that I removed the stageAssignments check for detaching the dependent files i.e. for deleteReviewRoundAssignment in deleteFile, because also the managers/editors/admins that are not assigned could delete a file. And that I then consider those 3 file stages for that: SUBMISSION_FILE_REVIEW_FILE, SUBMISSION_FILE_REVIEW_ATTACHMENT, SUBMISSION_FILE_REVIEW_REVISION.
Thanks!!!

**Comment by asmecher** [comment] 2017-11-10 23:26
Looks good, @bozana, please go ahead!

**Closed** 2017-11-12 10:32 UTC

**Comment by ciptoblues** [comment] 2018-08-03 04:36
the problem occurs because of an insert record failure in the galley submission table. example
UPDATE submission_galleys SET file_id = '3916' WHERE galley_id = 798;
