### ISSUE TITLE
Missing files break issue table of contents generation

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#6502] opened 2020-12-21 18:24 UTC
Israel and I discovered this in OJS 3.3.  We upgraded a test installation from 3.2.1 to 3.3 and received a blank screen loading the journal index, which was also loading the table of contents for the current issue.  Turning on debugging results in the following error message attached as a screenshot.  

Missing files are a fact of life for our clients, perhaps this exception can be caught and dumped as an error message.

![Screenshot from 2020-12-10 16-11-19](https://user-images.githubusercontent.com/218719/102809573-9e02b680-4398-11eb-96a4-28013d236f2e.png)

**Comment by NateWr** [comment] 2020-12-22 10:38
@jnugent can you provide reproduction steps? It's not clear precisely what is missing in the "missing files" and repro steps clear up any ambiguity.

**Comment by jnugent** [comment] 2020-12-22 12:35
Hi @NateWr ,

Sure.  Just create an OJS 3.3 installation with a full file tree, and then delete one of the proof files that would normally be a galley in the table of contents. We found this bug accidentally when we upgraded an install from 3.2 to 3.3 and mistakenly used the wrong files_dir value.

**Comment by NateWr** [comment] 2020-12-22 13:03
Just to make sure you mean delete the file on the filesystem, not delete the file from the galley in the UI, right?

**Comment by jnugent** [comment] 2020-12-22 13:26
That's correct.

**Comment by NateWr** [comment] 2021-01-06 12:17
The following PRs fix this issue and try to degrade gracefully or return appropriate 404 responses when a file is missing. Here's what happens:

- When downloading a submission file in the backend, a 404 page is displayed.
- When downloading a galley file in the frontend, a 404 page is displayed.
- When viewing a PDF galley file in the frontend, the pdf.js loads with an error message that says the file is missing.
- When viewing a HTML galley file in the frontend, a 404 page is displayed.
- When a dependent file, like a CSS file, is loaded in an HTML galley, the file just doesn't load (eg - there are no styles). The network request returns a 404.

These PRs also refactor the new file/submission file handling to reduce the number of cases where we need to check the file system to get file details.

The following changes are made:

- The mimetype is now stored in the `files` table.
- When a submission file is retrieved from the database, we pull the file_id, path and mimetype from the files table and store them as properties of the submission object. Before, we only pulled the file_id, but pulling all the file details prevents a lot of extra runs to the database to get the mimetype or path.
- Mimetypes are migrated in 3.3 from the `submission_files` to the `files` table. The existing mimetype data does not always perfectly match what Flysystem returns for the mimetype, but I think that Flysystem is just more specific in its definitions. I don't think that this will cause any issues?
- The `size` property is no longer returned in the submission files API.
- The filesystem still checks file size for every file when preparing an export. Maybe md5sum is a better way to monitor file integrity?
- The filesystem also checks file size in OMP for some publication format metadata. Just something to keep in mind as we move to support third-party file storage.
- The `docSize` key is no longer in the usage event data that is passed to `UsageEventPlugin::getUsageEvent`. I couldn't find any use for this.

This commit also fixes a bug in OJS with published dependent files. A URL to a dependent file routed through the ArticleHandler would return the parent file instead. I couldn't reproduce this with OMP.

@asmecher can you take a look at this? This is a little bit more churn than I would like to see after RC2 has gone out, but it seems like it is worth it to make the change now. If we don't implement the change to the files table in 3.3, we'll lose the existing mimetype info in the 3.2 database and will need to check every file in the system in a future migration. 

The biggest risk for introducing bugs is in the amount of code refactored now that `path` and `mimetype` are available on the SubmissionFile, as well as the removal of the `FileService::getPath()` method. I will update the Release Notebook and other docs to reflect this.

PRs:
https://github.com/pkp/pkp-lib/pull/6533
https://github.com/pkp/ojs/pull/2977
https://github.com/pkp/omp/pull/903
https://github.com/pkp/ops/pull/99
https://github.com/pkp/usageStats/pull/41
https://github.com/pkp/pdfJsViewer/pull/59

**Comment by asmecher** [comment] 2021-01-07 00:10
Looks good -- comments added to individual PRs.

**Comment by NateWr** [comment] 2021-01-07 15:21
All merged, thanks everyone!

**Closed by NateWr** 2021-01-07 15:21 UTC
Labels: Bug

**Comment by defstat** [comment] 2021-01-08 10:15
@NateWr @asmecher  I am executing `php tools/upgrade.php upgrade`, and the `files` table is not getting updated with the `mimetype` column. Should I execute another script for the migration to be executed?

**Comment by asmecher** [comment] 2021-01-08 18:00
Is this an upgrade from 3.3.0rc1, or from an older (formally released) version of OJS like 3.2.1-x?

**Comment by PublicSphere-Web** [comment] 2021-01-08 18:09
its from 3.3.0 (in fact from the master branch as it were on 21.12.2020

**Comment by defstat** [comment] 2021-01-08 18:12
its from 3.3.0 (in fact from the master branch as it were on 21.12.2020)

**Comment by asmecher** [comment] 2021-01-08 18:23
You'll need to regenerate your database -- there are no upgrade steps coded for the RC states.
