### ISSUE TITLE
Date field of announcements is not evaluated correctly

### ISSUE THREAD

**Issue by brunt82** [pkp/pkp-lib#9308] opened 2023-09-18 10:04 UTC
**Describe the bug**
When creating a new announcement, you can specify a date by which this announcement should be displayed to users.
However, if a future date is specified, the announcement will not be displayed.

**To Reproduce**
1. Go to /management/settings/announcements
2. Click on "Add announcement"
3. Enter some data
4. Add a future date
5. Open index page or announcement of OJS and the announcement is not be displayed.

If a past date is entered (or removed completely), the announcements will be displayed correctly.
It seems like the date is checked backwards: instead of hiding past announcements, future ones are being hidden

**What application are you using?**
OJS 3.4.0.3

**Comment by jonasraoni** [comment] 2023-10-23 11:54
Closed as a duplicate of https://github.com/pkp/pkp-lib/issues/9226

**Closed by jonasraoni** 2023-10-23 11:54 UTC
