### ISSUE TITLE
Article landing page development 

### ISSUE THREAD

**Issue by user2711** [pkp/pkp-lib#7060] opened 2021-05-14 09:54 UTC
Our journal administrators need a way to publish the full text article in the article landing page, considering that our journals are fully open access.  
At the moment the OJS article landing page includes metadata (title, abstract, keywords and references), but we would like to have the possibility to publish the full text in the same page, including the graphs and tables. 
Evidently it could increase the interest of readers to check out the article without clicking on hyperlink or downloading a galley. 
For now we have to create an external webpage in order to provide users with an attractive article landing page that does not require readers to download a full text. 
We are looking for any acceptable solution, such as customization or plugin. 
Thanks

**Comment by asmecher** [comment] 2021-05-14 17:14
There is some relevant conversation about active developments on the forum; see: https://forum.pkp.sfu.ca/t/how-to-upload-an-html-file-and-display-it-as-full-text-no-docx-nor-jats/67417

**Comment by NateWr** [comment] 2021-05-17 10:03
Thanks @user2711, in addition to the forum post that Alec mentioned, you can find some detailed discussion about how we might support `fullText` from a variety of sources (HTML file, JATS XML, a WYSIWYG editor) in https://github.com/pkp/pkp-lib/issues/6279.

I'm going to close this as a duplicate of #6279 but feel free to post any follow-up or questions there.

**Closed by NateWr** 2021-05-17 10:03 UTC

**Comment by user2711** [comment] 2021-05-17 10:16
I'm not sure if it's a duplication. We need to have an extra field besides the metadata to paste the whole text of the article, including the graphs and tables, but in mentioned discussions the question is to show the html. 
We would like to avoid: 1. converting a word/pdf to html and add it as a galley; 2. extra clicking to see the article, i.e. by it could be displayed in the same page of abstract and references.
Is it possible to make a customization?

**Comment by NateWr** [comment] 2021-05-18 11:17
In the issue, the discussion begins with a question about extracting content from the HTML galley, but it goes into our plans for a `fullText` property which would include what you're asking for: an editable text field to enter the body of the article and display it on the landing page.
