### ISSUE TITLE
Limited view of roles in Profile

### ISSUE THREAD

**Issue by stranack** [pkp/pkp-lib#3313] opened 2018-01-24 23:39 UTC
When a user looks at the Roles tab in their profile, they only see Author, Reviewer, and Reader -- even when they are also an editor, journal manager, copyeditor, etc. All roles that they are enrolled in should be visible.

http://vpstest2.lib.sfu.ca/index.php/publicknowledge/user/profile

If they are an editor or journal manager, they should be able to self-enroll in any available role from here.

**Comment by asmecher** [comment] 2018-01-24 23:50
Dupe of https://github.com/pkp/pkp-lib/issues/2579!

**Closed by asmecher** 2018-01-24 23:50 UTC
