### ISSUE TITLE
[OJS 3.3] Crossref export fails with unexpected ORCID error

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#6852] opened 2021-03-10 19:52 UTC
I'm getting validation errors like:
```
Element '{http://www.crossref.org/schema/4.3.6}ORCID': This element is not expected. Expected is ( {http://www.crossref.org/schema/4.3.6}alt-name ).

Element '{http://www.crossref.org/schema/4.3.6}ORCID': This element is not expected. Expected is ( {http://www.crossref.org/schema/4.3.6}alt-name ).

Element '{http://www.crossref.org/schema/4.3.6}ORCID': This element is not expected. Expected is ( {http://www.crossref.org/schema/4.3.6}alt-name ).
```

Looking at the XML generated, it seems that the plugin is duplicating the ORCID tags:
```
        <contributors>
          <person_name contributor_role="author" sequence="first" language="pt">
            <given_name>Maria Luzia Silva</given_name>
            <surname>Mariano</surname>
            <ORCID>https://orcid.org/0000-0002-7563-2155</ORCID>
            <ORCID>https://orcid.org/0000-0002-7563-2155</ORCID>
          </person_name>
          <person_name contributor_role="author" sequence="additional" language="pt">
            <given_name>Sandra Aparecida Pires</given_name>
            <surname>Franco</surname>
            <ORCID>https://orcid.org/0000-0002-7205-744X</ORCID>
            <ORCID>https://orcid.org/0000-0002-7205-744X</ORCID>
          </person_name>
          <person_name contributor_role="author" sequence="additional" language="pt">
            <given_name>Katya Luciane de</given_name>
            <surname>Oliveira</surname>
            <ORCID>https://orcid.org/0000-0002-2030-500X</ORCID>
            <ORCID>https://orcid.org/0000-0002-2030-500X</ORCID>
          </person_name>
        </contributors>
```

**Comment by asmecher** [comment] 2021-03-10 20:04
@luizbgomide, what version of the ORCID profile plugin are you using, and what specific release of OJS 3.3.0?

**Comment by luizbgomide** [comment] 2021-03-10 20:27
@asmecher, I'm on OJS 3.3.0.3 and I'm wasn't using the ORCID profile plugin (it was disabled), but it is listed as being version: 1.1.2.14.

I just tried enabling the ORCID profile and it did not had any effect on the error, it still produces extra ORCID tags.

**Comment by luizbgomide** [comment] 2021-03-10 20:31
This is a file that is a complete file being generated by OJS, every ORCID field is duplicated.
```xml
<?xml version="1.0" encoding="utf-8"?>
<doi_batch xmlns="http://www.crossref.org/schema/4.3.6" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1" xmlns:ai="http://www.crossref.org/AccessIndicators.xsd" version="4.3.6" xsi:schemaLocation="http://www.crossref.org/schema/4.3.6 https://www.crossref.org/schemas/crossref4.3.6.xsd">
  <head>
    <doi_batch_id>_1615408179</doi_batch_id>
    <timestamp>1615408179</timestamp>
    <depositor>
      <depositor_name>Jose Anderson Santos Cruz</depositor_name>
      <email_address>anderson.cruz@unesp.br</email_address>
    </depositor>
    <registrant>Faculdade de Ciências e Letras/Unesp</registrant>
  </head>
  <body>
    <journal>
      <journal_metadata>
        <full_title>Revista Ibero-Americana de Estudos em Educação</full_title>
        <abbrev_title>Rev. Ibe. Est. Ed.</abbrev_title>
        <issn media_type="electronic">1982-5587</issn>
      </journal_metadata>
      <journal_issue>
        <publication_date media_type="online">
          <month>02</month>
          <day>01</day>
          <year>2021</year>
        </publication_date>
        <doi_data>
          <doi>10.21723/riaee.v16i2</doi>
          <resource>https://periodicos.fclar.unesp.br/iberoamericana/issue/view/771</resource>
        </doi_data>
      </journal_issue>
      <journal_article xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1" xmlns:ai="http://www.crossref.org/AccessIndicators.xsd" publication_type="full_text" metadata_distribution_opts="any">
        <titles>
          <title>Responsabilidad social universitaria en tiempos de pandemia: mirada desde la función docente (Universidad de Antofagasta – Chile)</title>
        </titles>
        <contributors>
          <person_name contributor_role="author" sequence="first" language="es">
            <given_name>Oscar</given_name>
            <surname>Rojas</surname>
            <ORCID>https://orcid.org/0000-0002-6739-5559</ORCID>
            <alt-name>
              <name language="en">
                <surname>Rojas</surname>
                <given_name>Oscar</given_name>
              </name>
              <name language="pt">
                <surname>Rojas</surname>
                <given_name>Oscar</given_name>
              </name>
            </alt-name>
            <ORCID>https://orcid.org/0000-0002-6739-5559</ORCID>
          </person_name>
          <person_name contributor_role="author" sequence="additional" language="es">
            <given_name>Marlenis</given_name>
            <surname>Martínez</surname>
            <ORCID>https://orcid.org/0000-0002-5926-599X</ORCID>
            <alt-name>
              <name language="en">
                <surname>Martínez</surname>
                <given_name>Marlenis</given_name>
              </name>
              <name language="pt">
                <surname>Martínez</surname>
                <given_name>Marlenis</given_name>
              </name>
            </alt-name>
            <ORCID>https://orcid.org/0000-0002-5926-599X</ORCID>
          </person_name>
          <person_name contributor_role="author" sequence="additional" language="es">
            <given_name>Amely</given_name>
            <surname>Vivas</surname>
            <ORCID>https://orcid.org/0000-0002-5791-8619</ORCID>
            <alt-name>
              <name language="en">
                <surname>Vivas</surname>
                <given_name>Amely</given_name>
              </name>
              <name language="pt">
                <surname>Vivas</surname>
                <given_name>Amely</given_name>
              </name>
            </alt-name>
            <ORCID>https://orcid.org/0000-0002-5791-8619</ORCID>
          </person_name>
        </contributors>
        <jats:abstract xmlns:jats="http://www.ncbi.nlm.nih.gov/JATS1">
          <jats:p>El presente artículo tiene como objetivo analizar la responsabilidad social universitaria en tiempos de pandemia, mirada desde la función docente en la promoción del autocuidado de los estudiantes. Para ello se utilizó un enfoque cuantitativo y diseño no experimental transeccional-descriptivo. Los participantes fueron 85 docentes de la carrera de pedagogía en educación básica de la Universidad de Antofagasta. Se aplicó muestreo probabilístico intencional y se utilizó cuestionario con escalamiento tipo Likert. Los resultados demostraron que los docentes manejan la responsabilidad social universitaria en tiempos de pandemia, sin embargo, necesitan fortalecer la promoción del autocuidado en los estudiantes y el manejo del conocimiento sobre pandemia con herramientas poderosas de cuidado, protección y resguardo para la vida. Los hallazgos encontrados permitieron concluir que los docentes deben promover estrategias de promoción del autocuidado, tales como el uso de podcast, vodcast, videos y cápsulas educativas que acceden a la comprensión de la pandemia COVID-19.</jats:p>
        </jats:abstract>
        <publication_date media_type="online">
          <month>02</month>
          <day>01</day>
          <year>2021</year>
        </publication_date>
        <pages>
          <first_page>424</first_page>
          <last_page>439</last_page>
        </pages>
        <ai:program xmlns:ai="http://www.crossref.org/AccessIndicators.xsd" name="AccessIndicators">
          <ai:license_ref>https://creativecommons.org/licenses/by-nc-sa/4.0</ai:license_ref>
        </ai:program>
        <doi_data>
          <doi>10.21723/riaee.v16i2.14707</doi>
          <resource>https://periodicos.fclar.unesp.br/iberoamericana/article/view/14707</resource>
          <collection property="crawler-based">
            <item crawler="iParadigms">
              <resource>https://periodicos.fclar.unesp.br/iberoamericana/article/download/14707/10412</resource>
            </item>
          </collection>
          <collection property="text-mining">
            <item>
              <resource mime_type="application/pdf">https://periodicos.fclar.unesp.br/iberoamericana/article/download/14707/10412</resource>
            </item>
          </collection>
        </doi_data>
      </journal_article>
    </journal>
  </body>
</doi_batch>
```

**Comment by asmecher** [comment] 2021-03-10 20:45
@NateWr, I think this is caused by an accidental partial revert to https://github.com/pkp/ojs/commit/0d0e86df1734e68d8915dca44e8c613c43f9c5d2 in https://github.com/pkp/ojs/commit/863fbbc22f4ee3c0a2c7aad69134f586669838f3#diff-45b7b726d545a8c94d6ed8ae07dd593d2dea5ac43db23fbfb8739a4a9cc1547fR157 -- the ORCID add code is now in place twice. Could you have a look?

**Comment by NateWr** [comment] 2021-03-11 09:40
@asmecher of the two, I think the one I removed is in the wrong place, because it will only get added if a name exists in the submission's locale: https://github.com/pkp/ojs/blob/main/plugins/importexport/crossref/filter/ArticleCrossrefXmlFilter.inc.php#L122. But the commit message for https://github.com/pkp/ojs/commit/0d0e86df1734e68d8915dca44e8c613c43f9c5d2 suggests that there is some logic that needs to be considered here. Do you know if this is ok?

PR:
https://github.com/pkp/ojs/pull/3070 (`stable-3_3_0`)

**Comment by luizbgomide** [comment] 2021-03-11 11:40
@NateWr, according to the parser, the first ORCID is correct and the second on is misplaced/malformed.

**Comment by luizbgomide** [comment] 2021-03-11 11:44
I found this relevant section of the schema:
```xml
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="given_name" minOccurs="0"/>
<xsd:element ref="surname"/>
<xsd:element ref="suffix" minOccurs="0"/>
<xsd:element ref="affiliation" minOccurs="0" maxOccurs="5"/>
<xsd:element ref="ORCID" minOccurs="0" maxOccurs="1"/>
<xsd:element ref="alt-name" minOccurs="0"/>
</xsd:sequence>
<xsd:attributeGroup ref="contributor.atts"/>
</xsd:complexType>
```

**Comment by asmecher** [comment] 2021-03-11 17:32
Thanks, @luizbgomide; @NateWr, the wrong order of elements is what motivated https://github.com/pkp/ojs/commit/0d0e86df1734e68d8915dca44e8c613c43f9c5d2 in the first place. See https://github.com/pkp/ojs/pull/2882.

> I think the one I removed is in the wrong place...

@withanage, I think this is the problem I raised on the original pull request at https://github.com/pkp/ojs/pull/2882#issuecomment-715448673 but it didn't get fixed before merging. Could you and @NateWr resolve and review this?

**Comment by NateWr** [comment] 2021-03-11 17:38
Does the Crossref schema support an ORCID if there is no givenName or familyName? We will probably need to support deposits without a givenName or familyName (for example, institutional names). But I suppose these don't typically have ORCIDs?


I guess I'm wondering if the problem is at Crossref's end. Does having an ORCID depend on a `given_name` or `surname` existing? Or is it enough just to move it up top above all possible names?

**Comment by luizbgomide** [comment] 2021-03-11 17:42
> Does the Crossref schema support an ORCID if there is no givenName or familyName? We will probably need to support deposits without a givenName or familyName (for example, institutional names). But I suppose these don't typically have ORCIDs?

Here is the full documentation https://data.crossref.org/reports/help/schema_doc/doi_resources4.3.6/doi_resources4.3.6.html the relevant element is `person_name`. The fields are all independent but are sequential according to the schema excerpt I posted above. I think the only element that is required is `surname` the others are optional.

**Comment by NateWr** [comment] 2021-03-15 10:45
Ok, I've changed my PR to move the ORCID back into the block and I've filed an issue to catch problems with authors that have no `givenName` at https://github.com/pkp/pkp-lib/issues/6863.

From the schema that you posted, @luizbgomide, it doesn't sound like Crossref is ready to handle works attributed to an institution. I'll follow up with our team about that to see if we can figure it out.

**Comment by AhemNason** [comment] 2021-03-15 16:48
This is untrue. Crossref has schema for organizations, just not under the <person_name> element. 

https://data.crossref.org/reports/help/schema_doc/4.4.2/schema_4_4_2.html#contributors

`<contributors xmlns="http://www.crossref.org/schema/4.4.2">
  <organization contributor_role="" language="" name-style="" sequence="">{1,1}</organization>
  <person_name contributor_role="" language="" name-style="" sequence="">{1,1}</person_name>
  <anonymous contributor_role="" language="" name-style="" sequence="">{1,1}</anonymous>
</contributors>`

In this case, it is a mistake for OJS to assume a contributor is a person. Organization names are handled in the Crossref schema in a separate element within contributors.

**Comment by asmecher** [comment] 2021-03-15 19:35
Merged https://github.com/pkp/ojs/pull/3070 and cherry-picked to `main`. @NateWr, is there more to be done, in particular WRT @AhemNason's comment above?

**Closed** 2021-03-16 09:19 UTC

**Comment by diegoabadan** [comment] 2021-04-15 21:23
This problem seems to occur in 3.2.x as well.

**Comment by AhemNason** [comment] 2021-04-16 11:24
> This problem seems to occur in 3.2.x as well.

Hey @diegoabadan, it's possible what you're seeing in 3.2.x is this: https://github.com/pkp/ojs/pull/2882 

The validation errors are similar but they were caused by different things.

**Comment by diegoabadan** [comment] 2021-04-19 13:03
@ffpl, can confirm?

**Comment by diegoabadan** [comment] 2021-04-19 22:15
@AhemNason You're right, it was the pkp/ojs#2882 correction we used.
Thanks!

**Comment by marcbria** [comment] 2021-07-01 15:17
> The validation errors are similar but they were caused by different things.

@AhemNason does it means that issue #2882 still need to be fixed.
I tested today on ojs 3.2.1-4 with last plugin released in the galley (v1.1.2.18 published 22-05-2021) and ORCID tag is still missplaced after alt-name (instead of before).

Talking in #2882 if you prefer...

**Comment by AhemNason** [comment] 2021-07-03 23:17
> @AhemNason does it means that issue #2882 still need to be fixed.
> I tested today on ojs 3.2.1-4 with last plugin released in the galley (v1.1.2.18 published 22-05-2021) and ORCID tag is still missplaced after alt-name (instead of before).

I know this issue was fixed around the same time. Alec seems to suggest in #2882 that this patched addressed both issues. Or they were both addressed around the same time I do know that is of 3.3.0-4 we were in the clear on this error. Working backwards, I'd recommend exporting the XML and moving the order around. Depending on the volume being deposited might be a non-trivial headache! I had to do it for a few clients while we waited on patches.

**Comment by marcbria** [comment] 2021-07-05 07:07
Thanks Mike.

I though it was related with Dulip's orcid plugin and updating the plugin was enough... but looks like this part is in core.
Sorry for the misunderstanding.

@asmecher, do you remember if is this included in last stable-3.2? 
If not, any chance to add it next 3.2 release?

**Comment by asmecher** [comment] 2021-07-05 16:05
We're not planning any more 3.2.x releases, Marc; it's not in `stable-3_2_1` but if someone can quickly confirm that the patch (https://github.com/pkp/ojs/pull/2882) applies cleanly and works on 3.2.1 then I can cherry-pick it to `stable-3_2_1` for git users.

**Comment by marcbria** [comment] 2021-07-05 16:20
I didn't explain myself. I know about the end of 3.2.x releases (and I understand why they should end).
When I said "next 3.2 release" I was talking about next "stable-3.2" (aka. stable-3_2_1).

I will try to find some time tomorrow to test this.
@asmecher, if I test #7138 and #6807 are you open to include in the stable-3_2_1 too?

**Comment by asmecher** [comment] 2021-07-05 17:33
Yes, I can, @marcbria!

**Comment by asmecher** [comment] 2021-07-06 15:27
I've cherry-picked https://github.com/pkp/ojs/pull/2882/commits/0d0e86df1734e68d8915dca44e8c613c43f9c5d2 into `stable-3_2_1`, thanks for confirming.
