### ISSUE TITLE
Invalid language when adding a new journal

### ISSUE THREAD

**Issue by NateWr** [pkp/pkp-lib#8327] opened 2022-10-11 11:48 UTC
**Describe the bug**
It is possible to install a two-letter locale, such as `ar` instead of `ar_IQ`. If a two-letter locale has been installed and it is selected when creating a new context, the new context form will return a validation error:

> This is not formatted correctly.

**To Reproduce**
1. Go to Administration > Site Settings > Site Setup > Languages
2. Click **Install Locale**
3. Select the first option, **Arabic**. (Not the next one, **Arabic (Iraq)**).
4. Click **Save**.
5. Go to Administration > Hosted Journals.
6. Click **Create Journal**.
7. Enter the required fields.
8. Select **Arabic** as one of the **Languages**.
9. Click **Save**.
10. See error

**What application are you using?**
`main` branch (3.4 pre-release)

**Additional information**
Screenshot of the two-letter Arabic locale that can be installed. (there are other locales like this too)
![install-locale](https://user-images.githubusercontent.com/2306629/195081667-6aa6c887-37ea-4ded-854d-7cf6d3aaabfc.png)

Screenshot of the validation error when creating a new journal.
![allowed-languages-error](https://user-images.githubusercontent.com/2306629/195081762-25e8bb4b-113a-4df1-b0cb-d1912c7b76a8.png)

**Comment by touhidurabir** [comment] 2022-10-13 09:26
The cause of the problem is our regex based validation rules which require the locale code match the format `LangCode_CountryCode` (for example `en_US`) . We need to make the regex validation rule bit more flexible to make the `_CountryCode` part as optional . 

@NateWr PRs to review 

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8332
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3576

If all ok for `OJS` , then I will port the changes for `OMP` and `OPS` .

**Comment by NateWr** [comment] 2022-10-13 10:08
I'm going to let @asmecher review this because I'm not sure if we support two-letter language codes yet. He'll know better what the plan is here.

**Comment by asmecher** [comment] 2022-10-17 20:23
We went over this on the dev call today, but just to summarize: we should support two-letter language codes, and will probably need to do so for 3.4.0 due to the latest Weblate (to which we upgraded recently) being pickier in that regard. I'm supportive of starting to adopt support for 2-letter language codes ASAP.

**Comment by NateWr** [comment] 2022-10-18 09:04
I'm a little worried about the proliferation of languages from a UX perspective. Can we go ahead and merge country-level language codes with language-only codes? For example:

```
Arabic
Arabic (Iraq)
Portuguese (Brazil)
Portuguese (Portugal)
```

Could be come:

```
Arabic
Portugese
Portugese (Portugal)
```

Because Arabic only has one language code. And Portuguese (Brazil) is the more complete one?

**Comment by asmecher** [comment] 2022-10-18 15:52
> I'm a little worried about the proliferation of languages from a UX perspective.

Yes, I'm mulling this over and will come up with a solution for 3.4.0.

**Comment by touhidurabir** [comment] 2022-11-02 13:57
@asmecher with the merge of pkp/pkp-lib#7352, the bugs I was facing previously seems fixed . If the test for `OJS` passed , it should be good to merge as only regex validation rules get updated in the PRs . if all ok, then I will forward port the changes for `OPS` and `OMP` .

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8332
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3576

**Comment by asmecher** [comment] 2022-11-02 17:31
I've merged both, thanks; please do port to OMP and OPS.

**Comment by touhidurabir** [comment] 2022-11-03 07:24
@asmecher PRs 

[ops](https://github.com/touhidurabir/ops) --> https://github.com/pkp/ops/pull/385
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1239

**Comment by asmecher** [comment] 2022-11-03 19:35
Thanks, @touhidurabir! Closing.

**Closed by asmecher** 2022-11-03 19:35 UTC
Labels: Bug:3:Critical, Translation
