### ISSUE TITLE
[OJS] Saving the Website - Appearance - Setup form auto-focuses on Homepage Image Alt Text field

### ISSUE THREAD

**Issue by davidjb** [pkp/pkp-lib#6873] opened 2021-03-22 00:41 UTC
In OJS v3.3.0_3 (haven't yet tested with v3.3.0_4), saving the journal appearance setup form (at `/management/settings/website#appearance`) sees the browser auto-scroll to and shift focus to Homepage Image Alt Text field in the middle of the page:

```html
<input type="text" id="appearanceSetup-homepageImage-altText-en_US" aria-describedby="appearanceSetup-homepageImage-altTextDescription-en_US" class="pkpFormField__input pkpFormField--uploadImage__altTextInput">
```

This has the effect of confusing the user -- they get taken away from the Save button which correctly indicates the page saved.  In my user's case, they were editing the Alt Text field itself, which made them think that they'd made an error, since the form returned them to the field they just modified.

Looking into this issue further, the altText field receives focus irrespective of what changes were previously made; for example, editing the footer, other logos or other altTexts all will see the focus applied (and the browser auto-scroll) to this field.  The same applies if you don't even make any changes and just click Save -- the autofocus is always applied to _this_ altText field.

I can reproduce similar behaviour on a journal's Advanced appearance form (at `/management/settings/website#appearance/advanced`) -- clicking the Save button here auto-focuses on the Favicon Upload file button:

```html
<button class="pkpButton pkpFormField--upload__addFile dz-clickable" id="appearanceAdvanced-favicon-clickable-en_US"> Upload File </button>
```

Visually, one can see this but to observe the auto scrolling you need to shrinkthe height of the browser window, because the button is much earlier in the page than the altText field.

**Comment by NateWr** [comment] 2021-03-22 11:48
How strange! It will focus on the upload button if no image is uploaded, too. :thinking: 

Ok, it looks like this was due to some overzealous focus management. It was likely set up to prevent focus from getting dropped from the DOM when adding/removing files. But after removing the offending focus call, I couldn't reproduce any scenarios where the focus was dropped.

PR:
https://github.com/pkp/ui-library/pull/148 (stable-3_3_0)

Tests:
https://github.com/pkp/ojs/pull/3078 (stable-3_3_0)

**Comment by NateWr** [comment] 2021-03-23 10:22
Merged to `stable-3_3_0` and cherry-picked to `stable-3_3_1` and `main`.

**Closed by NateWr** 2021-03-23 10:22 UTC
Labels: Bug
