### ISSUE TITLE
Select window opens twice

### ISSUE THREAD

**Issue by amandasramalho** [pkp/pkp-lib#1740] opened 2016-08-19 19:09 UTC
When I select an attachment (image, PDF, Word), the select window opens twice: at the first time it doesn't work, it work only in the second time.
![telaanexos](https://cloud.githubusercontent.com/assets/5446933/17821168/9d59e9e6-6626-11e6-9c1a-ef8f03f46b77.png)

Current version: 1.2.0.0 (August 17, 2016 - 09:17 PM)

**Comment by Vitaliy-1** [comment] 2016-09-26 12:26
This issue is relevant and for OJS3

**Comment by asmecher** [comment] 2016-09-26 22:09
This appears to be Chrome-specific. @NateWr, I think I mentioned this one to you via email.

**Comment by NateWr** [comment] 2016-09-28 10:28
@asmecher Should we flag this for OJS 3.0.1 rather than OMP 1.2.1?

**Comment by asmecher** [comment] 2016-09-28 17:29
Yup, moved over to 3.0.1.

**Comment by NateWr** [comment] 2016-10-10 16:48
@amandasramalho and @Vitaliy-1 are you able to provide any more details about your OS or browser? I'm unable to reproduce this myself so I suspect it has to do with a particular mix of OS and browser (eg - Windows 10/Chrome 52.0.2743.116).

If you can provide me with those details I'll try to get a virtual machine going so I can test to see why this is happening.

**Comment by NateWr** [comment] 2016-10-10 16:58
Ok, I was able to reproduce this with Win10/IE11. It seems to be an oddity with the windows file browser. I'll see what I can find.

**Comment by amandasramalho** [comment] 2016-10-10 17:06
@NateWr Windows 10 Pro/ Google Chrome 53.0.2785.143 m

**Comment by NateWr** [comment] 2016-10-10 18:00
I've tracked the source of the problem down to [this code](https://github.com/pkp/pkp-lib/blob/master/js/controllers/UploaderHandler.js#L91-L97), which passes clicks on the visual button to plupload's invisible button which normally intercepts clicks. 

This code is important for keyboard accessibility though: it's what makes it possible to tab to the button and hit enter to open the file browser.

For some reason, Windows browsers (I was able to reproduce it in Windows 7 and 10 with IE11 and Chrome) are passing clicks through the visual button, even though this doesn't represent a "bubbling up" of the click event in the dom. All I can think is that maybe this is something inside of plupload that does this to fix some kind of previous Windows-specific bugs, so maybe it's detecting OS and passing the event or something. :shrug:

I will try to think of a work-around, perhaps by finding other ways to "fake" the keyboard interaction.

**Comment by NateWr** [comment] 2016-10-11 08:52
I've issued a PR: https://github.com/pkp/pkp-lib/pull/1871
Tests are running at: https://github.com/pkp/ojs/pull/1050

However, I'm pretty nervous about the hacky workaround we've got in place for this. I've included further details in the commit message, which is copied here:

> This commit removes code which passes clicks on the file upload button to the plupload control. This code was added to improve keyboard accessibility, but in Windows browsers it caused the file browser to be opened twice.
>
> Removing this code presents accessibility challenges, which were addressed by providing visual feedback which mocked a focus effect on the browse button when focus is placed on plupload's control. This does not address the accessibility issue whereby the plupload control has no meaningful text label. Screen readers may suffer.
>
> In addition, disabling clicks on the visual button could cause some compatibility runtimes to break. plupload includes several different compatibility runtimes to ensure as wide a browser support as possible. But we're not able to test all of these comprehensively. We may find the downside to this change is bigger than the upside.

**Comment by HighwayStar** [comment] 2016-10-11 09:34
I have same issue on openSUSE 13.2 with Chromium 51.0.2704.103 64bit with KDE integration (KDialog). I've not tried proposed fix yet.

**Comment by asmecher** [comment] 2016-10-12 04:13
@HighwayStar, hmm, can you try the fix and see if the behavior seems to be the same despite the different operating system?

**Comment by mfelczak** [comment] 2016-10-19 20:32
Hi @asmecher, @NateWr -- can also confirm this bug on the latest Chrome in OSX. The workaround seems to fix it.

**Comment by NateWr** [comment] 2016-10-20 09:34
Thanks @mfelczak. Unless we want to book time in a device lab (there's one here in Edinburgh), I think our best bet is just to implement the change for 3.0.1 and see if it causes loads of problems.

**Comment by mfelczak** [comment] 2016-10-20 15:31
Thanks @NateWr. I just read your comments above re: accessibility and it's quite a tradeoff to get this working. I don't know what to suggest, other than maybe it'd be worthwhile to keep this issue open for now and see if we can find another solution.

**Comment by NateWr** [comment] 2016-11-10 13:12
@asmecher It looks like I may have accidentally deleted the branch with this in it during a cleanup a while back.  Are we good with this solution for now? Should I re-submit the PR?

**Comment by asmecher** [comment] 2016-11-14 17:15
@NateWr, please do, thanks. This kind of front-end stuff is not my forte, and no better solution has come to mind.

**Comment by NateWr** [comment] 2016-11-21 15:48
New PR:
https://github.com/pkp/pkp-lib/pull/2014

Tests running at:
https://github.com/pkp/ojs/pull/1108

**Comment by ajnyga** [comment] 2016-11-21 18:49
Hi,

Have you tested the changed code with Safari as well? I just arranged 15 OJS3 workshops last week for our journals and basically with all Safari browsers only the drag and drop option worked for uploads. You could not select a file with Safari by pressing the button and searching for the file.

Many users also noticed the problem mentioned in this issue, so nice to hear that it is getting solved!

**Comment by NateWr** [comment] 2016-11-22 10:38
Hi @ajnyga, no, I haven't tested on Safari. I don't have a Mac and I'm not aware of any solid VM for testing Safari. Unfortunately, Safari is the new IE8 in terms of browser issues.

Are you able to checkout the change to see if it works on Safari?

**Comment by NateWr** [comment] 2016-11-22 10:39
@bozana, do you mind doing code review on this? The tests seemed to pass except for just one of the `pgsql` tests which seemed to [time out](https://travis-ci.org/pkp/ojs/jobs/177690101#L1819-L1834).

I'll rebase this to fix the `lib/pkp` conflict.

**Comment by bozana** [comment] 2016-11-22 12:42
@NateWr, would you correct those JS linting/compiling messages?

**Comment by ajnyga** [comment] 2016-11-22 13:16
@NateWr thanks, I can do the testing with Safari and will report back how this works.

**Comment by NateWr** [comment] 2016-11-22 15:04
Thanks @bozana, tests running again.

**Comment by bozana** [comment] 2016-11-22 16:24
@NateWr, tests passed, I will merge...

**Comment by NateWr** [comment] 2016-11-24 09:58
Yeah this should probably get cherry-picked since it's such a big problem for a couple browsers.

**Comment by bozana** [comment] 2016-11-24 13:56
@NateWr, will you cherry-pick it?

**Comment by NateWr** [comment] 2016-11-28 11:16
Cherry-picked!

**Comment by ajnyga** [comment] 2016-11-29 12:27
Hi,

This does not fix the issue with Safari. Only drag and drop works. I will open a new issue on this later today.

**Comment by NateWr** [comment] 2016-12-07 10:25
Carola is reporting issues with this change in OMP. Re-opening and assigning to the OMP 1.2.1 milestone. She'll provide a fuller report here.

**Comment by CFanselow** [comment] 2016-12-07 11:53
Hi, 

I have three installations where the file browser windows does not open anymore after pulling from omp-stable-1_2_0: one where I upgraded from OMP 1.1.1-1 and two OMP 1.2.0 installations. We didn't have problems with uploading files before (including the double window problem). 

I cleared all caches (browser, OJS-admin area, cache-folder) but that didn't change anything. 

There's also no entry in the error log. 

Browsers: Firefox 50.0.2, Chrome 54.0.2840.99 m, OS: Windows 7

The OMP installations are running on Debian GNU/Linux 8 (jessie), PHP 5.6.20-0+deb8u1.

I undid the change in fileUploadContainer.tpl  (https://github.com/pkp/pkp-lib/commit/9ab140b7342b436f1031b23beeeffae4eb3ea4b0) for the live installation and the upload works fine again. The other two installations are only testinstallations and I can do with them whatever you suggest for testing.

**Comment by NateWr** [comment] 2016-12-07 12:14
Thanks @CFanselow. Hmm, I'll have to do some testing in OMP to see if I can replicate the problem.

If it is working fine having reverted that change, I think you're probably safe leaving it. One thing you might want to check is whether you get any problems with IE on Windows. That's the problem this commit was trying to solve, so you'll at least have a sense of what you've reverted to if there is any problem for you.

**Comment by NateWr** [comment] 2017-02-21 13:32
@CFanselow I'm unable to reproduce this myself. I tested using a Win7 VM in IE9/10/11 and in the latest version of Chrome.

I see that there was an issue that Alec fixed on Dec 16, after you reported having problems:

https://github.com/pkp/pkp-lib/commit/9ab140b7342b436f1031b23beeeffae4eb3ea4b0#commitcomment-20220605

Maybe that fixed it? If you get a chance, would you be able to test again and see if you can reproduce the issue with the latest version of OMP master?

Thanks, and sorry for the lengthy delay on this one.

**Comment by NateWr** [comment] 2017-10-27 14:08
@CFanselow did you ever get a chance to test the fix in the comment above?

**Comment by NateWr** [comment] 2017-11-08 11:07
Closing until we get more reports of an issue.

**Closed by NateWr** 2017-11-08 11:07 UTC
