### ISSUE TITLE
[OJS 3.1.0-1] Settings for “CSL” plugin not saved/displayed properly

### ISSUE THREAD

**Issue by Ph-We** [pkp/pkp-lib#3222] opened 2017-12-25 11:19 UTC
When you get there for the first time, none of them is neither marked, nor saved. Actually the default settings get erased in this case.
When you get there again and mark some of them, they are saved, when you close it. 
When you open it again, they are still saved, but not marked.

https://forum.pkp.sfu.ca/t/settings-for-citation-style-language/34847

**Comment by NateWr** [comment] 2018-01-04 16:08
Just a quick comment but I think that this has been fixed as part of other work. If I recall, it was part of the listbuilders refactor, where some improvements were made to the SelectListPanel (https://github.com/pkp/pkp-lib/issues/2965#issuecomment-342225140).

That work is very near completion and should be merged soon. But I'll assign this to myself to check again once it's merged to ensure it's working ok.

**Comment by NateWr** [comment] 2018-01-09 16:37
I was able to reproduce this after merging that commit so I'll need to take a deeper look.

**Comment by NateWr** [comment] 2018-01-10 13:06
Oh ok, I see what's happening (sort of). There seems to be a delay in how long it takes to write the change to the database. If I reload the settings modal immediately, the changes don't appear to take place. But if you make changes, then wait a few seconds before opening the settings, it should appear correctly.

I'm not exactly sure what's causing the delay here, but I've noticed a similar thing with theme selection -- it takes a few seconds for the settings to "take effect". 

@asmecher would this be a caching layer of some kind?

**Comment by NateWr** [comment] 2018-01-10 13:06
(ps - I'm going to close this as the settings lists are working. if we can figure out the delay that's great but we can do it in a separate ticket.)

**Closed by NateWr** 2018-01-10 13:06 UTC

**Comment by Ph-We** [comment] 2018-01-10 13:38
@NateWr, thank you. But the problem was that the settings really got erased -- so that there was absolutely nothing in the "More citation formats" drop-down list. Regardless of the time passed.

**Comment by NateWr** [comment] 2018-01-10 14:52
@Ph-We That problem should be resolved in current `master` branch.

**Comment by Ph-We** [comment] 2018-01-10 14:56
OK, thanks again!

**Comment by asmecher** [comment] 2018-01-10 23:48
@NateWr, regarding an apparent delay, this *should* be the order of things:

1. POST gets processed by form
2. form saves settings to the database
3. If the settings are cached, the cache file is also updated
4. An OK message is bounced back to the front end (typically by JSON)
5. A grid reload or similar may re-present new data.

If a fetch hits the server before step 3 is executed, the client may get old data. However, any client-side reload (step 5) is usually kicked off by the JSON response (step 4), which keeps things in sequence. Beyond that, I'm not sure what could be happening.

**Comment by NateWr** [comment] 2018-01-11 10:57
Yeah that was my impression so I'm just not sure why I see this happening. But it doesn't seem to be causing any major issues.
