### ISSUE TITLE
[OJS 3.4 rc3] Dashboard link goes to user Profile

### ISSUE THREAD

**Issue by forgive38** [pkp/pkp-lib#8971] opened 2023-05-09 15:06 UTC
Hello

If we are login as an author and this author has no submission, if we are on the front website of OJS, and we select Dashboard in the menu in upper right, we go to the Profile page, it’s disappointing : I’d prefer to go to new submission I think.

Thanks

**Comment by saalam** [comment] 2023-06-08 19:46
Hi @forgive38 and @asmecher,
We run multi-journal website (OJS 3.3.0-14) and I have the same issue when I log in as administer. Dashboard link goes to user profile as well. I would prefer it to go to the administration page instead.  
Many Thanks,

**Comment by touhidurabir** [comment] 2023-06-12 12:13
I tried to reproduce this issue and was not able to . But I think I understand where and why this confusion is occurring . Consider the following set up case for a multi journal installation: 

Journal Installation path : my-test-journal.com
Journal 1 : Test-01(journal path set to test-01) with author Author1
Journal 2 : Test-02(journal path set to test-02) with author Author2

**CASE 1 :** Now when an author(author1) login from a link such as `http://my-test-journal.com/index.php/index/login` , after a successful login, it will redirect to `http://my-test-journal.com/index.php/index/index` . See that in the URI segment , there is no mention of journal path(such as `test-01` or `test-02`) . In such case if user tried to access the `Dashboard` link form the top right dropdown menu, it will take the user to profile path as there is no way to know which journal to take user to as that information is missing in the URL . 

**CASE 2 :** Consider that author(author2) has author role in journal Test-01(with journal path set to test-01) . now if author login via link `http://my-test-journal.com/index.php/test-01/login`, after a successful login , user will be redirected to submission page as the target journal path is present in the url as `test-01` . 

The same is happening for multi journal installation and for multi journal case , it make more sense . As if the any user has association with multiple journal, and user login via link such as `http://my-test-journal.com/index.php/index/login`, that is without the journal path, then via dashboard link it's not possible to determine which is the intended journal that user want to visit . 

@forgive38  and @saalam , can you confirm the scenario and cases that I have described above ? 

### Possible Solution :
When a user has association with multiple journal , for login URI such as `/index.php/index/login` , it think it's not possible to redirect user to any specific journal submission or other pages as there no way to determine user's intended journal . 

for a case when a single user has association with a single only journal or if there is no multiple journal configured, only then a user can be redirected only to the associated journal submission page or other page .

**Comment by saalam** [comment] 2023-06-12 14:23
Hi @touhidurabir 
I can only confirm **CASE1** and never tried **CASE2**. In CASE1, You described the issue I used to face as I always login with Administrator role. The problem is if I tried to access the Dashboard link form the top right dropdown menu, Both Dashboard and View profile links will take me to the profile page.

**Comment by touhidurabir** [comment] 2023-06-13 09:58
@saalam do you have multiple journal enable ? if that is the case and if you visit your site as `my-journal.com` and click login , it will redirect to url `http://my-journal.com/index.php/index/login` instead of a journal specific url path, for example `http://my-journal.com/index.php/test-01/login` . See the different between 2 url paths , there is a `index` for non journal and `test-01` for journal specific

```
http://my-journal.com/index.php/index/login (Non Journal specific url)
http://my-journal.com/index.php/test-01/login (Journal specific url)
```

As I have mentioned in `CASE 1` , that would be intended behaviour for any user regardless of role as there is no way to determined the user intended journal form the url path . 

I think the best solution for this would be what in mentioned above as 

> Possible Solution :
When a user has association with multiple journal , for login URI such as /index.php/index/login , it think it's not possible to redirect user to any specific journal submission or other pages as there no way to determine user's intended journal .
> 
> for a case when a single user has association with a single only journal or if there is no multiple journal configured, only then a user can be redirected only to the associated journal submission page or other page .

**Comment by saalam** [comment] 2023-06-14 17:26
@touhidurabir Yes I have. Thanks a lot for your explanation. I can now see the different between the two cases. 
Regards,

**Comment by asmecher** [comment] 2023-06-26 23:46
@forgive38, can you review the conversation here and see if it clarifies things for you? Would @touhidurabir's suggestion improve things?

**Comment by asmecher** [comment] 2023-07-13 16:26
Closing for now -- though always open to more feedback!

**Closed by asmecher** 2023-07-13 16:26 UTC
