### ISSUE TITLE
Error install QucikSubmit plugin via web

### ISSUE THREAD

**Issue by myzamri** [pkp/pkp-lib#6289] opened 2020-10-17 04:08 UTC
Installation of QuickSubmit plugin is unsuccesssful.  error log:

[Sat Oct 17 11:56:01.265575 2020] [php7:warn] [pid 25136] [client 183.171.185.96:48068] PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /var/www/ojs-3.2.1/lib/pkp/classes/plugins/PluginHelper.inc.php on line 114, referer: https://ojs.zakat.com.my/index.php/azjaf/management/settings/website?r=5f8a697ce4c90
[Sat Oct 17 11:56:01.265755 2020] [php7:warn] [pid 25136] [client 183.171.185.96:48068] PHP Warning:  rename(/tmp/quickSubmit9c5bee9632/quickSubmit,/var/www/ojs-3.2.1/plugins/importexport/quickSubmit): Invalid cross-device link in /var/www/ojs-3.2.1/lib/pkp/classes/plugins/PluginHelper.inc.php on line 114, referer: https://ojs.zakat.com.my/index.php/azjaf/management/settings/website?r=5f8a697ce4c90
[Sat Oct 17 11:56:01.265848 2020] [php7:notice] [pid 25136] [client 183.171.185.96:48068] PHP Notice:  Undefined variable: errorMsg in /var/www/ojs-3.2.1/lib/pkp/controllers/grid/plugins/PluginGalleryGridHandler.inc.php on line 311, referer: https://ojs.zakat.com.my/index.php/azjaf/management/settings/website?r=5f8a697ce4c90
[Sat Oct 17 11:56:29.449616 2020] [php7:warn] [pid 31629] [client 183.171.185.94:60048] PHP Warning:  fsockopen(): unable to connect to ssl://github.com:443 (Connection timed out) in /var/www/ojs-3.2.1/lib/pkp/classes/file/wrappers/HTTPFileWrapper.inc.php on line 77, referer: https://ojs.zakat.com.my/index.php/azjaf/management/settings/website?r=5f8a697ce4c90
[Sat Oct 17 11:56:29.449856 2020] [php7:notice] [pid 31629] [client 183.171.185.94:60048] PHP Notice:  Undefined variable: errstr in /var/www/ojs-3.2.1/lib/pkp/classes/file/wrappers/HTTPFileWrapper.inc.php on line 78, referer: https://ojs.zakat.com.my/index.php/azjaf/management/settings/website?r=5f8a697ce4c90
[Sat Oct 17 11:56:29.449950 2020] [php7:notice] [pid 31629] [client 183.171.185.94:60048] /var/www/ojs-3.2.1/lib/pkp/classes/file/wrappers/HTTPFileWrapper.inc.php:78 Could not connect to ssl://github.com: , referer: https://ojs.zakat.com.my/index.php/azjaf/management/settings/website?r=5f8a697ce4c90

**To Reproduce**
1. Click plugin link to install
2. Notification says null after installation
3. Unlisted in Installed Plugins tab

**What application are you using?**
 OJS 3.2.1

**Additional information**
![image](https://user-images.githubusercontent.com/24725694/96328027-606c6f00-1071-11eb-96d3-67bc9770fd84.png)

**Comment by asmecher** [comment] 2020-10-17 15:06
This is a duplicate of https://github.com/pkp/pkp-lib/issues/6035.

**Closed by asmecher** 2020-10-17 15:06 UTC
