### ISSUE TITLE
[OJS] Empty sidebar breaks javascript in front end

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2136] opened 2017-01-03 13:32 UTC
After a test upgrade to OJS 3.0.1 I noticed that my journals are not showing anything in article usage statistics:
![screenshot_25](https://cloud.githubusercontent.com/assets/16347527/21609110/336f3a68-d1c9-11e6-8912-c1156fca7545.png)

First I thought that the statistics migration has gone wrong but after looking into the usage stats plugin I noticed that I can easily print all usage data to the article page. However, all the javascripts the plugin is trying to load are not working and not visible in the source.

The reason seems to be that an empty sidebar is breaking something. There is nothing visible in the error logs or the console, but these screen caps summarize the problem.

The above problem is visible if the sidebar is empty:
![screenshot_26](https://cloud.githubusercontent.com/assets/16347527/21609188/ac2fba5e-d1c9-11e6-9ff5-5741c4eb2623.png)

However, if I move at least one block plugin to the sidebar:
![screenshot_27](https://cloud.githubusercontent.com/assets/16347527/21609198/c072c8e4-d1c9-11e6-8ce0-3789b0d236de.png)

The statistics load correctly:
![screenshot_28](https://cloud.githubusercontent.com/assets/16347527/21609205/c85bd302-d1c9-11e6-8f03-1f965a981dc8.png)

This was a extremly difficult problem to track, I wonder why there are no errors visible anywhere?

Edit: the same problem with a clean 3.0.1. install.

**Comment by bozana** [comment] 2017-01-05 16:33
:-P Crazy situation...
The problem is that the necessary JS scripts are missing i.e. they are not inserted into the page. But I cannot figure out why is this happening :-\
They are correctly added here: https://github.com/pkp/pkp-lib/blob/master/classes/template/PKPTemplateManager.inc.php#L699 i.e. the `$this->_javaScripts` contains all necessary scripts, but they are then not loaded here: https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/footer.tpl#L52 :-O
When I then display the `$script` variable in the template/frontend/objects/article_details.tpl template, where the scripts are added by the plugin, they are there, but in the next template templates/frontend/components/footer.tpl, where they are currently loaded (s. https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/footer.tpl#L52), they are not there :-OOO  This is only so if there is no sidebar i.e. if this code is missing: https://github.com/pkp/pkp-lib/blob/master/templates/frontend/components/footer.tpl#L18-25 :-OOO I do not understand why :-\ @asmecher, any idea why is this so?

I think this could be a solution:
To provide a different context than 'frontend' for those plugin JS here: https://github.com/pkp/ojs/blob/master/plugins/generic/usageStats/UsageStatsPlugin.inc.php#L67-68
And to load them at the very end of the appropriate plugin template file i.e. after the line 25 here: https://github.com/pkp/pkp-lib/blob/master/plugins/generic/usageStats/templates/outputFrontend.tpl#L25.
But I am not sure if this is the correct way -- I am not sure about the concept of plugin JS loading in general. @asmecher and @NateWr, could you tell me, how is it meant to be?

**Comment by asmecher** [comment] 2017-01-05 16:50
I think the basic problem is the lifecycle of the `$_javaScripts` array vs. the lifecycle of plugin/page loading. The `$_javaScripts` array needs to be fully populated when the page's header is presented, but I suspect it's only being populated later when the sidebar is built (=block plugins loaded) in some cases. @NateWr, what do you think about consideration for later `$_javaScripts` additions?

**Comment by bozana** [comment] 2017-01-05 16:53
Maybe just a comment for this case: this plugin populates JS when article page is loaded i.e. using the hook in the article_details.tpl file and the `$sripts` variable is there in the article_details.tpl but in the next included template file footer.tpl it is not there any more if there is no sidebar.

**Comment by NateWr** [comment] 2017-01-06 14:04
Hmm. :confused:

**Comment by NateWr** [comment] 2017-01-11 09:25
This is happening because the resources are displayed using the `$scripts` variable passed to the template. When something hooks in in while a template is being rendered, it adds to `$templateMgr->_javaScripts`, but the `$scripts` variable isn't updated.

I think the solution is to remove the `$scripts` variable from the `{load_scripts}` and `{load_styles}` calls. These helper functions can pull directly from `$templateMgr` so any updates during processing will be included.

**Comment by NateWr** [comment] 2017-01-11 09:43
These PRs fix this issue by removing the `$scripts`, `$styles`, and `$headers` template variables. The smarty functions now fetch these assets from the template manager. This may be a breaking change in some cases, if anyone relied on access to these template variables. But I suspect not.

I also added something I did in the manuscript child theme: if no sidebar is present, the content panel is now centered.

PRs:
https://github.com/pkp/pkp-lib/pull/2181
https://github.com/pkp/ojs/pull/1187
https://github.com/pkp/omp/pull/380

**Comment by asmecher** [comment] 2017-01-11 17:21
@NateWr, are these ready for someone to look at?

**Comment by NateWr** [comment] 2017-01-11 17:29
Looks like the tests are failing. I'm kinda heads-down on something now but I'll try to fix the tests tomorrow.

**Comment by asmecher** [comment] 2017-01-11 21:05
The tests are failing because we updated the ISO countries list and United States became United States of America. I've updated the tests to suit and they're running now; by the time you read this you should be able to rebase to fix the issue on your PRs.

**Comment by NateWr** [comment] 2017-01-12 10:13
Rebased and tests are running. I'll check back after lunch.

**Comment by NateWr** [comment] 2017-01-12 13:56
Looks like a couple of the tests timed out. There was a merge conflict anyway so I've rebased. Tests re-running.

**Comment by NateWr** [comment] 2017-01-17 15:38
Tests passed. I've just rebased to resolve a merge conflict. @bozana do you mind doing code review?

**Comment by bozana** [comment] 2017-01-18 16:47
@NateWr, great! Everything works fine now -- the JS is there, also when there are no blocks in the sidebar :-) It can be merged and cherry-picked (if necessary)... :-)

**Comment by NateWr** [comment] 2017-01-19 11:16
Thanks @bozana! All merged. Closing without cherry pick because it seems like an uncommon scenario.

**Closed by NateWr** 2017-01-19 11:16 UTC
Labels: Critical Issue

**Comment by NateWr** [comment] 2017-02-06 12:11
It looks like the CSS for centering content when no sidebar is present didn't get merged:

https://github.com/pkp/ojs/pull/1187

Since it's just CSS, I've gone ahead and cherry-picked in the OJS commit and pushed it straight to master:

https://github.com/pkp/ojs/commit/cbdc00247fa814dd685a8b2a9d58d9a75aea6b0e

Just recording this for the future, as it didn't make it into the 3.0.2 release. But it's just cosmetic so shouldn't be a big deal.
