### ISSUE TITLE
Editorial History shows Download link for certain submission files that journal managers don't have access to download

### ISSUE THREAD

**Issue by nwoodward** [pkp/pkp-lib#6003] opened 2020-06-16 16:32 UTC
**Describe the bug**
When journal managers view the Editorial History of submissions they see a Download link (1) for certain submissions files that they can't actually download. The reason for this seems to be that when the SubmissionFileDAO class calls the getWorkflowStageId() method (2) for submission files with a file stage of SUBMISSION_FILE_ATTACHMENT then the method returns null. And subsequently a stageId isn't added to the Download link, which means that the journal manager sees the message "You have not been assigned to this submission with a role that is allowed to access this operation".  

That message doesn't seem entirely accurate to me, but maybe I'm missing something about the permissions of journal managers. Is there something particular about the SUBMISSION_FILE_ATTACHMENT file stage that should prohibit them from viewing the file? Or could this be an issue for any file uploaded to a submission that doesn't correspond to a specific workflow stage?

1. https://github.com/pkp/pkp-lib/blob/stable-3_1_2/controllers/grid/eventLog/EventLogGridRow.inc.php#L78
2. https://github.com/pkp/pkp-lib/blob/stable-3_1_2/classes/submission/SubmissionFileDAO.inc.php#L752

**To Reproduce**
1. Log in as a journal manager
2. Click on a submission and then view the Editorial History
3. Look for Download links that don't contain a stageId parameter

**What application are you using?**
 OJS 3.1.2.1

**Comment by defstat** [comment] 2020-06-19 12:04
@asmecher 

The https://github.com/pkp/pkp-lib/blob/master/controllers/api/file/FileApiHandler.inc.php seems to manage authorization for 3 different cases:
- Multiple Files
- Library Files
- All other files. 

The last, which is our case, is handled here: https://github.com/pkp/pkp-lib/blob/master/controllers/api/file/FileApiHandler.inc.php#L63 which defines the default policy to be the https://github.com/pkp/pkp-lib/blob/master/classes/security/authorization/SubmissionFileAccessPolicy.inc.php.

Here the `AssignedStageRoleHandlerOperationPolicy` [https://github.com/pkp/pkp-lib/blob/master/classes/security/authorization/AssignedStageRoleHandlerOperationPolicy.inc.php] is declared as one of the policies included, which, in turn, does not allow access if a `worflow stage` is not provided. 

That means that any file that does not correspond to a workflow stage, will not be accessible for downloading from the Activity History at least.

That means that it seems that https://github.com/pkp/pkp-lib/blob/stable-3_1_2/controllers/grid/eventLog/EventLogGridRow.inc.php#L78 should be reached only if the `$workflowStageId` is set. For the cases of `SUBMISSION_FILE_ATTACHMENT` (even though I was unable to produce such file entries in the `submission_files` DB table), the download link is created because of the `|| $submissionFile->getFileStage() != SUBMISSION_FILE_QUERY` part of the condition. 
I wonder if this comment https://github.com/pkp/pkp-lib/blob/stable-3_1_2/controllers/grid/eventLog/EventLogGridRow.inc.php#L75-L76 describes the need of that second condition to be there. If so, I think that it's safe to remove that condition because the comment's case seems to be handled here: https://github.com/pkp/pkp-lib/blob/stable-3_1_2/classes/submission/SubmissionFileDAO.inc.php#L769-L774.

in any case, I propose to **remove the download link for files that don't correspond to a workflow stage**.

There are 4 file stage identifiers that are not defining any workflow stage:
```
define('SUBMISSION_FILE_NOTE', 3);
define('SUBMISSION_FILE_FAIR_COPY', 7);
define('SUBMISSION_FILE_EDITOR', 8);
define('SUBMISSION_FILE_ATTACHMENT', 13);
```

**Comment by NateWr** [comment] 2020-06-30 14:15
> in any case, I propose to remove the download link for files that don't correspond to a workflow stage.

Thanks for looking into it @defstat. So this pertains to files uploaded with queries (discussions)? What other places can a file be uploaded that causes this problem?

If possible I'd like to preserve these links so that editors don't have to go hunting for them. Is it possible for us to detect these files and present a link that does not route through that handler?

It looks like it may be possible in `EventLogGridRow` to use a `LinkAction` along with a `OpenWindowAction` to simply insert a link to the file that would authorize correctly...

**Comment by defstat** [comment] 2020-07-03 05:06
@NateWr it seems that those are the files that are attached to emails send during the review process - I wasn't able to produce one though. I will try the solution you propose.

**Comment by asmecher** [comment] 2020-07-18 00:12
@defstat, this use of `SUBMISSION_FILE_ATTACHMENT` comes from https://github.com/pkp/pkp-lib/issues/2438#issuecomment-455006867.

**Comment by mfelczak** [comment] 2021-03-25 14:53
Hi all, just a note that we may have run into this recently as well, although there is a stage ID present in the generated download URL, e.g. /api/file/file-api/download-file?fileId=1234&revision=1&submissionId=100&stageId=3

The editor is assigned to the submission and has the JM role, but still receives the error message "You have not been assigned to this submission with a role that is allowed to access this operation".

**Comment by NateWr** [comment] 2021-03-29 09:38
@mfelczak what version are you using? The file authorization has changed significantly in 3.3.

**Comment by mfelczak** [comment] 2021-04-06 20:39
@NateWr, this was from an OJS 3.1.2 install and it's entirely possible that this has since been resolved. I did ask for additional details and I'm including the editor's feedback in case it's helpful:

"There is a problem when users, who are assigned to a submission, change role. They seem still to be assigned to the submission with the former role, but possibly do not have the former access rights ... [I]t would be good to prevent this kind of issue somehow "by design" (and there should be a real error message)."

**Comment by NateWr** [comment] 2021-04-07 09:14
@mfelczak I think what your editor describes is a different issue, filed at https://github.com/pkp/pkp-lib/issues/5396.

**Comment by mfelczak** [comment] 2021-04-08 16:35
Thanks @NateWr!

**Comment by defstat** [comment] 2022-06-27 15:16
@asmecher @NateWr @mfelczak 

I checked both `stable_3.3.0` and `main` branches to check for the issue, especially by trying to reproduce it with email attachments to author (Request Revisions) (like I did [here](https://github.com/pkp/pkp-lib/issues/6003#issuecomment-646598813) a while ago - I tried sending ). It seems that in both branches no `Activity Log` for the editor is created regarding those attachments. Also I tried the same for a new discussion, namely I added a new discussion with an attachment. Also `Activity Log` has no trace of that action. 

If an email is send (for example to a reviewer), the email it self is recorded in the `Activity Log`, and the `view email` action displays the email (subject, body, sender, recipients) but not the attachments. So, there is no download action there either. 

In addition, the `file_stage` column of the `submission_files` table seems to be `not nullable` in both the branches. 

At this point, for the two afore-mentioned branches, I can't reproduce the problem with the download button, as no Activity Log is added in the those two cases (and I am not sure how to reproduce other file types that may produce the issue).

**Comment by asmecher** [comment] 2022-06-27 18:24
@nwoodward, I'm aware that this is an older issue that was originally filed in 3.1.x, but have you since upgraded to a newer release of OJS? If so, are you able to confirm whether the issue still appears?

**Comment by asmecher** [comment] 2022-08-26 18:43
Closing -- please follow up if there's still an issue!

**Closed by asmecher** 2022-08-26 18:43 UTC
Labels: Hosting
