### ISSUE TITLE
googleSearch report a lot of slowpages linking to author's search

### ISSUE THREAD

**Issue by marcbria** [pkp/pkp-lib#7183] opened 2021-07-12 17:41 UTC
**Describe the bug**
I'm not able to tell you where, but looks like somewhere in OJS 3.2.1 (stable) the application builds a link to the searcher with a reference to the author as follows:
https://revistes.uab.cat/enrahonar/search/authors/view?firstName=Josep&middleName=M%C2%AA&lastName=Quintana%20Cabanas&affiliation=&country=

This search takes tooo long to be resolved and google Search counts those urls as an error.

The search returns values that, at fist glace, don't make any sense to me.
Do you know where is this referenced? Is this something important to keep?

**To Reproduce**
1. Go to https://revistes.uab.cat/enrahonar/search/authors/view?firstName=Josep&middleName=M%C2%AA&lastName=Quintana%20Cabanas&affiliation=&country=
2. See error (long time to resolve)

**What application are you using?**
 OJS stable-3.2.1 from docker images (packaged last week).

**Additional information**
This is the error 5xx increment that google Search reports after moving from 2.x to 3.x:
![imagen](https://user-images.githubusercontent.com/2779168/125251923-1b235800-e2f8-11eb-81a9-7e44895773c9.png)

The error could be related with this:
https://forum.pkp.sfu.ca/t/ojs-3-0-2-search-filters/30766/14

As a workaround you can remove this path from your robots... even they will be still exposed in your sitemap.
If this feature is not working fine, I would encourage to disable it till it's fixed.

**Comment by asmecher** [comment] 2021-07-12 18:50
@marcbria, I don't actually think `search/authors` does appear in the sitemap. It's sort of in a "twilight" state -- it works (except for performance issues), but isn't linked from anywhere in the interface and needs to be rewritten or removed. See the related issue: https://github.com/pkp/pkp-lib/issues/5449

If you're encountering performance problems with it, I'd recommend excluding it using robots.txt. I'll leave this issue open as I don't think there's an open issue about its future in the longer term.

**Comment by marcbria** [comment] 2021-07-13 10:16
Thanks Alec. 

Two questions about this that are still unanswered:
1. Where were those links created? 
2. What are those searches doing? 

About 1, I look into the article's page and I didn't found them... do you remember who links here?

About 2, I thought it was supposed to return all the articles' related with the author, but with the example I posted is showing much more than this... like making an OR of all user data instead of and AND.

I see it still happens in 3.3, so as said, I would encourage disable those links till we fix the issue.

If you point me in the right direction I think I will be able to do a PR to remove those links.

**Comment by asmecher** [comment] 2021-07-13 16:07
> Where were those links created?

The links haven't been included in OJS 3.x for quite some time (since at least 3.2.0, probably longer), but I think they used to appear in the sidebar as "browse by author" and also as a link on the author's name from the article view. We deprecated it and removed the incoming links in favour of better mechanisms like ORCID years ago, but haven't fully removed that feature.

> What are those searches doing?

Those searches are probably URLs that Google captured a long time ago (when the search area was linked) and is still indexing for lack of a better plan. The searches *should* be "and"ing the provided terms, but it's been a while since this code was maintained properly so it's possible there's been a regression.

**Comment by asmecher** [comment] 2021-07-27 16:28
See also this similar report: https://forum.pkp.sfu.ca/t/ojs-3-1-0-1-search-authors-interface-dead-code/37354

**Comment by asmecher** [comment] 2021-07-27 16:36
Also on the forum: https://forum.pkp.sfu.ca/t/country-is-shown-on-authors-detail-page-only-3-2-1-3/68951/3

I've also pinged the #general slack channel and will see what they have to add (particularly hosting).

**Comment by ajnyga** [comment] 2021-07-28 07:54
I actually removed that index when we upgraded to 3.2 because of the slow queries on the page. It seems that search engines hit the author index a lot. I just added 404s to those handlers.

**Comment by marcbria** [comment] 2021-07-28 15:39
@ajnyga I would like to do the same: Did you patch ojs or you fixed it at apache level?

I think a 404 is better than a very slow page: I feel like this big list of slowpages (error 500 for google) is starting to impact in our SEO (motomo is showing a high decrease of visit after ojs3 migration).

**Comment by ajnyga** [comment] 2021-07-28 15:57
I just edited SearchHandler.inc.php

```
	/**
	 * Show index of published submissions by author.
	 * @param $args array
	 * @param $request PKPRequest
	 */
	function authors($args, $request) {
		error_log("SearchHandler::authors");
		$request->getDispatcher()->handle404();
```
The error log is for checking the amount of hits we are getting to author search.

**Comment by loleary-uic** [comment] 2021-09-21 18:35
@ajnyga Would that be the entire function then?  Just those two lines and a closed bracket?

Thank you,
Lisa

**Comment by jonasraoni** [comment] 2023-02-27 13:59
@asmecher, may I submit a PR to drop this from OJS 3.3.0?
Use case: We've got a reasonably powerful server and a single large journal with around 70K authors was able to slow down everything. Search engines attempt to query very far away pages, which is a performance issue on itself.

**Comment by asmecher** [comment] 2023-02-27 17:08
@jonasraoni, OK, on balance I think that's the least-harm approach.

**Comment by jonasraoni** [comment] 2023-02-28 11:47
@asmecher here are the PRs for `stable-3_3_0` (I didn't find it on OMP). If you think this interface is worth to keep (I didn't see anything linking to it), then we can create an issue to restore it with a reviewed performance/interface.

- https://github.com/pkp/ojs/pull/3801
- https://github.com/pkp/ops/pull/485

**Comment by asmecher** [comment] 2023-02-28 20:52
Merged both, thanks. This would normally be too big a change for a stable build, but those pages are long-deprecated and have been causing harm in the wild.

**Closed by asmecher** 2023-02-28 20:52 UTC
Labels: Housekeeping:1:Todo
