### ISSUE TITLE
[OJS 3.3.0.3] Slow queries on the user management page

### ISSUE THREAD

**Issue by luizbgomide** [pkp/pkp-lib#6991] opened 2021-04-23 19:04 UTC
The user list/search page `/management/settings/access#users` is very slow on my system. Inside OJS this pages it takes around 7-8 minutes to search for "luiz" in all journals. Outside OJS, running the SQL query below in phpMyAdmin it takes around 80-90 seconds, which also feels slow.

This have been slow since I first migrated to OJS 3.X at version 3.2.1.1 last year, previously at 2.4.8.5 it was very fast. I thought it could be the new system, but I'm thinking that there must be another issue at play here.
My users table has 27806 entries, it is MySQL 8.0.23 with InnoDB tables and encoding utf8_general_ci.

SQL query extract from apache error log after toggling debub on:
```
SELECT DISTINCT u.*,
				COALESCE(ugl.setting_value, ugpl.setting_value) AS user_given,
			CASE WHEN ugl.setting_value <> '' THEN ufl.setting_value ELSE ufpl.setting_value END AS user_family
			FROM	users AS u
				LEFT JOIN user_settings us ON (us.user_id = u.user_id AND us.setting_name = 'affiliation')
				LEFT JOIN user_interests ui ON (u.user_id = ui.user_id)
				LEFT JOIN controlled_vocab_entry_settings cves ON (ui.controlled_vocab_entry_id = cves.controlled_vocab_entry_id)
				LEFT JOIN user_user_groups uug ON (uug.user_id = u.user_id)
				LEFT JOIN user_groups ug ON (ug.user_group_id = uug.user_group_id)
				LEFT JOIN user_settings ugl ON (u.user_id = ugl.user_id AND ugl.setting_name = "givenName" AND ugl.locale = "pt_BR")
			LEFT JOIN user_settings ugpl ON (u.user_id = ugpl.user_id AND ugpl.setting_name = "givenName" AND ugpl.locale = "pt_BR")
			LEFT JOIN user_settings ufl ON (u.user_id = ufl.user_id AND ufl.setting_name = "familyName" AND ufl.locale = "pt_BR")
			LEFT JOIN user_settings ufpl ON (u.user_id = ufpl.user_id AND ufpl.setting_name = "familyName" AND ufpl.locale = "pt_BR")
				LEFT JOIN user_settings usgs ON (usgs.user_id = u.user_id AND usgs.setting_name = "givenName")
				LEFT JOIN user_settings usfs ON (usfs.user_id = u.user_id AND usfs.setting_name = "familyName")

			WHERE	1=1  AND (   ( LOWER(CONCAT(COALESCE(usgs.setting_value,''),COALESCE(usfs.setting_value,''),u.email,COALESCE(us.setting_value,''))) LIKE "%luiz%" OR LOWER(cves.setting_value) LIKE "%luiz%" )   ) ORDER BY user_family, user_given LIMIT 25 OFFSET 0
```

**Comment by asmecher** [comment] 2021-04-23 19:24
@luizbgomide, if you're able to (privately!) share a database dump, it'll save me some time in figuring out an environment that replicates the problem. Feel free to anonymize any details you like, as long as the issue is still easy to replicate.

**Comment by luizbgomide** [comment] 2021-04-26 11:25
@asmecher, sent to your e-mail, let me know if you find anything odd with it.
Thanks in advance.

**Comment by NateWr** [comment] 2021-04-26 11:44
@luizbgomide I'd also like to know if you see the same slow performance (or worse) when using the REST API. You can see [how to access the API](https://docs.pkp.sfu.ca/dev/api/) and then see the specifications for the [user endpoint](https://docs.pkp.sfu.ca/dev/api/ojs/3.3#tag/Users/paths/~1users/get). You'd use the `searchPhrase` query param to search for a user.

This will help us find and fix performance problems before we switch the user list in the UI over to the API.

**Comment by luizbgomide** [comment] 2021-04-26 11:56
@NateWr, what parameters do you want me to use?

Just running this: `https://periodicos.fclar.unesp.br/iberoamericana/api/v1/users` is 2 seconds max to output 20 users. For comparison just opening this page `https://periodicos.fclar.unesp.br/iberoamericana/management/settings/access` that also lists 20 users (different ones, so there is sorting involved) it took 68 seconds.

Is there a way to use the REST API to search all users? That would be a good comparison, considering this takes 7-8 minutes to do that in the UI.

**Comment by NateWr** [comment] 2021-04-26 12:58
@luizbgomide try `https://periodicos.fclar.unesp.br/iberoamericana/api/v1/users?searchPhrase=luiz` to compare searching against that phrase.

**Comment by NateWr** [comment] 2021-04-26 14:08
> Is there a way to search side-wide in all journals via the REST API?

Not at the moment, no. The REST API does not support returning users with no role in the context, and this is a blocker for the new users list until we can support a feature to invite a user to adopt a role. See more in [this comment](https://github.com/pkp/pkp-lib/issues/2860#issuecomment-388906925).

**Comment by luizbgomide** [comment] 2021-04-29 11:51
> @luizbgomide, if you're able to (privately!) share a database dump, it'll save me some time in figuring out an environment that replicates the problem. Feel free to anonymize any details you like, as long as the issue is still easy to replicate.

Hello @asmecher, did you receive the data I've sent you via e-mail? Any ideas on what is making it slow? I have some follow-up information after a few tests, Load time of the user page in english and portuguese, and Search time for "luiz" in both languages, in a two journals with a default Items per page of 100 users.

Large Journal (iberoamericana)
- Load time EN: 65 seconds for 10362 users
- Load time PT: 100 seconds for 10372 users
- Search time EN: 55 seconds for 120 users
- Search time PT: 75 seconds for 120 users

Smaller Journal (itinerarios)
- Load time EN: 20 seconds for 1718 users
- Load time PT: 27 seconds for 1725 users
- Search time EN: 18 seconds for 32 users
- Search time PT: 23 seconds for 32 users

So there is an overhead due to the language, and it is proportional to the number of users found. A new oddity is that I got a different number of users listed in both journals! I have more users found in the PT interface than in EN. What could have caused that?

**Comment by luizbgomide** [comment] 2021-04-29 13:51
I had 5000 fake users removed from my base and now the there is a total of 22297 users.

I made a lot of load time tests in many of our journals:
- The "Items per page" doesn't change the time it takes to load the users, be it 10 or 100 items.
- Every time you click on a page number or Next it takes the whole time list it again 

Regarding the loading times:
- 5 seconds in a journal with ~100 users;
- 4 seconds in a journal with ~200 users;
- 6 seconds in a journal with ~300 users;
- 7-10 seconds in a journal with ~1 200 users;
- 15-20 seconds in a journal with ~600 users; !!!
- 15-20 seconds in a journal with ~1 000 users;
- 15-20 seconds in a journal with ~2 600 users;
- 25-30 seconds in a journal with ~400 users; !!!
- 25-30 seconds in a journal with ~600 users; !!!
- 25-30 seconds in a journal with ~900 users; !!!
- 25-30 seconds in a journal with ~1 700 users;
- 30-35 seconds in a journal with ~400 users; !!!
- 35-40 seconds in a journal with ~2 900 users;
- 35-40 seconds in a journal with ~4 000 users;
- 45-50 seconds in a journal with ~7 000 users;
- 55-60 seconds in a journal with ~1 500 users; !!!
- 90-100 seconds in a journal with ~10 300 users;
- 6m30s-6m40s in to list all 22 297 users (using "Include users without roles in this journal").
 
I did the tests a few times in each journal (each line is a differente journal).
The increase in time is not linear, also, some journals took a lot longer than other with a similar user count, and some were very fast compared to what I was expecting, I have no idea why. 
Either in the Users & Roles page, or in the Administration -> Hosted Journals -> Users, the times were very similar, but using the Journal Users page was a few seconds faster than using the admin page.

**Comment by asmecher** [comment] 2021-04-30 16:24
Hi @luizbgomide -- just getting a chance to look at the database now.

**Comment by luizbgomide** [comment] 2021-04-30 20:12
Hello @asmecher,
I'm using phpMyAdmin to connect to the server which is running MySQL 8.0.23 protocol version: 10 (I don't know what other information I can gather from there). I just ran the same query as you, this is the result:
![image](https://user-images.githubusercontent.com/18707781/116747636-94d3c700-a9d4-11eb-9fd0-b20d7a3e9dce.png)

Later, running the same query I got:
![image](https://user-images.githubusercontent.com/18707781/116748091-4672f800-a9d5-11eb-96eb-cf6b5201a219.png)

Also, it is worth mentioning that my userbase is about 17% smaller than the one I gave to you, since I removed a lot of fake users this week.

I'm not sure if there is some caching involved, but I got the same result even changing the search string.

I put EXPLAIN in front of the query (is that what you meant?) and got this (sorry for the image, I couldn't get a useful text output):
![image](https://user-images.githubusercontent.com/18707781/116749078-cc437300-a9d6-11eb-8185-bff6b79c309b.png)

I think our results are similar. How is the loading time in the user interface for `iberoamericana/management/settings/access#users`

**Comment by luizbgomide** [comment] 2021-04-30 20:31
Here is the Chrome profile of the user page loading for `iberoamericana/management/settings/access#users` and then searching for "luiz":
![image](https://user-images.githubusercontent.com/18707781/116750259-8daeb800-a9d8-11eb-9046-99d6683ccb0c.png)

I'm one hop away from the server, so there is no lag or download speed issues (the same is true for the server and the database).

And here is search using "Include users with no roles in this journal." which is terribly slow and effectively unusable for me.
![image](https://user-images.githubusercontent.com/18707781/116751036-d024c480-a9d9-11eb-8f77-34fdd2e98c1b.png)

**Comment by luizbgomide** [comment] 2021-05-10 14:38
A few more tests on a secondary DB server with a temporary 3.3.0-3 install (to be the same version as I have in production), these are the results:
Green: load time for the user page.
Blue: searching for "luiz" in the current journal
Red: searching for "josé" in all journals
![image](https://user-images.githubusercontent.com/18707781/117661460-c9821400-b174-11eb-9f39-6c983a78f108.png)

The load times are MUCH faster in the test server, the search in the current journal is somewhat faster but had similar results and the search in all journals is ever worse than in the production server.

Everything is the same except for the DB servers, the test server is running MySQL 5.7.27-log and is on MySQL 8.0.23, both with InnoDB tables, the only difference between them is that the production server has GTID enabled.

@asmecher, any ideas? This problem is really hard to work around since there is no other way of searching and manipulating user information/settings.

**Comment by jnugent** [comment] 2021-06-22 16:21
Hi everyone,  just wanted to jump on this issue too.  We've got a client with a reasonably large installation (8 thousand users) and running a search in the User grid in the interface takes about 8 to 9 minutes, total.  With ~57 thousand entries in the user_settings table and a sufficiently large CVES table, the "rows examined" when running this search query exceeds 100 million rows.  At first the entire operation was hitting the polling timeout limit in Apache, bumping that from two minutes to ten minutes is enough to get it to go to completion.  

This installation is running 3.3.0.6

Some screens:

![Screenshot at 2021-06-22 11-14-09](https://user-images.githubusercontent.com/218719/122962411-c8d7c280-d35b-11eb-8fa1-aae6f00158c2.png)

![Screenshot at 2021-06-22 11-12-16](https://user-images.githubusercontent.com/218719/122962471-d4c38480-d35b-11eb-9f59-e7423dfa0f38.png)

The weird thing is that running the query @asmecher  (and myself, after dumping it to a log) directly in PHPMyAdmin causes it to return in about 90 seconds or so.  It does run more than once during the grid search due to count totals, but that's still much faster.  

I don't really know enough about the UI library to know if there's a latency here due to something rendering on the client?

I also noticed that in UserGroupDAO, the _getSearchSql method that ultimately builds a big piece of the query still seems to have some legacy code that I believe at one point was used to limit the search to specific fields, the $searchTypeMap array right inside the method.  Is it worth bringing any of that back? 

Oh, and this is a decently large server.  I think we have 32 Gb of RAM allocated just for MySQL. 

Cheers,
Jason

**Comment by jnugent** [comment] 2021-06-22 18:44
Just another update.  I modified the search query and removed the join across the user interests and the cves.setting_value search and our grid refresh time dropped from nearly 9 minutes to a minute and a half:

![Screenshot at 2021-06-22 15-41-55](https://user-images.githubusercontent.com/218719/122981936-ab612380-d370-11eb-8b36-bda1da96204a.png)

I was also watching the queries via "show processlist" while the search was running and the search query runs four times in total in order to reload the grid with results.

**Comment by luizbgomide** [comment] 2021-06-22 19:04
I honestly have no idea how the User search is so slow. We have more articles than users and the search is absurdly faster, and even in the assign reviewer window the search is very fast and it is essentially doing something very similar to the User search function.

**Comment by jnugent** [comment] 2021-06-25 13:07
I was doing some more testing today, and comparing two 3.3.0.6 installations.  The first is the one I've mentioned above, with ~8000 users, and the second is an also large installation, submission-wise, but with only 5800 users.   As I mentioned, the search takes nearly 9 minutes to run in the larger installation, but only a minute and 40 seconds in the second.  The big difference between the two is the 8000 user installation has more reviewers with entries in the user_interests table, 12 thousand versus 4 thousand, and 37 thousand versus 29 thousand in the CVES table. 

These two installations are on the same server and the testing time of day was the same so performance conditions were identical.

**Comment by luizbgomide** [comment] 2021-06-25 14:05
@jnugent that might have something to it. I have 16 thousand unique `user_id`  in the `user_interests` (33 thousand total entries), my `controlled_vocab_entries` table has 115 thousand entries.

**Comment by NateWr** [comment] 2021-06-28 10:38
Just a couple of clarifications: the user grid does not use the UI library so there shouldn't be any specific client-related delay here.

@jnugent can you try hitting the REST API for these installs to see what the time is like? This would be the request.

```
GET /<journal-path>/api/v1/users/?searchPhrase=<search>&apiToken=<apiToken>
```

The easiest solution here may be to simply move the grid over to using the user service to perform the search. That's what searches in the REST API. It can be difficult to rejig the grids, but Alec is working on that entity right now so may be able to roll that in without too much hassle.

**Comment by jnugent** [comment] 2021-06-28 17:24
Hi @NateWr  With the smaller installation (the one that had a complete grid reload in 1.56 minutes), using the API returned a result set in 16 seconds.  The larger site returned an API call in 40 seconds.  Those are averages of three calls, each.

**Comment by NateWr** [comment] 2021-06-29 09:37
Thanks @jnugent. That's better, but still not good enough!

**Comment by OGouda** [comment] 2021-07-09 13:53
Hi,
I had the same exact problem until recently I noticed there are some duplication in the Reviewer Report. I traced the problem to the `user_settings` table in the database. I found around 10,000 duplicated entries there. The settings were there once with the `assoc_type` and `assoc_id` have the value 0, while the old/not updated settings have them as null. 

To solve this problem I have done the following:

1. Identify all the new/updated entries in the table 
`SELECT distinct user_id FROM ojs2.user_settings where assoc_id = 0;`

2. Delete the entries with null in the mentioned columns 
`SELECT * FROM ojs2.user_settings where user_id in ( **IDs from the last query**)
AND assoc_id is NULL;`

3. Update all the other entries to avoid repeating this problem in the future (2 Steps)
`Update ojs2.user_settings Set assoc_id = 0 where user_id not in ( **IDs from the last query**)
AND assoc_id is NULL;`
`Update ojs2.user_settings Set assoc_type= 0 where user_id not in ( **IDs from the last query**)
AND assoc_type is NULL;`

The UI grid used to take around 1 min to load but now it takes 11 secs.

I hope this helps.

**Comment by luizbgomide** [comment] 2021-07-09 14:25
@OGouda I have another issue somewhat related to that too #7146 and refactored into #7167. But I suspect your query could be deleting more information that you actually want too. Just checking for `assoc_id = 0` is enough to insure that the `NULL` are overwritten?

**Comment by OGouda** [comment] 2021-07-09 15:09
@luizbgomide We have a small database of around 2800 users. I went through them before executing the queries. The only difference between the old and new duplicates were the `assoc_id` and `assoc_type`  from `null` becoming 0. if you want to add another condition like `AND assoc_type = 0` but from what I have observed both are always 0 or `null`.

and for step 3, I am aware of `assoc_type = 256` referring to the profile image of the user but I did not change the  type value in the queries only the `assoc_id`.
You can try the queries out on a copy of the database and OJS on another machine to make sure it works for you. I know what works for me may not work for everyone. but if there are any problems please let me know here so I can learn and update the answer.

**Comment by retostauffer** [comment] 2021-09-02 10:42
I was trying to track down the long loading times on the user search/user list. We are running `OJS 3.3.0-7` with about `130.000` registered users. The loading time for the user-list or one search request is around **1 minute 15 seconds** in our case. I have not had time to dig into the php code yet, but here some findings (if not well known already).

#### DB log

I've sent one user search request, logged all requests to the DB, and extracted the 'main' queries to the `users` table. Seems there are 5 requests. Each query takes about **15 seconds** which results in the overall time of **1 minute 15 seconds** .

* Statement 1: Loads the users given the table limit set (`SELECT DISTINCT u.* .... LIMIT 25 OFFSET 0`)
* Statement 2: Counts total number of entries (`SELECT COUNT(*) AS row_count ....`)
* **Statement 3-5**: Seem to be _identical_ to Statement 1

I understand Statement 1+2 but 3, 4, and 5 seem to be unnecessary and take up 3/5th of the overall query time.

**Test script:** Here is my [usersearch_test.txt](https://github.com/pkp/pkp-lib/files/7098205/usersearch_test.txt) script used which is actually a bash/shell script (`.txt` to be able to attach it here) containing the queries.

#### Technical details

* OJS `3.3.0-7`
* DB: `mysql  Ver 15.1`;  `Distrib 10.3.28-MariaDB`
* PHP `7.4.22`

**Comment by alexxxmendonca** [comment] 2021-09-02 11:40
I would just like to weight in to say that we have the same problem in SciELO's OJS when doing any search across the whole system and during merging of users.

I don't know how many users we have, but I know it's a lot. We've been using OJS since 2007 with over 100 journals (41 currently active).

**Comment by asmecher** [comment] 2021-09-02 16:05
Hi all -- we have substantial rewrites to this code already in place for the 3.4 release (see https://github.com/pkp/pkp-lib/issues/7127). The changes remove the `DISTINCT` (this is probably the biggest performance problem) and change any conditionals the query might require for far-flung cases so that they are only brought in when needed.

Unfortunately the side-effect of this being a comprehensive rewrite is that it can't be directly back-ported to earlier releases.

I would recommend planning to work around the bottleneck until 3.4 is be released -- and please consider participating in community testing for that release, as it'll help us ensure it's as stable as possible! Currently it's looking like 3.4 will come out in the first quarter of 2022.

**Comment by retostauffer** [comment] 2021-09-02 16:08
Good news, thank you very much @asmecher !

We can work with the current version, no real need for back-porting (may be some good tee to click-and-wait), but nice to hear that it will be addressed in a future release.

We are currently trying to go live with `3.3.0-7`, and will try to find time to test `3.4.x` next spring if possible!

**Comment by jonasraoni** [comment] 2021-10-31 18:08
@asmecher I had to solve an incident today, so here goes the PR to address this issue (in case it's enough to fix just the user search at `/management/settings/access` route):

[pkp-lib](https://github.com/pkp/pkp-lib/pull/7414)
[OJS => tests](https://github.com/pkp/ojs/pull/3213)

**Comment by jonasraoni** [comment] 2021-11-06 11:44
Added PRs for /main as it's using basically the same code:
pkp-lib: https://github.com/pkp/pkp-lib/pull/7437
OJS: https://github.com/pkp/ojs/pull/3220

**Comment by asmecher** [comment] 2021-11-10 00:58
Thanks, @jonasraoni -- I've merged for both `stable-3_3_0` and `main`.

**Closed by asmecher** 2021-11-10 00:58 UTC
Labels: Dev Housekeeping

**Comment by luizbgomide** [comment] 2021-11-10 12:40
@asmecher it is worth noting that (from what I understood) this also relies on the `user_settings` entries being unique. So if that is applied to a user that migrated from 2.X they would probably have the odd NULL values there (see https://github.com/pkp/pkp-lib/pull/7414#issuecomment-961857377). The performance is still much better, but the results seems to be quirky.

**Comment by retostauffer** [comment] 2021-11-10 13:31
Just to confirm: loading times for "Users & Roles" dropped from ~80secs down to 2secs (initial page view) and to about 20 seconds for user search (138.000 registered users).

Latest 3.4 development version (commit `050b74953249d3bed7f54369a88062aa919c8502`; main branch).

**Comment by jonasraoni** [comment] 2021-11-10 19:46
@luizbgomide After my latest modifications, the code is supposed to work without removing the duplicated entries, it will just be slower =]

@retostauffer If you're handy with SQL, you might check if you're affected by duplicated user_settings (https://github.com/pkp/pkp-lib/pull/7414#issuecomment-961857377), after fixing that, the performance should receive another bump.

Also, it's still possible to improve the searching performance in general, but there are other issues opened for that.

**Comment by retostauffer** [comment] 2021-11-11 09:54
@jonasraoni I have tested your fix of duplicated settings. We are affected (https://github.com/pkp/pkp-lib/issues/4900) but not a lot. Applying your patch reduces the number of rows in our `user_settings` table by only 0.5%, thus - in our case - an improvement of the performance is not visible. But still good to get these `NULL` duplicates out of the DB.

**Comment by mdagostino1212** [comment] 2021-11-17 14:49
Hi @jonasraoni! I am trying to apply your patch but I am having problems. I 've changed the file located in lib/pkp/classes/security/UserGroupDAO.inc.php but it has a different structure that the one you add. When I change the code I got errors. Is this a different implementation of OJS? I am using OJS 3.3.0-6. Thanks in advance

**Comment by jonasraoni** [comment] 2021-11-17 17:19
Hi @mdagostino1212!

It's a bit risky to update a single file as it might depend on other modifications, you'd better follow the [documentation](https://docs.pkp.sfu.ca/dev/upgrade-guide/en/), looks like the latest tag is `3_3_0-8`.

If you still seeing errors after upgrading it properly, then share with us the error message.
