### ISSUE TITLE
New journal settings wizard displays untranslated key ##manager.masthead.title##

### ISSUE THREAD

**Issue by mfelczak** [pkp/pkp-lib#3514] opened 2018-03-23 16:31 UTC
In OJS 3.1.0-1, in the journal settings wizard displayed after a new journal is created.

Masthead tab => Masthead setting title

**Comment by asmecher** [comment] 2018-03-23 16:34
Dupe of e.g. https://github.com/pkp/pkp-lib/issues/3225

**Closed by asmecher** 2018-03-23 16:34 UTC
