### ISSUE TITLE
OAI-PMH does not respect URLencoded identifiers as parameters

### ISSUE THREAD

**Issue by ctgraham** [pkp/pkp-lib#3053] opened 2017-11-13 16:53 UTC
Reported: https://forum.pkp.sfu.ca/t/failed-to-register-database-at-oai/35252

To reproduce, follow a normal OAI-PMH path, but replace an `identifier` parameter with a URLencoded version of the parameter.

The verb "ListMetadataFormats" returns:  `Error Code | idDoesNotExist | No matching identifier in this repository`.

The verb "GetRecord" returns: `Error Code | badArgument | Identifier is not in a valid format`.

**Comment by bozana** [comment] 2017-11-13 23:28
@ctgraham, I believe this is a duplicate of this issue: https://github.com/pkp/pkp-lib/issues/3052, correct?

**Closed** 2017-11-14 00:03 UTC

**Comment by ctgraham** [comment] 2017-11-14 13:05
Yes, it is.  Good catch.
