### ISSUE TITLE
Provide submission/book DOI/URN via OMP OAI

### ISSUE THREAD

**Issue by bozana** [pkp/pkp-lib#9877] opened 2024-04-11 13:12 UTC
In OMP an OAI record is per publication format. We only consider publication format DOIs there. However, mostly users will assign the DOIs to submissions and not to publication formats (this is also what we recommend for Crossref export). We also provide the submission/book view URL.
Thus, consider submission/book DOIs in OMP OAI record if there is no publication format DOI found.

s. https://forum.pkp.sfu.ca/t/omp-doi-missing-in-oai-dc/14778/19

PRs:
~~stable-3_3_0: https://github.com/pkp/omp/pull/1618~~
~~stable-3_4_0: https://github.com/pkp/omp/pull/1619~~
~~main: https://github.com/pkp/omp/pull/1620~~

- main: https://github.com/pkp/omp/pull/1629, https://github.com/pkp/omp/pull/1637
- stable-3_4_0: https://github.com/pkp/omp/pull/1636
- stabl-3_3_0: https://github.com/pkp/omp/pull/1638

**Comment by asmecher** [comment] 2024-07-12 22:42
@bozana / @ewhanson, I've just noticed that this is a duplicate of [this forum thread](https://forum.pkp.sfu.ca/t/missing-doi-in-oai-export-omp-3-4-0-5/89063/3) and [the linked PR](https://github.com/pkp/omp/pull/1629), which is merged. I do think that just adding the book identifier to the record risks breaking the spec, as it's not guaranteed to be a unique identifier, so I favour the approach in the linked thread. What do you two think?

**Comment by bozana** [comment] 2024-07-15 11:22
Yes, I think we can leave it as dc:relation.
(Just a note: Crossref for example only suggests to have DOIs on book and chapter level, so once we implement Crossref deposit in OMP, it will only be possible to assign DOIs to book and chapters (if using Crossref). -- Similar to article and galley in OJS.).

**Comment by bozana** [comment] 2024-07-15 11:23
Maybe we can just back port it to stable-3_4_0 and stable-3_3_0?

**Comment by bozana** [comment] 2024-07-15 14:03
I have backported it to stable-3_4_0 and stable-3_3_0 and considered URN i.e. other pubIds in the same way... When the tests pass I will merge...

**Closed** 2024-07-15 15:02 UTC
Labels: Enhancement:1:Minor
