### ISSUE TITLE
OJS update 3.3.0.14 to 3.4.0.0 Orc3

### ISSUE THREAD

**Issue by Mathewwss** [pkp/pkp-lib#9003] opened 2023-05-16 17:41 UTC
I'm trying to upgrade OJS 3.3.0.14 to 3.4.0.0 0rc3.

When executing the update, with the command 'php tools/upgrade.php upgrade',
I had some bank related issues. To solve I modified
some tables.

After the changes, during the update there was no more error related to the
database.

The last error was this:

![16 May 2023_02 35 48](https://github.com/pkp/pkp-lib/assets/50458770/8f64c5c8-f0c0-4754-a2d5-da819cccd405)

Solution ??

**Comment by jonasraoni** [comment] 2023-05-16 18:10
@Mathewwss I'm closing as a duplicate of https://github.com/pkp/pkp-lib/issues/8929, some solutions are already present there, others will be released soon.

**Closed by jonasraoni** 2023-05-16 18:10 UTC
