### ISSUE TITLE
AuthorDAO::getPublishedArticlesForAuthor fails when executed from author search index

### ISSUE THREAD

**Issue by Vitaliy-1** [pkp/pkp-lib#5442] opened 2020-01-27 16:13 UTC
OJS 3.1.2-4
When trying to view author details from the search author index page, I'm receiving MySQL error, e.g.:
```
DB Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(asg3.setting_value = 'Rostislav' AND asf3.setting_value = 'Abdryakhimov' AND as' at line 22
```
Also, when trying to browse the authors' list from a certain letter, there is another error:
```
DB Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LOWER(asf3.setting_value) LIKE LOWER('l%')) GROUP BY names ) as t1 ON (' at line 52
```  
Works fine on my test OJS instance v. 3.1.2-1: http://dev-ojs.e-medjournal.com/index.php/sjt/search/authors

**Comment by asmecher** [comment] 2020-01-27 16:51
@Vitaliy-1, what respective versions of MySQL/MariaDB are you using on your two servers?

**Comment by Vitaliy-1** [comment] 2020-01-27 16:56
mysqld  Ver 5.7.28-0ubuntu0.18.04.4 for Linux on x86_64 ((Ubuntu))
mysql  Ver 14.14 Distrib 5.7.28, for Linux (x86_64) using  EditLine wrapper

For another server with OJS 3.1.2-1, the version is the same but for Ubuntu 16.

**Comment by asmecher** [comment] 2020-01-27 17:45
@Vitaliy-1, can you try using the `debug` `config.inc.php` feature to extract the entire SQL statement?

**Comment by Vitaliy-1** [comment] 2020-01-28 10:21
For the first one:
```
ADOConnection._Execute(SELECT DISTINCT a.submission_id FROM	authors a LEFT JOIN submissions s ON (s.submission_id = a.submission_id) ...) % line 1032, file: adodb.inc.php
ADOConnection.Execute(SELECT DISTINCT a.submission_id FROM	authors a LEFT JOIN submissions s ON (s.submission_id = a.submission_id) ..., Array[1]) % line  100, file: DAO.inc.php
DAO.retrieve(SELECT DISTINCT a.submission_id FROM	authors a LEFT JOIN submissions s ON (s.submission_id = a.submission_id) ..., Array[11]) % line  100, file: AuthorDAO.inc.php
AuthorDAO.getPublishedArticlesForAuthor(1, Rostislav, Abdryakhimov, Eye Microsurgery Center, Kyiv, Ukraine, UA) % line  205, file: SearchHandler.inc.php
SearchHandler.authors(Array[1], Object:Request) % line  390, file: PKPRouter.inc.php
```
For the second:
```
ADOConnection._Execute(SELECT COUNT(*) FROM (SELECT a.*, ug.show_title, s.locale, COALESCE(agl.setting_value, agpl.setting_value) AS author_given, ...) % line 1032, file: adodb.inc.php
ADOConnection.Execute(SELECT COUNT(*) FROM (SELECT a.*, ug.show_title, s.locale, COALESCE(agl.setting_value, agpl.setting_value) AS author_given, ..., Array[1]) % line  153, file: adodb-mysqli.inc.php
ADODB_mysqli.GetOne(SELECT COUNT(*) FROM (SELECT a.*, ug.show_title, s.locale, 	COALESCE(agl.setting_value, agpl.setting_value) AS author_given, ..., Array[10]) % line  440, file: adodb-lib.inc.php
_adodb_getcount(Object:ADODB_mysqli, SELECT a.*, ug.show_title, s.locale, COALESCE(agl.setting_value, agpl.setting_value) AS author_given, 	CASE WHEN agl.setti..., Array[10], 0) % line  505, file: adodb-lib.inc.php
_adodb_pageexecute_all_rows(Object:ADODB_mysqli, SELECT a.*, ug.show_title, s.locale, COALESCE(agl.setting_value, agpl.setting_value) AS author_given, 	CASE WHEN agl.setti..., 40, 1, Array[10], 0) % line 2744, file: adodb.inc.php
```
```
ADOConnection._Execute(SELECT a.*, ug.show_title, s.locale, COALESCE(agl.setting_value, agpl.setting_value) AS author_given, CASE WHEN agl.setti...) % line 1032, file: adodb.inc.php
ADOConnection.Execute(SELECT a.*, ug.show_title, s.locale, COALESCE(agl.setting_value, agpl.setting_value) AS author_given, CASE WHEN agl.setti..., Array[1]) % line  458, file: adodb-lib.inc.php
_adodb_getcount(Object:ADODB_mysqli, SELECT a.*, ug.show_title, s.locale, COALESCE(agl.setting_value, agpl.setting_value) AS author_given, 	CASE WHEN agl.setti..., Array[10], 0) % line  505, file: adodb-lib.inc.php
_adodb_pageexecute_all_rows(Object:ADODB_mysqli, SELECT a.*, ug.show_title, s.locale, COALESCE(agl.setting_value, agpl.setting_value) AS author_given, 	CASE WHEN agl.setti..., 40, 1, Array[10], 0) % line 2744, file: adodb.inc.php
ADOConnection.PageExecute(SELECT a.*, ug.show_title, s.locale, 	COALESCE(agl.setting_value, agpl.setting_value) AS author_given, CASE WHEN agl.setti..., 40, 1, Array[10]) % line  191, file: DAO.inc.php
```

**Comment by Vitaliy-1** [comment] 2020-01-28 10:32
Looks like it's truncated. Here's full:
```
Query: SELECT DISTINCT
				a.submission_id
			FROM	authors a
				LEFT JOIN submissions s ON (s.submission_id = a.submission_id)
				
				LEFT JOIN author_settings asg1 ON (asg1.author_id  = a.author_id AND asg1.setting_name = 'givenName' AND asg1.locale = 'en_US')
				LEFT JOIN author_settings asf1 ON (asf1.author_id  = a.author_id AND asf1.setting_name = 'familyName' AND asf1.locale = 'en_US')
			
					LEFT JOIN author_settings asa1 ON (asa1.author_id  = a.author_id AND asa1.setting_name = 'affiliation' AND asa1.locale = 'en_US')
				
				LEFT JOIN author_settings asg2 ON (asg2.author_id  = a.author_id AND asg2.setting_name = 'givenName' AND asg2.locale = 'uk_UA')
				LEFT JOIN author_settings asf2 ON (asf2.author_id  = a.author_id AND asf2.setting_name = 'familyName' AND asf2.locale = 'uk_UA')
			
					LEFT JOIN author_settings asa2 ON (asa2.author_id  = a.author_id AND asa2.setting_name = 'affiliation' AND asa2.locale = 'uk_UA')
				
				LEFT JOIN author_settings asg3 ON (asg3.author_id  = a.author_id AND asg3.setting_name = 'givenName' AND asg3.locale = 'ar_IQ')
				LEFT JOIN author_settings asf3 ON (asf3.author_id  = a.author_id AND asf3.setting_name = 'familyName' AND asf3.locale = 'ar_IQ')
			
					LEFT JOIN author_settings asa3 ON (asa3.author_id  = a.author_id AND asa3.setting_name = 'affiliation' AND asa3.locale = 'ar_IQ')
				
				WHERE s.status = 3 AND
				((asg1.setting_value = 'Rostislav' AND asf1.setting_value = 'Abdryakhimov' AND asa1.setting_value = 'Eye Microsurgery Center, Kyiv, Ukraine') OR (asg2.setting_value = 'Rostislav' AND asf2.setting_value = 'Abdryakhimov' AND asa2.setting_value = 'Eye Microsurgery Center, Kyiv, Ukraine')(asg3.setting_value = 'Rostislav' AND asf3.setting_value = 'Abdryakhimov' AND asa3.setting_value = 'Eye Microsurgery Center, Kyiv, Ukraine')) AND a.country = 'UA' AND s.context_id = 1 failed. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(asg3.setting_value = 'Rostislav' AND asf3.setting_value = 'Abdryakhimov' AND as' at line 22
```
Would it be helpful a full query for the second error?

**Comment by Vitaliy-1** [comment] 2020-01-28 10:39
@asmecher, my capabilities in debugging SQL are limited but if remove (not simply deactivate) ar_IQ language, the problem disappears.

**Comment by Vitaliy-1** [comment] 2020-01-28 11:05
My bad, deactivating all languages except primary (English) is enough. Those authors have names specified only for English locale, thus, I think there should be some check in the statement for that.

**Comment by asmecher** [comment] 2020-01-28 16:58
@Vitaliy-1, what does your `supportedLocales` journal setting look like?

**Comment by Vitaliy-1** [comment] 2020-01-29 17:16
@asmecher,
```
SELECT * FROM `journal_settings` WHERE `setting_name`='supportedLocales' AND `journal_id`='1'
1		supportedLocales	a:2:{i:1;s:5:"en_US";i:2;s:5:"uk_UA";}	object	
	
```
I've deleted `ar_IQ` language when tested. If deactivate Ukrainian, the problem resolves.

**Comment by asmecher** [comment] 2020-01-29 22:52
@Vitaliy-1, can you try the attached patch and let me know if it works? I think the problem is that your locales array isn't 0-based for whatever reason, and the `AuthorDAO` code intermixes indexes and counts.

[5442.diff.txt](https://github.com/pkp/pkp-lib/files/4131213/5442.diff.txt)

**Comment by Vitaliy-1** [comment] 2020-01-30 17:12
This is weird, the starting index is different between versions:

version | supportedFormLocales | supportedLocales | supportedSubmissionLocales
3.1.1-1 | 0 | 0 | 0
3.1.1-4 | 0 | 1 | 0
3.1.2-0 | 0 | 1 | 0
3.1.2-1 | 1 | 1 | 1

In all those versions I've experimented with adding/removing locales, including the Arabic language for testing styling for rtl scripts. By googling I can find another journal that uses this language and has the same issue. Production OJS instance of our university's journal, which uses English and Ukrainian from the start isn't affected.

Yes, this patch resolves the problem. The second problem that I've mentioned remains. Would it be helpful if I post a full SQL statement for it?

**Comment by asmecher** [comment] 2020-01-30 17:36
Thanks, @Vitaliy-1, I've committed that patch to both `stable-3_1_2` and `master`.

Yes, please do post a full query for the second problem!

**Comment by Vitaliy-1** [comment] 2020-01-31 09:38
Another database error associated with this page occurs when clicking a link to search by initial:
```
Query: SELECT a.*, ug.show_title, s.locale,
				COALESCE(agl.setting_value, agpl.setting_value) AS author_given,
			CASE WHEN agl.setting_value  '' THEN afl.setting_value ELSE afpl.setting_value END AS author_family
			FROM	authors a
				JOIN user_groups ug ON (a.user_group_id = ug.user_group_id)
				JOIN submissions s ON (s.submission_id = a.submission_id)
				LEFT JOIN author_settings agl ON (a.author_id = agl.author_id AND agl.setting_name = 'givenName' AND agl.locale = 'en_US')
			LEFT JOIN author_settings agpl ON (a.author_id = agpl.author_id AND agpl.setting_name = 'givenName' AND agpl.locale = s.locale)
			LEFT JOIN author_settings afl ON (a.author_id = afl.author_id AND afl.setting_name = 'familyName' AND afl.locale = 'en_US')
			LEFT JOIN author_settings afpl ON (a.author_id = afpl.author_id AND afpl.setting_name = 'familyName' AND afpl.locale = s.locale)
				JOIN (
					SELECT
					MIN(aa.author_id) as author_id,
					CONCAT(
					CAST('' AS CHAR),
					' ',
					aa.country,
					' '
					,
				COALESCE(asg1.setting_value, ''), ' ',
				COALESCE(asf1.setting_value, ''), ' ',
				COALESCE(SUBSTRING(asa1.setting_value FROM 1 FOR 255), ''), ' '
			,
				COALESCE(asg2.setting_value, ''), ' ',
				COALESCE(asf2.setting_value, ''), ' ',
				COALESCE(SUBSTRING(asa2.setting_value FROM 1 FOR 255), ''), ' '
			
					) as names
					FROM	authors aa
					JOIN submissions ss ON (ss.submission_id = aa.submission_id AND ss.status = 3)
					JOIN journals j ON (ss.context_id = j.journal_id)
					JOIN published_submissions ps ON (ps.submission_id = ss.submission_id)
					JOIN issues i ON (ps.issue_id = i.issue_id AND i.published = 1)
					
				LEFT JOIN author_settings asg1 ON (asg1.author_id  = aa.author_id AND asg1.setting_name = 'givenName' AND asg1.locale = 'en_US')
				LEFT JOIN author_settings asf1 ON (asf1.author_id  = aa.author_id AND asf1.setting_name = 'familyName' AND asf1.locale = 'en_US')
				LEFT JOIN author_settings asa1 ON (asa1.author_id  = aa.author_id AND asa1.setting_name = 'affiliation' AND asa1.locale = 'en_US')
			
				LEFT JOIN author_settings asg2 ON (asg2.author_id  = aa.author_id AND asg2.setting_name = 'givenName' AND asg2.locale = 'uk_UA')
				LEFT JOIN author_settings asf2 ON (asf2.author_id  = aa.author_id AND asf2.setting_name = 'familyName' AND asf2.locale = 'uk_UA')
				LEFT JOIN author_settings asa2 ON (asa2.author_id  = aa.author_id AND asa2.setting_name = 'affiliation' AND asa2.locale = 'uk_UA')
			
					WHERE j.enabled = 1 AND
					j.journal_id = '1' AND (LOWER(asf1.setting_value) LIKE LOWER('b%')LOWER(asf2.setting_value) LIKE LOWER('b%'))
					GROUP BY names
				) as t1 ON (t1.author_id = a.author_id)
				ORDER BY author_family, author_given LIMIT 0,40 failed. You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LOWER(asf2.setting_value) LIKE LOWER('b%'))
					GROUP BY names
				) as t1 ON (' at line 44
```

**Comment by asmecher** [comment] 2020-01-31 16:48
@Vitaliy-1, this was an additional case of the same problem; it's fixed here: https://github.com/pkp/ojs/commit/514cf466dc5687603599d447e035ee2b5214447e

Thanks for helping track this down!

**Closed by asmecher** 2020-01-31 16:48 UTC
Labels: Bug
