### ISSUE TITLE
[OPS] "Comments to the Moderator" not showing to Moderators

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#5786] opened 2020-04-24 18:32 UTC
**Describe the bug**
Any content added to the "Comments to the Moderator" box during the submission process aren't shown to the Moderators during Production stage.

Basically, that information is not being passed along to the moderation.

**To Reproduce**
1. Submit a preprint;
2. Add some content to the "Comments to the Moderator" box;
3. Check submitted preprint as Moderator;
4. Notice that the comments are not available anywhere.

**What application are you using?**
Open Preprint Systems 3.2.0.1

**Additional information**
![image](https://user-images.githubusercontent.com/4059679/80245315-d81c8c80-8640-11ea-9187-530c0ffdee0b.png)

**Comment by asmecher** [comment] 2020-04-24 20:45
The "comments to the moderator" field contents are sent to a new query in the Submission stage, per `lib/pkp/classes/submission/form/PKPSubmissionSubmitStep1Form.inc.php` (`setCommentsToEditor` function). @ajnyga, I suppose the issue is that we're only showing the production workflow stage?

**Comment by ajnyga** [comment] 2020-04-26 09:53
Yes, but this is fixed in the current stable branch.

**Comment by ajnyga** [comment] 2020-04-26 09:54
https://github.com/pkp/ops/blob/master/classes/submission/form/SubmissionSubmitStep1Form.inc.php#L122-L128

**Comment by asmecher** [comment] 2020-04-27 16:04
I thought so -- thanks!

**Closed by asmecher** 2020-04-27 16:04 UTC
