### ISSUE TITLE
When deleting issue cover image, keys for deleted languages are still present in database

### ISSUE THREAD

**Issue by LevelUpGit** [pkp/pkp-lib#7526] opened 2021-12-02 15:26 UTC
**Describe the bug**
In multilanguage setup, when deleting issue cover image, keys for deleted images are still present in database, although empty.
Also, when your UI is in one language uploaded image gets assigned to that language, there is no way to see if both are present, except changing language.

This has effect on archive page, since if you have one image only, OJS defaults on it, but if you create 2 cover images, then delete one, 
on archive page there will not be cover image for issues on one of the languages. When I delete empty meta, in table "issue_settings", column "settings_name", OJS returns to default behavior.

**To Reproduce**
1. In multilanguage setup open one issue, and add cover image,
2. Change language
3. Repeat step one
4. Delete one image
5. Go on archive page and one of the languages will not have cover images.

**What application are you using?**
 OJS version 3.3.0.8 

**Additional information**
![Screenshot_2](https://user-images.githubusercontent.com/69863985/144451374-f37b41b8-eed1-4d69-9f99-81962c449af3.jpg)

**Comment by NateWr** [comment] 2021-12-06 12:43
@LevelUpGit Looking at the code, this is the intended behaviour. With multilingual data, the localization code will fall back to the journal's primary locale. So if you have a cover image in the primary language but not another, it will fall back to the journal's primary cover image locale. But if you have a cover image in another language but not the primary one, it will not fall back to that. 

@asmecher It looks like this is the intended fallback behaviour and it has worked this way for a [long time](https://github.com/pkp/pkp-lib/blame/b2b45d77413f62d091714aa0c48521c8dbe1ee1c/classes/core/DataObject.inc.php#L66-L71). See also [deleting the cover image](https://github.com/pkp/ojs/blame/stable-3_3_0/classes/controllers/grid/issues/IssueGridHandler.inc.php#L214-L216) and [updating _settings tables](https://github.com/pkp/pkp-lib/blame/stable-3_3_0/classes/db/DAO.inc.php#L384). What's happening is that `DataObject::getLocalizedObject()` is returning the [first found locale key](https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/core/DataObject.inc.php#L63-L68), but the value of this is an empty string. Obviously not something we want to change in the stable version. But I'm curious if this intended or if we should be checking the return value? I imagine changing this would have a lot of unexpected effects.

**Comment by NateWr** [comment] 2021-12-06 12:44
ps - I'm going to close this as it is not something we're necessarily going to fix as a bug. But let's keep the conversation open as we think through the locale fallback in such cases.

**Closed by NateWr** 2021-12-06 12:44 UTC

**Comment by LevelUpGit** [comment] 2021-12-14 20:53
@NateWr Hi,

I agree with "Looking at the code, this is the intended behaviour. With multili...", but I came across two issues: 

1. If you set image on both languages than delete from one of those, OJS is will not fall back to remaining one.
- expected behavior would be to fall back to remaining one.
2. There is no way to see if you have set second image, except from changing languages back and fourth, not like other text fields where we have both of languages displayed.
