### ISSUE TITLE
[OPS] Editorial Activity statistics are inaccurate

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#7709] opened 2022-02-17 12:07 UTC
**Describe the bug**
The statistics that are given in the Editorial Activity section are inaccurate.

Taking by example SciELO Preprints, this is what is shown today as overall Editorial Activity:

![image](https://user-images.githubusercontent.com/4059679/154478200-6fd1c4fa-a036-4859-916d-2c7a784fedfe.png)

- It says 1856 submissions received but our Archive tab says more than that:
![image](https://user-images.githubusercontent.com/4059679/154478501-b6ebf2e2-1486-411e-8757-c2002cd6bd4c.png)
- It says 0 submissions accepted even though we currently have over 1400 preprints posted
- It says 1041 submissions "published" (correct wording should be "posted") even though we currently have over 1400 preprints posted

**What application are you using?**
OPS 3.3.0.8

**PRs**
`stable-3_3_0`
- https://github.com/pkp/pkp-lib/pull/7726
- https://github.com/pkp/ojs/pull/3311
- https://github.com/pkp/omp/pull/1072
- https://github.com/pkp/ops/pull/239

`main`
- https://github.com/pkp/pkp-lib/pull/7731
- https://github.com/pkp/ojs/pull/3312
- https://github.com/pkp/omp/pull/1073
- https://github.com/pkp/ops/pull/241

**Comment by jonasraoni** [comment] 2022-02-17 12:37
I've just checked an OPS 3.3.0.8 instance and I can confirm the results are inaccurate.

**Comment by mfelczak** [comment] 2022-02-17 15:07
@ajnyga is this something that you'll have a chance to tackle shortly? We have a hosted client affected as well and can provide a PR next week if it might be helpful.

**Comment by ajnyga** [comment] 2022-02-17 17:47
@jonasraoni did you check OJS as well? Just seems a bit weird that for example the submissions received stat would be incorrect in OPS since that is mostly dealt with in the pkp-lib probably

**Comment by ajnyga** [comment] 2022-02-17 17:50
@mfelczak of course go ahead, I will not have time to look at this in more detail before next week anyway

**Comment by NateWr** [comment] 2022-02-17 17:55
Is it possible that there are submissions that were "declined" _before_ the author finished submitting them? The stats code excludes submissions where the `submission_progress` column is not `0` (which it should be after the author finishes submitting).

There is also some code that excludes some cases that might arise from imported submissions:

https://github.com/pkp/pkp-lib/blob/5f17a8b649677f17728e311ca51323ace2fd3e72/classes/services/queryBuilders/PKPStatsEditorialQueryBuilder.inc.php#L368-L380

**Comment by alexxxmendonca** [comment] 2022-02-17 17:56
> Is it possible that there are submissions that were "declined" before the author finished submitting them? 

Not in our case.

**Comment by ajnyga** [comment] 2022-02-18 07:51
Has to be something in pkp-lib. This is from the current OJS main branch (I only got three submissions because the tests seem to crash locally in XAMPP sometimes)

Three submissions, two in editing and one published
<img width="298" alt="Screenshot 2022-02-18 at 9 48 01" src="https://user-images.githubusercontent.com/16347527/154640548-d3b79dcc-e555-4a7e-8443-9f878c9aeb52.png">

The statistics say two submissions received.
<img width="677" alt="Screenshot 2022-02-18 at 9 49 06" src="https://user-images.githubusercontent.com/16347527/154640611-45baed2b-6232-4e2e-989d-600305ec3daf.png">

**Comment by ajnyga** [comment] 2022-02-18 08:01
At least `applyCustomRange` seems to be giving a javascript error. Maybe the daterange is not passed on correctly.

**Comment by jonasraoni** [comment] 2022-02-19 18:10
I just started taking a look on it =]

About the submissions received, here's the culprit on my use case:

https://github.com/pkp/pkp-lib/blob/480c1515b4d5db219ceb6f9699a3cfb5f658fda6/classes/services/queryBuilders/PKPStatsEditorialQueryBuilder.inc.php#L383

According to the comment above this line, looks like this condition is trying to ignore imported submissions.
1. Does it make sense to not count imported items? Without context, it sounds a bit counterintuitive for me... If yes, then I think it would be better to have a flag for this.
2. The condition is currently error-prone due to the different data types (`publications.date_published` is a `date` and `submissions.date_submitted` is a `datetime`). This way if we submit something at `2000-01-01-10:00` and publish it on the same day, the final condition will end up like `2000-01-01-10:00 < 2000-01-01-00:00`, which will ignore a valid record 🤔

**Comment by jonasraoni** [comment] 2022-02-19 19:13
About the accepted count... The code is looking for accepted editorial decisions, but no decision is created when a preprint is published (only the rejected ones receive a decision). I guess it should be this way, but just to confirm, isn't it needed to have an accepted decision?

**Comment by ajnyga** [comment] 2022-02-21 10:08
Yes, we actually discussed this with Nate last week. It has just been left there when OPS was created based on OJS. There are currently not "accepted" editorial decision in OPS that the count could be based on. You can just decline a submission or post it online. I think you could remove that with the same PR?

**Comment by ajnyga** [comment] 2022-02-21 10:13
I think it makes sense to ignore imported submissions. The reason for counting accepted/rejected is to get the percentage for approved submissions. The imported articles are all accepted so it affects the percentage in the wrong way because you never import rejected articles from those years.

BUT I think the problem with the accepted/rejected count is also that it counts all types of submissions. Not just reviewed articles. So an editorial is regarded as an accepted submission. Or at least I think it does. We would need a content type taxonomy to the system...

**Comment by NateWr** [comment] 2022-02-21 11:19
> The code is looking for accepted editorial decisions, but no decision is created when a preprint is published (only the rejected ones receive a decision)

In the `main` branch, I am removing these stats as part of #7265. If you want to remove them for `stable-3_3_0`, please do so in a separate commit that won't be forward-ported to `main`.

> this condition is trying to ignore imported submissions

You can see the original bug report at https://github.com/pkp/pkp-lib/issues/6011. This was well-tested against real data, so we do want to keep this in.

> if we submit something at `yyyy-mm-dd-10:00` and publish it on the same day, the final condition will end up like `yyyy-mm-dd-10:00 < yyyy-mm-dd-00:00`, which will ignore a valid record

That's a good point, and a use-case that only exists in OPS. I think we could safely change this condition to `date_submitted > date_published` without impacting OJS/OMP. But I'd love to see this tested against a real journal's data that has imported submissions, to make sure we aren't accidentally reintroducing the problem in #6011.

**Comment by jonasraoni** [comment] 2022-02-21 12:39
@NateWr The PR is huge, if you can save me some time, confirm if the following is the way to go:
- Remove/omit the accepted and declined statistics in `ops/3.3.0`
- Do not add a declined decision
- Leave the accepted decision

**Import:**
What about adding an `is_imported` field to the submission? And in the report, I think it would be useful to add a note stating that N submissions were imported and discarded from the statistics.

**Issue with filter:**
I'll take a look on the https://github.com/pkp/pkp-lib/issues/6011 and import a submission to see the outcome :)

**Comment by alexxxmendonca** [comment] 2022-02-21 12:42
> Remove/omit the accepted and declined statistics in ops/3.3.0

Hey all, I'm not sure I am following the conversation (forgive me if I'm not), but we _do want_ to know the number of accepted and rejected submissions.

**Comment by NateWr** [comment] 2022-02-21 12:51
> The PR is huge

Which PR?

> Remove/omit the accepted and declined statistics in `ops/3.3.0`

No, only remove the accepted statistics. In OPS, accepted = published, so we should only see numbers for Received, Declined, and Published.

> Do not add a declined decision / Leave the accepted decision

Maybe I'm misunderstanding something, but you shouldn't need to touch the decisions at all. The one-line change to the conditional expression you mentioned should be enough to include preprints published on the same day as they are submitted.

> we do want to know the number of accepted and rejected submissions

Yes, but in OPS it will be called Published and Declined.

**Comment by NateWr** [comment] 2022-02-21 12:52
Sorry @jonasraoni, I realize you meant the PR for #7265. I didn't mean for you to crawl through that. Just reducing the stats to Received, Declined and Published in `stable-3_3_0` should do the trick.

**Comment by alexxxmendonca** [comment] 2022-02-21 12:52
Thanks @NateWr for the clarification!

**Comment by NateWr** [comment] 2022-02-21 12:54
> What about adding an `is_imported` field to the submission?

Can we talk about this as part of #7446? If we add something like this, I don't want to do it as part of this little issue. I'd prefer to think through how something like this might be used (or not) throughout the entire system. We might, for example, need to make distinctions between imports for different purposes (back catalogue vs. current but doesn't use the workflow).

**Comment by jonasraoni** [comment] 2022-02-23 17:04
Well, I just omitted the submissions accepted, and added this extra item to make it clear where the "missing items" went:

![image](https://user-images.githubusercontent.com/361921/155367192-eeeb8e7f-e35e-44b2-a9e9-f0b4adaef463.png)

If that's fine, I'll apply these PRs to OJS/OMP and their `/main` branches:

- https://github.com/pkp/pkp-lib/pull/7726
- https://github.com/pkp/ops/pull/239

**Comment by NateWr** [comment] 2022-02-24 10:59
That sounds sensible @jonasraoni. Can we change the name of the metric to "Other Submissions"? And a suggestion for the description:

> This includes submissions that are not counted in other totals, such as those that are still in progress and those that appear to have been imported.

**Comment by jonasraoni** [comment] 2022-02-25 10:18
@NateWr I had used "Other Submissions" (in case more exceptions get added to the list), but then I changed my mind 😁
I've updated the wordings and created the remaining PRs. Is there anything else missing? If not, then I'll merge and close this one.

**Comment by jonasraoni** [comment] 2022-02-25 10:30
@asmecher there's nothing special here, but if you'd like to take a look while @NateWr is away, great 👌

**Comment by asmecher** [comment] 2022-02-26 00:53
@alexxxmendonca and/or @ajnyga, can you confirm that the PRs listed in the top of the issue correct your real-world data? OJS just needs the pkp-lib commit; OPS needs an additional change as well.

**Comment by ajnyga** [comment] 2022-02-26 18:36
Not sure, you tell me.

Here are the screenshots of my OJS main branch install after applying the changes.
<img width="921" alt="Screenshot 2022-02-26 at 20 34 30" src="https://user-images.githubusercontent.com/16347527/155855087-196a3a40-dfc5-43c4-a7cd-0025195aa97c.png">
<img width="933" alt="Screenshot 2022-02-26 at 20 34 54" src="https://user-images.githubusercontent.com/16347527/155855095-ada0121b-c628-4fe9-9313-a17090242f94.png">

**Comment by ajnyga** [comment] 2022-02-26 18:37
So if a scheduled submission should be in the Other Submissions column, then it seems to be ok. At least the numbers match in my case.

**Comment by asmecher** [comment] 2022-03-03 20:51
Deferring to 3.3.0-10 -- I'm releasing -9 today or tomorrow -- but please don't forget to look at the comment above, @jonasraoni!

**Comment by jonasraoni** [comment] 2022-03-08 13:21
@ajnyga, the rule we're using to check if a submission was imported is:
- Submission is published
- Date submitted < date published

This way, if you submit and publish a submission at the same day, it will be considered as imported (the wording that Nate chose fits well "(...) and those that appear to have been imported"). I guess your submissions must be falling in this case.

I've added a note about improving this check here: https://github.com/pkp/pkp-lib/issues/7446#issuecomment-1047774944

For now, I think it's better to leave it this way.

**Comment by jonasraoni** [comment] 2022-03-18 12:00
@ajnyga let me know if that makes sense, then I'll merge these PRs =]

**Comment by asmecher** [comment] 2022-04-08 17:31
@jonasraoni, the PRs at the top of the issue look OK to me, except for a couple that appear to be failing tests (OMP and OJS main) for reasons that are probably unrelated to your changes. If you can restart those tests and get them to pass, I'm OK for everything to be merged. @ajnyga, a sober second thought is always welcome :)

**Comment by alexxxmendonca** [comment] 2022-10-06 17:55
We have upgraded to OPS 3.3.0-13 today and this was the first time I was able to run tests about this issue (our previous version was 3.3.0-10).

The numbers are still confusing to me...

![image](https://user-images.githubusercontent.com/4059679/194384237-e65050c7-4cae-4faf-8933-389908aa8269.png)

It says there are 1386 submissions published, but we have 1965 preprints right now:

![image](https://user-images.githubusercontent.com/4059679/194384439-ddf631c5-40dd-4a9c-8b9f-03c516051c11.png)

It says 2344 submissions received, but the "Archives" tab shows 2915:

![image](https://user-images.githubusercontent.com/4059679/194384719-fe8cda79-eff4-4cd0-98a5-6ae57fe291a0.png)

The numbers don't match...

**Comment by asmecher** [comment] 2022-10-06 21:58
Reopening for a look when you have time, @jonasraoni...

**Comment by jonasraoni** [comment] 2022-10-14 19:38
@alexxxmendonca,

I've just checked the numbers against a production installation that I've got here, and it seems to be ok, even though I agree it looks confuse.

The `Submissions Received` refers to submissions that are:
- Complete/submitted
- Not flagged as imported data (when the submission date is equals to the publication date)

In order to make it less confuse, I think we'll need to add extra descriptions, just like the one for `Other submissions` or to break down the values using extra rows (e.g. `Incomplete submissions`, `Imported submissions`).

---

Follow sample numbers/screenshots:

`Submissions Received` + `Other Submissions` = 2568
`All Active` + `Archives` = 2568

![image](https://user-images.githubusercontent.com/361921/195924111-927c8d2a-15e2-4b93-8f97-615d7cf7a2b3.png)
![image](https://user-images.githubusercontent.com/361921/195924361-82e8752f-aff9-4d9a-8692-16cb27e20212.png)

**Comment by NateWr** [comment] 2022-10-17 08:52
> Not flagged as imported data (when the submission date is equals to the publication date)

Based on [this comment](https://github.com/pkp/pkp-lib/issues/7709#issuecomment-1046844858), I thought that we had come up with a conditional expression that worked for OPS too. Is that not right?

**Comment by jonasraoni** [comment] 2022-10-17 12:54
@alexxxmendonca after the https://github.com/pkp/pkp-lib/issues/6011, submissions that have been submitted and published in the **same day**, will be assumed to be imported. The difference must be coming from such cases.

**Comment by alexxxmendonca** [comment] 2022-10-17 12:56
I see. I was not aware of that.

That happens a lot with preprints (submitted and posted on the same day). Would it be possible to have a note about that too?

Or, wouldn't it be better to treat it differently in OPS?

**Comment by NateWr** [comment] 2022-10-17 13:02
Hmm, yeah maybe this is my fault for a lack of clarity, but I thought the purpose of the conditional expression was to support the OPS use case while catching _most_ imported submissions in OJS/OMP. The way that would work would be by including same-day matches but excluding one-day-ago:

```
if (date_published < date_submitted) {
    exclude_from_stats();
} else {
    include_in_stats();
}
```

I think the crucial difference here is using `<` instead of `<=`.

**Comment by jonasraoni** [comment] 2022-10-21 09:21
Correct me if I'm wrong, but if we change the condition to the above (count as received if `date_published >= date_submitted`), then the imported submissions will be included as well... I've just imported one item using the `NativeImportExport` plugin and it ends up with this pattern:

|date_submitted|date_published|
|-|-|
|2021-03-15 00:00:00|2021-03-15|

I didn't see how the `QuickSubmit` works... But if it has the same date pattern, then another possibility to flag imported content would be to check if `date_submitted == date_published` and `time(date_submitted) = '00:00:00'` (probably rare to have someone publishing exactly as this time).

As a last resort, if it's not possible to find a great heuristic, I'd rather count the imported submissions and wait for a proper fix. It sounds easier to explain unexpected deviations due to imported items lacking decisions, than wrong numbers 🤔

**Comment by NateWr** [comment] 2022-10-24 09:10
I think in a realistic import setting, the date published is metadata that should represent the date the item was actually published. Wouldn't this usually be in the past?

**Comment by jonasraoni** [comment] 2022-10-24 10:05
That makes sense. Here I've been using a dataset which perhaps was imported in a not perfect way (I've got the conditions above), so I'll check the `QuickSubmit` and the `NativeImportExport` plugin, then come back with PRs =]

**Comment by jonasraoni** [comment] 2022-10-30 20:23
I just did some tests:
- `Native` plugin: if the XML has a `date_submitted` attribute defined, it will be used (and then probably break the heuristic).
- `QuickSubmit` plugin: `date_submitted` is always set to the current date time (fits the heuristic).
- Other import plugins: When the `date_submitted` is absent, they are defaulting to the `publication_date` (I've just checked two repositories, which I'll update).

Follow the PRs to update the condition and add extra information (submissions in progress + imported submissions). I'll port to `main` once it's reviewed:
https://github.com/pkp/ojs/pull/3595
https://github.com/pkp/pkp-lib/pull/8385

**Comment by asmecher** [comment] 2022-11-10 21:41
@jonasraoni, did you tag someone to review these? Are they ready for review?

**Comment by jonasraoni** [comment] 2022-11-11 10:06
@asmecher, it's ready for review... But looks like I didn't tag anybody, so feel free to take a look :)

**Comment by asmecher** [comment] 2022-11-15 01:26
@jonasraoni, I presume it also needs porting to the other apps?

**Comment by asmecher** [comment] 2022-11-15 01:26
@jonasraoni, can you open PRs to the other apps to kick off Travis tests there?

**Comment by jonasraoni** [comment] 2022-11-15 11:58
Ok! Here are all PRs for the stable:
- https://github.com/pkp/pkp-lib/pull/8385
- **[TESTS ONLY]** https://github.com/pkp/ojs/pull/3595
- **[TESTS ONLY]** https://github.com/pkp/ops/pull/392
- **[TESTS ONLY]** https://github.com/pkp/omp/pull/1249

**Comment by asmecher** [comment] 2022-11-15 20:37
Thanks! All 3 tests suffered hiccoughs :frowning_face: but none of them were related to your changes. I've merged all 4 PRs. Please go ahead with forward-porting this to `main`!

**Comment by jonasraoni** [comment] 2022-11-17 08:01
@asmecher Here are the PRs for main
- https://github.com/pkp/pkp-lib/pull/8439
- https://github.com/pkp/ojs/pull/3625
- https://github.com/pkp/omp/pull/1250
- https://github.com/pkp/ops/pull/393

**Comment by asmecher** [comment] 2022-11-17 19:40
@jonasraoni, thanks, I've pinged Bozana on the pkp-lib main PR to see how it'll interact with her stats rewrite.

**Comment by jonasraoni** [comment] 2022-11-27 14:45
I've rebased and merged the remaining PRs.

**Closed by jonasraoni** 2022-11-27 14:45 UTC
Labels: Bug:1:Low
