### ISSUE TITLE
[Sprint/UIUX] More Detailed Stage Indicators on Dashboard

### ISSUE THREAD

**Issue by retostauffer** [pkp/pkp-lib#4103] opened 2018-09-27 16:20 UTC
> Result of the UI/UX group from the Heidelberg Sprint 2018 (@stranack @NateWr).

One of our ideas was to improve the dashboard using **visual indicators** (see screen-draft below). This requires to have a more detailed tracking of the state of each submission (which we see as *a requirement* from a user/admin perspective, especially when maintaining high-volume journals).

We came up with an idea where we can stick to the current labeling of the dashboard but we have extended the visual representation to give more detailed information about the current state of a submission. Two examples for the Review and Production stage below, might also be useful for other stages (?).

**For review stage:**

- **All empty**: submission sent _to review_ but no further actions taken
- **Dot 1** = at least one reviewer said yes
- **Dot 2** = at least one reviewer decided
- **Dot 3** = all reviews are in

![Screen-draft on how this might look like.](https://user-images.githubusercontent.com/13628564/46159853-9e777a00-c281-11e8-8123-3e73606721f1.png)

Very similar for **the production stage**:

- **All empty**: submission sent to production but no further actions taken
- **Dot 1** = discussions started
- **Dot 2** = galleys uploaded
- **Dot 3** = scheduled for publication

![Screen-draft on how this might look like.](https://user-images.githubusercontent.com/13628564/46159923-c6ff7400-c281-11e8-8763-7e7c5264828f.png)

Might be interesting in addition:
- [Quick-Filter Options/Buttons on Dashboard #4101](https://github.com/pkp/pkp-lib/issues/4101)
- [Refinement of Filter Options on Dashboard #4012](https://github.com/pkp/pkp-lib/issues/4102)

**Comment by asmecher** [comment] 2018-09-27 16:57
(@stranack and @NateWr!)

**Comment by NateWr** [comment] 2018-09-28 12:09
Thanks @retostauffer, providing some more detailed stage status has been a [common request](https://github.com/pkp/pkp-lib/issues/1662).

I am a little bit hesitant to embrace the dot technique. In an early version of the new submissions list panels, we used just colored icons to try to indicate various states of review assignments, discussions and file uploads. During user testing, users found it completely bewildering. So we opted for the icon + text, with the accompanying legend in the dropdown that you now see. I am worried that going to a dot notation will similarly cause a lot of confusion for editors.

Still, we obviously need to do a better job of signalling what's going on inside of a stage. For the review stage, I've mocked up a quick example which would display reviewer acceptance alongside reviewer decisions:

![selection_070](https://user-images.githubusercontent.com/2306629/46207048-dc29e080-c31d-11e8-8115-bc82393e509f.png)

Would this adequately address the desire to see how many reviewers have accepted a review assignment?

The other big change suggested by the group is to indicate when all reviews are in. An editor should see a notice when the reviews are in. However, looking at it now, I can see that the message doesn't indicate that _all_ reviews are in:

![selection_071](https://user-images.githubusercontent.com/2306629/46207211-7558f700-c31e-11e8-8a4d-0c916d4e1849.png)

Perhaps we should explore a more significant change to the item in the list, such as a splash of color in an unexpected place:

![selection_073](https://user-images.githubusercontent.com/2306629/46207346-fa441080-c31e-11e8-9082-5d674d14fa4a.png)

Maybe this is also a candidate for a dedicated filter, like "Needs Decision"?

For the Production stage, the info from the first two dots should be indicated in the icons. Do you remember in what ways the group felt that discussion and galley icons did not communicate the information very well? Is it just that the group wants a "progress bar" of some kind for each submission?

And finally, the "Scheduled for publication". We should really indicate this more clearly. In fact, it seems like any article scheduled for publication should be moved to the Archive tab, since editorial activity should effectively be complete. Do you think that would address some of the concerns that were raised?

**Comment by openacademia** [comment] 2018-10-01 11:03
Hi @NateWr ,

We completely agree that it is important to distinguish between "New Reviews have been submitted" and a situation where all reviews are in. I think your suggestion is great: "All reviews are in and a decision is needed. View Reviews." (and an added splash of color! ;))

We also like the idea of an added filter like "Needs Decision".

Generally, the most important thing is for the system to indicate when an action is required by an editor, such as "Revised Manuscript Uploaded" (splash of color, please! :)) and "All reviews are in and a decision is needed. View Reviews."

Your suggestion to add a little icon indicating that for instance 2/3 reviewers have accepted the invitation sounds like a really great idea!

**Comment by alex-wreschnig** [comment] 2019-07-30 20:27
The UI/UX group at the 2019 Pittsburgh sprint took a long look at the Submissions component and the group identified a problem very similar to the problem identified here. For users managing large journals, this was considered very important and it was echoed by a majority of participants.

We viewed this as different from, but related to, a need to have a better understanding of what you are _personally_ responsible for (as opposed to managing), which we documented as #4958 .

(Group doc from the sprint: (https://docs.google.com/document/d/1oWcsyHX2Ww5tHPpSN_-c2KaIhmAdaGYcZn3gFHjMEpc/edit?usp=sharing))

**Comment by NateWr** [comment] 2019-08-20 08:41
@forgive38 This is a complex problem, but your idea of having separate filters tied to review round status is a good idea. However, there are a bunch of statuses and I'd like to reduce the number of filters. A quick idea would be:

- Needs Action (`REVIEW_ROUND_STATUS_PENDING_REVIEWERS`, `REVIEW_ROUND_STATUS_REVIEWS_COMPLETED`, `REVIEW_ROUND_STATUS_REVIEWS_OVERDUE`)
- Revisions Requested (`REVIEW_ROUND_STATUS_REVISIONS_REQUESTED`, `REVIEW_ROUND_STATUS_RESUBMIT_FOR_REVIEW`)
- Revisions Submitted (`REVIEW_ROUND_STATUS_REVISIONS_SUBMITTED`, `REVIEW_ROUND_STATUS_RESUBMIT_FOR_REVIEW_SUBMITTED`)

No filter is needed for the `REVIEW_ROUND_STATUS_REVIEWS_READY`, which means one or more reviews have been submitted but not all are in yet.

These filters can be placed inside the review stage.

![Selection_107](https://user-images.githubusercontent.com/2306629/63331966-a7a48600-c32e-11e9-8d8e-ea72fe4141a7.png)

These filters should only appear for editors (`ROLE_ID_MANAGER`).

**Comment by forgive38** [comment] 2019-08-21 15:19
Good idea !
I will have a try

**Comment by alexxxmendonca** [comment] 2019-08-21 16:06
@NateWr that's a really good idea!

> Revisions Requested (REVIEW_ROUND_STATUS_REVISIONS_REQUESTED, REVIEW_ROUND_STATUS_RESUBMIT_FOR_REVIEW)

I'm a little hesitant about adding REVIEW_ROUND_STATUS_RESUBMIT_FOR_REVIEW to this filter. For papers in that stage, wouldn't it give the impression that the revisions have already been requested, while that's not really the case?

One might assume that revisions have been requested but the Editor needs to use the "Request Revisions" decision to actually request revisions. Isn't that right?

**Comment by NateWr** [comment] 2019-08-21 17:03
@alexxxmendonca can you say a little bit more about this? My understanding is that Resubmit for Review is the same as Request Revisions except the presumption is that the revisions will be subject to another round of reviews...

**Comment by alexxxmendonca** [comment] 2019-08-21 17:09
@NateWr do we even still have "Resubmit for Review" in OJS 3?

The only "revisions" decision I see is "Request Revision".

When does "Resubmit for Review" come into place?

**Comment by NateWr** [comment] 2019-08-21 17:16
When you click "Request Revisions" there are two options to select. One of them is resubmit for review. Depending on the option you select, the associated status will be set.

**Comment by alexxxmendonca** [comment] 2019-08-21 17:24
@NateWr ok, that makes perfect sense then and my initial concern can be discarded as no matter the option chosen by the Editor, revisions will always be requested to the authors.

**Comment by forgive38** [comment] 2019-09-25 09:24
@NateWr  
First proposition for this issue : 

pkp/ojs#2471
#5088 
pkp/ui-library#36

I don't know why tests didn't pass as I can't access to screenshots. 
It seems to be Timeout error. Tests pass on my computer.

Can you check ?
Thank you

**Comment by NateWr** [comment] 2019-09-25 11:08
Thanks @forgive38! At first glance this looks good. Can you stage your changes against our `master` branch rather than the `stable-3_1_2` branch?

There have been significant changes to the filters system for the `master` branch and, given the closing deadline for feature freeze, I can't guarantee we would get the changes into `master` in time for 3.2. For that reason, I can't add it to 3.1.x because it could lead to a regression when 3.2 is released.

**Comment by PeterfordUP** [comment] 2020-06-22 17:21
I have presented a current solution that we at Ubiquity Press have developed for our custom forked version of the OJS2 platform in the thread linked below. We are very interested in contributing this functionality to OJS3:
https://github.com/pkp/pkp-lib/issues/4172#issuecomment-647662058

**Comment by NateWr** [comment] 2021-11-29 12:38
Thanks everyone for the discussions and brainstorming on this issue. I think we have settled on good filters to add, and we have scheduled work on this for 3.5. To keep the issue's clean and easy to read, I have filed a new issue at https://github.com/pkp/pkp-lib/issues/7488. I'm closing this issue in favour of that one. Please take a look and add any comments there.

**Closed by NateWr** 2021-11-29 12:38 UTC
Labels: UI/UX
