### ISSUE TITLE
[OJS] Review form radio buttons filled by default.

### ISSUE THREAD

**Issue by WaDelma** [pkp/pkp-lib#3249] opened 2018-01-09 17:41 UTC
In 2.x review form radio buttons weren't filled and in the review form test they aren't filled in 3.x, but when doing actual review they are.

This makes it easy for reviewer to miss choice making the data less reliable. It also makes required flag for radio button do nothing.

**Comment by asmecher** [comment] 2018-11-29 17:20
Duplicate of https://github.com/pkp/pkp-lib/issues/4147 (already fixed).

**Closed by asmecher** 2018-11-29 17:20 UTC
