### ISSUE TITLE
Replace tag-it library with something else

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#4208] opened 2018-11-02 21:32 UTC
Tag-it has several problems...
- Keyword separator character interferes with [Arabic](https://forum.pkp.sfu.ca/t/an-arabic-letter-unexpectedly-ends-current-entry-in-keywords-field/49627) and [Cyrillic](https://forum.pkp.sfu.ca/t/cyrillic-b-treated-as-enter-in-keywords/35690)
- It may not be compatible with JQuery 3.x: see comments at https://github.com/pkp/pkp-lib/issues/3404

Evaluate possible replacements, choose one, and implement!

**Comment by asmecher** [comment] 2018-11-02 21:33
(https://select2.org/ seems popular...)

**Comment by NateWr** [comment] 2018-11-05 11:05
Select2 is popular but my understanding is that it has accessibility issues. I doubt Tag-it is any better, though. Eventually we will phase out Tag-it as forms move to Vue.js, where we'll use an autosuggest that attempts to be WCAG compliant.

**Comment by ajnyga** [comment] 2018-11-05 16:40
This https://github.com/pkp/pkp-lib/issues/1550 is very much connected to this issue.

**Comment by NateWr** [comment] 2018-11-22 11:16
Personally, I am tempted to just wait until we make it obsolete with the Vue.js forms. But if you or someone wants to do a quick swap in the meantime to something better I have no objections.

It would also be possible to turn each tag-it field into a little Vue.js app that loads https://github.com/Educents/vue-autosuggest. But, again, we might be bending over backwards for something that will be replaced before too long.

**Comment by asmecher** [comment] 2018-11-24 15:54
@natewr, I think tag-it is currently broken since the JQueryUI upgrade, no?

**Comment by NateWr** [comment] 2018-11-26 16:03
Oh I didn't realize! In that case, we do need to replace it. :joy: 

@jamshidhashimi I'd say choose the one with the API you like the best and bring it in, ideally if it can be integrated through the `package.json` or `composer.json` files, so that we can more easily keep it updated.

**Comment by jamshidhashimi** [comment] 2018-11-26 17:08
I learnt from [here](https://github.com/aehlke/tag-it/issues/402) that this [fork](https://github.com/fagianijunior/tag-it) works with jQuery 3. From there, I further [learnt](https://github.com/fagianijunior/tag-it/commits/master) that `.andSelf()` is depreciated in jQuery 3 and that should be changed to `andBack()` and that seems to be the source of the issue.

Should I go with the fix or replace the library? sorry, just wanted to make sure :)

**Comment by ajnyga** [comment] 2018-11-26 17:24
+1 for fixing this in tag-it, if in the long it will be replaced anyway (thinking of myself of course since I have a plugin that hooks into tag-it autosuggest...)

**Comment by jamshidhashimi** [comment] 2018-12-03 00:53
**On compatibility with JQuery 3.x:**
Going through the issues and merged PRs, I noticed @asmecher already applied the [patch](https://github.com/pkp/pkp-lib/commit/1fbcaabb5b9a6923648210238c5d0237ea496374#diff-0a1c6970cd39720bb6e4b13a65194aef) I mentioned above. So there shouldn't be an issue regarding that. 

**On resolving the issues available:**
On resolving this [issue](https://forum.pkp.sfu.ca/t/an-arabic-letter-unexpectedly-ends-current-entry-in-keywords-field/49627) on Arabic and this [issue](https://forum.pkp.sfu.ca/t/cyrillic-b-treated-as-enter-in-keywords/35690) on Cyrillic, I found out that the source of the issue is `KeyboardEvent.keyCode` (in addition to being [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent)), because although the `KeyboardEvent.key` changes, `KeyboardEvent.keyCode` is always 188, in any language keyboard. You can test the behaviour [here](https://keycode.info/). To resolve the issues we are dealing with in the scope of this and related issues, changing the line:
`(event.which === $.ui.keyCode.COMMA && event.shiftKey === false) ||`
to
`(event.key === ',' && event.shiftKey === false) ||` 
does the work. This keeps the comma (,) working fine in any keyboard that uses it and stops thinking that (و) in Arabic or Farsi and (б) in Cyrillic is a comma. I also tested the solution with Turkish keyboard, where the key in the keyboard that generates comma is located in a different place than the English one and it works fine.

**On supporting commas in all languages:**
I also thought of providing support for the Arabic and Cyrillic comma through tag-it, but I noticed there are a lot of types of [commas](https://en.wikipedia.org/wiki/Comma) out there. It looks possible to provide that support, as we can detect `ctrl`, `shift` and `meta` keys through JavaScript and combining that with the `event.code` can let us fire actions. This solution needs a complete list of keyboard shortcuts to incorporate the solution.

Any thoughts?

**Comment by jamshidhashimi** [comment] 2018-12-06 08:52
PR:
[#4285](https://github.com/pkp/pkp-lib/pull/4285)

@asmecher @NateWr please review. Thanks.

**Comment by asmecher** [comment] 2018-12-06 19:45
@NateWr, would you mind reviewing this one? Thanks!

**Comment by NateWr** [comment] 2018-12-13 14:39
@jamshidhashimi It looks like you've closed that PR. Is there an active one you want me to look at?

**Comment by jamshidhashimi** [comment] 2018-12-13 20:15
@NateWr submitted the pkp/ojs#2224 for test in OJS. All tests are have passed.

**Comment by NateWr** [comment] 2018-12-21 14:02
Merged! Thanks @jamshidhashimi.

**Closed** 2018-12-21 14:02 UTC
Labels: Try Me
