### ISSUE TITLE
[OJS] Tap controls don't work for dropdown menus in the backend

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#2473] opened 2017-04-26 03:29 UTC
Hi @NateWr,

Maybe related to https://github.com/pkp/pkp-lib/issues/2085

With a iPad Safari browser in OJS 3.0.2 when trying to exit dashboard:

Click on username in right corner => the menu with Profile and Logout link appears => click on Logout => nothing happens

However, if you click on Profile link, the menu with the two items is shifted above the username and after that the logout link works.

This happened already in November in the first OJS3 Workshops I had with 3.0.0 and now also with 3.0.1

**Comment by NateWr** [comment] 2017-04-26 08:30
Thanks @ajnyga. I've updated the title and assigned myself to this.

**Comment by NateWr** [comment] 2017-06-12 11:47
HI @ajnyga, I'm having trouble reproducing this issue in Chrome's device emulator. It's not a 100% perfect emulation, though.

It sounds like there were some layout issues for you that may have been contributing to the issue. Can you describe that in more detail? You talk about the position of links shifting. Any more details you can provide there might help figure out what was going on.

**Comment by ajnyga** [comment] 2017-06-13 04:57
Hi, I will try to do a screencast of the problem, but I will have the opportunity to do so next Monday.

**Comment by NateWr** [comment] 2017-08-21 16:36
Hi @ajnyga, if you're still able to do a screencast of the problem, that'd be great. Otherwise I may close this until we get additional bug reports.

**Comment by ajnyga** [comment] 2017-08-22 15:57
Hi,

This was recorded with iPad Air 2, IOS 10.3.2. 

Between 0:00-0:15 I try to select a journal from the pull down menu, it does not respond.
Between 0:17-0:30 I first try to click the "log out" link but it does not respond. I then click on "My profile" link, which causes the menu to shift up (around 0:23). After this, the log out link responds to the click.

https://youtu.be/q1MpcV5ikoU

**Comment by NateWr** [comment] 2017-08-22 16:02
Thanks @ajnyga! I'm not able to access the video. Maybe you need to change the access permissions on it?

**Comment by ajnyga** [comment] 2017-08-22 16:06
sorry, try now.

**Comment by NateWr** [comment] 2017-08-22 16:22
Hmm, nothing jumps out at me from the video. Seems like a long shot, but can you removing the multiple contexts dropdown menu from `usernav.tpl` and testing to see if you still have the issue?

https://github.com/pkp/pkp-lib/blob/master/templates/header/usernav.tpl#L41-L55

**Comment by ajnyga** [comment] 2017-08-22 16:38
I will try that, but I have to create a test server for that. I am doing that anyway.

**Comment by NateWr** [comment] 2017-08-25 13:57
Finally got my wife's iPad going and I can replicate your video. I'll see what I can figure out.

**Comment by NateWr** [comment] 2017-08-25 15:27
Arg! I'm locked out again and don't remember the access code!

I decided to look at the Bootstrap4 dropdown for clues and found [this tidbit](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L159-L166). I'm wondering if this is what's causing the taps on the submenu links to not fire. 

If you (or anyone) can get a test situation set up with an iPad, can you try adding the following code to the end of the `MenuHandler.js` constructor (right after [this line](https://github.com/pkp/pkp-lib/blob/master/js/controllers/MenuHandler.js#L64)):

```
$('body').children().on('mouseover', null, $.noop);
```

Then test with the iPad to see if the links get followed.

**Comment by ajnyga** [comment] 2017-08-25 18:43
I finally have a server online where I can test this as well if needed. You probably already tried removing the contexts dropdown as well?

This is definitely a Safari issue, or at least I do not get this with my Android phone (Chrome).

**Comment by NateWr** [comment] 2017-08-28 10:02
This has really thrown me for a loop. It seems to be related to an iOS peculiarity with event handling, but I haven't been able to narrow it down. [This code](https://github.com/pkp/pkp-lib/blob/master/js/controllers/MenuHandler.js#L58-L64), which lets the first tap on a dropdown open the submenu instead of follow the link, seems to effect the clicks on the submenu links. However, it's not actually firing that event. It seems instead to be a case of the `blur` event closing the menu before the click is registered or that the `preventDefault` flag is getting switched onto that event, or that the bubble is getting tampered with. :thinking: 

I'm leaning towards one of two fixes:

1. Just don't make any top-level links follow-able. This doesn't pose any issues for our existing links, and it would allow us to remove the tap-to-open code that's breaking iOS.

2. Make all dropdowns click-to-open. I like this philosophy, but in prior experience it tends to generate a strong backlash. Since our backend user-base is overwhelming using mouse controls, I'm tempted to leave the open-on-hover functionality.

**Comment by NateWr** [comment] 2017-08-28 14:15
Here are some PRs implementing the first option. I reckon we'll get some negative feedback for removing a couple of clickable links, but it seems like the least-worst option as long as I can't determine the underlying cause of the iOS issues.

PRs:
https://github.com/pkp/pkp-lib/pull/2745
https://github.com/pkp/ojs/pull/1510
https://github.com/pkp/omp/pull/433 (TESTS ONLY)

**Comment by NateWr** [comment] 2017-08-30 12:49
@ajnyga Also, can you test this fix for the backend menus? If it works for you on iOS/Safari, I'll probably leave it as-is and not integrate the Bootstrap dropdown on the backend. Before too long, I'll be searching for a Vue.js-based solution for our menus.

**Comment by ajnyga** [comment] 2017-08-30 13:52
Working with Android 7 + Chrome 59. I will check this with iPad later.

**Comment by ajnyga** [comment] 2017-08-30 17:12
Working with iPad 2 + Safari. Actually the backend navigation seems to be working better that front end with Safari at the moment.

**Comment by NateWr** [comment] 2017-08-31 16:51
Great! @bozana can you code review?

**Closed** 2017-09-01 11:26 UTC
Labels: Critical Issue
