### ISSUE TITLE
Add missing foreign key declarations

### ISSUE THREAD

**Issue by asmecher** [pkp/pkp-lib#8826] opened 2023-03-17 20:53 UTC
Several foreign key constraints were missed in the introduction of https://github.com/pkp/pkp-lib/issues/6093. Add them:
- [ ] filters.context_id
- [ ] plugin_settings.context_id
- [ ] navigation_menus.context_id
- [ ] navigation_menu_items.context_id
- [x] user_groups.context_id
- [x] email_log.sender_id

**Comment by bozana** [comment] 2023-08-16 10:47
I am not sure if it belongs here, but: submission_file_settings contain chapterId setting_name (in OMP). This chapter IDs could apparently be orphaned, not exist any more in the table submission_chapters. S. the case here https://github.com/pkp/pkp-lib/issues/9186.

**Comment by bozana** [comment] 2023-08-25 09:00
Here an update to the situation described above, when submission files exist with not existing chapter IDs (s. https://github.com/pkp/pkp-lib/issues/9186#issuecomment-1693012191): in this case the submission files do exist and are listed and approved under Publication > Publication Formats. Removing the entries with not existing chapter IDs from the table `submission_file_settings` would lead to publicly listing of those files on the book view page. Thus, maybe the solution here is to just check and report such cases during the upgrade preflight check, so that users can resolve them manually.

**Comment by asmecher** [comment] 2024-05-08 18:27
PRs to add fk/index to email_log.sender_id:
- https://github.com/pkp/pkp-lib/pull/9947
- https://github.com/pkp/ojs/pull/4272

**Comment by jonasraoni** [comment] 2024-05-20 11:26
I'm closing this as a duplicate of https://github.com/pkp/pkp-lib/issues/8333, which has a couple of initial PRs.

**Closed by jonasraoni** 2024-05-20 11:26 UTC
Labels: Bug:2:Moderate
