### ISSUE TITLE
OPS  Support for Citation Style Languages Plugin

### ISSUE THREAD

**Issue by withanage** [pkp/pkp-lib#6700] opened 2021-02-01 19:10 UTC
Add compatibility for [CSL Plugin](https://github.com/pkp/citationStyleLanguage/) up from  3.3

- [ ]  OPS

**Comment by isgrim** [comment] 2021-02-04 10:35
Hi Dulip @withanage ,

Alec already opened an issue for citationStyleLanguage Plugin for OMP here:
https://github.com/pkp/pkp-lib/issues/6201

A colleague of mine wants to start working on the port for OMP starting with version 3.3.0

@asmecher Where should we discuss the update?

Best regards,

NIls

**Comment by withanage** [comment] 2021-02-04 11:01
Hi @isgrim ,

Please go ahead with the OMP  in the separate issue and create  I have removed it from the ticket.

**Comment by diegoabadan** [comment] 2021-08-30 13:10
We are porting to OPS, soon we will send the PR.

**Comment by diegoabadan** [comment] 2021-09-08 13:48
Hi!

We have a preliminary version of the OPS plugin at https://github.com/lepidus/citationStyleLanguage/tree/stable-3_3_0

Adaptations are lacking so that references are generated in a format suitable for a preprint and not as a journal article.

I imagine it might also be necessary to update the styles https://github.com/pkp/citationStyleLanguage/tree/main/citation-styles

Can someone from PKP or community with greater familiarity with this subject help us with these points? CC @NateWr and @asmecher

**Comment by asmecher** [comment] 2021-09-08 20:07
@diegoabadan, were these changes made in order to convert the plugin so that the modified version *only* works with OPS? I would recommend making the changes so that the plugin works with both OJS and OPS -- see e.g. the usage stats plugin, which has a few conditional areas for each application: https://github.com/pkp/usageStats/blob/main/UsageStatsPlugin.inc.php

**Comment by asmecher** [comment] 2021-09-08 20:08
I'll ask a few of our friendly librarians what they think about citations for preprints rather than articles!

**Comment by diegoabadan** [comment] 2021-09-08 20:40
Hi Alec!

> @diegoabadan, were these changes made in order to convert the plugin so that the modified version only works with OPS?

We are modifying it to work on both OJS and OPS! :)

> I'll ask a few of our friendly librarians what they think about citations for preprints rather than articles!

Thanks!

**Comment by kshuttle** [comment] 2021-09-22 01:26
Hi Everyone,

I've done some research and come up with what I think are the correct citation formats for preprints in the various styles.

As is always the case with citations, there is some room for interpretation. I've done my best with the information available, but I'll note that some style guides don't seem to have articulated a format for preprints yet. Those that have seem to style preprints very similar to online reports, so where I was unsure I've generally gone with a report format. I used the sample article below and followed the lead of the citation styles in Zotero (which aligned with the report-like format for the preprint citations). For each citation I've included a description of the format along with an example from the sample article (with a reduced number of authors for simplicity).

I would love another set of eyes on these if someone else would like to weigh-in.

Sample article https://preprints.scielo.org/index.php/scielo/preprint/view/2968
 
**ACM**
 
Format:
First Middle Last, First Middle Last, and First Middle Last. Year. Title of the work. DOI:
 
Example:
Laís de Almeida Relvas-Brandt, Caroline Gava, and Ronaldo Fernandes Santos Alves. 2021. Síndrome inflamatória multissistêmica pediátrica: estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020. DOI: https://doi.org/10.1590/s1679-49742021000400005
 
**ACS**
 
Format:
Last, F. M.; Last, F. M.; Last, F. M. Title of the work. Preprint server name Month dd, yyyy. URL
 
Example:
Relvas-Brandt, L. de A.; Gava, C.; Alves, R. F. S. Síndrome inflamatória multissistêmica pediátrica: estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020. SciELO Preprints September 20, 2021. https://doi.org/10.1590/s1679-49742021000400005.
 
**APA**
 
Format:
Last, F. M., Last F. M., & Last, F. M. (Year). _Title of the work_. Preprint server name. URL
 
Example:
Relvas-Brandt, L. de A., Gava, C., & Alves, R. F. S. (2021). _Síndrome inflamatória multissistêmica pediátrica: Estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020_. SciELO Preprints. https://doi.org/10.1590/s1679-49742021000400005
 
**Chicago author date**
 
Format:
Last, First Middle., First Middle Last, and First Middle Last. Year. "Title of the work." Preprint server name. URL.
 
Example:
Relvas-Brandt, Laís de Almeida, Caroline Gava, and Ronaldo Fernandes Santos Alves. 2021. “Síndrome inflamatória multissistêmica pediátrica: estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020.” SciELO Preprints. https://doi.org/10.1590/s1679-49742021000400005.
 
**Harvard**
 
Format:
Last, F.M., Last F.M., and Last, F.M. (Year) _Title of the work_, Preprint server name, Available at: URL (Accessed: dd Month yyyy).
 
Example:
Relvas-Brandt, L. de A., Gava, C., and Alves, R.F.S. (2021) _Síndrome inflamatória multissistêmica pediátrica: estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020_ SciELO Preprints, Available at: 10.1590/s1679-49742021000400005 (Accessed: 20 September 2021).
 
**IEEE**
 
Format:
F.M. Last _et al._, "Title of the work." Preprint server name, m. dd, yyyy. doi: 
 
Example:
L. de A. Relvas-Brandt _et al._, “Síndrome inflamatória multissistêmica pediátrica: estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020.” SciELO Preprints, Sep. 20, 2021. doi: 10.1590/s1679-49742021000400005.
 
**MLA**
 
Format:
Last, First Middle, et al. _Title of the work_. Preprint server name, dd m. yyyy. _preprint-server-URL_, URL. 
 
Example:
Relvas-Brandt, Laís de Almeida, et al. _Síndrome inflamatória multissistêmica pediátrica: estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020_. SciELO Preprints, 20 Sept. 2021. _preprints.scielo.org_, https://doi.org/10.1590/s1679-49742021000400005.
 
**Turabian**
 
Format:
Last, First Middle, First Middle Last, and First Middle Last. "Title of the work." Preprint server name, Month dd, yyyy. Accessed Month dd, yyyy. URL.
 
Example:
Relvas-Brandt, Laís de Almeida, Caroline Gava, and Ronaldo Fernandes Santos Alves. “Síndrome inflamatória multissistêmica pediátrica: estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020.” SciELO Preprints, September 20, 2021. Accessed September 20, 2021. https://preprints.scielo.org/index.php/scielo/preprint/view/2968.
 
**Vancouver**
 
Format:
Last FM, Last FM, Last FM. Title of the work [Internet]. Preprint server name; year [cited yyyy m. dd]. Available from: URL
 
Example:
Relvas-Brandt L de A, Gava C, Alves RFS. Síndrome inflamatória multissistêmica pediátrica: estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020 [Internet]. SciELO Preprints; 2021 [cited 2021 Sep 20]. Available from: https://preprints.scielo.org/index.php/scielo/preprint/view/2968
 
**Associação Brasileira de Normas Técnicas - ABNT**
 
Format:
LAST, F. M. et al. Title of the work, Preprint server name, dd m. yyyy. Disponível em: URL. Acesso em: dd m. yyyy
 
Example:
RELVAS-BRANDT, L. DE A. et al. Síndrome inflamatória multissistêmica pediátrica: estudo seccional dos casos e fatores associados aos óbitos durante a pandemia de COVID-19 no Brasil, 2020, SciELO Preprints, 20 set. 2021. Disponível em: < https://preprints.scielo.org/index.php/scielo/preprint/view/2968>. Acesso em: 20 set. 2021

**Comment by asmecher** [comment] 2021-09-23 00:49
Thanks, @kshuttle!

**Comment by diegoabadan** [comment] 2022-02-25 21:55
Thanks, @kshuttle and Alec!

We are working on this issue for Scielo.

**Comment by JhonathanLepidus** [comment] 2022-03-03 20:06
While trying to accomplish what was put on the [comment above](https://github.com/pkp/pkp-lib/issues/6700#issuecomment-924507805), we faced a problem with the [citation-style files](https://github.com/pkp/citationStyleLanguage/tree/main/citation-styles). Some of them need to be upgraded, something that has already been issued on https://github.com/pkp/pkp-lib/issues/5629. Should we send a PR to accomplish this?

**Comment by NateWr** [comment] 2022-03-07 11:49
@JhonathanLepidus yes, thank you!

**Comment by JhonathanLepidus** [comment] 2022-03-08 18:58
@NateWr , sure. These are the PRs related to this issue:

#### To add support of the CSL plugin to OPS:
* [To the stable-3_3_0 branch](https://github.com/pkp/citationStyleLanguage/pull/89)
* [To the main branch](https://github.com/pkp/citationStyleLanguage/pull/90)

#### To fix the DOI getting in OPS 3.3.0:
* [Fixing of the getCitationData method in DOI plugin](https://github.com/pkp/ops/pull/245)

#### To upgrade the citation-style files in the CSL plugin
* [To the stable-3_3_0 branch](https://github.com/pkp/citationStyleLanguage/pull/91)
* [To the main branch](https://github.com/pkp/citationStyleLanguage/pull/92)

**Comment by NateWr** [comment] 2022-03-16 09:22
Thanks @JhonathanLepidus, this looks good! I checked it out on `main` with your changes to the CSL plugin and all the styles worked smoothly. I think we're just about ready to merge the changes to the `main` branches.

Before merge, we need to get this added as a submodule to OPS and make sure the tests are running. To do this, there are a couple steps:

1. Add the changes to the CSL files to your PR that adapts the CSL plugin, so they are all in one PR on your `lepidus/main` branch. This will ensure the tests run against all of the changes.
2. Add the `citationStyleLanguage` plugin as a submodule to OPS. You can do that by running `git submodule add https://github.com/pkp/citationStyleLanguage.git plugins/generic/citationStyleLanguage && git submodule update --init --recursive`. (You'll then need to go back and add your repository as a remove and check out your branch.)
3. Finally, create a PR to OPS that includes the submodule change. To make sure that the OPS tests run against your branch of the CSL plugin, there's a special commit syntax you need to use. Read the section in our docs on how to [prepare pull requests for testing](https://docs.pkp.sfu.ca/dev/testing/en/continuous-integration#prepare-pull-requests-for-testing). (That section uses `lib/pkp` as an example submodule, but you'll use `plugins/generic/citationStyleLanguage` as the submodule.)

Let me know if you have any questions about this part. The submodules and testing takes a little bit of work to get right the first time.

**Comment by JhonathanLepidus** [comment] 2022-03-17 19:29
@NateWr I couldn't understand this part in step 2:

> You'll then need to go back and add your repository as a remove and check out your branch

I added the submodule to my fork using the same command in step 2, but I didn't get it if I can move to step 3 or need to do something else before it.

**Comment by NateWr** [comment] 2022-03-21 11:38
Yes, that looks great, @JhonathanLepidus! The only problem that I noticed is that the name of your branch in the commit message (`##lepidus/i6700-cslOps##`) used a `-` and the branch in in your `citationStyleLanguage` repository (`i6700_cslOps`) uses a `_`. The names have to match exactly because that's how our test software knows what branch to check out.

You can fix this in OPS by renaming your last commit:

```
git commit --amend -m "Submodule update ##lepidus/i6700_cslOps##"
```

Once you've done that, open new PRs with your branches and the OPS tests should run against that.

**Comment by JhonathanLepidus** [comment] 2022-03-21 17:28
@NateWr , in fact I named the branches wrongly, but I edited the commit message to match them and opened a PR: https://github.com/pkp/ops/pull/251

**Comment by NateWr** [comment] 2022-03-23 12:09
Thanks @JhonathanLepidus. I've gone ahead and opened a PR against OJS too, so that we can run the tests there. That will help catch any unintended regressions. I think these are all of the PRs.

PRs:
https://github.com/pkp/citationStyleLanguage/pull/93
https://github.com/pkp/ops/pull/251

Tests only:
https://github.com/pkp/ojs/pull/3342

**Comment by JhonathanLepidus** [comment] 2022-03-23 17:57
Good! What about the [PR to add compatibility with OPS 3.3.0](https://github.com/pkp/citationStyleLanguage/pull/89) and [the one to upgrade style files in 3.3.0](https://github.com/pkp/citationStyleLanguage/pull/91)? Should they be closed, since it's a big change to a stable version?

**Comment by NateWr** [comment] 2022-03-24 09:03
I've merged the updates to `citationStyleLanguage` and the PR to add the submodule to OPS. Thanks @JhonathanLepidus! :tada: 

> What about the https://github.com/pkp/citationStyleLanguage/pull/89 and https://github.com/pkp/citationStyleLanguage/pull/91? Should they be closed, since it's a big change to a stable version?

At this time, we don't want to add them to the `stable-3_3_0` branch. However, Alec set out [some conditions](https://github.com/pkp/citationStyleLanguage/pull/91) that would need to be met if you did want to push for a merge to `stable-3_3_0`. 

If you're happy with the merge to `main`, I can close the other PRs. But if you did want to push for a `stable-3_3_0` change, we can keep them open. I'll leave this comment open until you've decided.

**Comment by diegoabadan** [comment] 2022-03-24 13:43
Thank you, Nate.

Scielo can wait for 3.4.

Among other customers is not a strong demand.

**Closed** 2022-03-24 14:58 UTC
Labels: Major Feature
