### ISSUE TITLE
Notifying a user from the participant grid generates fatal error

### ISSUE THREAD

**Issue by jnugent** [pkp/pkp-lib#9140] opened 2023-07-11 12:36 UTC
**Describe the bug**
In 3.4, using the "Notify" link to send an email to a user generates the following fatal error:

`
PHP Fatal error:  Uncaught TypeError: array_intersect_key(): Argument #2 must be of type array, null given in /var/www/html/lib/pkp/controllers/grid/users/stageParticipant/form/PKPStageParticipantNotifyForm.php:221
`

**To Reproduce**
1.  Create a submission
2. As an editor, attempt to use the Notify link below the author.  Choose any email template or just craft your own message.
3. The modal will not close, a fatal error is logged.

**What application are you using?**
OJS 3.4.0.1, PHP 8.1.2

**Comment by asmecher** [comment] 2023-07-11 17:50
This is a duplicate of https://github.com/pkp/pkp-lib/issues/9139 (and seems to be due to tightening of requirements with PHP 8.1.x).

**Closed by asmecher** 2023-07-11 17:50 UTC
