### ISSUE TITLE
[OPS] Unable to delete a rejected preprint unless user is assigned as "Editor" to submission

### ISSUE THREAD

**Issue by alexxxmendonca** [pkp/pkp-lib#7448] opened 2021-11-11 14:06 UTC
**Describe the bug**
It's not possible to delete a rejected preprint submission unless the user is assigned to the submission as Editor.

It doesn't matter if you have a Site Administrator role or the Editor (but not assigned to the submission). If you are not assigned as a submission Editor, you can't delete it.

**To Reproduce**
1. Make sure the preprint has been rejected so the submission is sent to the Archives.
2. Make sure the user you are logged in is not assigned as Editor to the submission (they could be the Site Administrator, for example, or simply an Editor that hasn't been _assigned_ to the submission)
3. Navigate to the Archives page and locate the preprint submission.
4. Notice how the "Delete" button doesn't appear.

**What application are you using?**
OPS 3.3.0-8

**Additional information**
Not assigned as Editor:
![image (1)](https://user-images.githubusercontent.com/4059679/141311615-3aa6871a-ef2b-4589-8ff0-b67a06e3dbb0.png)

Assigned as Editor:
![image (2)](https://user-images.githubusercontent.com/4059679/141311646-9b46a797-b13a-4483-9e01-ab781f42602c.png)

**Comment by NateWr** [comment] 2021-11-15 10:43
I was unable to reproduce this in `stable-3_3_0`. I took the following steps:

1. Login as author and create a new preprint.
2. Login as site admin and decline the preprint.
3. Go to Submissions > Archived. **Delete button is present**
4. Login as Preprint Server Manager (`ROLE_ID_MANAGER`).
5. Go to Submissions > Archived. **Delete button is present**

I checked and neither the admin nor the preprint server manager were assigned to the submission. Still, the delete button appeared in both cases.

Since the Editor role does not appear in OPS by default, perhaps there is some confusion there. Can you post a screenshot of the roles configuration for this preprint server?

**Comment by alexxxmendonca** [comment] 2021-11-16 11:32
Hi @NateWr 

It's strange that you couldn't reproduce it...

Here is the list of roles: 
![image](https://user-images.githubusercontent.com/4059679/141977627-54c1517f-6278-4015-8d9e-2f2340cea2d5.png)

We don't have an "Editor" role. I wrote "Editor" in my original post because originally the comment you made on the other issue mentioned an editor role and I sticked to it.

I am logged in as Preprint Server Manager and I do not see the delete button:

![image](https://user-images.githubusercontent.com/4059679/141977976-8383f8cb-2036-45cf-ab62-9ff804686e16.png)

**Comment by NateWr** [comment] 2021-11-16 12:09
@alexxxmendonca this is the code that determines whether the delete button is available: 

https://github.com/pkp/ui-library/blob/stable-3_3_0/src/components/ListPanel/submissions/SubmissionsListItem.vue#L276-L292

Is the user assigned as an author in the submission?  (authors can not delete submissions after they are submitted)

The first thing I'd recommend you do is try to reproduce the issue on the [OPS test drive](https://pkp.sfu.ca/ops/demo/) instance. (It says 3.2 but it's on 3.3.0-8.) If you can't reproduce it, then it's an issue on your installation. You'll want to ask your IT support whether you've deployed 3.3.0-8 from the package for via git. If from git, make sure they have recompiled the JavaScript.

I'm going to close this for now but if you're able to reproduce the problem on the test drive install we'll reopen it.

**Closed by NateWr** 2021-11-16 12:09 UTC
