### ISSUE TITLE
[OJS] Undefined calls at the ContextService

### ISSUE THREAD

**Issue by jonasraoni** [pkp/pkp-lib#8736] opened 2023-03-05 10:51 UTC
**Describe the bug**
At the `APP\services\ContextService` there are a bunch of invalid calls at the `beforeDeleteContext()` and `afterDeleteContext()`.

```php
PHP Fatal error:  Uncaught Error: Call to undefined method APP\section\Repository::deleteByContextId() in /var/www/html/classes/services/ContextService.php:165
Stack trace:
#0 [internal function]: APP\services\ContextService->afterDeleteContext('Context::delete', Array)
#1 /var/www/html/lib/pkp/classes/plugins/Hook.php(139): call_user_func_array(Array, Array)
#2 /var/www/html/lib/pkp/classes/plugins/Hook.php(112): PKP\plugins\Hook::run('Context::delete', Array)
#3 /var/www/html/lib/pkp/classes/services/PKPContextService.php(634): PKP\plugins\Hook::call('Context::delete', Array)
#4 /var/www/html/lib/pkp/controllers/grid/admin/context/ContextGridHandler.php(288): PKP\services\PKPContextService->delete(Object(APP\journal\Journal))
#5 [internal function]: PKP\controllers\grid\admin\context\ContextGridHandler->deleteContext(Array, Object(APP\core\Request))
#6 /var/www/html/lib/pkp/classes/core/PKPRouter.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#7 /var/www/html/lib/pkp/classes/core/PKPComponentRouter.php(291): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#8 /var/www/html/lib/pkp/classes/core/Dispatcher.php(163): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#9 /var/www/html/lib/pkp/classes/core/PKPApplication.php(372): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#10 /var/www/html/index.php(21): PKP\core\PKPApplication->execute()
#11 {main} thrown in /var/www/html/classes/services/ContextService.php on line 165
```

**What application are you using?**
OJS 3.4

**Comment by asmecher** [comment] 2023-03-06 16:28
Presumably this is triggered by removing a journal/press/server, right?

**Comment by asmecher** [comment] 2023-03-06 16:53
Actually, marking this as a duplicate of https://github.com/pkp/pkp-lib/issues/8744 -- there are reproduction steps there.

**Closed by asmecher** 2023-03-06 16:53 UTC
