### ISSUE TITLE
[OJS] OJS 3.1.0.1 adding a participant with Safari does not close the modal window

### ISSUE THREAD

**Issue by ajnyga** [pkp/pkp-lib#3422] opened 2018-02-24 09:29 UTC
Hi,

Tagging @NateWr.

One of our editors reported that when assigning users to a submission, the modal window does not close after clicking "OK". The user is assigned though and you can just close the window from the "X" button, but in other browsers the window is closed automatically.

I was able to reproduce this with a clean installation of 3.1.0.1 and Safari 11 on Mac OS X 10.

**Comment by NateWr** [comment] 2018-03-06 17:04
Confirmed with my iPad. In my case, the user is not actually assigned.

I don't have access to the console there. Do you see any messages in the browser's console?

**Comment by ajnyga** [comment] 2018-03-07 17:04
`Error: Syntax error, unrecognized expression: #submissionEditorDecisionsDiv,#copyeditingEditorDecisionsDiv,[id^=reviewDecisionsDiv` jquery.min.js:554

**Comment by NateWr** [comment] 2018-03-07 17:07
Bingo! Missing the closing `]` in the attribute value selector.

https://github.com/pkp/pkp-lib/blob/master/js/controllers/grid/users/stageParticipant/StageParticipantGridHandler.js#L38-L40

**Comment by t4x0n** [comment] 2018-03-08 14:07
hi @NateWr,  if I add this closing ` ] ` should work good?   or is better wait to release 3.1.1?

**Comment by NateWr** [comment] 2018-03-08 15:33
@t4x0n I think so. If you're able to test the fix for me that'd be great!

**Comment by t4x0n** [comment] 2018-03-08 18:19
@NateWr is not working for me on iOS neither MacOS...  I think is another problem but I can't confirm it ... in Chrome console you can see the error too!

**Comment by t4x0n** [comment] 2018-03-08 18:24
maybe the problem is jQuery 1.11.0... I want to try change to 1.11.3 but I am not sure about how :/

**Comment by ajnyga** [comment] 2018-03-08 19:06
After adding the closing `]` I am not seeing the problem anymore. No errors with Safari 11.0.3. This is in the current master branch.

**Comment by t4x0n** [comment] 2018-03-08 19:53
I am trying in Safari 11.0.3 too but not with the master branch, with OJS 3.0.1-1

maybe a have troubles with my files in cache because I can't make changes... sorry I am not helping

**Comment by ajnyga** [comment] 2018-03-09 07:42
the js cache seems to be especially hard to empty sometimes, but disabling the minified setting usually helps.

**Comment by t4x0n** [comment] 2018-03-09 17:26
Yes! thanks @ajnyga it is working now! I am not seeing the problem anymore!

**Comment by NateWr** [comment] 2018-03-13 16:01
Thanks to both of you. I've confirmed the fix as well.

PR:
https://github.com/pkp/pkp-lib/pull/3473

Tests:
https://github.com/pkp/ojs/pull/1875

**Comment by NateWr** [comment] 2018-03-19 11:56
Merged.

**Closed by NateWr** 2018-03-19 11:56 UTC
Labels: Critical Issue
