### ISSUE TITLE
[OJS 3.x] is not possible delete Keywords in second language with X

### ISSUE THREAD

**Issue by t4x0n** [pkp/pkp-lib#3003] opened 2017-11-01 21:40 UTC
When I need to delete a Keyword in the main language is difficult by clicking the X when I have more languages. Also is impossible delete a Keyword by click in the second language. 
I used Firefox, Chrome and Safari (all updated and all in Mac). 

Please see the video: https://youtu.be/lbBxdQhDf9E

**Comment by asmecher** [comment] 2017-11-02 02:03
@NateWr, mind taking a look?

**Comment by bozana** [comment] 2017-11-02 08:57
@t4x0n, what OJS version are you using? -- I cannot reproduce it with OJS 3.1 and firefox locally...

**Comment by NateWr** [comment] 2017-11-02 11:42
I can reproduce it. Yeah that's annoying. We'll need a short-term workaround specifically for multilingual tag-it fields -- probably a toggle as @t4x0n suggested in #911.

**Comment by t4x0n** [comment] 2017-11-02 17:42
@bozana this issue appear since OJS 3.0 to 3.1 and maybe is because popover

**Comment by NateWr** [comment] 2018-01-15 15:49
I made the multilingual popovers always visible on tag-it fields. Not the prettiest solution but I think it's the least worst in the near-term.

![multi-lingual-tag-it](https://user-images.githubusercontent.com/2306629/34950597-7d867146-fa0b-11e7-957d-f26c5f68abd5.png)

PR:
https://github.com/pkp/pkp-lib/pull/3275

Tests only:
https://github.com/pkp/ojs/pull/1793

**Comment by NateWr** [comment] 2018-01-15 17:02
Tests passed. @asmecher can you take a quick look and merge if you're ok with this?

**Comment by asmecher** [comment] 2018-01-16 19:25
Merged, thanks!

**Closed by asmecher** 2018-01-16 19:25 UTC

**Comment by t4x0n** [comment] 2018-04-06 07:57
Hi @NateWr, 
thanks for try to improve this issue, looks better and sometimes work, because when you click out the textfield the popover contract and the issue appear, but like I say now work sometimes, and I need to try in other browsers yet ;)
