### ISSUE TITLE
Allow editors other than the assigned editor to confirm a review and thank the reviewer

### ISSUE THREAD

**Issue by amandastevens** [pkp/pkp-lib#7486] opened 2021-11-26 16:47 UTC
After a review has been submitted in OJS 3.X, a link appears to "Read Review."  After the assigned editor reads the review they can click "Confirm" and then the "Read Review" link is replaced with a link to "Thank Reviewer."  However, if another editor or journal manager who is not the assigned editor reads the review and clicks "Confirm," OJS does not consider the review as having been read and the link to "Read Review" continues to show. "Thank Reviewer" does not become available.

I imagine this is done so that an assigned editor can keep track what work needs to be done on a submission, but it often causes confusion in users who don't understand why their actions as editors and journal managers do not count.  There are a number of posts on the Forum about this (see below). They could be bugs in the individual installations, but the fact that none have been resolved suggests they simply don't understand this feature or it isn't working in an intuitive way.

The number of posts about this suggest that often other editors and journal managers read reviews and want to confirm them and thank reviewers, so it would be great if this was possible, or at least that the need for an assigned editor to do it was made clear in the interface. A PKP Publishing Services hosted client requested this as well.

https://forum.pkp.sfu.ca/t/thank-reviewer-link-doesnt-appear-in-ojs-3-1-0-1/38709
https://forum.pkp.sfu.ca/t/email-reviewer-error-review-ack/66812
https://forum.pkp.sfu.ca/t/option-thank-reviewer-ojs-3-0-2/40909
https://forum.pkp.sfu.ca/t/unable-to-confirm-a-review/51656
https://forum.pkp.sfu.ca/t/as-an-editor-journal-manager-i-cannot-confirm-the-reviewers-review/35374

**Comment by alexxxmendonca** [comment] 2021-11-26 17:00
This makes a lot of sense. Sometimes an executive editor or someone from the editorial team with an editor role would like to thank the reviewer and move things forward but is unabled to because only the assigned editor has this capability.

+1 for SciELO.

**Comment by NateWr** [comment] 2021-11-29 10:48
:exploding_head: Now I finally understand why I've never been able to get the "Thank Reviewer" option to show up!

I had a look at the code and it looks to me like the original intention was related to recommending editors. So the idea is that a review can't be confirmed by a recommending editor. But a side effect (ie - bug) is that it also means that a journal manager can not confirm a review either.

For that reason, I've flagged this as a bug, not an enhancement, and scheduled it for 3.3.0-9.

**Comment by NateWr** [comment] 2021-11-29 10:55
Ah, I was looking at the wrong code. It looks like the code checks for a record that someone assigned to the submission has read it. So in this case, the system correctly records the view by the unassigned editor. But the code doesn't pick up on this when it checks if the review has been read.

I don't think this is intentional, so I'll still classify it as a bug. But it's a little bit more complicated to solve. The logic at `ReviewAssignment::isRead()` would need to change, and we would need to make sure this didn't have unanticipated effects.

https://github.com/pkp/pkp-lib/blob/main/classes/submission/reviewAssignment/ReviewAssignment.inc.php#L649

**Comment by NateWr** [comment] 2021-11-29 11:07
@asmecher I've tracked this down to an issue with how the `ViewsDAO` works. When someone views a review response, a view is recorded for that user. We then check for views by assigned users to determine if the `ReviewAssignment` has been read. This misses out reads by users who are not assigned (ie - Journal Managers).

We can create a `ViewsDAO::getLastEditorViewDate()` method to address this. However, it occurred to me that this is going to cause problems with editorial turnover. If a Journal Manager confirmed reviews from 2018-2020, but then was removed from this role in the journal, all of the reviews they confirmed would switch from read to unread.

I think we need to save the "read" status to the review assignment itself, rather than rely on whether an entry exists from an appropriate user in the views table. Does that sound right or am I missing something about how the views system is meant to work?

**Comment by asmecher** [comment] 2021-12-01 20:25
Have a look at the `unconsidered` column in the `review_assignments` table (if you're ready to scratch your head about some egregious double-negatives). I'm in favour of getting rid of the `ViewsDAO` stuff entirely; it was an old attempt to build a generally-useful feature but has never been well realized.

**Comment by touhidurabir** [comment] 2022-11-21 11:42
> We can create a ViewsDAO::getLastEditorViewDate() method to address this. However, it occurred to me that this is going to cause problems with editorial turnover. If a Journal Manager confirmed reviews from 2018-2020, but then was removed from this role in the journal, all of the reviews they confirmed would switch from read to unread.

@NateWr , I think similar case still possible to produce. To produce it , first confirmed a review as the editor assigned to that stage and submission but do not thank the reviewer . Then remove that editor and assign another new editor and see that review now showing `Read Review` .  

> we need to save the "read" status to the review assignment itself, rather than rely on whether an entry exists from an appropriate user in the views table.

I think what you suggest is the best approach but we can not do a DB modification for a stable release, right ? 

I think the core of the problem lies with how the implementation done for `ReviewAssignment::isRead` method at https://github.com/pkp/pkp-lib/blob/stable-3_3_0/classes/submission/reviewAssignment/ReviewAssignment.inc.php#L540-L568 . It's looking for `user group` assignment for both `context` and `stage` . if we remove the `stage` requirement which seems to be the case for this issue, we can make it work without any DB modification . So in that case , even a different editor who is not assigned to a submission will be able to confirm and thank a reviewer and changing the Editor/JM will not change the `Read Review` status . 

@asmecher PRs to review for `Stable-3.3.0` branch
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8441
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3627 [TEST ONLY]

my suggestion is to have a different implementation for the `main` branch where we can update the `review_assignments` table to store proper data . If we dont want to maintain 2 different implementation, then probably it's best to schedule this one for next release only.

**Comment by NateWr** [comment] 2022-11-21 12:09
I think the best thing to do is to only modify this for 3.4, since it is a change in behaviour for the stable version that doesn't technically fix a "bug". But I'll defer to what @asmecher thinks is best here.

**Comment by asmecher** [comment] 2022-11-22 22:29
@NateWr, I agree with your assessment -- sorry, @touhidurabir, but can you forward-port this to `main`?

**Comment by touhidurabir** [comment] 2022-12-04 08:21
@asmecher PRs to review for `main` branch

[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8465
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3643

**Comment by asmecher** [comment] 2022-12-06 23:06
@touhidurabir, I think the new columns partially overlap with the `unconsidered` column discussed in [this comment](https://github.com/pkp/pkp-lib/issues/7486#issuecomment-984026966). It would be wonderful if the new mechanism for recording this could be implemented in a way that'll make bad/inconsistent data unrepresentable.

**Comment by NateWr** [comment] 2023-01-17 09:56
@asmecher it looks like this was close to ready. Do you want to complete the final review or would you like me to take a look?

**Comment by asmecher** [comment] 2023-01-17 15:56
This is on my list to review, but if you've got time to look, that would be welcome! Touhidur and I had been working on how to store the information, and I think it's still a little redundant, but I haven't looked it over recently.

**Comment by asmecher** [comment] 2023-01-20 19:35
@touhidurabir, reviewing this again, I think we can find a simpler approach. I think in fact we already track whether or not the review has been marked considered by an editor -- the `review_assignments.unconsidered` column [has 3 states](https://github.com/pkp/pkp-lib/blob/36a961e7fc10378981ad6cf176376e928eee4e11/classes/submission/reviewAssignment/ReviewAssignment.php#L45..L49):
```php
    // A review is "unconsidered" when it is confirmed by an editor and then that
    // confirmation is later revoked.
    public const REVIEW_ASSIGNMENT_NOT_UNCONSIDERED = 0; // Has never been unconsidered
    public const REVIEW_ASSIGNMENT_UNCONSIDERED = 1; // Has been unconsindered and is awaiting re-confirmation by an editor
    public const REVIEW_ASSIGNMENT_UNCONSIDERED_READ = 2; // Has been reconfirmed by an editor
```
So for 3.3.0-x, the data is actually stored in several places, redundantly:
1. In the `item_views` table, flagging which editor considered the review and when;
2. In the event log (`event_log` et al), providing a user-facing audit history, and
3. In the `review_assignments.unconsidered` column providing a simple status flag.

I don't see any programmatic need to track details like who marked the review and when; we can simply get rid of the use of `item_views` for this purpose and rely on `unconsidered` in `PKPReviewerGridHandler`, `ReviewAssignment`, and `ReviewNotesLinkAction`. And if someone needs the full details, the event log has the audit trail.

For bonus points, since this is the last use of `ViewsDAO`, it can be removed along with supporting code!

**Comment by asmecher** [comment] 2023-01-20 19:48
There will need to be one change to the `unconsidered` column, though -- currently it does not include a "review has been considered for the first time". This state would need to be added, and `review_assignments.unconfirmed` would need to be updated for submissions in this situation during migration.

I think it would be a *lot* clearer if the column could be renamed to `considered`, and the states renamed to...
```
    public const REVIEW_ASSIGNMENT_NEW = 0; // Has never been considered by an editor
    public const REVIEW_ASSIGNMENT_CONSIDERED = 3; // Has been marked considered by an editor
    public const REVIEW_ASSIGNMENT_UNCONSIDERED = 1; // Considered status has been revoked by an editor
    public const REVIEW_ASSIGNMENT_RECONSIDERED = 2; // Considered status has been granted again by an editor
```

If you're curious why distinguish between never-considered reviews and considered-then-revoked, it's used here: 

https://github.com/pkp/pkp-lib/blob/main/classes/submission/reviewAssignment/ReviewAssignment.php#L669..L679

This code determines the submission's status.

**Comment by touhidurabir** [comment] 2023-01-23 09:31
> I don't see any programmatic need to track details like who marked the review and when

@asmecher you are right, as we are not putting these details with each review assignment in a review round, but that was the purpose of it. Right now only the assigned stage Editor can mark a review assigned as accepted/rejected which is the main point of this issue . Even if another Editor/JM try to make that decision, it does not get registered which is ambiguous. But with our new implementation, any `Editor/JM` associated with `Context` can mark a review accepted/rejected. I think that will also make the assigned stage editor confused as after a certain period, editor log in back and see a review assignment marked as accepted/rejected and no way to know who did this . I am thinking that we can present this information with each review assignment such as `Confirmed/Rejected By EDITOR_NAME at ACTION_DATE` . But if we do not include it , no need for it .

**Comment by touhidurabir** [comment] 2023-01-31 13:48
> since this is the last use of `ViewsDAO`, it can be removed along with supporting code!

@asmecher I can see that the `ViewsDAO` is used in `PKP\controllers\review\linkAction\ReviewNotesLinkAction` class . so can we still remove it ? Though I could not populate any data in the `item_views` table other than only when confirming a submitted review by stage editor but need to be sure . Also what is that class used for ?

**Comment by touhidurabir** [comment] 2023-02-01 07:21
@asmecher updated PRs
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3689
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8593

**Comment by asmecher** [comment] 2023-02-02 20:24
> I can see that the ViewsDAO is used in `PKP\controllers\review\linkAction\ReviewNotesLinkAction`...

That's here:

https://github.com/pkp/pkp-lib/blob/6a36732b9c59ced3e417b3ddc687290a9e85ca3c/controllers/review/linkAction/ReviewNotesLinkAction.php#L58..L61

This just checks to see whether the review is unread, and if it is, presents it along with a `read_new_review` icon.

So according to the slightly adjusted constants in your PR, I think we can use something like...
```php
$icon = match($reviewAssignment->getConsidered()) {
  ReviewAssignment::REVIEW_ASSIGNMENT_NEW => 'read_new_review',
  default => null;
}
```

**Comment by touhidurabir** [comment] 2023-02-04 14:53
@asmecher updated PRs
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3689
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8593

Also `ViewDAO` related all reference(code, table, migration etc) has been removed . If all ok , I will to port it to `OMP` .

**Comment by asmecher** [comment] 2023-02-04 15:22
Thanks, @touhidurabir! Please go ahead.

**Comment by touhidurabir** [comment] 2023-02-06 10:50
@asmecher updated PRs
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3689
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8593
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1321
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/457

**Comment by asmecher** [comment] 2023-02-09 01:40
Good spotting re: the review report plugin! Currently that report uses the confusing "unconsidered" terminology and just sends out "yes" if the review has been unconsidered. It would be better to call the column "Considered" and give it a value corresponding to each of the constants.

**Comment by touhidurabir** [comment] 2023-02-09 14:02
@asmecher 
#### Apps PR
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3689
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8593
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1321
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/457

#### PR for Review Report Plugin
[reviewReport](https://github.com/pkp/reviewReport) -> https://github.com/pkp/reviewReport/pull/45

**Comment by touhidurabir** [comment] 2023-02-09 19:29
@asmecher All rebased . If tests pass, all good to merge . 

#### Apps PR
[ojs](https://github.com/pkp/ojs) --> https://github.com/pkp/ojs/pull/3689
[pkp-lib](https://github.com/pkp/pkp-lib) --> https://github.com/pkp/pkp-lib/pull/8593
[omp](https://github.com/pkp/omp) --> https://github.com/pkp/omp/pull/1321
[ops](https://github.com/pkp/ops) --> https://github.com/pkp/ops/pull/457

#### PR for Review Report Plugin
[reviewReport](https://github.com/pkp/reviewReport) -> https://github.com/pkp/reviewReport/pull/45

**Comment by asmecher** [comment] 2023-02-14 02:05
All merged/cherry-picked, thanks!!

**Closed by asmecher** 2023-02-14 02:05 UTC
Labels: Hosting, Bug:1:Low
